### ISSUE TITLE
conda-build chokes on pyc compilation error

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#1001]
In Numba, we have a Python 3-specific test file. `conda-build` tries to compile that file and the resulting `SyntaxError` fails the build (see `compile_missing_pyc()` in `conda_build/post.py`).

By contrast, disutils ignores compilation errors, which is the right thing to do when some files (such as our Python 3-specific test file) are only conditionally imported.

**Comment by pitrou** [comment]
Interesting, compiling pyc files is already conditional on the Python version:
```
    if config.CONDA_PY < 30:
        compile_missing_pyc()
```

Apparently, someone realized that some Python 2 syntax isn't valid on Python 3, but they didn't envision that the converse may be true as well... Unfortunately, digging in the repository's history doesn't give more insight (most code was imported in fe7f773010f4c8c200298c83a4164ca404626d52).

**Comment by pitrou** [comment]
Also, since there are no comments or docstrings, it's not obvious in which circumstances `compile_missing_pyc` is useful at all.

**Comment by msarahan** [comment]
Yeah, people have had this error before, especially with Django where some .py files are actually templates that can't be compiled as-is.  https://github.com/conda/conda-build/pull/715

The arguments for compile_missing_pyc are that end-users may not have write permissions at execution time.  We discussed, but did not decide to pursue, compilation at install time (basically shifting this over to conda).

I would advise you to set the PYTHONDONTWRITEBYTECODE environment variable for now.  I will look into ignoring compilation errors.

**Comment by pitrou** [comment]
Hmm... PYTHONDONTWRITEBYTECODE is a massive hammer for this problem. Fortunately, conda installs are usually in writable locations, so compiling lazily may work for conda users (is that always the case, though?).

**Comment by msarahan** [comment]
yeah, that's the kicker, @kalefranz is sure that there are situations where conda installs are not in writable locations.

**Comment by jakirkham** [comment]
Sounds like a dup of this issue ( https://github.com/conda/conda-build/issues/686 ).

**Comment by pitrou** [comment]
A side effect of the workaround we're using is that our Python 2 packages have a "dirty" tag in the versioneer-generated version string: https://github.com/numba/numba/issues/1984

**Comment by jreback** [comment]
we just hit this (only on python 3.4 on windows): https://ci.appveyor.com/project/jreback/pandas-465/build/1.0.847/job/fb6cmln4nrxw52ef

will try setting the env variable.

**Comment by msarahan** [comment]
Try again now that 1.21.11 is out.  A fix for this was in https://github.com/conda/conda-build/pull/1155 I think, which should be present in 1.21.10 and above.

**Comment by msarahan** [comment]
Closing this for now, as I believe that #1146 and #1155 have fixed this issue.  Please reopen or reraise if you still have problems.
