### ISSUE TITLE
During test phase cwd gets deleted

### ISSUE THREAD

**Issue by marscher** [conda/conda-build#1007]
For instance if one does a stack inspection during testing, the absolute path to the source files will be looked up. This will fail, because the _test directory is deleted during testing somehow and this is the current working directory.

Please note that this for now only popped up in conjunction with pytest. Fixing pytest-dev/pytest#1235 will only partially solve this problem, since every call to os.getcwd() will raise, no matter where it occurs.

This is a blocker for using pytest in testing phase - IMHO.

Thank you very much for taking a look.

**Comment by msarahan** [comment]
Just a note to say I'm aware of this, and hope to work on it soon.

If you could post your use case, or a build log showing what you do, that would be helpful.

**Comment by msarahan** [comment]
Never mind, just hit this myself while working on a conda-build recipe for conda-build.  I'll try to figure out where these temporary directories are misbehaving.  Thanks for the background info at pytest.

**Comment by msarahan** [comment]
@marscher Can you explain why you think _test is cwd?  I see that _test is deleted at https://github.com/conda/conda-build/blob/master/conda_build/build.py#L665-L672

and then recreated at https://github.com/conda/conda-build/blob/master/conda_build/build.py#L693

but I don't see why you would be in the _test prefix, unless you are intentionally cd'ing there.  Do you mean the test-tmp folder?  In playing with conda-build, that seems to get me into hot water:

https://github.com/conda/conda-build/blob/master/conda_build/build.py#L644-L645

With conda-build making a conda-build package, I'm in that folder when it is removed, and I'm pretty sure this triggers the pytest issue you linked to.  Is there another way that conda-build trips over itself, or do you also have a way of being in test-tmp when conda-build tries to clean it up?

**Comment by marscher** [comment]
Actually I'm not changing directory neither to _test nor test-tmp. So 
I'd guess that cwd is being set to one of these directories during 
test-phase.

When I print cwd within my run_test.py script, it points to
~/miniconda3/conda-bld/test-tmp_dir

So the culprit has to be the removal/recreation of this dir.

**Comment by marscher** [comment]
Maybe it is sufficient to change directory to the newly created dir, since the inode changes during re-creation.

**Comment by marscher** [comment]
Still present in 2.0.1.

**Comment by msarahan** [comment]
Thanks for the update. I will try to reproduce and fix for the next
release.

**Comment by marscher** [comment]
Am 09.09.2016 um 14:13 schrieb Mike Sarahan:
> Thanks for the update. I will try to reproduce and fix for the next
> release.

Thank you so much!

**Comment by msarahan** [comment]
I have attempted to recreate the failure using the test from https://github.com/pytest-dev/pytest/issues/1235 .  This works fine on my computer.  If it passes CI, then I think I need more information from you.  Namely, how exactly you are running your tests - any source you can point me to would be helpful.

https://github.com/conda/conda-build/pull/1347
