### ISSUE TITLE
Dependency build can end up in infinite loop

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1038]
Example from Bokeh channel: building ggplot for python 3.5 results in infinite loop, because ggplot depends on brewer2mpl, but that seems to depend on ggplot.

Need to compute DAG, rather than simply looping.

CC @bryevdv

**Comment by ocefpaf** [comment]
> because ggplot depends on brewer2mpl, but that seems to depend on ggplot.

I cannot see the `brewer2mpl` dependency on `gpplot` in the PyPI tarball.

**Comment by pelson** [comment]
FWIW conda-build-all has a loose dependency sorter (and fails on circular deps). https://github.com/SciTools/conda-build-all/blob/master/conda_build_all/order_deps.py
Code is BSD 3 and I'd happily see it move into conda-build.
