### ISSUE TITLE
all builds fail on Fedora due to environment corruption

### ISSUE THREAD

**Issue by havocp** [conda/conda-build#1040]
On Fedora 22, conda build fails when trying to run build.sh, like this:

```
/bin/bash: scl: line 1: syntax error: unexpected end of file
Command failed: /bin/bash -x -e /home/hp/checkout/conda-project/conda.recipe/build.sh
```

The issue appears to be that the environment variable called `BASH_FUNC_scl()` (the parens are in the env var name!) gets its value corrupted. `BASH_FUNC_module()` also exists and has the same issue.

Here is the output of printenv:
```
BASH_FUNC_scl()=() {  local CMD=$1;
 if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
```

If I add debug prints to conda_build/build.py, the value of `BASH_FUNC_scl()` is `() {  local CMD`

The code in environ.py doesn't look prepared for newline or "=" to be in the value of an env var, but in this case both of them are.

On Linux a possible fix would be to use `env --null` then `split('\x00')` instead of newline, and then only special-case the _first_ '=' (treat any subsequent '=' as part of the value), maybe using `var.split('=', 1)`.  However, I wouldn't be surprised if BSD lacks `--null`. Then again, BSD probably doesn't set env vars to stuff containing '=' and newline.

**Comment by msarahan** [comment]
Thanks for the great bug report and suggestions.  That's a tough problem.  OS X does not seem to have --null.

Perhaps I should just ignore any variables that have unmatched brackets before a newline?  I really don't want to write a super-duper parser here.

**Comment by havocp** [comment]
nutty possibility, maybe replace "env" with something like `python -c 'import json; print(json.dumps(environ))'` ? didn't test that but you get the idea ...

**Comment by msarahan** [comment]
That is pretty clever.  I think I'm going a different path, though.  I think if I just call the activate scripts from the build scripts, then none of this will be an issue.  It's only in trying to have python in the layer in between where problems arise.

Thanks for thinking about it.  I'll ping you on the pending PR when I get tests running cleanly.

**Comment by AlbertDeFusco** [comment]
I have the same problem on OSX (bash 4.3.42 from MacPorts). Notice the newline, `()` and `%%` in my printenv output.

```bash
BASH_FUNC_module%%=() {  eval `/usr/local/Modules/$MODULE_VERSION/bin/modulecmd bash $*`
}
```

I also use environment modules and I had to launch a new shell with it disabled to get `conda build` to work.
