### ISSUE TITLE
conda-build environment setup introduces either system or root Python at beginning of PATH

### ISSUE THREAD

**Issue by insertinterestingnamehere** [conda/conda-build#1047]
This popped up recently on the dynd-python CI builds. Before the build environment is set up the miniconda Python that is installed in C:\Py takes precedence over the system installation provided by AppVeyor. For some reason, even after the PATH is set inside the build environment either the system python or the root Python installation (and its corresponding Library/bin directory) still take precedence over the Python installation in the build environment.
dynd-python builds two separate conda packages. When building the first one, conda-build somehow picks up the system python and uses that instead of the build environment python. See https://ci.appveyor.com/project/libdynd/dynd-python/build/1.0.1430/job/jy0xyb9nysdnsa2g#L214. When building the dynd.nd package, something similar happens, but the second time around the root python installation takes precedence instead of the system python. This happens at https://ci.appveyor.com/project/libdynd/dynd-python/build/1.0.1430/job/jy0xyb9nysdnsa2g#L903. Any idea what's going on here?

For the time being, I was able to work around this by using the `PYTHON` environment variable in the build environment, but this behavior is still very surprising.

**Comment by msarahan** [comment]
Yikes,
https://ci.appveyor.com/project/libdynd/dynd-python/build/1.0.1430/job/jy0xyb9nysdnsa2g#L214
seems
to show a really jumbled up PATH.

For one thing, remember that the system PATH and the user PATH are
independent, and concatenated, with user coming after.  That does not
explain this, though.  I'll try to reproduce here.

**Comment by insertinterestingnamehere** [comment]
Just a shot in the dark here, but is there something special we need to be doing now to activate the root environment to begin with? Currently we're just modifying the `PATH` after install at https://github.com/libdynd/dynd-python/blob/8fc5d3bb21ae83fd2742b6623085cc0b043e75c4/appveyor.yml#L22.

**Comment by msarahan** [comment]
no, theoretically you could to something like:

C:\Py\Scripts\activate.bat [root]

to activate things rather than modifying PATH.  root is optional - no args is implicitly root.  If you did so, then your root environment would be taken off of path when the build environment was activated.  As you have done it, your root env should always stay in PATH, but the _build and _test environments should precede it during build and test.

**Comment by msarahan** [comment]
I think this was a bug in how I was trying to merge two distinct sets of environment variables.  I have abandoned that effort for now, and gone back to just straightforwardly doing things in the shell script, and having the state in that script be the merge.  It's a lot more code, but it's more reliable, for now.  New tag coming very soon.

**Comment by msarahan** [comment]
Please let me know if this issue is still present with conda-build 1.21.2.  Closing issue for now.

**Comment by insertinterestingnamehere** [comment]
https://ci.appveyor.com/project/libdynd/dynd-python/build/1.0.1438/job/u5arqui5mat0y52r#L231 looks right to me now. Thanks for looking in to this!
