### ISSUE TITLE
conda build test phase does not test package which was built

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#1051]
The test phase of conda build will pick up packages with the same build string in the main conda `pkgs` directory which can result in a test which should fail to pass.  An easy method to observer this is to create a recipe which passed, build it, then modify it so that it should fail in the test phase.  If the build number has not changed the working package  will be installed during the test phase rather than the newly built package.

A tell-tale sign of this behavior is that the package is not listed as being downloaded during the test phase.

I am seeing this behavior on a OS X system with the follow conda info:

```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.3
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : /Users/jhelmus/anaconda  (writable)
  default environment : /Users/jhelmus/anaconda
     envs directories : /Users/jhelmus/anaconda/envs
        package cache : /Users/jhelmus/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/jhelmus/.condarc
         offline mode : False
    is foreign system : False
```

**Comment by Korijn** [comment]
`1.21.0` was the last version that did not have this bug. We've pinned the versions of conda, conda-build and conda-env across our whole system, many regressions are being introduced lately and it's... distracting, to say the least. :)

**Comment by msarahan** [comment]
Thanks for the report.  This is a good excuse to finally have the test phase actually test the built module, rather than some strange series of "read metadata from built package, but then try to download package using that metadata."

@Korijn, my sincerest apologies for all the bugs I've introduced.  As part of #953, I have discovered that we only have about 45% test coverage (prior to that PR, most of our tests did not give us coverage information, because they run in subprocesses).  With that, breakage is somewhat inevitable. =(

I hope we'll have enough stability and new features to win you back soon.  Any tests you propose, whether as problem descriptions in issues like this one, as pseudocode, or as PR's, will be most helpful in assuring conda-build's stability going forward.

**Comment by Korijn** [comment]
@msarahan Well, I'm married to conda already, so no need to win me over! I'm eagerly awaiting new versions to see if I can remove the version pins yet... :)

**Comment by jjhelmus** [comment]
Minimal example which exhibits the broken behavior:

**meta.yaml**
``` yaml
package:
  name: foobar
  version: 1.0.0

build:
  number: 0
  script: echo "exit 0" > $PREFIX/bin/foobar; chmod +x $PREFIX/bin/foobar

test:
  commands:
    - foobar
```

* Run `conda build .` in a directory with this file, test phase should pass.
* Change "exit 0" to "exit 1", rerun `conda build .`, test phase should fail but will pass
* Change the build number to 1, rerun `conda build .`, test phase will now correctly fail.

Removing the foobar package from the package cache will also result in the correct behavior.

Some additional investigation leads me to believe that this is actually a bug in `conda` not `conda-build`.  Downgrading conda to version `4.0.9` removes this buggy behavior, upgrading to `4.1.0` and above causes the erroneous behavior.  Feel free to move this issue to the correct repository, ping me if you would like me to open an issue there.

**Comment by msarahan** [comment]
Thanks @jjhelmus.  Considering that varying conda version changes behavior, I'm inclined to move this issue over there.  I will still be working to improve the way that packages are tested (more directly), but I think that's orthogonal to this issue.  @kalefranz @mcg1969, incoming!

**Comment by msarahan** [comment]
Issue moved to [conda/conda #2885](https://github.com/conda/conda/issues/2885) via [**ZenHub**](https://www.zenhub.com/)
