### ISSUE TITLE
conda develop: "Error: python is not installed in <path_to_envs>/<env>"

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1055]
_From @sscherfke on June 27, 2016 9:16_

I have a python2 env created by miniconda3.  When I run `conda develop trunk/src` inside the python2 env, I get the message "Error: python is not installed in `/home/user/mniconda3/envs/myenv` and no `conda.pth` file is created.

Output of `conda info`:

```
Current conda install:

             platform : linux-64
        conda version : 4.1.3
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/user/miniconda3  (writable)
  default environment : /home/user/miniconda3/envs/myenv
     envs directories : /home/user/miniconda3/envs
        package cache : /home/user/miniconda3/pkgs
         channel URLs : http://***/conda/development/linux-64/
                        http://***/conda/development/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/user/.condarc
         offline mode : False
    is foreign system : False
```

_Copied from original issue: conda/conda#2877_

**Comment by msarahan** [comment]
Sorry @sscherfke, I can't reproduce this.  Here's what I've tried:

```
conda create -n devtest python=2.7
source activate devtest
conda develop <path to conda-build source root>
```

I get

```
added /Users/msarahan/code/conda-build
completed operation for: /Users/msarahan/code/conda-build
```

Is there some source code you can point me to to help reproduce the issue?

**Comment by sscherfke** [comment]
Must the path I pass to `conda develop` contain a certain file or something? The docs are unfortunately a bit vague.

**Comment by msarahan** [comment]
It needs to have a setup.py file, similar to most standard Python projects.
I think conda develop was created a an alternative to the

python setup.py develop

command. I'm not sure that conda develop sees much use, though, so it may
well have bugs.

**Comment by sscherfke** [comment]
Why do I have to have setup.py when for conda-only-packages when even the conda docs disourage building conda packages from a setup.py? I thought, a conda receipt would be enough?

Also, the error message is not very helpful and misleading.

**Comment by msarahan** [comment]
Where do the docs discourage building conda packages from a setup.py?  I'm guessing the docs discourage installation of packages from PyPI using pip.  That's very different.

Strictly speaking, a setup.py file is not necessary to create a conda package.  You can create a conda package with conda build that bundles arbitrary content.  That's different from the development mode, where conda is setting up a link to your code.  Setup.py files are the standard for Python projects as descriptors of the project structure, and what to install.  Conda recipes do not have the notion of project links - we rely on the existing notions.  This is not to say that we can't support that someday.  I think it's a good idea to not need setup.py, because conda recipes are more straightforward than setup.py.

Sorry for the confusion.  I'll try to clean up the error message.

**Comment by sscherfke** [comment]
http://conda.pydata.org/docs/bdist_conda.html, first paragraph ;-)

I am new to the conda eco system. I thought I don't need setup.py because it would be redundant with the conda receipt …

**Comment by dgrigonis-gmt** [comment]
I am having the same issue. `conda develop` just stopped working. Both on my mac and windows pc. Has anubody found a problem/solution?

**Comment by msarahan** [comment]
I don't have an immediate solution, but I will fix this before the next release.

**Comment by karelva** [comment]
Hi, I had the same issue, for me it worked to downgrade to conda 4.0 (conda install conda=4.0), then remove conda-build and reinstall with the (--no-update-dependencies)

**Comment by jorisvandenbossche** [comment]
I also get an error when trying to `conda develop` in a python 2.7 env using miniconda with python 3.5. I only get another error:

```
(docs) joris@joris-XPS-13-9350:~/scipy/pandas$ conda develop -b .
running build_ext
...
Completed: python /home/joris/scipy/pandas/setup.py build_ext --inplace
===============================================
Traceback (most recent call last):
  File "/home/joris/miniconda3/bin/conda-develop", line 6, in <module>
    sys.exit(conda_build.cli.main_develop.main())
  File "/home/joris/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_develop.py", line 72, in main
    return execute(sys.argv[1:])
  File "/home/joris/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_develop.py", line 68, in execute
    build_ext=args.build_ext, clean=args.clean, uninstall=args.uninstall)
  File "/home/joris/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 186, in develop
    return execute(recipe_dir, prefix, no_pth_file, build_ext, clean, uninstall)
  File "/home/joris/miniconda3/lib/python3.5/site-packages/conda_build/develop.py", line 191, in execute
    write_to_conda_pth(sp_dir, pkg_path)
  File "/home/joris/miniconda3/lib/python3.5/site-packages/conda_build/develop.py", line 50, in write_to_conda_pth
    with open(c_file, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/joris/miniconda3/envs/docs/lib/python3.5/site-packages/conda.pth'
```

So it wants to find/put a `conda.pth` file in `lib/python3.5`, but since it is a python 2.7 environment, this of course does not exist.
