### ISSUE TITLE
Need ability to specify the build output directory as a command line parameter or env var

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda-build#1062]
On shared systems where multiple users may be performing builds from the same root Anaconda installation it is desirable to be able to specify the build output directory on a per build basis.

Add a command line parameter and/or and env var where the output directory can be specified to override the default output location.

This is an immediate need at the JPM client site.

**Comment by msarahan** [comment]
Got it.  I'll see what I can do.

**Comment by msarahan** [comment]
Note that this won't solve conda's locking though - simultaneous builds will still be limited by environment creation (though I'll make sure these environments can coexist.)
