### ISSUE TITLE
msvc9 compiler fails initialization; 1.21.3 still broken on Windows

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1065]
Using Python 2.7.11, Windows 10:
```
$ conda info
Current conda install:

             platform : win-64
        conda version : 4.1.4
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Miniconda2  (writable)
  default environment : C:\Miniconda2
     envs directories : C:\Miniconda2\envs
        package cache : C:\Miniconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```
When trying to compile a Cython file, I get:

```
   File "C:\Miniconda2\envs\_build\lib\distutils\msvc9compiler.py", line 473, in compile
     self.initialize()
   File "C:\Miniconda2\envs\_build\lib\distutils\msvc9compiler.py", line 383, in initialize
     vc_env = query_vcvarsall(VERSION, plat_spec)
   File "C:\Miniconda2\envs\_build\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsall
     raise ValueError(str(list(result.keys())))
 ValueError: [u'path', u'include', u'lib']
```

The problem is that the query_vcvarsall() routine is also looking for "libpath", which isn't there, and isn't used anywhere.  And why is the result comparison (in query_vcvarsall()) done with len(), instead of just comparing two sets for equality?

**Comment by msarahan** [comment]
Which compiler do you have installed? 

Is there more to that traceback that you did not show? Please post the whole build log somewhere. I am guessing that it is not finding a compiler at all. Conda build does not use query_vcvarsall.

**Comment by msarahan** [comment]
Ps,  regarding your question about result comparison: that code is in Python's distutils package, not conda build. I don't know why they do things that way, but we can raise that issue upstream if you want.

**Comment by janssen** [comment]
Sorry, I misunderstood.  Yes, if you could raise that, it would be good.  What bugs me is that this was  all working last week.  I figured once 1049 was added, it would work again.  Something else has changed, I guess.

**Comment by msarahan** [comment]
What compiler are you trying to use, though?  This should work, and does on my system and on AppVeyor.  I'm very curious how your system might be different.

**Comment by msarahan** [comment]
PS: My system: VS 2008 Pro SP1.  AppVeyor: VS Express 2008 for 32-bit.  VC for Python 2.7 for 64-bit.

**Comment by msarahan** [comment]
I think the issue here was that setuptools/cython was not finding your compiler.  I'm closing this issue.  If you want to provide us with more information about what compiler you have installed, I'll happily reopen it.
