### ISSUE TITLE
Issue fetching source from FTP server requiring username/password

### ISSUE THREAD

**Issue by tgjohnst** [conda/conda-build#1069]
I am encountering the following unexpected error when using conda-build to build a recipe that fetches from an FTP server, looks like the issue is arising when it tries to split out the username and password from the FTP url. Any suggestions?

```
...
File "/large/tgjohnst/conda_envs/miniconda3/lib/python3.5/site-packages/conda/connection.py", line 417, in get_username_password_from_header
    components = decoded.split(':')
TypeError: a bytes-like object is required, not 'str'
```

The full traceback, the output from conda info, and the recipe's meta.yaml are attached. 

[meta.yaml.txt](https://github.com/conda/conda-build/files/340133/meta.yaml.txt)  (username/password provided in meta.yaml are public info)
[conda info.txt](https://github.com/conda/conda-build/files/340136/conda.info.txt)
[conda output.txt](https://github.com/conda/conda-build/files/340135/conda.output.txt)

Thanks!

**Comment by keithj** [comment]
I encountered this using Miniconda on Python3 (incidentally using the same FTP site as above). The same release of Miniconda on Python 2.7 works fine.
