### ISSUE TITLE
Conda-build issue for an example in the tutorial for pyinstrument

### ISSUE THREAD

**Issue by raj0926** [conda/conda-build#1070]
((Anaconda3)) C:\Users\Rajesh>conda build pyinstrument
Removing old build environment
BUILD START: pyinstrument-0.10.1-py35_0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 144, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 389, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 332, in execute
    dirty=args.dirty, activate=args.activate)
  File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 478, in build
    has_vcs_available = os.path.isfile(external.find_executable(vcs_executable))
  File "C:\Anaconda3\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument

((Anaconda3)) C:\Users\Rajesh>

**Comment by msarahan** [comment]
I think that you are suffering from #1061 - basically, when the build process activates an environment, and an environment is already active, you can lose entries from PATH.  In your case, you are losing your PATH to your VCS tool.  That's how the output of find_executable is becoming None - there is no way for the vcs_executable to be None: https://github.com/conda/conda-build/blob/1.21.x/conda_build/build.py#L476-L478

There is a proposed fix at https://github.com/conda/conda/pull/2917 - until then, you have a few options:

1. Try to build without an environment active to begin with
2. list the appropriate version control system (VCS) in the build dependencies (git, svn, or whatever it uses)
3. call conda build with the --no-activate argument

**Comment by msarahan** [comment]
Fixed in #1100; part of 1.21.5 release.  Should be available soon.  Please let me know if you have further issues.  Closing this issue for now.
