### ISSUE TITLE
conda skeleton can't find setuptools

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-build#1075]
I don't know what to do here:

```
$ conda skeleton pypi --version 1.2.0  pydoop
Using url https://files.pythonhosted.org/packages/75/75/085a6410b085f231328884ca3349287a8705822ad8afdca715401e5c4f33/pydoop-1.2.0.tar.gz (934 KB) for pydoop.
Downloading pydoop
Unpacking pydoop...
done
working in /tmp/tmpxaIyxLconda_skeleton_pydoop-1.2.0.tar.gz
Fetching package metadata .........
Solving package specifications: ..........

Applying patch: '/tmp/tmpxaIyxLconda_skeleton_pydoop-1.2.0.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    import setuptools
ImportError: No module named setuptools
$PYTHONPATH = /tmp/tmpxaIyxLconda_skeleton_pydoop-1.2.0.tar.gz/pydoop-1.2.0:/opt/rh/devtoolset-2/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-2/root/usr/lib/python2.7/site-packages
Error: command failed: /home/ijstokes/.conda/envs/_build/bin/python setup.py install
```

**Comment by msarahan** [comment]
I think that this is very related to the problem you reported in #1073 - it's look in the wrong sys.prefix somehow.

**Comment by ijstokes** [comment]
@msarahan if you have a few minutes to look at this with me I'd very much appreciate it.  Or I can give you access to the system in question and you can try for yourself.  I am trying to build a set of packages for a client and am unable to do so because of this, so it isn't idle curiosity or a side project.

I'm now getting this problem just with vanilla `conda build` commands as well.

**Comment by ijstokes** [comment]
I'm sure @msarahan will add more, but my best understanding from the debug session I just had with him was that it came down to a buggy Python 2.7.12 build, and that pinning to 2.7.10 should fix things.

**Comment by msarahan** [comment]
Issue was an improper python package.  See https://github.com/ContinuumIO/anaconda-issues/issues/870 - closing
