### ISSUE TITLE
conda build not cleaning old version of setup.py

### ISSUE THREAD

**Issue by patanijo** [conda/conda-build#1093]
I am using conda build to create a package.

In my setup.py, I have the following:

setup(name=os.getenv('PKG_NAME', ''),
      version=os.getenv('PKG_VERSION', 0.1),
      packages=packages, requires=['pandas', 'scipy'])

I am getting the error message below in conda build (Note the difference in the requires argument)

Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    packages=packages, requires=['scipy', 'pandas','scikit-learn'])

This error is from an older version of setup.py, and I am unable to get the conda install to run the current version of setup.py.  I have tried conda clean as well as totally unistalling and reinstalling Anaconda. I have deleted the _build and _work environments without success.

Any suggestions at how to resolve this issue and clear out the cached setup.py file?

**Comment by msarahan** [comment]
What does your recipe's meta.yaml contain?  Wherever it is pulling source from is where you need to change setup.py - not the _build or _work or _test or whatever folders.  In general, it's best not to change contents in those, since they will be destroyed with other builds.

**Comment by patanijo** [comment]
Thanks that was the issue. Source for recipe was a central git repository, and I was committing but had not pushed yet, and thus it was always using my previous setup.py
