### ISSUE TITLE
Support use of command to get version

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1110]
As we have deprecated `__conda_??__.txt` files ( https://github.com/conda/conda-build/issues/951 ), we need to be able to have a way to run a command (e.g. `python setup.py --version`) so that we can get the version in development recipes.

**Comment by msarahan** [comment]
I think #1106 should take care of this use case.  If people aren't using setuptools, then I need to talk with them to figure out how to get their build numbers before the build starts.  Any time during rendering is fine - before source is downloaded, after, or anywhere.
