### ISSUE TITLE
[regression] windows x86 linker error introduced in 1.21.4 for Python-3.5

### ISSUE THREAD

**Issue by marscher** [conda/conda-build#1111]
With recent conda-build versions my builds fail on Appveyor on Python-3.5, windoze 32 bit:

When I enforce a previous version of conda-build, it works again:
* https://ci.appveyor.com/project/marscher/pyemma-668/build/1.0.783/job/6kpk5aq3p7k0fqw6 1.21.3 success
* https://ci.appveyor.com/project/marscher/pyemma-668/build/1.0.784 1.21.4 regression

I've also asked the maintainer of Appveyor about this, since there has been some changes to the build-worker-image, but this seems not to affect this:
http://help.appveyor.com/discussions/problems/5003-visual-studio-linker-error-with-several-build-images

**Comment by msarahan** [comment]
Thanks for reporting this.  Nothing comes to mind right away, but I will investigate.

**Comment by marscher** [comment]
@msarahan thanks for looking into this.

**Comment by marscher** [comment]
the new version sets MSSdk=1 and DISTUTILS_USE_SDK=1 whereas the old version doesn't

**Comment by marscher** [comment]
It seems like the new version shadows the desired linkage path, since the linker throws this warning:

LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library

**Comment by msarahan** [comment]
That last point of yours indicates less a path problem and more a confused
mixup of some libraries compiled with  /MT (use static msvc runtime) and
/MD (use msvc runtime DLLs). It seems like the newer version may be forcing
/MD somehow, while one or more of your dependencies were compiled with /MT.

**Comment by marscher** [comment]
how would I find out which dependencies that are? If the new version enforces the usage of the dynamic runtime libraries, we essentially would have to recompile all existing dependencies, right?

**Comment by msarahan** [comment]
I would look for msvcrt.dll dependencies on your DLLs with dependency walker.

Recompiling everything with /MD would be one solution, but I don't understand why it would be forcing /MD.  Conda-build should not interfere with that.  Do you have that explicitly set somehow on your build?  This said, unless you really want static libraries for your end product, I think you're better off with /MD - it's what you'll find the vast majority of available binary libraries compiled with.

Also, note that your library can be static, but still depend on the dynamic MSVCRT.  They're not the same thing.  /MT and /MD only apply to which MSVCRT is used, not whether your output library is static or dynamic.

**Comment by marscher** [comment]
thanks for the explanation! The binary Python extension format is not known by DependencyWalker, however I'm pretty sure that something with mdtrajs libtheobald linkage blows things up. The relevant code for linking this library can be found here:
https://github.com/mdtraj/mdtraj/blob/master/basesetup.py#L278-L307

So do you suggest to (forcefully) set the linker args to /MD?

**Comment by msarahan** [comment]
It seems like this might be the right place: https://github.com/mdtraj/mdtraj/blob/master/basesetup.py#L297

You might be able to set it at: https://github.com/mdtraj/mdtraj/blob/99a34e99a17ac86ce7827762203e3239d298d582/setup.py#L181

I think that distutils or whatever is ultimately driving your compilation does not understand the distinction that I outlined above about /MD & /MT vs static/dynamic library.  It is OK that libtheobald is static, but it should use /MD to use the DLL version of MSVCRT.  If that ends up being too hard to fix, maybe make libtheobald just a library, not a static library?

**Comment by msarahan** [comment]
May also be an arg you can pass around at: https://github.com/mdtraj/mdtraj/blob/99a34e99a17ac86ce7827762203e3239d298d582/setup.py#L78

**Comment by msarahan** [comment]
@marscher I think we may have the issue fixed in #1129 - see http://stevedower.id.au/blog/building-for-python-3-5-part-two/ - especially the "Always statically link" section

**Comment by marscher** [comment]
Confirmed, #1129 fixed the issue! Thanks a lot!
