### ISSUE TITLE
conda-build won't create a build environment that I can create by hand

### ISSUE THREAD

**Issue by davidslac** [conda/conda-build#1120]
I am writing a recipe for tables (pytables). conda-build reports 

    Warning: package conflict - you may have unresolved dependencies. Try to conda install each of your dependencies to figure out which has unresolved dependencies.TEST START: tables-3.2.3.1-py27_hdf18_100

and halts. However I am able to create the build environment, so I don't see any issue with the dependencies. My requirements area looks like

    requirements:
     build:
        - python ==2.7
        - nomkl ==1.0
        - numpy ==1.11.1 py27_blas_openblas_200
        - numexpr ==2.6.0 np111py27_nomkl_0
        - openmpi ==1.10.3 lsf_verbs_{{ openmpi_build }}
        - hdf5 ==1.8.17 openmpi_{{ hdf5_build }}

openmpi and hdf5 are comming from local channels. I have conda-forge in place to pick up their numpy since I was having a lot of trouble with the mkl based defaults conda numpy, but since conda-forge doesn't have numexpr, to get a numexpr compatible with their numpy, I made my own nomkl package (also from a local channel) so that I could get conda to select the numexpr in its defaults that doesn't have the mkl. It's kind of messy. 

Anyways, since I can create that build environment, is their a switch to force conda-build to proceed?

**Comment by msarahan** [comment]
Conda-build might be getting confused with the python constraint.  You might need to pass an additional argument:

    conda build <recipe dir> --python=2.7

and potentially also numpy:

    conda build <recipe dir> --python=2.7 --numpy=1.11

If this works, it's because conda-build handles python and numpy specially.  Leaving them as just requirements bypasses that special handling.

**Comment by davidslac** [comment]
That helped, it wasn't building without that, but I also had to explicitly list my custom channels on the conda build command line. For some reason, conda-build stopped getting them from the .condarc in the central installation directory. Anyways, I seem to be moving again, thanks!

**Comment by msarahan** [comment]
conda-build should be respecting your condarc.  I'll look into that.

**Comment by davidslac** [comment]
I don't know if this is related, but since updating to the latest conda/conda-build, I also get a warning about binstar not being defined. I've never installed the anaconda bin star package, I've just been working with custom channels that are local paths on our filesystem.

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by msarahan** [comment]
@davidslac I have a test for this behavior in https://github.com/conda/conda-build/pull/1157 - it seems to work fine, but I am not testing without anaconda-client.

If you keep having issues, please let us know.  I'm closing this issue for now, but will reopen it if further issues occur.

**Comment by davidslac** [comment]
Thanks for doing this, I think I'm just going to build a fresh miniconda install, and install anaconda-client. If I still see the problem, will let you know.

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by davidslac** [comment]
I am still having a problem - but maybe this is not a conda build problem so much as a conda problem. I re-installed miniconda and updated to conda, conda-env, conda-build and anaconda-client as of today. I have a package called szip in one of my file based channels, but I can't create an environment with it unless I explicitly pass the channel. Details below:

```
(psreldev) psel701: /reg/g/psdm/sw/conda $ which python 
/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/bin/python
(psreldev) psel701: /reg/g/psdm/sw/conda $ cat /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/.condarc 
channels:
  - file:///reg/g/psdm/sw/conda/channels/system-rhel7
  - file:///reg/g/psdm/sw/conda/channels/psana-rhel7
  - file:///reg/g/psdm/sw/conda/channels/external-rhel7
  - defaults
  - scikit-beam
  - file:///reg/g/psdm/sw/conda/channels/testing-rhel7

(psreldev) psel701: /reg/g/psdm/sw/conda $ conda create -n tst szip
Fetching package metadata .......
Solving package specifications: .
Error: Package missing in current linux-64 channels: 
  - szip

Close matches found; did you mean one of these?

    szip: sip

You can search for packages on anaconda.org with

    anaconda search -t conda szip
(psreldev) psel701: /reg/g/psdm/sw/conda $ conda create -n tst szip -c file:///reg/g/psdm/sw/conda/channels/external-rhel7
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...INFO:stdoutlog:Fetching package metadata ...
.DEBUG:dotupdate:fetching repodata: args ('file:///reg/g/psdm/sw/conda/channels/external-rhel7/linux-64/',) kwargs {'session': <conda.connection.CondaSession object at 0x7f4364abef50>, 'use_cache': False}
.DEBUG:dotupdate:fetching repodata: args ('file:///reg/g/psdm/sw/conda/channels/external-rhel7/noarch/',) kwargs {'session': <conda.connection.CondaSession object at 0x7f4364abef50>, 'use_cache': False}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/linux-64/',) kwargs {'session': <conda.connection.CondaSession object at 0x7f4364abef50>, 'use_cache': False}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/noarch/',) kwargs {'session': <conda.connection.CondaSession object at 0x7f4364abef50>, 'use_cache': False}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/linux-64/',) kwargs {'session': <conda.connection.CondaSession object at 0x7f4364abef50>, 'use_cache': False}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/noarch/',) kwargs {'session': <conda.connection.CondaSession object at 0x7f4364abef50>, 'use_cache': False}

INFO:stdoutlog:

Solving package specifications: INFO:stdoutlog:Solving package specifications: 
.DEBUG:dotupdate:Solving for [MatchSpec('szip')]
.DEBUG:dotupdate:Checking satisfiability
.DEBUG:dotupdate:Package removal metric: 0
.DEBUG:dotupdate:Initial package version/build metrics: 0/0
.DEBUG:dotupdate:Track feature count: 0
.DEBUG:dotupdate:Package feature count: 0
.DEBUG:dotupdate:Dependency update count: 0
.DEBUG:dotupdate:Additional package version/build metrics: 0/0
.DEBUG:dotupdate:Weak dependency count: 0
.DEBUG:dotupdate:Looking for alternate solutions

INFO:stdoutlog:


Package plan for installation in environment /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/tst:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    szip-2.1                   |              100          37 KB  file:///reg/g/psdm/sw/conda/channels/external-rhel7

The following NEW packages will be INSTALLED:

    szip: 2.1-100 file:///reg/g/psdm/sw/conda/channels/external-rhel7

Proceed ([y]/n)? n


```

**Comment by msarahan** [comment]
That does seem like conda is not respecting the file:// channels.  Please raise an issue on the conda issue tracker: https://github.com/conda/conda/issues

**Comment by davidslac** [comment]
Aha! I had a .condarc in my home directory! I delete ~/.condarc ~/.conda and ~/.continuum, all the local stuff for this account, and now it picked up the central .condarc. 

So maybe this is the bug? If I go back and just to 

touch ~/.condarc

The central install .condarc doesn't get read. I thought the conda  configuration was some kind of mix of your local .condarc in the home directory and the central install one? I'm only testing this from the account that created the central install, don't know if that matters.

**Comment by msarahan** [comment]
Sure, that's probably it.  There's a much better scheme for this in conda 4.2.  It's in the early release stage, if you'd like to try it.

**Comment by davidslac** [comment]
Thanks, I see the tags in the github, I'll see if I'm feeling brave this week :) Or do you have a development channel to pull it from?

**Comment by msarahan** [comment]
We have the conda-canary channel for this purpose: https://anaconda.org/conda-canary - your feedback would be most appreciated!
