### ISSUE TITLE
Deprecation warning: support for __conda_version__ will be removed in Conda build

### ISSUE THREAD

**Issue by srossross** [conda/conda-build#1121]
How is this going to work? We are specifically **not** using Jinja templates because we do not know the version until after the build has run.

```
Deprecation warning: support for __conda_version__ will be removed in Conda build 2.0.Try Jinja templates instead: http://conda.pydata.org/docs/building/environment-vars.html#git-environment-variables
Setting version from __conda_version__.txt: 2.19.3
Deprecation warning: support for __conda_buildnum__ will be removed in Conda build 2.0.Try Jinja templates instead: http://conda.pydata.org/docs/building/environment-vars.html#git-environment-variables
```

**Comment by msarahan** [comment]
The reason for this is that I think it should always be possible to output the built package name without building. If it is fundamentally impossible or impractical to know the version before build, I'll reconsider. However, I would rather teach conda build whatever it needs to know in order to get your version before build. Your load_setuptools Jinja context function is a good example. I have also heard several requests for an auto incrementing build number, and have some preliminary code on that.

**Comment by msarahan** [comment]
xref https://github.com/conda/conda-build/issues/1023 - closing this issue to consolidate discussion there.  Please post your requirements, and I'll do my best to help you find a way to get your version pre-build - or change my plans if necessary.

**Comment by anton-malakhov** [comment]
@msarahan , it's a pity that this feature is removed. I don't think that parsing setup.py file with fixed name and location is an acceptable option for non-python packages that do not use git (like TBB internally). Any suggestion how to solve this as elegant as using `__conda_version__.txt`?

**Comment by msarahan** [comment]
The only thing that was removed is any support for versioning as a post
build bit of info. Getting the version from a file is elegant. Doing
anything related to versioning after the build step breaks a ton of other
stuff and is anything but elegant.

Take a look at load_file_regex as a way of getting the version from a file.
That file must exist in your source tree prior to build, but there are no
other restrictions.

Sorry I can't provide a link, I'm on my phone.

**Comment by anton-malakhov** [comment]
Thanks, Mike! That is something I can work with! One possibly missing functionality is multiple matches support (e.g. findall or scan instead of `re.search`). E.g. I could specify one regex with two capture groups and use a dictionary to access key/values pairs parsed from a file.
