### ISSUE TITLE
repodata.json references conda-4.1.9 but the file doesn't exist

### ISSUE THREAD

**Issue by rgargente** [conda/conda-build#1134]
This makes the installation of some packages, like for example pyyaml fail. The json file was edited yesterday so it might be a very new bug.

**Comment by ilanschnell** [comment]
How can you tell that the file does not exist?  Did you try downloading it?

**Comment by rgargente** [comment]
Well I can assure you it wasn't in https://repo.continuum.io/pkgs/free/win-64/ just a few hours ago but now it seems like it is actually there. Weird!

**Comment by ilanschnell** [comment]
The HTML index is sometimes out-of-date, as it only gets updated nightly.  Thanks for letting us know though.

**Comment by rgargente** [comment]
Ok, that makes sense then. We were downloading our own copy of the free repo and we use the html index for that. That's how we ended up with an inconsistent version. It could be worth considering updating both at the same time.
