### ISSUE TITLE
Please sign Contributor License Agreement

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1144]
To the honorable, honored group below: your contributions make up conda-build.  Continuum needs to obtain contributor signatures from all of you, so that we can offer Conda-build to our customers under different indemnification terms.  I will edit this issue to remove names as people sign the CLA.

Please read and sign https://www.clahub.com/agreements/conda/conda-build

Current and past Continuum employees are not strictly required to sign, but it would be nice.

Best regards, and my admiration to all of you for helping to get conda-build where it is today.

@tacaswell (5, 82)
@shoyer (4, 9)
@userzimmermann (3, 47)
@llawall (2, 11)
@esc24 (2, 4)
@tkf (2, 16)
@whitequark (2, 2)
@yannpaul (2, 9)
@dlovell (1, 31)
@alexcoman (1, 197)
@RobertCoop (1, 7)
@jlas (1, 11)
@flub (1, 1)

**Comment by flub** [comment]
Hi,

Could you detail what this CLA enables Continuum to do which it can not with the 3-part BSD license under which we submitted our contributions?  It seems to me you are seeking safety from patents, but as not a specialist in the matter I would be more comfortable with well-known licenses which include this.  I'm also not sure how clause 2 interacts with the 3-part BSD license, does it mean Continuum can just re-license to anything they want at any time?

I also find the sentence "In return, Continuum shall not use Your Contributions in a way that is contrary to the public benefit." rather weird and vague and am not even sure it if is part of the legal agreement sought here or not.

Regards,
Floris

**Comment by msarahan** [comment]
@flub, here's a response from @teoliphant, our CEO:

> These are good questions.    We will need to prepare a response or FAQ.

> The quick and dirty answer that you can give of the purpose of the CLA is:

> 1) We need to be assured that you can actually provide the contribution and have your employers permission
> 2) We need to be assured you haven't included things you knew were patents.  

> We are using Facebook's CLA which is well-known rather than invent our own.     The contribution is governed under the 3-clause BSD.   This is a set of extra assurances that help us indemnify those who rely on this code.    

> The 3-clause BSD does allow Continuum (and anyone else) to create proprietary derivatives from the work.    That is true. 

> I agree that the clause "contrary to the public good" is vague --- it was borrowed from Facebook.    It tries to convey that we are not intending to do anything with it that you wouldn't expect --- better language welcome.

**Comment by msarahan** [comment]
Collaborators, this is one final reminder.  Even if your answer is "I don't want to sign," I would appreciate a response.  The numbers in parentheses are your number of commits, and the number of lines added.

@richafrank (7, 74)
@tacaswell (5, 82)
@shoyer (4, 9)
@userzimmermann (3, 47)
@rmcgibbo (3, 50)
@meawoppl (3, 49)
@llawall (2, 11)
@esc24 (2, 4)
@tkf (2, 16)
@whitequark (2, 2)
@yannpaul (2, 9)
@mhworth (1, 5)
@dlovell (1, 31)
@rvianello (1, 11)
@gdementen (1, 24)
@alexcoman (1, 197)
@RobertCoop (1, 7)
@jlas (1, 11)
@flub (1, 1)
@brantfaircloth (1, 2)

Thanks, to all of you.

**Comment by richafrank** [comment]
@msarahan I believe I signed some time ago. Anything else I need to do?

**Comment by shoyer** [comment]
I'm afraid I can't help you here. This would need to be reviewed by the legal department at my former employer.

**Comment by rmcgibbo** [comment]
Done

**Comment by msarahan** [comment]
@richafrank, confirmed, sorry for the noise.
@shoyer, could you please email me the details for your former employer?  msarahan@continuum.io
@rmcgibbo, thank you!

**Comment by gdementen** [comment]
@msarahan I thought I did sign it a while back... Am I missing something?

**Comment by msarahan** [comment]
@gdementen, confirmed.  Sorry for the noise, and thanks.

**Comment by meawoppl** [comment]
Can you shoot me the agreement, it's my GitHub name at Gmail
