### ISSUE TITLE
`bdist_conda` fails: `work` directory already exists

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1150]
Running into a weird issue with `bdist_conda` where it seems unable to build due to the `work` directory already existing. Please see this [log]( https://travis-ci.org/nanshe-org/nanshe/jobs/148072433#L601 ) for more details.

**Comment by msarahan** [comment]
Thanks for pointing this out.  bdist_conda is not tested at all right now.  Glad to see how it is used, though - I hadn't seen it before this.  I'll fix this in the next release.

**Comment by jakirkham** [comment]
IIUC the main benefit of having `bdist_conda` was to easily generate conda packages from Python source code. Though it seems there are better ways to do that since like `conda pipbuild` (now deprecated) and `conda skeleton pypi`.

When I wrote the `setup.py` file, it was just an easy way for me to get started with `conda-build`. More recently I have been wondering if it would be better to switch to something a little more mainstream like writing a recipe.

**Comment by msarahan** [comment]
I've seen requests to create packages from setup.py.  It seems to me that something like

```conda skeleton pypi <dir with setup.py>```

might be useful or more intuitive than pipbuild or bdist_conda.  Perhaps ```pypi``` could be something else, since it isn't really pypi in the loop here.

**Comment by msarahan** [comment]
I'm pretty sure this is fixed in https://github.com/conda/conda-build/pull/1175 or before.  Closing - but please reopen if issue recurs.
