### ISSUE TITLE
Logic behind source.get_dir

### ISSUE THREAD

**Issue by pelson** [conda/conda-build#1173]
Just trying to get my head around how conda-build goes about determining the `work` dir and spotted https://github.com/conda/conda-build/blob/d2a89e4b04cdbfffc424d679267cc681031cd00a/conda_build/source.py#L29-L36. 

If I'm reading it correctly, the intention is for conda-build to report the work dir as the first directory that  doesn't contain exactly one other directory, else it will return the configured WORK_DIR. 

Unfortunately, I'm experiencing (through conda-build-all, not the conda-build CLI) a problem (https://github.com/SciTools/conda-build-all/issues/51) emanating from https://github.com/conda/conda-build/blob/d2a89e4b04cdbfffc424d679267cc681031cd00a/conda_build/build.py#L553-L558 whereby makedirs is trying to make a directory that already exists. I'm interested to know if the intention for those lines was to check ``src_dir`` rather than `source.WORK_DIR`?

**Comment by msarahan** [comment]
Yes, I think this was a bug, and thank you for fixing it!  I think this issue can be closed thanks to your PR.
