### ISSUE TITLE
pypi url broken

### ISSUE THREAD

**Issue by enzobusseti** [conda/conda-build#1179]
If i do

> enzo$ conda skeleton pypi scs
> INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.io
> INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org
> Error: XMLRPC Fault while parsing PyPI response.  This is likely a transient error - please try again soon.

The url to pypi is broken. I fixed this by changing

>    pypi.add_argument(
>        "--pypi-url",
>        action="store",
>        default='https://pypi.io/pypi',
>        help="URL to use for PyPI (default: %(default)s).",
>    )

into

>    pypi.add_argument(
>        "--pypi-url",
>        action="store",
>        default='https://pypi.python.org/pypi',
>        help="URL to use for PyPI (default: %(default)s).",
>    )

in main_skeleton.py

**Comment by msarahan** [comment]
Thanks for this report, and especially for the fix.  There's a little more detail in #1177 - I'm closing this issue as a duplicate.  Please follow the other issue for status.
