### ISSUE TITLE
conda-build is creating .pyc files for entry points scripts on Windows

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda-build#1180]
conda-build 1.21.7 did not have this problem, but using 1.21.10 or master, when I build a conda package on Windows (at least on Python 2 on Python 3 probably also in the `__pycache__` directory), I get a `.pyc` file next to the Windows entry point Python script.  For example, when I build https://github.com/ContinuumIO/anaconda-recipes/tree/master/grin, I now get:
```
Scripts/grin.exe
Scripts/grin-script.py
Scripts/grin-script.pyc
...
```
This is not a huge problem, but https://github.com/ContinuumIO/anaconda-verify/ complains about the unnecessary extra file.

**Comment by msarahan** [comment]
Thanks.  What is a necessary vs. unnecessary pyc file?  I'm very confused on that.  We have had many discussions on the topic, and mostly I have thought that your opinion and @kalefranz is that we should always ship pyc's (or perhaps create them at install time, when write permissions are guaranteed).  

I changed the compilation code in https://github.com/conda/conda-build/pull/1155 in an attempt to ensure that we did not accidentally package pyc files for other packages.  Do I need to restrict the folders for that?  I'd be happy to omit entry points somehow, but I think limiting it to strictly site-packages may be a little too tight.

**Comment by ilanschnell** [comment]
Thanks for your reply Mike.  The entry points are certainly an exception here.  `.pyc` are only used by Python when *importing* modules, not when executing scripts directly, which is what the Windows entry point executable does.  In addition, some packages, such as the old `pil`, but also others install "scripts" ending in `.py` in the `bin/` (or `Scripts/`) directory.  One wouldn't want `.pyc` files for those, when those packages are installed using `python setup.py install`, no `.pyc` files are created either, again because they scripts meant to be executed directly and not imported.

I summary, I would argue that `.pyc` files should never be created in `bin/` (or `Scripts/`), simply because they are not imported.
