### ISSUE TITLE
Always using expanded placeholder prefix

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1184]
Appears that `conda-build` is now always using the expanded placeholder prefix. Here is an [example]( https://travis-ci.org/conda-forge/libgfortran-feedstock/builds/150473169#L406 ). This seems to be new behavior in `1.21.11` and was not present in `1.21.9`.

**Comment by msarahan** [comment]
Can you explain to me how this breaks things?  Having it switch was breaking things when the configuration lost track of whether to use long or short prefixes, so I set it to always be long in unix, and always short on Windows (where it is not necessary for reserving space in a binary, and where we have problems with a 260 char path limit).

**Comment by jakirkham** [comment]
Not sure it is breaking things. Just noting this did change and trying to understand if it is intentional. Sounds like the answer is yes.

**Comment by msarahan** [comment]
Yep, totally intentional.  Trying to simplify some things, and didn't see why this dichotomy needed to exist on Unix.  Please keep me posted if it causes issues.  Closing this issue for now.

**Comment by hainm** [comment]
@msarahan the long placeholder makes the build logv very hard to read. 

An example here

```bash
g++ -O3 -Wall -fopenmp  -DNO_ARPACK -DHASBZ2 -DHASGZ -DBINTRAJ -
D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/home/ubuntu/miniconda/conda-
bld/libcpptraj_1477501410738/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -I/home/ubuntu/miniconda/conda-
bld/libcpptraj_1477501410738/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -I/home/ubuntu/miniconda/conda-
bld/libcpptraj_1477501410738/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -I/home/ubuntu/miniconda/conda-
bld/libcpptraj_1477501410738/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -Ixdrfile  -fPIC    -c -o Action_LESsplit.o 
Action_LESsplit.cpp
```

**Comment by msarahan** [comment]
The Config class has a way to change the prefix length.  It would be pretty easy to add a command line option to shorten it.  I'm absolutely not going to change the default, though.  That long prefix length is obnoxious and it makes logs hard to read, but it is necessary to allow people to install packages into longer prefixes.  Any usage of a shorter prefix should be strictly limited to developing recipes, not putting production packages out.

**Comment by hainm** [comment]
Fair enough. Cheers.
