### ISSUE TITLE
Conda build fails on automated build attempt

### ISSUE THREAD

**Issue by briantoby** [conda/conda-build#1185]
I am able to build g2pkg on my local mac, but when I try to move it to a remote machine, I run into the error shown below:

+ /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/bin/conda build g2pkg
+ source activate /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
++ [[ -n 3.2.53(1)-release ]]
++ _SCRIPT_LOCATION=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/activate
++ _SHELL=bash
+++ dirname /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/activate
++ _CONDA_DIR=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin
++ '[' 1 -gt 1 ']'
++ case "$(uname -s)" in
+++ uname -s
++ EXT=
++ [[ -n 3.2.53(1)-release ]]
+++ basename /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/conda-bld/work/conda_build.sh
++ [[ conda_build.sh == \a\c\t\i\v\a\t\e ]]
++ '[' 1 -eq 0 ']'
++ args=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
++ /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/conda ..checkenv bash /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
++ ((  0 != 0  ))
++ source /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/deactivate
+++ [[ -n 3.2.53(1)-release ]]
+++ _SCRIPT_LOCATION=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/deactivate
+++ _SHELL=bash
++++ dirname /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/deactivate
+++ _CONDA_DIR=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin
+++ case "$(uname -s)" in
++++ uname -s
+++ EXT=
+++ [[ 1 > 0 ]]
+++ key=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
+++ case $key in
+++ shift
+++ [[ 0 > 0 ]]
+++ [[ -n 3.2.53(1)-release ]]
++++ basename /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/conda-bld/work/conda_build.sh
+++ [[ conda_build.sh == \d\e\a\c\t\i\v\a\t\e ]]
+++ [[ -z '' ]]
+++ [[ -n 3.2.53(1)-release ]]
++++ basename /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/conda-bld/work/conda_build.sh
+++ [[ conda_build.sh == \d\e\a\c\t\i\v\a\t\e ]]
+++ return 0
+++ /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/conda ..activate bash /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
++ _NEW_PART=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin
++ ((  0 == 0  ))
++ export CONDA_PATH_BACKUP=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin:/Users/jenkins/bin:/usr/local/bin:/opt/local/bin:/bin:/usr/bin:/usr/sbin:/sbin
++ CONDA_PATH_BACKUP=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin:/Users/jenkins/bin:/usr/local/bin:/opt/local/bin:/bin:/usr/bin:/usr/sbin:/sbin
++ export CONDA_PS1_BACKUP=
++ CONDA_PS1_BACKUP=
++ export PATH=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin:/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin:/Users/jenkins/bin:/usr/local/bin:/opt/local/bin:/bin:/usr/bin:/usr/sbin:/sbin
++ PATH=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin:/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin:/Users/jenkins/bin:/usr/local/bin:/opt/local/bin:/bin:/usr/bin:/usr/sbin:/sbin
++ [[ '' == */* ]]
++ export CONDA_DEFAULT_ENV=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
++ CONDA_DEFAULT_ENV=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
++ firstpath=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin
+++ echo /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin
+++ sed 's|/bin$||'
++ export CONDA_PREFIX=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_
+++ /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/conda ..changeps1
++ '[' 1 = 1 ']'
+++ grep -q CONDA_DEFAULT_ENV
++ export 'PS1=(/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_) '
++ PS1='(/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_) '
++ _CONDA_D=/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/etc/conda/activate.d
++ [[ -d /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/etc/conda/activate.d ]]
++ unset CONDA_PATH
++ [[ -n 3.2.53(1)-release ]]
++ hash -r
+ echo 'running build.sh'
running build.sh
+ mkdir -p /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin
+ cp /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/GSAS-II/install/g2pkg/src/bootstrap.py /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs/_build_placehold_/bin/gsas2-install.py
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Removing old build environment
BUILD START: g2load-0.1.8-0
    (actual version deferred until further download or env creation)
Copying /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/GSAS-II/install/g2pkg/src to /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/conda-bld/work
BUILD START: g2load-0.1.8-0
Package: g2load-0.1.8-0
source tree in: /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/conda-bld/work
compiling .pyc files...
Traceback (most recent call last):
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/site-packages/conda_build/main_build.py", line 152, in main
    args_func(args, p)
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/site-packages/conda_build/main_build.py", line 415, in args_func
    args.func(args, p)
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/site-packages/conda_build/main_build.py", line 358, in execute
    debug=args.debug)
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/site-packages/conda_build/build.py", line 646, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/site-packages/conda_build/post.py", line 182, in post_process
    compile_missing_pyc(files)
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/site-packages/conda_build/post.py", line 174, in compile_missing_pyc
    call([python_exe, '-Wi', '-m', 'py_compile'] + compile_files, cwd=cwd)
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

+ /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/bin/conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.1
  conda-build version : 1.21.11+0.g5b44ab3.dirty
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2  (writable)
  default environment : /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2
     envs directories : /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/envs
        package cache : /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

+ /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2/bin/conda list
# packages in environment at /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/conda2:
#
anaconda-client           1.5.1                    py27_0  
clyent                    1.2.2                    py27_0  
conda                     4.1.11                   py27_0  
conda-build               1.21.11                  py27_0  
conda-env                 2.5.1                    py27_0  
constructor               1.3.1                    py27_0  
jinja2                    2.8                      py27_1  
libconda                  4.0.0                    py27_0  
markupsafe                0.23                     py27_2  
openssl                   1.0.2h                        1  
pip                       8.1.2                    py27_0  
pycosat                   0.6.1                    py27_1  
pycrypto                  2.6.1                    py27_4  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.11                     py27_4  
readline                  6.2                           2  
requests                  2.10.0                   py27_0  
ruamel_yaml               0.11.14                  py27_0  
setuptools                23.0.0                   py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  

+ ls -lR /Users/jenkins/workspace/GSAS-II-Mac64-Constructor/GSAS-II/install/g2pkg
total 40
-rw-r--r--  1 jenkins  staff  230 Aug  7 17:18 bld.bat
-rw-r--r--  1 jenkins  staff  118 Aug  7 17:18 build.sh
-rw-r--r--  1 jenkins  staff  178 Aug  7 17:18 meta.yaml
-rw-r--r--  1 jenkins  staff  288 Aug  7 17:18 post-link.bat
-rw-r--r--  1 jenkins  staff  227 Aug  7 17:18 post-link.sh
drwxr-xr-x  4 jenkins  staff  136 Aug  7 17:18 src

/Users/jenkins/workspace/GSAS-II-Mac64-Constructor/GSAS-II/install/g2pkg/src:
total 16
-rw-r--r--  1 jenkins  staff  7084 Aug  7 17:18 bootstrap.py

**Comment by msarahan** [comment]
Just to be clear - are all of the versions the same on both of your systems?  Conda-build 1.21.11 in both places?

**Comment by briantoby** [comment]
oops. No. This fails in conda-build-1.21.11 on both machines.

**Comment by briantoby** [comment]
It succeeds with conda-build 1.19.2, but fails with both conda-build 1.20.3 and conda-build 1.21.11. 

In case it is of help, the source is in https://subversion.xray.aps.anl.gov/pyGSAS/install (g2pkg)

**Comment by msarahan** [comment]
Thanks.  Having the source available should help a lot.  I'll see what I can find.

**Comment by msarahan** [comment]
I'm able to build the recipe successfully with #1186.  How urgently do you need this in a release?

**Comment by hainm** [comment]
For some reasons related to conda update, our build failed on travis (only happens today)

Status: https://travis-ci.org/arose/nglview/builds/150530492

Example: https://travis-ci.org/arose/nglview/jobs/150530498#L1410

**Comment by briantoby** [comment]
Since I can do a build with 1.19.2, getting this fixed is not a priority for me.

**Comment by msarahan** [comment]
@hainm please file a new issue.  I think your issue is related to an egg being created: https://travis-ci.org/arose/nglview/jobs/150530498#L1323

You probably need to change your ```python setup.py install``` line to ```python setup.py install --single-version-externally-managed --record=record.txt``` so that the egg does not get created.

**Comment by hainm** [comment]
> please file a new issue. 

done

> You probably need to change your python setup.py install line to python setup.py install --single-version-externally-managed --record=record.txt so that the egg does not get created.

thanks. I will try.
