### ISSUE TITLE
release dirty version? 1.21.11+0.g5b44ab3.dirty + long long build folder name

### ISSUE THREAD

**Issue by hainm** [conda/conda-build#1188]
Hi,

I was suggested to update conda-build from the conda message.

However, looking at the __version__, it's `1.21.11+0.g5b44ab3.dirty`

And I also see the very long and weird build folder

`_build_placehold_placehold_placehold_placehold_place`

**Comment by jakirkham** [comment]
> However, looking at the version, it's 1.21.11+0.g5b44ab3.dirty

Covered in this issue ( https://github.com/conda/conda-build/issues/1187 ). Probably some versioning program that is too clever or not clever enough.

> And I also see the very long and weird build folder

> _build_placehold_placehold_placehold_placehold_place

Covered in this issue ( https://github.com/conda/conda-build/issues/1184 ). The latter change is intentional.

**Comment by hainm** [comment]
thanks. sorry to duplicate the issues. (I only search `1.21.11+0.g5b44ab3.dirty`).

**Comment by jakirkham** [comment]
No worries. It's always good to know that you are not alone in experiencing an issue. 😄
