### ISSUE TITLE
conda-build failed due to an egg being created?

### ISSUE THREAD

**Issue by hainm** [conda/conda-build#1191]
from this issue: https://github.com/conda/conda-build/issues/1185#issuecomment-238144989

My issue: (a part of the error log)
========================

```bash
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all 
dependencies in the
 meta.yaml  url=https://pypi.python.org/packages/source/c/certifi/
certifi-2016.8.2.tar.gz#md5=004ae166985d3a684bcac5368e22ed63r
Command failed: /bin/bash -x -e /home/travis/miniconda/conda-bld/work/conda_build.sh
Using Anaconda API: https://api.anaconda.org
```

Full travis build log (https://s3.amazonaws.com/archive.travis-ci.org/jobs/150530498/log.txt)

Versions
=======
`setuptools 25.1.6`
`conda-build-1.21.11`

Solution (temporarily?) 
=================

from @msarahan
> You probably need to change your python setup.py install line to python setup.py install --single-version-externally-managed --record=record.txt so that the egg does not get created.

**Comment by hainm** [comment]
it's likely a setuptools issue. 

We have fine build with `setuptools-23.0.0` and `conda-build-1.21.11`

**Comment by msarahan** [comment]
Thanks @hainm - please reopen this issue or file a new one if you come across this again in conda-build.
