### ISSUE TITLE
Invalid Python/NumPy selector

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1202]
So I tried to `skip: true  # [np110]` in the `build` section of `meta.yaml`, but it came back as an invalid selector. :confused: Though apparently comparisons are allowed. It would be nice if things like `np110` were interpreted as `np==110` as might be reasonably expected.

**Comment by jakirkham** [comment]
Related to this is Python selectors that are out of scope (e.g. `py36`). Against it would be nice to interpret that as `py==36`.

**Comment by sebastian-luna-valero** [comment]
Following up on this issue, the `py36` preprocessing selector is not still available in the docs:
https://conda.io/docs/building/meta-yaml.html?highlight=selectors#preprocessing-selectors

but can be used?

**Comment by msarahan** [comment]
No, this is a train wreck waiting to happen.  Package names can have numbers in them (hdf5, proj4), and splitting is all but guaranteed to screw up.

This will not be done while I'm maintaining this project.  You can use comparison operators, and considering that any variable from conda_build_config.yaml is fair game, the field is pretty large.

I have no plans to add py37 or any future hardcoded selector here.  I will not remove the existing ones, though.
