### ISSUE TITLE
setuptools package egg_info suffix contains python version, if python=no_arch

### ISSUE THREAD

**Issue by marscher** [conda/conda-build#1209]
I've seen you are doing some post processing for **pycache** etc to set the correct python version for pure packages in link.py

However the .egg_info directory created with setuptools egg_info  contains the Python version which leads to dependencies can't be resolved (the dependency is installed, but the major.minor versions of egg_info makes easy_install think it is not there).

I worked around this by creating a universal wheel and install it in build.sh:
$PYTHON setup.py bdist_wheel --universal
$PYTHON -m wheel install dist/*

Another solution seems to add a renaming function for egg_info in link.py

I have to admit that this is maybe a rare use case. The setup of a depending Python package is using automatic dependency resolution, which will brake conda-build, since setup.py will then try to download/install the no_arch package again.

**Comment by msarahan** [comment]
Thanks. Noarch improvements are on our short to mid term timeline. We will factor this issue in those discussions.
