### ISSUE TITLE
Allow cloning without submodules

### ISSUE THREAD

**Issue by whitequark** [conda/conda-build#1210]
Currently, submodules are always cloned without caching. Sometimes, external projects include submodules for compile-time optional components, and these submodules can be extremely large (e.g. Rust and LLVM).

It would be great if conda-build allowed turning off passing `--recursive` to `git clone`. Even better if the submodules were cached as well, but it's not as critical.

**Comment by mingwandroid** [comment]
I have submodule caching (and a fix for using relative paths for submodules) here:

https://github.com/mingwandroid/conda-build/commit/41854c74efdd81c7bf31a10d379782dc6c0b3991

I need to finish writing the tests for it though.
