### ISSUE TITLE
Conda build skeleton pypi does not select the newest version

### ISSUE THREAD

**Issue by ajdes** [conda/conda-build#1214]
conda-build 1.21.11 on osx

`conda skeleton pypi pg8000`
selects version 1.9.9, the newest version is 1.10.6

As far as I am aware conda skeleton automatically selects the newest version via version numbering.  Assuming this is the case (and there is not other logic at play), it seems to not be comparing versions correctly, i.e. 1.10.6 > 1.9.9

Manually specifying version 1.10.6 seems to work correctly
`conda skeleton pypi pg8000 --version 1.10.6`

**Comment by msarahan** [comment]
What version of conda build?

**Comment by ajdes** [comment]
Updated the ticket

**Comment by msarahan** [comment]
The version sorting is really primitive: https://github.com/conda/conda-build/blob/master/conda_build/pypi.py#L309-L338

It just sorts things as strings, then picks the last one.  It works for a surprising number of things, but I think it falls over when you roll from x.9.x to x.10.x.

I'll leave this open, but I don't have time to work on it right now.  PR's welcome in the meantime.

**Comment by ajdes** [comment]
Does this only affect 'conda skeleton' or other version checks as well?  Its pretty common to have a major/minor version which is >= 10.
