### ISSUE TITLE
implement conda inspect linkages on windows

### ISSUE THREAD

**Issue by jankatins** [conda/conda-build#1217]
dumpbin is probably not as easy to use as ldd (which provides full paths and not only filenames)  but at least it provides the files it's linked against:

```
c:\data\external\pydata\matplotlib (newer_conda_packages)
λ set "DUMPBIN=%VS140COMNTOOLS%\..\..\VC\bin\dumpbin.exe"

c:\data\external\pydata\matplotlib (newer_conda_packages)
λ "%DUMPBIN%" /DEPENDENTS lib\matplotlib\_png*.pyd
Microsoft (R) COFF/PE Dumper Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file lib\matplotlib\_png.cp35-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    zlib.dll
    MSVCP140.dll
    python35.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll

  Summary

        1000 .data
        1000 .gfids
        2000 .pdata
        8000 .rdata
        1000 .reloc
        1000 .rsrc
       19000 .text
```

If I read https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396, then in the case of the `inspect linkage` case (in an activated environment), this becomes:

1.) get the dll files form that output
2.) filter for some windows host specific ones (kernel32.dll, more?)
3.) do a `where <xyz.dll>` or `from ctypes.util import find_library; find_library("zlib") -> the returned path must be in the currently activated environment

**Comment by msarahan** [comment]
This would be a very nice addition.  I'm too swamped to do this right now, but if you have time for a PR, I'd be very excited to see it.
