### ISSUE TITLE
Fatal Error LNK1181 failed to find "Files.obj"

### ISSUE THREAD

**Issue by Luindil** [conda/conda-build#1233]
Hi,

I am trying to build some packages on windows which need the VS compiler. I always get the error:

LINK : fatal error LNK1181: Eingabedatei "Files.obj" kann nicht geöffnet werden.
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Clemens\Anaconda3\envs\_build\libs /LIBPATH:C:\Users\Clemens\Anaconda3\envs\_build\PCbuild\amd64 /LIBPATH:C:\Users\Clemens\Anaconda3\envs\_build\Library\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\um\x64 /EXPORT:PyInit_cf_io build\temp.win-amd64-3.5\Release\fabio\ext\cf_io.obj build\temp.win-amd64-3.5\Release\fabio/ext/src/columnfile.obj /OUT:build\lib.win-amd64-3.5\fabio\ext\cf_io.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\fabio\ext\cf_io.cp35-win_amd64.lib" failed with exit status 1181

Which I guess is in principle an issue with using "" or not. If I install the packages with "python setup.py install" it works without problems.

Any Idea how to fix it? 

Best wishes

**Comment by msarahan** [comment]
This is an issue with the latest setuptools version and numpy.  See https://github.com/pypa/setuptools/issues/728 and https://github.com/pypa/setuptools/pull/739

For now, you can pin your recipes to setuptools <=23 - a fixed release of setuptools should be available soon.

**Comment by Luindil** [comment]
thank you for the fix!

**Comment by msarahan** [comment]
You're welcome. Closing this issue.
