### ISSUE TITLE
Add numpy.distutils.core to load_setup_py_data method

### ISSUE THREAD

**Issue by bladwig1** [conda/conda-build#1241]
The load_setup_py_data method in jinja_context.py will return an empty dictionary when using numpy.distutils.core.setup for the setup method.  This happens when using {{load_setup_py_data()}} tags in meta.yaml.  The fix is to add the same setup method patch to numpy.distutils.core.setup, as is done with setuptools.setup and distutils.core.setup, inside of load_setup_py_data.

**Comment by msarahan** [comment]
Thanks.  Could you please suggest a test case for this, to make sure I get it right?

**Comment by bladwig1** [comment]
Hi Mike,

I patched my local copy of jinja_context.py located in
lib/python2.7/site-packages/conda_build (conda-build 1.21.0) to get around
the problem here, but this doesn't appear to match the jinja_context.py
located on github. So I'm either looking in the wrong place, or there have
been quite a few changes made since the 1.21.0 release.  In any case, I
have attached it for reference.  I'll try to put together a simple test
soon.

Thanks,

Bill

**Comment by msarahan** [comment]
Hi Bill,

Attachments unfortunately don't make it to Github.  Do you mind sending it to me at msarahan@continuum.io, and I will integrate it?
