### ISSUE TITLE
(version 1.21.14) Config.prefix_length use within main_inspect

### ISSUE THREAD

**Issue by pelson** [conda/conda-build#1248]
Sorry if I'm missing something, but looks like ```conda_build.config.Config``` doesn't have a `prefix_length` (in v1.21.14 https://github.com/conda/conda-build/blob/1.21.14/conda_build/config.py), yet main_inspect uses it as a default value at https://github.com/conda/conda-build/blob/1.21.14/conda_build/main_inspect.py#L172

**Comment by msarahan** [comment]
Bug. Bad merge from master. The 2.0 release is slated for Monday. Can this wait?

**Comment by pelson** [comment]
Sure can. Thanks for letting me know.

**Comment by msarahan** [comment]
The 2.0 beta is out.  If you have time to test, or time to review the API, I'd highly value your input.

**Comment by pelson** [comment]
Phew! https://github.com/conda/conda-build/pull/953 is pretty substantial 😄 .
Honestly, I'm not going to be able to apply all of the updates to all of the tools that may be impacted, but in some respects that is absolutely fine by me - we can always control the version dependencies whilst we/I try to resolve any substantial incompatibilities.

@jakirkham - are you at all interested in taking some of conda-build-all and conda-smithy for a spin with conda-build 2?

**Comment by msarahan** [comment]
Yeah, it spun out of control.  Getting rid of the global config was especially far-reaching, and then hard to separate from other changes.

I know you certainly don't have time to review the whole PR.  I would still appreciate it if you took a look at just the one api.py file, and make any suggestions for additions, removals, or edits that you think would improve things.

**Comment by msarahan** [comment]
I will take on conda-build-all.  @ericdill let me know that it is pretty
broken.  I will appreciate comments on any PR, of course, but I am the
right person to do this, since I have just created all this mess (hopefully
for the better in the end).

**Comment by jakirkham** [comment]
So this particular error is going to start cropping up everywhere as there was a push to add `conda inspect linkages` in the `test` phase of every compiled build.

**Comment by jakirkham** [comment]
> @jakirkham - are you at all interested in taking some of conda-build-all and conda-smithy for a spin with conda-build 2?

I don't think I'm going to have much time ATM unfortunately. Have some friends visiting from out of town this week/weekend. Also going to be out of the office at various times over the next two weeks. In what little time I have left I'm doing a refactor/split of two of our codebases. If we are still in betas in two weeks, I can take a closer look.

**Comment by pelson** [comment]
> So this particular error is going to start cropping up everywhere as there was a push to add conda inspect linkages in the test phase of every compiled build.

Motivation to move to 2.0 :wink: 

> I am the right person to do this, since I have just created all this mess

Some might call it a mess, but I would call it progress. Keep progressing! :+1: 

The one thing to watch out for @msarahan - there are some fundamental assumptions in the *unit* tests of conda-build-all that may no longer hold with conda-build 2.0. Don't let chasing those deamons drive this - by all means use them as a way to update the assumptions and see what breaks, or alternatively completely ignore them and get the code behaving as it should. Either way, whilst I can't take much on at the moment, I'm also not keen to just dump this on you - so do enough to get value from understanding the usage. Finally - if there are use cases in there that we can move towards conda-build - I'd be happy to reduce conda-build-all's scope.

**Comment by msarahan** [comment]
> if there are use cases in there that we can move towards conda-build - I'd be happy to reduce conda-build-all's scope.

That's more for the next big release.  We're working internally to describe a concept we're calling "core dependency trees" to define and understand compatibility better.  In conjunction with #1142, I think we'll have very powerful tools to define build matrices, and conda-build will then be in a good place to take on conda-build-all's role.

**Comment by jakirkham** [comment]
>> I am the right person to do this, since I have just created all this mess

> Some might call it a mess, but I would call it progress. Keep progressing! 👍

Agreed. Don't feel sheepish about this. Having this API is going to be a huge win all around. Thanks for seeing it through.

**Comment by msarahan** [comment]
Closing as fixed in Conda-build 2.0.  If anyone *really* needs another 1.x release, let me know.
