### ISSUE TITLE
conda-build forces MACOSX_DEPLOYMENT_TARGET to 10.6

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#1269]
This means certain stuff can fail compiling, such as C thread-local variables (example: https://redmine.darktable.org/issues/11048).

**Comment by msarahan** [comment]
I agree with removing this in general, but it has been in conda-build a very long time:

```
git log -G "DEPLOYMENT_TARGET" conda_build/environ.py
```

```
commit c1d896244fd62554048957855baf9051beedc194
Author: Kale Franz <kfranz@continuum.io>
Date:   Wed Mar 30 13:29:29 2016 -0500

    clean up environ.py

commit 991491684daadb63f6b83e292c5c3820bbb0ccd8
Author: MinRK <benjaminrk@gmail.com>
Date:   Thu Feb 13 16:43:59 2014 -0800

    update MACOSX_DEPLOYMENT_TARGET to 10.6

    10.5 can cause build problems, as the SDK is rarely present.

commit fe7f773010f4c8c200298c83a4164ca404626d52
Author: Ilan Schnell <ilanschnell@gmail.com>
Date:   Fri Jan 17 13:11:35 2014 -0600

    add new files
```

Changing this could cause quite a lot of breakage.  Is there a way that you would suggest adopting this change to minimize such breakage?

**Comment by pitrou** [comment]
Since apparently this is meant to appease `install_name_tool`, perhaps only set it when invoking that executable? Or does it need to be set to the same value accross the entire build process?

**Comment by msarahan** [comment]
@mingwandroid do you understand the implications of this?  My gut feel is that you only get the full compatibility guarantee if it is set across the entire build process.

This is a setting that preferably should be set on a per-build-system basis, not conda-build wide, for sure.  We need to have that setting in place in the major build systems (internal anaconda, conda-forge, bioconda, omnia, probably more that I'm missing) before this is a relatively "safe" change.

CC @ilanschnell @jakirkham @pelson @johanneskoester @bgruening @marscher

**Comment by mingwandroid** [comment]
AFAIK, it's not as simple as the SDK version. TLS via __thread on Apple is a minefield, see for example: http://stackoverflow.com/a/23850891/3257826

We need to get on top of our compiler situation by building our own.

**Comment by pitrou** [comment]
Well, by bumping the OS X deployment target, TLS works here (builds and tests pass).
Note I'm talking about C TLS, not C++ (i.e. the non-standard `__thread`).

**Comment by mingwandroid** [comment]
Good. I'm +1 for making it 10.7 for sure.

**Comment by marscher** [comment]
thanks for the notification @msarahan. Is there a way to override this setting?
I think 10.7 is a sane setting. Also ping @jchodera, @peastman

**Comment by msarahan** [comment]
@marscher If you set the variable in build.sh, you will be overriding this setting.

**Comment by ocefpaf** [comment]
> We need to get on top of our compiler situation by building our own.

:heavy_plus_sign:  :100:

**Comment by pitrou** [comment]
Apparently conda-build allows setting environment variables in the recipe (http://conda.pydata.org/docs/building/environment-vars.html#inherited-environment-variables ), but in the source code it appears they get overwritten with hardcoded variables such as `MACOSX_DEPLOYMENT_TARGET`...

Also, from the doc it's not obvious if the `script_env` variables only apply to the build script, or also to the test script.

**Comment by msarahan** [comment]
For the sake of others here, pasting this from Flowdock:

if you follow this https://github.com/conda/conda-build/blob/master/conda_build/build.py#L773 through, then you end up here: https://github.com/conda/conda-build/blob/master/conda_build/environ.py#L292 - script_env applies to both build and test environments.

Hardcoded variables overriding script_env is a bug, and I'll fix it.

**Comment by jakirkham** [comment]
> This is a setting that preferably should be set on a per-build-system basis, not conda-build wide, for sure. We need to have that setting in place in the major build systems (internal anaconda, conda-forge, bioconda, omnia, probably more that I'm missing) before this is a relatively "safe" change.

Should `MACOSX_DEPLOYMENT_TARGET` just be a whitelisted environment variable with a default of 10.7 then? That would make it easy to set in the build system without having copy-pasta weaving through all recipes.

**Comment by msarahan** [comment]
Yes, I think that sums it up well.  I might be able to work on this later this week, but no promises.

**Comment by jakirkham** [comment]
If you don't have time, I'm pretty motivated to solve this. Can send a PR once I have some time. Should be pretty simple I hope.

**Comment by jakirkham** [comment]
Added in PR ( https://github.com/conda/conda-build/pull/1561 ).
