### ISSUE TITLE
__conda_version__ deprecation warning in conda build 2.0.0

### ISSUE THREAD

**Issue by rvianello** [conda/conda-build#1295]
Hi,

support for getting the post-build metadata from txt files is apparently still present in conda build 2.0.0, but the deprecation warnings still refer to this version ("Deprecation warning: support for __conda_version__ will be removed in Conda build 2.0").

were these changes postponed? and if so, to which version? 

Thank you very much in advance,
riccardo

**Comment by msarahan** [comment]
These changes have been postponed, probably until the next major version.  That's probably 1-2 months away.

**Comment by rvianello** [comment]
Thanks for the clarification @msarahan
