### ISSUE TITLE
Python 3 packages missing __pycache__ have .pyc

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1301]
Seeing a number of occurrences of packages built on Python 3 with `conda-build` that have `.pyc` files instead of `__pycache__` directories. This is actually causing a world of hurt in some cases as it results in other packages potentially containing `__pycache__` directories for their dependencies due to our compilation of all Python files in the build directory. In turn this results in challenging to debug problems like this one ( https://github.com/conda-forge/conda-smithy/issues/289 ).

xref: https://github.com/conda-forge/setuptools-feedstock/issues/18

**Comment by jakirkham** [comment]
Should add this is most acute on Python 3.5 in particular. Not really seeing this with Python 3.4.

**Comment by msarahan** [comment]
I think I'm just going to gut the bit that tries to get rid of the pycache folder.
