### ISSUE TITLE
prefix too long error when building package for Python 2.6

### ISSUE THREAD

**Issue by pavoljuhas** [conda/conda-build#1306]
After updating to conda-build 2.0.0 an attempt to build a package for Python 2.6 on Mac OS X fails as follows:

```shell
$ CONDA_PY=26 conda build the-recipe-directory
...

Error: PREFIX too long: 255 characters, but only 128 allowed
Error: post-link failed for: openssl-1.0.1k-1
```

This happened for a Python-only package so I tried to add to my meta.yaml
```
build:
  binary_relocation: False
```
however the result was the same.  For more details on conda-build failure with Python 2.6 see the travis log at https://travis-ci.org/pavoljuhas/diffpy.utils/jobs/156885496.

**Comment by msarahan** [comment]
Unfortunately, the problem occurs because the prefix that conda-build asks conda to create for it is too long.  This is complicated by the fact that openssl has its own legacy specialized program to do prefix replacement.  I will catch this error and act accordingly, but I also must warn you that Python 2.6 is not, and has not been an officially supported platform for some time now.

**Comment by msarahan** [comment]
To be clear, I am going to fix this.  I'm only mentioning a lack of 2.6 support for conda/anaconda as a whole.  If you have need of 2.6 and are going to maintain it, go for it.  It's just that things like openssl may not get updated, and may not work, as we see here.  In this case, I can fix conda-build, but I don't know what else you might find.

**Comment by pavoljuhas** [comment]
@msarahan - this seems to be still broken.  The most recent python-2.6.9-1 requires openssl-1.0.1k-1 which will crash upon the prefix/relocation tricks in conda build - see the build log at https://travis-ci.org/pavoljuhas/diffpy.utils/jobs/161930569.

Strangely, if I require "openssl >=1.0.2h" in meta.yaml, the build environment would use python-2.6.9-0 and the build would proceed successfully - https://travis-ci.org/pavoljuhas/diffpy.utils/jobs/161933427.
This however only works on Mac OS X.  On Linux the combination of recent openssl and python 2.6 leads to unresolvable dependencies - https://travis-ci.org/pavoljuhas/diffpy.utils/jobs/161933422.

It seems the special prefix handling for openssl in conda build does not work as intended.  If Python 2.6 must be limited to openssl-1.0.1, maybe the easiest is to release "openssl-1.0.1L", which would be built with whatever prefix lengths are needed in conda build.
