### ISSUE TITLE
generic/native noarch packages

### ISSUE THREAD

**Issue by soapy1** [conda/conda-build#1307]
meta.yml should support a noarch option like:
```
build:
    noarch: true
```

If noarch is true
* it should put the package in $CONDA_ROOT/conda-bld/noarch
* it should add the key/value pair `noarch: True` to info/index.json

If noarch is false
* don't change the default behaviour

**Comment by kalefranz** [comment]
@msarahan Need to start moving forward with more robust noarch support.  Are you ok with this as a first step?

**Comment by msarahan** [comment]
Sure.  Take a look also at the work that @mingwandroid has already done in https://github.com/conda/conda-build/pull/1285

**Comment by kalefranz** [comment]
Oh wow looks like it's already almost done.  Cool!

**Comment by mingwandroid** [comment]
I'm not sure about the need for:

`it should add the key/value pair noarch: True to info/index.json`

.. arguably that's redundant information? Or is there already a `noarch` key that I'm not setting correctly?

**Comment by kalefranz** [comment]
@mingwandroid, @msarahan and I just discussed some of this. We should all catch up sometime.

**Comment by mingwandroid** [comment]
Sure, I just went ahead and coded it as I had a pressing need to use it :-) It was pretty simple anyway.

**Comment by msarahan** [comment]
Closing as fixed by #1285 and #1334
