### ISSUE TITLE
conda-build=2.0.0 doesn't doesn't add noarch builds to noarch dir

### ISSUE THREAD

**Issue by canavandl** [conda/conda-build#1317]
From the Bokeh issue tracker:

https://github.com/bokeh/bokeh/issues/5084

>We build noarch conda packages for our releases. Using conda-build=2.0.0, a conda-bld/noarch/ directory is created and a repodata.json file is added, but no zipped build is added.

Here's the Travis log with the line noting that the build file is missing:
https://travis-ci.org/bokeh/bokeh/jobs/157146984#L1793

We rolled back versions and pinned to 1.21.14 as a stop gap, but would like to resolve this issue.

**Comment by msarahan** [comment]
Thanks for the report.  I think #1297 should fix this, but I'll appreciate your feedback on that.

**Comment by canavandl** [comment]
Yes - this issue appears to be resolved in master (f4eb973e0bb5fd1cd3a3039ae9282e8ad5818bd4). 

I'll mark this as closed - thanks @msarahan
