### ISSUE TITLE
Only info got packaged?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1335]
Had some packages that have no `Lib` on Windows and are merely the `info` directory turned into a tarball. Probably worth investigating. Please see issue ( https://github.com/conda-forge/olefile-feedstock/issues/1 ).

cc @pmlandwehr @conda-forge/olefile

**Comment by msarahan** [comment]
This is concerning, but until conda-forge updates to conda-build 2, or until someone decides to pay Continuum to maintain old versions of conda-build, I can't spare the time.

**Comment by jakirkham** [comment]
My current theory is this was a one time spurious issue, but the severity made it worth reporting.

**Comment by msarahan** [comment]
Thanks, I sure hope so.  I'll be happy to investigate this issue should it recur with the current version of conda-build.

**Comment by jakirkham** [comment]
AFAICT rebuilding fixed it. So let's chalk it up to a fluke, but be mindful that a similar error mode could occur again in the future. Feel free to close this.

**Comment by msarahan** [comment]
Thanks.  Closing for now.  Happy to reopen if issue should recur.

**Comment by jakirkham** [comment]
Here's another occurrence ( https://github.com/conda-forge/pypdf2-feedstock/issues/2 ) of this issue. Not that I'm expecting anything to be done about it ATM. Merely noting it for reference.

**Comment by msarahan** [comment]
Thanks. Good to keep track of these.

**Comment by jakirkham** [comment]
FWIW (not that two cases make for a great sample size) both cases occurred ~3mos ago using `conda-build` version `1.21.2`. Maybe there is some old issue that we are only now discovering that has since been fixed. Does anything like this come to mind?
