### ISSUE TITLE
Conda convert to windows does not create `Scripts/*-script.py`

### ISSUE THREAD

**Issue by desilinguist** [conda/conda-build#1346]
With the older versions of `conda-build`, converting a linux package to `win-64` created `Scripts/foobar-script.py` in addition to `Scripts/foobar.bat` for an entry point `foobar`. However, with the latest version of `conda-build` (v2.0.1), those files are no longer created which leads to the entry points not working on Windows.

**Comment by msarahan** [comment]
Thanks for the report.  I'll make sure it's fixed for the next bugfix release, due probably tomorrow.
