### ISSUE TITLE
Mentioning Conda on Backstroke's home page

### ISSUE THREAD

**Issue by 1egoman** [conda/conda-build#1376]
Hello!

I noticed that you've added Backstroke to this repo. I'm its developer, and I'm currently working on a webpage for the service. Would you mind if I mention Conda as using Backstroke? Here's what it would look like:
<img width="760" alt="screen shot 2016-09-20 at 8 00 24 am" src="https://cloud.githubusercontent.com/assets/1704236/18669356/9f78c9e0-7f08-11e6-8402-a03b9f9749cf.png">

Thanks for using Backstroke,
Ryan

(I'm pretty sure @msarahan is a maintainer, so tagging in hopes you can answer this)

**Comment by msarahan** [comment]
Hi @1egoman, I actually have never gotten it to work.  I like the idea, and if you can help me get it to work, I think adding the logo to your site would be fair.

**Comment by 1egoman** [comment]
@msarahan Ok. DId you get any errors after adding http://backstroke.us as a webhook to this repository?

From what I can tell from my end, it seem to be working. Here's a pull request Backstroke made in one of this repository's forks: https://github.com/gabm/conda-build/pull/1

**Comment by msarahan** [comment]
Sorry, I have been watching for these in my own fork, and have not seen them.  There are no errors reported in this repo's webhook settings.

I have tried to re-create the webhook using what looks to be your new website, but I cannot seem to enable it.  It always just says "server error."  I tried removing the existing webhook on conda-build, but it had no effect on this server error.

**Comment by 1egoman** [comment]
@msarahan AWS was giving me trouble all morning. Sorry to have to ask, but give it a another try.

Because of the way it was doing things, Backstroke chunked updates to forks in small groups to conserve api requests. This means that forks that were made early in a repository's history could take a while to be updated. Part of the reason I wrote the new web interface for Backstroke was to alleviate this problem (since oauth can be used, conserving requests is no longer a priority), so this should no longer be an issue. That being said, I haven't gotten an opportunity to use Backstroke in an environment with more than a few forks, so I really value any feedback you can give me in regards to how Backstroke works in a large scale environment.
