### ISSUE TITLE
Command line options dropped in transition to 2.0

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#1382]
The options ``--setup-options`` and ``--pin-numpy`` added in #680 were inadvertently dropped in the refactor of the command line options. The underlying code to implement them is still there; I can do a PR this weekend to fix.

**Comment by msarahan** [comment]
Argh, sorry about that.  Merge conflicts and such.  I think it's better if I do it, unless you just want to.  In particular, we should add tests in test_cli.py to ensure that these options are available.

**Comment by msarahan** [comment]
Looking back, I probably changed the tests to use the API, but did not keep the CLI integration test part of it.  Sorry again.

**Comment by mwcraig** [comment]
@msarahan -- no worries! You are right about the tests -- they check the API (which works) but not the cli. Completely fine with me if you want to take care of it.

**Comment by mwcraig** [comment]
I will have time this weekend though..so if it gets to Sunday afternoon and you haven't had a chance, I'll open PR.

**Comment by sooneecheah** [comment]
https://github.com/conda/conda-build/pull/1384  <- this is the region of code that appears to be causing the issue. Let me know whether accessing the attributes of the config object is an appropriate patch strategy - alternatively the entire config object would need to be passed into the skeletonize function and CLI options extracted in there.

**Comment by mwcraig** [comment]
I think #1384 is addressing a separate problem. The issue here is that some options available in `api.skeletonize` are not recognized as command line arguments.

**Comment by sooneecheah** [comment]
Hey @mwcraig - Whoops - you're right. The PR addresses the CLI arguments being ignored. Apologies!

**Comment by mwcraig** [comment]
@sooneecheah -- no worries! Glad you caught the other issue too.

@msarahan -- PR to close this is at #1387

**Comment by mwcraig** [comment]
Actually, I spoke too soon. #1384 *is* relevant because even when I add the command line arguments they don't get passed on to skeletonize.

Looks to me like the root cause is in [`main_skeleton`](https://github.com/conda/conda-build/blob/master/conda_build/cli/main_skeleton.py#L61):

```python
    for package in args.packages:
        api.skeletonize(package, repo=args.repo, config=config)
```

None of the arguments are *ever* passed in to [`api.skeletonize`](https://github.com/conda/conda-build/blob/master/conda_build/api.py#L163).

@sooneecheah -- I'd guess a better fix in #1384 might be to modify `main_skeleton` so that the API of `api.skeletonize` doesn't change, but @msarahan  will need to weigh in.

**Comment by sooneecheah** [comment]
@mwcraig Sure - I was tossing up whether to make main_skeleton pass the arguments, or to have the api extract the arguments from config; I'm relatively new to this repo so I'll wait for @msarahan to hear re: the preferred approach.

**Comment by msarahan** [comment]
If the arguments are things that are specific to skeletonization, then I'd make them arguments.  Otherwise, if they are shared in any way with other functions, I'd make them members of the config object.  In this case, it seems to me like they should be arguments, not config members.

Thanks @sooneecheah @mwcraig for looking into this!  I'm happy to review and merge whenever you're ready.

**Comment by msarahan** [comment]
In the interest of not modifying the API right now, I have merged #1384 as is.  Thanks both of you.

**Comment by mwcraig** [comment]
I'm a little confused...doesn't #1384 modify the API since it modifies the signature of `api.skeletonize`, and arguments that would have been passed from `api.skeletonize` will now be ignored unless they are added to config?

**Comment by msarahan** [comment]
Don't worry about it.  I wanted to capture both of your PRs, and I'll work out the inconsistencies.

**Comment by sooneecheah** [comment]
Hey @msarahan @mwcraig, thanks for going through this - time differences are a killer. My understanding of #1384 was that given the CLI rolls up all the arguments into the config object, the easiest way to handle the skeletonize API was to take in the config object and any keyword arguments handed to it, before merging and resolving any conflicts between the two into an updated config object (the merging process was already there - it favours kwargs over config). Options relevant to the skeltonizer (i.e. pypi, cpan, cran etc) are then extracted from the config object before being handed into the repo specific skeletonizers as keyword arguments.
