### ISSUE TITLE
build/script_env is undocumented

### ISSUE THREAD

**Issue by flub** [conda/conda-build#1385]
Hi,

On the published documentation at http://conda.pydata.org/docs/building/meta-yaml.html the build/script_env setting is undocumented.  I would create a pull request but I don't actually know where the source for the docs live, I may have missed something obvious.

**Comment by msarahan** [comment]
Thanks for raising this.  The docs for conda and conda-build live together at https://github.com/conda/conda-docs - not at all obvious, sorry.

In particular, I think the file to change is: https://github.com/conda/conda-docs/blob/master/docs/source/building/meta-yaml.rst

If you have time, a PR would be much appreciated.

**Comment by flub** [comment]
Oh thanks.  Apologies for failing to spot that, I even had a (very old) checkout.  Raised https://github.com/conda/conda-docs/pull/356
