### ISSUE TITLE
environ undefined in jinja2 template environment

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1386]
Originally reported by @marscher in https://github.com/conda/conda-docs/pull/355

Copy of my comment from there:

I'm pretty sure that environ should be defined, and the fact that it isn't is a regression in conda-build. The difference between os.environ and environ is that the latter is a more cherry-picked subset of os.environ, plus additional values, such as the GIT_* variables.

**Comment by marscher** [comment]
Docs should be covered by regression tests :)

**Comment by msarahan** [comment]
Indeed.  We do have tests for this, though we need more explicit tests that duplicate the documentation examples.

https://github.com/conda/conda-build/blob/aa566bd1e70edb86ff841d9d3161265b0f948cbe/tests/test-recipes/metadata/source_git_jinja2/meta.yaml

Doc examples have a place in https://github.com/conda/conda-build/blob/aa566bd1e70edb86ff841d9d3161265b0f948cbe/tests/test_published_examples.py

**Comment by msarahan** [comment]
Added regression tests, but did not encounter this issue in the process.  I'm going to close this issue for now, but please reopen it or post a new issue if you have an example that demonstrates the issue.
