### ISSUE TITLE
Conda-build and conda-versions should be included in package meta-data

### ISSUE THREAD

**Issue by srossross** [conda/conda-build#1419]
I'm trying to update and build an older package for a client and I can not because of errors. I need to figure out the context in which this package was originally built.

cc @csoja  re Anaconda-Platform/anaconda-server#2949

**Comment by srossross** [comment]
There are also no recorded versions for the build requirements
```
requirements:
  build:
    - python
    - setuptools
    - nodejs
    - gulp

```

**Comment by msarahan** [comment]
Good ideas.  I have wanted to pin the build dependencies in the included meta.yaml for some time.  This is good motivation to get around to it.  See #1407 for recording conda/conda-build versions.  Please comment there if you have ideas to do that differently.
