### ISSUE TITLE
change log out of date

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1420]
conda-build is at 3.x, and the changelog seems stuck at 2.0.2.  If it's not going to be updated, it should be removed.

**Comment by janssen** [comment]
Sorry, my mistake.  I was confusing the conda version with the conda-build version.

**Comment by kalefranz** [comment]
@janssen Conda has been at >4.x for many months now. Are you still using a 3.x version of conda? If so, and you have explicit reasons, would love to jump on a quick chat with you at some point.
