### ISSUE TITLE
documentation on CONDA_BUILD_STATE is missing

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1421]
At least, I can't find it.

**Comment by msarahan** [comment]
Yes, sorry.  I haven't written it.  There are presently 3 potential states: RENDER, BUILD, TEST.  I think besides those values, this feature is pretty self-explanatory.  I'm too swamped to do the docs right now, but I'd appreciate a PR if you have time.

**Comment by msarahan** [comment]
Documented at https://github.com/conda/conda-docs/pull/367 - closing.
