### ISSUE TITLE
Setting VC version

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1445]
It would be great if we had a general way (outside of Python versions) to set the VC version in `conda-build`. Here are some of things that would be desirable.
- [ ] `--vc` flag that takes a version (e.g. `--vc 9` for VC 2008)
- [ ] `CONDA_VC` environment variable to set the VC version (e.g. `set CONDA_VC=9` for VC 2008).
- [ ] Support year in both of the above (e.g. `--vc 2008` for VC 2008 or `set CONDA_VC=2008` for VC 2008).
- [ ] Possibly auto-configure feature tracking. (mixed feelings ATM)
- [ ] Baking of a [`vc`-style package](https://github.com/conda-forge/vc-feedstock/blob/d4235305592d24d3c575ca69c5c6a80e4e3e435e/recipe/meta.yaml) into `conda-build`.

cc @jjhelmus @pelson @msarahan

**Comment by jakirkham** [comment]
Any thoughts on these, @msarahan ? I suspect many of them should be trivial to do and would be very helpful.

**Comment by msarahan** [comment]
I see the value in this and would readily accept a PR, but do not have time to do this myself right now.

**Comment by msarahan** [comment]
I believe this is resolved with conda-build 3.  Closing.  Please correct me if I'm wrong.
