### ISSUE TITLE
permissions errors cause hang in conda-build 2.0.4 on win

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1449]
I'm trying to build my goodstuff package on Windows 7, with conda-build 2.0.4.  In fact, here's the conda info:

```
               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.4
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : C:\Miniconda2  (writable)
    default environment : C:\Miniconda2
       envs directories : C:\Miniconda2\envs
          package cache : C:\Miniconda2\pkgs
           channel URLs : https://goodstuff.parc.xerox.com/conda/win-64/
                          https://goodstuff.parc.xerox.com/conda/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Miniconda2\.condarc
           offline mode : False
```

And the build just hangs.  I've put debugging statements in my bld.bat and the top of my setup.py file, and none of them are emitted.  I've added the --debug flag to conda build; nothing.  Here's what I see:

`conda build --debug goodstuff --no-test`

That's it.

**Comment by janssen** [comment]
Reverting back to conda-build 1.21.14 works, though.

**Comment by msarahan** [comment]
How long have you waited?  Conda-build tries to clean up the trash, and there has been a long-standing bug that conda-build 2.0.4 fixed, in which the trash was never deleted.  It could just be taking a really long time to clear out several hundreds of thousands of files.  I have seen it take several minutes to delete this folder using just Windows Explorer.

**Comment by msarahan** [comment]
PS: the folder it is clearing is ```<miniconda or anaconda root>/pkgs/.trash``` by default.

**Comment by janssen** [comment]
Well, three hours seems a bit much.

I think the problem is related to the fact that the account which installed Miniconda2 on the machine isn't the same account that's attempting to build (it's a Jenkins buildbot).  When I build using the same account that installed Miniconda2, it builds OK.  Shouldn't the build envs be in %TEMP%, instead of under C:\Miniconda2\?

**Comment by msarahan** [comment]
They certainly can be, but they are not by default.  I'm mixed on whether they should be.  It's definitely better for permissions, but this would also be a major change to what people are used to.

You can change the root directory with the ```--croot``` argument.

I'll see if there's any way that we can check permissions and error out rather than hanging.

**Comment by janssen** [comment]
I don't have physical access to the console, but this kind of feels to me like a problem where there's some Windows pop-up on that console, waiting for an answer.  I think that if it were a permissions problem, we'd get errors, wouldn't we?  It wouldn't just hang.  But I'm seeing nothing which indicates how far conda-build is getting, here.  Is there perhaps a top-secret internal env var I could set to make it output more?

**Comment by msarahan** [comment]
There's nothing top-secret about conda-build.  It's completely open source.  There are no environment variables for more debugging that I know of, though - just the ```--debug``` flag.

The file deletion happens at https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1049

It seems very unlikely that an error console would be opened by that command.  I'd be very interested to know if you can set a breakpoint just before then and hit it (or if the hang happens before then).  My hunch about this file deletion is only that that piece of code changed in 2.0.4.  This could be something completely different.

**Comment by janssen** [comment]
Properly speaking, we don't know that my problem is being caused by a permissions error, I think.  What is the "file deletion" you mention?

**Comment by msarahan** [comment]
The file deletion I'm referring to is clearing out the trash folder.  Windows is a difficult platform in that you can't delete a file that is in use.  You can, however, move or rename it.  This is critical, because otherwise conda would not be able to update python or itself.  Conda moves files into the ```<miniconda/anaconda root>/pkgs/.trash``` folder.  Conda-build tries to clear these out at the beginning of each build.  This was not functional from conda versions 3.19 or so, and is not functional in conda now.  Conda-build 2.0.4 replaces conda's cleaning function with a lower-level call to cmd.exe builtin del.  That's the line I pointed out.

The fact that conda-build works fine as the user under which conda was installed, but does not for another user points strongly to a permissions issue.  You're right, we haven't completely isolated it, but it's a reasonable place to start.

**Comment by janssen** [comment]
If I modify my buildbot build to "conda build goodstuff --croot %TEMP%", would that avoid the permissions exception?  Probably not, because it wouild still try to clear that .trash folder?

**Comment by msarahan** [comment]
Yes, that's accurate.  That might be a good test.

**Comment by janssen** [comment]
OK, I went into c:/Miniconda2/Lib/site-packages/conda-build/build.py and added a print statement at the indicated point.  Don't see it when I run the buildbot.  But is that the correct file to edit?

**Comment by msarahan** [comment]
Assuming that's the Miniconda install location, that should be the right
file to edit.  If print statements are not showing up, maybe it's hanging
before that point?  I sometimes also resort to more drastic debugging when
print statements either don't show up or otherwise aren't enough:

import pdb; pdb.set_trace()

**Comment by janssen** [comment]
OK, when I add --croot=/tmp, I get this:

```
+ conda build --debug goodstuff --no-test --croot=/tmp
Deleting trash...
Cloning into bare repository 'C:/Windows/TEMP\git_cache\githubenterprise.parc.com\goodstuff\goodstuff'...
```

Progress!

**Comment by msarahan** [comment]
And then it hangs?

**Comment by janssen** [comment]
So, the hang seems to have been somewhere before the trash is emptied, and now I'm past that, and hanging because the clone is failing.

**Comment by msarahan** [comment]
I see that your temp folder is in the Windows folder.  Do you have write permissions there?

You might want to set croot a little differently:

```--croot %TEMP%```

**Comment by janssen** [comment]
After fixing the clone issue, it proceeds to build.  If I remove --croot, it hangs again.

**Comment by janssen** [comment]
Hmmm, it's running as a Windows service, which is (I presume) why /tmp (this is a bash script, using Git's bash, so %TEMP% wouldn't evaluate properly).  I'll try your suggestion, with $TEMP.

**Comment by janssen** [comment]
Interestingly enough, reverting to conda-build 1.21.7, and removing the --croot flag, seems to work OK.

**Comment by msarahan** [comment]
That is interesting.  Sorry I don't have more time to investigate this right now.  If you narrow it down to a particular section of code, or if you have a proposed fix, I'll be happy to take a look.

**Comment by janssen** [comment]
I've simplified things quite a bit, mainly by adding a private win-64 channel, and now everything works with 2.0.7.  Let's close this for now.
