### ISSUE TITLE
build 2.0.4 fails if "conda" is not in Path

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#1450]
`conda-build` executes come `conda` subprocesses that fail if `conda` is not in `$PATH`. You should prepend it with `join(sys.prefix, 'bin')` or `dirname(sys.executable)`.

Example error locations:
- https://github.com/conda/conda-build/blame/master/conda_build/build.py#L298
- https://github.com/conda/conda-build/blame/master/conda_build/build.py#L317

**Comment by mingwandroid** [comment]
Conda should always be on PATH.

**Comment by sscherfke** [comment]
I don’t see any reason why this should be the case. In some build-scenarios (or if you need/want to have multiple conda installations in parallel), it makes no sense to always have `conda` in `$PATH`. Instead, you explicitly point to the conda executable when you call it.

**Comment by mingwandroid** [comment]
This is the case because conda-build versions have explicit dependencies on conda versions (they are tightly coupled). Making this seem laisse-faire will lead to many bug reports due to incompatibilities.

`conda info conda-build` can be used to see these dependencies.

**Comment by sscherfke** [comment]
If you prepend `conda` with `sys.prefix` (or a similar), you explicitly call the conda that is installed in the same env that is currently running.  If you just call `conda` you (might) run an arbitrary conda that happens to be first in $PATH.

**Comment by sscherfke** [comment]
Another point: It worked without having `conda` in `$PATH` before, thus the new *patch* release breaks backwards compatibility what it should not do.

**Comment by msarahan** [comment]
I think we can fix this pretty easily.  I don't think that conda-build should necessarily require that conda be on PATH - just that it is installed in the same environment with conda-build.

Sorry for the breakage.  We don't (and probably can't) have complete coverage of all use cases, but we'll cover the ones we know from reports like these.

**Comment by hajs** [comment]
I guess that ``conda_build.os_utils.external.find_executable('conda')`` should find the correct conda executable

**Comment by mcg1969** [comment]
I just got bit by this on a customer project, and it represented a regression for us. FYI.

**Comment by msarahan** [comment]
Sorry for the breakage @mcg1969.  This will be a new integration test (running conda build with an absolute path), and a new unit test for this particular functionality.

**Comment by mcg1969** [comment]
Wonderful, thanks Michael!

**Comment by sscherfke** [comment]
@msarahan Thanks for closing all the issues so fast!
