### ISSUE TITLE
Merge problem in Numba build farm

### ISSUE THREAD

**Issue by stuartarchibald** [conda/conda-build#1451]
Numba has a workflow of building on one system with tests disabled, then testing on potentially a few another systems (for testing specialisms like CUDA). conda-build 2.0.4 fails in the Numba build farm setup with an `IOError` as it can't merge the source into the build directory because `file exists`. This ticket is a placeholder/reminder of the offline discussion  with @msarahan .

**Comment by janssen** [comment]
I'm seeing this one, too, trying to build the pyobjc prerequisites for dmgbuild.  Works fine from PyPI, fails with conda.
