### ISSUE TITLE
MetaData not filling in template from passed Config obj?

### ISSUE THREAD

**Issue by daler** [conda/conda-build#1464]
Hi - 

My goal is to identify the built output file for a recipe using the `conda_build.api` module rather than having to use a subprocess call like `conda build --output`.

It mostly works, but I'm having trouble in cases where I need to fill in jinja variables. Here's an example to show what I mean. It shows a case where I'm trying to have a custom build string to specify the Boost version, and checking the output of `api.get_output_file_path`. 

If I call `conda build . --output`, it works as expected.

(by the way this is with conda-build 2.0.6)

```python
import os
from textwrap import dedent
from conda_build.metadata import MetaData
from conda_build import api
import subprocess as sp

# To start, ensure no env var for CONDA_BOOST
os.environ.pop('CONDA_BOOST', None)

with open('meta.yaml', 'w') as fout:
    fout.write(dedent(
        """
        package:
          name: one
          version: 0.1
        build:
          number: 1
          string: {{ CONDA_BOOST }}_{{ PKG_BUILDNUM }}
        """))


# I was expecting that providing a config would fill in the build string
config = api.Config(CONDA_BOOST=1.6)
m = MetaData('.', config=config)
print(api.get_output_file_path(m))
#
# /miniconda3/conda-bld/linux-64/one-0.1-_.tar.bz2



# If we stick CONDA_BOOST into env vars, it is filled in. But the
# PKG_BUILDNUM is still not filled in
os.environ['CONDA_BOOST'] = '1.6'
m = MetaData('.')
print(api.get_output_file_path(m))
#
# /miniconda3/conda-bld/linux-64/one-0.1-1.6_.tar.bz2



# Running conda-build --output does what I was expecting
# (note: leaving CONDA_BOOST in environment for this command-line call)
print(sp.check_output(['conda', 'build', '.', '--output'], universal_newlines=True))

# return what I was expecting:
# /miniconda3/conda-bld/linux-64/one-0.1-1.6_1.tar.bz2
```

**Comment by msarahan** [comment]
This is an interesting spin on arguments to Config, but it's not the way it works right now.  You can pass arbitrary arguments to it, and they'll be stored as attributes on the config, but those are not provided in the jinja context.  They could be, but I think it might be better to provide the config object itself, and have people access its attributes for clarity and keeping the namespace small.

As for the env var example, that's probably a case of PKG_BUILDNUM never being None.  It is obtained from MetaData here: https://github.com/conda/conda-build/blob/714c1890c0ef0807648d52b6362f750baa539e54/conda_build/environ.py#L331 but that is never returned as None: https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L556-L563

I don't remember why those things in particular are special cased that way.  I want to say I've tried to return None there and it broke stuff, but I don't remember well.

Please feel free to try to hack the MetaData code to return None - then it should work.  If you fix it, I'll welcome a PR.  I'm tied up with other things for a little while.

**Comment by daler** [comment]
Thanks, I'll take a stab at the MetaData.

 > I think it might be better to provide the config object itself, and have people access its attributes for clarity and keeping the namespace small.

Can you clarify what you mean by this? Or, I guess more to the point: given the above meta.yaml and the dict `{'CONDA_BOOST': 1.6}`, can you provide a quick example of how I should be getting that dictionary into the jinja context?

**Comment by msarahan** [comment]
I think if you add

```
config=config
```

in https://github.com/conda/conda-build/blob/master/conda_build/jinja_context.py#L216-L225

it will be available in templates like:

{{ config.CONDA_BOOST }}

**Comment by daler** [comment]
Returning None [here](https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L556-L563) just filled in the PKG_BUILDNUM as "None".

Adding `config=config` [here](https://github.com/conda/conda-build/blob/master/conda_build/jinja_context.py#L216-L225) did just as you said, allowing `config` to be used within templates.

However, following those leads, I realized that really the problem was that I needed to render the recipe first. As long as I put the var in os.environ, and making no changes to conda-build, this works:


```python
import os
from textwrap import dedent
from conda_build import api
from conda_build.render import bldpkg_path, render_recipe

with open('meta.yaml', 'w') as fout:
    fout.write(dedent(
        """
        package:
          name: one
          version: 0.1
        build:
          number: 1
          string: {{ CONDA_BOOST }}_{{ PKG_BUILDNUM }}
        """))

os.environ['CONDA_BOOST'] = '1.6'
1.6'
recipe_dir = '.'
config = api.Config()
m, _, _ = render_recipe(recipe_dir, no_download_source=True, config=config)
print(bldpkg_path(m, config))
# /miniconda3/conda-bld/linux-64/one-0.1-1.6_1.tar.bz2
```

So for now I'll stick with the os.environ so that stays analogous to what the command-line is doing. 

Thanks for your help and for pointing me in the right direction!

**Comment by msarahan** [comment]
Note that you need not pass config when passing metadata, only when passing paths to recipes.  Metadata objects have a reference to a config object and you should manipulate that object directly.

**Comment by daler** [comment]
Thanks. Looks like `render.bldpkg_path` has `config` as a required arg but it's not used/needed: https://github.com/conda/conda-build/blob/master/conda_build/render.py#L68

So is `bldpkg_path(m, m.config)` the best way to do it?

**Comment by msarahan** [comment]
The better way is probably to only use functions in the api module, and
raise issues of you need more or different functionality.
