### ISSUE TITLE
Separating build and install environments

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1467]
Often the case arises (particularly with compilers) that one must have the compiler already present in order to build a new version of the compiler. This would be a really desirable thing to be able to accomplish with `conda-build`, but at present is simply not doable.

The reason being if I install the new build of the compiler into the same environment as the existing compiler we have a number of issues. The most pressing amongst them is that some files may not be included in the new compiler package as they were part of the old compiler package. As a result, we only package part of the compiler and have an unusable end product.

To solve this issue, it would be nice to have a build environment that provides us the necessary build tools, but would not actually hold the installation prefix. This environment could provide us the compiler executable, but, as it would not be in the installation prefix, should not affect our ability to have clean workable compiler package at the end.

**Comment by msarahan** [comment]
This is the same idea as having separate, standalone environments to use particular tools.  I support the idea.  It's a conda issue, though.

Here, we may be able to change the way that conda-build deals with packaging: put the build environment on path and all that, but direct $PREFIX and LIBRARY_BIN and all that to a totally separate folder, which would then be the basis for packaging.  It would solve this issue, but I fear it would break untold numbers of recipes that use/assume the current behavior of those variables.  It may be that as an intermediate, there can be new variables, and if they are used (or if some switch in meta.yaml is used), then conda-build's packaging will look to that new location and ignore the build prefix.

**Comment by msarahan** [comment]
Conda-build 3 has the notion of build and host.  When host is not present, build behaves as it always has.  When host is present, the build prefix is activated, then the host prefix is activated.  Both are active, though a hack.  Any binary not in host gets found in build.

I think this satisfies this issue.  Closing.

**Comment by notestaff** [comment]
@msarahan "Conda-build 3 has the notion of build and host" -- could you please point me to the docs for this?  I tried to find but couldn't.  Also, if you know of any sample recipes that use this, that would help too.  Thanks!

**Comment by msarahan** [comment]
https://github.com/AnacondaRecipes/python-feedstock/blob/master/recipe/meta.yaml

Docs are lacking.  In a recent internal presentation, I summarized them as:

build: Build-time dependencies.  When host is also present, think of this section as “build tools” - things that run on the native platform that can emit artifacts for the foreign platform.

host: For recipes that can be cross-compiled.  These are libraries for the foreign platform that need to be present at build time.

**Comment by jakirkham** [comment]
Sorry, but I'm really unclear on how this solved the issue raised. Maybe I need this illustrated step by step to understand. Below I have added a specific use case that motivated the issue.

Building modern versions of `go` requires a `go` for bootstrapping. There is one exception `go` 1.4 (and earlier), which can be built with `gcc`. So to resolve the bootstrapping issue one builds `go` 1.4. However one really wants a more recent copy of `go`. So for all later versions of `go` (1.5+), one must be able to install the older `go` 1.4. to bootstrap them. How does `host` and `build` help with that?

Thanks in advance for the advice.

cc @nehaljwani (who is now tackling this problem in PR ( https://github.com/conda-forge/staged-recipes/pull/4119 ))

**Comment by msarahan** [comment]
Having both packages named go may make conda build complain about things not depending on themselves.  That might need a PR to make it smart enough to also consider version and installability from current channels.  Aside from that, make a go build dependency for the old version, and make all the other deps host deps.

The host prefix is the only one considered for packaging files, so having the old go in the build prefix will prevent any need for always_include_files.

We kind of do the same thing for cmake, because it is a dependency if many of its dependencies. There, we package the cmake binary from upstream in a package called cmake-binary, and use that to break the cycle.

**Comment by notestaff** [comment]
@msarahan Is yum_requirements.txt documented somewhere?  I'm trying to add ghc (Haskell compiler), but all recent versions require ghc to already be installed.   Is the right thing then to put haskell_platform in yum_requirements.txt?   How does that work with MacOS?

**Comment by msarahan** [comment]
@notestaff yum_requirements.txt is a conda-forge concept, not a conda-build concept.  I don't know where the best source of information on it is, but you definitely won't find it here on the conda-build issue tracker.

**Comment by jakirkham** [comment]
> Is yum_requirements.txt documented somewhere? I'm trying to add ghc (Haskell compiler), but all recent versions require ghc to already be installed. Is the right thing then to put haskell_platform in yum_requirements.txt? How does that work with MacOS?

Unfortunately there isn't any documentation at conda-forge yet. It's an open issue ( https://github.com/conda-forge/conda-forge.github.io/issues/378 ). Though there are plenty of examples if you search in conda-forge. It only works on Linux. There is nothing analogous on macOS. Basically it just lists things line by line to install with `yum` and feeds it directly to `yum install`. The rest of this conversation seems best redirected to your conda-forge PR, @notestaff, wherever that might be. 😄

**Comment by jakirkham** [comment]
Admittedly some of the terminology in this issue needs to be refreshed. Namely I think we need to be talking about `host` and `build` instead of `build` and `install` IIUC. That said, this idea of separating some build time dependencies (e.g. compilers) from the install location during the build came up today in our compiler meeting. Would be nice to have this issue reopened so that we can track this. Alternatively could open a fresh issue if that would be preferred. Thoughts @msarahan?

**Comment by jakirkham** [comment]
@msarahan, this came up again in the meeting yesterday as separating `build` and `host`. Could you please reopen this issue? Thanks.

**Comment by msarahan** [comment]
As discussed yesterday, there needs to be a flag to keep these envs separate, even when build and host are the same subdir.

**Comment by jakirkham** [comment]
Thanks Mike. Feel free to edit the title and/or OP to clarify this further.
