### ISSUE TITLE
conda-build no longer generates .exe files for my scripts on Windows

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1468]
I notice that conda-build, verson 1.21.7, used to generate .exe files to invoke my scripts.  But 2.0.6 doesn't seem to do that.  I've got Python scripts, goodstuff, goodstuff-data, and goodstuff-library, which are marked as scripts in my setup.py file.  1.21.7 turns them into goodstuff-script.py and goodstuff.exe, goodstuff-data-script.py and goodstuff-data.exe, etc.  Which I found very useful.

Is there any way to get that 1.21.functionality back again?

**Comment by janssen** [comment]
Looks like this was removed by https://github.com/conda/conda-build/pull/1246/commits/d598cdbda1bbe6ce6cd8b3c49a2240f38cf4161b

**Comment by janssen** [comment]
Where would the sources for cli-32.exe and cli-64.exe be?

**Comment by msarahan** [comment]
Sorry, this does seem like a regression.  If you have a main entry point, you can use the entry points functionality instead.  I'll fix this soon - 1-2 week timeframe.

I don't actually know where the source for those exe's is.  They pre-date me by quite a lot.  It seems they may have been copied from setuptools at some point: https://bugs.python.org/setuptools/issue2

**Comment by janssen** [comment]
Unfortunately, my script files have hyphens in their name, and there's a name clash between my Python package, "goodstuff", and the Python script called "goodstuff", too.  So the entry_points feature in meta.yaml doesn't seem like it would work without some re-arranging.  If one uses that feature, would there still be a "scripts" entry in setup.py?

**Comment by janssen** [comment]
Btw, 2.0.7 would be fine.

**Comment by janssen** [comment]
The source is apparently this: https://github.com/pypa/setuptools/blob/master/launcher.c
