### ISSUE TITLE
Add ability to make multiple packages from a single meta-file

### ISSUE THREAD

**Issue by teoliphant** [conda/conda-build#148]

**Comment by pelson** [comment]
> I don't understand what this issue means? Can you give more details, or an example?

If I were guessing (at least, this is what I want):

@teoliphant is asking for the ability for a single meta.yaml to produce multiple packages (read ``package/name``). A great example of where this is useful is in producing ipython distributions which have optional components, such as producing sub package called ```ipython-notebook``. Another good reason would be for a package such as matplotlib, which is rather hefty on anaconda (~40MB), could be split into the bits that most people care about (small), and the tests (big) - one might call these ``matplotlib`` and ``matplotlib-tests``. The key though is that these come from the same source and are parts of the same build - you just want to glob the files needed for certain packages.

**Comment by msarahan** [comment]
superseded by #1338 - closing.
