### ISSUE TITLE
tar.gz automatically uncompressed by conda -> conda-build md5 check KO

### ISSUE THREAD

**Issue by afeblot** [conda/conda-build#1483]
With conda 4.2.11 (and 4.2.10) and conda build 2.0.7 (and 2.0.6), 

Building the zlib recipe from conda-recipe fails with:

MD5 mismatch: '1142191120b845f4ed8c8c17455420ac' != '44d667c142d7cda120332623eab69f40'

It seems conda:fetch.py:download() (thanks to requests) is automatically gunzipping the archive, and checks the md5 of the 2.7 uncompressed .tar (even though the created file is still named .tar.gz), whereas the md5 specified in the recipe is obviously the one of the original compressed archive.

I don't know which behavior is wanted for download(), but it's currently not consistent with conda-build.

**Comment by msarahan** [comment]
Thanks for hunting this down.  This has been very confusing.  I think the right answer is that our use of requests should not be automatically gunzipping things, and I'll try to figure out how to make that happen.

**Comment by msarahan** [comment]
CC @kalefranz

**Comment by msarahan** [comment]
http://stackoverflow.com/questions/25749345/how-to-download-gz-files-with-requests-in-python-without-decoding-it

**Comment by kalefranz** [comment]
Yup! Thanks @afeblot!

With things being gzippes all the time for web transfer, we usually want this behavior. For example when downloading the plaintext repodata.json file, the web server will typically gzip it. 

I think the solution is that if a URL ends with .gz, we turn unzip off. We also trust that the web server hasn't taken the liberty of adding an extra gzip round. (gzipping an already gzipped file)

**Comment by kalefranz** [comment]
This issue was moved to conda/conda#3798
