### ISSUE TITLE
`conda skeleton pypi` doesn't respect --version option

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1487]
_From @mickeydonkey on October 25, 2016 10:50_

my environment:
win-64
conda=4.2.11-py35_0
just try `conda skeleton pypi logbook --version 0.12.5` it gives you build recipe for  version 1.0.0

_Copied from original issue: conda/conda#3724_

**Comment by kalefranz** [comment]
_From @mickeydonkey on October 25, 2016 11:2_

this is mentioned by this [SO question](http://stackoverflow.com/questions/39869535/how-to-specify-package-version-with-conda-skeleton-pypi-command), and I checked logbook 0.12.5 release on pypi supports py35.

**Comment by msarahan** [comment]
@mickeydonkey, this should be fixed in the current 2.0.7 release.  Please update, and report back if this is still an issue.

**Comment by remram44** [comment]
This is also an issue for me. Opening a new ticket since obviously you didn't care to reopen.
