### ISSUE TITLE
Getting a "Error: no such patch:" when the field is empty

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#1490]
@msarahan I noticed that latest `conda-build` is failing when a field is empty for certain platforms. This used to work:

```yaml
  patches:
    - skip_failing_test.patch  # [osx]
    - makefile.vc.patch  # [win]
```

but now I need to add a `# [not linux]` to the ` patches` filed otherwise  I get:

```
Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: libspatialite-4.3.0a.tar.gz
Downloading http://www.gaia-gis.it/gaia-sins/libspatialite-4.3.0a.tar.gz
Success
Error: no such patch: /conda-recipes/recipes/libspatialite/

./scripts/run_docker_build.sh returned exit code 1
```

I see similar failures for tests too.

recipe: https://github.com/ioos/conda-recipes/blob/master/recipes/libspatialite/meta.yaml#L11

CI log: https://circleci.com/gh/ioos/conda-recipes/1363

**Comment by ocefpaf** [comment]
@msarahan I can confirm that this is solved in latest `master`.

**Comment by msarahan** [comment]
Thanks for the confirmation.  Any word on #1491 also?
