### ISSUE TITLE
Extra underscore in the package name before the build number

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#1491]
@msarahan latest `conda-build` is adding an extra `_` on the Linux packages, like `linux-64/proj4-4.9.3-_0.tar.bz2`. I rebuilt on all platforms using the latest `conda-build` and that happened only on Linux. See See https://anaconda.org/IOOS/proj4/files

Recipe: https://github.com/ioos/conda-recipes/blob/master/recipes/proj4/meta.yaml

**Comment by ocefpaf** [comment]
BTW that goes away when I downgrade to `conda-build=2.0.6`

**Comment by msarahan** [comment]
Thanks for pointing this out.  I'll fix and add a test.

**Comment by msarahan** [comment]
This is probably also fixed by #1493, but I still need to test it.

**Comment by ocefpaf** [comment]
@msarahan I do not recall the original behavior but this is what I get now:

```
libiconv-1.14-0.tar.bz2  # one `-` Before the build number for `NPY`/`PY` packlages
rasterio-1.0a2-np111py35_0.tar.bz2  # an `_` before the build number. Maybe this is OK because the whole things after the `-` is the build number and I never noticed it :smile.

```

**Comment by msarahan** [comment]
yeah, thanks.  That's back to normal.  It was that list containing empty strings.  I'm going to go ahead and close this one.

**Comment by ocefpaf** [comment]
Thanks for fixings all those @msarahan! Now back to try and push `conda-build 2` to `conda-forge`. I guess this part will be much harder...
