### ISSUE TITLE
feature: vc14 causes conflict at end of test process.

### ISSUE THREAD

**Issue by dschreij** [conda/conda-build#1499]
Another error that occurs now, which never did before.

I'm trying to build this [recipe](https://github.com/dschreij/staged-recipes/tree/sdl2/recipes/sdl2) using conda-build 2.0.7 on Windows 

It builds correctly, and after completing the test phase (which is empty in this particular case), the following output appears:

~~~
TEST START: sdl2-2.0.4-vc14_0
updating index in: C:\Anaconda3\conda-bld\win-64
updating index in: C:\Anaconda3\conda-bld\noarch
...INFO:stderrlog:...
Can't build C:\Users\Daniel\Documents\Github\staged-recipes\recipes\sdl2 due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - sdl2 2.0.4 vc14_0 -> feature:vc14
Use "conda info <package>" to see the dependencies for each package.
~~~

This obviously is related to [the vc14 option in the build section](https://github.com/dschreij/staged-recipes/blob/sdl2/recipes/sdl2/meta.yaml#L23). Has anything changed in how you indicate which version of Visual Studio to use?

**Comment by dschreij** [comment]
I should add that the recipe appears to have built correctly and I can install the package afterwards using
`conda install sdl2 --use-local`

**Comment by msarahan** [comment]
You have to have a way to activate the feature at test time.  This is why you'll often see people using the vc package as a runtime dependency.  https://github.com/conda-forge/tk-feedstock/blob/master/recipe/meta.yaml#L23 - mind you that this example depends on some non-standard definition of environment variables: https://github.com/conda-forge/tk-feedstock/pull/7/files

An alternative older way that you'll also see is to use Python instead: https://github.com/conda-forge/openssl-feedstock/blob/master/recipe/meta.yaml#L39-L43

**Comment by dschreij** [comment]
Thanks. I think the tk-option is the most elegant and I will go for that. Is this requirement documented in the conda-build documentation? I scanned that before I posted something here at least, but didn't anything.

**Comment by msarahan** [comment]
I don't think we document it anywhere near well enough.  I'll see about adding something for it.

**Comment by msarahan** [comment]
Nearest thing I could find is

> It’s a good idea to create a metapackage for track_features. If you add track_features to a package that also has versions without that feature, then the versions without that feature will never be selected, because conda will always add the feature when it is installed from the track_features specification if your package with the feature.

from http://conda.pydata.org/docs/building/meta-yaml.html#id1 - but that's about as clear as mud.

**Comment by dschreij** [comment]
I'm having a similar problem now that in the [sdl2 feedstock](https://github.com/conda-forge/sdl2-feedstock), the recipe is built only for Python 2.7 + VC9 but not for the other Pythons + VCs, even though I applied the above suggestions. 
This is especially weird, since in the staged-recipes repo the CIs did build for all VC and Python versions. Is there any way I can force builds for the other VCs?
