### ISSUE TITLE
master broken got ppc64le platform

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda-build#1505]
I'm trying to build https://github.com/ContinuumIO/anaconda-recipes/tree/master/sqlite on `linux-ppc64le` using conda-build master 6f13867d4208040b6ddfa17b1eb2c102b032b7de, and I get:
```
...
Traceback (most recent call last):
  File "/home/ilan/minonda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/ilan/conda-build/conda_build/cli/main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "/home/ilan/conda-build/conda_build/cli/main_build.py", line 234, in execute
    already_built=None, config=config)
  File "/home/ilan/conda-build/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/home/ilan/conda-build/conda_build/build.py", line 1074, in build_tree
    config=recipe_config)
  File "/home/ilan/conda-build/conda_build/build.py", line 819, in build
    tarcheck.check_all(tmp_path)
  File "/home/ilan/conda-build/conda_build/tarcheck.py", line 92, in check_all
    x.correct_subdir()
  File "/home/ilan/conda-build/conda_build/tarcheck.py", line 85, in correct_subdir
    " got {1}".format(subdir, info['subdir']))
AssertionError: Incorrect subdir in package - expecting linux-ppc64le, got linux-64
```
This was working fine using conda-build 1.19.2

**Comment by msarahan** [comment]
How does ppc64le get set?  What part of Conda provides that info?  subdir is a combination of two parts: platform and bits (though bits is obviously wrong here and needs fixing.)  I'm wondering where I should get the right info from.

**Comment by ilanschnell** [comment]
Ah, I see the problem.  You assume that the subdir is platform `-` bits.  However, it is not bits, but architecture (where `32` is short for `x86` and `64` is short for `x86_64`).  conda-build used to get this from `conda.config.subdir`.  In the conda `4.1.x` branch the code is:
https://github.com/conda/conda/blob/4.1.x/conda/config.py#L44

I think `conda.config.subdir` is still the way to get this information.  CC @kalefranz

**Comment by msarahan** [comment]
@ilanschnell please pull and test master.  I hope that #1506 has fixed this issue.  I don't want to directly use subdir from conda for everything.  I'm OK with using it to initialize default values, but the ability to set platform and arch independently is very useful for testing, if nothing else.  I think it will also prove useful for using conda-build for packages that do not necessarily match the system they're built on.

**Comment by ilanschnell** [comment]
Thanks for fixing the issue.  It seems to be working now.

**Comment by msarahan** [comment]
Excellent, thanks for your time in testing.
