### ISSUE TITLE
main page points to deprecated hyperlink

### ISSUE THREAD

**Issue by denfromufa** [conda/conda-build#1508]
this hyperlink is deprecated:

http://github.com/conda/conda-recipes

and instead should point here:

https://github.com/conda-forge/feedstocks/tree/master/feedstocks

**Comment by msarahan** [comment]
Agreed.  Want to put in a PR, or want me to fix it?

**Comment by denfromufa** [comment]
I don't like how the new link looks, so I cannot put this PR:

![image](https://cloud.githubusercontent.com/assets/7870949/19978305/78b62698-a1c4-11e6-8d1c-8c6ef349f6a1.png)

**Comment by msarahan** [comment]
Sorry, I'm very confused here.  You say the current link is deprecated, but you don't like the new one?  What change would you like to see?

**Comment by denfromufa** [comment]
More organized list of conda recipes would be handy, because GitHub
truncates the new list. Did you see the picture that I attached?

**Comment by msarahan** [comment]
I see. Conda forge is a separate organization, not a continuum project (though continuum is involved). I recommend raising this as an issue on that feedstocks repository. I'll change the link here, but I don't have time to work on a more complete view for conda forge.
