### ISSUE TITLE
Bad symbolic links crash conda-build

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-build#1509]
We were getting this strange error in a CI build (package name redacted):
```
Copying /home/ubuntu/xxxxxx to /home/ubuntu/miniconda/conda-bld/conda-recipe_1478271856877/work
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_build/utils.py", line 165, in copytree
    shutil.copy2(s, d)
  File "/home/ubuntu/miniconda/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ubuntu/miniconda/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/xxxxxx/xxxxxx/bin/activate'
````
The file that is not found here is in fact a symbolic link: `/home/ubuntu/xxxxxx/xxxxxx/bin/activate` points to a path that does not exist in the CI instance. 

That entire `bin` directory had been checked into our repository unintentionally. The reason it got there [is a separate `conda` issue](https://github.com/conda/conda/issues/3808). However, its existence does not prevent our package from being built and tested _in situ_, so it seems to me that conda-build should be able to handle this error gracefully. 

I can't decide whether it should _ignore_ faulty symbolic links (or copy them without question), or whether it should do a better job of explaining the failure. But I don't think it should be responding in this manner; a more informative error message would be helpful, because it would help people diagnose the problem much more quickly.

**Comment by msarahan** [comment]
OK.  I'll try to improve this for the next bugfix release.

**Comment by mcg1969** [comment]
Thank you! You might also be interested in the issue that created those symbolic links: https://github.com/conda/conda/issues/3808
