### ISSUE TITLE
Builds using qmake fail with XCode > 8

### ISSUE THREAD

**Issue by dschreij** [conda/conda-build#1515]
Projects that use qmake crash when XCode > 8 is installed, issuing the following message:

~~~
+ /Users/daniel/anaconda/conda-bld/qscintilla2-qt5_1478527333650/_b_env_placehold_/bin/qmake qscintilla.pro -spec macx-llvm
Project ERROR: Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.
Command failed: /bin/bash -x -e /Users/daniel/anaconda/conda-bld/qscintilla2-qt5_1478527333650/work/QScintilla_gpl-2.9.3/conda_build.sh
~~~

After Googling this error message, I found that the cause is that the invocation of `xcrun` changed to `xcodebuild`, see [this StackOverflow question](http://stackoverflow.com/questions/33728905/qt-creator-project-error-xcode-not-set-up-properly-you-may-need-to-confirm-t). I tried looking for the mentioned entry-to-change in `anaconda/mkspecs/features/mac/default_pre.prf` but it appears Anaconda uses a custom default_pre.prf file which does not contain the specified line: `isEmpty($$list($$system("/usr/bin/xcrun -find xcrun 2>/dev/null")))`

**Comment by msarahan** [comment]
This is not something that conda-build controls.  Please file this issue at https://github.com/continuumIO/anaconda-recipes - that is where the recipe for qt lives, and presumably that's where this issue can be addressed.

**Comment by mingwandroid** [comment]
You need to run `xcodebuild` or `xcrun` from the command line and accept the license agreement.

**Comment by dschreij** [comment]
@mingwandroid I tried this, but I don't get prompted to agree with any EULA. I already did this by opening the XCode.app in general, so I doubt I have to do it again in the XCode tools. I will file an issue at the qt recipe.
