### ISSUE TITLE
IOError: [Errno 2] No such file or directory when building noarch package in clean environment

### ISSUE THREAD

**Issue by starcruiseromega** [conda/conda-build#1519]
After updating to 2.0.8, I found that our noarch packages no longer build on our continuous integration system. I've managed to reproduce this locally with a fake package checked in at https://github.com/starcruiseromega/insolent-meow-feedstock. Here are the steps:
1. Install a fresh copy of conda 4.1.12 (used Miniconda3-4.1.12 on the build system and Miniconda2-4.1.12 on my computer) and conda-build 2.0.8.
2. `git clone https://github.com/starcruiseromega/insolent-meow-feedstock`
3. `cd insolent-meow-feedstock`
4. `conda build recipe`
And the output is:
```ShellSession
BUILD START: insolent-meow-0.0.1-py_0
Cloning into '/Users/swilsak/miniconda2/conda-bld/recipe_1478732287822/work'...
done.
checkout: u'4f1416ae85c94b0836f8921141fa4fc35d26ba44'
Note: checking out '4f1416ae85c94b0836f8921141fa4fc35d26ba44'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4f1416a... Add import resolver and ankify projects.
==> git log -n1 <==

commit 4f1416ae85c94b0836f8921141fa4fc35d26ba44
Author: Sally Wilsak <starcruiseromega@gmail.com>
Date:   Sat Aug 29 12:55:32 2015 -0700

    Add import resolver and ankify projects.


==> git describe --tags --dirty <==

0.0.1


==> git status <==

HEAD detached at 4f1416a
nothing to commit, working directory clean


Package: insolent-meow-0.0.1-py_0
source tree in: /Users/swilsak/miniconda2/conda-bld/recipe_1478732287822/work
+ source /Users/swilsak/miniconda2/bin/activate /Users/swilsak/miniconda2/conda-bld/recipe_1478732287822/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+ mkdir -p /Users/swilsak/miniconda2/conda-bld/recipe_1478732287822/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/Examples/insolent-meow
+ cp -r LICENSE README.md conda_build.sh import_resolver vocab_file_converter /Users/swilsak/miniconda2/conda-bld/recipe_1478732287822/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/Examples/insolent-meow
compiling .pyc files... failed as no python interpreter was found
number of files: 8
Fixing permissions
Fixing permissions
Traceback (most recent call last):
  File "/Users/swilsak/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/swilsak/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "/Users/swilsak/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 234, in execute
    already_built=None, config=config)
  File "/Users/swilsak/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/Users/swilsak/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1070, in build_tree
    config=recipe_config)
  File "/Users/swilsak/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 818, in build
    copy_into(tmp_path, path, config.timeout)
  File "/Users/swilsak/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 120, in copy_into
    shutil.copy2(src, dst_fn)
  File "/Users/swilsak/miniconda2/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/swilsak/miniconda2/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'/Users/swilsak/miniconda2/conda-bld/noarch/insolent-meow-0.0.1-py_0.tar.bz2'
```
Replacing step 4 with:
4a. `mkdir ~/miniconda2/conda-bld/noarch && conda build recipe`
and the package is built as expected.

The CI system is running on Linux and I ran locally on a Mac. My guess is that the noarch directory just needs to be created the same way the OS-specific directory is created, but I wasn't able to find where in the code that happens to try it out and possibly send a PR. If you can tell me where to look, I can submit a patch.

**Comment by msarahan** [comment]
argh.  Yes, your analysis seems correct.  That location is computed at https://github.com/conda/conda-build/blob/master/conda_build/build.py#L795

I think the "right" place is probably within that function.  My philosophy has been to create folders as necessary whenever the path is requested.  That location is https://github.com/conda/conda-build/blob/master/conda_build/render.py#L73

See https://github.com/conda/conda-build/blob/master/conda_build/config.py#L300 and https://github.com/conda/conda-build/blob/master/conda_build/config.py#L35-L42 for examples
of how I do this elsewhere.

**Comment by starcruiseromega** [comment]
Hm, I took a look at those links and it looks like it is creating the directory properly, but the way it's determining if the package is a noarch package is by checking for "noarch" in the config. So I can get this to work the way that I want by using "noarch: True" in the recipe instead of "noarch_python: True" (https://github.com/starcruiseromega/insolent-meow-feedstock/tree/noarch-config).

In that case, maybe the only thing that needs to be updated is the documentation at http://conda.pydata.org/docs/building/meta-yaml.html#architecture-independent-packages? Or is "noarch_python" still a config parameter that should be supported, in which case we'd just want the "noarch_python: True" setting to also imply "noarch: True"?

**Comment by msarahan** [comment]
noarch_python still needs support - sorry that broke.  noarch_python is not equivalent to noarch: True, though.  It is equivalent to noarch: python, but since noarch's value is "truthy", they are somewhat equivalent.

@soapy1 could you please look into this when you can?

**Comment by soapy1** [comment]
@msarahan @starcruiseromega 
I can't reproduce this issue on master. I think maybe https://github.com/conda/conda-build/commit/bfe25468892d97396d9906ab92c13c95834c05e7 fixed this issue.

**Comment by msarahan** [comment]
I'm going to call this resolved based on @soapy1's testing and my own, but please reopen or open a new issue if it is not actually fixed.

**Comment by starcruiseromega** [comment]
That does look like it would fix it. Thanks for looking into it!
