### ISSUE TITLE
Lock timeouts

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1524]
Tests run concurrently often encounter lock timeouts.  This is making CI failures meaningless.

Proposed reason behind lock timeouts:  Race conditions with multiple locks.  If these get out of order, then deadlock can occur.  Can we move to a single lock location instead, or perhaps "category" locks in arbitrary places (for example, a lock for "index" operations)

**Comment by frol** [comment]
I missed this issue and raised a new one instead (#1597). Is there a workaround? I am in a desperate search for a solution as I have a number of dependent packages, which just fail randomly ruining the whole continuous integration :(

**Comment by msarahan** [comment]
@frol sorry, I'll try to get #1540 working better.  Failing that, I'll create a --no-lock option that will not do any locking (and thus may not work with parallel builds), but at least won't break builds.

**Comment by msarahan** [comment]
Hopefully fixed by #1540 - closing for now.
