### ISSUE TITLE
conda 4.1.x incompatibilities introduced in 2.0.9

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1527]
The `2.0.9` release appears to have introduced incompatibilities with `conda` version `4.1.x` despite noting [compatibility]( https://github.com/conda/conda-build/blob/7016ee81371a26970583cf292f2eb331d51362c1/conda.recipe/meta.yaml#L26 ). In particular, this [import]( https://github.com/conda/conda-build/compare/2.0.8...2.0.9#diff-6d8cb4644da89eaf24a8c9617a738d55R27 ) and this [import]( https://github.com/conda/conda-build/compare/2.0.8...2.0.9#diff-6d8cb4644da89eaf24a8c9617a738d55R28 ) are not available in `conda` version `4.1.x`. Either this release needs to bump its version constraint (and thus arguably be a major or at least minor version change) or compatibility should be restored.

cc @scopatz

**Comment by jakirkham** [comment]
At least for near term problems, it would be nice if either this `conda-build` version were pulled or at a bare minimum hot-fixed to have the right version constraint w.r.t. `conda`.

**Comment by jakirkham** [comment]
Also would like to ask that the CI version matrix be expanded to include all minor versions of `conda` that are currently supported in the future so as to avoid this sort of problem.

**Comment by msarahan** [comment]
John, have you ever seen "The Big Lebowski?"  How well received are your bug reports that tell people what to do, in general?

> would like to ask that the CI version matrix be expanded to include all minor versions of conda that are currently supported in the future so as to avoid this sort of problem.

We do try to do this, but it seems there is a problem:

https://github.com/conda/conda-build/blob/master/.travis.yml#L36
https://travis-ci.org/conda/conda-build/jobs/175208215#L237
https://travis-ci.org/conda/conda-build/jobs/175208215#L360

```auto_update_conda: false``` is not being respected.  I'll raise this on the conda issue tracker.  In the meantime, please put your finger down.

**Comment by jakirkham** [comment]
Sorry, if that came off as harsh, was a bit surprised by this sort of break.

**Comment by msarahan** [comment]
conda-build 2.0.10 is released and should address this issue.
