### ISSUE TITLE
Terminal throws error message everytime I cd to a git repository

### ISSUE THREAD

**Issue by simmimourya1** [conda/conda-build#1529]
I used anaconda2 for a project. I don't remember the first time when it threw this error because at that point it didn't affect the work flow and everything was working fine. I tried to fix it but couldn't find any work around. It still doesn't affect anything but this message  pops up every time I `cd` to a local git repository:
`Error: too few arguments, must supply command line package specs or --file`

![screenshot from 2016-11-13 07 03 32](https://cloud.githubusercontent.com/assets/8150326/20243125/86e7fa7c-a96f-11e6-8928-64faee826845.png)

And it is bugging me. 

No error is thrown if I am not inside a git repository. 

![screenshot from 2016-11-13 07 03 52](https://cloud.githubusercontent.com/assets/8150326/20243127/921228dc-a96f-11e6-9533-86b6d8f0e544.png)

Any clue?
 Thanks a lot for reading this!

**Comment by msarahan** [comment]
Sorry, I don't see how this is related to conda-build.  I'm moving this issue to conda.  I think it probably has something to do with your zsh customization, which is trying to run conda to figure out when environment you're in somehow.  I don't think this is anything standard, so unfortunately, you're probably going to need to figure this out yourself.

**Comment by msarahan** [comment]
Issue moved to [conda/conda #3866](https://github.com/conda/conda/issues/3866) via [**ZenHub**](https://www.zenhub.com/)

**Comment by simmimourya1** [comment]
Well, thanks anyway. I'll post the workaround if I find any!
