### ISSUE TITLE
Can I build a package without an rpath set?

### ISSUE THREAD

**Issue by davidslac** [conda/conda-build#1532]
I am trying to create a conda package from some C++ code which does not have RPATH set  . This is so I can use the package in a development manner by manipulating LD_LIBRARY_PATH. (here is a post on the users group about this: https://groups.google.com/a/continuum.io/forum/#!topic/conda/_JN8ayjmjzU) Is there a way to do this? From reading the docs, I tried:

```
build:
  ignore_prefix_files: True
  binary_relocation: False
```
but if I look at the rpath, I see
```
RPATH=$ORIGIN/../lib:/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/conda-bld/psana-conda-dev_1479144497787/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib
```

**Comment by msarahan** [comment]
Sorry, that seems like a bug.  I'll try to look into it soon.

**Comment by mingwandroid** [comment]
In general, to build stuff that's testable via `LD_LIBRARY_PATH` this you need to use the linker flag of `--enable-new-dtags`, usually passed in from GCC via `-Wl,--enable-new-dtags`:

https://en.wikipedia.org/wiki/Rpath

**Comment by davidslac** [comment]
Wait, this might be my error - I see my scons build system sets 
rpath, I'll look into this more, sorry if noise

best,

David

**Comment by davidslac** [comment]
Ray, thank you so much! That was just the detail I was missing! I just 
built my package with that flag, and told conda-build not to change 
RPATH, and I see my package is now using RUNPATH and I can override it 
with LD_LIBRARY_PATH.

Now if I continue to build with RUNPATH using that flag, and then let 
conda build change RPATH, I should get the best of both worlds? readelf 
will magically change both the RPATH and RUNPATH in my package files to 
find libraries in an installed conda environment, and I can still 
override with LD_LIBRARY_PATH? Anyways, I'll try it.

best,

David

**Comment by davidslac** [comment]
It looks like when conda-build fixed up RPATH, and I set  -Wl,--enable-new-dtags, it is actually setting RUNPATH, which is just what I wanted - I'll close this, I forgot my build system was setting an RPATH already, no bug in conda-build

**Comment by mingwandroid** [comment]
Some consider building released packages with `--enable-new-dtags`/`LD_LIBRARY_PATH` a security risk because if someone can hack your process environment block they can divert your shared libraries.

Apple recently more or less completely shutdown their equivalent (the `DYLD_*` family of env. vars) under the name of System Integrity Protection. This was good for security but bad for developers.

**Comment by davidslac** [comment]
I was thinking of building two versions of our package, one with 
--enable-new-dtags and one without, for production, not so much for 
security but just to prevent someone from accidentally picking up the 
wrong library with LD_LIBRARY_PATH. Our environment is open scientific 
software analysis, someone can always do LD_PRELOAD to divert shared 
object libraries - we should be careful to make sure we never need to 
collect passwords from users, that might make me worry about security 
issues. Thanks again, I'd read about the difference between RPATH and 
RUNPATH but missed the fact that I could create a RUNPATH when I build.
