### ISSUE TITLE
list of used dependency versions for each build..

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1534]
_From @martin-mann on November 14, 2016 13:54_

Hi,

we just discussed for bioconda the problem of updated runtime dependencies that break existing downstream packages (eg for perl etc..).

eg. think about the following situation: given a (perl) package A and a dependent package B, which only provides a minimal required version for A. Now A is updated and rebuild to a new version which drops the interface used by B. So the build of A is successful, but as soon as B is installed, the recent A is installed too and B fails on runtime.

Is is planned/possible/useful to add to each package also the *full list* of packages including version number used for the build?

This would very much ease 
- debugging for the described scenario and 
- enable the identification of outdated packages to be rebuild.

Thanks for feedback on that,
Martin

_Copied from original issue: conda/conda#3872_

**Comment by kalefranz** [comment]
This might already be done, or it might be planned.  I'm not sure.  I'm going to move the issue to conda-build for you so it gets more attention by the people who would know best :)

**Comment by msarahan** [comment]
@martin-mann Yes, this is of interest.  I'm not sure I totally understand the issue, though.  I think that there are at least two issues to address:

1. General pinning of runtime requirements given build-time versions.  This is the crux of #1142 
2. Exact pinning of build-time versions in the recipe contained in any produced packages.  This is mostly for the sake of reproducibility.  It is something that I certainly intend to do on a near-term timescal.

Which of these is your greater concern?

**Comment by martin-mann** [comment]
@msarahan My idea/question was much weaker than either 1 or 2. It would already be of much help, if each package provided in its meta data the information on 
- what packages it depends on (both build and runtime) and
- on what exact package versions it was built on.

Thus, it is more a tracking issue rather than pinning everything. This way you get both: automatic updates of runtime dependencies (if only a minimal version is required within the meta.yaml) and a way to identify the change that might cause runtime issues when a runtime dependency was updated and got incompatible (eg via different output/API/...).

Pinning a build already in the recipe to an exact version is ok (makes things reproducable), but rather strict. For instance if you are pushing a bugfix release of a tool/lib/whatever. Do you have to update/rebuild ALL packages that use that package? Sounds quite unrealistic.. And what about packages in other channels that use that package too?

But anyway, until everything is pinned to the core, just to have the build meta data would be of great help anyway! 

Hope that clearifies my concern. :)

Thanks for consideration!

**Comment by msarahan** [comment]
Sorry, I'm still confused. 

Packages by default include meta.yaml, both in its raw form with any template variables and selectors as well as a "rendered" version that fills all of that in. These do not capture build time dependency versions. I would like the rendered version to do so, eventually. This will not affect flexibility, you'll still have the original, unpinned recipe. It's just that that particular package will be more reproducible. 

Runtime stability is an ill-posed problem for conda build. If everyone followed semantic versioning perfectly, it might be feasible. The only approach that will work even some of the time is for package builders to pin their runtime requirements based on their knowledge of any changed API or whatever. The downside is that pinning to specifically can quickly lead to conflicts and unsatisfiable dependencies. 

Integration of some API tracking database may help. That may be part of #1142. ABI is also important, and that's definitely what #1142 aims to  address. 

Sorry there is no magic bullet. Does this clarify things, or do you still have questions?

**Comment by martin-mann** [comment]
No questions left. To add the build time version information to the rendered meta.yaml is exactly what I was looking for. This would enable both (a) tracking of needed package updates (dep too old) as well as (b) debugging if a certain runtime dep version has changed (a lot).

Is there a way to push this information also to webfrontends like the anaconda package listing? (I know this is the wrong place to ask.. just asking)

Thanks for the discussion!

**Comment by msarahan** [comment]
It's a simple concept, but I don't know about implementation.  You'd have to update some database when uploading a package, or parse the meta.yaml file somehow.  You can file an issue for a feature request.  I think https://github.com/Anaconda-Platform/anaconda-client might be the right repo.

**Comment by sebastian-luna-valero** [comment]
Interesting discussion.

Currently, I have to manually do:
```
conda build mypackage-folder >& conda-build.output
awk '/The following NEW packages will be INSTALLED/,/^#/' conda-build.output
```

I was wondering whether having an option for `conda build` that simply displays the package names and versions that are used to build the package is of interest for anyone other than me.
```
conda build mypackage-folder --dependency-versions conda-build.output
```
Many thanks,
Sebastian.

**Comment by msarahan** [comment]
@sebastian-luna-valero I don't know if that's useful enough to warrant a new argument.

I think it'd be fine to make sure that conda render outputs this information, also, though.  That outputs yaml text, which you should be able to parse more easily than the conda-build raw output.  It does not seem to output the frozen build dependencies currently, but I'll make a new issue to fix that.

**Comment by sebastian-luna-valero** [comment]
That would be great!

**Comment by msarahan** [comment]
Don't thank me yet.  No promises that it will be fast.  It may need some nasty hacking (like your awk solution) or some new conda feature, which would take time to be available.  I'll work on it at some point, though.

**Comment by sebastian-luna-valero** [comment]
@msarahan 

Sorry, I was naively thinking that this could be solved by adding a line to the for loop here:
https://github.com/conda/conda/blob/master/conda/plan.py#L214

No worries then, and again thanks for thinking about it!
