### ISSUE TITLE
Using git_url with a Windows UNC path would fail conda build

### ISSUE THREAD

**Issue by will133** [conda/conda-build#1545]
On Windows, it seems like if I include a unc path in the meta.yaml:

```
git_url: \\server\path\to\git\repo
```

Somehow the git clone command it'll invoke would append the c:\ in front and so the git clone would fail since c:\server\path\to\git\repo is not a valid path.  I ended up having to map the unc path to a drive letter (that we're discouraged to do in general) in order to make this work.  Does anybody know if it's supposed to work like that?

I've also tried to do a file:// prefix, but the git clone command now would create a path called \\server\path\to\git\repo.lnk and of course that is not found.  I can't seem to find a way to make this work without mapping it to a drive letter.

**Comment by msarahan** [comment]
I don't think we generally support this use case very well.  This is a good feature request, but I don't know when I can fit it into the roadmap - probably 1-2 major releases away right now.  PRs welcome if you have time to dig into it.
