### ISSUE TITLE
README.rst should include pytest-cov dependence

### ISSUE THREAD

**Issue by gomyhr** [conda/conda-build#1552]
Trying to follow the recipe in ``README.rst`` for testing. It says that it uses ``py.test`` for testing, and I found that in the ``pytest`` package. However, ``py.test tests`` fails with 

    usage: py.test [options] [file_or_dir] [file_or_dir] [...]
    py.test: error: unrecognized arguments: --cov-report tests
      inifile: /home/gom/src/conda-build/setup.cfg
      rootdir: /home/gom/src/conda-build

After some searching and git-blaming I found out that this was fixed by installing the ``python-cov`` package.

It should be stated in ``README.rst`` that ``pytest`` and ``pytest-cov`` packages are required.

**Comment by msarahan** [comment]
Thanks.  We do have this in the conda recipe: https://github.com/conda/conda-build/blob/master/conda.recipe/meta.yaml#L40

Sadly, conda, doesn't really have a notion of creating an environment based on the composite of runtime and test-time dependencies from a meta.yaml file.  I think that's something that the ```conda develop``` command should grow the ability to do.
