### ISSUE TITLE
docs for new release build/uploading 

### ISSUE THREAD

**Issue by arsenovic** [conda/conda-build#1566]
thank you all very much for the conda system. i would like to use anaconda as the preferred package source for the project scikit-rf.org. 

i have a working conda build recipe and have uploaded in the past (~1yr ago).  just now  i tried to make another release. obviously i forgot what i did, so i  tried to find docs on how to do this upload a new version to anaconda.org. i found the docs very hard to read for this purpose.  to be clear, i desired the following.  

* build for couple py-versions
* build for all platforms
* upload all builds to anaconda.org under the organizations channel (never figured this out)
* do this every time i make a release. 

 it would be nice if this common set of task was made clearer in the docs, or perhaps scripted so that developers  can just 'hit the release button' !

**Comment by msarahan** [comment]
Good idea.  I'll try to write up these docs.

For uploading builds to anaconda.org channel, you need to pass the ```--user``` argument to conda-build.

For the other questions, these are really questions better answered by some build system - Conda Forge has very good tooling across Travis CI, Circle CI, and Appveyor.  Continuum is working on a project for a build system that will supplement that: https://github.com/conda/conda-concourse-ci

The goal is that commits to particular repositories will trigger builds, leading to eventual package deployment.  That build system is pretty new, so only investigate it if you have lots of time to spare.  We're still working out the kinks internally.

**Comment by arsenovic** [comment]
thanks for your answer and   i will look into  your suggestions.  building on anaconda.org(binstar) was the best solution for me.  ideally, they would have a `dev` versions built on each commit, and  have release versions built when specific tags are  pushed.  i hate to see redundancy of effort wasted in building packages, and really appreciate the work conda has relieved. 
thanks again,
