### ISSUE TITLE
libffi too hard to use

### ISSUE THREAD

**Issue by Horta** [conda/conda-build#1567]
I'm still trying to figure out how to make libffi visible: https://github.com/conda-forge/staged-recipes/pull/2044

I keep getting the following error:

```
  File "/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.4/site-packages/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

**Comment by msarahan** [comment]
Sorry, I don't understand the question here.  I think this issue belongs on the https://github.com/conda-forge/libffi-feedstock issue tracker.

**Comment by jakirkham** [comment]
This actually appears to be a `cffi` issue. However, that is a problem with `defaults` copy of `cffi` as we don't have it in `conda-forge`. Maybe the easiest way forward will be to create a `cffi` that works in `conda-forge` and solves this issue.

In any event, it is not a `conda-build` issue and should probably be moved to [anaconda-issues]( https://github.com/ContinuumIO/anaconda-issues/issues ).
