### ISSUE TITLE
Make the fallback dependency directory configurable

### ISSUE THREAD

**Issue by gbrener** [conda/conda-build#1568]
Currently, if `conda-build` doesn't find a recipe's dependencies in the existing channels, it falls back to the filesystem and searches the parent directory of the main recipe: https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1257

It would be nice if this "fallback dependency directory" were configurable, either as a command-line option, environment variable, or in the `meta.yml`. This would allow conda recipes (that are used as dependencies) to be stored in other locations on the filesystem.

**Comment by msarahan** [comment]
This is a good idea, and worth doing at some point.  However, it is a "nice to have" in my opinion and sits behind split packages ( #1338 ) and build customization/better compiler metadata ( #1142 )

PRs welcome at any time.
