### ISSUE TITLE
Duplicate conda-build processes in docker environment (fails to acquire lock)

### ISSUE THREAD

**Issue by groutr** [conda/conda-build#1569]
This has got me baffled.  I'm using the continuumio/conda_builder_linux image with docker 1.12.1.  Conda build always fails to acquire a lock and then quits.

Running `ps -eaf` during this failure shows that there are two conda build processes running inside the container.  I'm not sure where the extra conda build process is getting launched.  It doesn't look like conda build does parallel updates to indexes.  I'm not sure if docker is at fault since this only happens with conda build.  Running conda, or any other binary works fine and only launches one process.  But with conda-build, duplicate processes get started.

This is after running conda clean --lock both on the host and inside the container.
```
% docker run -it -v ~/conda-recipes:/home/dev/conda-recipes -v ~/.condarc.docker:/home/dev/.condarc -v ~/conda-bld:/home/dev/conda-bld continuumio/conda_builder_linux /opt/share/internal_startup.sh
WARNING: No ABI default set.  Falling back to compatibility mode with GCC 4.

Welcome to the conda-builder image, brought to you by Continuum Analytics.

Binaries produced with this image should be compatible with any Linux OS
that is at least CentOS 5 or newer (Glibc lower bound), and anything    
that uses G++ 5.2 or older (libstdc++ upper bound)                      

    GCC is: gcc (GCC) 5.2.0
    Default C++ ABI: 4 (C++98)
    GLIBC is: glibc 2.5       
    ld/binutils is: GNU ld (GNU Binutils) 2.26.20160125

    Native arch is x86_64.  To build 32-bit code, set the ARCH environment
        variable to 32. (-e "ARCH=32" docker argument)                    

    The dev user (currently signed in) has passwordless sudo access.
    miniconda (2.7) is installed at /opt/miniconda.                 
    git is also available.                                          

Helpful aliases:
    clone_recipes: clones the conda/conda-recipes repo from Github
    clone_anaconda: clones the continuumIO/anaconda (private) repo from Github
    anaconda_setup: clones anaconda repo and sets up continuum internal build system.

[dev@dc012a28664c ~]$ conda build conda-recipes/xxxxxxxx
BUILD START: <xxxxxxxx>                        
    (actual version deferred until further download or env creation)
updating index in: /home/dev/conda-bld/linux-64                     
File lock on /home/dev/conda-bld/linux-64/.conda_lock could not be obtained.  You might need to try fewer builds at once.  Otherwise, run conda clean --lock
```
@msarahan, have you seen this before/can you reproduce this?

**Comment by groutr** [comment]
Some futher notes:
The only relevant thing in .condarc for conda-build is
```
conda-build:
  root-dir: ~/conda-bld
```

The docker image is (includes the latest conda build
```
continuumio/conda_builder_linux   latest                           ee7ef70d9c75        6 days ago
```

and `conda info`
```
[dev@a14eeee2636f ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.11
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /opt/miniconda  (writable)
    default environment : /opt/miniconda
       envs directories : /opt/miniconda/envs
          package cache : /opt/miniconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/dev/.condarc
           offline mode : False

**Comment by msarahan** [comment]
yikes.  I have not seen this.  Have you tried running the conda-build executable directly?  This goes around some of the conda argparse stuff, and might simplify the situation.

I'm tied up with training stuff the next few days, but will look into this when I come up for air.

**Comment by groutr** [comment]
I can't remember if I tried that or not, but that is a really good suggestion.  I'll give that a try and see what happens.

**Comment by groutr** [comment]
Running conda-build directly fixes the duplicate process problem.  However, I think I stumbled onto the deeper issue.  Conda-build can't acquire the lock inside the docker container due to permission problems caused by what appears to be selinux.

**Comment by msarahan** [comment]
Thanks for narrowing this down.  I'm going to close this issue.  Long-term, I'd like people to use conda-build directly, as the overhead in calling conda's argparse stuff is adding 1-2 seconds of delay for each command.  I think a less extensible approach local to conda-build might be better.

**Comment by frol** [comment]
I also encounter this race condition or whatever it is on my CI server (I am also using Docker containers). I have to re-run my jobs 2-3 times before they succeed.

@msarahan `conda-build` is not available when non-root environment is activated (while `conda build` is available). What is the suggested workaround then? Activate root env whenever I want to build something and reactivate my non-root env for further development?

**Comment by frol** [comment]
Using `conda-build` directly (instead of `conda build`), indeed, "solves" the issue.

**Comment by msarahan** [comment]
Sorry @frol - I agree that this is not a solution, just a workaround.  I'll try to figure out how to do some kind of fallback when the permission error occurs.

**Comment by msarahan** [comment]
Closing as superseded by #1601 - to be developed for the 3.0.0 release.
