### ISSUE TITLE
conda build . --dirty results in 'need_source_download' referenced before assignment'

### ISSUE THREAD

**Issue by looooo** [conda/conda-build#1570]
the --dirty flag doesn't work for me. (conda-build 2.0.11)

```bash
Traceback (most recent call last):
  File "~/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "~/anaconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 244, in main
    execute(sys.argv[1:])
  File "~/anaconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 236, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "~/anaconda/lib/python3.5/site-packages/conda_build/api.py", line 75, in build
    need_source_download=need_source_download, config=config)
  File "~/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 1227, in build_tree
    config=recipe_config)
  File "~/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 790, in build
    config=config)
  File "~/anaconda/lib/python3.5/site-packages/conda_build/render.py", line 112, in parse_or_try_download
    return metadata, need_source_download, need_reparse_in_env
UnboundLocalError: local variable 'need_source_download' referenced before assignment
```

**Comment by looooo** [comment]
Could we set "need_source_download" by default to false? It seems "need_source_download" isn't set when --dirty is specified.
https://github.com/conda/conda-build/blob/master/conda_build/render.py#L84-L87

**Comment by msarahan** [comment]
Sure. That seems like a bug to me.

PRs welcome, otherwise I'll be sure to fix this for the next bugfix release.

**Comment by looooo** [comment]
I would like that conda-build with --dirty replace the source code if a local path for the source is given. At the moment, with simple setting "need_source_download = False" the source isn't copied, or maybe pulling all diff files, if this is somehow possible.

**Comment by msarahan** [comment]
That's not really what --dirty is intended to do.  --dirty was a flag to avoid downloading the source code completely.  If you want current code, you probably want to use the

```
source:
    path:
```

entry in meta.yaml to point at a current folder.  Are you just dealing with a massive source tree that takes a long time to copy?

Regarding the git repo, this is expected.  Git repos are clones, and thus they only capture committed work.  The path example above is a straight copy of the code as it exists elsewhere on disk.

**Comment by looooo** [comment]
I was looking for an option to develop c++ projects with conda. Something to reuse the cmake cache and only build th

**Comment by msarahan** [comment]
Can you tell me more about your use case?

Conda-build is really meant to be at the end of the whole development process - packaging.  The assumption is that you are doing development with other better-suited tools that are aware of your existing compiled artifacts.  What is conda-build adding to your workflow, so that it is better than these tools during the development phase?  Why do you need rpath replacement during development?  That is primarily a redistributability/relocatability measure, and I don't understand why things need to be relocatable when they are under development - they just need to work on the local development machine.

**Comment by looooo** [comment]
My use-case is a c++ library which has many dependencies. As conda is the only tool providing a consistent method to install dependencies on all platforms, it would be nice to use the dependencies from conda to build the package (also to develop stuff). 
But maybe I was a bit too fast with the rpath-assumption and have misinterpreted the error.

The error was:
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
```

and setting $PYTHONHOME does indeed work. So this solves my issue.
Thanks for your help!

**Comment by msarahan** [comment]
OK, thanks for working with me.  I'll close this issue.  If you want to use Conda as a development environment, I recommend using a compiler as a package (GCC), and then also making sure that these relevant environment variables are set using http://stackoverflow.com/questions/31598963/how-to-set-specific-environment-variables-when-activating-conda-environment

**Comment by looooo** [comment]
thanks, the information in the link is exactly what I needed. :+1:

**Comment by looooo** [comment]
setting the pythonhome variable works, but then conda doesn't work anymore. I get this:

```
conda install numpy
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007f8145f4e700 (most recent call first):
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by msarahan** [comment]
It is very easy to mess things up with these environment variables.  Please make sure that whenever you set an environment variable, you also keep its existing value.

For example, if you want to add a PATH:

```export PATH=$PATH:some_new_path```

the same holds for all of the other variables you might set.  If you clobber system stuff, things can break in drastic but mysterious ways.

**Comment by looooo** [comment]
I tried this also with the PYTHONHOME variable, but it doesn't worked. Still get this error with encodings.

Building with cmake in a conda enviroment works but as there are still problems (PYTHONHOMEPATH) I would like to add another option to conda-build.
Something like a --develop option where:
- the source is not copied at all for a local path
- and the build-directory isn't recreated (as it is the case with --dirty)

This option would be nice because it uses the std. conda-build files and would decrease the build time. Maybe you can give me some information if such an option would work and where to implement the function for this.

**Comment by croth1** [comment]
this bug is still present in conda-build 2.0.12
