### ISSUE TITLE
SYS_PYTHON environment variable : feature or implementation detail

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#1571]
I noticed that the environement variable `SYS_PYTHON` is set in the build environment but this variable is not mentioned in the [documentation](http://conda.pydata.org/docs/building/environment-vars.html#environment-variables-set-during-the-build-process).  Should this variable be considered a feature of the build environment that recipes and build scripts can depend upon or is this a implementation detail that may be removed in future versions?

**Comment by msarahan** [comment]
I don't remember. =(

If it's useful, I'm happy to document and codify it.

**Comment by jjhelmus** [comment]
This can be useful for building package which require Python during build time for configuration or other one-off steps but not at run time.  Using `SYS_PYTHON` in the build script removes the need for including python in the build requirements which in turn can remove circular recipe dependencies.  For example: `pkg-config` requires `python` during build, `pkg-config` is required for `ncurses` which is required for `python`.

Additionally, you can do some *interesting* things if you have access to `conda_build.api` from within the build environment.  Not all of these are *good* ideas but it does unlock some possibilities.  One example I was playing with was to use this to copy over wheel files to the conda build output directory:

``` bash
# build and install a whl file
${PYTHON} setup.py bdist_wheel
cd dist
${PYTHON} -m pip install --no-deps *.whl

# copy the whl file to the conda build output directory
OUT_DIR=`${SYS_PYTHON} -c "import os; from conda_build import api; print(os.path.split(api.get_output_file_path(os.environ['RECIPE_DIR']))[0])"`

echo "Copying whl file"
cp *.whl ${OUT_DIR}
```

**Comment by jakirkham** [comment]
Does this still make sense with the `build`/`host` split?

**Comment by mingwandroid** [comment]
Yes. It's the Python running the show, always.
