### ISSUE TITLE
Missing `recipe.json` file results in default metadata on Anaconda.org

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#1577]
`anaconda-client` [uses the contents of the `recipe.json` file](https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/inspect_package/conda.py#L89-L93) to extract the package attributes (summary, license and homepage) when the package is uploaded to Anaconda.org.  

This file is no longer included by package created by `conda-build`, (conda/conda-build#781).

When uploaded, packages which are missing a `recipe.json` file will have default values used for this metadata ("No Summary", "Unspecified") unless manually specified by the user.  For example, https://anaconda.org/conda-forge/fenics.

Either this file should be added back to packages created by `conda-build`, or `anaconda-client` should be updated to extract this metadata from the `about.json` file.  The later makes more sense to me.  

I'll open a similar issue in the `anaconda-client` repository, Anaconda-Platform/anaconda-client#379

**Comment by msarahan** [comment]
Thanks for raising this @jjhelmus - I'll try to work with the anaconda-client team to get this adapted to the newer about.json file.

**Comment by ilanschnell** [comment]
Yes, this is exactly the reason why `info/about.json` was created.

**Comment by jakirkham** [comment]
This was solved in `anaconda-client`. So this should be closed.
