### ISSUE TITLE
work directory not deleted for test stage

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#1580]
The work directory is not deleted when the recipe tests are run. This has caused a problem where paths from the source directory were hardcoded in the executable, but I did not notice because the test passed. See https://github.com/conda-forge/emacs-feedstock/issues/2#issuecomment-267542043.

I don't remember if this has always been this way, or if there was a good reason for it if it was. I agree that the work directory should stay intact if there are no tests, or if the build fails and the tests are not gotten to, but it should be deleted (or if you're worried about deletion, at least set aside) during the tests, for the same reason that the build environment is deleted for the tests.

**Comment by msarahan** [comment]
I don't remember if this has changed as a result of my work on this.  I do see that it would be helpful to catch errors this way.  It also makes the source_files feature more complicated, unfortunately - you have to keep track of some location where you move the source to for when source_files goes looking for things.

I'd call this a feature request, and will try to work it into a release soon.  If you have time, a PR would be appreciated.

**Comment by mingwandroid** [comment]
We'd need to make sure that the split-packages (new feature) all get packaged before any tests are run for this to work.

Renaming the work folder would cause havoc on Windows too (virus scanners holding file handles), so please don't do it that way.

**Comment by asmeurer** [comment]
What needs to access the source files after the tests are run? 

My plan was to just add a call to the top of `test()` to (re)move the test directory. I don't know how split packages work but assumedly any building should be done by then.

**Comment by asmeurer** [comment]
Oh I see what `source_files` is. So I guess it should just be (re)moved after those files are copied.

**Comment by asmeurer** [comment]
(and yes, I'll be happy to contribute this, but I want to get a full idea of potential issues from you guys first)

**Comment by msarahan** [comment]
@mingwandroid and I have agreed offline that removing the source folder after files are copied for ``source_files`` should be fine.  With the split packages concept, we should have everything done before we leave the build phase, anyway.

**Comment by asmeurer** [comment]
PR at https://github.com/conda/conda-build/issues/1580
