### ISSUE TITLE
Packages with malformed version and tests build infinitely in a loop

### ISSUE THREAD

**Issue by Zaharid** [conda/conda-build#1586]
If I build the recipe:

````
package:
    name: mypackage
    version: ".0.wqqw"

source:
    file: .

build:
    command: echo

test:
    commands:
        - echo
````

It starts building again immediately after it finishes:

````
$ conda build .
BUILD START: mypackage-.0.wqqw-0
Package: mypackage-.0.wqqw-0
source tree in: /home/zah/anaconda3/conda-bld/pkg_1482102768196/work
number of files: 0
Fixing permissions
Fixing permissions
updating index in: /home/zah/anaconda3/conda-bld/linux-64
updating: mypackage-.0.wqqw-0.tar.bz2
TEST START: mypackage-.0.wqqw-0
updating index in: /home/zah/anaconda3/conda-bld/linux-64
updating index in: /home/zah/anaconda3/conda-bld/noarch
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/zah/anaconda3/conda-bld/linux-64/mypackage-.0.wqqw-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

BUILD START: mypackage-.0.wqqw-0
Package: mypackage-.0.wqqw-0
source tree in: /home/zah/anaconda3/conda-bld/pkg_1482102771898/work
number of files: 0
Fixing permissions
Fixing permissions
updating index in: /home/zah/anaconda3/conda-bld/linux-64
updating: mypackage-.0.wqqw-0.tar.bz2
TEST START: mypackage-.0.wqqw-0
updating index in: /home/zah/anaconda3/conda-bld/linux-64
updating index in: /home/zah/anaconda3/conda-bld/noarch
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/zah/anaconda3/conda-bld/linux-64/mypackage-.0.wqqw-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

BUILD START: mypackage-.0.wqqw-0
Package: mypackage-.0.wqqw-0
source tree in: /home/zah/anaconda3/conda-bld/pkg_1482102775221/work
number of files: 0
Fixing permissions
Fixing permissions
updating index in: /home/zah/anaconda3/conda-bld/linux-64
updating: mypackage-.0.wqqw-0.tar.bz2
TEST START: mypackage-.0.wqqw-0
updating index in: /home/zah/anaconda3/conda-bld/linux-64
updating index in: /home/zah/anaconda3/conda-bld/noarch
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/zah/anaconda3/conda-bld/linux-64/mypackage-.0.wqqw-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

BUILD START: mypackage-.0.wqqw-0
Package: mypackage-.0.wqqw-0
````
and so on. This happens if:

 - The recipe has some tests.
 - The recipe has a malformed version (starting with dot), which can happen for example if `git describe --tag` fails for some reason and part of the version string gets sliced.

**Comment by msarahan** [comment]
@Zaharid thanks for the report.  I hope that #1594 fixes this issue.  Let me know if you have any further comments on a better fix.

**Comment by Zaharid** [comment]
Thanks!
But is there any reason things should rebuild infinitely, versions aside?
Also, it could possibly be useful if the GIT_DESCRIBE_TAG environment variable was the git_describe_tag() function (that gets passed to jinja), that knows how to report errors nicer and so on.

**Comment by msarahan** [comment]
Mostly these errors arise because the logic for following a build tree is recursive, and fragile.  Rather than computing a graph of build tasks, conda-build starts with the first recipe you give it, and if it finds others that it needs to build, it builds those first.  The danger here is that unless we catch every possible failure mode, then this recursion tends to end up in infinite loops.  It's frustrating, and I'd like to get rid of that recursion altogether.

FWIW, there are proper graph building approaches in other places around the ecosystem.

https://ocefpaf.github.io/python4oceanographers/blog/2014/11/17/networkX/
https://github.com/conda/conda-concourse-ci

I just haven't had time to refactor conda-build to use one of these better approaches.  The latter link there is a project that writes input to a CI system, which uses conda-build to do each individual build.

**Comment by Zaharid** [comment]
I'm working on graph processing logic as well! See:

https://github.com/NNPDF/reportengine/blob/master/src/reportengine/resourcebuilder.py

**Comment by msarahan** [comment]
Nice @Zaharid - graphs are definitely useful.  I hope I'll have time soon to do that refactor.

**Comment by Zaharid** [comment]
Basic logic for executing dependencies in parallel and sequentially is here:

https://github.com/NNPDF/reportengine/blob/master/src/reportengine/dag.py#L140

This solves a similar problem, so may be useful.

**Comment by msarahan** [comment]
Sure, thanks for the pointers.  Out of curiosity, why did you choose to reimplement the graph stuff, rather than use NetworkX or something like it?  This is kind of a running curiosity at Continuum, where several projects have made the same choice, for one reason or another.

**Comment by Zaharid** [comment]
Mostly because I didn't find how to write this dependency_resolver thing
easily with networkX: I have something that unblocks pending tasks once
some random task has completed (e.g. to run in parallel). Also I want a
simple mapping between nodes a values (and want to assume that values are
unique). Networkx seems a little too general for this task so some simple
things get complicated.

**Comment by msarahan** [comment]
Ah, yes.  I guess I never encountered that because I stop shy of actually executing the graph.  I instead leave that to Concourse to figure out.  Cool, I'll be sure to remember your code if/when I get to implementing something for conda-build.
