### ISSUE TITLE
Support all PEP 440 release specifiers (i.e., ~=)

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#1590]
Conda-build currently only supports the [version specifiers](https://www.python.org/dev/peps/pep-0440/#version-specifiers) `==`, `!=`, `>` , `<`, `>=`, `<=`, but not `~=`.

The idea of [compatible releases](https://www.python.org/dev/peps/pep-0440/#compatible-release) is nearly the same as conda-build's `*` syntax (e.g., `python 3.6*`), but more powerful. `~=1.4.5` for example means "the 1..4 release, but at least 1.4.5" (`>=1.4.5,==1.4.*). This is currently not expressable in conda-build and hinders porting of pypi-packages that use this in their setup.py.

**Comment by msarahan** [comment]
Good idea.  I'm implementing stuff like this in #1585.  Right now, what I have as the expression for this is a version pin using Jinja2, like:

```
requirements:
  build:
    - python  {{ compatible('python', '3.5') }}
```

**Comment by ebolyen** [comment]
I just wanted to drop in and mention that we're having issues using `==X.Y.*` (which setuptools uses just fine) and is part of PEP440. We can install with `package=X.Y.*` on the cli but it just doesn't work in the recipe (and using a single `=` causes it to hang forever). 

We can match the behavior with `package X.Y*` (no operator at all) for now.
