### ISSUE TITLE
Problem: When using --skip-existing with --output-folder it fails for skipped packages

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#1591]
conda-build tries to copy the package to the output folder even if it got skipped by the `skip: True` is specified

**Comment by gabm** [comment]
The same applies to: --skip-existing

**Comment by msarahan** [comment]
Thanks for reporting.  I think I fixed this in refactoring done in #1576 - please reopen this issue if it still occurs after the 2.1.0 release (coming later today).
