### ISSUE TITLE
packages without "Lib" on windows, but not on Mac or Linux

### ISSUE THREAD

**Issue by BjornFJohansson** [conda/conda-build#1605]
I have a set-up where I build packages on three different CI servers for different platforms:

* DroneIO and CircleCI builds linux packages
* Travis builds MacOSX packages
* Appveyor builds windows packages

The set up is using Miniconda for each platform and the same meta.yaml is used.

The problem is that the windows packages lack the Lib directory and jusat contain the info directory. The Mac and Linux packages seem ok. The weird thing is that the packages pass all the tests during the build phase. Trying to install them give no error until trying to import the packages.

The packages are [here](https://anaconda.org/BjornFJohansson/pydna/files) . The version 1.0.2 is the last good one and the windows packages lack the Lib dir for 1.1.1, 1.1.4, 1.1.5 and 1.1.6a4. 

The last good one was built on linux and then converted. conda-build 2.0.4 was used for this.

The bad builds were done on:

- conda-build 2.0.10              pydna 1.1.1 [build](https://ci.appveyor.com/project/BjornFJohansson/pydna/build/1.0.412)
- conda-build 2.0.12              pydna 1.1.4 [build](https://ci.appveyor.com/project/BjornFJohansson/pydna/build/1.0.486)
- conda-build 2.0.12              pydna 1.1.5 [build](https://ci.appveyor.com/project/BjornFJohansson/pydna/build/1.0.489)
- conda-build 2.1.0beta1       pydna 1.1.6a4 [build](https://ci.appveyor.com/project/BjornFJohansson/pydna/build/1.0.511)

The last conda-build was pip installed from the conda-build git repo to see if it makes a difference (does not seem like it). The builds are run by this [script ](https://github.com/BjornFJohansson/pydna/blob/py3dev/ci.sh) on all platforms.

I have experienced problems before uisng conda-build, but they did not pass silently.
I can at least not tell from the build outputs outputs (see build links above) that the builds failed 
so catastrophically. Here is my [meta.yaml](https://github.com/BjornFJohansson/pydna/blob/py3dev/meta.yaml)

At this point I do not know what to do except build on linux and then convert. Can someone knowledgeable show me the the right direction.

I would be very grateful for help on this matter!

**Comment by msarahan** [comment]
Using bash scripts is more complicated.  You are launching a shell within a
shell, and the environment variables are probably not being carried
through.  Try to echo some of the variables you expect to be set and make
sure that they are what you expect.  Next, those variables are almost
certainly in Windows path format.  You probably need to do extra work to
translate paths, or at least make sure that MSYS2 is doing the automatic
path translation correctly, so that any UNIX tools you are using are
getting meaningful input.

This is not an official feature of conda-build right now, so I can't offer
you further support.  @mingwandroid may have more tips for you.

**Comment by BjornFJohansson** [comment]
Thanks for the input! 
All of the variables are set as far as I can see and the script executes perfectly without any errors.
Does this mean that conda-build does not really work on windows yet?

**Comment by msarahan** [comment]
No, Conda build works fine on windows, but it's only tested with bat file input, not Unix sh input.  That is something that @mingwandroid has wanted for some time. Maybe he'll have more input on what might be going wrong.  Basically, you'll need to do a lot of debugging outputs showing the contents of the build prefix at each step, especially the end of your script.  If the files really are created in the build prefix, this could be a bug, but conda build has been making good packages on Windows for a long time.

**Comment by BjornFJohansson** [comment]
Ok, Ill probably make a bat file to run on appveyor for now. Thanks for the input.

**Comment by msarahan** [comment]
Cool. Tip: you can make a very simple bat file that just runs your build.sh file with bash. You just can't count on conda build to run build.sh by itself on windows.

**Comment by mingwandroid** [comment]
I figure it'd be pretty easy to allow build.sh on Windows too. I just didn't want to force msys2 on everyone as some people have an aversion to trying to force POSIX where it's not really a natural fit. 

Me, I don't care for those arguments, pragmatism trumps such philosophical musings IMHO.

I would be interested in continuing to explore making msys2 bash a first class citizen from conda-build's perspective when I have time, but only if there's concensus that it's the right thing to do.

**Comment by msarahan** [comment]
With Microsoft getting rid of cmd.exe, I find MSYS2 to be a nicer, more immediate fix for us than PowerShell. I support MSYS2 POSIX as a first class method, up to and including the posix metapackage as a dependency for conda build on windows.

**Comment by BjornFJohansson** [comment]
Just to see if I understood this correctly:
My appveyor.yml says:
```
install:
- bash ci.sh
```
The ci.sh file says 
`conda build . `
And the fact that conda is launched from within a bash script confuses the paths so that the Lib directory is not included.
my current build.bat is this 
```
"%PYTHON%" setup.py build
"%PYTHON%" setup.py install
if errorlevel 1 exit 1
```
how could I modify it to work in my setup while not breaking it for someone who wants to build on windows without bash?

**Comment by BjornFJohansson** [comment]
```
bash build.sh
rem "%PYTHON%" setup.py build
rem "%PYTHON%" setup.py install
if errorlevel 1 exit 1
```
This did not work as build.bat. The packages still have no Lib and no error msg.
appveyor [build](https://ci.appveyor.com/project/BjornFJohansson/pydna/build/1.0.520)
[appveyor.yml](https://github.com/BjornFJohansson/pydna/blob/py3dev/appveyor.yml)
[ci.sh](https://github.com/BjornFJohansson/pydna/blob/py3dev/ci.sh)

**Comment by msarahan** [comment]
Sorry this isn't working so well for you.  You have a file in your recipe, build.bat.  Unfortunately, conda-build won't use that.  It wants a file named bld.bat.  I think it's still failing because you are effectively not telling it to do anything at all.  It really should warn about that.

**Comment by BjornFJohansson** [comment]
right! now it works! thanks!
I suppose my bld.bat would fail on a windows machine that does not have bash installed.
Is it possible to create a fallback? I dont now much about batch scripting, but if anyone has a tip?

**Comment by mingwandroid** [comment]
`bld.bat` is a batch file, I guess you meant `build.bat` here? Yes, different bash / posix runtime implementations will search different file suffixes in different orders so it would be basically random whether `build.sh` or `build.bat` got run, and that's why the filename (minus the extension) is different.

**Comment by BjornFJohansson** [comment]
my bld.bat looks like this:

```
bash build.sh
rem "%PYTHON%" setup.py build
rem "%PYTHON%" setup.py install
rem if errorlevel 1 exit 1
```

So I it will surely fail if bash is not installed. The bld.bat could perhaps test if bash is installed
and run the commented out lines if not.

I am not sure what the difference between build.bat and bld.bat would be?

**Comment by mingwandroid** [comment]
If you want to use `bash` on Windows, and guarantee that a known version is available at build-time, you can add the `posix` package as a build requirement. This is a metapackage for a some `msys2` packages that provides a reasonable amount of POSIX software.
