### ISSUE TITLE
Windows compiler not properly activated on python 2.7/64-bit

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#1606]
I tried building a package on appveyor without using the widely-available `CMD_IN_ENV` for activating the appropriate compiler since conda build now does the activaation itself.

This succeeded (i.e. the package built) for python 3.5 and 3.5 but not for python 2.7. 

On python 2.7 I got a (see below for correct links) ~~[vcvarsall.bat not found](https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.150#L730) followed shortly by [`command 'cl.exe' failed: No such file or directory`](https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.150#L825)~~.

The repo/PR in which I'm doing the building is https://github.com/astropy/conda-channel-astropy/pull/110

If you want me to test out fixes to the issue when those are available, let me know.

ping @jakirkham 

Edit: Correct links, for a run with conda build 2.0.10:

[vcvarsall.bat not found](https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.350/job/47dv4sn3ydhd26f7#L861) followed shortly by [`command 'cl.exe' failed: No such file or directory`](https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.350/job/47dv4sn3ydhd26f7#L925)

**Comment by msarahan** [comment]
@mwcraig I have no idea what conda-build version is actually in use here.  It looks like it might be 1.21.5: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.150#L213

Could you please test this with the current stable release (2.0.12) or the coming 2.1.0 release?  The 2.1.0 release is available on conda-canary:

conda install -c conda-canary conda-build

Note that this will also install conda's canary by default.  It may not work.  You may need to disable the automatic update of conda.

**Comment by mwcraig** [comment]
@msarahan -- sorry about that, no idea how I ended up linking to those (really old) appveyor runs. Meant to link to ones with conda build 2.0.10 that I ran last week.

I get the same failure with conda build 2.0.12; note that this is running with python 3.4 miniconda for all of the the python builds. 

conda build version:  https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.380/job/xgr6eo5fwlno0h3b#L191

vcvarsall.bat fail: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.380/job/xgr6eo5fwlno0h3b#L298

`cl.exe` fail: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.380/job/xgr6eo5fwlno0h3b#L362

**Comment by mwcraig** [comment]
fwiw, also fails with python 2.7/conda build 2.0.12. Up next will be canary...

conda build version: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.381/job/fwy2dr5lg78ud0e8#L180

vcvarsall.bat fail: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.381/job/fwy2dr5lg78ud0e8#L286

`cl.exe` fail: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.381/job/fwy2dr5lg78ud0e8#L350

**Comment by mwcraig** [comment]
@msarahan -- the last case (canary) is below. It fails, but for a reason unrelated to the compiler settings (it never gets that far).

conda build version: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.382/job/nkny1ql31iy7nh6p#L239

error when extracting download: https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.382/job/nkny1ql31iy7nh6p#L271

**Comment by msarahan** [comment]
OK, I think I see what's going on.  In conda-build's appveyor, we do this: https://github.com/conda/conda-build/blob/master/appveyor.yml#L65

This appears to unify things.  It should be possible to handle this somehow without that copying, though I'm not certain that is the best approach.  This copying was done to fix cmake.  I'm not certain that without that copying, cmake will still work.  There was some attempt at conda-forge to do this copying: https://github.com/conda-forge/staged-recipes/pull/1678
https://github.com/conda-forge/staged-recipes/pull/1678/files#diff-6dbcad11e166ec6943bf1b047c126a58R16

Can you use that conda-forge package on appveyor?

**Comment by msarahan** [comment]
PS, regarding canary, thanks, I think I fixed that issue in #1615

**Comment by mwcraig** [comment]
@msarahan -- thanks, the copy alone does the job for what I need (though the `vs2008_express_vc_python_patch ` package also works).

**Comment by msarahan** [comment]
Thanks for the verification @mwcraig.  I think the major issue here is Appveyor's strange setup, with VS 2008 express and then VC++ for Python 2.7 layered on top.  Unfortunately, @patricksnape didn't have luck convincing the Appveyor team to apply this fix by default in their images.

**Comment by mwcraig** [comment]
Is the correct fix then to use the conda-forge package on appveyor and not try to fix in conda build? That seems like an improvement over the current situation (running the CMD_IN_ENV script) since the conda-forge package at least acts as a central place to manage the patches. 

Looking forward to 2020 more and more...

**Comment by msarahan** [comment]
I'm not sure it's the correct fix.  It's the fix I'd like to say is official.  A fix in conda-build would be better if we could also manage to make cmake work all of the time.  Unfortunately, I think that's just a bigger project than the payoff warrants.

**Comment by patricksnape** [comment]
Yes unfortunately that conda package patch was the best workaround we could come up with. The only other thing we could do would be to warn if we think we can't find the correct compiler so that it's more obvious that something else needs to be done.

**Comment by jakirkham** [comment]
FYI at conda-forge we are planning to run the patch step as part of the setup for Windows. For details, please see PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/48 ).
