### ISSUE TITLE
Add ability to audit licenses of dependency packages

### ISSUE THREAD

**Issue by necaris** [conda/conda-build#1617]
Along the lines of [Yarn's license commands](https://yarnpkg.com/en/docs/cli/licenses), it would be great if `conda build` could also give a package builder information about the licenses of their dependencies.

**Comment by msarahan** [comment]
Yes, this would be nice to have.  I'll try to work this in at some point, but there is quite a bit of work on other things that has priority right now.  Pull requests welcome in the meantime.

**Comment by necaris** [comment]
Completely not expecting this to be a high priority. I've had to do something similar for an internal project so expect a PR from me to resolve.
