### ISSUE TITLE
conda-build Python 2 packages missing enum34 requirement

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1623]
It appears `conda-build` 2.1.0 requires `enum34` for Python 2.7 as can be seen in the [code]( https://github.com/conda/conda-build/blob/2.1.0/conda_build/conda_interface.py#L27 ) and the [recipe]( https://github.com/conda/conda-build/blob/2.1.0/conda.recipe/meta.yaml#L28 ) in this repo. However, when I install and try to use `conda-build` on Python 2.7, I find that `enum34` is not pulled in, which results in [`ImportError`s]( https://travis-ci.org/jakirkham/conda-smithy/jobs/189235002#L434-L436 ). Have extracted copies of the `conda-build` package (links below). They all appear to be missing `enum34`. Here's an example.

```json
{
  "arch": "x86_64", 
  "build": "py27_0", 
  "build_number": 0, 
  "depends": [
    "conda >=4.1", 
    "conda-verify", 
    "contextlib2", 
    "filelock", 
    "jinja2", 
    "patchelf", 
    "pkginfo", 
    "pycrypto", 
    "python 2.7*", 
    "pyyaml"
  ], 
  "license": "BSD 3-clause", 
  "license_family": "BSD", 
  "name": "conda-build", 
  "platform": "linux", 
  "subdir": "linux-64", 
  "version": "2.1.0"
}
```

ref: https://repo.continuum.io/pkgs/free/linux-32/conda-build-2.1.0-py27_0.tar.bz2
ref: https://repo.continuum.io/pkgs/free/linux-64/conda-build-2.1.0-py27_0.tar.bz2
ref: https://repo.continuum.io/pkgs/free/osx-64/conda-build-2.1.0-py27_0.tar.bz2
ref: https://repo.continuum.io/pkgs/free/win-64/conda-build-2.1.0-py27_0.tar.bz2
ref: https://repo.continuum.io/pkgs/free/win-32/conda-build-2.1.0-py27_0.tar.bz2

cc @ocefpaf

**Comment by msarahan** [comment]
Yes, it looks like @ilanschnell has applied a fix.  Thanks @ilanschnell

**Comment by jakirkham** [comment]
Awesome. Thanks Ilan.
