### ISSUE TITLE
conda build 2.1 trying to run tests multiple times?

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-build#1624]
I'm seeing a regression between conda build 2.0 and conda build 2.1. I think it _might_ be related to #1581 or similar changes, but that's only because I was surprised to see that when I looked at the log output. Unfortunately this is a customer build so I can't share a whole lot, but let me start with this snippet, and let me know if there's any more info I can pull for you. This is using conda 4.2.13, by the way.

```
+ source /home/ubuntu/miniconda/bin/activate /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/_t_env
+ /bin/bash -x -e /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/test_tmp/run_test.sh
+ JUNIT=/tmp/circle-junit.UBdLLJz
+ COV=/tmp/circle-artifacts.5SW2jS5
+ mkdir -p /tmp/circle-junit.UBdLLJz /tmp/circle-artifacts.5SW2jS5
+ py.test -v --junitxml=/tmp/circle-junit.UBdLLJz/junit3.xml --cov-report html:/tmp/circle-artifacts.5SW2jS5/htmlcov3 /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/work --spec
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/_t_env/bin/python
cachedir: ../.cache
rootdir: /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334, inifile: 
plugins: cov-2.3.1, spec-1.0.1
collected 0 items 

----------- generated xml file: /tmp/circle-junit.UBdLLJz/junit3.xml -----------
========================= no tests ran in 0.00 seconds =========================
TEST START: packagexxx-v0.1.1-py_63
Deleting work directory, /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/work
updating index in: /home/ubuntu/miniconda/conda-bld/linux-64
updating index in: /home/ubuntu/miniconda/conda-bld/noarch

+ source /home/ubuntu/miniconda/bin/activate /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/_t_env
+ /bin/bash -x -e /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/test_tmp/run_test.sh
+ JUNIT=/tmp/circle-junit.UBdLLJz
+ COV=/tmp/circle-artifacts.5SW2jS5
+ mkdir -p /tmp/circle-junit.UBdLLJz /tmp/circle-artifacts.5SW2jS5
+ py.test -v --junitxml=/tmp/circle-junit.UBdLLJz/junit3.xml --cov-report html:/tmp/circle-artifacts.5SW2jS5/htmlcov3 /home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/work --spec
/home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/test_tmp/run_test.sh: line 5: py.test: command not found
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 1324, in test
    subprocess.check_call(cmd, env=env, cwd=config.test_dir)
  File "/home/ubuntu/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/ubuntu/miniconda/conda-bld/conda-recipe_1483572006334/test_tmp/conda_test_runner.sh']' returned non-zero exit status 5
```

**Comment by mcg1969** [comment]
So it's obvious why the second attempt to run the tests would fail---the work directory has been removed.

**Comment by mcg1969** [comment]
Here's what 2.0 does:
```
+ source /home/ubuntu/miniconda/bin/activate /home/ubuntu/miniconda/conda-bld/conda-recipe_1483633292427/_t_env
+ /bin/bash -x -e /home/ubuntu/miniconda/conda-bld/conda-recipe_1483633292427/test_tmp/run_test.sh
+ JUNIT=/tmp/circle-junit.QO1NOoP
+ COV=/tmp/circle-artifacts.Y3kekFH
+ mkdir -p /tmp/circle-junit.QO1NOoP /tmp/circle-artifacts.Y3kekFH
+ py.test -v --junitxml=/tmp/circle-junit.QO1NOoP/junit3.xml --cov-report html:/tmp/circle-artifacts.Y3kekFH/htmlcov3 /home/ubuntu/miniconda/conda-bld/conda-recipe_1483633292427/work --spec
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /home/ubuntu/miniconda/conda-bld/conda-recipe_1483633292427/_t_env/bin/python
cachedir: ../work/.cache
rootdir: /home/ubuntu/miniconda/conda-bld/conda-recipe_1483633292427/work, inifile: setup.cfg
plugins: cov-2.3.1, spec-1.0.1
collected 146 items 
tests/test_config.py
<<<<REDACTED>>>>
----------- generated xml file: /tmp/circle-junit.QO1NOoP/junit3.xml -----------
----------- coverage: platform linux, python 3.5.2-final-0 -----------
Coverage HTML written to dir /tmp/circle-artifacts.Y3kekFH/htmlcov3
============================ pytest-warning summary ============================
WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
================ 146 passed, 1 pytest-warnings in 7.23 seconds =================
TEST END: packagexxx-v0.1.1-py_64
# If you want to upload this package to anaconda.org later, type:
```
It's odd that with 2.1, py.test isn't seeing any of the tests.

**Comment by msarahan** [comment]
Do you have a test/source_files section?  Conda 2.1 removes the work folder
before testing as a safety verification.  @asmeurer changed that, because
he got tripped up having tests that succeeded where they should not have.

Anything from test/source_files should be copied and kept despite that
removal.

**Comment by mcg1969** [comment]
OK, that's news to me. It would have been nice to deprecate that more gently. :-(

**Comment by mcg1969** [comment]
What's the environment variable that points to these files, then? We're using `SRC_DIR` to point `py.test` to the right place.

**Comment by msarahan** [comment]
Those files are in the testing work directory, which is the folder that the test scripts run from.  So you just need to remove SRC_DIR and use relative paths.

**Comment by msarahan** [comment]
If you have ideas for how to implement a deprecation warning for this, I'd like to implement it.  It's not at all clear to me how to warn someone about this.  Maybe do a regex search in test scripts for SRC_DIR?

**Comment by mcg1969** [comment]
Yes, that sounds right. Alternatively, I'm not sure if this is possible or not, but one could scan for references to SRC_DIR (or its expanded value) in stderr. 

Granted, I'm biased here because this problem happened to my customer, but this is hard to interpret as anything but a serious regression. I understand Aaron's issue, but calling `py.test` on the source directory seems such straightforward thing to do that one certainly must expect this is going to break things.

And unfortunately, every CI test script that does "conda install conda-build" with no version pinning is going to get bit every time this kind of breaking change happens. Given that breaking changes are certainly unavoidable---the consequence of providing much-needed features and fixes---we may need to encourage people to pin to particular x.x versions of conda-build when constructing CI scripts.

**Comment by mcg1969** [comment]
Just as a sanity check I talked with my officemate about this. He agrees both that this is going to cause havoc for people, including his own projects; and that Aaron's issue is also valid and has caused him problems.

So our mutual conclusion is that the change in behavior was necessary, but that the silent change is problematic. Hopefully we can find a way to warn people.

**Comment by neok-m4700** [comment]
Hi, there is an attribute in conda_build.config, 'keep_old_work' that has been unused for sometimes, and I'm wondering if it couldn't be used to rename the work directory instead of deleting it.

This leaves the choice to override the default behavior since keep_old_work is by default set to False.

One possible implement could be like this [patch](https://github.com/neok-m4700/conda-build/commit/43abeba6a42b4a7ebdffceabe8efaf3578a28b3a.patch)

**Comment by mcg1969** [comment]
Well, what would happen if we simply passed a wilcard to `source_files`?

**Comment by msarahan** [comment]
If you use a wildcard, the SRC_DIR will still be invalid.  All of the source files would be copied into the testing work directory.  I can have SRC_DIR point instead to the testing workdir, that way you'll at least need less recipe changes.  You'd still need to set test/source_files to the wildcard.

**Comment by neok-m4700** [comment]
```yaml
test:
  source_files:
    - *
  commands:
    - conda inspect linkages $PKG_NAME
```

is giving jinja2 parsing error:
Unable to parse meta.yaml file

but this is working:
```yaml
test:
  source_files:
    - '*'
  commands:
    - conda inspect linkages $PKG_NAME
```

but in my case I'd like to be able to modify the deletion with a parameter, and not modify every recipe I work on ...

**Comment by msarahan** [comment]
@neok-m4700 I will also add a command line parameter to disable the automatic removal of the work dir.  It will default to removal, though.

**Comment by neok-m4700** [comment]
Thanks @msarahan , this isn't a problem since I always use conda build through it's api: conda_build.api.build(recipe) and can easily override the default configuration or context ...

**Comment by mcg1969** [comment]
I'm already committed to changing my recipes to suit the new regime anyway, so I'm not worried. Indeed, rarely should one need the _entire_ package. Even if you want the full source for some strange reason it will be sitting in a subdirectory.
