### ISSUE TITLE
conda-build 2.x uses longer recipe build dir

### ISSUE THREAD

**Issue by jschueller** [conda/conda-build#1631]
when swichting to 2.x the conda recipe build directory changed from .../conda-bld/work/... from .../conda-bld/recipe_[unixtime], which is somewhat longer

on windows this prevents from building boost, see issue in: 
https://github.com/conda-forge/boost-feedstock/pull/27

is there a quick work-around ?

cc @isuruf

**Comment by msarahan** [comment]
There's a flag to use the old behavior:

```
  --no-build-id         do not generate unique build folder names. Use if
                                 having issues with paths being too long.
```

**Comment by jschueller** [comment]
cool!
