### ISSUE TITLE
Conda 4.3 compatibility

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1650]
Summary of causes for incompatibility with conda 4.3 at present.

1. Resolve class lost its "get_pkg" method: https://travis-ci.org/conda/conda-build/jobs/190827542#L1088
2. package_cache() has been neutered: https://travis-ci.org/conda/conda-build/jobs/190827542#L1155

Really, those look like the only major things.  They just kill lots of tests...  Oh, to have time to refactor the test suite...

CC @kalefranz

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/4266

**Comment by kalefranz** [comment]
ok have initial attempts for fixes for both 1 & 2 on #4266

**Comment by msarahan** [comment]
Thanks, things are looking better.  Here's some ideas on the remaining failures:

test_recipe_builds[noarch]: no ideas yet.  Will revisit.
test_binary_has_prefix_files: looks like a conda lock issue.  Not sure why you're seeing this - you aren't even running the tests in parallel, are you?  Are you completely certain that your locks are getting cleaned up and that no part of the process is being done asynchronously?
test_relative_git_url_submodule_clone: This one looks like you're removing or clobbering environment variables somehow.  The test sets these git settings with environment variables: https://github.com/conda/conda-build/blob/master/tests/test_api_build.py#L470
test_recipe_builds[post_build_versioning]: Looks like maybe a connection error that needs better error handling (in conda).
test_recipe_builds[always_include_files_glob]: another lock error
test_recipe_builds[source_path]: this one looks totally wrong.  That work folder should be in a "build folder" of the form (recipe dir)_(timestamp).  I need to check myself why this might be, but it points to a pre-2.0 conda-build version in use, or a strange bug.
test_render_setup_py_old_funcname: again, indicative of the wrong version of conda-build in use.
test_skip_existing: This gets the index, and tries to find the package in that index.  Has the format of the index changed?  https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1616
test_render_setup_py_old_funcname: points to conda-build 1.21.5 being the actual version of conda-build in use, somehow

I think I'm seeing that you have the same problem with conda-build that you did with conda: you seem to be testing with a version other than the one you expect.  I'll take a look at your Travis setup script in a little while to see if I can see where that might be happening.

**Comment by kalefranz** [comment]
Ok, I was running tests in parallel.  Disabling that helped.

Latest is that 1. isn't running all the tests (only ~90).

2.0.12: https://travis-ci.org/conda/conda/jobs/191054237
`11 failed, 243 passed, 4 skipped, 3 xfailed, 4 pytest-warnings`

2.1.1: https://travis-ci.org/conda/conda/jobs/191054233
`10 failed, 225 passed, 3 skipped, 2 xfailed, 4 pytest-warnings`

**Comment by kalefranz** [comment]
I would drop `test_sign` from conda-build.  I removed support for it in `conda 4.3`.  There's a paragraph about it and why in the `4.3.0` changelog.

**Comment by kalefranz** [comment]
Ok fixed a couple of errors based on the latest results.  Let's see where that gets us.

**Comment by kalefranz** [comment]
> Has the format of the index changed?

Yeah, the key for index is a `Dist` object, not a `str`.  We might have to live with this failure.

**Comment by gabm** [comment]
The API incompatibility at the index cache has been discovered by me almost three weeks ago already: #1604

We're still suffering this bug in our CI services as it makes `--skip-existing` unusable. In my opinion it's not OK to release 2.1.1 with this major incompatibility. Also I think its not OK, to *live with this failure*... Sorry, but users rely on your software and breaking functionality by breaking internal APIs is not ok :cry:.
