### ISSUE TITLE
directories like xxx.git are removed from tarball

### ISSUE THREAD

**Issue by dfroger** [conda/conda-build#1655]
I'm trying to build a conda package for [craftr](https://craftr.net/), which contains a directory `craftr/stl/craftr.utils.git/` that is filtered out from the tarball during build. The problem is then detected in `tarcheck.py`. See https://github.com/conda-forge/staged-recipes/pull/2189

I think it comes from the [filter_files](https://github.com/conda/conda-build/blob/2.1.0/conda_build/build.py#L782-L788) function.

I'm working on a PR.

**Comment by msarahan** [comment]
Thanks. Naive of me to think that filter files would always work...

Looking forward to the PR.

**Comment by dfroger** [comment]
The cool thing is that `filter_files` already has unit tests :)
