### ISSUE TITLE
Relative path in source causes rm_rf to remove linked source files

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1661]
from https://github.com/conda/conda-build/pull/1598#issuecomment-272691858

@msarahan this commit (specifically these lines as found by running git bisect) - causes some odd behaviour - seen here. It seems that if you have a script in your project then the rm_rf call traverses the possibly? sym-linked script file and thus deletes the script in the original repository. This also may only be an issue for recipes built where the source is next to the recipe folder and thus copied using a relative path:

source:
  path: ../

To be clear:

After this commit, after the test phase the bin/lsfm script is deleted from inside the repository and not just from the work/build environment.

**Comment by patricksnape** [comment]
Thanks for adding as an issue - didn't raise in case something I did was wrong 😄

**Comment by jabooth** [comment]
@msarahan saw your request for feedback if you had caught the issue with #1684, I'm afraid I'm still seeing the same behaviour of scripts being deleted on conda build 2.1.2:

https://travis-ci.org/menpo/workerbee/jobs/195511033#L520

**Comment by msarahan** [comment]
Thanks @jabooth.  Using your recipe will help give me something of a start.
