### ISSUE TITLE
building gcc with conda build seems broken

### ISSUE THREAD

**Issue by rajatgirotra** [conda/conda-build#1663]
Here's the conda info:
`Current conda install:

               platform : linux-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/vagrant/miniconda2  (writable)
    default environment : /home/vagrant/miniconda2
       envs directories : /home/vagrant/miniconda2/envs
          package cache : /home/vagrant/miniconda2/pkgs
           channel URLs : file:///home/vagrant/conda_builds/linux-64
                          file:///home/vagrant/conda_builds/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/vagrant/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-514.2.2.el7.x86_64 CentOS Linux/7.3.1611 glibc/2.17
                UID:GID : 1000:1000
`

I am trying to build gcc 5.4.0. The build is fine. However conda build fails at the "test" step. It is unable to compile a simple hello world program.

I get the following error trying to run "gcc" executable from within "conda_builds/5.4.0_1484481584604/_t_env/bin/" : 
```
[vagrant@localhost bin]$ pwd
/home/vagrant/conda_builds/5.4.0_1484481584604/_t_env/bin
[vagrant@localhost bin]$ ./gcc
gcc: error: /home/vagrant/conda_builds/5.4.0_1484481584604/_t_env/lib/gcc/: Is a directory
[vagrant@localhost bin]$ 
```
This is not an issue if I run gcc from within the build directory:
```
[[vagrant@localhost bin]$ pwd
/home/vagrant/conda_builds/5.4.0_1484481584604/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
[vagrant@localhost bin]$ ./gcc
gcc: fatal error: no input files
compilation terminated.]([url](url))
```

Here's my recipe: 
[5.4.0.zip](https://github.com/conda/conda-build/files/707011/5.4.0.zip)

Also the checksums of gcc executable's do not match in the build and test folders. So looks like conda build is doing some transformation which isn't correct.

```
[vagrant@localhost bin]$ sha256sum gcc
d0f0f1c14f82cbde5f285af8214a789b2479ec3f5a06eb449fb87971415c195c  gcc
[vagrant@localhost bin]$ cd ../../_t_env/bin/
[vagrant@localhost bin]$ sha256sum gcc
12dd884cae5ed6fd0c4e4d6690a2d82b628fa08bcfc18d336ec9d85a3beb065f  gcc
```

**Comment by msarahan** [comment]
gcc has its own binary prefix replacement scheme.  You probably need to tell conda-build to not search for binary prefixes to replace.

Try this first: http://conda.pydata.org/docs/building/meta-yaml.html#detect-binary-files-with-prefix

If that doesn't work, try this next: http://conda.pydata.org/docs/building/meta-yaml.html#binary-relocation

**Comment by rajatgirotra** [comment]
Thanks @msarahan,

```
build:
  detect_binary_files_with_prefix: False 
```

fixes it
