### ISSUE TITLE
Failure to find osx-64 python.app during build test 

### ISSUE THREAD

**Issue by rayosborn** [conda/conda-build#1664]
I am submitting this as a new issue, although it is clearly related to #7, because this has just become a problem for my builds (https://github.com/nexpy/nexpy/blob/master/conda-recipe/meta.yaml but without commenting out the `osx_is_app` line), although they seemed to work fine a few months ago.

<details>
 <summary>Current conda install</summary>
  <pre><code>
              platform : osx-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.1
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/rosborn/anaconda  (writable)
    default environment : /Users/rosborn/anaconda
       envs directories : /Users/rosborn/anaconda/envs
          package cache : /Users/rosborn/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/nexpy/osx-64
                          https://conda.anaconda.org/nexpy/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/rosborn/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/2.7.12 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 938267710:660979062
  </code></pre>
</details>
<br>
The error is in running the test at the end, even though pythonw is installed in the test's bin directory.
<br>
<details>
 <summary>Error message</summary>
  <pre><code>
+ /bin/bash -x -e /Users/rosborn/anaconda/conda-bld/conda-recipe_1484588846841/test_tmp/run_test.sh
+ nexpy --help
/bin/bash: /Users/rosborn/anaconda/conda-bld/conda-recipe_1484588846841/_t_env/bin/python.app: No such file or directory
  </code></pre>
</details>
<br>
It looks to me as if the problem is that the code in post.py (https://github.com/conda/conda-build/blob/master/conda_build/post.py) tries to run python.app, but doesn't have pythonw as a fallback option if it's not there.

**Comment by msarahan** [comment]
I'm not actually sure that we can have fallbacks there - that's the shebang that is saying which executable to run.  I can certainly try to use pythonw on MacOS there rather than python.app, but I'm not sure exactly what the consequences of that are.  I think the key issue is that we need some way of distinguishing GUI-enabled programs from CLI-only programs.  If pythonw does not mess up CLI-only apps, then that is probably the best way forward.

**Comment by rayosborn** [comment]
I thought it would be possible to check if either python.app or pythonw exist within the bin directory before writing the shebang. It is only failing on the final test in a temporary environment that is deleted straight after the test, so it doesn't have to be particularly robust.

**Comment by msarahan** [comment]
Both python.app and pythonw come from the same package - the python.app package.  In fact, it appears that pythonw is nothing more than a link to python.app.  If one is missing, I would expect both to be missing.

I'm lost as to why we separate python.app and pythonw from the base python package.  We don't do that on Windows.  @ilanschnell can you comment on this discrepancy?

**Comment by ilanschnell** [comment]
Indeed `pythonw` and `python.app` are the same file.  The separation into the Mac OS X `python.app` conda package is done for (i) separation of concerns and (ii) historical reasons.

**Comment by rayosborn** [comment]
I haven't had time to test the #1669 yet, but it looks as if it would work. My pythonw file contains

    #!/bin/bash
    export PYTHONEXECUTABLE=/Users/rosborn/anaconda/bin/python
    /Users/rosborn/anaconda/python.app/Contents/MacOS/python "$@"

so it looks as if the problem is that, in post.py, the file path to python.app assumed it was in the `bin` directory, whereas, at least in my case, it is in the parent `anaconda` directory.
