### ISSUE TITLE
Future import issue in Python tests

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1668]
Ran into a future import issue when running using the default `run_test.py`. Seems there is a comment before the future import. Appears there is a second future import later in the same file.

```python
/zopt/conda2/conda-bld/recipe_1484678630264/_t_env/conda-bld/bdist_conda_1484678681338/_t_env/bin/python -s /zopt/conda2/conda-bld/recipe_1484678630264/_t_env/conda-bld/bdist_conda_1484678681338/test_tmp/run_test.py
  File "/zopt/conda2/conda-bld/recipe_1484678630264/_t_env/conda-bld/bdist_conda_1484678681338/test_tmp/run_test.py", line 30
    from __future__ import absolute_import, division, print_function
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by msarahan** [comment]
I don't think it's the comment.  30 lines of comments?  Can you please look at the run_test.py file there and post it here?

**Comment by jakirkham** [comment]
Yep, edited my comment. There is more going on than was immediately apparent. Am looking at this more closely.

**Comment by jakirkham** [comment]
After playing around a bit, this case is way more subtle. Was trying to run `conda-build` inside of a test step for a package (in this case also `conda-build`). The result was it appended to the same `run_test.py` file. So the tests from `conda-build` followed the tests from the new package being built.

Addressing this case feels more like an enhancement (and a rather advanced one) than a bug. Namely the ability to run `conda-build` recursively.

I'm going to go ahead and close this. Even if we do want to support such behavior, I think a better issue could be written for this case explicitly. Sorry for the noise.

**Comment by msarahan** [comment]
No problem, thanks for investigating.
