### ISSUE TITLE
conda develop should create environments from meta.yaml

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1677]
Would be nice if conda-develop operated on recipes - creating environments based on meta.yaml, and installing projects in develop mode.  Not clear how this generalizes from Python.

**Comment by bryevdv** [comment]
To be clear I don't want environments created for me, I want to get the lists of packages in various sections so that our test orchestration can create environments in whatever way is needed.

**Comment by bryevdv** [comment]
@msarahan I'm content if you want to close this. For completeness, we've moved on to this script which, altho slightly hacky, is short and simple and satisfies our needs:
```
import sys
import jinja2
import yaml


def load_setup_py_data():
    import os
    import setuptools
    os.environ['CONDA_BUILD_STATE'] = 'RENDER'
    data = {}

    def _setup(**kw): data.update(kw)
    setuptools.setup = _setup
    return data

meta_src = jinja2.Template(open("conda.recipe/meta.yaml").read())
meta_src = yaml.load(meta_src.render(load_setup_py_data=load_setup_py_data))

section = {
    "build": meta_src["requirements"]["build"],
    "run":   meta_src["requirements"]["run"],
    "test":  meta_src["test"]["requires"],
}

spec = []
for name in sys.argv[1:]:
    spec += section[name]

deps = ""
deps += " ".join(s for s in spec)
deps = deps.replace(' >=', '>=')  # conda syntax doesn't allow spaces b/w pkg name and version spec
deps = deps.replace(' <', '<')
deps = deps.replace(' [unix]', ' ')

print(deps)
```

**Comment by msarahan** [comment]
Thanks for pasting your script.  I'm leaving this open because it's still a long-term goal for conda-build.  People still post issues now and then about this.  It would be good to resolve sometime.
