### ISSUE TITLE
paths.json not updated during causing installation failure in conda 4.3.4

### ISSUE THREAD

**Issue by ElliotJH** [conda/conda-build#1678]
When converting from a win-64 package to a linux-64 package the `Lib/site-packages` directory should become `lib/python2.7/site-packages`. This is correctly updated in 'files' but should be updated in paths.json also. Otherwise this error is given when installing under conda 4.3.4 on Linux:

`
CondaError: Cannot link a source that does not exist. /home/NETWORK/e.hughes/miniconda3/pkgs/package-v1.0.0/Lib/site-packages/package-v1.0.0-py2.7.egg-info
`

**Comment by gomyhr** [comment]
This essentially means that any package built and converted with conda-build 2.1.x will be uninstallable by conda 4.3.x.

**Comment by gomyhr** [comment]
I guess I quick-fix would be if ``conda convert`` deletes ``paths.json`` when converting packages. IIRC, conda 4.3.x will then fall back to using "legacy" files (``files``, ``has_prefix``, etc.). But the real fix would be for ``conda convert`` to convert also ``paths.json``.

**Comment by kalefranz** [comment]
Commenting here so I can track also.  Limited bandwidth, but this seems like a high priority fix to me.  I'll jump on it if I get a chance.  `conda convert` is essentially broken until it's fixed.

@gomyhr You made me laugh. Evil hack. But you're absolutely right.  I'd rather fix `conda convert`.  The extra information in `paths.json` is going to become more and more important throughout 2017.
