### ISSUE TITLE
conda build try to remove "dat" folder

### ISSUE THREAD

**Issue by hainm** [conda/conda-build#1693]
Hi,

I got very weird deletion when using version `2.1.1`

My root folder is something like

```bash
$ ls .
AmberTools/src/conda-recipe
dat
```

`dat` folder has a file, e.g: `hello.c`.

If I run to conda build at root folder, all of the files in `dat/` folder will be deleted.
```
conda build AmberTools/src/conda-recipe
```

But if I did below, there won't be issue
```bash
cd AmberTools/src
conda build conda-recipe
```

Please see the attached folder (Note: you need to rename `.txt` to `.tar`)
[try.txt](https://github.com/conda/conda-build/files/725895/try.txt)

cheers
Hai

**Comment by msarahan** [comment]
I think this is the same as https://github.com/conda/conda-build/issues/1661, which I hope to address in https://github.com/conda/conda-build/pull/1715

Sorry this took a while to figure out...
