### ISSUE TITLE
Ctrl+C does not kill gcc

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#1705]
If I build a C-lib with conda-build, I can no longer cancel the build using `Ctrl-C`. Conda itself will die, but the compiler processes will continue to run. It looks like the signals are not (or no longer) forwared to all sub processes.

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.2
         python version : 3.6.0.final.0
       requests version : 2.12.5
             user-agent : conda/4.3.8 requests/2.12.5 CPython/3.6.0 Linux/4.8.15-200.fc24.x86_64 Fedora/24 glibc/2.23
```

**Comment by msarahan** [comment]
Confirmed.  Switching to conda 4.2.x fixes it for me.  Leaving this issue here until I can isolate it further.

**Comment by groutr** [comment]
https://github.com/conda/conda/pull/4045 might have clues.

**Comment by hainm** [comment]
confirmed the issue. :D
