### ISSUE TITLE
Wheel output based on build steps and meta.yaml

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1706]
presently, conda-build's support for wheels is based on just running bdist_wheel.  This is effectively just doing the build twice.  It would be better to make wheels be more simply a packaging process, though this may duplicate more code from setuptools/pip/wheel.

**Comment by msarahan** [comment]
This should also use the wheel packaging tools - delocate seems especially relevant: https://github.com/matthew-brett/delocate

**Comment by msarahan** [comment]
Punting to 3.1.0.  Need to get 3.0.0 out.

**Comment by jakirkham** [comment]
FWIW didn't seem to have any issues just reusing the build artifacts from building the conda package in the wheel packaging step. So FWICT this already works.

**Comment by msarahan** [comment]
what are your build steps?  what artifacts are you reusing?  I guess if the binaries or whatever are in the right build folder, then pip or wheel or whatever the tool is will find them?  In which case, we need to make sure that the conda builds come first, and that we also add in auditwheel or whatever extra repackaging is necessary.

**Comment by jakirkham** [comment]
Generally have documented in [this comment]( https://github.com/conda-forge/conda-smithy/issues/608#issuecomment-370359867 ) with links to specific examples. Comments welcome in that thread as well.

Right, think that wheel is able to find them afterwards. They roughly all look like [this]( https://github.com/conda-forge/numcodecs-feedstock/pull/17/files#diff-e178b687b10a71a3348107ae3154e44c ). The rest of the diff is re-rendering, which can be ignored.

**Comment by jakirkham** [comment]
Probably obvious, but guessing what I did won't work with build isolation. However build isolation would cause so many other problems that this would be merely another casualty on the list.

**Comment by jakirkham** [comment]
So the new `conda-build` worked on 64-bit, but failed on 32-bit. However I don't think the 32-bit failure is related to packaging wheels, but some other issue with `conda-build`.
