### ISSUE TITLE
conda skeleton pypi needs to support obtaining metadata from wheels, not just sdists

### ISSUE THREAD

**Issue by anandjeyahar** [conda/conda-build#1711]
conda version: 4.3.8(anaconda 3)
Ubuntu version: 16.04

Traceback (most recent call last):
  File "/home/anand/anaconda3/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/anand/anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 298, in main
    args_func(args, p)
  File "/home/anand/anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "/home/anand/anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 302, in execute
    import conda_build.pypi as pypi
  File "/home/anand/anaconda3/lib/python3.5/site-packages/conda_build/pypi.py", line 30, in <module>
    from conda.config import get_proxy_servers
ImportError: cannot import name 'get_proxy_servers'
conda skeleton pypi mxnet  1.78s user 0.11s system 98% cpu 1.911 total
[anand:~/playspace/oldToyProjects/conda_pkgs] 1 %

**Comment by msarahan** [comment]
What is the output of "conda info" ?

I think you probably have old versions of conda build but new versions of conda.  You probably need to update conda build.

**Comment by anandjeyahar** [comment]
Conda Info: output:


Current conda install:

> 
>                platform : linux-64
>           conda version : 4.3.11
>        conda is private : False
>       conda-env version : 4.3.11
>     conda-build version : 2.1.4
>          python version : 3.5.2.final.0
>        requests version : 2.12.4
>        root environment : /home/anand/anaconda3  (writable)
>     default environment : /home/anand/anaconda3/envs/analytics
>        envs directories : /home/anand/anaconda3/envs
>                           /home/anand/.conda/envs
>           package cache : /home/anand/anaconda3/pkgs
>                           /home/anand/.conda/pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/linux-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/linux-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/linux-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>             config file : /home/anand/.condarc
>            offline mode : False
>              user-agent : conda/4.3.11 requests/2.12.4 CPython/3.5.2 Linux/4.4.0-59-generic debian/stretch/sid glibc/2.23
>                 UID:GID : 1000:1000
> 
> conda info  1.13s user 0.06s system 97% cpu 1.212 total

**Comment by anandjeyahar** [comment]
I ran conda install -n root conda-build again. and then tried only to get this error.
> Error: Could not build recipe for mxnet. Could not find any valid urls

The command I tried after I got the error was:
`conda skeleton pypi --pypi-url https://pypi.python.org/pypi/mxnet/0.9.3a1 mxnet`

And same error again.

**Comment by msarahan** [comment]
The mxnet entry on PyPI has no source entry, only wheels.  We can't use just wheels.

https://pypi.python.org/pypi/mxnet

There is an existing package on anaconda.org: https://anaconda.org/derickl/mxnet/files

That's only built for osx, but the package contains the recipe (in the info/recipe folder), and you should be able to use that recipe to get you started on whatever platform you might need.

**Comment by softwaremechanic** [comment]
Thanks,.. I'll try that.. I need it on ubuntu.. I'll figure it out and release a package..
