### ISSUE TITLE
hardlinks in paths.json

### ISSUE THREAD

**Issue by groutr** [conda/conda-build#1714]
This relates to the discussion #1486.  I assume that `file_type` has been mapped to `path_type` in paths.json.  I've been updating my conda-tools project to support the new files present in newer conda releases.  I'm failing to comprehend how to represent `path_type`.  Since this file lives in the package cache, unless there is an hardlink or symlink between two files in the same package, this field should always be `regular`, right?

Given
```   {
      "_path": "lib/python3.5/site-packages/jinja2/visitor.py",
      "path_type": "hardlink",
      "sha256": "243d47d5c00d036f49727b457cde5f3f2a90c41e1b238c02d3407365af971e4b",
      "size_in_bytes": 3316
    }
```
Can you please elucidate what `hardlink` means this context? The way I understood the discussion (#1486) was that `path_type` would be for representing intrapackage hardlinks/symlinks, neither of which describes the type of this file.
```
% stat lib/python3.5/site-packages/jinja2/visitor.py
  File: `lib/python3.5/site-packages/jinja2/visitor.py'
  Size: 3316            Blocks: 51         IO Block: 524288 regular file
 Inode: 2131360572  Links: 1
```

@soapy1 @msarahan

**Comment by msarahan** [comment]
sorry @groutr I don't honestly know what @kalefranz and @soapy1 were thinking here.  I'll bug @kalefranz in the office if he doesn't chime in here soon.

**Comment by groutr** [comment]
ping @kalefranz

**Comment by msarahan** [comment]
@groutr I spoke with @kalefranz about this.  Here's what he explained to me:

1. The original intent was that any file with only one inode would be called "regular."  
2. @ilanschnell was of the opinion that there should not be a whole separate file type for files with only one inode - the fact that it has an inode is what makes it a "hardlink"

So, here we are: we just don't treat regular files differently from "hardlinks" - but the information is available to Conda about intra-package hard-links based on the count of entries in the "inode_paths" key.  If you want to dig further, here's a good starting place: https://github.com/conda/conda-build/blob/master/conda_build/build.py#L586-L587

Good enough?  or does this need further discussion?
