### ISSUE TITLE
conda-convert does not update entry points in paths.json

### ISSUE THREAD

**Issue by gomyhr** [conda/conda-build#1718]
After PR #1701, issue #1678 is half-way fixed. However, the bat-file entry points created by linux-to-win conversion are not included in ``paths.json``. For those, all the keys (``"_path"``, ``"sha256"``, ``"path_type"``, ``"size_in_bytes"``, etc.) need to be set in the same way as conda-build does.

This means that packages with entry points converted from linux to windows are still uninstallable with conda 4.3.x. I just confirmed this with the package generated by 

    py.test tests/test_api_convert.py::test_convert_from_unix_to_win_creates_entry_points

(on conda-build commit e92e8fdab8a5bc3b47bd3bd947df8c17faeb8bf9 on linux), installing with conda 4.3.9 on Windows.

**Comment by msarahan** [comment]
Sorry about this. I should have done more cross platform testing. I'll fix it today.
