### ISSUE TITLE
Additional Architectures in Skip clause

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#1723]
We have some custom builds of conda running that have additional architectures defined in conda. That works fine so far. Now we stumbled across a problem, that we want to skip some of the builds for some platforms. Namely we want to do this:

```
build:
  skip: True #[aarch64]
```

That works very well on our custom/patched aarch64 build as this architecture is added to `non_x86_linux_machines` and therefore known. However, it interferes with the other conda distributions on windows/linux that are supported by continuum itself. These platforms don't know about aarch64 and therefore produce a crash in `metadata.py:114`. 

As we don't really want to go into the process of shipping patched versions of these platforms as well, maybe we could provide a PR to solve this? I'd suggest to evaluate unknown selectors to `False` and letting the user know that there was an unknown selector. Additionally we could add a command-line flag (`--ignore-unknown-selectors`) to switch on the new behavior to not break the API..

@msarahan What do you think?

**Comment by msarahan** [comment]
PR is welcome.  The selectors are very hard-coded and not terribly friendly.  I would really like any work that builds towards making them more flexible - especially if you can use Jinja2 expressions to dynamically code selectors.  Not sure if that's already possible - might be, but might not be due to order of operations (templating before or after selectors applied?)

**Comment by gabm** [comment]
I'd almost say that templating is done before selectors, but I'll check that again and confirm.

Do you think we'd have to keep APIs stable? in this matter. I mean by default? Evaluating unknown selectors to `False` will change the current behavior. It will lead to side effects like typos (e.g. `win3` instead of `win32`} being evaluated to `False` instead of throwing an error...

**Comment by msarahan** [comment]
@gabm is this resolved by #1753?  Can I close this issue?

**Comment by gabm** [comment]
yes.. thats solved.. works as expected!
