### ISSUE TITLE
`conda build invalid/path` should fail with nonzero exit status

### ISSUE THREAD

**Issue by kernc** [conda/conda-build#1724]
conda-build exits with return status 0 and with no error printed if ran as, for example:
```bash
$ conda build what-the-fuck-is-this-shit
$ 
```
This is very misleading. The user expected something conda-build obviously couldn't deliver, so it should issue an error and set exit status != 0.

**Comment by msarahan** [comment]
Thanks for reporting. I know I've fixed this, but afraid I did so on a long running branch. Will find and port ASAP.

**Comment by kernc** [comment]
A broader issue spanning subcommands: https://github.com/conda/conda/issues/4512

**Comment by msarahan** [comment]
Fixed in #1585
