### ISSUE TITLE
anaconda navigator won't open

### ISSUE THREAD

**Issue by mlandaverde95** [conda/conda-build#1727]
I recently downloaded the newest anaconda for mac os but whenever I open it, it'll remain on the initializing then it will stop working and nothing happens after that.

**Comment by msarahan** [comment]
I don't understand why you submitted this issue to this repository.  Conda-build is a package building tool.  I think this is the appropriate issue for you to follow: https://github.com/ContinuumIO/anaconda-issues/issues/1413

Closing.
