### ISSUE TITLE
test/source_files should support recursive globs

### ISSUE THREAD

**Issue by filmor** [conda/conda-build#1730]
In Python >=3.5 there is a `recursive` flag that can be passed to `glob.glob`, allowing for patterns like `**/tests` which would simplify specifying `test/source_files` for us quite a bit.

**Comment by msarahan** [comment]
That's a great idea. Are you aware of any way to backport this to earlier python versions? Conda build can't be python 3.5+ only, unfortunately. Any support for this has to have graceful error handling at least for earlier python versions.

If you have time, please consider submitting a PR. Not sure when I'll have time to do this myself.

**Comment by filmor** [comment]
There is this package https://pypi.python.org/pypi/glob2, in case you are open to introducing it as a dependency.

**Comment by msarahan** [comment]
Totally fine with new dependencies when they add nice functionality. I prefer a new dep to crappy error handling code.

**Comment by msarahan** [comment]
fixed by #2146
