### ISSUE TITLE
--output is not aware of --output-folder 

### ISSUE THREAD

**Issue by ElliotJH** [conda/conda-build#1731]
--output always returns a path including the conda-bld subdirectory, but --output-folder overrides this - it ought to be taken into account when returning the path.

I'm not sure, but I think maybe Config.bldpkgs_dir should use output_folder, but I'm not sure how this is supposed to work with croot.

**Comment by ElliotJH** [comment]
I might be able to write a patch given a little guidance.

**Comment by msarahan** [comment]
Sorry this is confusing. Almost everyone should be using croot, not output-folder.  Croot keeps the indexing stuff working, while output-folder is much more of just a"dunno the package in this folder.". The reason why it exists is for a build system that we are working on, based on concourse.  The way that concourse shuttles intermediaries around is that you name a folder, and then it handles copying the files in that folder between workers.  So output-folder is really only for making that work.  We can talk about whether there's a better way to have it work for both concourse and what you want it to do.

Mostly, please just tell me what behavior you would find intuitive. I will fix it for the next bugfix release, probably tomorrow. It'll be a quick fix for me, as long as we agree on what the behavior should be.

**Comment by ElliotJH** [comment]
Ah, it looks like I should be using croot and just forget about --output-folder altogether. Perhaps it's worth putting a line in the docs mentioning that croot is preferred? Either way, --croot solves my problem entirely.
