### ISSUE TITLE
Allow git configuration to ignore initializing submodules

### ISSUE THREAD

**Issue by nnashok** [conda/conda-build#1733]
A project may support building with submodules (for project devs) as well as without submodules (for external devs). When an external dev tries to build such a project with conda, conda attempts to initialize submodules which was not the intention. In some cases (as in mine), the external dev might not even have access to the submodules, resulting in the conda build to fail.

Adding a configuration option in the recipe (meta.yaml) to specify that submodules should not be initialized, will give such users a way to build these kinds of projects.

**Comment by msarahan** [comment]
This is a good idea, but unfortunately it's such a rare occurrence that I can't spend time on this right now.  I'd happily review a PR for this.  I'll put it in the backlog for the time being.
