### ISSUE TITLE
Is it possible to build a package that depends on python>=3.0

### ISSUE THREAD

**Issue by mj-harvey** [conda/conda-build#1734]
Hi,

I distribute some software via conda that is Python 3 only. Right now I have a separate package for every 3.x point release. Is it possible to create a single package that depends on any Python >= 3.0? 
Failing that, is there a conda command converting the python dependency of a package, without having to rebuild manually?

Thanks,

Matt

**Comment by msarahan** [comment]
This is an area that we need to improve in.  There are noarch packages (which have recently been redone, but this lacks documentation), but these imply total python version independence.  There's no middle ground, unfortunately.  This is a very good feature request, and I'll try to see what I can do on a short-ish timeline (2-3 weeks)

Fundamentally, the reason behind this is that conda-build wants to compile .pyc files for you.  Noarch turns that off.  We need a way to have noarch, while keeping the ability to constrain python.

**Comment by jakirkham** [comment]
Related to this question, I can easily imagine cases where something may support Python 2 and Python 3 (or perhaps just Python 3), but not some old versions of Python 3 (e.g. anything below 3.3 or 3.4 for instance). It would be good to have some way to constrain the allowed Python version in these cases lest users get the wrong impression of where the software will work.
