### ISSUE TITLE
Problem: --output-folder Makes noarch packages being build as linux-64 packages

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#1735]
I'm building a noarch package using:

```
build:
  noarch: True
```

When I build it with `conda build package_dir` I get the desired result in `miniconda3/conda-bld/noarch/package-..`.

Building the same package with `conda build package_dir --output-folder=output-folder` it creates: `miniconda3/conda-bld/**linux-64**/package-..`. So its basically building it in the "host architecture" I guess... Maybe its even just a mistake when copying..

**Comment by msarahan** [comment]
From https://github.com/conda/conda-build/issues/1731#issuecomment-277744542

Sorry this is confusing. Almost everyone should be using croot, not output-folder. Croot keeps the indexing stuff working, while output-folder is much more of just a "dump the package in this folder." The reason why it exists is for a build system that we are working on, based on concourse. The way that concourse shuttles intermediaries around is that you name a folder, and then it handles copying the files in that folder between workers. So output-folder is really only for making that work. We can talk about whether there's a better way to have it work for both concourse and what you want it to do.

Mostly, please just tell me what behavior you would find intuitive. I will fix it for the next bugfix release. It'll be a quick fix for me, as long as we agree on what the behavior should be.

I'm inclined to perhaps make output-folder an alias for croot, and call the Concourse option something entirely different and obscure.

**Comment by gabm** [comment]
Ok, thats indeed confusing - I'll use --croot - it seems it is what I needed...

I would have expected the same behavior using output-folder... so maybe you could treat croot and output folder as aliases and maybe even declare output-folder deprecated?
