### ISSUE TITLE
packages download but don't install via meta.yaml

### ISSUE THREAD

**Issue by bucricket** [conda/conda-build#1738]
Sorry if this has been solved already.  Cant seem to find the answer to this one.  I can install a packages like

conda install hdfeos2 
 and it will download and install the libraries from the package however if I try to install the package via the meta.yaml in conda-build it downloads to pkgs but never installs.  Is this a bug or am I doing something wrong.  please see the conda info -a

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.3
         python version : 2.7.12.final.0
       requests version : 2.7.0
       root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
       envs directories : /Applications/anaconda/envs
          package cache : /Applications/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/bucricket/osx-64
                          https://conda.anaconda.org/bucricket/noarch
            config file : /Users/mschull/.condarc
           offline mode : False

# conda environments:
#
pyDMS34                  /Applications/anaconda/envs/pyDMS34
pydisalexi               /Applications/anaconda/envs/pydisalexi
pygst                    /Applications/anaconda/envs/pygst
root3                    /Applications/anaconda/envs/root3
test                     /Applications/anaconda/envs/test
root                  *  /Applications/anaconda

sys.version: 2.7.12 |Anaconda custom (x86_64)| (defau...
sys.prefix: /Applications/anaconda
sys.executable: /Applications/anaconda/bin/python
conda location: /Applications/anaconda/lib/python2.7/site-packages/conda
conda-build: /Applications/anaconda/bin/conda-build
conda-convert: /Applications/anaconda/bin/conda-convert
conda-develop: /Applications/anaconda/bin/conda-develop
conda-env: /Applications/anaconda/bin/conda-env
conda-execute: /Applications/anaconda/bin/conda-execute
conda-index: /Applications/anaconda/bin/conda-index
conda-inspect: /Applications/anaconda/bin/conda-inspect
conda-metapackage: /Applications/anaconda/bin/conda-metapackage
conda-render: /Applications/anaconda/bin/conda-render
conda-server: /Applications/anaconda/bin/conda-server
conda-sign: /Applications/anaconda/bin/conda-sign
conda-skeleton: /Applications/anaconda/bin/conda-skeleton
conda-tmpenv: /Applications/anaconda/bin/conda-tmpenv
conda-verify: /Applications/anaconda/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /opt/local/bin:/opt/local/sbin:/Applications/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /Applications/anaconda/licenses
    /Users/mschull/.continuum
    /Users/mschull/Library/Application Support/Anaconda
License files (license*.txt):
Package/feature end dates:

**Comment by msarahan** [comment]
What does your recipe look like?  Where are you expecting things to be installed?  Why do you think they are not getting installed (i.e. what are the error messages you're seeing that make you reach that conclusion?)

**Comment by bucricket** [comment]
I'm rather new to building packages, so any advice you can bestow upon me will be welcome. See my meta.yaml below.  my program uses externally compiled c binaries and I just use subprocess.call to use them.  I use scons to compile the binaries and put them in the ~/anaconda/lib directory.  I am using the conda-build meta.yaml to install the necessary libraries.  My problem is that it doesn't appear to be moving the libraries from the pks directory to the ~/anaconda/lib directory where I am pointing scons library path to.  If I do conda install hdfeos2 for example the libGctp.a static library will be put in the ~/anaconda/lib directory.  Doing that seems to be defeating the purpose of the meta.yaml file. The error I get is in compiling using scons because it obviously cannot libraries that it needs.

Thanks for your help in advance!


package:
  name: projectmaspreprocess
  version: 0.1.0

source:
  git_url: https://github.com/bucricket/projectMASpreprocess.git

  
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  script: 

  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - landsat-util = landsat-util:main
    #
    # Would create an entry point called landsat-util that calls landsat-util.main()

    - preparepydisalexi=preparepydisalexi.processLandsatLAI:main
    
requirements:
  build:
    - python 2.7*
    - setuptools
    - scons
    - gcc
    - jpeg
    - geotiff
    - zlib
    - hdfeos2 2.19*
    - szip
    - libtiff
    - hdf5
    - gdal 2.1*
    
  run:
    - python 2.7*
    - landsat-util ==0.13.1
    - keyring >=9.3.1
    - keyrings.alt >=1.2
    - gdal 2.1*
    - pymodis
    - pycurl
    - pandas ==0.18.1
    - simplejson
    - geocoder
    - wget

test:
  # Python imports
  imports:
    - preparepydisalexi

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  requires:

    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bucricket/projectMASpreprocess.git
  license: CCO
  summary: 'A tool to disaggregate ALEXI ET'
  license_family: OTHER

**Comment by msarahan** [comment]
The key to conda-build is the notion of the build "prefix" - the environment where your requirements are installed.  This is also the place that you need to be copying your files to - NOT into your root conda installation.  Conda detects "new" files - files that appear after environment creation, and these are what get packaged up.  There are environment variables to help you, documented at https://conda.io/docs/building/environment-vars.html

There are lots of recipes floating around.  Conda-forge is a great reference, if you haven't already checked there.  Here's one recipe that may help you understand: https://github.com/conda-forge/zlib-feedstock/blob/master/recipe/build.sh

**Comment by bucricket** [comment]
Mike,

Thanks!  That helped a lot.  Took me a while to figure out the $PREFIX and SCons but now it works great!

Mitch

**Comment by msarahan** [comment]
Great.  Glad you got it working.  Closing this issue.
