### ISSUE TITLE
Problem: Whitespaces in paths don't work

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#1742]
While working with `--croot` I stumbled across a problem with whitespaces in paths on both, Windows and Linux. Crashes are happening all over the place, always where external tools are called, because spaces are interpreted as argument separators..

Currently conda and conda-build do not allow whitespaces in at least:

- the root prefix
- the croot prefix
- the recipe directory

While Obviously whitespaces are quite evil and not such a big problem on Linux, on Windows they are *real* and used even in system directories.

I googled quite a while to look for strategies in python on how to escape paths properly and came up with these alternatives:
- putting the path in double quotes: `"\"" + path + "\""`, found here: http://stackoverflow.com/questions/14852140/whitespaces-in-the-path-of-windows-filepath
- parsing the path as raw string: `r"C:\path\with spaces\"`, found in the same place
- using `shlex.quote(..)`, found here: http://stackoverflow.com/questions/35817/how-to-escape-os-system-calls-in-python, https://docs.python.org/dev/library/shlex.html#shlex.quote
  - this converted my test string into 'single quotes'

@msarahan Any thoughts?

**Comment by msarahan** [comment]
Thanks for raising. On conda with the activate scripts, I made the tests all run in folders with spaces. I need to do the same for conda build.  I need to tag 2.1.4 without this, but will fix it for another release soon.

**Comment by msarahan** [comment]
I've tested this just now.  Unfortunately, I don't think it's going to be an easy fix on Linux/Mac:

```
updating index in: /private/tmp/cb/test_croot_with_spaces0/space path/osx-64
updating index in: /private/tmp/cb/test_croot_with_spaces0/space path/noarch

The following NEW packages will be INSTALLED:

    openssl:    1.0.2k-0
    pip:        9.0.1-py35_1
    python:     3.5.2-0
    readline:   6.2-2
    setuptools: 27.2.0-py35_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py35_0
    xz:         5.2.2-1
    zlib:       1.2.8-3

----------------------------------------------- Captured stderr call -----------------------------------------------
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'defaults::openssl-1.0.2k-0'.
LinkError: post-link failed for: defaults::openssl-1.0.2k-0

Attempting to roll back.

WARNING conda_build.build:create_env(699): Build prefix failed with prefix length 255
WARNING conda_build.build:create_env(700): Error was:
WARNING conda_build.build:create_env(701): post-link failed for: defaults::openssl-1.0.2k-0

WARNING conda_build.build:create_env(702): One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING conda_build.build:create_env(704): Falling back to legacy prefix length of 80 characters.
WARNING conda_build.build:create_env(705): Your package will not install into prefixes > 80 characters.
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'defaults::openssl-1.0.2k-0'.
LinkError: post-link failed for: defaults::openssl-1.0.2k-0
```

That prefix replacement is custom code that @ilanschnell wrote, so that things can be bootstrapped (can't depend on conda being available).

#1750 should at least fix the issue on Windows.
