### ISSUE TITLE
path.json showing path to old version

### ISSUE THREAD

**Issue by willis7** [conda/conda-build#1743]
Our build process packs our library in a Linux Docker container then converts to each of the arch's using convert. We then publish this behind a NGINX server.

```
conda convert --output-dir "$releases" -p all "$bzname"
```

When consuming this package we get the following error:
```
$ conda install transport -c http://myserver/condapkg

...

transport-0.2. 100% |###############################| Time: 0:00:00  15.23 MB/s
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'http://myserver/condapkg::transport-0.2.2-py35_0'.
CondaError: Cannot link a source that does not exist. C:\Tools\anaconda\pkgs\transport-0.2.2-py35_0\lib\python3.5\site-packages\transport-0.1-py3.5.egg-info\PKG-INFO

Attempting to roll back.

CondaError: Cannot link a source that does not exist. C:\Tools\anaconda\pkgs\transport-0.2.2-py35_0\lib\python3.5\site-packages\transport-0.1-py3.5.egg-info\PKG-INFO
```
If I inspect the pkgs `paths.json` I can see the path points to 0.1. On machines where 0.1 exists this carries on silently (which arguably isn't correct), but fails where it doesn't exist.

This appears to be similar to #1678 and #1701, but I can determine the fix to replicate the same.

Can anyone offer a steer on the solution?

**Comment by msarahan** [comment]
How is the 0.1 version installed in the first place?  Conda-build is pretty dumb about versions - if a file is missing when the build environment is created, and then present once the build process finishes, conda-build will happily bundle it.  I think you need to figure out how this file is getting into place.  I'd be happy to look at your recipe if you want.

**Comment by willis7** [comment]
After some digging I realised I had specified a version in the `setup.py` script that was missed. This was causing the 0.1 version. Thanks for the offer of help.
