### ISSUE TITLE
Lock files are written in the root environment

### ISSUE THREAD

**Issue by cpcloud** [conda/conda-build#1745]
My users do not have write permissions in the root environment and they still need to use conda build. What are my options beyond --no-locking?

**Comment by msarahan** [comment]
Use an older version of conda build.  Sorry.  Multi-user support is on the near-term road map, but not here yet.

**Comment by cpcloud** [comment]
@msarahan Is there a document detailing the design of the multi-user work? Might be useful to field some use cases.

**Comment by msarahan** [comment]
Not currently, but feel free to add on to the issue at #1601

**Comment by cpcloud** [comment]
Is there a way to turn on `--no-locking` by default?

**Comment by msarahan** [comment]
No.  Not much of conda-build is available in .condarc.  You can hack around it with an alias:

    alias conda-build="conda-build --no-locking"

I also don't think ``--no-locking`` will totally solve your problems.  There are some places where the configuration may not be passed through, and those may still try to use locks when copying files.

PRs welcome.  My timeline for doing this myself is 1-2 weeks out.
