### ISSUE TITLE
Run tests in a folder with a long path

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#1762]
This would reveal any problems of installing the package into a folder with a long path.

**Comment by msarahan** [comment]
Can you point to problems you've encountered?  I am aware of conda installing things into paths longer than 260 characters on Windows causing problems.  I'm not aware of any issues on mac or linux, though.

**Comment by isuruf** [comment]
It's not a problem of conda-build. It was a problem in the package itself. (It was storing where the package was installed in a buffer too small.)
When building the package with conda-build if the test environment had a long prefix, I would have noticed this problem

Ref: https://github.com/conda-forge/gap-feedstock/pull/4

**Comment by msarahan** [comment]
Ah, I think that is actually a problem with conda-build, though.  I think this is the same as https://github.com/conda/conda-build/issues/1674 - conda-build is not accounting for the null terminator or something like that.  But I though our prefix is 255 chars - your 256 char buf should have been enough?

**Comment by isuruf** [comment]
It wasn't storing the prefix, it was storing `<prefix>/lib/gap` which is longer than 256 because prefix is 256 chars long.

**Comment by msarahan** [comment]
all right.  Well, it's easy to turn on since we already have it for the build env, so I'll go ahead and implement this sometime soon.

**Comment by isuruf** [comment]
Thanks.

**Comment by msarahan** [comment]
fixed by #1799 - closing
