### ISSUE TITLE
Symbolic link folders don't work anymore

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#1769]
A symbolic link to a folder worked fine in conda-build 2.1.4, but it's not in conda-build 2.1.5 on osx (linux works fine).

conda-build 2.1.5 log
https://travis-ci.org/conda-forge/gap-feedstock/builds/204615074

conda-build 2.1.4 log
https://travis-ci.org/conda-forge/gap-feedstock/builds/200925407

**Comment by msarahan** [comment]
Thanks for reporting.  I'm writing a test and will fix asap.

**Comment by msarahan** [comment]
I've added further testing to make sure that symlinks in the package are still symlinks.  Currently those tests are failing.  Your links are probably copies right now.

**Comment by isuruf** [comment]
Thanks for fixing this
