### ISSUE TITLE
myenvironment/site-packages vs myenvironment/python2.7/site-packages (Windows problem???)

### ISSUE THREAD

**Issue by BjornFJohansson** [conda/conda-build#1778]
Hi, I have a pure python 2.7 package "[wikidpad](https://github.com/BjornFJohansson/WikidPad)" built on Linux-64 and then converted to the other platforms using conda convert. 
My Anaconda installation is an Anaconda3 so it has Python3 in the root. I therefore use
`conda build . --python=2.7` to build the package. This runs fine and I can upload a conda package to anaconda cloud which I can later download and install into a fresh python2.7 env and all works as expected on linux.
I have almost the same setup on my wife's windows machine(Anaconda3), but here the installation fails.
`conda list` listed wikidpad as installed, but I could not import the package ( `import WikidPad` fails).

Turned out that wikidpad was installed to myenvironment/python2.7/site-packages while everything else was installed to myenvironment/site-packages. If I copied the directories in myenvironment/python2.7/site-packages to myenvironment/site-packages, the package is found.

The latter directory does not exist on my Linux machine. Is this a bug or am I doing something wrong?

thanks!

**Comment by BjornFJohansson** [comment]
Tried the converted mac package on a mac with Yosemite and it finds the package. Seems that whatever problem I have is windows specific.

**Comment by msarahan** [comment]
Thanks.  Seems like a bug.  What version of conda-build is this?

**Comment by BjornFJohansson** [comment]
```
conda                     4.3.13                   py35_0  
conda-build               2.1.5                    py35_0  
conda-env                 2.6.0                         0  
conda-verify              2.0.0                    py35_0 
```

**Comment by BjornFJohansson** [comment]
the package has an internal "lib" package. Could this perhaps confuse conda-build or convert?

**Comment by msarahan** [comment]
ah, yes, that might confuse things.  Can you rename it?

**Comment by BjornFJohansson** [comment]
I did, but it did not help.

There is a peculiar difference in how the sys.path is set between the platforms.
Linux prefers    lib/python2.7/site-packages 
Windows prefers lib/site-packages

Both of these environments were created with the last version of conda on Anaconda3
so the root environment is python3.

Is this correct?

The package I made on linux installs to 
`myenvironment/lib/python2.7/site-packages `
on linux which works ok since sys.path has this directory and everything else is there too.
there is no `myenvironment/site-packages`

On windows I get two site-packages and only one of them is in sys.path.

my converted package ends up in 

`myenvironment/python2.7/site-packages`

while all other packages is in 

`myenvironment/site-packages`

I think the former is created by my package during installation, but I do not know why.
I have looked at the meta.yaml files, but I cannot see what is possibly wrong.

Linux:

```
(wptest) bjorn@bjorn-ThinkPad-T450s:~$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys
>>> for p in sys.path: print(p)
/home/bjorn/anaconda3/envs/wptest/lib/python27.zip
/home/bjorn/anaconda3/envs/wptest/lib/python2.7
/home/bjorn/anaconda3/envs/wptest/lib/python2.7/plat-linux2
/home/bjorn/anaconda3/envs/wptest/lib/python2.7/lib-tk
/home/bjorn/anaconda3/envs/wptest/lib/python2.7/lib-old
/home/bjorn/anaconda3/envs/wptest/lib/python2.7/lib-dynload
/home/bjorn/.local/lib/python2.7/site-packages
/home/bjorn/anaconda3/envs/wptest/lib/python2.7/site-packages
/home/bjorn/anaconda3/envs/wptest/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg
/home/bjorn/anaconda3/envs/wptest/lib/python2.7/site-packages/wx-3.0-gtk2
>>> 
```




Windows:

```
(wp) C:\Users\Utilizador>python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys
>>> for p in sys.path:
...     print(p)
C:\Users\Utilizador\Anaconda3\envs\wp\python27.zip
C:\Users\Utilizador\Anaconda3\envs\wp\DLLs
C:\Users\Utilizador\Anaconda3\envs\wp\lib
C:\Users\Utilizador\Anaconda3\envs\wp\lib\plat-win
C:\Users\Utilizador\Anaconda3\envs\wp\lib\lib-tk
C:\Users\Utilizador\Anaconda3\envs\wp
C:\Users\Utilizador\Anaconda3\envs\wp\lib\site-packages
C:\Users\Utilizador\Anaconda3\envs\wp\lib\site-packages\setuptools-27.2.0-py2.7.egg
C:\Users\Utilizador\Anaconda3\envs\wp\lib\site-packages\wx-3.0-msw
>>>
```

**Comment by BjornFJohansson** [comment]
I managed to solve this. I had perhaps a subtle error in my meta.yaml:
I had:
```
requirements:
  build:
    - python
    - wxpython >=3.0.0
    - whoosh
    - appdirs
  run:
    - wxpython >=3.0.0
    - whoosh
    - appdirs
```
but when I added python to run requirements:
```
requirements:
  build:
    - python
    - wxpython >=3.0.0
    - whoosh
    - appdirs
  run:
    - python
    - wxpython >=3.0.0
    - whoosh
    - appdirs
```
all of the errors went away. I dont know if this is the expected behaviour?
The built files also changed names from names like:
`wikidpad-2.3b29-0.tar.bz2`
to names like
`wikidpad-2.3b32-py27_0.tar.bz2`

**Comment by msarahan** [comment]
yeah, that's an important distinction.  Conda-build does not know to do any of the path renaming if it doesn't consider the package to be a python package.  The runtime dependency on python is what tells conda-build that it is a python package.  Glad you got this figured out.  Closing this issue.
