### ISSUE TITLE
`$PYTHON` is not the same as `python` in `run_test.py`

### ISSUE THREAD

**Issue by basnijholt** [conda/conda-build#1785]
I encountered this issue in building a conda package in the conda-forge pipeline.

I describe the issue is more detail here: https://github.com/conda-forge/conda-forge.github.io/issues/346

Unfortunately, I don't have time to create a minimal example, but I think that the issue is quite clear.

**Comment by jakirkham** [comment]
The title says it all. 😄

**Comment by msarahan** [comment]
@ChrisBarker-NOAA explains the reasoning well in https://github.com/conda-forge/conda-forge.github.io/issues/346#issuecomment-283717215

I don't think the full set of variables should be available.  As few as reasonably achievable.  Using the python on PATH should work - as long as that python is the test environment one.

**Comment by msarahan** [comment]
I think a "fix" for this issue is actually to unset $PYTHON completely in the test environment.

**Comment by ChrisBarker-NOAA** [comment]
On Thu, Mar 2, 2017 at 9:22 AM, Mike Sarahan <notifications@github.com>
wrote:
>
> I don't think the full set of variables should be available. As few as
> reasonably achievable. Using the python on PATH should work - as long as
> that python is the test environment one.
>
which it should be if the test environment is set up right -- if it's not:
 that's bug in conda-build, yes?

-CHB


-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by msarahan** [comment]
@ChrisBarker-NOAA yes, absolutely.

**Comment by msarahan** [comment]
Fixed by #1806.  Closing.
