### ISSUE TITLE
Meta.yaml schema

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#1798]
Is there an official `meta.yaml` schema?
If not, could there be one?
I am specifically interested in a list (indexed by the header) of the supported subheaders.

**Comment by msarahan** [comment]
I don't think there is one. I'm in favor of creating one, but I'm afraid I'm overbooked right now. I can put it in the backlog, or is be happy to take a PR for this.

**Comment by CJ-Wright** [comment]
I am kinda making one for conda-forge (see https://github.com/conda-forge/conda-smithy/issues/471) but I don't know if it will be complete.

**Comment by msarahan** [comment]
Cool, just put up what you have and we as a community can hopefully complete it and keep it up to date.

**Comment by CJ-Wright** [comment]
This is what I have [so far](https://github.com/conda-forge/conda-smithy/pull/473/files#diff-75c89ae9a2c5841bf730ed3474cc2987R21)
But I understand if that won't really work for this application.
Do you want a standard json schema?

**Comment by msarahan** [comment]
Please consider putting this in the conda-verify project: https://github.com/conda/conda-verify

The thought there was to create a tool separate from conda-build that could be lighter than conda-build in terms of dependencies.  We hoped that we could use it internally (conda-build depends on it), and also that it would be of use to projects like conda-forge's linter.  It hasn't really taken off, but maybe your effort will help give it some momentum.

I'm not actually all that familiar with what you'd use a schema for.  Is it for anything more than validation of recipes?

**Comment by CJ-Wright** [comment]
I am just planning on using it for validation.

**Comment by groutr** [comment]
@CJ-Wright have you seen this https://conda.io/docs/building/meta-yaml.html ?

**Comment by CJ-Wright** [comment]
Yes I have, however it is rather difficult to use the documentation in a program to validate a meta-yaml file (and does it have all the potential subheaders?). The hope was to check if the meta-yaml subheaders were valid automatically.

**Comment by groutr** [comment]
Maybe this is closer to what you're looking for: https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L378 and expected types are here https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L286

**Comment by CJ-Wright** [comment]
That is exactly what I was looking for. Thank you very much!
