### ISSUE TITLE
Switching to pycryptodome

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1809]
Currently `conda-build` [depends]( https://github.com/conda/conda-build/blob/4b393631fed62b560d61d0d44afe48613a5b040d/conda.recipe/meta.yaml#L36 ) on `pycrypto`. However there hasn't been an update to `pycrypto` in a few years. IMHO we should be switching to something that is actually still maintained like [`pycryptodome`]( https://github.com/Legrandin/pycryptodome ).

**Comment by msarahan** [comment]
Cool.  I'm not sure how relevant this is - I think we're going to be dropping the signature stuff pretty soon - conda no longer supports it.  That's what pycrypto was used for.  Long-term, I'm not exactly sure what the plan is for package verification, but let's keep pycryptodome in mind for that.

**Comment by jakirkham** [comment]
SGTM.

Part of the reason it came up was in relation to getting a Python 3.6 copy built, which we seem unable to do on Windows. Not sure if it is worth another round of investigation and patching if the plan is to drop it. How did you guys handle this internally?

**Comment by jakirkham** [comment]
This is no longer a dependency of `conda-build`.
