### ISSUE TITLE
2.1.6 missing from CHANGELOG file

### ISSUE THREAD

**Issue by nicoddemus** [conda/conda-build#1818]
Hi, 

Just noticed that `2.1.6` entries are not in the CHANGELOG file, but appear in [releases](https://github.com/conda/conda-build/releases); not sure if this is intended or an oversight.

**Comment by msarahan** [comment]
I think it's because 2.1.6 came from the 2.1.x branch, not master, and I haven't merged 2.1.x into master yet.

**Comment by nicoddemus** [comment]
Oh OK, makes sense. Feel free to close this then, or keep open if you would like it as a reminder.

**Comment by msarahan** [comment]
Should be fixed now.  I'll try to keep them in sync a little more as things converge.
