### ISSUE TITLE
Problem with the long prefix in the test environment since conda-build 2.1.6

### ISSUE THREAD

**Issue by markbarks** [conda/conda-build#1824]
We have a problem with the long prefix in the test environment since conda-build 2.1.6

We use some test resources to run integration tests during the build. The api for the db we are contacting doesn't support file paths longer than 255 chars however:

`E           RuntimeError: ERROR: Query names longer than 255 characters are not currently supported in queries: /home/markns/miniconda2/conda-bld/framework_1489136304223/_t_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/framework/datasources/../data/query.q::find`

Is there a way we can reduce this prefix length? Thanks.

**Comment by msarahan** [comment]
sorry about this.  That caused a lot more trouble than I imagined.  I'll make it optional, defaulting to False.

**Comment by msarahan** [comment]
fixed in #1838 - closing.
