### ISSUE TITLE
--output-folder ignored if building a wheel

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#1826]
With `conda 4.3.14` and `conda-build 2.1.6` (both from defaults), the `--output-folder` option is ignored if the output type is a wheel:

```
outputs:
    - type: wheel
```

The built wheel is still placed in the default location, `/Users/.../anaconda/conda-bld/osx-64`.

This [sample `meta.yaml`](https://gist.github.com/mwcraig/62ec496d07ec02797fe5f4b0321b18fd) should be reproduce the issue...run it with, e.g. `--output-folder foo`.

If both `wheel` and `conda` output types are specified in the meta.yaml, the conda package is put in the directory specified on the command line.

**Comment by msarahan** [comment]
fixed by https://github.com/conda/conda-build/pull/1838/commits/a03109220d968687ece5a6b5dc6cf4b5c2d1de8f - closing
