### ISSUE TITLE
Feature: Add logging option for INFO and WARNING

### ISSUE THREAD

**Issue by jgmorrison** [conda/conda-build#1827]
We have a customer request that an logging handlers be added for redirecting INFO and WARNING produced from the logging package to another place. Non critical issues could be sent to a file or suppressed. Possibly add these options for CRITICAL and ERROR. They would like separate handling for a cleaner run log as they sometimes build/deploy to other users systems which create concerns with the output.

**Comment by msarahan** [comment]
Sorry, I'm confused about this.  Have they tried the --quiet CLI flag?  I'm very confused about the build/deploy to other user systems. Those are two very different things. You're saying that they are building on user machines and want less output on those machines?  Why are they building on user machines?  On the other side, deployment is conda, and once a package is built, conda build is no longer involved.

What is the priority on this? Do they have some kind of support contract with us? Is this work covered by their support contract?  This is enough of a "nice to have" feature and there are enough important projects right now that this request is going to be long term unless there is some support contract or payment to prioritize the work.

**Comment by jgmorrison** [comment]
I think their general request is an option to suppress certain logging(INFO, WARNING) in conda-build and/or change where it is output, i.e. a file. This suggestion may extend further into conda in general or installers such as Anaconda/Miniconda. Conda-build was what the first brought it up in regards to. 

They have an Anaconda Pro support contract with us. I am trying to get more information but may not hear back until Monday. In general our products don't seem to have logging options which IT/System Admins ask about a lot as they are not monitoring these things in realtime and like to output somewhere for later as well as cleaner output based of what they care about seeing(ERROR, CRITICAL).

**Comment by jgmorrison** [comment]
The basic request is  for INFO to go to stdout and >=WARN to go to stderr. It appears some lines of "INFO conda_build.config:__exit__(405): --dirty flag…." Captured in stderr with an INFO severity.

We can disregard a feature request for logging options as I mentioned above. I will probably put that into a feature request for anaconda/conda at a later time.

**Comment by msarahan** [comment]
Great, that's much easier.  I'll get that in quickly.
