### ISSUE TITLE
Problem: Test stage failed in 2.1.6 under windows

### ISSUE THREAD

**Issue by argltuc** [conda/conda-build#1835]
```
The following NEW packages will be INSTALLED:

    cmake:              3.6.3-vc14_0                                                                    [vc14]
    eigen3:             3.2.9-2      local
    zlib:               1.2.8-vc14_3                                                                    [vc14]


C:\Miniconda3\conda-bld\eigen3_1489429928381\test_tmp>call "C:\Miniconda3\Scripts\activate.bat" "C:\Miniconda3\conda-bld
\eigen3_1489429928381\_t_env"  1>nul 2>&1

(C:\Miniconda3\conda-bld\eigen3_1489429928381\_t_env) C:\Miniconda3\conda-bld\eigen3_1489429928381\test_tmp>if errorleve
l 1 exit 1

(C:\Miniconda3\conda-bld\eigen3_1489429928381\_t_env) C:\Miniconda3\conda-bld\eigen3_1489429928381\test_tmp>call "C:\Min
iconda3\conda-bld\eigen3_1489429928381\test_tmp\run_test.bat"

(C:\Miniconda3\conda-bld\eigen3_1489429928381\_t_env) C:\Miniconda3\conda-bld\eigen3_1489429928381\test_tmp>cmake C:\Use
rs\WINDOW~1\AppData\Local\Temp\tmpql9wwf72\info\recipe\cmake_modules\ -G "Visual Studio 14 2015 Win64"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Miniconda3/conda-bld/eigen3_1489429928381/test_tmp/CMakeFiles/CMakeOutput.log".
See also "C:/Miniconda3/conda-bld/eigen3_1489429928381/test_tmp/CMakeFiles/CMakeError.log".

(C:\Miniconda3\conda-bld\eigen3_1489429928381\_t_env) C:\Miniconda3\conda-bld\eigen3_1489429928381\test_tmp>if errorleve
l 1 exit 1
TESTS FAILED: eigen3-3.2.9-2
```
CMAKE_CXX_COMPILER is already successfully used at compile stage. Under test stage it fails. Under conda-build 2.1.5 everything works well.

**Comment by msarahan** [comment]
Sorry, this has never been supported, and the fact that it worked in 2.1.5 was a bug, not a feature.  The test environment does not set up compilers.  If you need compilers set up, you need to run the appropriate activate scripts yourself.

Note that in conda-build 3.0 (coming soon), we'll be deprecating the compiler activation logic in conda-build itself, and moving towards activation scripts in packages.  With these packages, you'll be able to just list this package as a run or test time dependency.  I'll leave this issue open as something that will be more easily fixed by that transition.

**Comment by gabm** [comment]
wow, that comes a bit as a surprise... Is there some discussion going on on that topic? I subscribed the mailing list but there has been nothing in that direction?!

Is there some more information on the new technique? Documentation? anything?

**Comment by msarahan** [comment]
https://github.com/conda/conda-docs/pull/414
https://github.com/conda/conda-build/pull/1585
https://www.youtube.com/watch?v=WzAgRUa4iuA

**Comment by gabm** [comment]
thanks.. interesting...

**Comment by gabm** [comment]
after reading your documents: ufff... thats pretty cool stuff... :flushed: :checkered_flag: :tada: 

So do I understand correctly: 
- you list a jinja variable {{ cxx_compiler }} as a build dependency, which will be replaced by *several* compiler packages which are listed in a special conda_build_config.yaml in the mentioned locations
- this compiler package pins an implicit run dependency of the corresponding runtime package to the built package
- when I install the built package, the proper runtime library version gets installed as well

Cool so far, that replaces track_features right?

Now we want to implement this stuff for our own services. The compiler package under windows will be somewhat special, cause it only calls the `vcvarsxx.bat`, but in general the compiler *will be made available* through activation script or proper package. I think thats fine. 

Questions that arise:
- Should the runtime library contain the actual library? Guess so, right? Or is it just a placeholder to group project with of the same compiler?
- How do we specify, *which* runtime library we want to install on our systems? Currently we do that by *tracking* the corresponding feature. So How would I distinguish vc 9 and vc 14 on client side?

**Comment by msarahan** [comment]
Starting a new issue for this, as it has diverged greatly from the initial topic, and your questions are important and should be more visible.  New issue at #1841

**Comment by msarahan** [comment]
Closing as not supported, based on https://github.com/conda/conda-build/issues/1835#issuecomment-286205632
