### ISSUE TITLE
Problem: When multiple recipes are built at once, no new environments are created

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#1852]
When I build multiple recipes on Linux, somehow only the first build environment gets created. 

## Usecase
I run `conda build recipes/* --skip-existing`. There are several packages in this folder, lets call them pkg1.. pkg3. While pkg1 is already built, pkg2 and pkg3 are supposed to be built.

## Observation
1. conda-build successfully skips pkg1
2. conda-build attempts to build pkg2
  - it creates a build folder in conda-bld, its called **pkg1_timestamp** (note the wrong name!!!)
  - it installs the dependencies successfully
  - it builds successfully
  - it finishes and removes the build folder
3. conda-build attempts to build pkg3
  - it creates **the same build folder again**, pkg1_timestamp - even the timestamp is the same
  - it **does not** install the dependencies
  - build fails, because dependencies are not found

Each package is built successfully if I just build them seperately... So it seems the environment creation/preparation doesn't work properly...

**Comment by msarahan** [comment]
Thanks for the report.  I think this is fixed by https://github.com/conda/conda-build/pull/1842 which has not yet made it into a release.

**Comment by gabm** [comment]
looks like.. thanks..
