### ISSUE TITLE
Failure to find cx_Oracle in .condarc-specified channel

### ISSUE THREAD

**Issue by b-adams** [conda/conda-build#1854]
I am trying to build a package which depends on  [cx_Oracle](https://oracle.github.io/python-cx_Oracle/) to upload to [my Anaconda channel](https://anaconda.org/adambr/repo). Following along with ["Packaging Python Basics with Continuum Analytics Conda."](http://kylepurdon.com/blog/packaging-python-basics-with-continuum-analytics-conda.html) I was successful in building and uploading [a small example without cx_Oracle](https://anaconda.org/adambr/mvce). The working code is at [this commit](https://github.com/b-adams/mvce/commit/690f5320d746b12fddd239b85d82c0add5427766).

Initially, I ran into a problem when adding cx_Oracle as a dependency. I usually install it via pip, but I understand it needs to be available as a conda package for use as a dependency of another conda package. So, mirroring the "Converting an Existing Package/Upload Invoke to Your Channel" steps, I  built [and uploaded](https://anaconda.org/adambr/cx_oracle) using `conda skeleton pypi cx_Oracle` and `conda build cx_Oracle`.  It appears to have been successful, because after adding my channel to my .condarc (`conda config --add channels adambr`), I was able to create a new environment with cx_Oracle (`conda create -n test_my_upload python=3.6 cx_Oracle`) and it pulled from my channel and let me create a database connection as desired.

However, when I added cx_Oracle as a dependency in my test project, I ended up with the following error ([full log here](https://github.com/b-adams/mvce/blob/master/mvce/build.log)):

> Can't build C:\Users\adambr\Projects\Python\mvce due to environment creation error:
> Package missing in current win-64 channels:
>   - cx_Oracle

It's unclear to me why the package would be reported missing, or how to fix it. I've made sure that the `adambr` channel is in my .condarc file (per [this 2014 post](http://stackoverflow.com/questions/25610843/conda-build-requirement-add-package-from-specific-channel#25632265)), I invoked conda-build using `conda build -c adambr .` to further ensure the channel was specified, and it's picked up just fine for my system by `conda install`.

**Comment by msarahan** [comment]
yes, that does seem like it should work.  What version of conda and conda-build are you using?

**Comment by b-adams** [comment]
> C:\Users\adambr>conda -V
> conda 4.3.14
> 
> C:\Users\adambr>conda-build -V
> conda-build 2.1.7

**Comment by b-adams** [comment]
Issue resolved, not a bug: My meta.yaml file referenced `cx_Oracle` rather than `cx_oracle`.

**Comment by msarahan** [comment]
Great, glad you got it figured out. Thanks for following up here.
