### ISSUE TITLE
Incomplete list of essential Windows environment variables

### ISSUE THREAD

**Issue by wulmer** [conda/conda-build#1857]
Hi, after one of my packages failed to build with conda-build 2.1.7 due to a missing environment variable (`USERNAME`, used by [`getpass.getuser`](https://github.com/python/cpython/blob/master/Lib/getpass.py#L162)), I had a look into `conda_build/environ.py` and noticed that `windows_vars(prefix)` is missing some important environment variables.

I will prepare a pull request which adds the [default Windows environment variables](https://en.wikipedia.org/wiki/Environment_variable#Default_values).

**Comment by msarahan** [comment]
Excellent, thanks @wulmer.  Will look forward to merging that PR.
