### ISSUE TITLE
Fix RPATH for Mach-O stub files

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#186]
Conda currently skips install_name_tool calls when they won't update stub files, but these files need to be updated somehow, as they do have the build prefix baked into their RPATH, and it ends up affecting other things. An example is `lib/libgcc_ext.10.4.dylib` from my gcc 4.8.2-2 package on my binstar

```
$otool -L /Users/aaronmeurer/anaconda/lib/libgcc_ext.10.4.dylib
/Users/aaronmeurer/anaconda/lib/libgcc_ext.10.4.dylib:
    /Users/aaronmeurer/anaconda/envs/_build____________________________________________________________________________________________________/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```

This causes other files built with this gcc to get that build____ prefix (note that the build prefix for this conda build did not contain the underscores, so it has to be coming from the gcc stub files)

```
$otool -L /Users/aaronmeurer/anaconda/envs/_build/lib/python3.3/site-packages/george/_george.so
/Users/aaronmeurer/anaconda/envs/_build/lib/python3.3/site-packages/george/_george.so:
    @loader_path/../../../libstdc++.6.dylib (compatibility version 7.0.0, current version 7.18.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)
    /Users/aaronmeurer/anaconda/envs/_build____________________________________________________________________________________________________/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by asmeurer** [comment]
It should no longer be necessary to comment out code, because we use `otool -h` to check the file type. It still doesn't fix the stub files, though.

**Comment by bkreider** [comment]
fixed as in comment: https://github.com/conda-forge/pgplot-feedstock/pull/1#issuecomment-289232739
