### ISSUE TITLE
SHA256 mismatch x != x

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#1887]
Getting a weird failure, 
```
SHA256 mismatch: 
'c59e92ab9f82e156723dd3efb9433948dcb84facc21d6efb50f4d6c2d7aa6c5c' != 
'c59e92ab9f82e156723dd3efb9433948dcb84facc21d6efb50f4d6c2d7aa6c5c'
```

https://ci.appveyor.com/project/conda-forge/doxygen-feedstock/build/1.0.8/job/d5tehpaovu0pkbj9

**Comment by tadeu** [comment]
The second string seems to contain an extra piece from the `meta.yaml` file: `'\n- doxygen-1.8.13-NULL-dereference.patch'`:

```
SHA256 mismatch: 'c59e92ab9f82e156723dd3efb9433948dcb84facc21d6efb50f4d6c2d7aa6c5c' != 'c59e92ab9f82e156723dd3efb9433948dcb84facc21d6efb50f4d6c2d7aa6c5c
- doxygen-1.8.13-NULL-dereference.patch'
```

**Comment by tadeu** [comment]
I guess this can be closed? It seems it was a problem in the `meta.yaml`?

https://github.com/conda-forge/doxygen-feedstock/pull/4/files/29d885d2303bf89ad0c983157cc7f91523bd9f6a#r108633828

**Comment by isuruf** [comment]
Thanks

**Comment by isuruf** [comment]
@tadeu, thanks for looking into this. I forgot to update this issue. Sorry about that
