### ISSUE TITLE
Refreshing tarball indices

### ISSUE THREAD

**Issue by njalerikson** [conda/conda-build#1889]
We have a pretty large collection of in house recipes all build via `conda build`, a collection that will only continue to grow. 

As part of continuous cleanup and maintenance, how do I refresh the `.index.json`, `repodata.json`, and `repodata.json.bz2` files in `$CONDA_ROOT/conda-bld/{linux-64,noarch,...}` to reflect tarballs that have been removed or new tarballs that have been manually added?

Otherwise if we should not be manually removing/adding tarballs, what should I be doing instead?

References to applicable documentation would be most valuable as I seem unable to find any.

**Comment by mingwandroid** [comment]
`conda index .`, but I didn't manage to find the docs.

**Comment by groutr** [comment]
While maybe not explicitly documentation for `conda index`, @njalerikson what you are doing is essentially maintaining your own custom local channel.
https://conda.io/docs/custom-channels.html
and https://conda.io/docs/commands/build/conda-index.html has the help for the command.

**Comment by njalerikson** [comment]
Perfect, knowing me I probably glazed over the custom channels page a few times, oops. Thanks.
