### ISSUE TITLE
Conda skeleton pypi doesn't respect pypi URL's protocol

### ISSUE THREAD

**Issue by derenrich** [conda/conda-build#1891]
If you look at https://github.com/conda/conda-build/blob/320dcbe9b010f961c893b6b62cf36a3d857ba8c6/conda_build/skeletons/pypi.py#L64 you see that it decides to always use SSL when talking to pypi. It is possible to run a pypi server without SSL and it is possible to do so securely (my scenario involves doing so in a docker container for testing). So it'll try to negotiate a SSL handshake with the server and the whole thing fails.

**Comment by msarahan** [comment]
Thanks for pointing this out.  I'll gladly accept a PR for fixing this, but unfortunately it's enough of a corner case that I can't spend time on it right now.  If you decide to work on it, let me know if you have any questions about the code, and I'll be happy to help.
