### ISSUE TITLE
openssl build fails with conda-build 2.1.8 due to $PERL env being set

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#1898]
Our openssl recipe that builds on Linux with conda-build 2.1.4 fails with 2.1.8 due to the PERL environment variable being set to <buildenv>/bin/perl by conda-build. Perl is not listed as a build package dependency in our recipe (except on Windows), so it is not installed in the build environment, causing the failure. With CB=2.1.4 it found the system perl. Now that no longer works.

The recipe for openssl on AnacondaRecipes also does not list perl as a build dependency for Linux.

As a workaround, we can clear the PERL env variable in the build.sh script.

**Comment by msarahan** [comment]
sorry, I'm confused.  It seems to me that the recipe should list perl as a build dependency if it is required to build software?  I'll recommend that internally, too.

I agree that I also should not set these language environment variables when their associated packages are not listed as build time dependencies.  I'll try to add that in soon.

**Comment by tomashek** [comment]
In this case, CB is prescribing the location of perl. It used to be that the user could allow a system installation to be used rather than requiring the perl conda package.

If you make the change that does not set PERL in the env unless the perl conda package is a build requirement, that would continue to allow users the choice of where builds should get perl.

**Comment by msarahan** [comment]
Sure, but I see the point of conda-build being to prescribe whatever is necessary to completely and repeatably describe a build process.  I don't see how it is ever desirable to have a "latent" dependency for users to trip over - even if it is something that is almost always installed on the system, like perl.  Do you disagree?

**Comment by mingwandroid** [comment]
I ran into this too when cross compiling OpenSSL. We don't have `perl` in `defaults` for Linux and so IMHO shouldn't be setting `PERL` to something in the build prefix when there's no perl in the build dependencies.

As a result, to be able to complete my build I had no choice but to hack `conda-build`.

We should try to make it a priority to get `perl` (and all the others, lua etc) into `defaults` though.

**Comment by msarahan** [comment]
This should be fixed in 2.1.10 (PR was #1930).  Closing - but please reopen if this is still an issue.
