### ISSUE TITLE
remove group-write permissions from installed and package files

### ISSUE THREAD

**Issue by pavoljuhas** [conda/conda-build#1904]
After #1437 4a2af9c60ee57df90ec75ae7de2f5d35de80c25d the installed files have group-write
permission.  This is a significant security risk, because other uses from the install-tree owner group can modify .py or .pth file with malicious code.  It may be also possible for other user to inadvertently change owner's installation if they activate her Anaconda environment and issue some `conda install` or `conda update` command.

Please remove the `group-write` permission from the package archives and from the installed files.  If needed for a group-maintained installation, this should be an opt-in feature with a clear specification of the group for the installed group-writable files.

**Comment by mingwandroid** [comment]
Permissions are baked into the packages at build time and doing something more dynamic isn't a simple task (or likely globally acceptable for all files in all packages).

If this is necessary then we'll need to spend some time figuring out how best to approach it. Changes would be necessary in both `conda` and `conda-build` and changing the default for packages built going forwards would break the group administration capability. For now, can you manually run `chmod` after running `conda install`?

Pinging @csoja and @kalefranz.

**Comment by kalefranz** [comment]
The only permissions conda modifies itself are for entry point files created at install time, and then it's only modifying the execute permission.  All other permissions get set either through the umask of the user running conda or as @mingwandroid said baked into the package tarballs at build time.

**Comment by mingwandroid** [comment]
We need to discuss whether to do something better here along the lines of the opt-in feature @pavoljuhas requested.

**Comment by pavoljuhas** [comment]
> For now, can you manually run chmod after running conda install?

I am the only user on my system, so security is not an issue there.  However, I feel a bit uneasy about building and sharing packages with unsafe permissions.  I could post-filter the tar files from `conda-build`, but I don't think there is much point if all other packages would get still installed with group-write permissions.

> All other permissions get set either through the umask of the user running conda or as @mingwandroid said baked into the package tarballs at build time.

My account has umask set to 022, however there are group-writable files in my own Anaconda tree.
`conda install` must indeed pick permissions from the package tarballs which have the group-write permission forced in.  I feel appearance of group-writable files is unexpected and unsafe behavior for a user-only installation.

I think a better way is to use safe permissions (and ownership, see #1905) in the tarballs and have some configuration flag for a group-wide installation of Anaconda and the desired group for authorized users.  If such flag is on, `conda-install` should add the group-write permission and adjust group-ownership of the installed files accordingly.
