### ISSUE TITLE
jinja2 templating can't see changes to environment variables

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#191]
If a change is made to the environment variables based on a value from the meta.yaml, then it won't be present in the jinja2 templating, because it runs before the meta.yaml is parsed at all. For example, the build prefix and many other paths change if binary_has_prefix_files is set.

**Comment by asmeurer** [comment]
There are hacks around this now, some of which are not sufficient (see https://github.com/conda/conda-build/pull/223). I think the templating system is broken by design. You can't template anything in that requires knowledge of anything else in the meta.yaml.  This includes things like the GIT_DESCRIBE_* variables (which require knowledge of the fact that the build is a git repo at all, and can't even be run correctly until after the source is checked out). 

A better system would be to have some kind of variable system, which is valid YAML, where the variables can be replaced with their real values at the appropriate time in the build process (and possibly even corrected if they need to be).

**Comment by jakirkham** [comment]
This may be fixed actually as there is a two pass system now. So, undefined variables on the first pass get set after acquiring the source in a second pass.
