### ISSUE TITLE
'conda' script showing up in bin (Scripts) folder when building conda-devenv package

### ISSUE THREAD

**Issue by nicoddemus** [conda/conda-build#1916]
Hi,

Yesterday I build packages for version `0.9.3` of [conda-devenv](https://github.com/conda-forge/conda-devenv-feedstock) and noticed that the packages for all platforms contain a `conda` script in the `bin` directory: 

```
λ ls conda-devenv-0.9.3-py27_0\bin\
conda  conda-devenv
```

Or `Scripts` on Windows:

```
λ dir /b conda-devenv-0.9.3-py35_0\Scripts\ 
conda
conda-devenv-script.py
conda-devenv.exe
```

I did some local testing and noticed that this problem seems to have been introduced in **2.1.9**, because the exact same recipe when built with **2.1.5**, **.2.1.7** and **2.1.8** do not include the `conda` script above.

I did the same test in **2.1.9** with the `pytest` package it **does not** include the `conda` script, so I think the problem might have to do with the fact that `"conda-devenv"` starts with `"conda"`.

@gqmelo and I suspect this was introduced in #1881, but did not really verify this theory.

**Comment by nicoddemus** [comment]
More info:

`0.9.2` was [built using `conda-build-2.1.7`](https://circleci.com/gh/conda-forge/conda-devenv-feedstock/6) and `0.9.3` with [`conda-build-2.1.9`](https://circleci.com/gh/conda-forge/conda-devenv-feedstock/8), which supports the theory.

**Comment by groutr** [comment]
This should be resolved by https://github.com/conda/conda-build/pull/1913

**Comment by msarahan** [comment]
Needs to be backported to 2.1.x.  I'll do that very soon.

**Comment by nicoddemus** [comment]
Awesome, thanks guys!

**Comment by jakirkham** [comment]
Also saw this on other platforms (Mac and Linux) packages of `conda-smithy` that got built today.

**Comment by gqmelo** [comment]
@msarahan, maybe this bug alone is worth a 2.1.10 release?

**Comment by msarahan** [comment]
I agree, and will work on this today.

**Comment by msarahan** [comment]
2.1.10 is tagged - please ping me if there are further issues on this.

**Comment by gqmelo** [comment]
Thank you @msarahan !
