### ISSUE TITLE
Add an option to determine whether group-write should be set for packaged files, determine best default

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda-build#1918]
Related to https://github.com/conda/conda-build/issues/1904

**Comment by tomashek** [comment]
We at Intel would really like this. Ray helped start the request on my behalf

**Comment by msarahan** [comment]
The "determine best default" scares me.  I'm all for adding an option, but I think the default behavior should be consistent, not heuristic-driven.  I'd be in favor of a .condarc setting to switch it from one way to the other.
