### ISSUE TITLE
mpl_toolkits:Package missing in current linux-32 channels

### ISSUE THREAD

**Issue by mohseniaref** [conda/conda-build#1922]
Hi

I wonder how can I solve this issue
conda install mpl_toolkits
Fetching package metadata .........

PackageNotFoundError: Package missing in current linux-32 channels: 
  - mpl_toolkits

Close matches found; did you mean one of these?

    mpl_toolkits: prompt_toolkit

**Comment by msarahan** [comment]
Conda-build is a package build tool, not a package install tool.  This is the wrong issue tracker.

Your error indicates that the package you want does not exist in any of your current channels.  You might be able to find it by using

```
anaconda search mpl_toolkits
```

Look carefully - you may see channels that have the package, but don't provide it for linux-32.  You need a channel that provides it for linux-32.
