### ISSUE TITLE
Symlink directories has sha256:null in paths.json

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#1934]
Since `sha256` is null, an exception is thrown, `conda._vendor.auxlib.exceptions.ValidationError: Value for sha256 cannot be None.`
Happens with https://github.com/conda-forge/ecl-feedstock/issues/5

cc @mattwala

**Comment by msarahan** [comment]
You probably need to update conda. See https://github.com/conda/conda/pull/4759

**Comment by isuruf** [comment]
Thanks
