### ISSUE TITLE
complex dependencies

### ISSUE THREAD

**Issue by epruesse** [conda/conda-build#1935]
Conda currently (AFAIK) only implements simple dependencies where a package requires a series of packages with an optional range of permissible versions.

There are, however, often more complex requirements:
 - alternative dependencies, e.g. `libxml2 2.1.2 | libxml3* | libxml-ng`
 - exclusions: `pysam >0.8 !0.9.1`
 - other package connections, such as `conflicts`, `breaks`, `suggests`, `recommends`, `provides` or `enhances` (examples taken from dpkg).

Are there any plans to extend conda in this direction?

**Comment by msarahan** [comment]
As merely a consumer of conda's capabilities in this area, I don't think conda-build is the right place to file this issue.  Do you want me to move it to the conda repository?

**Comment by epruesse** [comment]
Yes, I guess conda/conda is the better place. I had looked at #1590 here which somewhat similar.

**Comment by msarahan** [comment]
Yeah, #1590 is related.  Ultimately, conda-build is bound by what conda can do.  It is absolutely not right at all for conda-build to implement its own parsing scheme beyond conda's, unless that scheme is completely specific to building or testing packages (like the jinja2 scheme mentioned in that issue.)

**Comment by msarahan** [comment]
Issue moved to [conda/conda #5069](https://github.com/conda/conda/issues/5069) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jakirkham** [comment]
Sorry, this is my bad. Had suggested raising it here. FWIW I think there were some other points in the original issue that are worth discussing at `conda-build`.

For instance, it would be good to have some method of failing builds that produce linkages that are not satisfied in the test phase. In terms of the original issue, if `fontconfig` has linkages to `xz` libraries that are missing in the test step, that build should be an outright fail. This seems clear on OS X and somewhat clear on Linux. Though it is less clear to me how to do this on Windows.

Admittedly there are other points raised in that issue like how we handle indirect dependencies. Namely if `fontconfig` links to `xz`, but pulls in the dependency indirectly (e.g. through `libxml2`), this should probably be a failure or at least a warning. Though handling this doesn't seem as straightforward.

Perhaps they should go in a new issue or is there an existing one?
