### ISSUE TITLE
STDLIB_DIR does not exist on Windows

### ISSUE THREAD

**Issue by AndresGuzman-Ballen** [conda/conda-build#1948]
While attempting to build python 3.5 on Windows, I found it to fail because %STDLIB_DIR% does not exist (while using conda-build 2.1.10). I did a sanity test and ran mkdir %STDLIB_DIR%\teststdlib_dir and didn't find the directory anywhere except in my C: drive as C:\teststdlib_dir.

I saw that this has happened before but didn't see this change on 2.1.10 using Github's blame feature: https://github.com/conda/conda-build/issues/1760. If there's anymore details you'd like, I can happily provide.

**Comment by msarahan** [comment]
Thanks.  I think I need to backport https://github.com/conda/conda-build/pull/1765 .  The 2.1 series of releases come from the 2.1.x branch, not master.

**Comment by msarahan** [comment]
Fixed in #2006 and should be in latest conda-build version.  Please update and give it a try.  Closing this issue.

**Comment by AndresGuzman-Ballen** [comment]
Great! I'll try it now. Thanks Michael!
