### ISSUE TITLE
build a single Python package that works for all python versions

### ISSUE THREAD

**Issue by hainm** [conda/conda-build#1951]
Hi,

Apology if someone already asked this question (I tried to google and search here but not sure how to specify "correct" keyword).

So our package, [nglview](https://github.com/arose/nglview), is pure Python and JavaScript. It's super simple to install via `pip install nglview` from a single wheel file or tar file. However, some of the users prefer to use `conda` since it (conda) is better in installing Jupyter ecosystem.

Is there any existing way/ or intention to build simple python package that work for all python versions instead of running separate builds for different python version?

The catch here is that we are distributing `nglview` via `bioconda` channel and python 3.6 is not available yet there. 

cheers.
Hai

**Comment by jjhelmus** [comment]
@hainm Conda and conda-build support `noarch: python` packages for exactly this reason.  These allow the creation of a single package that can be installed on all platforms and versions of Python.  There are some restrictions on what type of package can be `noarch: python`, specifically there cannot be compiled code and the package requirements must be the same on all platforms and Python versions.  A recent [blog post](https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages) provides additional details and instructions on how to build these.  Searching the [conda documentation](https://conda.io/docs/) for `noarch` will also bring up some content.

**Comment by ma-ba** [comment]
Note that `bioconda` currently does not support `noarch: python`, yet.

**Comment by hainm** [comment]
Thank you guys.
