### ISSUE TITLE
--output does not respect --output-folder

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1957]
From @stuartarchibald, via flowdock:

Think I might have hit a conda-build bug when developing a part of this tool. conda build RECIPE --output --output-folder=/foo/bar, the output doesn't ack the output-folder, is this intended?

**Comment by stuartarchibald** [comment]
An example would be (using https://github.com/numba/numba as I happen to have it at the command prompt, `$` is the prompt):
```
$ conda build --numpy=1.11 --output --output-folder=/tmp buildscripts/condarecipe.local
<INSTALL_PATH>/anaconda3/conda-bld/linux-64/numba-0.33.0.dev-np111py35_271.tar.bz2
```
I would expect this to produce:
```
/tmp/numba-0.33.0.dev-np111py35_271.tar.bz2
```
