### ISSUE TITLE
Proxy handling improvements

### ISSUE THREAD

**Issue by timsnyder** [conda/conda-build#1959]
1. conda build recognizes HTTP_PROXY and HTTPS_PROXY from the environment in [environ.py](https://github.com/conda/conda-build/blob/3b1e68085ac85509e04867800122243df038f651/conda_build/environ.py#L293-L294) but it doesn't keep the FTP proxy information from FTP_PROXY.  Need to start keeping that.  It is currently ruining my ability to fetch sources in conda-build recipes that use FTP.
   * conda itself also obeys the upper-case version of the variables see https://conda.io/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers
1. Programs like wget expect the proxy environment variables to be ''lower-case''.  For example, wget will pay attention to 'http_proxy' but doesn't obey 'HTTP_PROXY'. References supporting this lower-case nonsense:
   * http://git.savannah.gnu.org/cgit/wget.git/tree/src/retr.c?h=v1.19.1&id=6620c5156f363036079d413bfa567e9d871bb30d#n1292
   * https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca

To avoid issues with some programs accepting upper-case env vars and others wanting them to be lower-case, we should:
1. have a single, preferred casing that is supported via the conda config mechanisms documented at https://conda.io/docs/building/environment-vars.html#environment-variables-set-during-the-build-process
1. conda-builds env dictionary creation should define duplicate env variables with the non-preferred casing.

**Comment by timsnyder** [comment]
@msarahan Looking at [environ.py](https://github.com/conda/conda-build/blob/3b1e68085ac85509e04867800122243df038f651/conda_build/environ.py#L293-L294) after rereading the [conda config docs for proxies](https://conda.io/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers), it seems like conda-build may be ignoring the configured proxy in the .condarc because environ.py goes straight to `os.getenv('HTTP_PROXY', '')` instead of asking the conda config mechanisms what the proxy should be.  I know I've run into this before and thought it was confusing but just moved on with the environment variables taking care of things for me.  In general, does conda-build try to obey the conda config?

**Comment by msarahan** [comment]
@timsnyder and I agreed in a phone meeting today that we should split this into two issues:

1. Conda-build should follow Tim's proposal above for the proxy environment variables.
2. Long-term, Conda-build should absolutely respect .condarc for all configuration that conda supports.  It is not clear how to find all instances where conda-build is not drawing from .condarc appropriately.  That's what makes this long-term.
