### ISSUE TITLE
conda install --use-local not working after conda-build --build-only

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1966]
_From @rmancy-smg on April 28, 2017 6:45_

Hi,

Running `conda build --build-only my_package` does not put any tarballs into the `conda-bld` directory. I would have expected a build system to create a tarball as part of the output.

When `conda install --use-local my_package` runs, it looks in the `conda-bld` directory, but can't find the tarball and so fails. Of course, this problem doesn't come about if you just run `conda build my_package`. I suspect this is because it needs to install the package into a test environment, and thus the tarball would have to be created in the process.

I'm not sure if this behaviour is by design, or if I'm doing something else wrong, but I certainly didn't expect it.

_Copied from original issue: conda/conda#5175_

**Comment by msarahan** [comment]
@rmancy-smg,

``--build-only`` is somewhat strangely described.  It actually stops short of producing a package.  I am not completely sure what your use case is, but you might want ``--no-test``, or perhaps ``--no-anaconda-upload``

**Comment by rmancy-smg** [comment]
That's actually what I started off using (a combination of both of your suggestions), and then I saw `--build-only` and thought that would be a succinct way of doing it. I'll revert back to my previous behaviour :) Thanks.

**Comment by adriendelsalle** [comment]
Hello!

I was close to write a new issue about the same topic.
@msarahan,  why the `--build-only` option is not **only** a combination of `--no-test` and `--no-anaconda-upload`?
Is there a point to *build* a package and produce/get no artifact ? It looks like a bug isn't it ?

Thanks in advance for your support!

**Comment by adriendelsalle** [comment]
Add reference to a 4 years pending issue #632
