### ISSUE TITLE
perl only test.imports is creating run_test.py

### ISSUE THREAD

**Issue by timsnyder** [conda/conda-build#1967]
I'm on 3.0.0beta1-4-gec5416844 and a perl-only recipe is failing in test phase because the `test.imports` section is creating `run_test.py` that tries to `import LWP::UserAgent` and fails miserably because Python doesen't use `::`

I have a PR that I'm going to submit once I have this issue open.

**Comment by msarahan** [comment]
Nice, thanks for looking into this.
