### ISSUE TITLE
Conda skeleton does not support environment markers

### ISSUE THREAD

**Issue by evhub** [conda/conda-build#1974]
[PEP 508](https://www.python.org/dev/peps/pep-0508) added support for [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) in PyPI version specifications. Specifically, environment markers allow you to have versions like ([example on PyPI here](https://pypi.python.org/pypi/coconut))
```
pygments<2.3,>=2.2;python_version>='2.7'
prompt-toolkit<1.1,>=1.0;python_version>='2.7'
futures<3.1,>=3.0;python_version<'3'
argparse<1.5,>=1.4;python_version<'2.7'
```
where the package on the left is only a dependency if the current Python version meets the requirement on the right. This is a very useful feature for packages that aim to support multiple Python versions.

However, when `conda skeleton pypi` creates `meta.yaml`, it does not respect the environment markers, leaving any dependencies with environment markers _completely out of the dependency structure_. Thus, when one runs `conda build` on such a skeleton, it fails with (full error at https://github.com/evhub/coconut/issues/246)
```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml
```
since `setuptools` tries to respect the environment markers, but `conda` won't let it.

This is a major problem for packages that use environment markers in their dependencies. It'd be great if this could be fixed, but until then, do you have any ideas for a suitable workaround?

**Comment by msarahan** [comment]
I think selectors are the nearest concept in conda-build: https://conda.io/docs/building/meta-yaml.html#preprocessing-selectors

Adding translation of environment markers to selectors to the skeleton generator is definitely desirable, but I don't think I'll be able to get to it any time soon.  PRs welcome - and I'd be happy to answer any questions if anyone wants to tackle it.
