### ISSUE TITLE
ENH: conda skeleton -t python https://github.com/org/project 

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1975]
_From @westurner on January 27, 2015 0:22_

It would be really convenient to be able to generate a `meta.yml`  w/ `conda skeleton` from:
- a GitHub URL
- a pypi package w/ a "Homepage URL" that matches `github.com` and/or `bitbucket.org/`

Use case: https://github.com/audreyr/cookiecutter/issues/232

```
conda skeleton -t python https://github.com/audreyr/cookiecutter/
```

Where `-t python` would hint that there should be a setup.py found in the root directory.

_Copied from original issue: conda/conda#1109_

**Comment by kalefranz** [comment]
_From @asmeurer on January 27, 2015 17:31_

conda skeleton pypi already supports building from a url so this should be pretty easy to add using the same logic.

**Comment by kalefranz** [comment]
_From @westurner on January 28, 2015 19:52_

Maybe `git-py` or `git-python` instead of `-t python`?

**Comment by kalefranz** [comment]
_From @westurner on January 28, 2015 19:53_

Is there support for `hg`?

**Comment by kalefranz** [comment]
_From @asmeurer on January 28, 2015 19:57_

conda build has support for hg yes

**Comment by kalefranz** [comment]
_From @xguse on August 14, 2015 20:19_

Sooo...... Has this gotten any love?  I REALLY want this to be a thing.  I have a lot of my code that is mostly for personal use as `pip` installable git repos.  Being able to build a conda package with `conda skeleton -t python https://github.com/USER/PROJECT/` would REALLY help me complete my transition from pip/virtaulenv.  If its not too complicated I would even offer to prepare a pull request but I wouldn't mind being pointed in the right direction regarding conda's code etc.

If not from git repos specifically, why not be able to point to a pip installable directory and just use the setup.py as a guide to generate the `meta.yaml`.  This might even be possible but I cant find it any of the docs.

**Comment by kalefranz** [comment]
_From @westurner on August 14, 2015 20:43_

On Aug 14, 2015 3:19 PM, "Augustine (Gus) Dunn" notifications@github.com
wrote:

> Sooo...... Has this gotten any love? I REALLY want this to be a thing. I
> have a lot of my code that is mostly for personal use as pip installable
> git repos. Being able to build a conda package with conda skeleton -t
> python https://github.com/USER/PROJECT/ would REALLY help me complete my
> transition from pip/virtaulenv. If its not too complicated I would even
> offer to prepare a pull request but I wouldn't mind being pointed in the
> right direction regarding conda's code etc.

https://github.com/conda/conda-build/search?utf8=%E2%9C%93&q=skeleton

https://github.com/conda/conda-build/blob/master/conda_build/pypi.py

> If not from git repos specifically, why not be able to point to a pip
> installable directory and just use the setup.py as a guide to generate the
> meta.yaml. This might even be possible but I cant find it any of the docs.
- Host packages with http://doc.devpi.net/latest/
- create a cookiecutter and paste the github uris:
  https://github.com/audreyr/cookiecutter/issues/232
- http://conda.pydata.org/docs/building/meta-yaml.html#source-section

**Comment by kalefranz** [comment]
_From @jakereps on July 15, 2016 5:4_

``` bash
$ conda skeleton pypi --manual-url https://github.com/[user]/[repo]/archive/[branch].zip
```

**Comment by kalefranz** [comment]
_From @asmeurer on July 15, 2016 18:58_

Ideally this would work with the real github url and create a recipe that downloads the source from git.

**Comment by westurner** [comment]
Is there a new best way to do this? Conda-smithy?
