### ISSUE TITLE
conda skeleton pypi should use pip to build/install

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1977]
_From @ChrisBarker-NOAA on March 29, 2016 17:0_

conda skeleton creates build  scripts that do:

setup.py install

which is the "old" way to install python packages. It has the advantage of working with either setuptool sor raw distutils, but it has the disadvantage of not creating the proper pip meta-data, and sometimes using easy-install under the hood to build and install dependencies.

The "Modern" way to do it is with pip:

pip install ./

pip will monkey-patch setuptools in if necessary and create the proper pip meta-data.

(we probably want --no-deps, too, and maybe another flag or two.)

_Copied from original issue: conda/conda#2314_

**Comment by msarahan** [comment]
this gets very tricky with entry points, especially on Windows.  Pip has switched to using EXE entry points that embed the python script and the python interpreter prefix in the EXE.  Conda-build does set things up for prefix replacement, and conda does do the prefix replacement, so this all *should* work.  However, I don't think anyone has used it enough to call it the correct way for everyone.
