### ISSUE TITLE
"conda skeleton pypi" is failing with "xml.parsers.expat.ExpatError: no element found: line 1, column 0"

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1978]
_From @tadeu on April 2, 2014 16:32_

I'm trying to create a package for IPython 2.0 on a freshly installed `conda 3.3.2 py27_0` with `conda-build 1.3.1 py27_0`. I also have `anaconda 1.9.1 np18py27_0` loaded in an environment.

The command `conda skeleton pypi ipython` fails with the following traceback:

```
Traceback (most recent call last):
  File "D:\Miniconda\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Miniconda\lib\site-packages\conda_build\main_skeleton.py", line 124, in main
    args.func(args, p)
  File "D:\Miniconda\lib\site-packages\conda_build\main_skeleton.py", line 135, in execute
    pypi.main(args, parser)
  File "D:\Miniconda\lib\site-packages\conda_build\pypi.py", line 200, in main
    versions = client.package_releases(package)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "D:\Miniconda\lib\xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1471, in parse_response
    p.close()
  File "D:\Miniconda\lib\xmlrpclib.py", line 560, in close
    self._parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

I'm also not able to use `conda --debug skeleton pypi ipython`, with the following error message:

```
usage: conda-skeleton-script.py [-h] {pypi,cpan} ...
conda-skeleton-script.py: error: argument repo: invalid choice: 'skeleton' (choose from u'pypi', u'cpan')
```

_Copied from original issue: conda/conda#636_

**Comment by kalefranz** [comment]
_From @asmeurer on April 2, 2014 16:42_

`--debug` is broken with conda build, but there are no useful debug messages anyway.

**Comment by kalefranz** [comment]
_From @asmeurer on April 2, 2014 16:43_

It works for me. It looks like it was some issue with the data from PyPI, not a conda skeleton bug.

**Comment by kalefranz** [comment]
_From @tadeu on April 2, 2014 17:34_

Ok, what would be the best way for me to get more information about this error?

**Comment by kalefranz** [comment]
_From @asmeurer on April 2, 2014 19:13_

Are you maybe behind a proxy or something?

By the way, we will have IPython 2.0 released later today.

**Comment by kalefranz** [comment]
_From @tadeu on April 2, 2014 19:51_

There's no proxy here, `pip` is able to access PyPI normally (I installed IPython through`pip install`). I'm not able to use `conda skeleton` at all... it gives this error for any package that I try to use.  Anyway, if it's a connection problem, it could give a better error message.

About IPython 2.0, nice, I'll switch to the conda package when it's released.

**Comment by msarahan** [comment]
Wow, a 3 year old issue.  @tadeu is this still of interest at all?

**Comment by kalefranz** [comment]
Yeah @msarahan I bumped a few over to you.  Figured it's best for you to close them here.
