### ISSUE TITLE
conda build -- build dependencies

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1996]
_From @bkreider on October 24, 2013 6:0_

It tough to build packages that have build dependencies provided via Binstar without editing the .bashrc.  

I don't know the best way of solving this:
- Deps could be fully specified to point to a binstar channel - +1
- Defining binstar channels on the command-line when building - with access tokens
- Allowing one to pre-install packages into an environment with all of the dependencies. 

_Copied from original issue: conda/conda#320_

**Comment by kalefranz** [comment]
_From @ilanschnell on October 31, 2013 20:52_

An important thing to note is that when building packages, the directory in which the final conda packages are placed, e.g. ~/conda-bld/linux-64, is also added to the channels.  This means that when you build a package A (which depends on B, which you have already build), the build dependency B will be found (if you're build B and then A on the same machine), even if you don't upload B to binstar or anywhere else.

**Comment by kalefranz** [comment]
_From @asmeurer on January 28, 2014 21:15_

I suppose we should add the `-c` option to conda build.

**Comment by kalefranz** [comment]
_From @ilanschnell on January 28, 2014 21:57_

What would the `-c` option do?

**Comment by kalefranz** [comment]
_From @asmeurer on January 28, 2014 21:58_

Same thing it does everywhere. Add a channel to the list of channels that is searched.

**Comment by kalefranz** [comment]
_From @asmeurer on March 4, 2015 22:6_

The -c flag was added https://github.com/conda/conda-build/pull/334

**Comment by kalefranz** [comment]
_From @goanpeca on March 25, 2017 9:53_

@bkreider can we close this?

**Comment by msarahan** [comment]
I'm leaving this open because I think we could still really use channel specification on a per-package basis, rather than relying on channel priority for the whole file.

**Comment by kalefranz** [comment]
I agree.  And getting this incorporated properly into conda's user interaction is one of my top priorities after we get 4.4 out.  Ideally I'd like to get it into 4.4 but I don't think it'll make it.
