### ISSUE TITLE
conda build causes different compiler flags being used

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1997]
_From @twiecki on December 12, 2013 18:57_

I try to compile pymc on OSX. If I just run `python setup.py` build it works fine, but `conda build` of the same package produces an error. The `build.sh` does nothing more: https://github.com/fonnesbeck/conda-recipes/blob/master/pymc/build.sh

I tracked it down to different compile flags being set, manually calling `setup.py` produces gfortran being called with these flags, among others:

`/usr/bin/gfortran -Wall -m64 -Wall -undefined dynamic_lookup -bundle`

While conda build which also just calls setup.py omits some necessary flags:
`/usr/bin/gfortran -Wall -arch x86_64`

Why would the flags be different between these two?

_Copied from original issue: conda/conda#423_

**Comment by kalefranz** [comment]
_From @ilanschnell on December 13, 2013 5:5_

When you look at all the environment variables, and then also output them from within the `build.sh` you might notice some difference.  Conda build sets some environment variables, see: http://docs.continuum.io/conda/build.html, and discards the environment variables set by the user (who runs `build conda`) in order to make builds more reproducible.

**Comment by msarahan** [comment]
If you want to bring in your values, you can explicitly list them in the recipe:

https://conda.io/docs/building/meta-yaml.html#use-environment-variables
