### ISSUE TITLE
lxml does not build inside a conda environment

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1998]
_From @srossross on May 9, 2014 21:13_

```
gcc -bundle -undefined dynamic_lookup -L/Users/sean/anaconda/envs/binstar/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.etree.o -L/Users/sean/anaconda/lib -L/Users/sean/anaconda/envs/binstar/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.5-x86_64-2.7/lxml/etree.so

ld: mach-o string pool extends beyond end of file in /Users/sean/anaconda/lib/libxslt.dylib file '/Users/sean/anaconda/lib/libxslt.dylib' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/sean/anaconda/envs/binstar/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/jz/4s_n94bx7d96tsmyqq76nq2h0000gn/T/pip_build_sean/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jz/4s_n94bx7d96tsmyqq76nq2h0000gn/T/pip-monM6u-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/jz/4s_n94bx7d96tsmyqq76nq2h0000gn/T/pip_build_sean/lxml

```

See also: https://github.com/astropy/astroquery/issues/278

_Copied from original issue: conda/conda#721_

**Comment by kalefranz** [comment]
_From @srossross on May 9, 2014 21:14_

using `pip install lxml`

**Comment by kalefranz** [comment]
_From @ilanschnell on May 9, 2014 23:2_

Works for me, on OSX 10.7.5

**Comment by kalefranz** [comment]
_From @suhassatish on June 3, 2014 21:17_

I am hitting this issue on OS X 10.9.2
Whats the work around? Should I remove anaconda? I hit the issue with "pip install lxml"

**Comment by kalefranz** [comment]
_From @cloudride on August 20, 2014 19:6_

@suhassatish Have you resolved the issue? I got the same...

**Comment by kalefranz** [comment]
_From @asmeurer on August 20, 2014 19:39_

I was able to `pip install lxml` in a clean environment with Python 2.7, pip, and libxslt.

```
$pip install lxml
Downloading/unpacking lxml
  Downloading lxml-3.3.5.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py (path:/private/var/folders/yc/8wpl9rlx47qgzxqpcf003k280000gn/T/pip_build_aaronmeurer/lxml/setup.py) egg_info for package lxml
    /Users/aaronmeurer/anaconda/envs/test/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.3.5.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    Building against libxml2/libxslt in the following directory: /Users/aaronmeurer/anaconda/envs/test/lib

    warning: no previously-included files found matching '*.py'
Installing collected packages: lxml
  Running setup.py install for lxml
    /Users/aaronmeurer/anaconda/envs/test/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.3.5.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    Building against libxml2/libxslt in the following directory: /Users/aaronmeurer/anaconda/envs/test/lib
    building 'lxml.etree' extension
    /usr/bin/clang -fno-strict-aliasing -I/Users/aaronmeurer/anaconda/envs/test/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/aaronmeurer/anaconda/envs/test/include -I/Users/aaronmeurer/anaconda/envs/test/include/libxml2 -I/private/var/folders/yc/8wpl9rlx47qgzxqpcf003k280000gn/T/pip_build_aaronmeurer/lxml/src/lxml/includes -I/Users/aaronmeurer/anaconda/envs/test/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.etree.o -w -flat_namespace
    /usr/bin/clang -bundle -undefined dynamic_lookup -L/Users/aaronmeurer/anaconda/envs/test/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.etree.o -L/Users/aaronmeurer/anaconda/envs/test/lib -L/Users/aaronmeurer/anaconda/envs/test/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.5-x86_64-2.7/lxml/etree.so
    building 'lxml.objectify' extension
    /usr/bin/clang -fno-strict-aliasing -I/Users/aaronmeurer/anaconda/envs/test/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/aaronmeurer/anaconda/envs/test/include -I/Users/aaronmeurer/anaconda/envs/test/include/libxml2 -I/private/var/folders/yc/8wpl9rlx47qgzxqpcf003k280000gn/T/pip_build_aaronmeurer/lxml/src/lxml/includes -I/Users/aaronmeurer/anaconda/envs/test/include/python2.7 -c src/lxml/lxml.objectify.c -o build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.objectify.o -w -flat_namespace
    /usr/bin/clang -bundle -undefined dynamic_lookup -L/Users/aaronmeurer/anaconda/envs/test/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.objectify.o -L/Users/aaronmeurer/anaconda/envs/test/lib -L/Users/aaronmeurer/anaconda/envs/test/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.5-x86_64-2.7/lxml/objectify.so

Successfully installed lxml
Cleaning up...
```

**Comment by kalefranz** [comment]
_From @asmeurer on August 20, 2014 19:40_

@cloudride can you paste the full output you get from `pip`?

**Comment by kalefranz** [comment]
_From @suhassatish on August 20, 2014 20:49_

@cloudride - I took the same approach as asmeurer (reinstall in a clean environment outside of anaconda) and was able to solve my problem.

**Comment by kalefranz** [comment]
_From @cloudride on September 6, 2014 19:37_

Finally I decided to go with standard Python distribution, in this particular case it was sufficient.

**Comment by kalefranz** [comment]
_From @baisk on February 13, 2015 7:35_

I failed too. I ues virtualenv in a clean environment and do pip install lxml.

cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/Users/gaowei/anaconda/include -I/Users/gaowei/anaconda/include/libxml2 -I/Users/gaowei/Dreamer/scrapy/.venv/build/lxml/src/lxml/includes -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.9-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace

cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.9-intel-2.7/src/lxml/lxml.etree.o -L/Users/gaowei/anaconda/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.9-intel-2.7/lxml/etree.so

ld: mach-o string pool extends beyond end of file in /Users/gaowei/anaconda/lib/libxslt.dylib file '/Users/gaowei/anaconda/lib/libxslt.dylib' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'cc' failed with exit status 1

**Comment by kalefranz** [comment]
_From @toasteez on July 8, 2015 15:45_

When installing pandasdmx it trys to install lxml and regardless of whether it is there the following error happend.   I have latest conda and anaconda.

----- Installing 'pandasdmx' -----
Collecting pandasdmx
  Using cached pandaSDMX-0.2.2-py2.py3-none-any.whl
Collecting lxml (from pandasdmx)
  Downloading lxml-3.4.4-cp27-none-win_amd64.whl (3.3MB)
Requirement already up-to-date: pandas in c:\anaconda\lib\site-packages (from pandasdmx)
Requirement already up-to-date: requests in c:\anaconda\lib\site-packages (from pandasdmx)
Requirement already up-to-date: python-dateutil in c:\anaconda\lib\site-packages (from pandas->pandasdmx)
Requirement already up-to-date: pytz>=2011k in c:\anaconda\lib\site-packages (from pandas->pandasdmx)
Requirement already up-to-date: numpy>=1.7.0 in c:\anaconda\lib\site-packages (from pandas->pandasdmx)
Requirement already up-to-date: six>=1.5 in c:\anaconda\lib\site-packages (from python-dateutil->pandas->pandasdmx)
Installing collected packages: lxml, pandasdmx
Exception:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pip\basecommand.py", line 223, in main
    status = self.run(options, args)
  File "C:\Anaconda\lib\site-packages\pip\commands\install.py", line 299, in run
    root=options.root_path,
  File "C:\Anaconda\lib\site-packages\pip\req\req_set.py", line 646, in install
    **kwargs
  File "C:\Anaconda\lib\site-packages\pip\req\req_install.py", line 813, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Anaconda\lib\site-packages\pip\req\req_install.py", line 1008, in move_wheel_files
    isolated=self.isolated,
  File "C:\Anaconda\lib\site-packages\pip\wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Anaconda\lib\site-packages\pip\wheel.py", line 299, in clobber
    assert not info_dir, 'Multiple .dist-info directories'
AssertionError: Multiple .dist-info directories
----- Failed to install 'pandasdmx' -----

**Comment by kalefranz** [comment]
Guessing this can now be closed.  Moving it to conda-build to be sure though.

**Comment by msarahan** [comment]
I recommend building conda packages for anything discussed here.  lxml is available as a conda package.
