### ISSUE TITLE
Markupsafe halts windows builds

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1999]
_From @mrocklin on December 4, 2014 21:7_

Blaze builds were failing on windows 64bit python3 for a while because

Blaze imported Flask
Flask imported Jinja2
Jinja2 imported markupsafe

Importing markupsafe caused windows error R6034

![python3exe](https://cloud.githubusercontent.com/assets/306380/5306064/26214844-7bb6-11e4-9409-0d114188c8d8.png)

Oddly removing and reinstalling markupsafe removed the problem.  

It may also be related to this ignored error that popped up 

```
C:\Users\binstar\Miniconda\envs\_build\Lib\SITE-P~1\MARKUP~1\_speedups.pyd - Access is denied.
```

Here is a log of a full conda build session that hangs.  https://binstar.org/blaze/blaze/builds/57/16

@srossross @mwiebe and I all looked at this for an hour or so and tracked it down to this.  

_Copied from original issue: conda/conda#1029_

**Comment by kalefranz** [comment]
_From @srossross on December 4, 2014 21:15_

It is worth mentioning that this only happens in the the conda `_build` and `_test` environments when run by the `conda build` command.  When we manually removed and reinstalled markupsafe the tests ran.

**Comment by kalefranz** [comment]
_From @asmeurer on February 12, 2015 23:8_

This should really be a conda-build issue. I guess the problem is that conda build can't remove that file from the build environment when it is running, and somehow that breaks it.

**Comment by kalefranz** [comment]
_From @dragon788 on July 12, 2016 22:6_

I have a feeling if conda is using virtualenv it is related to that. I'm seeing the same errors with MarkupSafe/Jinja2 on other projects, but only if they run in an virtualenv (ie virtualenv, pew, tox, etc).

**Comment by msarahan** [comment]
Closing as too old to investigate.  If anyone runs into this again, please let me know and I'll reopen.

**Comment by patanijo** [comment]
I am seeing this same error running on trying to do windows builds on python 2.7. It only manifests itself if I have a test section and either have imports or a run_test.py file as part of the recipe.

Files locked include 
_speedups.pyd

when python was included as a build time dependency, several other files in the test installation had an Access denied error including `python.exe` and `python27.dll`

conda version is 4.5.11 
conda-build is 3.16.12

Would you like me to reopen here or as a different issues
