### ISSUE TITLE
Doesn't handle recursion ('**') in package_data setup.py option

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#2003]
_From @filmackay on January 26, 2016 9:53_

conda is not handling the following setup.py line: `package_data={'sandman2': ['templates/**.html']}`

Building without conda correctly picks up the `templates/admin/index.html` file, whereas conda does not. It should?

eg. `https://github.com/jeffknupp/sandman2/blob/master/setup.py`

_Copied from original issue: conda/conda#1993_

**Comment by msarahan** [comment]
@filmackay Sorry for the delay here.  ** is a python-3 only syntax (look up the glob2 project for a backport).  Is your root miniconda/anaconda install python 2 or 3?

There's really little that conda-build would do with this data - it should be running your setup.py in a conda environment that it creates.  If that env is python 2, I expect it would not work.  If it's python 3, I think it should.  If you past a traceback or more info, I can look.
