### ISSUE TITLE
bug in 2.1.12 - get_site_packages used with insufficient arguments

### ISSUE THREAD

**Issue by pavoljuhas** [conda/conda-build#2008]
conda-build 2.1.12 crashes, because 27703fc213676ef70213fab7a81d81d207cb458c from #2006 introduced a second mandatory argument to [utils.get_site_packages()](https://github.com/conda/conda-build/blob/27703fc213676ef70213fab7a81d81d207cb458c/conda_build/utils.py#L491), but some calls of that function were not updated:

- https://github.com/conda/conda-build/blob/231d8fc4828ff46f7ae2e2521374e97cfc2f0afa/conda_build/render.py#L115
- https://github.com/conda/conda-build/blob/231d8fc4828ff46f7ae2e2521374e97cfc2f0afa/conda_build/post.py#L94

My conda-build jobs crash on the call in post.py.  Please correct.

**Comment by msarahan** [comment]
Thanks.  Sorry our test suite didn't cover that one.

**Comment by msarahan** [comment]
fixed by #2009, closing.  2.1.13 has been tagged and should be available soon.
