### ISSUE TITLE
Parallel build execution

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2017]
@isuruf asked in a conda-forge meeting today about parallel execution of multiple builds.

I'm concerned about potential resource overconsumption when multiple builds try to use all of the CPUs on a system.  Otherwise, I have no problem with the idea.  I think it will require proper expression of the build tree as a DAG (rather than its current crappy while loop form), and then it's just a question of having an intelligent job execution framework.  This is a reasonably large project.  If anyone would like to undertake it, I'd be happy for this to go into conda-build.  However, Continuum's needs in this area are met by the Concourse build system (https://github.com/conda/conda-concourse-ci), so I can't justify spending time on this myself.

**Comment by isuruf** [comment]
> I'm concerned about potential resource overconsumption when multiple builds try to use all of the CPUs on a system.

SageMath project uses make's ability to do parallel work to divide the work between processors and to not overconsume resources. Similarly conda can use `CPU_COUNT` to control the building. This has the potential of under consumption of resources though.

**Comment by msarahan** [comment]
conda-build provides CPU_COUNT to each job right now.  If you have multiple builds that all use something like ``make -j${CPU_COUNT}``, what happens?

**Comment by isuruf** [comment]
You set `CPU_COUNT` to each build appropriately. Say you have 20 packages to build and there are 8 packages with no dependencies. If you have 16 threads, you give each package `CPU_COUNT=2` and once the package is built, the 2 threads are freed and they are assigned to another package.

**Comment by msarahan** [comment]
That scheduling is exactly what I don't want to do myself for conda-build.  Scheduling is a problem for other libraries - perhaps someone could work dask's scheduler into conda-build.

It is just an extraordinarily hairy problem.  Right now, people can run more than one conda-build process at a time.  Under your proposal, there would need to be only one, or at least one central job dispatch server.

**Comment by isuruf** [comment]
Yes, if this is ever implemented, it should use an existing scheduling library. You'll still need to have more than one conda-build process to do parallel building of packages each of which will be built parallelly as well.

**Comment by isuruf** [comment]
ccing @jdemeyer, @embray, @williamstein who was interested in using conda for [sagemath](http://www.sagemath.org) project.

**Comment by jdemeyer** [comment]
> If you have multiple builds that all use something like make -j${CPU_COUNT}

Those individual builds shouldn't do that. If they run `$MAKE` instead of `make -j${CPU_COUNT}`, then all is fine: make ensures that the total number of running processes is limited by the top-level `make`. So, if your top-level command is `make -j10`, there might be 10 packages being built in parallel, each using 1 process or 1 package being built with 10 processes or anything in between.

As @isuruf said, Sage uses this model and it works.

**Comment by jdemeyer** [comment]
Let me also mention one disadvantage with `make`: it is hard to support build parallelism for packages which use a different build system (Python packages for example). Those packages could only be built using a single process.

**Comment by msarahan** [comment]
Yeah, saying everything should use make is not really a solution for us. We are build system agnostic, for better or worse.  How would you account for some things using ninja, others using make, and just for fun, others using visual studio/nmake/msbuild?

Again, I'm happy to put this into conda build if someone else wants to do the work to implement it.  I think it's also easier to do things like conda-concourse-ci, where you layer parallelism on top of conda build.  Having a separate tool will let you have tighter constraints, like "only supports Linux" that we just can't do in conda build.

**Comment by isuruf** [comment]
> Yeah, saying everything should use make is not really a solution for us. We are build system agnostic, for better or worse. How would you account for some things using ninja, others using make, and just for fun, others using visual studio/nmake/msbuild?

This should be handled by a scheduler which will control the value of `CPU_COUNT` sent to each package. Then `ninja -j${CPU_COUNT}` or `make -j${CPU_COUNT}` will work. Scheduler has to make sure the sum of all `CPU_COUNT` is less than the total which is the job of the scheduler anyways.

**Comment by jdemeyer** [comment]
> Scheduler has to make sure the sum of all CPU_COUNT is less than the total number of threads of the computer which is the job of the scheduler anyways.

My point above was that `make` is such a scheduler, except that it only supports `make` of course.

**Comment by wilderfield** [comment]
bump! So, I have a project, where I have about 20 feedstocks, and I need to regularly build all of them together, to keep them in sync. I invoke conda build, serially, one after the other... It takes forever... 

I wonder if conda could build in parallel, and if that even makes sense? Thinking about it now... If each individual build is throwing all of the compute resources at an individual feedstock... maybe parallelization would just slow things down?

**Comment by mingwandroid** [comment]
If I thought there wasn't a huge amount of low hanging fruit in conda and conda build regarding optimization then I would look into this, but I am sure there's lots to be done in the serial case first.

Have you measured which parts of your build take a long time?

**Comment by isuruf** [comment]
> Thinking about it now... If each individual build is throwing all of the compute resources at an individual feedstock... maybe parallelization would just slow things down?

You can use `CPU_COUNT` env variable to control this.

**Comment by wilderfield** [comment]
@mingwandroid @isuruf thank you for your thoughts. I think I need to stay serial, because some packages are dependent on others... plus I am sure you are right, focus on improving the runtime of individual package builds would likely help the most. Thanks again.

**Comment by as-ec** [comment]
I've been looking at a recent issue that suggests that the statement from 2017 "Right now, people can run more than one conda-build process at a time" no longer holds. I think the code [here](https://github.com/conda/conda-build/blob/580862030df2e811dc1b5135da1fa35802c571d0/conda_build/index.py#L1003) establishes a race between two conda-builds attempting to create the same .cache. Am I mistaken here?
