### ISSUE TITLE
guided recipe creation

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#2022]
_From @bryevdv on July 16, 2014 19:9_

Should have a `conda recipe` command that will prompt the user for information, and create a minimal conda recipe directory for them. 

_Copied from original issue: conda/conda#815_

**Comment by kalefranz** [comment]
_From @asmeurer on July 16, 2014 22:25_

conda skeleton wizard?

**Comment by kalefranz** [comment]
_From @bryevdv on July 16, 2014 22:35_

Yes, exactly.

**Comment by msarahan** [comment]
I belive https://github.com/conda/conda-build/pull/1752 would address this nicely.  I'd like to move that PR to a separate conda organization repo, and then register it with the cookiecutter organization upstream.  Closing this issue to consolidate discussion at #1752

**Comment by enelson1995** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test Github Power-up Button!](https://trello.com/c/CAL0OGEe/2-test-github-power-up-button)

**Comment by msarahan** [comment]
@enelson1995 please don't spam on random unrelated issues.  Make a new issue if you need something to test on.
