### ISSUE TITLE
Split native packages can't separate libs and binaries on OSX

### ISSUE THREAD

**Issue by epruesse** [conda/conda-build#2023]
Since #1598, files belonging to a sub-package are removed from `$PREFIX` before the next sub-package is assembled. In native packages, this breaks splitting libraries and binaries into separate sub-packages on OSX: When the paths in the binaries are made relative by `mk_relative_osx -> osx_ch_link` the call to `find_lib` can't find the dynamic libraries referenced.

I'm not sure how to best fix this. I understand that the point of #1598 was to allow files to occur in multiple sub-packages. Since those can't be installed at the same time, they can't interdepend. So perhaps installing the packages listed in `requirements:` of a subpackage into `$PREFIX` before running `post` would solve the issue most cleanly.

Alternatively, having an `exclude:` keyword listing file patterns that although added to `$PREFIX` should not to become part of the current sub-package could perhaps also solve the issue.

**Comment by mingwandroid** [comment]
You are supposed to use `pin_subpackage`. Examples of this can be seen here: https://github.com/mingwandroid/conda-recipes/blob/master/cross-compilers/compilers_generic/meta.yaml

**Comment by msarahan** [comment]
Yeah, to be clear, pin_subpackage is a new thing in conda-build 3 that allows you to refer to other subpackages in the same recipe, and pin/constrain their versions.  In conda-build 2, you can still refer to other subpackages by name, but you have to manage the pin/constraint much more manually.

The right way is to put your files into one subpackage, then have the other subpackage depend on the first one.  Conda build will figure out the right order to build/package them.

**Comment by mingwandroid** [comment]
I should also mention, if ever two packages contain the same file and they're not set up in a way that the cannot be installed at the same time, then that's a problem since you can install both, remove one and would lose that file.

**Comment by epruesse** [comment]
Ah, good. I had been wondering about the use case for deliberately having the same file in sub-packages. It's annoying enough between unrelated packages...

> The right way is to put your files into one subpackage, then have the other subpackage depend on the first one. Conda build will figure out the right order to build/package them.

That's what I assumed / tried. I believe I observed the order to be the same as in the `meta.yaml` though. And, since the mentioned PR, the files are cleared in between calls to `package`, which means that the link-fixing for osx binaries fails.

To be more specific, here's what I was trying to do:

`openmotif` comprises a lot of files, most of which are rarely needed. There are a dozen or so library files needed at run time, about 700 header files and about a 1000 files in documentation and example. So I figured splitting them into `-doc` and `-dev` as is common in other distributions would be preferable to reduce the time needed for install, while still having them should they be needed.

Here's the `meta.yaml`:

```
outputs:
  - name: openmotif-dev
    script: install_dev.sh
    requirements:
      - openmotif
  - name: openmotif
    script: install_main.sh
  - name: openmotif-doc
    script: install_doc.sh
    requirements:
      - openmotif
```

 (Incidentally, having the option to pass an argument to the script referenced in `script:` would help making recipes cleaner comprising fewer tiny files)

The `-doc` package includes some (compiled) examples which require libs from the main package. The `-dev` and the primary package are build first and complete. The build then terminates while packaging the `-doc` subpackage ($PREFIX replaced for reability):

```
INFO conda_build.build:bundle_conda(864): Packaging openmotif-doc-2.3.7-0
number of files: 955
Fixing permissions
Fixing linking of $PREFIX/lib/libXm.4.dylib in $PREFIX/share/Xm/combo2/combo
Error: Could not find lib/libXm.4.dylib
```

That's because `libXm.4.dylib` was copied into `$PREFIX` by `install.sh`, packaged and removed and is no longer available. And while `openmotif` is required by `openmotif-doc`, it's not installed during the package assembly phase.

I can't see a way to put the library where it needs to be for fixing of relative links without it being included in the -doc package.

**Comment by msarahan** [comment]
Can you link to a build log?  You should see the environment creation output for openmotif-doc install the openmotif package.  At that point, it should no longer be considered a "new" file for openmotif-doc.  This may be a bug.  Your recipe seems correct to me.

**Comment by mingwandroid** [comment]
AFAIK, you need to use `pin_subpackage` here, otherwise it'll just fetch older versions of the packages and not sort the builds by intradependency order?

**Comment by epruesse** [comment]
Is `pin_subpackage` available in conda 2.1.10?

**Comment by epruesse** [comment]
Here's a build log (shortened for legibility):

```
INFO conda_build.build:bundle_conda(865): Packaging openmotif-dev-2.3.7-0
INFO conda_build.build:bundle_conda(865): Packaging openmotif-2.3.7-0
BUILD START: openmotif-2.3.7-0
    (actual version deferred until further download or env creation)
updating index in: $CONDA_HOME/conda-bld/osx-64
updating: openmotif-dev-2.3.7-0.tar.bz2
updating: openmotif-2.3.7-0.tar.bz2
updating index in: $CONDA_HOME/conda-bld/noarch

The following NEW packages will be INSTALLED:

    flex:             2.6.3-1  conda-forge
[... all the build requirements...]
    zlib:             1.2.11-0 conda-forge

Source cache directory is: $CONDA_HOME/conda-bld/src_cache
Found source in cache: openmotif-2.3.7.tar.gz
Extracting download
Applying patch: '[...]/recipes/openmotif/patch-lib-XmP.h.diff'
BUILD START (revised): openmotif-2.3.7-0
Package: openmotif-2.3.7-0
source tree in: $PREFIX/../work/motif-2.3.7
number of files: 251
Fixing permissions
Fixing permissions
Detected hard-coded path in text file lib/libMrm.la
Detected hard-coded path in text file lib/libUil.la
Detected hard-coded path in text file lib/libXm.la
$CONDA_HOME/conda-bld/osx-64/openmotif-dev-2.3.7-0.tar.bz2
updating index in: $CONDA_HOME/conda-bld
updating index in: $CONDA_HOME/conda-bld/noarch
number of files: 36
Fixing permissions
Making absolute symlink lib/libXm.dylib -> libXm.4.dylib relative
Making absolute symlink lib/libUil.dylib -> libUil.4.dylib relative
Making absolute symlink lib/libMrm.dylib -> libMrm.4.dylib relative
Fixing linking of $PREFIX/lib/libXm.4.dylib in $PREFIX/bin/xmbind
Fixing linking of @rpath/libXmu.6.dylib in $PREFIX/bin/xmbind
[...more of the same...]
install_name_tool -add_rpath @loader_path/../lib/ $PREFIX/bin/xmbind
Fixing linking of $PREFIX/lib/libUil.4.dylib in $PREFIX/lib/libUil.4.dylib
[...more of the same...]
install_name_tool -add_rpath @loader_path/ $PREFIX/lib/libUil.4.dylib
Fixing linking of $PREFIX/lib/libXm.4.dylib in $PREFIX/bin/mwm
[...more of the same...]
Fixing linking of @rpath/libXt.6.dylib in $PREFIX/lib/libMrm.4.dylib

[...bunch of empty lines...]

INFO conda_build.build:bundle_conda(865): Packaging openmotif-doc-2.3.7-0

Fixing linking of @rpath/libSM.6.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libuuid.1.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libICE.6.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libXft.2.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libfontconfig.1.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libxml2.2.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libicui18n.58.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libicuuc.58.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libicudata.58.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of /usr/lib/libSystem.B.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/liblzma.5.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libiconv.2.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libfreetype.6.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libXrender.1.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libX11.6.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libxcb.1.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libXau.6.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libXdmcp.6.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of /usr/lib/libc++.1.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libjpeg.9.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libpng16.16.dylib in $PREFIX/lib/libMrm.4.dylib
Fixing linking of @rpath/libz.1.dylib in $PREFIX/lib/libMrm.4.dylib
install_name_tool -add_rpath @loader_path/ $PREFIX/lib/libMrm.4.dylib
Fixing permissions
Detected hard-coded path in binary file bin/mwm
Detected hard-coded path in binary file bin/uil
Detected hard-coded path in binary file bin/xmbind
Detected hard-coded path in binary file lib/libMrm.4.dylib
Detected hard-coded path in binary file lib/libMrm.dylib
Detected hard-coded path in binary file lib/libUil.4.dylib
Detected hard-coded path in binary file lib/libUil.dylib
Detected hard-coded path in binary file lib/libXm.4.dylib
Detected hard-coded path in binary file lib/libXm.dylib
$CONDA_HOME/conda-bld/osx-64/openmotif-2.3.7-0.tar.bz2
updating index in: $CONDA_HOME/conda-bld
updating index in: $CONDA_HOME/conda-bld/noarch
number of files: 955
Fixing permissions
Fixing linking of $PREFIX/lib/libXm.4.dylib in $PREFIX/share/Xm/todo/todo
Error: Could not find lib/libXm.4.dylib
```

**Comment by msarahan** [comment]
``pin_subpackages`` is only conda-build 3.  Sorry.

I think I may be getting functionality mixed up between the 2.1.x series and the 3.0 series.  It seems like I need to backport the environment creation part of conda-build 3, so that this particular subpackage example works.  I don't have plans to backport ``pin_subpackages`` to the 2.1.x series, but 3.0 should be out soon.

**Comment by epruesse** [comment]
The example binaries in the openmotif package aren't that important. In general, splitting into `*-dev`, `lib*`, `*-util`, `*-dbg` and `*-doc` would be useful to minimize size and number of files installed (also by cutting down on number of dependency links, full package may require more things than just its libs do). If it's coming soon, that's good enough for me.
