### ISSUE TITLE
outputs section needs to be added to metadata.py

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2026]
https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L357

It's not presently in there.  It's not breaking anything, but it should be added for completeness.

**Comment by msarahan** [comment]
On second thought, I'm not sure it can be added.  That field is unlike the others.  It's a list of dicts, not a dict of dicts.  It should be verifiable some other way, though.

**Comment by jakirkham** [comment]
I think the link no longer points to the right part of code.
