### ISSUE TITLE
anaconda_upload option automatically uses the --force switch

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda-build#2041]
conda-build 2.1.0 introduced a change where 'anaconda upload' is now forced. https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1605. I don't see any kind of config setting that can alter the behavior. That line was changed in tag 2.1.0.

This seems a bit dangerous since it will blow away the package that's already there. We're normally pretty careful not to accidentally rebuild a package with the same version/build-string, but, sometimes it happens inadvertently. We drive conda build through a higher-level build process which is necessary to compile our internal libraries and handles much of the cross-company dependency management. After the compilation, conda build is driven and environment variables are set based on that outer build system's notion of the version. It's easy to forget to bump the version and accidentally rebuild with an existing version/build-string. 

The old behavior seems better: the upload fails because there's an existing instance of the package with the same version/build-string, but, there are instructions for how to upload manually if you really intended to do that.

Can we add a new config option to disable the --force flag on anaconda upload?

**Comment by msarahan** [comment]
Yes, I'm happy to add this flag.  I need to keep the behavior the same, at least for the 2.1.x series, but I'm quite happy to give you an easy way to change it.

**Comment by msarahan** [comment]
fixed by #2047, will be in 2.1.16 - out Monday at the latest.
