### ISSUE TITLE
[WinError 5] Access is denied:

### ISSUE THREAD

**Issue by kets999** [conda/conda-build#2043]
C:\Python34>easy_install -U setuptools
Searching for setuptools
Reading https://pypi.python.org/simple/setuptools/
Download error on https://pypi.python.org/simple/setuptools/: [Errno 11004] geta
ddrinfo failed -- Some packages may not be found!
Couldn't retrieve index page for 'setuptools'
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 11004] getaddrinfo fai
led -- Some packages may not be found!
Best match: setuptools 35.0.2
Processing setuptools-35.0.2-py3.4.egg
setuptools 35.0.2 is already the active version in easy-install.pth
Installing easy_install-script.py script to C:\Python34\Scripts
Installing easy_install.exe script to C:\Python34\Scripts
error: [WinError 5] Access is denied: 'C:\\Python34\\Scripts\\easy_install.exe'

I am running command prompt as administrator still, I am getting this error. Tried all the solution available on net, nothing works

**Comment by mingwandroid** [comment]
You do not appear to be using the `Anaconda Distribution` here. This repository is for the tool that is used to build packages for that. Closing as out of scope.
