### ISSUE TITLE
Conda build fails but manual build works

### ISSUE THREAD

**Issue by utsekaj42** [conda/conda-build#2053]
[conda_build_log_.txt](https://github.com/conda/conda-build/files/1025852/conda_build_log_.txt)
Is this a good place to ask questions as I'm not sure if this is a user issue or not? If not please suggest a more appropriate venue.

I am trying to build the recipe here [utsekaj42/odes-recipe](https://github.com/utsekaj42/odes-recipe) on macOS (I am able to do so successfully on Fedora 24).
Note that you need "sunidals" from the "conda-forge" channel.

`conda build -c conda-forge odes-recipe` 

Fails with a linker error. See attached log.

Assuming you have downloaded or cloned the repo [utsekaj42/odes](https://github.com/utsekaj42/odes) as `odes/` in the working directory.

Manually creating the build environment works. Can anyone explain what's missing?

```{.bash}
conda create -c conda-forge  -n odes_env python=3 gcc cython numpy scipy sundials nose
source activate odes_env
cd odes
python setup.py install
cd ..
python "import scikits.odes as od; od.test()"
```
works fine for me.

**Comment by msarahan** [comment]
Sorry, this one looks like a not-fun Mac issue.

This line:

  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64

seems to indicate that you're targeting 10.6 somehow.  That used to be the default that conda-build targeted.  Our current target OSX version is 10.7.  https://github.com/conda/conda-build/blob/84ccb006a04defd3e966070e531703b392e83572/conda_build/environ.py#L486

What version of conda-build have you used?  Maybe try updating?  2.1.15 is the current version.

**Comment by utsekaj42** [comment]
Is there a way to manually override the OSX version? I have updated to 2.1.15 from 2.0.6, but the same linker error is occurring.  I am running macOS 10.12.5 if that is relevant, though the build should be using gcc and gfortran from the conda environment.

**Comment by msarahan** [comment]
If you set the MACOSX_DEPLOYMENT_TARGET environment variable, conda-build will respect it.  For example:

```
export MACOSX_DEPLOYMENT_TARGET=10.12
conda build your_recipe
```

You may also want to install the earlier SDK, as this will make your packages more compatible with other people: https://github.com/phracker/MacOSX-SDKs

**Comment by utsekaj42** [comment]
I noticed that even using this export the build is still generating/linking against 10.9 libraries. Do you know how to install these SDKs if I only have the XCODE command line tools installed? I have put them in the same folder as the current library, but I'm not sure if that was the correct way.

**Comment by msarahan** [comment]
Sorry, I'm not ignoring this, I just don't really know what I'm doing here, and don't have the time to search for information on this.  @jakirkham is very good with MacOS and might know.  @mingwandroid might know.  Otherwise, I'll try to come back to this soon.

**Comment by jakirkham** [comment]
Looks like you are specifying the `gcc` compiler package be used in `build`, but not requiring `libgcc` in `run`. It might try to pick up the system version of `libgcc`, but that would be way to old to be compatible with that compiler (i.e. 4.2 vs 4.8). Also the Apple provided `gcc` has a slightly different structure than vanilla `gcc`. This is probably the cause of the error messages you are seeing. Would recommend either dropping `gcc` and using system compilers on Mac and Linux or adding `libgcc` to `run`.

**Comment by jakirkham** [comment]
Also might add `-undefined dynamic_lookup` to your `LDFLAGS`. This has been a real gem when compiling Fortran linked Python code.

**Comment by utsekaj42** [comment]
OK, it seems that using `LDFLAGS=$LDFLAGS" -undefined dynamic_lookup"` did the trick. Do you think it would still be advisable to include `libgcc` as a runtime dependency?

The choice of using `gcc`was because the native Apple `gcc` didn't like the inline functions the way the author has them. Further even changing those I started to get some Fortran errors, thus I thought it would be easier to use the `conda` supplied `gcc`.
