### ISSUE TITLE
Unexpected error leads user on wild goose chase

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-build#2059]
Some developers I work with spent quite a bit of time trying to understand this error, from conda-build running on Jenkins 2.0:
```
OSError: Can't merge /prod/msp/build/slave1/workspace/ABCDEFG/ABCDEFGHIJKLM/testpkg/testpkg/miniconda/src into /prod/msp/build/slave1/workspace/ABCDEFG/ABCDEFGHIJKLM/testpkg/testpkg/miniconda/conda-bld/testpkg_1495824479950/work: file exists: /prod/msp/build/slave1/workspace/ABCDEFG/ABCDEFGHIJKLM/testpkg/testpkg/miniconda/conda-bld/testpkg_1495824479950/work/MAINTAINERS
```
This error is of course generated by `merge_tree`. But it was curious, because there are no duplicates here. It's building a single package. There's no reason this message should have happened. `copy_tree` shouldn't have even dumped off to `merge_tree`.

Running in debug mode I was able to find that this appeared twice:
```
Copying /prod/msp/build/slave1/workspace/ABCDEFG/ABCDEFGHIJKLM/testpkg/testpkg/miniconda/src to /prod/msp/build/slave1/workspace/ABCDEFG/ABCDEFGHIJKLM/testpkg/testpkg/miniconda/conda-bld/testpkg_1495824479950/work
```
The first instance appears right _before_ `BUILD START`, and then the second time several clicks down in the logs. So that certainly explains it. The first copy succeeds, the second copy fails, but there shouldn't be a second copy.

Digging further in the debug logs, I discovered that the _creation of the build environment_ failed for unexpected reasons---specifically, a `ConnectTimeoutError` when fetching channel information. (It turns out we needed to set a proxy before starting the package build.) For some reason, this error was being intercepted, and instead of sharing it with the user, conda-build for some reason tried to _repeat_ the build. And because the source code copy had already been done, the second attempt was doomed to fail in `copy_tree`.

So the _true_ error was a failure in environment creation, but because this error was caught and buried in favor of a simple retry, we were given a completely different error that proved to be a red herring.

**Comment by msarahan** [comment]
Sorry, I'll see if I can clean up my exception handling.  Generally what that horrible exception handling is resultant from is the race condition bug that causes random failures when multiple builds are done in parallel.

**Comment by mcg1969** [comment]
Thanks Michael!

**Comment by mcg1969** [comment]
Obviously, we can't expect conda build to succeed in this circumstance. It's just a matter of find a way to make sure that the true cause of failure is exposed. Thanks again.

**Comment by msarahan** [comment]
@kalefranz you only have CondaError and PaddingError in exports.  Can you please give me more options so that I can narrow my exception handling scope?

**Comment by kalefranz** [comment]
Absolutely.

**Comment by kalefranz** [comment]
I'll go through the list in `conda/exceptions.py` and pull out the ones that look most relevant for you.  But if there are any in particular you need, also please just let me know.

**Comment by msarahan** [comment]
Punting to 3.0.1 due to https://github.com/conda/conda/issues/5515

**Comment by msarahan** [comment]
This is long cleaned up.  Closing.
