### ISSUE TITLE
Installing a tar bundle

### ISSUE THREAD

**Issue by martinfiers** [conda/conda-build#2061]
Hello,

Upon recommendations here https://github.com/conda/conda/issues/5211, I repeat this issue in the correct repository.

Basically, I want to build a bundle with multiple conda packages. According to 
https://docs.continuum.io/anaconda/faq#how-do-i-install-packages-on-a-non-networked-machine

This should be possible. Nevertheless, the ability to do this has been removed https://github.com/conda/conda/commit/d61e73a86003a036a3fbba24ad3f246fa5c532f7

Alternatives that I consider are building a new 'bundle' package that just installs the individual packages, i.e., it has a build script that looks like this:

    conda install package1
    conda install package2

But that doesn't seem the right approach. In short, I am looking for the best way to bundle several conda packages. The use case is that I want to install a home-made package with its dependencies in 1 shot (but I don't want to trigger automatic dependency calculation, i.e., exactly the behavior that was described in https://docs.continuum.io/anaconda/faq#how-do-i-install-packages-on-a-non-networked-machine).

**Comment by msarahan** [comment]
I recommend two things:

1. Make a "metapackage" with all of the things that you want to bundle together.  Just list run requirements with all the things you want to include.
2. Make a local "channel" and add this to your condarc.  You can make a channel on your local disk by making a folder structure like this:

```
base
- noarch   # (must be here, even if you don't use it)
- your_native_arch (like win-64 or linux-64)
```

Put your packages into the native arch folder or noarch folder, as appropriate.  Now, run ```conda index``` on both the noarch folder and the native arch folder.

finally, add the path to your condarc:
```conda config --add channels file:///home/you/channel```
Omit the noarch and native arch from the channel addition - it gets added for you.

This will do dependency calculation, but it will look on your local channel first.  If you disable dependency calculation, then installing the metapackage won't install any of its dependencies, and this will be pointless.
