### ISSUE TITLE
Updating shared-libraries in directories deeper than <prefix>/lib

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#2067]
_From @teoliphant on December 18, 2013 0:24_

For many system libraries, there might be shared libraries built in directories different than /lib.   conda build should be able to change the RPATH or linking properties of files that depend on libraries in these deep directories.

_Copied from original issue: conda/conda#433_

**Comment by kalefranz** [comment]
_From @asmeurer on January 29, 2014 23:19_

Is there an example package that might use this to test against?

**Comment by msarahan** [comment]
@mingwandroid I believe you fixed this quite a while ago - back when we were messing with JDK packages?  Can you confirm?

**Comment by mingwandroid** [comment]
Way before that even, but yes RPATH replacement is not completely dynamic.
