### ISSUE TITLE
conda convert ignores dependencies

### ISSUE THREAD

**Issue by plieningerweb** [conda/conda-build#2085]
```
conda convert pakcage-xyz-linux-bla.tar.bz -d 'numpy >=1.8'
```
The dependency 'numpy >=1.8' will not be in the converted package.

How it should be?
The dependency should be included in the new package. Even better, the parsed meta.yaml with conditional depenencies should be used for the converted package.

Example:
meta.yaml
```
requirements:
    build:
        - python
    run:
        - python
        - pywin32 # [win]
```

when first built on linux and then converted to win64 using `conda convert --platform win-64 -o /opt/miniconda3/conda-bld/ /opt/miniconda3/conda-bld/linux-64/package_xy-0.1.31-py34_0.tar.bz2 -d 'pywin32'` the converted package will not have the dependency of pywin32.
The "quick hack" with -d failed as well as mentioned above.

Fix for convert:
See https://github.com/conda/conda-build/blob/master/conda_build/convert.py#L235
There should be something like:
```
# see https://github.com/conda/conda-build/blob/master/conda_build/convert.py#L412
        if dependencies:
            info['depends'].extend(dependencies)
```

**Comment by msarahan** [comment]
@mandeep since you are digging into conda-convert already, please take a look at this.
