### ISSUE TITLE
{{PYTHON}} rendering stopped to work in conda-build 2

### ISSUE THREAD

**Issue by anton-malakhov** [conda/conda-build#2086]
I have recipes which work with CB-1, they contain:
```
requirements:
    build:
      - python
build:
    script: {{PYTHON}} setup.py install
```
After update to CB-2, it says the following:
```
$ conda build -q --source --output --python 3.5 smp-recipe
Error: Failed to render jinja template in /projects/pythoni/smp-recipe/meta.yaml:
'PYTHON' is undefined
$ conda list
# packages in environment at /localdisk/work/miniconda3-cb2:
#
asn1crypto                0.22.0                   py36_0
beautifulsoup4            4.6.0                    py36_0
cffi                      1.10.0                   py36_0
chardet                   3.0.3                    py36_0
conda                     4.3.16                   py36_0
conda-build               2.1.15                   py36_0
conda-env                 2.6.0                         0
conda-verify              2.0.0                    py36_0
cryptography              1.8.1                    py36_0
filelock                  2.0.7                    py36_0
idna                      2.5                      py36_0
jinja2                    2.9.6                    py36_0
libffi                    3.2.1                         1
markupsafe                0.23                     py36_2
openssl                   1.0.2l                        0
packaging                 16.8                     py36_0
patchelf                  0.9                           0
pip                       9.0.1                    py36_1
pkginfo                   1.4.1                    py36_0
pyasn1                    0.2.3                    py36_0
pycosat                   0.6.2                    py36_0
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_6
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
python                    3.6.1                         2
pyyaml                    3.12                     py36_0
readline                  6.2                           2
requests                  2.14.2                   py36_0
ruamel_yaml               0.11.14                  py36_1
setuptools                27.2.0                   py36_0
six                       1.10.0                   py36_0
sqlite                    3.13.0                        0
tk                        8.5.18                        0
wheel                     0.29.0                   py36_0
xz                        5.2.2                         1
yaml                      0.1.6                         0
zlib                      1.2.8                         3
```
would replacing with just `python` guarantee the same effect?

**Comment by msarahan** [comment]
in short, yes, if you just replace {{PYTHON}} with python (no braces) it will work, because the python executable on PATH should always be the right one.

Why are you using --source and --output together?  Those are distinct operations, and it's strange to see them together.  --output will download the source code if it needs to fully render the recipe.

Sorry for the breakage, anyway.  I think this happened because the PYTHON variable used to be much more hard-coded, and now it is more derived from other things.  PYTHON should certainly work in build.sh and bld.bat, and it really should work in meta.yaml, too, but for the latter you're depending much more on some tricky iterative parsing.

**Comment by anton-malakhov** [comment]
Thanks, Mike! I'll use the workaround for now, so the issue might not be critical for me. However, if it is not indicated in documentation, please fix either documentation or implementation.

@tomashek might answer your question regarding the command line options

**Comment by Bezier89** [comment]
We've encountered this issue as well. Just had to roll back an update because we have hundreds of recipes that use {{ PYTHON }} and changing them all would be a huge hassle. Unfortunately this issue is preventing us from upgrading to conda-build 3.*

**Comment by dan-at-teza** [comment]
Was there any resolution to this issue? I am running into issues with {{ PYTHON }} in my conda build scripts, and if I try to replace them with 'python' as suggested earlier, I run into a different error:

conda_build.exceptions.CondaBuildException: Empty package; python present in build and host deps.  You probably picked up the build environment's python  executable.  You need to alter your recipe to  use the PYTHON env var in your recipe to run that executable.

This is with conda-build 3.17.8, conda 4.6.1, and python 2.7.15.

**Comment by dan-at-teza** [comment]
Copy meta.yaml from https://github.com/conda-forge/kazoo-feedstock/blob/master/recipe/meta.yaml:

(base) (root)grixis:kazoo dadkins$ conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for kazoo
INFO:conda_build.metadata:Attempting to finalize metadata for kazoo
Error: Failed to render jinja template in /Users/dadkins/teza/tcm/statarb/python/recipes/kazoo/meta.yaml:
'PYTHON' is undefined

(base) (root)grixis:kazoo dadkins$ sed -i.bak 's/{{ PYTHON }}/python/' meta.yaml

(base) (root)grixis:kazoo dadkins$ conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for kazoo
INFO:conda_build.metadata:Attempting to finalize metadata for kazoo
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: [u'kazoo-2.6.1-py_0.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/dadkins/teza-conda/conda-bld/kazoo_1548956881747/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.12.5-0            
    certifi:         2018.11.29-py37_0      
    libcxx:          4.0.1-hcfea43d_1       
    libcxxabi:       4.0.1-hcfea43d_1       
    libedit:         3.1.20181209-hb402a30_0
    libffi:          3.2.1-h475c297_4       
    ncurses:         6.1-h0a44026_1         
    openssl:         1.1.1a-h1de35cc_0      
    pip:             18.1-py37_0            
    python:          3.7.2-haf84260_0       
    readline:        7.0-h1de35cc_5         
    setuptools:      40.6.3-py37_0          
    sqlite:          3.26.0-ha441bb4_0      
    tk:              8.6.8-ha441bb4_0       
    wheel:           0.32.3-py37_0          
    xz:              5.2.4-h1de35cc_4       
    zlib:            1.2.11-h1de35cc_3      

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/dadkins/teza-conda/conda-bld/kazoo_1548956881747/_build_env


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.12.5-0            
    certifi:         2018.11.29-py27_0      
    libcxx:          4.0.1-hcfea43d_1       
    libcxxabi:       4.0.1-hcfea43d_1       
    libedit:         3.1.20181209-hb402a30_0
    libffi:          3.2.1-h475c297_4       
    ncurses:         6.1-h0a44026_1         
    openssl:         1.1.1a-h1de35cc_0      
    pip:             18.1-py27_0            
    python:          2.7.15-h8f8e585_6      
    readline:        7.0-h1de35cc_5         
    setuptools:      40.6.3-py27_0          
    sqlite:          3.26.0-ha441bb4_0      
    tk:              8.6.8-ha441bb4_0       
    wheel:           0.32.3-py27_0          
    zlib:            1.2.11-h1de35cc_3      

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
Source cache directory is: /Users/dadkins/teza-conda/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /Users/dadkins/teza-conda/conda-bld/src_cache
Found source in cache: kazoo-2.6.1_4a73c2c62a.tar.gz
INFO:conda_build.source:Found source in cache: kazoo-2.6.1_4a73c2c62a.tar.gz
Extracting download
source tree in: /Users/dadkins/teza-conda/conda-bld/kazoo_1548956881747/work
export SRC_DIR=/Users/dadkins/teza-conda/conda-bld/kazoo_1548956881747/work
export PREFIX=/Users/dadkins/teza-conda/conda-bld/kazoo_1548956881747/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export BUILD_PREFIX=/Users/dadkins/teza-conda/conda-bld/kazoo_1548956881747/_build_env
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-lhjDQn
Created temporary directory: /private/tmp/pip-req-tracker-MTngWk
Created requirements tracker '/private/tmp/pip-req-tracker-MTngWk'
Created temporary directory: /private/tmp/pip-install-ExQMc1
Processing $SRC_DIR
  Created temporary directory: /private/tmp/pip-req-build-fR_z6e
  Added file://$SRC_DIR to build tracker '/private/tmp/pip-req-tracker-MTngWk'
  Running setup.py (path:/private/tmp/pip-req-build-fR_z6e/setup.py) egg_info for package from file://$SRC_DIR
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/kazoo.egg-info
    writing requirements to pip-egg-info/kazoo.egg-info/requires.txt
    writing pip-egg-info/kazoo.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/kazoo.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/kazoo.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/kazoo.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/kazoo.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'Makefile'
    warning: no previously-included files found matching 'run_failure.py'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*pyo' found anywhere in distribution
    writing manifest file 'pip-egg-info/kazoo.egg-info/SOURCES.txt'
  Source in /private/tmp/pip-req-build-fR_z6e has version 2.6.1, which satisfies requirement kazoo==2.6.1 from file://$SRC_DIR
  Removed kazoo==2.6.1 from file://$SRC_DIR from build tracker '/private/tmp/pip-req-tracker-MTngWk'
Installing collected packages: kazoo
  Created temporary directory: /private/tmp/pip-record-aBHwCh
  Running setup.py install for kazoo: started
    Running command $BUILD_PREFIX/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-fR_z6e/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-aBHwCh/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/kazoo
    copying kazoo/interfaces.py -> build/lib/kazoo
    copying kazoo/version.py -> build/lib/kazoo
    copying kazoo/client.py -> build/lib/kazoo
    copying kazoo/security.py -> build/lib/kazoo
    copying kazoo/__init__.py -> build/lib/kazoo
    copying kazoo/hosts.py -> build/lib/kazoo
    copying kazoo/python2atexit.py -> build/lib/kazoo
    copying kazoo/retry.py -> build/lib/kazoo
    copying kazoo/exceptions.py -> build/lib/kazoo
    copying kazoo/loggingsupport.py -> build/lib/kazoo
    creating build/lib/kazoo/recipe
    copying kazoo/recipe/queue.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/election.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/partitioner.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/watchers.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/barrier.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/cache.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/__init__.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/lock.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/lease.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/counter.py -> build/lib/kazoo/recipe
    copying kazoo/recipe/party.py -> build/lib/kazoo/recipe
    creating build/lib/kazoo/tests
    copying kazoo/tests/test_retry.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_utils.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_security.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_watchers.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_eventlet_handler.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_lease.py -> build/lib/kazoo/tests
    copying kazoo/tests/util.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_connection.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_election.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_exceptions.py -> build/lib/kazoo/tests
    copying kazoo/tests/__init__.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_partitioner.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_barrier.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_party.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_queue.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_build.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_lock.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_gevent_handler.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_paths.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_counter.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_client.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_hosts.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_threading_handler.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_cache.py -> build/lib/kazoo/tests
    copying kazoo/tests/test_interrupt.py -> build/lib/kazoo/tests
    creating build/lib/kazoo/protocol
    copying kazoo/protocol/paths.py -> build/lib/kazoo/protocol
    copying kazoo/protocol/__init__.py -> build/lib/kazoo/protocol
    copying kazoo/protocol/connection.py -> build/lib/kazoo/protocol
    copying kazoo/protocol/states.py -> build/lib/kazoo/protocol
    copying kazoo/protocol/serialization.py -> build/lib/kazoo/protocol
    creating build/lib/kazoo/testing
    copying kazoo/testing/harness.py -> build/lib/kazoo/testing
    copying kazoo/testing/__init__.py -> build/lib/kazoo/testing
    copying kazoo/testing/common.py -> build/lib/kazoo/testing
    creating build/lib/kazoo/handlers
    copying kazoo/handlers/gevent.py -> build/lib/kazoo/handlers
    copying kazoo/handlers/__init__.py -> build/lib/kazoo/handlers
    copying kazoo/handlers/threading.py -> build/lib/kazoo/handlers
    copying kazoo/handlers/utils.py -> build/lib/kazoo/handlers
    copying kazoo/handlers/eventlet.py -> build/lib/kazoo/handlers
    running egg_info
    writing requirements to kazoo.egg-info/requires.txt
    writing kazoo.egg-info/PKG-INFO
    writing top-level names to kazoo.egg-info/top_level.txt
    writing dependency_links to kazoo.egg-info/dependency_links.txt
    reading manifest file 'kazoo.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'Makefile'
    warning: no previously-included files found matching 'run_failure.py'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*pyo' found anywhere in distribution
    writing manifest file 'kazoo.egg-info/SOURCES.txt'
    warning: build_py: byte-compiling is disabled, skipping.

    running install_lib
    creating $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    copying build/lib/kazoo/interfaces.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    copying build/lib/kazoo/version.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    creating $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/queue.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/election.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/partitioner.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/watchers.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/barrier.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/cache.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/__init__.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/lock.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/lease.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/counter.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/recipe/party.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/recipe
    copying build/lib/kazoo/client.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    copying build/lib/kazoo/security.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    creating $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_retry.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_utils.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_security.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_watchers.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_eventlet_handler.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_lease.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/util.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_connection.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_election.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_exceptions.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/__init__.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_partitioner.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_barrier.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_party.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_queue.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_build.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_lock.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_gevent_handler.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_paths.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_counter.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_client.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_hosts.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_threading_handler.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_cache.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/tests/test_interrupt.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/tests
    copying build/lib/kazoo/__init__.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    copying build/lib/kazoo/hosts.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    creating $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/protocol
    copying build/lib/kazoo/protocol/paths.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/protocol
    copying build/lib/kazoo/protocol/__init__.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/protocol
    copying build/lib/kazoo/protocol/connection.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/protocol
    copying build/lib/kazoo/protocol/states.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/protocol
    copying build/lib/kazoo/protocol/serialization.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/protocol
    copying build/lib/kazoo/python2atexit.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    copying build/lib/kazoo/retry.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    creating $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/testing
    copying build/lib/kazoo/testing/harness.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/testing
    copying build/lib/kazoo/testing/__init__.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/testing
    copying build/lib/kazoo/testing/common.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/testing
    copying build/lib/kazoo/exceptions.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    copying build/lib/kazoo/loggingsupport.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo
    creating $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/handlers
    copying build/lib/kazoo/handlers/gevent.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/handlers
    copying build/lib/kazoo/handlers/__init__.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/handlers
    copying build/lib/kazoo/handlers/threading.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/handlers
    copying build/lib/kazoo/handlers/utils.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/handlers
    copying build/lib/kazoo/handlers/eventlet.py -> $BUILD_PREFIX/lib/python2.7/site-packages/kazoo/handlers
    warning: install_lib: byte-compiling is disabled, skipping.

    running install_egg_info
    Copying kazoo.egg-info to $BUILD_PREFIX/lib/python2.7/site-packages/kazoo-2.6.1-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/private/tmp/pip-record-aBHwCh/install-record.txt'
    Running setup.py install for kazoo: finished with status 'done'
  Removing source in /private/tmp/pip-req-build-fR_z6e
Successfully installed kazoo-2.6.1
Cleaning up...
Removed build tracker '/private/tmp/pip-req-tracker-MTngWk'

Resource usage statistics from building kazoo:
   Process count: 3
   CPU time: Sys=0:00:00.3, User=0:00:00.5
   Memory: 51.0M
   Disk usage: 1.8K
   Time elapsed: 0:00:04.1

Packaging kazoo
INFO:conda_build.build:Packaging kazoo
Packaging kazoo-2.6.1-py_0
INFO:conda_build.build:Packaging kazoo-2.6.1-py_0
No files or script found for output kazoo
WARNING:conda_build.build:No files or script found for output kazoo
Traceback (most recent call last):
  File "/Users/dadkins/teza-conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/dadkins/teza-conda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/Users/dadkins/teza-conda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/dadkins/teza-conda/lib/python2.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/dadkins/teza-conda/lib/python2.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/Users/dadkins/teza-conda/lib/python2.7/site-packages/conda_build/build.py", line 1628, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/dadkins/teza-conda/lib/python2.7/site-packages/conda_build/build.py", line 935, in bundle_conda
    "run that executable.".format(dep, env_var_name))
conda_build.exceptions.CondaBuildException: Empty package; python present in build and host deps.  You probably picked up the build environment's python  executable.  You need to alter your recipe to  use the PYTHON env var in your recipe to run that executable.

**Comment by msarahan** [comment]
That recipe is not sane.  Listing build and host both like that is wrong.

https://github.com/conda-forge/kazoo-feedstock/blob/master/recipe/meta.yaml#L20-L25

should be:

```
host:
  - python
  - pip
  - setuptools
```

i.e. no build section at all.

Conda-build messaging could be better here, but it's reasonably clear: you effectively have python in both build and host, and the wrong one is getting used to install your bits.

**Comment by msarahan** [comment]
https://conda.io/projects/conda-build/en/latest/source/define-metadata.html#requirements-section
