### ISSUE TITLE
Missing development workflow with CB-2: `. activate _test`

### ISSUE THREAD

**Issue by anton-malakhov** [conda/conda-build#2092]
I understand the reasoning for the changes in CB-2 which eliminate races for multiple builds on the same miniconda instance and so on.. Though, it's not clear how to replace the following workflow which was possible with CB-1:
```
$ conda build -q --python 3.5 my_module-recipe
...
TEST START: tbb-2017.0.6-py35_intel_12
Error: some failure
$ . activate _test
$ python -c "import my_module; ..." # debug build which succeeded but test failed
```
Thank you for the advice

**Comment by msarahan** [comment]
This is totally possible, you just need a more specific path.  All of the build folders from any failed build are still there.  Instead of ``. activate _test`` it will look something more like

```
. activate tbb_(timestamp)/_t_env_placehold_placehold...(out to 255 chars)
```

**Comment by anton-malakhov** [comment]
I see, it looks like the test environment `_t_env...` hasn't been created because of unsatisfied dependencies while activating `_b_env...` has no the package

**Comment by msarahan** [comment]
Ah, so you didn't even make it to the test phase?  That would preclude the test env creation, yes.

Technically, the dependencies are unsatisfiable when creating the environment, not when activating it (activating it can only be done when it is created)

**Comment by anton-malakhov** [comment]
yep, something wrong with our tester package, so the log is (full disclosure :) )
```
TEST START: tbb-2017.0.6-py35_intel_13
WARNING conda_build.build:test(1305): Not removing work directory after build.  Your package may depend on files in the work directory that are not included with your package
Can't build /projects/pythoni/tbb-recipe due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - intel_tester -> python 2.7*
  - python 3.5.*
Use "conda info <package>" to see the dependencies for each package.

Typically if a conflict is with the Python or R
packages, the other package needs to be rebuilt
(e.g., a conflict with 'python 3.5*' and 'x' means
'x' isn't build for Python 3.5 and needs to be rebuilt.
```
I assume it should work when it will be able to complete test environment creation, correct?

**Comment by msarahan** [comment]
Yes, if test env creation works but tests fail, then the folder I described will be there, and you can activate it and work with it to your heart's content.
