### ISSUE TITLE
conda build 3 always rebuilds the environment in post build phase

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#2110]
conda build 3 rebuilds the build environment during the post build phase even when the recipe only has a single output.  A rebuild is not needed in these cases.

**Comment by msarahan** [comment]
A little bit of wishful thinking - this might be a rather advanced task for the sprints, but I'd like to get it done.

**Comment by msarahan** [comment]
fixed in recent CB3 releases.
