### ISSUE TITLE
Is there a way to keep test env while building clean

### ISSUE THREAD

**Issue by anton-malakhov** [conda/conda-build#2114]
Another question regarding development flow with conda-build 2
When the package is built and tested successfully, I see the following message:
`INFO:conda_build.config:--dirty flag not specified.  Removing build folder after successful build/test.`
Thus, I'm unable to source the test environment after such a build.

But when I refer to the `--dirty`, it is described as
```
              Do  not remove work directory or _build environment, to speed up
              debugging. Does not apply patches or download source.
```
The last sentence does not fit my needs. I want to build a clean package for every run and be able to interact with it in-place, without additional environment switching and installation
Any advice?
Thanks!

**Comment by msarahan** [comment]
I think --dirty will do what you need.  Give it a try.  I think that last sentence is inaccurate.  It should not re-apply patches or re-download source, but it does do those things on the first pass.

**Comment by anton-malakhov** [comment]
My concern is the second and following passes.. It sounds like I cannot make this option default for my build scripts because it reuses whatever left before while I need a clean build which keeps the test environment

**Comment by msarahan** [comment]
I see.  You want --dirty, but without the reuse.  I think that's what @mingwandroid originally had with --keep-old-work.  Seems like I need to bring that back.

**Comment by jjhelmus** [comment]
If you run `conda build purge` before the build you should be guaranteed to download and patch the code during the build.  This isn't ideal but should work.

**Comment by anton-malakhov** [comment]
Thanks! Yes, I'll appreciate such a feature

**Comment by anton-malakhov** [comment]
hm.. for some reason `conda build purge` does not work, not removing the directories with the timesptamps. I did just `rm -rf conda-build/*_1*`

**Comment by anton-malakhov** [comment]
this is what I did to `config.py` file to achieve my goals:
```
    def clean(self, remove_folders=False):
        # build folder is the whole burrito containing envs and source folders
        #   It will only exist if we download source, or create a build or test environment
        if remove_folders and not getattr(self, 'dirty'):
            if self.build_id:
                if os.path.isdir(self.build_folder):
                    rm_rf(self.build_folder)
            else:
                for path in [self.work_dir, self.test_dir, self.build_prefix, self.test_prefix]:
                    if os.path.isdir(path):
                        rm_rf(path)
            if os.path.isfile(os.path.join(self.build_folder, 'prefix_files')):
                rm_rf(os.path.join(self.build_folder, 'prefix_files'))
        else:
            print("\nLeaving build/test directories:"
                  "\n  Work:\t", os.path.relpath(self.work_dir),
                  "\n  Test:\t", os.path.relpath(self.test_dir),
                  "\nLeaving build/test environments:"
                  "\n  Test:\tsource activate ", os.path.relpath(self.test_prefix),
                  "\n  Build:\tsource activate ",os.path.relpath(self.build_prefix),
                  "\n\n")

        for lock in get_conda_operation_locks(self):
            rm_rf(lock.lock_file)
```

**Comment by msarahan** [comment]
Great.  Want to submit a PR?  I am going to release 2.1.16 very soon.  You can get this in.  Make sure to base your work on the 2.1.x. branch.

**Comment by anton-malakhov** [comment]
@msarahan This has rather hard-coded.. which I guess is not what you want, please note `remove_folders=False`

**Comment by AndresGuzman-Ballen** [comment]
Hi @msarahan ! How soon is "very soon"?

**Comment by msarahan** [comment]
waiting on one other PR - #2116 then it'll be done.

**Comment by AndresGuzman-Ballen** [comment]
Oh so you're going to release by the end of today? Or sometime next week? I would create a PR right now but I have to get going "very soon" ;)

**Comment by msarahan** [comment]
let's say by first thing monday morning?  If you tell me that you're working on it and can have it done by then, I will wait.

**Comment by AndresGuzman-Ballen** [comment]
I might have a chance to work on it this weekend; I'll keep you in the loop either way. I guess all I have to do is add a --remove-folders flag on top of what Anton pasted above and then create a PR?

**Comment by AndresGuzman-Ballen** [comment]
Oops, spoke with Anton. The default would still be True, but you'd have to specify a --no-remove-folders flag.

**Comment by msarahan** [comment]
yeah, that's pretty much it.  You might want to restore --keep-old-work since it is already there.

**Comment by AndresGuzman-Ballen** [comment]
Alright, I created a PR: https://github.com/conda/conda-build/pull/2119

**Comment by msarahan** [comment]
#2119 fixed --keep-work-dir.  Closing this issue.
