### ISSUE TITLE
Install-time dependence genertion

### ISSUE THREAD

**Issue by anton-malakhov** [conda/conda-build#2125]
There is TBB module for Python in Intel Distro, it has the native part (the TBB run-time) and the Python part. We might want to decouple it into two packages accordingly and make interdependent, so whenever the `tbb` package installed, the `tbb4py` is installed as well. But somebody might actually say that they don't want the Python part if there is no Python in their environment. On the other hand, having Python counterparts is pretty important for us when these libraries are being installed along with the Python. Another example is OpenMP runtime which ideally needs some fixes/integration on the Python side when installed next to Python. Do you have some existing mechanism which would do that for me? Otherwise, please consider this as a feature request.

I could think of some triggers in meta.yaml, e.g.:
```
   - tbb4py # [python]
```
Or/and some script executed at install time which outputs additional dependencies as necessary:
```
requirements:
  install-time-script: python install.py --list-requirements
```

Another usage for this thing is to optimize size of packages to install for particular platforms. E.g. install-time dependency can decide whether to install `SSE4.2`, `AVX2`, or `AVX-512` runtime for a package.

Triggers might be preferable in order to support scenarios when tbb/openmp are installed ahead of python, and when the python is added to the environment, the triggers would schedule Python modules to be installed

**Comment by msarahan** [comment]
Issue moved to [conda/conda #5608](https://github.com/conda/conda/issues/5608) via [**ZenHub**](https://www.zenhub.com/)
