### ISSUE TITLE
`conda build purge` does not work

### ISSUE THREAD

**Issue by anton-malakhov** [conda/conda-build#2126]
As I reported earlier, it does not work in my setup with `conda-build/` being a symlink. Apparently, it does not work for @oleksandr-pavlyk either, who is not using a symlink. Here is the log:

```
[17:36:13 fxsatlin01 pythoni]$ conda update conda-build
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /nfs/an/proj/scripting_tools/amalakho/home/local/miniconda3:
#
conda-build               2.1.15                   py36_0
[17:36:39 fxsatlin01 pythoni]$ du -hs conda-build/
2.6G    conda-build/
[17:36:45 fxsatlin01 pythoni]$ conda build purge
[17:36:54 fxsatlin01 pythoni]$ du -hs conda-build/
2.6G    conda-build/
[17:36:56 fxsatlin01 pythoni]$ conda build purge --build-only
[17:37:06 fxsatlin01 pythoni]$ du -hs conda-build/
2.6G    conda-build/
```

**Comment by msarahan** [comment]
sorry, please clarify what "conda-build" being a symlink means.  There are tests for this at https://github.com/conda/conda-build/blob/master/tests/test_cli.py#L430-L444 - if you can tell me what those tests don't cover, or better yet, put up a PR to improve the tests, I'd be happy to take a look.

**Comment by anton-malakhov** [comment]
The description comment is not met `purge clears out build folders - things like some_pkg_12048309850135`. For example:
```
[18:43:01 fxsatlin01 pythoni]$ conda build purge
[18:43:08 fxsatlin01 pythoni]$ ls conda-build/
git_cache                 setuptools_1498259433020  tbb_1498252810052  tbb_1498258488650
hg_cache                  smp_1498516195067         tbb_1498253240570  tbb_1498258561601
linux-64                  smp_1498516198425         tbb_1498253485231  tbb_1498258604319
noarch                    smp_1498516284753         tbb_1498255005464  tbb_1498258654608
repodata.json             smp_1498516287133         tbb_1498257355935  tbb_1498259491177
repodata.json.bz2         src_cache                 tbb_1498258171034  tbb_1498261476392
setuptools_1498258616805  svn_cache                 tbb_1498258319285  tbb_1498512582959
setuptools_1498258783595  tbb_1498252279168         tbb_1498258468205  work
```

**Comment by msarahan** [comment]
oh, I see.  I think your complaint is that it does not recognize non-default folders for these things to be in.  It probably doesn't understand the root dir configuration from https://conda.io/docs/config.html#specify-conda-build-output-root-directory

Is that what you're using to get conda-build to put its folders into your conda-build folder?

**Comment by anton-malakhov** [comment]
My bad.. thank you for pointing it out! I thought it just looks into current working directory. Specifying the build path via the env var works: 
```
[18:55:19 fxsatlin01 pythoni]$ CONDA_BLD_PATH=conda-build conda build purge; ls conda-build/
git_cache  hg_cache  linux-64  noarch  repodata.json  repodata.json.bz2  src_cache  svn_cache  work
```
