### ISSUE TITLE
disable_pip option is removing explicitly specified dependencies

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2128]
This option is meant to disable conda's implicit addition of pip, setuptools, and wheel.  However, it is overly zealous and removes these packages even when they are explicitly specified in the recipe dependencies.  The only packages it removes should be the implicit ones.

cc @mingwandroid

**Comment by gabm** [comment]
we were debugging into this as well some time ago... what is the rational behind adding pip/setuptools/wheel in the first place as implicit dependency? imho thats the cause of a lot of issues due to unexpected behavior...

**Comment by msarahan** [comment]
That's how upstream Python behaves now.  They ship with setuptools, pip, and wheel.  Unfortunately, that means that many packages are missing an explicit dependency on setuptools.

**Comment by gabm** [comment]
interesting.. didn't know that.. thanks for clarification

**Comment by msarahan** [comment]
fixed by #2129. closing

**Comment by msarahan** [comment]
Fixed again (due to a change in conda's str representation matchspecs) in #2793
