### ISSUE TITLE
Request: PYTHON_INCLUDE_DIR, PYTHON_LIBRARY environment variables

### ISSUE THREAD

**Issue by djsutherland** [conda/conda-build#2130]
CMake's FindPythonLibs, when used with anaconda, often needs some nudging to find the right one, usually via something like:
```
cmake .. -DPYTHON_INCLUDE_DIR=$py_inc -DPYTHON_LIBRARY=$py_lib
```
I used to use `$PREFIX/include/python$PY_VER` and `$PREFIX/lib/libpython$PY_VER.so`. But on Mac, it's now `libpython$PY_VER.dylib`, and anaconda's python 3.6 now uses `3.6m` in those file names, while `$PY_VER` is still `3.6`.

The include dir [can be found via](https://stackoverflow.com/a/35071359/344821)
```
$($PYTHON -c "from distutils import sysconfig; print(sysconfig.get_python_inc())")
```
but there doesn't seem to be an equivalent there for the library to link. (`get_python_lib()` goes to the `site-packages` dir.) `$PREFIX/lib/libpython$PY_VER*` seems to work, but it'd be nice for `conda-build` to set e.g. `$PYTHON_INCLUDE_DIR` to `distutils.sysconfig.get_python_inc()` and `$PYTHON_LIBRARY` to...something that figures it out appropriately, not sure what the best answer there is.

**Comment by msarahan** [comment]
This would be a great addition, I agree.  If you have time, please submit a PR.  Otherwise, I'll mark this as a potential project for someone to tackle during the SciPy 2017 sprints in a couple of weeks.  Sorry I don't have more time to do this myself right now.

**Comment by dougalsutherland** [comment]
Haven't had a chance to write a patch yet, but for the record here's what I ended up doing in my recipe for Linux/Mac:

```
pyinc=$($PYTHON -c "from distutils import sysconfig; print(sysconfig.get_python_inc())")
if [[ $(uname) == "Darwin" ]]; then
    pylib=$(otool -L $PYTHON | grep 'libpython.*\.dylib' | tr '\t' ' ' | cut -d' ' -f2 | sed "s|@rpath|$PREFIX/lib|")
else
    pylib=$(ldd $PYTHON | grep $PREFIX | grep 'libpython.*\.so' | cut -d' ' -f3)
fi
```

The latter should obviously be done instead with `conda_build.os_utils.ldd.get_linkages`, but I'm not sure how to get at the conda-build python install from a recipe.

**Comment by jschueller** [comment]
imho that works totally fine, a good practice is to detect pythoninterp first in your CMakeLists, and set CMAKE_PREFIX_PATH to ${PREFIX}.

**Comment by dougalsutherland** [comment]
@jschueller For shogun at least (https://github.com/conda-forge/staged-recipes/pull/3237 -- though that's since been split in two recipes so that the linked one no longer uses Python, oops), I found that CMAKE_PREFIX_PATH wasn't enough for it to find the right Python interpreter. Dunno if they're doing something weird that makes that happen and it usually Just Works or not.

**Comment by jschueller** [comment]
Try to reenable Python in your recipe then, we'll see how it goes.
I could list a lot more examples where it does work :)

**Comment by dougalsutherland** [comment]
Huh, it seems to be working for me now with just CMAKE_PREFIX_PATH. Not sure what the difference was...so maybe this feature is less important.

**Comment by dougalsutherland** [comment]
Never mind, here's a build where it breaks!

https://travis-ci.org/conda-forge/staged-recipes/builds/254889552

Seems to be working on Linux but sometimes not work on Mac.

**Comment by jleni** [comment]
Are there any news with respect to this? 
I wonder why this is not something that gets set when calling source activate... it would simplify life so much. 
I am not much into the details of conda.. Maybe someone can provide some feedback before I spend time on looking at this?

**Comment by mingwandroid** [comment]
If CMake cannot determine all that it needs from the python interpreter that it encounters first on path (or the one in `CMAKE_PREFIX_PATH`) then CMake needs to be fixed.

This way it works for everyone and `conda-build` does not need to carry this build-system-specific code.

**Comment by jleni** [comment]
I have a pip package that uses cmake to compile things. I am not suggesting changing conda-build but that `source activate` should set both PYTHON_INCLUDE_DIRS and PYTHON_LIBRARIES. It should be pointing to the appropriate environment.

But that make sense?

**Comment by mingwandroid** [comment]
`CMake` does not pick up these env vars. The values need to be passed on the command line to it. This is the wrong place to fix this. Either `CMake` or build systems that use `CMake` wrongly is the right place.

**Comment by jjhelmus** [comment]
Some users may set these variables for other uses, for example to pick up local packages that are not tracked by conda.  Setting them during `source activate` would break these use cases.
