### ISSUE TITLE
Use of os.path.exists is problematic on Windows Server Containers

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda-build#2131]
c.f. discussion in jupyter/notebook#2574

On Windows Containers `os.path.exists` doesn't work for host mapped volumes as `os.stat` sees the directory as a broken symlink when it is in fact not broken.

I'm currently trying to deploy `conda-build` on a Windows Container but am having issues due to the checking of `os.path.exists`:
```
C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is DAF8-6E64

 Directory of C:\

11/23/2016  08:45 AM             1,894 License.txt
06/28/2017  10:11 AM    <DIR>          Miniconda3
07/16/2016  11:18 PM    <DIR>          PerfLogs
06/28/2017  09:56 AM    <DIR>          Program Files
06/28/2017  09:56 AM    <DIR>          Program Files (x86)
06/28/2017  09:56 AM    <SYMLINKD>     temp [\\?\ContainerMappedDirectories\7A567A86-B2DF-4DFB-BB34-FF8565A88066]
06/28/2017  09:56 AM    <DIR>          Users
06/28/2017  10:03 AM    <DIR>          Windows
               1 File(s)          1,894 bytes
               7 Dir(s)  20,985,233,408 bytes free

C:\>cd temp

C:\temp>conda build .
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "C:\Miniconda3\lib\site-packages\conda_build\api.py", line 93, in build
    raise ValueError("Path to recipe did not exist: {}".format(recipe))
ValueError: Path to recipe did not exist: C:\temp
```

I think in most cases it would be better if conda used the [EAFP ](https://blogs.msdn.microsoft.com/pythonengineering/2016/06/29/idiomatic-python-eafp-versus-lbyl/) principle. Where that's not appropriate a replacement [`exists`](https://github.com/jupyter/notebook/pull/2574/files#diff-cfd162d49724a067e7279765ec3f7a17R28) utility function should probably be used to allow `conda-build` to also work on Windows Containers

**Comment by dhirschfeld** [comment]
I'm happy to submit a PR but have opened this issue to collect any discussion of the best way forward before jumping in and making wholesale changes!

**Comment by msarahan** [comment]
Sure, I'd be quite happy to accept a PR for this.  Lately I've been doing more ``exists`` checks rather than try/except blocks because it's less code, and it's easier to get higher code coverage.  Those are good to have, but having conda-build work at all on Windows Containers is more important.

**Comment by dhirschfeld** [comment]
I'll close this as I'm pretty sure the Windows Containers bug has been long fixed now...
