### ISSUE TITLE
Simple syntax for library loading test

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2135]
Would be nice to have some simplified syntax for loading libraries as part of the test phase of a recipe build. An example of how this is being done now can be seen in this [commit]( https://github.com/conda-forge/arpack-feedstock/pull/7/commits/1ce86bf4006f4298c30b74b475cec44c9a4bee48 ). Absorbing the boiler plate into `conda-build` would make it easier for users to try and apply this nice testing technique.

cc @dougalsutherland @jschueller

**Comment by jschueller** [comment]
something like:
````
test:
   libs:
    - libarpack
```
would test existence then load using ctypes.

**Comment by jakirkham** [comment]
Was going to add that printing out linkages could be good as well. Though there are other ways to get at that info.

**Comment by mingwandroid** [comment]
conda-build 3 has a [new implementation of ldd and otool](https://github.com/conda/conda-build/blob/master/conda_build/os_utils/pyldd.py) that could (and should IMHO) be used to record and check all library linkages at the end of each package build.

I want to add symbol parsing to it too and record that stuff.

**Comment by jakirkham** [comment]
That's cool. Is this or will this be accessible from the CLI?

**Comment by mingwandroid** [comment]
I don't know, I mean, `conda inspect linkages` runs it at present, but only in a checking fashion (and also for when the native tool fails as it does in cross-compilation scenarios).

Personally, I would have something similar to `conda inspect linkages` happen at the end of every package build and it would run either in an advisory or a detecting problems / errors mode (here problems would include things like unlinked to library dependencies, so dependencies that are *likely* not needed). Another problem would be linking to a system library outside of the CDT sysroot packages (those are not live yet though).

**Comment by jakirkham** [comment]
As noted above, a lot of the functionality is there now. We could certainly improve on it, but going to go ahead and close this out.
