### ISSUE TITLE
TypeError: <function configuration at 0x102a6a378> is not JSON serializable

### ISSUE THREAD

**Issue by astaric** [conda/conda-build#2139]
A [recipe](https://github.com/biolab/orange3/blob/master/conda-recipe/meta.yaml) that builds fine with conda-build=2.1.15 throws an error when built with conda-build=2.1.16.

In the recipe, load_setup_py_data is used to read version information from a [setup.py](https://github.com/biolab/orange3/blob/master/setup.py) script. In the setup.py script, one of the [parameters to the setup function](https://github.com/biolab/orange3/blob/master/setup.py#L248) is a configuration function (used by numpy distutils).

As load_setup_py_data collects all parameters and tries to save them to a json file, it fails with a TypeError: <function configuration at 0x102a6a378> is not JSON serializable

**Comment by msarahan** [comment]
Thanks for reporting. I know what caused this and will fix ASAP.

**Comment by pavoljuhas** [comment]
I am getting a similar error when setup.py defines an extension module:
```
TypeError: Object of type 'Extension' is not JSON serializable
```
This broke in commit f96aa7d8442bf54f33542b30a4f569de3e583202.
