### ISSUE TITLE
test-environment is removed regardless of the "--dirty" options.

### ISSUE THREAD

**Issue by pavoljuhas** [conda/conda-build#2166]
After updating to conda-build 3.0.3 the `conda-build --dirty ...` reports that test environment has been left around, but in reality it is removed:
```sh
$ conda-build --dirty diffpy.utils/conda-recipe
...
Leaving build/test environments:
  Test:	source activate  ../../../../arch/anaconda/conda-bld/diffpy.utils_1499469046695/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:	source activate  ../../../../arch/anaconda/conda-bld/diffpy.utils_1499469046695/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
...
```

The build environment is there, but not the test one.  I tried to add the `--keep-old-work` option, but it had no effect.  The removal of the test-environment has started as of f148fdc1a9fb9c72782d7edbd5c6f242450f10b5.

Can you please fix this?

BTW, the reason I need to keep the test environment is to use it in travis script to export and capture a full version of the built package.  With a full version (i.e., including the built tag) I can reliably install that package in other environment for further testing - even if there is a newer version on my conda channel.
https://github.com/diffpy/diffpy.utils/blob/master/.travis.yml#L72-L77

Is there some other way how to obtain a full version specs for the currently built package?

**Comment by msarahan** [comment]
Yep, that's a bug. Thanks for reporting. We'll fix it. For your use case,
it may be less convoluted to instead capture the output of

conda render --output recipe

Which should output the filenames of all packages produced by that recipe.
This d should respect any conda_build_config.yaml files that you have set
up or that you specify.
