### ISSUE TITLE
CONDA_PY=27, 34 not recognized by conda-build 3.0

### ISSUE THREAD

**Issue by MatthieuDartiailh** [conda/conda-build#2168]
Those values now leads to a search for Python 27.* which fails as illustrated here https://travis-ci.org/Ecpy/conda-recipes/builds/251547219.
This is likely o break a number of continuous integration scripts and break backwards compatibility. Furthermore setting CONDA_PY=2.7 appears to work even if conda re-export CONDA_PY=27 as illustrated here https://travis-ci.org/Ecpy/conda-recipes/jobs/251550112.

**Comment by MatthieuDartiailh** [comment]
Out of curiosity should one prefer the CONDA_PY=27 or CONDA_PY=2.7 format in the future. Also the documentation needs to be updated.

**Comment by msarahan** [comment]
Honestly, you should prefer the new conda_build_config.yaml way of doing things.  The format there is with the period, 2.7.  https://conda.io/docs/building/variants.html

The env vars will be maintained probably forever, and it's my fault for breaking them.  They should stay the same as they always have been - no period in them.  I think the code right now allows either, but staying with the older way is probably good for simple consistency.

**Comment by MatthieuDartiailh** [comment]
Ok thanks for pointing me to the right docs. For Travis build the env vars remain quite useful even if I could manage with --variants. Anyway thanks for fixing it.

**Comment by msarahan** [comment]
Yes, Travis build is a great example of why the env vars will be maintained in perpetuity.  Thanks again for the report.
