### ISSUE TITLE
Issue with Conda-build 3.0.3 on Python 3.4 (linux and osx)

### ISSUE THREAD

**Issue by MatthieuDartiailh** [conda/conda-build#2169]
I have seen on two different projects failures that affect only Python 3.4 (https://travis-ci.org/Ecpy/conda-recipes/builds/251550111, https://travis-ci.org/Ecpy/ecpy/builds/251553686). In the first case the build is also run on Windows and work fine there. 
There dos not seem to be a clear error message...

**Comment by msarahan** [comment]
Thanks for reporting.  This appears to be an issue with conda-build losing its mind when it encounters a package with a short prefix:

https://travis-ci.org/Ecpy/ecpy/jobs/251553688#L1537

The build itself seems to still be looking for the long prefix somehow: https://travis-ci.org/Ecpy/ecpy/jobs/251553688#L1630

After that, all hell breaks loose, and you end up trying to create a py35 env, which is not at all what you've just built a package for: https://travis-ci.org/Ecpy/ecpy/jobs/251553688#L1641

I'll try to figure out what's going on here.

**Comment by msarahan** [comment]
PS: a workaround might be to try to shorten your prefix, through the use of this flag to conda-build:

```
  --prefix-length _PREFIX_LENGTH
                        length of build prefix. For packages with binaries
                        that embed the path, this is critical to ensuring that
                        your package can run as many places as possible.
                        Note that this value can be altered by the OS below
                        conda-build (e.g. encrypted filesystems on Linux), and
                        you should prefer to set --croot to a non-encrypted
                        location instead, so that you maintain a known prefix
                        length.
```

**Comment by pavoljuhas** [comment]
As a quick fix - would it help to remove Python 3.5.0rc4 from the defaults channel?

The "rc" version is earlier than 3.5.0.  Perhaps that confuses dependencies 
resolution enough to choose the 3.5rc instead of the last Python 3.4.

**Comment by msarahan** [comment]
@pavoljuhas that was exactly the problem.  I have fixed this in #2183.

**Comment by msarahan** [comment]
fixed by #2183 - closing

**Comment by MatthieuDartiailh** [comment]
Do you have a rough estimation of the next release timeline ?

**Comment by MatthieuDartiailh** [comment]
And thanks for fixing all those issues !

**Comment by msarahan** [comment]
later today is my goal.  Thanks for the bug reports and your patience.

**Comment by msarahan** [comment]
3.0.4 is released and should be available on defaults.  Please let us know if (when?) you see further issues
