### ISSUE TITLE
--output is overly verbose

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2173]
the output option is used by our scripts to determine the name of the file that is being generated. In all 2.* versions it used to print one single line with the FQFN. Unfortunately with 3.0.3, it starts to print many info lines as well which clutter the output...

```
$ conda build conda-receipe/ --output                                                                                                                        
Attempting to finalize metadata for dione-ci-scripts
INFO:conda_build.metadata:Attempting to finalize metadata for dione-ci-scripts
/home/gabm/miniconda3/conda-bld/linux-64/package-name.tar.bz2
```

**Comment by msarahan** [comment]
Thanks for the report. There is a test for this, but it seems to not be
working. I'll investigate today.

**Comment by msarahan** [comment]
One workaround for now:

``conda render --output conda-receipe/``

Those CLI commands are identical; investigating why only one of them works.
