### ISSUE TITLE
Support for Microsoft Visual C++ Compiler for Python 2.7

### ISSUE THREAD

**Issue by petrushy** [conda/conda-build#218]
Microsoft has a package of compilers for python for windows:
http://www.microsoft.com/en-us/download/details.aspx?id=44266

The installer seems to install by default to current user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat

if installed by command line for all users it installs to:
C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat

conda-build/windows.py assumes it's located under a specific place at C:\Program Files(x86)\Micros... (line 67-69).
Are there some setting to override this, otherwise I would propose to have such?

**Comment by msarahan** [comment]
Closed by #861
