### ISSUE TITLE
feature request: 'conda skeleton' for local pip packages

### ISSUE THREAD

**Issue by electronwill** [conda/conda-build#2185]
"conda skeleton" can make skeleton conda recipes from packages hosted on cpan cran luarocks and pypi. It would be nice if it could make a skeleton conda recipe from a pip package that is available locally but not on pypi.

**Comment by ijstokes** [comment]
Or for that matter from pip packages that come from Anaconda Repository.

**Comment by krinsman** [comment]
I am having this problem as well -- there is a Python package which does have a `requirements.txt`, but for some reason that `requirements.txt` doesn't seem to be included with the source distribution uploaded to PyPI, so `conda skeleton pypi <package-name>` doesn't work. (Throws a `requirements.txt` not found error or some such.)

Also `conda skeleton pypi --manual-url <github-repo-of-package>` doesn't work (I don't understand whether that was a suggestion for what could work in [this other issue](https://github.com/conda/conda-build/issues/1975) or if it is supposed to work and I'm just dumb and/or unlucky).

So I tried cloning the repo and then running `conda build` or `conda skeleton` on it, but again no cigar. I guess I'll have to change the `requirements.txt` manually into a `meta.yaml`. Not a complete back-breaker, I know, but it could be more convenient.
