### ISSUE TITLE
When using pinned_packages, conda forgets implicit python version feature on env creation

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2188]
As a workaround for other bugs we pinned the conda-build version in condarc like this:

```
pinned_packages:
  - conda-build 2.*
```

`conda update --all` will now correctly install conda-build in version 2.1.17 for py35 ( we're still on python 3.5). 

Unfortunately, when a build gets started now with: `conda build .` then conda-build will be auto-updated to 2.1.17_py36 - and then a lot of new packages including python 3.6 get installed into the build environment. Adding an explicit track_feature to py35 doesn't help, but pinning conda-build to an exact version including its tag does the job:

```
pinned_packages:
  - conda-build 2.* py35_*
```

**Comment by msarahan** [comment]
Whoa, this is pretty crazy. I don't understand why building a package would
be installing conda build itself. Are you substituting conda build here as
an example for something else?

I'm also not sure that pinned_packages is something that conda build should
respect at all.  It seems like it could easily conflict with recipes and
also make recipes harder to reproduce.  Sooner you are using conda build 3,
have you looked into the new build variants?
https://conda.io/docs/building/variants.html

**Comment by gabm** [comment]
> Whoa, this is pretty crazy. 

indeed - took us some time to find out why

> I don't understand why building a package would
be installing conda build itself. Are you substituting conda build here as
an example for something else

well when creating the build environment, conda and conda-build seems to install/upgrade itself into the new environment. I thought that was intented? Our condarc looks like this because we cannot upgrade to 3.* because of other bugs atm.. until they are fixed we need to stay in 2.* release. 

Because the auto upgrade happens we need to fix the conda-build version through pinning like this...If the auto-upgrade is not intented, then maybe thats the problem?

**Comment by gabm** [comment]
.. maybe its installing because we are using `--croot`?

**Comment by msarahan** [comment]
no, the auto-upgrade is something that conda does when altering the root environment, but conda-build has never done this.  Maybe pinned_packages itself is responsible - the help says:

            A list of package specs to pin for every environment resolution.
            This parameter is in BETA, and its behavior may change in a future release.

so you're actually forcing conda-build to be installed into every build environment by using pinned_packages.  I think you should instead follow your conda update --all with an explicit install of a given conda-build version, rather than using pinned_packages.  A little wasteful, but at least it will do the right thing.

It seems like conda-build itself should probably ignore pinned_packages.

**Comment by gabm** [comment]
actually i think its the other way around

- conda and conda-build seems to be installed/updated automatically somehow
- that brought us 3.0.3 (and now 3.0.4)
- thats why we need to pin it to 2.1.17 (because there are regressions)
- thats why we got py36 variant of 2.1.17 somehow
- thats why we need to do above workaround and even pin the right flavor...

I'll check again, why conda-build and conda get installed/updated in the first place.. From your comments I understand, that the version of conda/conda-build should not get altered/installed or anything... On my laptop thats indeed the case, but on our servers it behaves differently

**Comment by gabm** [comment]
I did some further investigation, now its quite clear to me what happens: conda-build is installed because it is a pinned package upon environment creation. I guess its more or less a desired behavior. Lets hope that 3.* works soon for us so that the upgrade is safe and that we can remove the workarounds..
