### ISSUE TITLE
Windows conda build includes lib2to3 grammar pickle files in unrelated package

### ISSUE THREAD

**Issue by takluyver** [conda/conda-build#219]
I built packages of [mistune](https://github.com/lepture/mistune) on Windows, using `conda skeleton pypi`. The resulting packages had extra files `Lib/lib2to3/PatternGrammar3.4.1.final.0.pickle` and `Lib/lib2to3/Grammar3.4.1.final.0.pickle`. It only seems to occur on Windows; the Linux package I built for it doesn't show this.

You can see this in [this package](https://binstar.org/takluyver/mistune/0.4/download/win-64%5Cmistune-0.4-py34_0.tar.bz2).

**Comment by ilanschnell** [comment]
I think adding the `.pickle` files to the build of Python on Windows is the best solution.
