### ISSUE TITLE
conda-build {RECIPE_DIR} --output produces unwanted stdout

### ISSUE THREAD

**Issue by jkeller-miovision** [conda/conda-build#2190]
I run 'conda-build {RECIPE} --output' as part of a script and capture the stdout to determine the location and name of the package to be built.  Recently (in 3.x I think), I noticed that conda-build started adding additional stdout output when using the --output flag, such as:

"Attempting to finalize metadata for {PKG}"

In my opinion, there should be a way to maintain clean output from this command - perhaps have this extra output go to stderr, or enabled only if a --verbose flag is present.   Alternatively, perhaps a --json output could aid in such use cases.

Thanks.

**Comment by msarahan** [comment]
This should be fixed in conda-build 3.0.4 - what version are you using?

**Comment by jkeller-miovision** [comment]
I believe it was 3.0.3.  I'll check right now with 3.0.4.   Thanks for the ultra-fast reply!!

**Comment by jkeller-miovision** [comment]
Excellent.  3.0.4 is all good.  Thank you.
