### ISSUE TITLE
Download of source packages is done before skip-existing

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2216]
This behaviour changed between CB2 and 3: in CB2 the source download is done after deciding whether we can skip the build while in CB3 not.. That wastes a lot of space and computing time. Could that be changed back?

**Comment by msarahan** [comment]
Conda-build should only be downloading when it is necessary either to render or to build.  If you are not using git jinja, for example, it should not be downloading.  If you can provide a recipe or procedure that reproduces the problem, I'll be happy to look into it.
