### ISSUE TITLE
conda pipbuild can not parse its generated recipe

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#222]
Moved from https://github.com/conda/conda/issues/936.

```
File "/home/marscher/anaconda/lib/python2.7/site-packages/yaml/scanner.py", line 580, in fetch_value
self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here in "/tmp/foo/jpype1/meta.yaml", line 60, column 21
```

steps to reproduce:
conda pipbuild JPype1

conda version: 3.6.4

**Comment by lemoneer** [comment]
I experienced this when doing the following

`conda skeleton pypi pypyodbc`
`conda build pypyodbc`

The build failed with
*yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 56, column 21:
      license: License :: OSI Approved :: MIT License*

That line can be fond in the generate recipe meta.yaml

    about:
      home: http://code.google.com/p/pypyodbc/
      license: License :: OSI Approved :: MIT License
      summary: 'PyPyODBC - A Pure Python ODBC module by ctypes'

The license line found in PKG-INFO is a standard classifier defined here https://pypi.python.org/pypi?%3Aaction=list_classifiers

It would seem the yaml scanner does not like the location of the :: after License or after Approved.  Editing the meta.yaml file to remove these allows `conda build pypyodbc` to succeed.

**Comment by lemoneer** [comment]
I experienced this when doing the following

`conda skeleton pypi pypyodbc`
`conda build pypyodbc`

The build failed with
*yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 56, column 21:
      license: License :: OSI Approved :: MIT License*

That line can be fond in the generate recipe meta.yaml

    about:
      home: http://code.google.com/p/pypyodbc/
      license: License :: OSI Approved :: MIT License
      summary: 'PyPyODBC - A Pure Python ODBC module by ctypes'

The license line found in PKG-INFO is a standard classifier defined here https://pypi.python.org/pypi?%3Aaction=list_classifiers

It would seem the yaml scanner does not like the location of the :: after License or after Approved.  Editing the meta.yaml file to remove these allows `conda build pypyodbc` to succeed.

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
