### ISSUE TITLE
`--old-build-string` breaks bld.bat

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda-build#2225]
I have a `mkdir` command in my `bld.bat` simliar to the below:
`mkdir %PREFIX%\Library\share\myfolder`

With the `--old-build-string` the folder is never created. The same build works fine without that flag or if I revert to `conda-build=2*`

**Comment by msarahan** [comment]
I don't understand what should automatically be created here.
%PREFIX%\Library certainly should be. Is the issue that you're creating the
folder, but it's empty and then not appearing in your package?

**Comment by dhirschfeld** [comment]
The package just unzips `api.7z` to `%PREFIX%\Library\share\myfolder`. For the unzipping to work I've found the folder needs to exist first so I try to create it with `mkdir` (after enabling the extensions to allow it to create folders recursively).

With the `--old-build-string` argument 7z complains that the directory doesn't exist. I've no idea how that could be the case but it's completely replicable for me - without the flag it works, with the flag it doesn't. It also works using conda 2*.

The entirety of the `bld.bat` is below:
```batch
setlocal enableextensions enabledelayedexpansion

mkdir %PREFIX%\Library\share\myfolder

start /wait %PREFIX%\Library\usr\lib\p7zip\7za.exe x api.7z -y -r -o%PREFIX%\Library\share\myfolder
```
With `meta.yaml`:
```yaml
package:
  name: myapi
  version: "2017.07.21"

source:
  path: ../src

build:
  number: 1

requirements:
  build:
    - m2-p7zip
```
And `api.7z` just being in the top-level `src` folder.

**Comment by msarahan** [comment]
That is bizarre. I'm on vacation this week, but will take a look when I
return. @mingwandroid or @mandeep may be able to take a look before then.

**Comment by nehaljwani** [comment]
I tried to reproduce this error, but couldn't. Am I doing something wrong? Attached it the log.
[log.txt](https://github.com/conda/conda-build/files/1167889/log.txt)

**Comment by msarahan** [comment]
@dhirschfeld any tips for reproducing this?  I have also tried with the meta.yaml and bld.bat that you provided, but do not see any issues.

**Comment by dhirschfeld** [comment]
Thanks for having a go. I'll see if I can create an exact repro and post back here...

**Comment by dhirschfeld** [comment]
I can't repro anymore so I'll go ahead and close this....
