### ISSUE TITLE
Build fails if both meta.yaml build script and build.sh are specified

### ISSUE THREAD

**Issue by isaacovercast** [conda/conda-build#2231]
This was introduced in conda-build 3.0. If you specify a build script and build.sh exists the build fails. Steps to reproduce:
* Add the following to a meta.yaml file:
```
build:
  script: python setup.py install
```
* `echo "python setup.py install" > build.sh`

Results in (just the useful part of the error):
```
running install_scripts
writing list of installed files to 'record.txt#!/bin/bash'
error: [Errno 2] No such file or directory: 'record.txt#!/bin/bash'
```
If you rename build.sh or remove the script line from meta.yaml the build works fine. This was not the behavior in 2.x. Seems like the current way (you can have one or the other but not both) is probably "right", but maybe the default behavior could be something better than breaking (took me a _while_ to debug this).

**Comment by mandeep** [comment]
Thanks for reporting this. I'll think about how we want conda-build to decide between build.sh and the build script in meta.yaml, but I do think a warning of some sort is in order.
