### ISSUE TITLE
Building Package on Windows for Linux/Mac

### ISSUE THREAD

**Issue by ratstache** [conda/conda-build#2252]
I've been interested in conda's cross compilation capabilities and decided to try this out myself. Is there a way to build a package on Windows and have it be located in the linux-64 or osx channels.

## Situation

An example of this situation would be if you had dlls that are shared across all three platforms with some platform specific endpoints included. This rules out the use of noarch packages (or forces you to have some extra identifier for each platform). Ideally you would want them located in the repository where they belong.

 ## Problem

The problem for me is there is a lack of documentation on the cross compiling feature. All the examples and test recipes are targeting the same platform but using another compiler. I'm not even sure if what I'm trying to do is possible.

## Goal

I would like to know for my own curiosity if there is a way to do what I've described, and also flag the issue of the documentation being unclear surrounding cross compilation. If someone could get me up to speed with the features I would love to explore this fully and write the documentation update myself!

**Comment by msarahan** [comment]
What do you mean "dlls that are shared across all three platforms"?  Each platform has its own binary format for shared libraries.  You can't reuse shared libraries on arbitrary platforms.  Cross compiling in conda-build 3 is a combination of specifying target platform, but also having compiler packages that do the cross compiling.  conda-build 3 is actually not doing much - just providing a pattern for naming and selecting which compiler package to use, and then setting up the output folder appropriately.  The real work is all in creating the cross compiler package.  Crosstool-ng is a good place to start on that, and you can see a recipe we use with crosstool-ng here: https://github.com/conda/conda-recipes/tree/master/cross-compilers/compilers_generic

**Comment by ratstache** [comment]
Using Mono on Linux and Mac allows you to use DLL's across all three platforms but I would like to always build those DLL's on Windows. So I need to build the packages on Windows and have them housed in the other platforms specific directory (linux-64 and osx-64 instead of win-64).

My apologies if my explanation was unclear

**Comment by msarahan** [comment]
Ah, C#.  We have precious little experience with that - please forgive our limited worldview, and thanks for opening it up.

What you'll need to do here is create compiler "packages" that set up your Mono compiler or whatever it has.  If there's nothing to set up, you can ignore this.  Next, set your target_platform entries in your conda_build_config.yaml, I think.  That might be enough to get conda-build to build packages for each platform.

If you have an example recipe and corresponding C# repo, I can iterate on it with you.

**Comment by ratstache** [comment]
is there any way to change the target platform without including the ```conda_build_config.yaml``` file? When given a list of possible target_platforms it seems to randomly select one when executing ```conda build```. Also zip keys appeared promising but it appears they are managed with a key value store and won't allow duplicate values for ```target_platform```. 

I have read the docs on build variants a few times and I think I am still unclear about how they work. Any advice here would be greatly appreciated.

**Comment by msarahan** [comment]
zip_keys itself doesn't allow duplicate values within a set, but here's an example of pairing up duplicate variants:

```
abc:
  - 1
  - 1
  - 2
def:
  - a
  - b
  - a
zip_keys:
  -
    - abc
    - def
```

You should end up with 3 variants here:

abc: 1, def: a
abc: 1, def: b
abc: 2, def: a

**Comment by ratstache** [comment]
that works well, but I suppose it's not possible to use the variants as flow control in the meta.yaml? For example using one of the variants as a feature in the package.

**Comment by msarahan** [comment]
I think you mean selectors.  I think you might be able to, but I haven't tried/tested it.

meta.yaml
```
some_line   # [{{ somevar }} == 'abc']
```

conda_build_config.yaml
```
somevar:
  - abc
  - def
```

should only run some_line for one of the variants.  This is a tricky thing to get right with the eventual consistency.  I keep finding more and more edge cases.  Please give it a try and let me know if you have problems.

**Comment by ratstache** [comment]
Yes, I get a warning saying that the selector is unknown. When is the ```conda_build_config.yaml``` evaluated? I guess that' means that {{ somevar }} wouldn't be available for use in jinja directives either?

**Comment by msarahan** [comment]
well, there's a lot of re-parsing going on.  A first pass should fail, but later passes should succeed.  It may be that the selector stuff is overly restrictive.  It's pretty old and I haven't messed with it much.  If your code does the right thing eventually, the warning is probably misleading.

**Comment by ratstache** [comment]
you are right, but using ```somevar``` as a feature directly has an unexpected behavior.
```
features:
  - {{somevar}}
```
It locks it down to the first value it selects and doesn't change when the package is rebuilt. So every package is named ```packagename-version-initialvalueofsomevar_0```

So it appears that it isn't re-evaluated later on, and using it as a selector eventually throws an error. 
```
Error: Invalid selector in meta.yaml line 29:
```

**Comment by ratstache** [comment]
I guess the main thing I'm interested in is if there is a way to build cross platform without including the ```conda_build_config.yaml``` file. Can I do that directly from the ```meta.yaml```?

**Comment by msarahan** [comment]
sure, you can hard-code any output's target field to any target platform.  That might work, but unfortunately some if it might be tied into variants.

```
outputs:
  - name: mypkg
     target: osx-64
```

The purpose of the target field is for differentiating the end destination platform when it differs from the build/host platform.  For example, with cross compiler packages, the runtime libraries will use the target field: https://github.com/conda/conda-recipes/blob/master/cross-compilers/compilers_generic/meta.yaml#L76, while the compilers themselves will not: https://github.com/conda/conda-recipes/blob/master/cross-compilers/compilers_generic/meta.yaml#L22

There may be some issues with having similarly named outputs.  I'm not sure.

Out of curiosity, why are you trying to avoid conda_build_config.yaml?

**Comment by ratstache** [comment]
This is the error message I get when trying to specify a target platform in the ```meta.yaml```:
```
AssertionError: Inconsistent subdir in package - index.json expecting win-64, got osx-64
```

The only reason I am tryinng to bypass the ```conda_build_config.yaml``` is because it doesn't conform with the way we handle variants in our other packages and because I can't seem to get the behavior I need when using it.

**Comment by ratstache** [comment]
Just to let you know, I was on 3.0.8 before and just upgraded to 3.0.9 and it works. It being ```{{ target_platform }}``` being used directly as a feature. I think whatever fix you made for #2243 for 3.0.9 release fixed the issue I was having with it being pinned to the original version. 

I am going to close this because I am now able to build linux/mac packages on windows consistently. Using this solution along with ```target_platform```.
```
abc:
  - 1
  - 1
  - 2
def:
  - a
  - b
  - a
zip_keys:
  -
    - abc
    - def
```

I would still like to see the documentation updated as a lot of the cross platform compiling is still unclear to me.

Thanks for all of your help!

**Comment by msarahan** [comment]
Great!  Glad that took care of things.  We'll update the docs soon,
hopefully, but we're very preoccupied with putting out a new anaconda
release.  We will be less crunched perhaps after September.  Any PRs you do
on conda-docs would be much appreciated.

On Thu, Aug 3, 2017 at 4:12 PM, Landon Butterworth <notifications@github.com

**Comment by msarahan** [comment]
#2258 should also help things be smoother.  3.0.10 will be out soon.
