### ISSUE TITLE
SSL Crypto errors when building with 3.0.8

### ISSUE THREAD

**Issue by darkdreamingdan** [conda/conda-build#2255]
I have a basic NLTK downloader recipe, with a simple build.sh:

`python -m nltk.downloader -d $PREFIX/nltk_data book`

This works fine in conda-build 2.1.15.  After upgrading to 3.0.8, i get the following error:

```[nltk_data] Error loading book: <urlopen error [SSL:
/home/user/miniconda3/conda-bld/nltk_book_1501757062443/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:748)>
```

I think this is to do with the pycrypto dependency that conda-build has.  For now, I am using 2.1.15

**Comment by msarahan** [comment]
conda-build removed pycrypto as a dependency when we took out the package signing stuff, which was not implemented securely enough.  Maybe you just need to add pycrypto as a package build time requirement?

**Comment by darkdreamingdan** [comment]
I just tried adding pycrypto as a dependency to by meta.yaml, installing it doesn't seem to help - the bug doesn't seem related to pycrypto after all.

What's really strange is that I can only only seem to reproduce with `conda build`, and not otherwise.  After the build hangs at this step, if i cd into the placeholder directory, and do `bin/python -m nltk.downloader book` it works fine, which is really strange.  It's not something to do with the environment layout itself, I think it's some variable that's not being set correctly during the conda build process.

**Comment by msarahan** [comment]
yes, that might be the case.  Please see what you can find by comparing a dump of environment variables from your base prompt to what you should see embedded at the top of the generated conda_build.sh or build.sh file in the work folder.

**Comment by darkdreamingdan** [comment]
So i digged into the conda_build.sh .   3.0.8 seems to export a _lot_ of variables while 2.1.15 only activates the environment.  While digging through the file, i found this:

`export SSL_CERT_FILE=""`

After removing this line, and executing conda_build.sh by hand, it seems this bug is resolved.  It seems for whatever reason, conda build is exporting this variable but clearing it so that SSL fails.  What's strange is that my `SSL_CERT_FILE` isn't even set in the first place.  This might be an NLTK bug, but I'm not sure.

Observe:
```echo $SSL_CERT_FILE=""
python -m nltk.downloader book
```
works fine, and SSL_CERT_FILE is clearly not set.

However:
```
export SSL_CERT_FILE=""
python -m nltk.downloader book
```
will fail.  It's really odd - but somewhere somtehing is differentiating between an empty string and it not being set at all.

**Comment by darkdreamingdan** [comment]
Breaking it down some more - it appears conda build breaks urllib.  On Python3:

```
export SSL_CERT_FILE=""
python
from urllib.request import urlopen
urlopen("https://google.com")
```

**Comment by msarahan** [comment]
yes, conda-build should not be setting blank variables at all.  Thanks for helping to isolate this.  I'll fix it.

**Comment by neok-m4700** [comment]
@darkdreamingdan 

I had encountered this issue, had to :
```bash
unset REQUESTS_CA_BUNDLE
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt  # OS dependent
```
to fix SSL issues, maybe that'll help ...

**Comment by msarahan** [comment]
@neok-m4700 do you have ca-certificates package installed?  Maybe that has gotten stale and we need to update that package?  I would never advise people to point to system locations like that - it's just a bandaid over the real problem, and we (continuum) need to fix any real problem.

**Comment by neok-m4700** [comment]
Ok, so it works, but I still have to manually export and use the certificates from certifi through ca-certificates:

Specifically I encounter this issue when building
https://github.com/rust-lang/rust and 
https://github.com/rust-lang/cargo

```bash
unset REQUESTS_CA_BUNDLE
export SSL_CERT_FILE=$PREFIX/ssl/cacert.pem
```

**Comment by msarahan** [comment]
great, so we really need to fix the ca-certificates package so that at activation time it makes those changes.  I can take care of that.

**Comment by jakirkham** [comment]
Think this could be caused by PR ( https://github.com/conda/conda-build/pull/2142 ). Would think PR ( https://github.com/conda/conda-build/pull/2322 ) should have fixed this. Did that turn out to be the case or is this still an issue?

**Comment by jakirkham** [comment]
Based on @pkgw's work on issue ( https://github.com/conda-forge/mosfit-feedstock/issues/23 ), it seems that `conda-build` is setting the environment variables `REQUESTS_CA_BUNDLE` and `SSL_CERT_FILE` to empty strings even when the user has not specified them externally. This is likely due to PR ( https://github.com/conda/conda-build/pull/2142 ). It was not the case in `conda-build` 2.1.17, but appears in 2.1.18 where that changed entered. While we have not checked this in `conda-build` 3, would not be surprised if the issue is absent in 3.0.1, but appears in 3.0.2+. IOW this appears to be a `conda-build` bug. How would we like to fix it?
