### ISSUE TITLE
New added surfing to file names, h######, added to package name?

### ISSUE THREAD

**Issue by blowekamp** [conda/conda-build#2256]
I have compiled on linux, OS X, and Windows with newly updated conda, and conda-bld versions:

```
conda                     4.3.23                   py27_0  
conda-build               3.0.9                    py27_0  
```

I am now getting what appears to be a hash added to the package name: "simpleitk-1.0.1-py27h83ca6a7_0.tar.bz2". I can't seem to find any information about this new feature. I am trying to ensure my binary packages have maximum compatibility. So I am wondering if this versioning is compatible with older clients. And also noting that is does not appear to appear with the current condo-forge version of the building tools.

Thanks!

**Comment by msarahan** [comment]
Please see blog post at https://www.continuum.io/blog/developer-blog/package-better-conda-build-3

If you still have questions, I'm happy to answer them

**Comment by msarahan** [comment]
Closing based on thumbs up and party time feedback - we welcome any other feedback from your experience with CB3.

**Comment by blowekamp** [comment]
I just referenced this issue to an initial update to my package, which takes advantage of the much needed automatic pinning of dependent libraries.

CB3 appears to add a lot of really great features, which I can take advantage with my project. There are a large number of options, and I am not sure what the best practices for these are. Are there some exemplar recipes that I could explore?

In particular the multiple outputs looks very interesting and useful for my project. It produces an C++ libraries (static), and then used SWIG to wrap them. This seems like it should be useful to only compile the C++ library once ( per compiler ), and then wrap it for multiple py versions.

**Comment by msarahan** [comment]
Yes, that's a great use for it.  There's a good example of this at https://github.com/conda/conda-recipes/tree/master/xgboost

**Comment by blowekamp** [comment]
Thank you for the example. I do have another follow up question if you will.

Previously, we had to represent the toolchain dependence of libraries with adding them to the feature i.e. vc9 for py27. Does does this work with the xgboost example? Is is now implicit?

**Comment by msarahan** [comment]
Features are not implicit.  If you want features (i.e. you aren't achieving a self-consistent set some other way), you still need the vc features.  CB3 makes it easier, though:

https://github.com/AnacondaRecipes/hdf5-feedstock/pull/1

Even fancier - variant variables in selectors:

https://github.com/AnacondaRecipes/zlib-feedstock/pull/2

The run_exports stuff also really helps with not needing to remember to list runtime reqs in downstream packages.  The zlib recipe does this.  The hdf5 recipe probably should, too.  Packages providing only static libs don't need to, obviously.

**Comment by hainm** [comment]
@mandeep does the new change mean `conda build --output receipt/ --py 2.7` won't give correct output anymore?

**Comment by msarahan** [comment]
Not at all. Conda build asks conda what packages it would install before anything happens, so it knows what the final output path will be before any building actually happens.

**Comment by hainm** [comment]
Do you know why I got two different names for the same receipt here?

https://github.com/conda/conda-build/issues/2305#issue-252139887

Basically, I use "conda build" to build the package, later I add "--output" to get the package path (so I can use that in another build workflow).

**Comment by hainm** [comment]
oh, never mind about my above comment. I think I posted wrong filename. Let me do some digging first.

**Comment by msarahan** [comment]
It's definitely a bug if completely identical inputs lead to different output filenames.  The output filename may change if any of the input packages change.  For example, the build dependencies are hashed at their exact versions.  If one of your upstream dependencies is updated, and you rebuild your same recipe later, it will be a new hash value, and a new output filename.  This is based on the assumption that a different set of build input versions *might* result in a different package, and there's no good way for conda to know, exactly, in a general sense.

One caveat: although I intend for hashes to be stable, we're still finding small things that need to be included or excluded.  So hashes may change between conda-build versions.  In the long-term, this will stabilize, but right now, you should not count on it.
