### ISSUE TITLE
conda render ignores channels specified on command line

### ISSUE THREAD

**Issue by chaubold** [conda/conda-build#2266]
I noticed that `conda render` complained about missing package dependencies, but `conda build` did not. Looking at the code it turns out that `conda render` does not pass on any channels specified on the command line, it only considers those from the `.condarc` file.

To be more precise: the `execute` method in `conda render`'s command line interface [cli/main_render.py#L138](https://github.com/conda/conda-build/blob/master/conda_build/cli/main_render.py#L138) should probably also contain those lines from `conda build` [cli/main_build.py#L309-L323](https://github.com/conda/conda-build/blob/master/conda_build/cli/main_build.py#L309-L323).

**Comment by msarahan** [comment]
what version of conda-build is this?

**Comment by chaubold** [comment]
The very latest one (3.0.9), and my links to the code above were all to the current master.

(Give me one sec, I'm preparing a PR with a fix, just waiting for the test suite to run through...)
