### ISSUE TITLE
"hoisting" unpacked source up one level fails names are identical

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#2273]
I ran into a problem writing a recipe for the package montage (source link is http://montage.ipac.caltech.edu/download/Montage_v5.0.tar.gz). The tarball unpacks into a directory called `Montage`, which contains in it a folder also called `Montage`. in [`hoist_single_extracted_folder`](https://github.com/conda/conda-build/blob/master/conda_build/source.py#L86) that causes a problem because the destination for the copy has the same name as the `nested_folder`.

**Comment by giacomov** [comment]
Same here for other packages, like:

https://heasarc.gsfc.nasa.gov/fitsio/ccfits/CCfits-2.5.tar.gz
