### ISSUE TITLE
Problem: conda-build doesn't clean up temporary files

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2289]
It seems conda-build doesn't clean up temporary files located under `/tmp/tmpxxxxxx` or `User/../AppData/Local/tmpxxxxxx` on windows. After the build these folders contain the decompressed packages that I suppose have been installed as dependencies during the build. Maybe its also a conda problem?!

Anyway, on our Windows build machine we accumulated 25Gb within some weeks ....

**Comment by gabm** [comment]
.. the same files are located again in `miniconda3/pkgs`...

**Comment by msarahan** [comment]
Conda-build uses this functionality in conda for temporary folders: https://github.com/conda/conda/blob/dbe99de1d45206c5d6f2e19017a9e2466f81dc6d/conda/compat.py#L23-L67

When we get files from packages, we do so with the package_has_file function: https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L714-L730

package_has_file does not ever extract the whole package.  This seems like a conda issue.  Sorry, I don't currently have time to investigate this more.  I can move this issue to the conda repo if you'd like.

**Comment by gabm** [comment]
ok, then please move it there... If I find time, I'll have a further look. I realised some strange folders `/tmp/tmpxxxxxxx` some weeks ago, so could be easy to reproduce...

**Comment by msarahan** [comment]
Issue moved to [conda/conda #5847](https://github.com/conda/conda/issues/5847) via [**ZenHub**](https://www.zenhub.com/)
