### ISSUE TITLE
Document why _build is removed during test

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#23]
See https://github.com/conda/conda-build/pull/13.

**Comment by bkreider** [comment]
Can this be closed at this point?

**Comment by asmeurer** [comment]
I think the only place this is documented is at the top of http://conda.pydata.org/docs/build.html, which nobody ever seems to understand.

**Comment by bkreider** [comment]
Is this a common question?  Do people only want to persist it for debugging their builds? If that is the case, instead of deleting it, could it be renamed something like _old_build until the next build cycle?

**Comment by asmeurer** [comment]
I think people are confused by it more than anything. Once they understand why it is done they don't want to change it.

**Comment by msarahan** [comment]
There is now text during the build about the build environment getting moved (not removed).  Closing.
