### ISSUE TITLE
conda build --output doesn't respect --output-folder

### ISSUE THREAD

**Issue by andreas-h** [conda/conda-build#2306]
I'm using conda 4.3.24 on Python 3.5.

When I run `conda build mypackage --output-folder pkgs/ --output`, the path conda returns is the filename the package would have if I hadn't specified the `--output-folder`, i.e., it points to the default conda-build `root-dir` as set in my `~/.condarc`.

This has the effect that I cannot use the path returned by the conda-build command to do further things with the package file.

**Comment by msarahan** [comment]
Use --croot instead of --output-folder.  This is still a bug that I'll try to fix soon, but using --croot should get you further.

**Comment by andreas-h** [comment]
thanks, `conda build mypackage --output --croot pkgs/` does what I want!

**Comment by msarahan** [comment]
Thanks for closing, but I'm going to reopen this until I have managed to make --output-folder behave as expected.

**Comment by andreas-h** [comment]
ah, sorry, I read your comment as "that's already recorded somewhere" -- my bad.
