### ISSUE TITLE
`patch` package crashes when patching

### ISSUE THREAD

**Issue by scw** [conda/conda-build#2307]
The current `patch` package, 2.5.9, can't handle CRLF line endings, and causes a CRT failure when executing against a file with these endings:

```
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
patching file setup.py
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Applying unmodified patch failed.  Convert to unix line endings and trying again.
```

That causes the standard Windows 'searching for errors' popup to trigger. I see that `m2-patch` is recommended instead, I think it makes sense to just require that, and ignore the standalone `patch.exe` altogether.

**Comment by msarahan** [comment]
We can adapt the recipe here, but I think your issue is really with the recipe elsewhere - either at conda-forge, https://github.com/conda-forge/conda-build-feedstock, or at anacondarecipes, https://github.com/anacondarecipes/conda-build-feedstock/

Changing our recipe in this repo won't really fix anything, because the internal recipe is not used for anything other than development packages.  Regardless, please feel free to submit a PR here, or to any of the other repos.

**Comment by scw** [comment]
Hi @msarahan thanks for the reply. I neglected to include enough details: I'm rebuilding a package that I've previously build successfully, currently using:
```
conda                     4.3.24                   py35_0
conda-build               3.0.10           py35h689962e_0
```
My environment also included the `patch` package, version 2.5.9. When I tried to rebuild the same package I'd built previously, I received the error above. Here's what I see in the defaults channel for the package:

```
patch                        1.12.11                  py27_0  defaults
                             2.5                           0  defaults
                             2.5.9                         0  defaults
                          *  2.5.9                         1  defaults
```

I've created a simple repository containing the package that previously I was able to build without any changes:

  https://github.com/scw/netcdf-patch-example/

That should hopefully include enough details to reproduce the behavior. On my machine, that will consistently cause a crash in the patching phase, though conda-build still will try to continue after the failed patching. In the absence of an updated `patch` on anaconda.org which doesn't exhibit this behavior, I think for Windows, it makes sense to have `m2-patch` be 'the right way' to apply patches. On MacOS and Linux, it's either available out of the box or one apt-get away, but on Windows that's not the case. I was suggesting `m2-patch` as a dependency on Windows because it would simplify the workflow somewhat. If there are specific details of my environment which are causing this and it's not reproducible, this issue can be closed.

Perhaps a separate issue is that the documentation doesn't really communicate how to generate patches that conda-build can consume at the moment, I can open a separate documentation issue on that, and provide some suggested copy if that'd be useful. I've just been using `diff -u` and `git diff` to generate my patches, but I see that there are some more sophisticated options using e.g. `git format-patch` which may be worth documenting.

Thanks for all your great work on Conda,
Shaun

**Comment by msarahan** [comment]
Does conda eventually succeed at patching?  What's new relative to old versions is that old versions always tried to convert line endings to unix.  New versions try the patch as-is, but then fall back to converting to windows and then unix line endings.  So, as long as the patch eventually succeeds, the errors are meaningless.

Anyway, I think Conda (as a package ecosystem) can make this situation better by having a patch package available on all platforms.  It doesn't matter if it's already available on the system - having it be a dependency at some know version will help make sure it always works.

We do need to document how to generate patches.  I personally do mine with ``git diff``.

**Comment by ratstache** [comment]
I've run into this issue before, it actually pops up the windows not responding/debug dialogue so it is a proper crash. The only time I saw it come up was when the line endings in my patch file were a mixture of Windows and Unix, like Unix line endings for where it is actually working with code and Windows line endings where it's just patch file information. Switching all line endings to Unix worked as a solution for me. I also reverted back to conda-build 2 out of curiosity and it worked with the mixed line endings, due to what you said before.

**Comment by scw** [comment]
Right, as it does for @ratstache it causes a full windows crash. The rest of conda build will  continue, without the patch being applied, which in my case will later cause a failure due to the library names differing. Here's the output of dos2unix on this patch file:
```
$ dos2unix -i hdf5.patch
       0      33       0  no_bom    text    hdf5.patch
```
So 33 LF (Unix) line breaks only. None of the files in the above repository have Windows-style line endings. I can confirm that this package builds for me on 2.1.17, but not on any of the 3.x versions I've tested.

**Comment by benmwebb** [comment]
FWIW, I think I'm seeing the same issue here - patch on Windows crashes when given a 'normal' diff (Unix-style LF line endings) so the patch is not correctly applied. It works fine if given a DOS format file though (CRLF line endings). My workaround for now is to provide CRLF variants of each patch for Windows builds, as per salilab/conda-recipes@b9c2c0195.

**Comment by mingwandroid** [comment]
Use `m2-patch`.

**Comment by scw** [comment]
@mingwandroid Yes, `m2-patch` is definitely the right answer. However, other users will still hit this if they happen to have `patch` which will still be used by `conda-build`. I recommend making `m2-patch` a requirement of conda-build when running on Windows.
