### ISSUE TITLE
When specifying "disable_pip" dependencies of pip don't get removed

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2313]
When I specify `disable_pip=True` in a meta.yaml, then pip, setuptools and wheel gets removed as desired. But the dependencies of them are still present...

Background: I built certifi and i got a circular dependency problem. I realised that pip/setuptools is implicitly added, so i specified `disable_pip` in the recipe and pip/setuptools/wheel was successfully suppressed. But not certifi which is why i still got the circular dep. problem. *something instisted* on installing certifi itself, i ran the dependency tree up and and down for hours - and finally i realised that its about that. conda seems to resolve pip and CB is removing it again. but not their deps.. so I still got certifi installed :/

As a workaround I disabled pip globally in .condarc, but ... hmmm

**Comment by neok-m4700** [comment]
Have a look into `add_pip_as_python_dependency` in conda, not conda_build !

 It is a matter of resolving dependencies, and that is the job of conda not conda_build.

I achieve that progammatically using
```python
import conda as c
import conda_build as cb

conda_context = c.base.context.reset_context(argparse_args=context)  # change the context here, where context is a dict e.g. dict(add_pip_as_python_dependency=False)

cb.index.local_index_timestamp = 0  # force rebuild of the conda index
```

**Comment by gabm** [comment]
well there is the option `disable_pip` which basically does the same as `add_pip_as_python_dependency`, but on recipe-level.

I suspect the problem is that instead of handing over that flag into conda so that conda can prevent installing pip in the first place it asks conda to resolve pip/setuptools/wheel and then _manually_ removes these three packages. But not their dependencies...

Globally setting `add_pip_as_python_dependency` in condarc works as a workaround

**Comment by msarahan** [comment]
I have just debugged another issue related to this (#2793), and can confirm that disable_pip is working as it should.  If this is still an issue for anyone, please create a new issue.
