### ISSUE TITLE
ImportError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by reedjasonf** [conda/conda-build#2315]
I am running conda version 4.3.25 and conda-build 3.0.12.

When attempting to build a conda package I've developed with the command 'conda build --no-anaconda-upload --no-include-recipe --python 3.5 ./' I get the following error: 

Copying C:\Users\jreed01\Documents\Python Projects\Generic_Waveform\trunk to C:\Miniconda3\conda-bld\generic_waveform_1503617119709\work
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "C:\Miniconda3\lib\site-packages\conda_build\api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "C:\Miniconda3\lib\site-packages\conda_build\build.py", line 1726, in build_tree
    bypass_env_check=True)
  File "C:\Miniconda3\lib\site-packages\conda_build\render.py", line 594, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "C:\Miniconda3\lib\site-packages\conda_build\render.py", line 427, in distribute_variants
    bypass_env_check=True)
  File "C:\Miniconda3\lib\site-packages\conda_build\metadata.py", line 772, in parse_again
    bypass_env_check=bypass_env_check),
  File "C:\Miniconda3\lib\site-packages\conda_build\metadata.py", line 1339, in _get_contents
    rendered = template.render(environment=env)
  File "C:\Miniconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Miniconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Miniconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jreed01\Documents\Python Projects\Generic_Waveform\trunk\meta.yaml", line 1, in top-level template code
    {% set data = load_setup_py_data() %}
  File "C:\Miniconda3\lib\site-packages\conda_build\jinja_context.py", line 106, in load_setup_py_data
    permit_undefined_jinja=permit_undefined_jinja)
  File "C:\Miniconda3\lib\site-packages\conda_build\_load_setup_py_data.py", line 85, in load_setup_py_data
    exec(code, ns, ns)
File "C:\Miniconda3\conda-bld\generic_waveform_1503617119709\work\setup.py", line 31, in <module>
    from generic_waveform import __version__ as version, __doc__ as long_description
  File "C:\Miniconda3\conda-bld\generic_waveform_1503617119709\work\generic_waveform\__init__.py", line 33, in <module>
    from generic_waveform.generic_waveform import GenericWaveform
  File "C:\Miniconda3\conda-bld\generic_waveform_1503617119709\work\generic_waveform\generic_waveform.py", line 35, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named 'matplotlib'

However, I have matplotlib listed in my requirements section of the meta.yaml. I also have the matplotlib module installed in my current environment so I'm not sure why it still won't build but I thought that conda-build created a new temporary environment with all the dependencies anyway but this appears not to be happening.

**Comment by msarahan** [comment]
You're triggering a nasty import chain.  Is this your library?  If so, you really need to find a way of running setup.py without triggering imports all the way into matplotlib.  That's something you *really* don't want to be doing at build time.  I recommend using something like versioneer or setuptools_scm for handling your version.  Conda-build uses versioneer, if you need an example.

**Comment by reedjasonf** [comment]
Thanks for the quick response.

I'm confused thoroughly. When I run 'conda build...' isn't is supposed to make a temporary environment with all my dependencies in it, build the package, then clean up the environment? Why don't I want to import matplotlib? My matplotlib import isn't even that deep in my library.

But I'll give versioneer a try. I was hoping this library was going to build like all the other ones. :-<

**Comment by msarahan** [comment]
It should be there, and conda-build should be re-parsing your library in the build environment.  It should work.  If you point me to your library, I may see something.

Still, it remains that this program architecture is overly burdensome.  The more imports that happen in setup.py or because of setup.py, the harder your software is to build.

**Comment by reedjasonf** [comment]
Unfortunately the library isn't published anywhere you could view it but I can provide the snips of what I think might assist...

structure:
```
trunk/
├── bld.bat
├── environment.yaml
├── meta.yaml
├── setup.py
└── generic_waveform/
    ├── __init__.py
    ├── errors.py
    └── generic_waveform.py
```

in generic_waveform.py:
```
import csv
import os

import matplotlib.pyplot as plt

class GenericWaveform:
...
```

That is the only class in generic_waveform.py. It is actually a really short class implementation too.

in \_\_init\_\_.py:
```
from __future__ import (
    unicode_literals,
    print_function,
    division,
    absolute_import
)

from generic_waveform.generic_waveform import GenericWaveform
from generic_waveform.errors import GenericWaveformError

__version__ = '0.0.0'
__author__ = 'reedjasonf'

__all__ = ['GenericWaveform', 'GenericWaveformError']
```


meta.yaml:
```
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set description = data.get('description') %}
package:
  name: generic_waveform
  version: {{ version }}

source:
  path: ./

build:
  number: 1
  string: py{{ CONDA_PY }}_{{ ARCH }}


requirements:
    build:
        - python >=3.5
        - matplotlib >=2.0
        - numpy >=1.13
    run:
        - python >=3.5
        - matplotlib >=2.0
        - numpy >=1.13
    test:
        - python >=3.5
        - matplotlib >=2.0
        - numpy >=1.13

about:
  home:
  license:
  summary: {{ description }}
```


setup.py:
```
from __future__ import (
    unicode_literals,
    print_function,
    division,
    absolute_import
)

from setuptools import setup, find_packages

from generic_waveform import __version__ as version, __doc__ as long_description

setup(
    name='generic_waveform',
    version=version,
    author='reedjasonf',
    author_email='',
    description=(
        "Empty description"
    ),
    long_description=long_description,
    packages=find_packages('.', exclude=['test', 'test.*', 'docs']),
    entry_points={
        # To be specified later
    },
    install_requires=['matplotlib>=2.0', 'numpy>1.13']
)

```

**Comment by reedjasonf** [comment]
Additionally, downgrading conda-build to 2.1.17 builds the library just fine.

**Comment by msarahan** [comment]
Thanks for the data point.  I'll try to figure out what broke when I get a chance.  We're kind of swamped trying to get the next Anaconda release out the door right now.  Please stick to 2.1.17 as necessary.

**Comment by msarahan** [comment]
closing - we have attempted to provide better messaging in this situation in #2784
