### ISSUE TITLE
SP_DIR variable in test section points to build environment's site-packages directory

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [conda/conda-build#2331]
According to [conda-build documentation](https://conda.io/docs/user-guide/tasks/build-packages/environment-variables.html#environment-variables-that-affect-the-test-process) one should expect ``SP_DIR`` variable to point to ``site-packages`` directory of the test environment. 

However adding to `meta.yaml` 

```
test:
   commands:
       - echo {{SP_DIR}}
```

and executing conda-build, I see that it actually points to the build-environment:

```
+ echo /localwork/projects/cellprofiler/sources/conda-build/javabridge_1504016692348/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages
/localwork/projects/cellprofiler/sources/conda-build/javabridge_1504016692348/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages
```

My environment:

```
(root) [09:25:14 vmlin sources]$ conda list conda
# packages in environment at /localwork/miniconda3:
#
conda                     4.3.23                   py35_0
conda-build               2.1.17                   py35_0
conda-env                 2.6.0                         0
conda-verify              2.0.0                    py35_0
(root) [09:26:37 vmlin sources]$
```

**Comment by msarahan** [comment]
Ah, so there's not actually a bug here.  You're getting jinja2 variables mixed up with environment variables.  You have a jinja2 variable.  That's always evaluated at build time.  You need to be using environment variable syntax instead:

- echo $SP_DIR  # [not win]
- echo %SP_DIR%  # [win]

**Comment by oleksandr-pavlyk** [comment]
@msarahan Thanks for the explanation. Using env. variable does indeed work.
