### ISSUE TITLE
LD_RUN_PATH

### ISSUE THREAD

**Issue by neok-m4700** [conda/conda-build#2332]
https://github.com/conda/conda-build/commit/2bf8f1df900362cac68d359d6e498a6c252acdea removed `LD_RUN_PATH` from environment variables on linux, shouldn't it be keep pointing to $PREFIX/lib ?

What's the point of building into a  $PREFIX when not linking by default with libs in the $PREFIX when no -rpath is given ?

Especially when the whole libraries relocation process is done afterwards with patchelf ...

**Comment by msarahan** [comment]
@mingwandroid knows more.  The thought was that this should be handled by the compiler.  Our new GCC packages handle rpath during build using a custom specfile.

https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-feedstock/recipe

and specifically

https://github.com/AnacondaRecipes/aggregate/blob/master/ctng-compilers-feedstock/recipe/install-gcc.sh#L145-L159

You can use these compilers with the c3i_test channel.

**Comment by neok-m4700** [comment]
Thanks for the links, very interesting !

I think I'll also go for a specfile with my own gcc recipe, of course this is the way to go.

This broke a lot of my recipes, and it took some time to figure out what went wrong, so maybe you'll get some more issues on this ...

**Comment by msarahan** [comment]
I need to make sure I won't break anything, but you're right, I should keep this around and put a deprecation notice in.

**Comment by mingwandroid** [comment]
I would rather we didn't use `LD_RUN_PATH` and instead use the more explicit `-rpath-link`.

**Comment by mingwandroid** [comment]
I am actually having second thoughts about modifying the specs file at all. I don't think it is necessary now that we have `weak` and `strong` `run_exports`.

IMHO strong `run_exports` should cause conda-build to install those into the `host` prefix at build-time.
