### ISSUE TITLE
conda build can't seem to download CRAN packages despite proxy settings

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-build#2336]
Submitted on behalf of another user, but note that I have reproduced this myself on their system.

We're running conda-build 2.1.15 with requests 2.12.4 here. Steps to reproduce:
```
conda skeleton cran ldavis
conda build r-ldavis
```
During the build process, the CRAN package cannot be downloaded:
```
Source cache directory is: /opt/wakari/anaconda/conda-bld/src_cache
Downloading source to cache: LDAvis_0.3.2.tar.gz
Downloading https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz
Error: HTTP None None for url <https://cran.r-project.org/src/contrib/LDAvis_0.3.2.tar.gz>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Downloading https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.3.2.tar.gz
Error: HTTP None None for url <https://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.3.2.tar.gz>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download LDAvis_0.3.2.tar.gz
```
Using `wget` to download the package from the same URL works just fine, giving evidence that the proxy settings are correct.

The user reports that it worked before. He was running 2.1.7 at the time, but upgrading to 2.1.15 did not help. It's not clear then what could have changed from when it worked for him and when it did not, so it's possible the issue is environment-specific. Nevertheless, if wget is successfully able to navigate the proxy, it stands to reason that conda-build should be able to as well.

**Comment by mcg1969** [comment]
cc: @kalefranz 

@msarahan and I have determined that the failure is occurring inside the `conda.gateways.download.download()` method, which conda-build uses to fetch the package. A little printf debugging reveals that `session.proxies` is empty.

**Comment by stephenakearns** [comment]
Hi @msarahan and @csoja - any chance of looking at this now that we're thru the release of AD5? The associated #GSK support ticket has been open for a month now and I'm wondering if this is an easy fix.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda#6081
