### ISSUE TITLE
conda3 pipbuild fails with a python2.7 installation

### ISSUE THREAD

**Issue by tiagoantao** [conda/conda-build#234]
conda pipbuild is failing (conda based on python 3).
I have an environment with python=2.7 (though I do not believe that is the problem) and, if I do
conda pipbuild whatever
it fails, for example:
conda pipbuild pygraphviz
Returns (a typical python 3 problem):

Fetching package metadata: ..
Creating standard recipe for pygraphviz-1.3rc2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/tra/anaconda3/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/tra/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 77, in main
    args_func(args, p)
  File "/home/tra/anaconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 308, in args_func
    args.func(args, p)
  File "/home/tra/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 350, in execute
    build_package(package, version)
  File "/home/tra/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 300, in build_package
    directory = build_recipe(package, version=version)
  File "/home/tra/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 161, in build_recipe
    output = result.strip().split('\n')
TypeError: Type str doesn't support the buffer API

conda info is:
Current conda install:

```
         platform : linux-64
    conda version : 3.7.0
```

  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.4.1
     root environment : /home/tra/anaconda3  (writable)
  default environment : /home/tra/anaconda3
     envs directories : /home/tra/anaconda3/envs
        package cache : /home/tra/anaconda3/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

Notice that after the first pipbuild attempt, conda stays in a unstable state (and starts reporting other errors), for example the directory
/home/tra/anaconda3/envs/_pipbuild_
appears

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
