### ISSUE TITLE
SP_DIR doesn't handle --python 3 correctly

### ISSUE THREAD

**Issue by ezyang** [conda/conda-build#2346]
When I run `conda build foo --python 3`, it seems to think SP_DIR is `lib/python3./site-packages` (note the period slash!)

**Comment by 2quarius** [comment]
similar situation encountered:
When I specified python 3.8.* under requirements.build of `meta.yaml`, the SP_DIR still points to `libpython3.6/site-packages` which is not existing.

**Comment by 2quarius** [comment]
> similar situation encountered:
> When I specified python 3.8.* under requirements.build of `meta.yaml`, the SP_DIR still points to `libpython3.6/site-packages` which is not existing.

mine solved:
for conda build specified python version by --python
