### ISSUE TITLE
conda skeleton leaves tilde chars from requires.txt

### ISSUE THREAD

**Issue by notestaff** [conda/conda-build#2351]
Running conda skeleton pypi fs gives

requirements:
  build:
    - python
    - setuptools
    - appdirs~ 1.4.3
    - pytz
    - setuptools
    - six~ 1.10.0
  run:
    - python
    - setuptools
    - appdirs~ 1.4.3
    - pytz
    - setuptools
    - six~ 1.10.0

**Comment by mandeep** [comment]
Looks like a bug in how package version specs with tilde are being parsed. According to PEP 440 the tilde is for compatible releases: https://www.python.org/dev/peps/pep-0440/#compatible-release

@msarahan should we parse something like ``appdirs~=1.4.3`` as ``appdirs >=1.4.3, <1.5``?

**Comment by msarahan** [comment]
As I understand it, it would translate more to 

```appdirs >=1.4.3, <2```

which is coincidentally the default ``pin_compatible`` behavior.  I think ideally the build dep should be ``>=(value from ~)`` and the run dep should be ``{{ pin_compatible('depname') }}``

**Comment by notestaff** [comment]
also, note that setuptools dependency is listed twice in both build and run sections

**Comment by notestaff** [comment]
also, test dependencies in the generated meta.yaml that are also run dependencies could be omitted.

**Comment by msarahan** [comment]
You're getting into a lot of nice-to-haves.  Pull requests are very welcome.
