### ISSUE TITLE
build paramereter python: noarch (some packages we can't install yet)

### ISSUE THREAD

**Issue by ReimarBauer** [conda/conda-build#2357]
We found trying python: noarch that menuinst can't be installed

conda 4.3.25
conda-build 3.0.15

WARNING:conda_build.noarch_python:Don't know how to handle file: Menu/mss_shortcut.json. Omitting it from package
WARNING:conda_build.noarch_python:Don't know how to handle file: Menu/mss.ico. Omitting it from package.

**Comment by msarahan** [comment]
Thanks for reporting.  PR's welcome.  This is an important improvement, but not one I can give priority to right now, as we currently do not use noarch for the Anaconda Distribution.  If anyone has time to submit a PR, I'll gladly incorporate it.

**Comment by mbargull** [comment]
@ReimarBauer: Does #2420, i.e., using `conda-build >=3.0.24`, fix this issue?

**Comment by onlyjus** [comment]
`conda-build >=3.0.24` fixes the `Omitting it from package` however if I build the conda package in the Anaconda Docker container (dedian:8) and try installing on windows, during the install process I get a `menuinst Exception`.

my build.sh script looks like this:
```
#!/bin/bash
mkdir -p "$PREFIX/Menu"

cp "$RECIPE_DIR/menu-windows.json" "$PREFIX/Menu"
cp "$RECIPE_DIR/icon.ico" "$PREFIX/Menu"

$PYTHON setup.py install --old-and-unmanageable
```

**Comment by mbargull** [comment]
@onlyjus: Three questions:
1. What does the `menuinst Exception` say exactly?
2. Does the same error occur if you build on Windows (without `noarch: python`)?
3. I'm not sure if `conda`/`menuinst` take care of file name collisions in `Menu`. Can you try using package-specific file names? E.g., something like:
```bash
sed -i.bak 's/\<icon\.ico\>/'"$PKG_NAME-$PKG_VERSION.ico"'/g' "$RECIPE_DIR/menu-windows.json"
cp "$RECIPE_DIR/menu-windows.json" "$PREFIX/Menu/$PKG_NAME-$PKG_VERSION.json"
cp "$RECIPE_DIR/icon.ico" "$PREFIX/Menu/$PKG_NAME-$PKG_VERSION.ico"
```

**Comment by onlyjus** [comment]
Thanks @mbargull. Looks like conda install is just catching a blanket exception when calling `menuinst`, so the text printed to the console (--debug and --verbose did not effect) is just `menuinst Exception`. Adding prints and capturing exceptions in the installed `menuinst`, I discovered that I had an extra comma in my `menu-windows.json`. 

I now am successfully building in the miniconda3 docker (Debian 8) image and installing on windows 10 with menu entries.

**Comment by mbargull** [comment]
> Looks like conda install is just catching a blanket exception when calling menuinst

That's odd, `conda` should pass the exception information along (see the `exc_info` in https://github.com/conda/conda/blob/4.3.30/conda/gateways/disk/create.py#L151).

But it is good to hear, it works now. Although I'd like to stress that the `Menu` files will be installed under any OS, not just Windows. This is theoretically undesirable as this would create broken menu entries under Linux/OSX. In praxis this currently just doesn't make much of a difference since `menuinst` is only working for Windows and not used for the other OSes. See https://github.com/ContinuumIO/menuinst/issues/48 for potential future work on that topic.

**Comment by onlyjus** [comment]
I will keep that in mind. Looks like that issue has already been discuss in ContinuumIO/menuinst#48 and  ContinuumIO/conda#5153

Thanks for your help! I  vote to close this issue.
