### ISSUE TITLE
Cannot build packages due to dependencies being in conflict with ... nothing?

### ISSUE THREAD

**Issue by benmwebb** [conda/conda-build#2361]
With latest conda (4.3.25) and conda-build (3.0.17) on 64-bit Windows 7 I'm unable to build simple packages:

    C:\> conda build --python=3.6 testpkg
    INFO:conda_build.metadata:Attempting to finalize metadata for testpkg
    failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
      - jpeg 9b.*
    Use "conda info <package>" to see the dependencies for each package.

where `testpkg/meta.yaml` is simply:

    package:
        name: testpkg
        version: 1.0
    
    build:
        features:
          - vc9 [win and py27]
          - vc14 [win and py36]
    
    requirements:
        build:
            - python [win]
            - jpeg 9b.*
        run:
            - jpeg 9b.*

The error message is rather confusing because it doesn't say what the `jpeg` dependency conflicts with! BTW, it's definitely possible to install jpeg 9b, as it's **already** installed in this environment.

**Comment by msarahan** [comment]
You have no way to activate a feature at runtime.  If you add

```
requirements:
    build:
        - python [win]
        - jpeg 9b.*
    run:
        - jpeg 9b.*
        - vc  9 [win and py27] 
        - vc  14 [win and py36]
```

it should work.  There's a better way with conda-build 3.  See https://github.com/AnacondaRecipes/zlib-feedstock/blob/master/recipe/meta.yaml for an example.  Note that the {{ compiler('c') }} is actually going to impose a runtime requirement on vc for you.  More info at https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/ and the VS20?? recipes, such as https://github.com/AnacondaRecipes/aggregate/blob/master/vs2008/meta.yaml

**Comment by benmwebb** [comment]
OK, thanks (although this is certainly not clear from https://conda.io/docs/user-guide/tasks/build-packages/features.html; perhaps that pertains only to older versions of conda-build) But that my issue was really why the error message claims that the set of conflicting packages has a size of 1 (which is surely impossible).

**Comment by msarahan** [comment]
Features are extraordinarily painful, and I'm sorry you've been bitten here.  We're working on a better way that hopefully will be ready soon.  Between conda-build 3 variants and conda 4.4 being much more able to select arbitrary varieties, there will be much more intuitive behavior - eventually...

**Comment by benmwebb** [comment]
Sounds good. Many thanks for the detailed reply! I'll muddle through somehow in the meantime.
