### ISSUE TITLE
automagic splitting of debug symbols into -dbg packages

### ISSUE THREAD

**Issue by epruesse** [conda/conda-build#2363]
Conda binary packages often contain large amounts of debug symbol information not needed for normal operation. Mainstream distros offer tools to help split these into separate packages. Manually creating a `-dbg` package requires good understanding of linkers and debuggers, but it's pretty much always the same process. 

`conda-build` already deals with `rpath` issues, so it knows which files are affected. Automating calls to `strip` and creating a secondary `-dbg` output package should be relatively straightforward and would reduce overall package size and bandwidth usage.

**Comment by epruesse** [comment]
@msarahan as requested, noted idea as ticket

**Comment by msarahan** [comment]
Excellent, thanks for writing this down.  This would be a nice feature.

**Comment by epruesse** [comment]
It might be worthwhile to consider an approach that will allow for help with the other "standard" sub-pakages: 
 - `{name}-dev` (headers and static libs not usually required)
 - `lib{name}{sovers}` (to allow multiple so versions at the same time) 

and perhaps even 

 - `{name}-doc` (archival, once online manual disappears)
 - `{name}-src` (legal, GPL mandates binary distributor must ensure source availability)

**Comment by jakirkham** [comment]
This sounds like a good idea @epruesse.

We talked briefly about this at our last conda-forge meeting, but it was not the primary subject of the discussion. So we didn't really plan a path forward for it.

That said, this is a good topic to discuss and expect many people to be interested in this sort of thing. In particular debug libraries are a frequent discussion topic in conda-forge. Given we are about to move to conda-build 3 in conda-forge, expect this to have renewed interest. Perhaps we can explore a bit how we want to do this manually and then codify what works in an automated conda-build workflow? Raised issue ( https://github.com/conda-forge/conda-forge.github.io/issues/544 ) to discuss this further.
