### ISSUE TITLE
New command for creating an offline channel

### ISSUE THREAD

**Issue by lambdalisue** [conda/conda-build#2387]
Recently, I needed to create an offline channel of particular packages. It seems there are no way to create a channel with all dependencies so I made https://github.com/lambdalisue/conda-offline-channel

So I would like to ask if this feature helps you. I'd love to include it in conda-build package if it helps someone.

Thanks.

**Comment by msarahan** [comment]
Thanks!  This seems extremely useful, coincidentally for exactly what we're doing now in terms of rebuilding the Anaconda distribution.  Now isn't the right time for me to look at integrating this immediately, but I think your tool will be useful to us as it stands, and I'm definitely interested in incorporating it after we get the Anaconda 5 release out.

**Comment by lambdalisue** [comment]
Thanks for the reply. So when should I send a PR?

**Comment by msarahan** [comment]
Go ahead and send a PR whenever you're ready.  I may not get to merging it immediately, but I'll try to provide feedback as time allows.

**Comment by lambdalisue** [comment]
OK I will. For now, users can use it via

```
conda install -c lambdalisue conda-offline-channel
conda offline-channel {package names...} {options}
```

**Comment by cyonghui81** [comment]
Lambdaliuse, what you did is good !
Can we specify the specific versions of the packages ?
