### ISSUE TITLE
conda skeleton creates wrong url using lower case for some packages

### ISSUE THREAD

**Issue by Jacob-Barhak** [conda/conda-build#2389]
When using conda skeleton on some PyPi packages, skeleton produces a url with lower case characters that leads to a wrong location, making the skeleton useless.

See an example when building the rxpy package using: 
`conda skeleton pypi rxpy`

Try running the following build command afterwards:
`conda build rxpy`

The system returns an error: 
```
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download https://pypi.io/packages/source/r/rxpy/rxpy-0.1.0.tar.gz
```
The correct package link in this case is:
https://pypi.io/packages/source/r/rxpy/RXPY-0.1.0.tar.gz

Yet looking at meta.yaml it seems that lower case name is used twice for both package directory and package name. Here are relevant lines from the meta.yaml file:
```
{% set name = "rxpy" %}
name: '{{ name|lower }}'
url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
```

It would be great if the url code will be changes to include the correct case for each name occurrence - lower for the directory name followed by the proper case of the package name. 

It would also help if skeleton will check the existence of the URL before build and at least raise a warning.

**Comment by mandeep** [comment]
Instead of using packagename.lower() we could just use packagename, but then the user would be responsible for downloading the correct package.

https://github.com/conda/conda-build/blob/master/conda_build/skeletons/pypi.py#L201

**Comment by BartholomaeusAstrum** [comment]
Had the same problem with the TextGrid package: https://pypi.org/project/TextGrid/#files
To get around the capitalization problem, copying the correct URL into `meta.yaml` seems to have worked!

**Comment by snajder-r** [comment]
Same happened to me, but it was my own fault for running `conda skeleton` with the lowercase name. Interestingly `conda skeleton` is still successful at retrieving the dependencies from pypi and building the meta.yaml, but then `conda-build` fails when downloading the source.
