### ISSUE TITLE
Parsing issue on Windows with quoted license_file text

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2397]
Appears that when quoting the `license_file` text (as in the linked PR), `conda-build` on Windows only has an issue parsing the `meta.yaml` file. This happens regardless of whether Python 2 or Python 3 is used. Some AppVeyor builds are linked below for demonstration of the issue. Sample output from one of the logs is shown below. Note that the line it links is not the `license_file` line even though there are no other changes. However the issue goes away if those quotes are dropped (as in the last linked logs).

```
> conda build recipe --quiet
----------------------------------------------------------------------
Unable to parse meta.yaml file
Error Message:
--> while parsing a quoted scalar
-->   in "<unicode string>", line 35, column 19
--> found unknown escape character
-->   in "<unicode string>", line 35, column 22
Command exited with code 1
```

Example: https://github.com/conda-forge/jpeg-feedstock/pull/12
Failure: https://ci.appveyor.com/project/conda-forge/jpeg-feedstock/build/1.0.27
Passing: https://ci.appveyor.com/project/conda-forge/jpeg-feedstock/build/1.0.26

**Comment by mandeep** [comment]
Looks like a common YAML error to me.  Does the error still occur if you use the full file path instead of Jinja2?

**Comment by jakirkham** [comment]
We don't really know what the full path is. It's up to `conda-build` to tell us that.

That said, we are not seeing this error when building on macOS or Linux. Seems like something is peculiar on Windows specifically.
