### ISSUE TITLE
cannot remove folder from PATH in deactivate.d script

### ISSUE THREAD

**Issue by codingpoets** [conda/conda-build#2398]
When I add a folder to the PATH variable in the activate script (through activate.d) and remove it in the deactivate script (through deactivate.d) it seems to be stuck in the PATH. => adding works, removal does not
I am trying to use conda for managing our research software tools. Since some of them are written in Matlab I created a conda package for the Matlab Compiler Runtime environment to be set as a requirement/dependency for the tool. The MCR contains a set of directories as shown in the image below.

![grafik](https://user-images.githubusercontent.com/10432668/30810380-42abb364-a205-11e7-9556-a4651dff0b49.png)

I guess I could try and separate the different parts of it and put them in the corresponding directories in the conda environment, but I would rather keep the entire structure of the directory as it is so that I do not mess with any internal referencing. 
Thus my approach is to create a separate MCR directory, in the root of my conda (virtual-)environment where I can install different versions of the runtime environment. But in order to find the MCR during my tool execution, I need to add one of the directories to the system path (MCR/runtime/arch). On windows it includes some dlls and one executable.
That is why I use the activate.d and deactivate.d to add that path to the sytsem PATH when activating the environment.

My activate script looks is:
```
@echo off
REM for v91 there is only a win64 version available
pushd .
cd %~dp0\..\..\..
set MCRROOT91=%cd%\MCR\v91\runtime\win64
set PATH=%MCRROOT91%;%PATH%
popd
```

My deactivate script is:
```
@REM @echo off
SETLOCAL EnableDelayedExpansion
@REM remove MCRROOT91 path from the system path
CALL SET PATH="%%PATH:!MCRROOT91!;=%%"

ENDLOCAL & (
			SET MCRROOT91=
			ECHO %PATH%
			SET PATH=%PATH%
)
```

As I mentioned above, the activation works fine and I can execute the compiled Matlab tool as expected. I also see the additional environment variable MCRROOT91. But when after the deactivation of the environment the added path still appears in the system path variable. Every time I activate and deactivate the environment it adds an additional entry of that path to the system path variable. At first I throught that I did some mistake in the deactivation script - I am not a windows batch expert. But it seems to me that my removal of the path from the system path is simply overwritten by the main deactivation script. The path is properly removed in my deactivate script in etc/conda/deactivate.d as I can see from the `ECHO %PATH%` line. BTW, the MCRROOT variable is properly removed.

I also added a `ECHO "%PATH%"` to the main deactivate script (ROOTENV/Script/deactivate.bat) after the invocation of the sub deactivation script. From the output I can see that my changes do not have any effect.

![grafik](https://user-images.githubusercontent.com/10432668/30810530-ba8a1e5c-a205-11e7-9315-80feafa0cdb1.png)

Now my question is, would you take a different approach? Maybe there is there a better way to do this? Maybe there is an option to modifying the system path?

Additional information:
I run a Windows 7 64bit OS with Anaconda2 (32bit) installation.
The installed conda package versions are:

```
conda                     4.3.25                   py27_0
conda-build               3.0.15           py27h281fb7f_0
conda-env                 2.6.0                         0
```

Any kind of feedback is highly appreciated.

**Comment by msarahan** [comment]
I don't see anything obviously wrong with your deactivate.d stuff.  I'd guess it's probably just some annoying batch script detail that you need to work out.  I recommend copying your script out to standalone things and running them outside of conda to iterate on them more quickly.

You could copy stuff from your MCR/runtime/arch in Library/bin so that it would be on PATH right away, but I'm not sure if that might break the matlab stuff with whatever relative path finding they have.

**Comment by codingpoets** [comment]
Thank you for the quick reply. I did check the scripts individually and I thought they worked fine. But now that I checked again I realized that my deactivate script adds quotes around the path variable.
I seem to do that in line 4.

![grafik](https://user-images.githubusercontent.com/10432668/30814992-116c6336-a212-11e7-9996-da9c43382988.png)

I can remove them and then it works as expected in cmd window, but it gives some syntactical error when used as part of the de-/activation. Since the error message is in german here is the google translation.

> "\ PuTTY \" can not be processed syntactically at this point

I guess the syntax could be slightly different when called through another batch script.

I tried different variations including the one I found in the conda deactivation batch file.
The following deactivation works in cmd window but not through condas deactivate:

```
@REM @echo off
@SETLOCAL EnableDelayedExpansion
@REM remove MCRROOT91 path from the system path
@CALL SET "PATH=%%PATH:!MCRROOT91!;=%%"

@ENDLOCAL & (
	@SET "PATH=%PATH%"
	@SET "MCRROOT91="
)
```

**Comment by codingpoets** [comment]
I just simulated the conda deactivate script by taking the minimum parts I think are relevant for the issue.
I moved my deactivate script into a separate directory and used the following script to call it:
```
@SETLOCAL enabledelayedexpansion

@ENDLOCAL & (
	@PUSHD "deactivate.d"
	@FOR %%g IN (*.bat) DO @CALL "%%g"
	@POPD
	
	REM @SET "PATH=%PATH%"
)
```
This also works. But as soon as I uncomment the line which sets the PATH variable again, as done in the conde deactivate script line 51 (see screenshot), the path is reset.

![grafik](https://user-images.githubusercontent.com/10432668/30818538-1d6be0da-a21c-11e7-8ff3-6b42787faf65.png)

Don't you think this could be the problem? Maybe the local variable (from SETLOCAL) is used instead of the one I set/update in the deactivate script.

**Comment by mbargull** [comment]
I think the problem might be that in `deactivate.bat` we have
```batch
@SETLOCAL enabledelayedexpansion

@ENDLOCAL & (
          @SET "PATH=%PATH%"
)
```
where `ENDLOCAL` can remove the delayed expansion for the following code. The outcome is that `%PATH%` is set to the value set from before `ENDLOCAL`'s call but subsequent modifications to `PATH` will not be picked up because there is not delayed expansion (and we are inside a `( ... )` expression).

I will have to check that hypothesis and try out how to fix this. If I'm correct, then this is actually an issue for https://github.com/conda/conda instead of `conda-build`. cc @kalefranz

**Comment by codingpoets** [comment]
That would fit with my observations. Thank you for the update.
