### ISSUE TITLE
pre-link error with noarch package having noarch package dependency

### ISSUE THREAD

**Issue by kzuberi** [conda/conda-build#2401]
Creating a noarch conda package that depends on another noarch package results in
the following error at package installation time (package build succeeds):

```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'local::foo-0.1.0-pyh2a343f1_0'.
LinkError: pre-link script failed for package local::foo-0.1.0-pyh2a343f1_0
```

Using conda 4.3.25 and conda-build 3.0.19.

Changing either or both to arch dependent packages results in the install succeeding. Attached minimal example with instructions to reproduce, on the chance there's something incorrect with the way the packages are being setup: [conda_noarch_package_bug.zip](https://github.com/conda/conda-build/files/1334000/conda_noarch_package_bug.zip)

**Comment by jakirkham** [comment]
Is it just that pre/post-[un]link scripts don't work in `noarch` packages?

**Comment by jakirkham** [comment]
Is it possible to share the recipes or perhaps slimmed down versions of them in some GitHub repo somewhere?

**Comment by msarahan** [comment]
I don't honestly know how compatible pre-link scripts are with noarch packages.  Old-style noarch (noarch_python: True) uses pre-link scripts to install stuff.  New style noarch (noarch: python) does not have pre-link scripts - equivalent code is built into conda, and requires conda 4.3.  I have no idea if it works to mix old style and new style noarch.

**Comment by kzuberi** [comment]
For my own use case I switched to building an arch specific package along with using conda convert to build versions for the other platforms I'm interested in. 

@jakirkham if you are still interested in reproducing, the zip file attached to the original bug report contains a minimal example.

**Comment by hattne** [comment]
It's old, but I think this may still be an issue.

At least with conda-forge, it appears `noarch` packages are built on Linux, and they do seem to have the Linux pre-link scripts. However, the corresponding scripts for Windows do not appear to be included.

This leads to inconsistent behavior in that `noarch` packages with prelink scripts work on Linux and macOS but now Windows.
