### ISSUE TITLE
Should field values be sets?

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#2402]
Currently `conda_build.metadata.FIELDS` is a dict of lists, but would a better representation be sets? I imagine that repetition would be at best wasteful at worst cause some potential problems.

**Comment by msarahan** [comment]
Sure, mind submitting a PR?  This isn't code that changes much, and hasn't caused many issues that I know of.

**Comment by CJ-Wright** [comment]
Sure, this will break everything that does `.append` on the lists.

**Comment by msarahan** [comment]
fixed by #2403 - closing
