### ISSUE TITLE
Hashes lead to "garbage" packages

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2405]
In building the Anaconda 5.0 distribution with conda-build 3 and its hashes, we have come across an interesting problem.  The hashes are extremely sensitive.  They will change value:

  - When any dependency version (including hash) changes
  - When any input script changes (including comments!)
  - When any constraints are changed in meta.yaml

What we observed was that it was very easy to have something down low in the stack need a change, and for that change to then cause a cascade of “needed” rebuilds up the stack.  I quote “needed” because a rebuild isn’t necessarily needed.  If a rebuild is done, yes, you’ll get a new hash, but you don’t need to do a new build just because there’s a newer dependency.  The only time a rebuild would be necessary would be if the underlying dependency changed versions that would affect compatibility - either API or ABI.

Hashes are important for reproducibility.  When you build a package, conda-build records the exact ID’s for all the packages you use - names, versions, and build strings, including hashes.  While it might be true that building a package using dependency A with hash h1234567 is the same as building that package with dependency A with hash h7654321, there is no way for conda-build to generally know that.  Rather than have conda-build fight to discern what “relevant” information is, we punt and capture as much change as we can, and do no filtering whatsoever.  On the bright side, it’s much easier to reproduce packages.  On the other side, it’s easy to fill up channels with packages that are not necessarily in use, just by tweaking a given recipe little by little.

One thing that we bumped up against that definitely needs improvement: conda-build’s --skip-existing mode needs to ignore hashes.  Instead, it needs to grow the ability to compare two things: the package version, and the package variant set.  This will factor out hashes from causing unnecessary rebuilds.

If you don’t care about reproducibility, we’ll also be publishing tools that will help you trim software collections based on what is actually needed to install a (meta)package.  We’ll do this by recursively grabbing build, host, run, and test dependencies, but we’ll toss the hash information that gets recorded in the package, while keeping any other version constraints.

**Comment by rainwoodman** [comment]
This cascades and gets combinationally bad as packages are gradually updated. 

Hashing on a dependency that's not pinned is very different from the old way where only the pinned packages are hashed (a path that has been proved useful) By hashing on all dependency packages, you are ignoring the API compatibility commitment of all of the packages. I argue this is not good.

The pursue of reproducibility is important and fashionable, but it needs to stop after some point before it becomes impractical -- when software packages are API compatible it is probably easier to leave it up to the application bundler to seek and find the exact combination of software versions. (requirement.yaml) Rather, binary distributions shall probably focus on binary compatibility excluding the cominations that by definition won't work (pinning). The binary distribution tool makes it easier for the application bundler to achieve the reproducibility goals; but shall not do this directly. I suspect that the cascading issue you also acknowledge is suggesting that a two phase solution like this can be more efficient -- which was essentially the cb2 pinning rules.

I am posting here because after switching to CB3 our channel is full of these useless rebuilds --  Continuum.io can probably afford building these -- but I am not sure how we can survive the cascading rebuild issue without any real funding for build farms and  storage space. At least for us the approach here is reaching reproducibility at the cost of producibility.

**Comment by msarahan** [comment]
I would agree with you if the hashes only served the end of reproducibility.  Unfortunately, that's not their only purpose.  They also are necessary to support "variants" of packages - for example, packages built with different BLAS implementations, or different versions of a given dependency.  We use this right now for building packages against both hdf5 1.8 and 1.10, which are not binary compatible.  This helps us support more people by allowing older 3rd party packages to be used without requiring them to be recompiled.  In fact, this is why hashes were created in the first place.  Reproducibility was a benefit that we realized later.

We're working on this, but it will take time.  The key is that conda, not conda-build, needs a better way of knowing when two packages are equivalent.  On the conda-build side, this will boil down to what went into the recipe, in terms of what variables from conda_build_config.yaml actually played a role, and what their values were.  Conda needs to factor that into what it says is already available, and conda-build needs to respect that in ``--skip-existing``.

Whether ``--skip-existing`` becomes default behavior is a related question.  If it doesn't, then these "garbage" packages will continue to be created by default, even if conda understands that something equivalent exists.  If it does, then people need to understand that while developing recipes, they need to enable some flag to force rebuilds.  I don't know what the right answer is here.  I'm inclined to stick with existing behavior, and document that ``--skip-existing`` is more important in the context of hashed packages.  

I would also be in favor of a tool that helps people clean up garbage packages, by detecting "equivalent" packages, and keeping only the newest ones.

**Comment by rainwoodman** [comment]
1. I'd like to note that currently `--skip-existing` doesn't appear to understand the equivalence. 

2. What if hashes are only applied to variants packages and version pinning packages? I suppose part of the conda-build data model may need to be extended to extract propagate this information from the jinja template to the name generation, but it sounds like that's exactly the right amount of hashing to solve both issues.

**Comment by msarahan** [comment]
1. yes, this is a known issue.  Sorry if it wasn't clear from my post.
2. interesting idea.  I will need to think about this and would appreciate input from others (@mingwandroid, @kalefranz, @jjhelmus, @nehaljwani, and anyone else interested).  I like the potential simplicity, but going away from uniformity is heavy.  It's especially heavy across ecosystems.
3. I think the complexity is unavoidable.  We can't encode enough information in filenames.  It's just not extensible enough.  Yes, the hidden layer of equivalence will be harder to get right.  I am not convinced that there is any other way that also permits variants in a general way.

**Comment by msarahan** [comment]
We've discussed this internally and come up with the following plan:

A hash will be added if all of these are true for any dependency:
1. package is an explicit dependency in build, host, or run deps
2. package has a matching entry in conda_build_config.yaml which is a pin to a specific version, not a lower bound
3. that package is not ignored by ignore_version

If any of those are not true, that package will not contribute to a hash.  If no deps contribute to a hash, no hash will be added.

In the interests of binary stuff being reproducible, I think {{ compiler() }} stuff should pretty much always lead to a hash.  Shared library packages will always have a hash.  Numpy, scipy, scikit-learn, etc. will always have a hash.  Pure python packages, and python packages that use other hashed packages will mostly not have hashes.  So, while numpy will have a hash, something that uses only numpy's python interface (not its C interface; no compiler), will not have a hash.  Pytables will be built against different hdf5 versions, so it needs a hash.  Packages that use pytables and don't care which hdf5 version they use will not need a hash.

**Comment by jjhelmus** [comment]
I don't know if the inclusion of {{ compiler() }} in a recipe should always lead to a hash.  There are a number of Python packages with compiled extensions which a hash is unneeded as their interaction with other packages is only via Python.  For example psutil, pyyaml, wrapt, and pycosat all require a compiler but it is unlikely that variants of these packages would be required.  On windows the hash could be used to differentiate between Visual C++ builds which would be useful although the `vc` feature can provide this differentiation in the build string.

**Comment by msarahan** [comment]
My reasoning with the compiler always requiring a hash is that the compiler package represents compiler flags and other things that can and do dramatically change compatibility.  It is much more risky to drop this info (by dropping the hash) than it is for other software.

**Comment by rainwoodman** [comment]
For compatible ABI we shall only build against the lowest version of the dependency; producing one single hash.

**Comment by msarahan** [comment]
No, that's not how ABI works.  It's how *some* ABI works.  You can't build software against HDF5 1.8 and expect it to work with 1.10.  Hashes were created to support the use case where an ecosystem can support packages built against HDF5 1.8 and 1.10 simultaneously.

**Comment by rainwoodman** [comment]
HDF5 1.8~ <1.10 and 1.10+ have incompatible ABIs -- so a binary for 1.8 and a binary for 1.10. I missed 'for *each set of* compatible ABIs...' in the sentence to cause the confusion?

- Does conda support having both HDF5-1.8 and HDF5-1.10 installed the same time? Is there a plan for so? (This probably opens another can of worms) 

- Where does conda-build encode the knowledge that numpy 1.9 ~ 1.13 are all ABI compatible?

**Comment by msarahan** [comment]
> Does conda support having both HDF5-1.8 and HDF5-1.10 installed the same time? Is there a plan for so? (This probably opens another can of worms)

No.  What it does support, though, is having a downstream package, say pytables, built against both versions.  So we aren't constraining our entire ecosystem to a single hdf5 version, but allowing parallel individual self-consistent sub-ecosystems.

> Where does conda-build encode the knowledge that numpy 1.9 ~ 1.13 are all ABI compatible?

``{{ pin_compatible('numpy') }}`` results in a runtime dependency of something like ``numpy  >=1.9.3,<2.0a0``  It is up to you to define the exact bounds of that expression.  The default is exact lower bound for what is used at build time, and upper bound less than the next major version.  See the blog post at https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/ for more information.
