### ISSUE TITLE
Enhancements slated for conda index

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#2407]
- [ ] Update mechanism for package metadata, without changing package contents (and md5 hashes).  Draft spec at https://gist.github.com/jjhelmus/bf9489e3847d8e1737afca7d04b2f66d
- [x] Version 2 format for channel-level metadata.json file, possibly renamed. Draft spec and discussion at https://github.com/conda/conda/issues/5340
- [ ] RSS feed generation for repodata diffs.
- [x] Add index.html creation to conda index.  https://github.com/conda/conda-build/pull/2395

**Comment by kalefranz** [comment]
channel-level metadata.json done in https://github.com/conda/conda-build/pull/2463

**Comment by kalefranz** [comment]
xref: https://github.com/conda/conda/issues/4956

**Comment by kiwi0fruit** [comment]
I investigated possibility to pin packages of fixed versions with sha256 hashes. So I open this issue: https://github.com/conda/conda/issues/7882

After I thought about it and read through this #2407 issue I'm curious what is simpler to implement: additional metadata per channel or new additional conda package format like in https://github.com/conda/conda/issues/7882#issuecomment-431643062 ?
