### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64: ['gcc_linux-64']

### ISSUE THREAD

**Issue by AntoineD** [conda/conda-build#2416]
I am trying to use the build requirement {{ compiler('c') }} (anaconda2 4.4.0 on RH5) instead of gcc, but I get an error even with the minimal meta.yaml:
```
    package:
      name: cross
      version: 1.0
 
    requirements:
      build:
        - {{ compiler('c') }}
```
I get:
```
Attempting to finalize metadata for test INFO:conda_build.metadata:Attempting to finalize metadata for test

Leaving build/test directories:
  Work:  ../../../../../scratch/conda-bld/work
  Test:  ../../../../../scratch/conda-bld/test_tmp
Leaving build/test environments:
  Test: source activate  ../../../../../scratch/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
  Build:        source activate  ../../../../../scratch/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


Traceback (most recent call last):
  File "/scratch/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1771, in build_tree
    notest=notest,
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 881, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 543, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 1757, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 638, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 289, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 112, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/scratch/anaconda/lib/python2.7/site-packages/conda_build/environ.py", line 681, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['gcc_linux-64']
```

**Comment by mingwandroid** [comment]
RH5 cannot use the new compilers as it is too old. We target CentOS6 now.

**Comment by mingwandroid** [comment]
It is possible for us to build CentOS5-targeting compilers but it would be a lot of work. If you were interested in this you should email sales@anaconda.com

**Comment by AntoineD** [comment]
What do you mean by _new_ compiler?

**Comment by mingwandroid** [comment]
We rebuilt all of AD5 using compilers we built from scratch. gcc_linux-64 is one of core packages of those compilers. They were built on CentOS6 and to target CentOS6.

**Comment by AntoineD** [comment]
I am staying on the RH5 compatible channel as described [here](https://github.com/conda/conda/issues/6041), and I can use the gcc package from there but still not compiler('c').
Is compiler('c') using a package different from gcc and not compatible with RH5?

**Comment by msarahan** [comment]
compiler('c') is a conda build 3 expression. You can see more about how it works in conda build's jinja_context.py file. It has two parts: compiler package base name (gcc) and target platform. Each platform has a default compiler package base name. The target platform is the same as the native platform by default.

What you need in order for this to work is to create a very simple meta package, gcc_linux-64, that has only one run requirement: gcc

You can also use a conda_build_config.yaml file to set c_compiler and target_pkatform to arbitrary values, but I don't think there's currently a way to have no target platform at all.

Sorry to impose this burden on you, but our recipes are not guaranteed to be immediately usable anywhere other than what we build for.

**Comment by AntoineD** [comment]
Thanks a lot for the explanations an suggestions. 👍
In my context, would there be any benefit under the hood to create the meta package?
Or is it just cosmetic? (still in my context)

**Comment by msarahan** [comment]
If you want to use our recipes, all of which use the {{ compiler() }} function, you'll need to create the metapackage.  The change here is the up to now, compilers were implicit.  Now they're explicit.  If you can't use our compilers, you need to provide another way of having the compiler provided explicitly.

**Comment by msarahan** [comment]
PS: lots more docs on the topic at https://docs.google.com/document/d/103QY204eD82fJzpT7eXy_rV2bKwe6Hx5uAnkMg_xwkI/edit?usp=sharing

**Comment by AntoineD** [comment]
Thx again, closing the issue.
