### ISSUE TITLE
Silence the INFO:filelock:Lock

### ISSUE THREAD

**Issue by j3mdamas** [conda/conda-build#2421]
Hi,

When running `conda build` on travis machines I am having a lot of these log info messages:

```
INFO:filelock:Lock 140222368435224 acquired on /home/travis/miniconda/locks/L2hvbWUvdHJhdmlzL21p
```

When building locally, I do not have them. Travis particularities or some verbose mode I can silence? The `-q` flag did not seems appropriate for this.

**Comment by msarahan** [comment]
fixed by #2418, will be part of 3.0.24.  If you'd like to backport this to 2.1.x, PRs welcome.

**Comment by msarahan** [comment]
3.0.25 is out on the main channel.  Closing.

**Comment by j3mdamas** [comment]
Thanks, I will see how it's going in conda 3

**Comment by j3mdamas** [comment]
Perfect! Thanks a lot @msarahan
