### ISSUE TITLE
Could sh/bash -x tracing be made optional (or disabled) when running 'conda build'?

### ISSUE THREAD

**Issue by maddenp** [conda/conda-build#2425]
The voluminous traces obscure the useful console output.

```
% conda build --version
conda-build 3.0.23
```

**Comment by msarahan** [comment]
Fine by me. @mingwandroid?

Maybe this can be affected by the--debug flag?

**Comment by mingwandroid** [comment]
Sounds good to me

**Comment by msarahan** [comment]
Closing as fixed by #2426.  Thanks @maddenp
