### ISSUE TITLE
pip error: TypeError: '>' not supported between instances of 'Version' and 'SetuptoolsVersion'

### ISSUE THREAD

**Issue by cateee** [conda/conda-build#2444]
After some updates of conda (last months it worked, python 3, I think only after some update around 3.6.3), when I do `pip list --local --format=columns --outdated` I get the following trace:

    $ pip list --local --format=columns --outdated
    Exception:
    Traceback (most recent call last):
      File "D:\Anaconda\envs\RH2\lib\site-packages\pip\basecommand.py", line 215, in main
        status = self.run(options, args)
      File "D:\Anaconda\envs\RH2\lib\site-packages\pip\commands\list.py", line 157, in run
        packages = self.get_outdated(packages, options)
      File "D:\Anaconda\envs\RH2\lib\site-packages\pip\commands\list.py", line 168, in get_outdated
        dist for dist in self.iter_packages_latest_infos(packages, options)
      File "D:\Anaconda\envs\RH2\lib\site-packages\pip\commands\list.py", line 169, in <listcomp>
        if dist.latest_version > dist.parsed_version
    TypeError: '>' not supported between instances of 'Version' and 'SetuptoolsVersion'

This weeks and last week `conda update --all` (both in root and in virtenv) doesn't solve the issue. I just have two packages outside conda (so just in pip).

    $ conda --version
    conda 4.3.29

selected package version:

    pip                       9.0.1            py36hadba87b_3    defaults
    python                    3.6.3                h9e2ca53_1    defaults

**Comment by msarahan** [comment]
Sorry, I don't see how this is related to conda-build.  Please file an issue on the anaconda-issues tracker: https://github.com/continuumIO/anaconda-issues

Note that here the issue may be remnants of an old pip package remaining.  We have seen related issues on Windows with our efforts to un-vendor pip (out of concerns for path length issues).  The only fixes are to either figure out the legacy files and remove them, or do a fresh, clean install of anaconda.

**Comment by timeregained** [comment]
I met the same issue and I have tested to make a clean install of anaconda 5.0.1 in a whole new windows 10 1709, the issue continues without any luck.

**Comment by E3V3A** [comment]
Try:
```bash
pip3 install --ignore-installed pip --user
```
