### ISSUE TITLE
Simple typos are met with silence

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-build#2452]
If I mistype the name of my conda build recipe directory, _and_ my source/build intermediaries directory is empty, `conda build <typo>` just exits. No error message, no warning, just silence.

And if the source/build intermediaries directory is _not_ empty, I get something like this:
```



####################################################################################
Source and build intermediates have been left in /Users/mgrant/miniconda3/conda-bld.
There are currently 3 accumulated.
To remove them, you can run the ```conda build purge``` command
```
The user really needs some sort of affirmative error or warning in this case. Specifically, if someone types `conda build <blah>` and there are no matches, it needs to say so, so the user realizes something has been mistyped. 

I just spent quite a bit of time with a customer on this one. I could not for the life of me reproduce what he was seeing, until I finally got him to send me a screenshot! ;-)

**Comment by msarahan** [comment]
What conda-build version?  I think this is addressed in 3.x, but may need to be backported to 2.1.x if a customer needs that.

**Comment by mcg1969** [comment]
I thought I tested this on 3.x too---but now I realize I didn't---but he's definitely running 2.x.
