### ISSUE TITLE
unexpected differences in test and run environments / unexpected info in package

### ISSUE THREAD

**Issue by maddenp** [conda/conda-build#2454]
(I posted this to the conda mailing list last week and have received no responses, so I thought I'd vet it here as a possible issue. I can't tell if the problem is with `conda build` or `conda create` -- or an error on my part.)

I am confused by conda's behavior in regard to dependencies when building packages vs installing them into environments. I hope I'm just misunderstanding or doing something wrong, and would be grateful for advice.

Preliminaries:

```
% conda list | grep "conda "
conda                     4.3.29           py36ha26b0c0_0

% conda list | grep "conda-build "
conda-build               3.0.25           py36hd2c3b30_0

% cat meta.yaml 
package:
  name: condatest
  version: '0.0.1'

requirements:
  run:
    - python 2.7.14
    - numpy 1.13.0.*

% cat run_test.sh 
true

% cat ~/.condarc
channels:
  - foobar
```
First, I build my package. In the following block, note that the test environment is constructed with `numpy` from `conda-forge`, which is what I would expect given the `--channel` flags I use. In fact, this is exactly the package list I would expect.
```
% conda build --channel conda-forge --channel defaults --override-channels .
Attempting to finalize metadata for condatest
INFO:conda_build.metadata:Attempting to finalize metadata for condatest
BUILD START: ['condatest-0.0.1-h2acfc42_0.tar.bz2']
source tree in: /home/pm/miniconda/conda-bld/condatest_1507909621554/work
Packaging condatest
INFO:conda_build.build:Packaging condatest
Packaging condatest-0.0.1-h2acfc42_0
INFO:conda_build.build:Packaging condatest-0.0.1-h2acfc42_0
number of files: 0
Fixing permissions
Fixing permissions
updating: condatest-0.0.1-h2acfc42_0.tar.bz2
Updating index at /home/pm/miniconda/conda-bld/linux-64 to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/pm/miniconda/conda-bld/linux-64 to make package installable with dependencies
Updating index at /home/pm/miniconda/conda-bld/noarch to make package installable with dependencies
INFO:conda_build.build:Updating index at /home/pm/miniconda/conda-bld/noarch to make package installable with dependencies
TEST START: /home/pm/miniconda/conda-bld/linux-64/condatest-0.0.1-h2acfc42_0.tar.bz2
Renaming work directory,  /home/pm/miniconda/conda-bld/condatest_1507909621554/work  to  /home/pm/miniconda/conda-bld/condatest_1507909621554/work_moved_condatest-0.0.1-h2acfc42_0_linux-64

The following NEW packages will be INSTALLED:

    blas:            1.1-openblas                  conda-forge
    ca-certificates: 2017.7.27.1-0                 conda-forge
    certifi:         2017.7.27.1-py27_0            conda-forge
    condatest:       0.0.1-h2acfc42_0              local      
    libgfortran:     3.0.0-1                                  
    ncurses:         5.9-10                        conda-forge
    numpy:           1.13.0-py27_blas_openblas_200 conda-forge [blas_openblas]
    openblas:        0.2.19-2                      conda-forge
    openssl:         1.0.2l-0                      conda-forge
    pip:             9.0.1-py27_0                  conda-forge
    python:          2.7.14-0                      conda-forge
    readline:        6.2-0                         conda-forge
    setuptools:      36.3.0-py27_0                 conda-forge
    sqlite:          3.13.0-1                      conda-forge
    tk:              8.5.19-2                      conda-forge
    wheel:           0.30.0-py_1                   conda-forge
    zlib:            1.2.8-3                       conda-forge

[...]

+ /bin/bash -x -e /home/pm/miniconda/conda-bld/condatest_1507909621554/test_tmp/run_test.sh
+ true
TEST END: /home/pm/miniconda/conda-bld/linux-64/condatest-0.0.1-h2acfc42_0.tar.bz2

[...]
```
The local package was built, so now I create an environment using only this package:
```
% conda create --channel conda-forge --channel defaults --override-channels --name condatest --use-local --yes condatest
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/pm/miniconda/envs/condatest:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.7.27.1-0      conda-forge
    certifi:         2017.7.27.1-py27_0 conda-forge
    condatest:       0.0.1-h2acfc42_0   local      
    mkl:             2017.0.3-0                    
    ncurses:         5.9-10             conda-forge
    numpy:           1.13.0-py27_0                 
    openssl:         1.0.2l-0           conda-forge
    pip:             9.0.1-py27_0       conda-forge
    python:          2.7.14-0           conda-forge
    readline:        6.2-0              conda-forge
    setuptools:      36.3.0-py27_0      conda-forge
    sqlite:          3.13.0-1           conda-forge
    tk:              8.5.19-2           conda-forge
    wheel:           0.30.0-py_1        conda-forge
    zlib:            1.2.8-3            conda-forge

mkl-2017.0.3-0 100% |###| Time: 0:00:09  14.82 MB/s
numpy-1.13.0-p 100% |###| Time: 0:00:00  14.80 MB/s

[...]
```
Note that, now, `numpy` from `defaults` was installed, along with `mkl`. Why? I wouldn't expect different packages to be used in the test environment than are used in an environment created solely based on this package. Does the order of the `--channel` flags have no meaning? I would have expected for position to indicate priority but, even if that's not true, I would have expected the same set of packages in both environments.

Am I doing it wrong, or missing something?

Also, if I look inside my package's `about.json` file, I see:
```
  "channels": [
    "foobar",
    "conda-forge",
    "defaults"
  ],
```
I don't know how this JSON document is used, but I'm surprised that info from my `.condarc` (i.e. the bogus `foobar` channel) has been recorded here, given my use of the `--override-channels` switch. I would have hoped that information from my `.condarc` would not be leaked into the package.

Thanks in advance for any help.

**Comment by msarahan** [comment]
about.json is strictly informational.  It's not used in environment creation.

I think the strangeness you're seeing is that ``--override-channels`` is either not working, or not working quite the same way between conda and conda-build.

My only other idea here is that the order of the channels may not be maintained somehow?  The priority for channels specified on the command line is the order given (left has highest priority)

> -c CHANNEL, --channel CHANNEL
              Additional  channel  to  search  for  packages.  These  are URLs
              searched in the order they  are  given  (including  file://  for
              local directories). Then, the defaults or channels from .condarc
              are searched (unless --override-channels is given). You can  use
              'defaults'  to  get the default packages for conda, and 'system'
              to get the system  packages,  which  also  takes  .condarc  into
              account.  You  can  also  use  any  name  and the .condarc chan‐
              nel_alias value will be prepended. The default channel_alias  is
              http://conda.anaconda.org/.

https://conda.io/docs/commands/conda-install.html

Given that spec, it looks to me like conda-build is behaving as documented, but conda is not.  Have you tried omitting ``--override-channels``?  It seems very strange to me that you are both including that flag, and then also adding defaults as a channel.

**Comment by jjhelmus** [comment]
`--override-channels` has been broken for some time, conda/conda#/5158.  I am not aware of a workaround at this time.

**Comment by maddenp** [comment]
Thanks @jjhelmus -- I ran into that issue at some point but wasn't sure if it was the cause of the behavior I'm seeing. I see that this was added to a milestone two days ago, so that's a hopeful sign.

@msarahan:

> Have you tried omitting --override-channels? It seems very strange to me that you are both including that flag, and then also adding defaults as a channel.

I just checked and the behavior is the same when I omit `--override-channels`, presumably because the switch is broken.

Going by the switch's description -- "Do not search default or .condarc channels." -- I assume that I _must_ include `--channel defaults` if I want `defaults` to be searched. And I suspect that, when `--override-channels` is fixed, omitting `--override-channels` would make my `conda create` command without `--channel defaults` fail, since the environment (either the `conda build` test one, or the `conda create` one) requires packages from `defaults`. At least I'd hope so -- it seems like that's the common-sense reading of that switch's purported behavior. Am I wrong?

> about.json is strictly informational. It's not used in environment creation.

As you say, it doesn't seem to affect environment creation, but if I had e.g. local `file://` channel URLs in my `.condarc`, I probably wouldn't want them to appear in packages I'd upload to public channels, as they might expose private information. Now that I know this, of course, I could just delete my `.condarc` before building packages, but IMHO this information appearing in the package is surprising, unwanted behavior.

Also, is there any benefit to looking at the channels specified in `.condarc` when `--override-channels` ("Do not search default or .condarc channels.") is specified? What good could that do? It seems like only a vector for bugs.

That's just my $.02 on that, for what it's worth. Please feel free to disregard and close if you don't consider it an issue. I have a workaround.
