### ISSUE TITLE
unexpected RUNPATH instead of RPATH

### ISSUE THREAD

**Issue by speleo3** [conda/conda-build#2456]
conda build should call `patchelf --remove-rpath` before `patchelf --force-rpath`. The reason is inconsistent behavior of patchelf, namely that RUNPATH isn't cleared. See NixOS/patchelf/issues/94.

Current Anaconda releases have RUNPATH in the qt libraries, see ContinuumIO/anaconda-issues/issues/6783.

**Comment by mingwandroid** [comment]
I would rather not have `conda-build` do this. I'm sure there's some valid use cases (ok, I cannot think of them).

IMHO `conda-build` should report these things as errors (with a way to ignore it, like `no-error-dt-runpath`) and the software should be patched and the patches upstreamed.

**Comment by speleo3** [comment]
No RUNPATH in latest Anaconda release. Closing this issue.
