### ISSUE TITLE
Different Package Build Names between two machines

### ISSUE THREAD

**Issue by seahawks8** [conda/conda-build#2461]
I have a custom package that my friend and I have built.
however when I build the package 

- apples-0.1.1-py35hcdf5662_0.tar.bz2 (first build)
- apples-0.1.1-py35h87895c6_0.tar.bz2 (more recent build)

however, when my friend builds the package on his machine, he gets

- apples-0.1.1-py35_0.tar.bz2

and when I run index on the local channel I have, it does not recognize the package he built as the latest,

wondering why it is doing this?

thank you so much,
Doug

**Comment by groutr** [comment]
Are you both using the same version of conda-build?

**Comment by msarahan** [comment]
This might help explain everything you're seeing.
https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/
