### ISSUE TITLE
Conda-skeleton cpan error - "corelist" is missing

### ISSUE THREAD

**Issue by npavlovikj** [conda/conda-build#2464]
Hi,

I am trying to create a conda recipe for a perl module. When I type:
**$ conda-skeleton cpan File::Copy::Link**
I get the error "**FileNotFoundError: [Errno 2] No such file or directory: 'corelist'**".
I am using "conda-build 2.1.16", but the same occurred for "conda-build 3.0.27" as well.

I would appreciate if you can help me fix this issue.

Thank you,
Natasha

**Comment by mandeep** [comment]
I believe this was fixed in 3.0.28. Are you able to update?

**Comment by npavlovikj** [comment]
Many thanks @mandeep ! I just updated "conda-build" to 3.0.28, and I was able to successfully built the "perl" recipe with "conda-skeleton".

**Comment by mandeep** [comment]
Glad it works! 😃
