### ISSUE TITLE
suppress filelock:Lock INFO messages?

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#2465]
Is there some way to get rid of this bumf?

INFO:filelock:Lock 4580648400 acquired on /var/folders/cg/k_rflgw13pjf4m8sw_gnnrl80000gp/T/miniconda2/locks/L3Zhci9mb2xkZXJzL2Nn

If not, there should be.

**Comment by msarahan** [comment]
update conda-build.

**Comment by janssen** [comment]
Thanks.  Something keeps downgrading it to 3.0.10.  Got to find that next.
