### ISSUE TITLE
conda-convert for IBM Power architecture

### ISSUE THREAD

**Issue by electronwill** [conda/conda-build#2471]
Our continuum-docs package contains html and data files but no running code. Currently we build it on macOS and then use conda-convert to make packages for 32 and 64 bit Linux and Windows. Would be good to make it available to Power users as well.

(There was another request at https://github.com/conda/conda-build/issues/834 for conda-convert on armv7l.)

**Comment by mandeep** [comment]
Shouldn't be a problem. I think the only things that need to change when converting from macOS to ppc64le would be the ``arch`` and ``subdir`` in index.json.

**Comment by jjhelmus** [comment]
I'll add `armv6l`, `armv7l` and `aarch64` to the list of platforms for conda convert to target.  The full list of platforms conda currently is aware of is in [constants.py](https://github.com/conda/conda/blob/49cc9ff6faf43759c77afbd66c46c8838da635e6/conda/base/constants.py#L50-L61)

**Comment by electronwill** [comment]
Hm... linux-ppc64le linux-armv6l linux-armv7l and linux-aarch64 seem to be on that list currently on the branches master, 4.3.x, and 4.4.x, and they all say the file hasn't been changed in several days. However, when I updated conda to 4.3.30 and conda-build to 3.0.28 and ran "conda-convert -p all filename" I got linux-32 and linux-64 but nothing labeled as ppc64le. Was I just using the wrong command?

**Comment by mandeep** [comment]
The ``all`` flag will pull the architectures from here:

https://github.com/conda/conda-build/blob/master/conda_build/convert.py#L708

**Comment by electronwill** [comment]
Thank you!

Should "-p ppc64le" be working now, or will that take more work to enable?

```
~$ conda-convert ~/miniconda3/conda-bld/osx-64/continuum-docs-2.0.17-h215ba9a_0.tar.bz2 -p linux-ppc64le
usage: conda-convert [-h] [-p {osx-64,linux-32,linux-64,win-32,win-64,all}]
                     [--dependencies [DEPENDENCIES [DEPENDENCIES ...]]]
                     [--show-imports] [-f] [-o OUTPUT_DIR] [-v] [--dry-run]
                     [-q]
                     files [files ...]
conda-convert: error: argument -p/--platform: invalid choice: 'linux-ppc64le' (choose from 'osx-64', 'linux-32', 'linux-64', 'win-32', 'win-64', 'all')
~$
```

**Comment by mandeep** [comment]
I'm working on a PR now to incorporate this. There are a few changes that need to be made to the code apart from the list of platforms.

**Comment by electronwill** [comment]
Great! Sorry for the noise.
