### ISSUE TITLE
Defining package name using load_setup_py_data no longer permitted

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2475]
I seem to recall this was possible at one point in time. Though admittedly this was about a year and a half ago. So my recollection could be faulty and/or many other things could have affected this since.

In any event, it would be nice to be able to set the package name again by simply using `load_setup_py_data` like in the code snippet for the `meta.yaml` below.

```jinja
 {% set data = load_setup_py_data() %}
 
 package:
   name: "{{ data.get('name') }}"
```

**Comment by msarahan** [comment]
I would accept a PR, but have no intention to fix this otherwise.  The name is something that gets used in several places, and leaving it for eventually being there makes a lot of stuff more hairy.  Sorry for any inconvenience.
