### ISSUE TITLE
Allow PROCESSOR_ARCHITECTURE env var in windows

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2479]
Some software like CMake looks at this env variable.

**Comment by msarahan** [comment]
Already in 3.x: https://github.com/conda/conda-build/blob/c119bd2b799a742fff5fbb5681dfda71233ec8c9/conda_build/environ.py#L495

PRs to backport to 2.1.x welcome, but I'm not going to do that work myself.

**Comment by isuruf** [comment]
Ah, thanks. 

> PRs to backport to 2.1.x welcome, but I'm not going to do that work myself.

I thought 2.1.x was abandoned after waiting for https://github.com/conda/conda-build/pull/2348

**Comment by isuruf** [comment]
ping @msarahan, is 2.1.x still maintained?

**Comment by msarahan** [comment]
I don't have time to revisit it right now.  If anyone wants to run tests themselves and tell me that it's fixed, I can tag a release.  I have less than zero time for debugging anything that's wrong with it.
