### ISSUE TITLE
Error while installing Anaconda on windows 7

### ISSUE THREAD

**Issue by jatin759** [conda/conda-build#2491]
![error](https://user-images.githubusercontent.com/32077264/32698493-e99127d0-c7cc-11e7-888d-ca5d687faeed.PNG)

The above error is shown each time while installing anaconda. I have already installed Python 3.6 on my PC

**Comment by msarahan** [comment]
This is not a conda-build error.  Closing.  You should search https://github.com/continuumio/anaconda-issues for this problem.
