### ISSUE TITLE
conda build --no-test/--test looking for different package hashes

### ISSUE THREAD

**Issue by stuartarchibald** [conda/conda-build#2499]
I've been chasing down bugs in the Numba build system, I noted that build steps ran like:

1. `conda build  <recipe> --output` gives a package name with a hash.
2. `conda build <recipe> --no-test` builds a package with that hash.
3. `conda inspect hash-inputs <package>` shows what was used to create that hash.
4. `conda build  <recipe> --test` looks for a package with a different hash from that which was built and described in `--output`.

After some discussion with @mingwandroid it transpired that the hash for the built package was possibly being influenced by the inclusion of test files or similar? The work around was to simple pass the known built package name to `conda build --test`, however the above pattern used to work and probably ought to still work.

To reproduce, using https://github.com/numba/llvmlite/pull/315, build the recipe in ` conda-recipes/llvmdev` on linux x86_64 first with `--no-test` then with `--test`.

Further, it may be useful perhaps to make it so that `conda inspect hash-inputs` works on a source directory so that the hash/package name reported by `conda build --output` can be compared to that of a created package (assuming that the problem is diagnosed correctly above)?

**Comment by msarahan** [comment]
Yes, this has been a difficult recurring issue.  Sorry it's still not working for you.  I'll look into it.

**Comment by msarahan** [comment]
@stuartarchibald and I discovered that this was because script_env was in use, and similar values were not used at build time and test time.  We're documenting this as a requirement when using ``--no-test`` to split build and test.
