### ISSUE TITLE
conda build recipe problem

### ISSUE THREAD

**Issue by anitakh1** [conda/conda-build#2514]
while running 'conda build recipe' for simpleitk in anaconda on ubuntu,
when it come to cloning into bare repository, it says unable to connect to itk.org. my internet connection are there but this code is not getting executed. please help

**Comment by msarahan** [comment]
Sorry, we can't help you debug internet connection issues.  Please triple-check that the URL is valid and that itk.org wasn't undergoing some temporary availability issues.
