### ISSUE TITLE
Outputs section does not allow to override binary_relocation setting?

### ISSUE THREAD

**Issue by anton-malakhov** [conda/conda-build#2519]
I want to use single recipe for single repository of TBB library in order to produce `tbb`, `tbb-devel`, and `tbb4py` packages running single conda-build command. They do share common build process and can benefit from being placed into single recipe. However, as TBB takes care of itself for RPATH and other relocation-related questions, I want to disable any binary patching for TBB native binaries but I still want regular conda way for Python module for TBB. This possibly can be solved by providing a list of files in the global build section.. but it is not convinient enough even if works as I want to separate all the knowledge about internal package structure to a build script leaving conda recipe with higher-level packaging questions.

It's rather minor issue as I managed to redefine everything else necessary to be different between output packages: entry_points, run_exports, features, and about sections. Overall, multiple outputs is very useful feature, thanks!

**Comment by msarahan** [comment]
I'm not sure if you're aware, but as of pretty recent versions (maybe 3.0.27 or so), you can use the "build" section wholesale on any output.  Taking individual keys and passing them through was just too annoying.  The individual key pass-through will be deprecated in favor of "mini-meta.yaml" sections: each output can have its own full ``requirements``, ``build``, ``test``, and ``about`` sections.  They can't have their own ``source`` or ``outputs`` section.  The ``package`` section is the only thing that remains something of a pass-through, with its keys being mapped more directly onto the output.

That *might* be what you need for your desired customization.  Please let me know if it still isn't enough.

**Comment by anton-malakhov** [comment]
Right! I was using conda-build 3.0.19.. sorry for not checking it first. Does it mean that outputs/build/script will work the same way as global build/script? meaning that issue #2512 is not relevant anymore?

**Comment by anton-malakhov** [comment]
No, it is still relevant as outputs/build/script is ignored as well as outputs/test/imports and commands :(
At least, binary_relocation, run_exports, entry_points, and features found a better place - all these work well in outputs/build section

**Comment by msarahan** [comment]
Yeah, sorry.  I hadn't anticipated that use for it.  I think it may be easier to plumb that into working than it would be to repurpose the other script entry.  I'll try that as a shorter-term solution.
