### ISSUE TITLE
conda-build section of .condarc does not recognize environment variables

### ISSUE THREAD

**Issue by akovner** [conda/conda-build#2521]
I have a multi-user conda installation, and I tried the following .condarc entry:

    conda-build:
        root-dir: /path/to/dir/$USER

based on the behavior of other .condarc entries (such as pkgs_dirs & envs_dirs) the environment variable should populate correctly, but it does not.

**Comment by msarahan** [comment]
Yes, conda does nothing special for conda-build entries in condarc.  This would be nice to fix, but I'm afraid I don't have much time to do it myself right now.  If you'd like to submit a PR, I'd be happy to review it.

**Comment by msarahan** [comment]
fixed by #2563
