### ISSUE TITLE
[question] gcc 7.2 conda packages are installed on a Ubuntu 16.04.3 LTS with gcc 5.4

### ISSUE THREAD

**Issue by anton-malakhov** [conda/conda-build#2530]
I added cxx compiler into my requirements:
```
requirements:
  build:
    - {{ compiler('cxx') }} # [unix]
 ```
However, neither my conda_build_config.yaml nor command line specify version of the compiler - I'd assume it should be deducted from the environment.
So, on Ubuntu 16.04.3 LTS, I got errors like `g++: error: unrecognized command line option ‘-fno-plt’`.
This probably happens because of these packages:
```
The following NEW packages will be INSTALLED:

    binutils_impl_linux-64: 2.28.1-h04c84fa_2
    binutils_linux-64:      7.2.0-hc67e822_15
    ca-certificates:        2017.08.26-h1d4fec5_0
    certifi:                2017.11.5-py36hf29ccca_0
    gcc_impl_linux-64:      7.2.0-hc5ce805_2
    gcc_linux-64:           7.2.0-haf1f6fa_15
    gxx_impl_linux-64:      7.2.0-hd3faf3d_2
    gxx_linux-64:           7.2.0-h2e50c1c_15
```
while `gcc --version` says `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609`

While, deducting versions from environment would be nice to have, this is rather a question than a feature request since I did not find a good illustrative example how to handle this situation, please advise.

**Comment by msarahan** [comment]
It's actually best to not have system compilers installed when using our compilers (and that's what you're doing when you leave the default values for the compilers).

Please read https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/ if you haven't already.

What you'll see is that there is no g++ executable in our packages.  Instead, there's a prefixed one, like x86_64-conda-linux-g++.  We set environment variables that most (sane) build systems respect: CC, CXX, etc.  If your build systems aren't respecting those env vars, you should fix your build system.

**Comment by anton-malakhov** [comment]
Thank you, Mike! that helped!
