### ISSUE TITLE
Suggestion: hard link working files if source files are lying on the same file system.

### ISSUE THREAD

**Issue by marscher** [conda/conda-build#2536]
Conda does a great job linking package files across environments. Can't we use the same feature in conda-build, if the source files are given by a path directive? This would greatly reduce build times and lower disk usage.

**Comment by msarahan** [comment]
Sure, good idea.  I'd gladly take a PR that implemented this.  I personally am too busy with getting conda-forge up and running with conda-build 3 right now.

**Comment by marscher** [comment]
On 05.12.2017 04:54, Mike Sarahan wrote:
> Sure, good idea.  I'd gladly take a PR that implemented this.  I personally am too busy with getting conda-forge up and running with conda-build 3 right now.
> 

I can look into, when I have time. Good luck with cf and conda-build-3!

**Comment by marscher** [comment]
Actually this would break a lot of assumptions like build isolation. Thinking of the build is progress and some process modifies a linked file in the originating tree.
