### ISSUE TITLE
source_files not working during build when a folder recipe_folder/../test exists

### ISSUE THREAD

**Issue by kuepe-sl** [conda/conda-build#2550]
Conda build is unable build packages that contain "test source_files" located inside of a `test` folder, when the `test` folder exists in the parent directory of the recipe. It will quit with the following exception  
`RuntimeError: ('Did not find any source_files for test with pattern %s', 'test')`

The bug was introduced by commit 66b7d852aa5a60379a89372189d598406e035281.
The reason is that the variable `pkg_test_files_path` is set to `recipe_folder/../test`, which is correct while testing but not while building and thus it searches for the test files in the wrong directory.

I attached a small project that demonstrates the issue.
[testproject.zip](https://github.com/conda/conda-build/files/1538737/testproject.zip)

**Comment by msarahan** [comment]
Thanks.  I cut down your example to get rid of the cmake stuff, so that the tests don't get too bogged down.  I think it still keeps your fundamental issue, and I could reproduce it.  I tried to fix it with #2551.

**Comment by msarahan** [comment]
3.1.2 is available with this fix.

**Comment by kuepe-sl** [comment]
CB 3.1.2 works like a charm! Thanks!
