### ISSUE TITLE
Build string hashes are missing

### ISSUE THREAD

**Issue by jhunkeler** [conda/conda-build#2554]
conda-build `>=3.1.0` no longer generates packages with hashes in the build string. Building the same recipe under `3.0.31` produces a package containing a hash.

Is this behavior considered a regression or an improvement?

# conda_build_config.yaml

```yaml
python:
  - 3.6
  - 3.5
  - 2.7

numpy:
  - 1.13
  - 1.12

pin_run_as_build:
  python:
    max_pin: x.x
  numpy:
    min_pin: x.x
```

The `aprio` recipe below does not depend on `numpy`. The build matrix above explodes under the latest conda-build because the resulting package name end up being the "same" (i.e. no hash, no `npXY`, nothing is unique) so in effect, the resolver ends up eating its own tail while looking for dependencies.

# Before...

## 3.0.3
```
conda build --output aprio
Attempting to finalize metadata for aprio
INFO:conda_build.metadata:Attempting to finalize metadata for aprio
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py27ha356f7f_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py35h79c1544_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py36h1a08477_0.tar.bz2
```

## 3.0.31
```
$ conda build --output aprio
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py27h562ef67_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py35h62adaba_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py36h4664fa8_0.tar.bz2
```

# After....

## 3.1.0
```
$ conda build --output aprio
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py27_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py35_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py36_0.tar.bz2
```

## 3.1.1
```
conda build --output aprio
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py27_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py35_0.tar.bz2
/opt/conda/conda-bld/linux-64/aprio-1.0.1-py36_0.tar.bz2
```

Thoughts?

**Comment by nehaljwani** [comment]
See https://github.com/conda/conda-build/blob/master/CHANGELOG.txt#L25-L36

**Comment by jhunkeler** [comment]
Changelog says:
>  * package is an explicit dependency in build, host, or run deps
>  * package has a matching entry in conda_build_config.yaml which is a pin to a specific version, not a lower bound

Interesting. Now what? I can't figure out the exact combination of pins or keys necessary to produce a unique package built against a unique version of numpy.

I want this:
```
package-x.y.z_py27_[unique]_0 # < numpy 1.12
package-x.y.z_py27_[unique]_0 # < numpy 1.13
package-x.y.z_py35_[unique]_0 # < numpy 1.12
package-x.y.z_py35_[unique]_0 # < numpy 1.13
package-x.y.z_py36_[unique]_0 # < numpy 1.12
package-x.y.z_py36_[unique]_0 # < numpy 1.13
```

I get this:
```
package-x.y.z_py27_0
package-x.y.z_py35_0
package-x.y.z_py36_0
```

I've been using this guide for reference: https://github.com/conda/conda-docs/blob/master/docs/source/user-guide/tasks/build-packages/variants.rst (last updated in October *hint hint*)

Are there examples in the wild I can look at? Do you know of any?

**Comment by msarahan** [comment]
numpy x.x should still work.  Really, though, why are you doing that?  Numpy doesn't need to be pinned like that.  Build against an old version, and get forward compatibility.

**Comment by jhunkeler** [comment]
Hmm, I wasn't aware this was no longer a thing.

I was under the impression the original concept of `numpy x.x` was rolled into `pin_run_as_build`. Or is it that `numpy x.x` at the recipe-level is still treated differently than `numpy {{ numpy }}`?

Before the `npYYYpyZZ` naming convention was deprecated you'd see packages built like this all over the place:

```
astropy [...]
                             1.3.3               np111py27_0  defaults
                             1.3.3               np111py35_0  defaults
                             1.3.3               np111py36_0  defaults
                             1.3.3               np112py27_0  defaults
                             1.3.3               np112py35_0  defaults
                             1.3.3               np112py36_0  defaults
                             1.3.3               np113py27_0  defaults
                             1.3.3               np113py35_0  defaults
                             1.3.3               np113py36_0  defaults
[...]

scipy [...]
                             0.19.0              np111py27_0  defaults
                             0.19.0          np111py27_nomkl_0  defaults        [nomkl]
                             0.19.0              np111py35_0  defaults
                             0.19.0          np111py35_nomkl_0  defaults        [nomkl]
                             0.19.0              np111py36_0  defaults
                             0.19.0          np111py36_nomkl_0  defaults        [nomkl]
                             0.19.0              np112py27_0  defaults
                             0.19.0          np112py27_nomkl_0  defaults        [nomkl]
                             0.19.0              np112py35_0  defaults
                             0.19.0          np112py35_nomkl_0  defaults        [nomkl]
                             0.19.0              np112py36_0  defaults
                             0.19.0          np112py36_nomkl_0  defaults        [nomkl]
                             0.19.0              np113py27_0  defaults
                             0.19.0          np113py27_nomkl_0  defaults        [nomkl]
                             0.19.0              np113py35_0  defaults
                             0.19.0          np113py35_nomkl_0  defaults        [nomkl]
                             0.19.0              np113py36_0  defaults
                             0.19.0          np113py36_nomkl_0  defaults        [nomkl]
                             0.19.1              np112py27_0  defaults
                             0.19.1          np112py27_nomkl_0  defaults        [nomkl]
                             0.19.1              np112py35_0  defaults
                             0.19.1          np112py35_nomkl_0  defaults        [nomkl]
                             0.19.1              np112py36_0  defaults
                             0.19.1          np112py36_nomkl_0  defaults        [nomkl]
                             0.19.1              np113py27_0  defaults
                             0.19.1          np113py27_nomkl_0  defaults        [nomkl]
                             0.19.1              np113py35_0  defaults
                             0.19.1          np113py35_nomkl_0  defaults        [nomkl]
                             0.19.1              np113py36_0  defaults
                             0.19.1          np113py36_nomkl_0  defaults        [nomkl]
[...]
```

That aside...

When using the prescribed method of building against the minimum version, how do you handle a situation where a C extension linking against Numpy is no longer compatible with the latest release?

Let's pretend 1.14 deprecates or refactors something found in 1.12.  If we link against 1.12 at build-time but ultimately rely on 1.14 at run-time, a missing symbol error might just... happen... except for it won't happen to a user that installed Numpy 1.13 in their environment (a day or a month before 1.14 enters the channel). If the missing symbol is caught during the recipe test phase, that's good I suppose; no "bad package" will be produced, most maintainers can live with that.

However, there's nothing stopping a non-C-API package that imports Numpy from making calls to a deprecated function "at some point during its execution" not covered in the test phase. At this point, a "bad package" will be released into the channel.

Anyway... If I link X against Y, and Y is too new for X, how is X kept up to date? Is the expectation here for the maintainer to bump the numpy requirements in `conda_build_config.yaml` to the next mostly-compatible minimum version, increase the build revision number, rebuild the package, publish it, and then say to hell with the suddenly broken version they used to link against?

**Comment by msarahan** [comment]
What you are describing is the fundamental problem of ABI compatibility.  @jjhelmus has done research and confirmed that the numpy community has a strong commitment to ABI forward compatibility.  Build against an old version, and it'll be compatible with newer versions.

The general problem is one that you should approach with the pin_compatible jinja2 function.  Every library will be different.  Some you'll want max_pin not set (defaults to next major version).  For more finicky libraries, you'll want max_pin='x.x' or even more, 'x.x.x', or so on.

I don't understand about the "suddenly broken version" - the only time you should ever have broken pins are when the external dependency unexpectedly breaks their API/ABI in a way that your pinning allows.  

It is a balance between needing to rebuild all of the time (pin tightly) or breaking sometimes unexpectedly.  This balance is different for every library and you need to make the call.  We use https://abi-laboratory.pro/tracker/ to guide our decisions.

**Comment by msarahan** [comment]
PS - the numpy file naming might be a little broken.  It should still work, but it represents the old "x.x" ONLY when you have ``pin_compatible('numpy', max_pin='x.x')``

**Comment by jhunkeler** [comment]
Thank you for the clarification here, I appreciate it. Things are starting to click.

Sorry about the confusion regarding the "suddenly broken version" part. I agree the scenario I described shouldn't happen if `max_pin` if applied correctly. I somehow ended up describing the effect of using unpinned versions :)

☕️
