### ISSUE TITLE
Jinja2 is a direct dependency for CB

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2565]
https://github.com/conda/conda-build/blob/3.1.2/conda_build/index.py#L21

Although it is present in conda.recipe, shouldn't this also be specified in `install_requires` in setup.py? I was trying to (in the base env):
```
pip install https://github.com/conda/conda-build/archive/master.zip
```
But it didn't pull in jinja2, which is not part of the Miniconda installers.

**Comment by msarahan** [comment]
sure, please file a PR
