### ISSUE TITLE
DOC: `test: run_test.sh` does not work

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#2574]
The docs seem to show that one can have a [meta.yaml structured like](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#run-test-script):
```yaml
test:
  run_test.sh
```
But this causes errors for conda-build 2.1.17. Is this possible in later versions? What am I doing wrong here?

**Comment by msarahan** [comment]
Sorry the docs are misleading.  Those files get found if they exist.  They are never listed explicitly in meta.yaml.

**Comment by CJ-Wright** [comment]
Ah ok. Should I put in a PR for the docs? Also what is the best way to exclude OSX from a `run_test.sh`?

**Comment by msarahan** [comment]
sure, a docs PR would be nice.

Excluding something in run_test.sh is done with bash platform checks: https://github.com/AnacondaRecipes/pyzmq-feedstock/blob/master/recipe/build.sh#L3
