### ISSUE TITLE
Is a subprocess call necessary to delete one file?

### ISSUE THREAD

**Issue by wulmer** [conda/conda-build#2577]
Hi, I noticed in recent versions of `conda-build` (which I like a lot!) that it sometimes hangs for a long time without any progress message. After a quick look in my task explorer, I noticed that `python` was spawning a lot of `cmd.exe` subprocesses, each with a command line similar to `cmd.exe /c del <somefile>`.

Then I found [this comment](https://github.com/conda/conda-build/blob/2e597a1f07a7cd60c7d55ee3422a40522ee0501b/conda_build/utils.py#L1036) in `conda_build.utils` (in the `rm_rf` function):

> \# native windows delete is potentially much faster

I fully agree for whole directory trees, but is this also the case for a single file? In the current `rm_rf` function, even for a single file, a new `cmd.exe` subprocess is created. And processes on Windows are much slower than on Linux. Especially if you have virus scanners around.

For example on my laptop, I tested the following snippets:

```python
In [1]: import os

In [2]: import subprocess

In [3]: def create_file():
   ...:     with open('dummy.txt', 'w') as f:
   ...:         f.write('')
   ...:

In [4]: %%timeit
   ...: create_file()
   ...: os.unlink('dummy.txt')
   ...:
1.18 ms ± 30.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [5]: %%timeit
   ...: create_file()
   ...: subprocess.check_call('del dummy.txt', shell=True)
   ...:
626 ms ± 18.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

So deleting a single file via subprocess and not via builtins is up to several hundred times slower!

Were there other reasons for falling back to shell instead of using `os.unlink` (or similar) ?

**Comment by msarahan** [comment]
Aside from speed, I've also found the subprocess call to be much more reliable than os.remove or os.unlink.  The python functions tend to leave files around from my experience.  I'd say that's the main reason I prefer it.  This is pretty bad, though.  If it's only one single file, it's probably not worth fixing it, but it sounds like you're seeing loads of files deleted this way.  I'll try to fix this.  It would help me track this down in the code if you could isolate which files (or at least some small subset of them) are being deleted this way.

**Comment by wulmer** [comment]
This happens during/after the console output

    Fixing permissions
    Fixing permissions
    updating: pkgxy-version-py36_0.tar.bz2

I can see command lines like

    C:\WINDOWS\system32\cmd.exe /c "del C:\some\path\_h_env\info\paths.json"
    C:\WINDOWS\system32\cmd.exe /c "del C:\some\path\_h_env\info\files"
    ...

I think the common pattern here is the `_h_env`... when conda cleans up these intermediate files. For large packages however this takes ages....

**Comment by msarahan** [comment]
Thanks, that helps.  I'll work on it very soon.
