### ISSUE TITLE
Specifying a git_url with a local repository with a trailing / will break conda build

### ISSUE THREAD

**Issue by will133** [conda/conda-build#2585]
This seems to be a pretty subtle and misleading bug in the git mirroring code.  By accident, I defined the git_url to point to a local repository, which does not seem wrong.  For instance:

```
git_url: /some/absolute/path/
```

(note the trailing "/" at the end)

When I do this and do a conda build, I get the following:

```
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['/.../git', 'fetch']' returned non-zero exit status 128
Failed to download or patch source. Please see build log for info.
```

After looking at the source a bit, it seems the git_mirror_checkout_recursive function (source.py:201) has a problem where it will create /some/absolute/path directory instead of just the /some/absolute/:

```
    if not isdir(os.path.dirname(mirror_dir)):
        os.makedirs(os.path.dirname(mirror_dir))
    if isdir(mirror_dir):
        ...
```

(Since os.path.dirname('/some/absolute/path/') would return '/some/absolute/path', the directory is created.)

This affects the next check, which call isdir(mirror_dir) and would return True.  Thus, the whole "git clone --mirror" section is skipped and git fetch is called instead.  Since the mirror_dir is not instantiated, the conda build would fail with such error.

The fix, of course, is to not leave a trailing '/' at the end (and you have to blow away that bogus git directory under git_cache).  I feel like this is a very easy mistake to make though.

**Comment by msarahan** [comment]
Thanks for raising this, and for the detailed description.  I'm happy to put in an rstrip on the parsed git_url, but I don't want to do much more than that, for fear of smoking the proverbial exploding cigar.  This code has historically been fragile, and it hasn't caused problems (aside from the one you point out) lately.

**Comment by will133** [comment]
Can the parent directory (the makedirs of os.path.dirname(mirror_dir)) be changed to something like this?

```
os.makedirs(os.path.abspath(os.path.join(mirror_dir, os.pardir)))
```
for instance:
```
 In [7]: os.path.abspath(os.path.join('/abc/def/', os.pardir))
'/abc'

In [8]: os.path.abspath(os.path.join('/abc/def', os.pardir))
'/abc'

In [9]: os.path.abspath(os.path.join('/abc/def.git', os.pardir))
'/abc'
```

It seems like the intention is to create the parent directory here.

**Comment by msarahan** [comment]
Yes, I do agree that that is the intent.  @mingwandroid can you please take a quick look and confirm?

**Comment by mingwandroid** [comment]
Input validation should happen as early as possible so I do not think this is the right place to fix this personally.

**Comment by will133** [comment]
I'm not sure about the other cases with the git_url, but is having a trailing "/" an invalid input?  If there's no side effect to other type of url, it can probably be stripped when you read the meta.yaml file.

In general, I think it's just a very easy mistake for people to make.  For instance, when this didn't work I tried putting in "file://" prefix, adding a ".git" suffix, and even remove the trailing slash.  All the options would not work since the cache was already is in a bad state.  You really had to clean the cache, remove the trailing slash, and try again.  It's definitely not something obvious without looking at the conda build source.

**Comment by mingwandroid** [comment]
Well, at least is is not normalised, and normalisation should be done as early as possible (or else it gets done in multiple places). I'm not asking you to fix your input here, I'm wondering if it's not better to remove the '/' early in the code-flow for any git_url (like at the time it is first assigned).

The worry with changing this code is that it's historically been a little brittle.

**Comment by mbargull** [comment]
Note that, for example, a HTTP server might differentiate between URLs with and without slashes. Thus removing a trailing slash in all cases wouldn't be desirable.
