### ISSUE TITLE
Error ignoring .exe.manifest files on win32 with noarch: python

### ISSUE THREAD

**Issue by igortg** [conda/conda-build#2619]
Hello People,

I'm getting the following error when trying to build a package with entry_points on win32 using `noarch: python` flag.

```
Installing ptw-script.py script to C:\Dev\Bin\Miniconda3-x86\conda-bld\pytest-watch_1515277470663\_b_env\Scripts
Installing ptw.exe script to C:\Dev\Bin\Miniconda3-x86\conda-bld\pytest-watch_1515277470663\_b_env\Scripts
Installing ptw.exe.manifest script to C:\Dev\Bin\Miniconda3-x86\conda-bld\pytest-watch_1515277470663\_b_env\Scripts
writing list of installed files to 'record.txt'
INFO:conda_build.build:Packaging pytest-watch-4.1.0-0
number of files: 17
Fixing permissions
Fixing permissions
'python-scripts/ptw.exe.manifest' not in info/files
INFO:conda.gateways.disk.delete:rm_rf failed for W:\sgs\tmp\tmpud5yin1l
Traceback (most recent call last):
  File "C:\Dev\Bin\Miniconda3-x86\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\build.py", line 1524, in build_tree
    config=config)
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\build.py", line 1159, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\build.py", line 931, in bundle_conda
    tarcheck.check_all(tmp_path)
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\tarcheck.py", line 90, in check_all
    x.info_files()
  File "C:\Dev\Bin\Miniconda3-x86\lib\site-packages\conda_build\tarcheck.py", line 55, in info_files
    raise Exception('info/files')
Exception: info/files
```

In win32, my setuptools is generating `exe.manifest` files together with the entry_point executables, and conda-build [seems not aware of that](https://github.com/conda/conda-build/blob/459e74102b032e6a64443001e2f597a62d5d673d/conda_build/build.py#L509). I have these questions:

1. Is the default behaviour of setuptools to generate a `.exe.manifest` file on win32? 
1. Should we add a new entry on for `.exe.manifest` [on this method](https://github.com/conda/conda-build/blob/459e74102b032e6a64443001e2f597a62d5d673d/conda_build/build.py#L509)?
1. Or is some other thing that I'm not getting?

(Seems that the same problem was reported by #2575)

**Comment by msarahan** [comment]
This is the first time I've seen such a ``exe.manifest`` file.  I don't know what might lead to their generation.  Can you try a different version of setuptools?  What setuptools version are you using?

What are the contents of that manifest file?  Does it seem at all important?  Ideally, we'd just ignore those files.

I believe #2575 is a different issue (that's a script, not an entry point - the difference is subtle and annoying).

**Comment by igortg** [comment]
Setuptools versions were 36.5 in my local machine and 38.2.4 on [appveyor](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.19814/job/w92u4y4lrsjbxpno).

This seems and old feature of setuptools: https://github.com/pypa/setuptools/commit/aa5a03972360fdd48530183a60171ecbf477d1e6#diff-acb60a5a1c1defb3e92f17b675a74cdd

I'm also finding weird, cause I remember to have successfully done builds of noarch packages with entry_points.

**Comment by igortg** [comment]
Closing it till we get more consistent reports of the problem
