### ISSUE TITLE
conda build fails. How to enable source downloading?

### ISSUE THREAD

**Issue by biocyberman** [conda/conda-build#2622]
I got this error
`Undefined Jinja2 variables remain (['CONDA_BZIP2', 'CONDA_BZIP2']).  Please enable source downloading and try again.   `

I don't understand the suggestion there. How do I enable source downloading? Because you wrote it, maybe you Mike @msarahan could give some idea? 

The relevant lines  of code are here:
https://github.com/conda/conda-build/blob/e687511904c182d6f5cdc520241be08e2cd3b7cd/conda_build/metadata.py#L894

More details about the issue here https://github.com/bioconda/bioconda-recipes/issues/7233

**Comment by msarahan** [comment]
It looks like you figured this out at bioconda/bioconda-recipes#7233

The source downloading message is a red herring.  One way that env vars can be undefined is if the source isn't available.  This is not the reason why your env vars are undefined.  You weren't running the rest of bioconda's setup stuff.
