### ISSUE TITLE
debugging info is incompatible with old gdb on linux-64

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2624]
After gcc 4.8 we need to add -gdwarf-2 to make sure the debugging info is understood by older gdb, see

https://gcc.gnu.org/gcc-4.8/changes.html

Since conda-build with the cross compilation tools is supposed to produce binaries usable on very old systems; the flag -gdwarf-2 may need to be added.

**Comment by mingwandroid** [comment]
The binaries are intended to *run* on old systems but I have no interest in having them be debuggable by old tools (at the expense of space and richness of debug info).

Compiling gdb with these new compilers is trivial.
