### ISSUE TITLE
(User?) Error running "build.sh" command

### ISSUE THREAD

**Issue by boustrephon** [conda/conda-build#2629]
I am very puzzled. I am trying to follow the instructions on "building conda packages from scratch" (https://conda.io/docs/user-guide/tutorials/build-pkgs.html) but I find that the build.sh file does not run. I am using miniconda3 on a Mac running High Sierra.

```
My-MacBook-Air:~/Documents/GitHub/remi$ bash -x -e build.sh
+ setup.py install --single-version-externally-managed --record=record.txt
build.sh: line 1: setup.py: command not found
```

I checked the files in the directory, but I don't see anything wrong, and the contents seem to match the ones specified (files attached - [Archive.zip](https://github.com/conda/conda-build/files/1632086/Archive.zip)):

```
My-MacBook-Air:~/Documents/GitHub/remi$ ll
total 88  
-rw-r--r--   1 diomedea  staff  11308 Jan 15 19:53 LICENSE  
-rw-r--r--   1 diomedea  staff     56 Jan 15 19:53 MANIFEST.in  
-rw-r--r--   1 diomedea  staff  12464 Jan 15 19:53 README.md  
-rw-r--r--@  1 diomedea  staff    124 Jan 15 22:02 build.sh  
drwxr-xr-x   8 diomedea  staff    256 Jan 15 19:53 doc  
drwxr-xr-x   9 diomedea  staff    288 Jan 15 19:53 editor
drwxr-xr-x  22 diomedea  staff    704 Jan 15 19:53 examples
-rw-r--r--@  1 diomedea  staff    320 Jan 15 22:01 meta.yaml
drwxr-xr-x   6 diomedea  staff    192 Jan 15 19:53 remi
-rw-r--rw-   1 diomedea  staff    350 Jan 15 19:53 setup.py
```

**Comment by mingwandroid** [comment]
You are not meant to run that script, conda-build runs it.

**Comment by boustrephon** [comment]
Thanks. That clarifies that one then. 

Having said that, I find it a little strange that the [tutorial](https://conda.io/docs/user-guide/tutorials/build-pkgs.html) states, "You can run build.sh with bash -x -e", if you are not intended to do so. Why would it tell you this unless it wanted you to do so...?

Anyway... no need for me to worry any further... thanks again...

This then leads to my next problem which I have documented on [issue 2628](https://github.com/conda/conda-build/issues/2628). If you could also help on that, it would be great...

```
My-MacBook-Air:~/Documents/GitHub/remi$ conda-build remi
Traceback (most recent call last):
  File "/Users/diomedea/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/diomedea/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 393, in main
    execute(sys.argv[1:])
  File "/Users/diomedea/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 384, in execute
    verify=args.verify)
  File "/Users/diomedea/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 184, in build
    raise ValueError('No valid recipes found for input: {}'.format(recipe_paths_or_metadata))
ValueError: No valid recipes found for input: ['remi']
```
