### ISSUE TITLE
"--[no-]channel-priority" missing in "conda build"

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#2654]
Is there a specific reason why `conda build` has `--channel` and `--override-channels` options but not the `--[no-]-channel-priority` option?

If there is no specific reason, could you please add this option (analogous to the `update` and `install` commands). :-)

**Comment by msarahan** [comment]
I'd gladly merge a PR, but this is far outside of our normal operating procedures, and I can't spend any time on it.  If you really need it, you'll need to do more than ask for it.

**Comment by sscherfke** [comment]
I’ll see what I can do.

**Comment by mingwandroid** [comment]
Why do you want this? no-channel-priority is a hack implemented to workaround long fixed solver issues as far as I remember.

**Comment by sscherfke** [comment]
`install`, `update` and `build` all have similar options regarding Conda channels, but the `build` command has no `--[no-]channel-priority` setting.

`--no-channel-priority` is an important feature for our internal stable/staging workflow and also, I do not like inconsistancies. ;-)

**Comment by angelo-peronio** [comment]
Now that `--strict-channel-priority` provides a significant performance bonus, this issue has become more relevant. To my workflow, for instance 😉

**Comment by gabm** [comment]
does conda-build respect the strict channel_priority setting in the .condarc?

**Comment by mingwandroid** [comment]
Yes
