### ISSUE TITLE
`pin_compatible` has no effect

### ISSUE THREAD

**Issue by lschr** [conda/conda-build#2658]
I created a recipe for the `tifffile` package that uses variants to build multiple versions. Unfortunately, it does not work. `conda build --output -m conda_build_config.yaml tifffile` yields
```
.../conda-bld/linux-64/tifffile-0.13.5-py35_nomklhba1e662_3.tar.bz2
.../conda-bld/linux-64/tifffile-0.13.5-py35hb4372cb_3.tar.bz2
.../conda-bld/linux-64/tifffile-0.13.5-py36_nomklhba1e662_3.tar.bz2
.../conda-bld/linux-64/tifffile-0.13.5-py36hb4372cb_3.tar.bz2
```
There should be 12 outputs (2 Python versions, 2 BLAS implementations, 3 numpy versions). It seems as if `pin_compatible("numpy", min_pin="x.x", max_pin="x.x")` has no effect.

Recipe and build config are attached below.
[meta.yaml](https://github.com/conda/conda-build/files/1668545/meta.yaml.txt)
[conda_build_config.yaml](https://github.com/conda/conda-build/files/1668525/conda_build_config.yaml.txt)

**Comment by msarahan** [comment]
confirmed.  Thanks for reporting.  I think it's a bug related to numpy not being considered a "used" variable.  We'll fix for 3.3.1.
