### ISSUE TITLE
Is it possible to extend a conda recipe without duplicating the contents?

### ISSUE THREAD

**Issue by mithro** [conda/conda-build#2662]
I apologize if there is an already open issue for this request, but I wasn't able to find one.

I would like a way to "extend" a conda recipe without duplicating the entire contents of the recipe.

My use case is that I want to use conda to ship cross-compilers for architectures used on the soft-CPU inside our FPGA. This means I would like to extend [the ctng-compilers-feedstock recipe](https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-feedstock/recipe) with support for some new configurations.

To do this I currently have to copy the entire `ctng-compilers-feedstock/recipe` directory and then add my own `conda_build_config.yaml` file. However, I don't need to modify 99% of the recipe, so it would be nice to be able to reuse all the existing code without having to copy it.

Something like;
```
{% extends <path to other meta.yaml> %}

things_i_override:
 - etc
 - etc
```

Is that something that can already be done that I have missed? There seems to be a lot of mentions about more general templates stuff, but I can't find anything in the docs.

**Comment by msarahan** [comment]
That was a large motivation for the whole general-purpose conda_build_config.yaml file.  The compilers are a special case where tons of stuff changes, and we've opted to have separate conda_build_config.yaml files for each configuration.  You can also have just one conda_build_config.yaml that loops over many settings - that's what we have in our aggregate repo.

Long story short: no, there's no "extend."  There is "clobber" and "append"

```
  --append-file APPEND_SECTIONS_FILE
                        Append data in meta.yaml with fields from this file.
                        Jinja2 is not done on appended fields
  --clobber-file CLOBBER_SECTIONS_FILE
                        Clobber data in meta.yaml with fields from this file.
                        Jinja2 is not done on clobbered fields.
```

but neither of these are probably what you want.  I think the correct answer is for you to fix up the ctng-compilers-feedstock recipe to generalize it for anything you need to change, and leave template placeholders for whatever you need to swap out.  Ideally, the only part you should need to maintain is a conda_build_config.yaml file.

**Comment by mithro** [comment]
Thanks for the super fast reply!

I'm not sure how `--append` and `--clobber` are used? I'd like to do a `conda build <directory>` and have it build my gcc with my `conda_build_config.yaml` in the directory?

**Comment by msarahan** [comment]
No, with these recipes, what you really want to do is have your own conda_build_config.yaml, and pass it explicitly.  We have to do this too - note that the filenames of the config files in the recipe aren't the standard conda_build_config.yaml, and won't be automatically picked up.

conda build <directory> -m path/to/your/config.yaml

The exact filename you use for your config doesn't matter, as long as you are not depending on conda-build to find it, but rather you're telling it where to look.
