### ISSUE TITLE
error when building `descartes` using conda skeleton

### ISSUE THREAD

**Issue by willangley** [conda/conda-build#2663]
### Actual Behavior

I'm unable to conda build [descartes](https://pypi.python.org/pypi/descartes/1.1.0) following the instructions in [Building conda packages with conda skeleton](https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html).

The generated meta.yaml fails to build with an error, `Invalid selector in meta.yaml line 44`.

This is very likely the same issue as conda/conda#1540.

### Expected Behavior

I should be able to build this without manually tweaking meta.yaml.

### Steps to Reproduce

In a fresh python3 Conda install on macOS,

```
$ conda install conda-build
$ conda skeleton pypi descartes
$ cd descartes && curl -O https://conda.io/docs/_downloads/build1.sh
$ conda-build descartes
Error: Invalid selector in meta.yaml line 44:
offending line:
    \ zorder=1)\n  ax.add_patch(patch2a)\n\n  eroded = dilated.buffer(-0.3)\n\n  # GeoJSON-like data works as well\n\n  polygon = eroded.__geo_interface__\n  # >>> geo['type']\n  # 'Polygon'\n  # >>> geo['coordinates'][0][:2]\n\
exception:
invalid syntax (<string>, line 1)
```

##### `Output of conda info`

```
     active environment : None
       user config file : /Users/wmangley3/.condarc
 populated config files :
          conda version : 4.4.8
    conda-build version : 3.3.0
         python version : 3.6.3.final.0
       base environment : /Users/wmangley3/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/wmangley3/anaconda3/pkgs
                          /Users/wmangley3/.conda/pkgs
       envs directories : /Users/wmangley3/anaconda3/envs
                          /Users/wmangley3/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.8 requests/2.18.4 CPython/3.6.3 Darwin/17.3.0 OSX/10.13.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Generated recipes are not guaranteed to run right away without any tweaking.  We can't anticipate everything that anyone might put in their recipes.  We also can't currently determine when compiler metadata needs to be added - adding that is currently always a manual step.  I don't think we communicate this expectation well enough.

In this case, your description has stuff in it that looks like a selector, but not quite.  You need to remove that part of the description, which is almost certainly way more verbose than you need anyway.  No one puts code examples in their description.

If you have suggestions on how to improve documentation or error messages, I'm open to them.  I'd also accept a PR if you'd like to improve the selector detection regex (https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L124-L192).  I'm not willing to accept the statement that "I should be able to build this without manually tweaking meta.yaml" for all cases - it's just too open-ended.

**Comment by msarahan** [comment]
To be clear, we should definitely update our docs to point at something that does "just work" unless we also use descartes as an example here to talk about what can go wrong.

**Comment by willangley** [comment]
@msarahan thanks for taking a look at this!

I didn't write that description, it was autogenerated by `conda skeleton pypi`. Tweaking compiler flags is an obvious thing to try when builds fail, tweaking descriptions was... a little surprising.

If I had to guess how this happened I'd say the PyPI JSON API is serving the package's `long_description` field as `"description"` and `description` as `"summary"` nowadays, and `conda skeleton pypi` is copying them directly into the YAML output.

I've attached a copy of the response I got from https://pypi.python.org/pypi/descartes/json, and the `meta.yaml` that resulted, renamed so GitHub would accept the attachments.

[descartes.json](https://github.com/conda/conda-build/files/1672119/descartes.json.txt)
[meta.yaml](https://github.com/conda/conda-build/files/1672125/meta.yaml.txt)

**Comment by msarahan** [comment]
Again, we can't necessarily cope with arbitrary text input, which is what we have here.  I know it's in the description, and I know the skeleton tool is getting it from the contents on pypi.  This is a bizarre corner case that arises because descartes has code samples in their long_description that happen to match our regex pattern for selectors.  Selectors apply to raw text - it makes no difference whether it is a requirement or description text.  There's no notion of where in the recipe a given selector is, because the recipe hasn't been parsed at that point.

Selectors could just warn when they fail.  The trade-off here is that people may have buggy recipes but not notice, and that can lead to more subtle problems.  I'd much rather have this error out.  I spent a summer in grad school running simulations.  I had a typo in my configuration then, and it put a warning out, but proceeded anyway.   That entire summer went to waste because the simulation program proceeded happily.
