### ISSUE TITLE
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh']' returned non-zero exit status 127

### ISSUE THREAD

**Issue by balathl** [conda/conda-build#2675]
Hi,

I am getting the below error when i try to build conda for flash2:

### Actual Behavior

# conda-build flash2
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for flash2
INFO:conda_build.metadata:Attempting to finalize metadata for flash2
BUILD START: [u'flash2-2.2.00-0.tar.bz2']
From https://github.com/dstreett/FLASH2
 * [new tag]         2.2.00     -> 2.2.00
Cloning into '/root/anaconda/conda-bld/flash2_1518095364537/work'...
done.
checkout: u'2.2.00'
Note: checking out '2.2.00'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 64826f4... Merge pull request #7 from dstreett/develop
==> git log -n1 <==

commit 64826f4574b11b3c0ae7460826f30be16f49c3ea
Merge: 55e230f 288e1f0
Author: David Streett <davidastreett@hotmail.com>
Date:   Fri May 6 15:45:53 2016 -0700

    Merge pull request #7 from dstreett/develop
    
    Develop

==> git describe --tags --dirty <==

2.2.00

==> git status <==

HEAD detached at 2.2.00
nothing to commit, working directory clean

source tree in: /root/anaconda/conda-bld/flash2_1518095364537/work
/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh: line 56: setup.py: command not found
Traceback (most recent call last):
  File "/root/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1240, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/root/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh']' returned non-zero exit status 127

### Steps to Reproduce

conda-build flash2

flash2 is the folder contains three files "bld.bat",  "build.sh", "meta.yaml"
==> bld.bat <==
"%PYTHON%" setup.py install --single-version-externally-managed --record=record.txt
if errorlevel 1 exit 1

==> build.sh <==
$PYTHON setup.py install --single-version-externally-managed --record=record.txt  # Python command to install the script.

==> meta.yaml <==
package:
  name: flash2
  version: "2.2.00"

source:
  git_rev: 2.2.00
  git_url: https://github.com/dstreett/FLASH2.git

requirements:
  build:
    
  run:

test:
  imports:

about:
  home: https://github.com/dstreett/FLASH2
  license: BSD
  license_file: LICENSE

##### `Output of conda info`
<!-- # conda info

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.4.8
    conda-build version : 3.4.0
         python version : 2.7.12.final.0
       base environment : /root/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /root/anaconda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.8 requests/2.14.2 CPython/2.7.12 Linux/3.13.0-141-generic ubuntu/14.04 glibc/2.19
                UID:GID : 0:0
             netrc file : None
           offline mode : False

Any help is greatly appreciated!!!

Bala

**Comment by msarahan** [comment]
The error is:

```
/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh: line 56: setup.py: command not found
```

Your recipe has no python requirement, but it obviously needs one.  $PYTHON is undefined without explicit python requirements.  I advise you to put python requirements in build and host.  Please refer to other python library recipes, such as click: https://github.com/AnacondaRecipes/click-feedstock/blob/master/recipe/meta.yaml

**Comment by balathl** [comment]
conda-build flash2
----------------------------------------------------------------------
Unable to parse meta.yaml file

Error Message:
--> while scanning for the next token
--> found character that cannot start any token
-->   in "<unicode string>", line 18, column 1


I am getting the above error if i follow the receipe that you mentioned. Below is the content of my meta.yaml file:

########meta.yaml##############
{%set name = "click" %}
{%set version = "6.7" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b" %}
{%set build_num = "0" %}

package:
  name: {{ flash2 }}
  version: {{ 2.2.00 }}

source:
  git_rev: 2.2.00
  git_url: https://github.com/dstreett/FLASH2.git

requirements:
  host:
	- python
	- setuptools
  
  run:
	- python
test:
  imports:
	- click

about:
  home: https://github.com/dstreett/FLASH2
  license: BSD
  license_file: LICENSE
###############################

Is there any mistake that i need to correct?? Any help is greatly appreciated. Thanks in advance!

Bala

**Comment by msarahan** [comment]
Sorry, but I really can't help you learn how to write recipes here.  Please follow documentation at https://conda.io/docs/user-guide/tasks/build-packages/index.html and https://conda-forge.org/docs/

If this package is already on pypi, you may find this section in particular helpful: https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html

You may find help on the conda-forge gitter or the anaconda users mailing lists.  However, it seems that right now you are hoping to just copy-paste something that already exists.  That approach will not get you very far.  You will need to actually read about these things and understand them in order to create a recipe.

**Comment by balathl** [comment]
Hey!

Thanks for your reply! I am quite new to conda implementation. I will try to read the content of recipes. But just wondering why putting a software from github into conda env  is very demanding if not available in anaconda cloud??? Anyway thanks for your help!

Bala

**Comment by msarahan** [comment]
If your only goal is to install it for your usage, you can just use pip.  Pip can install from github urls.  That will get you on your way.  You only need to deal with recipes if you want to create a conda package, which will make it easier for other people to install this software in the future, and reduce problems with pip (which can sometimes clobber files and make life generally painful).

As for recipes, your definition of "very demanding" is strange.  You can't expect software to work when you aren't providing the dependencies that it needs to work.  That is the cost of doing business, so to speak.  We need an equivalent to pip's installation from github for our skeleton generator to make this easier, but it will still require some understanding and work from you.  This is already a request in issue https://github.com/conda/conda-build/issues/1474

**Comment by balathl** [comment]
Hey,

I solved the issue and now made flash2 available in anaconda with the below code. Now it can be integrated into some pipelines easily with conda env. Hope it can be a good starting point for the people who had similar issues like me.


#####################################################################################
cat meta.yaml
{% set name = "flash2" %}
{% set version = "2.2.00" %}
{% set build = 0 %}
{% set hash = "7bb357a935de87be8a294b35ed281eca2e08afa1e1a1d1b1c24a024b80b713ff" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version}}.tar.gz
  url: https://github.com/dstreett/FLASH2/archive/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: {{ build }}
  script: make

requirements:
  build:
    - python
    - make

test:
  commands:
    - /root/anaconda/conda-bld/flash2_1518176363321/work_moved_flash2-2.2.00-0_linux-64/flash2 --help

about:
  home: https://github.com/dstreett/FLASH2
  summary: FLASH is a tool to merge paired-end reads generated from DNA fragments
  #license: [the repos license (which doesn't exist)]
#license_file: [you should create a LICENSE file since the repo has none]


conda-build flash2 #flash2 is folder containing meta.yaml file

anaconda upload /root/anaconda/conda-bld/linux-64/flash2-2.2.00-0.tar.bz2

conda install -n myenv  -c flash2 software2 software3 ...

source activate myenv

####################################################################################

Bala



________________________________

**Comment by msarahan** [comment]
Great!  Recipe looks good.  Thanks for following through on it.

**Comment by balathl** [comment]
Thanks Mike! a small update on the “build.sh” as there are some issues with the binary file missing after conda install and I figure it out that I need to add $PREFIX as below in the build.sh file for conda-build:

==> build.sh <==
#!/bin/bash
make
mkdir -p $PREFIX/bin
cp flash2 $PREFIX/bin

==> meta.yaml <==
{% set name = "flash2" %}
{% set version = "2.2.00" %}
{% set build = 0 %}
{% set hash = "7bb357a935de87be8a294b35ed281eca2e08afa1e1a1d1b1c24a024b80b713ff" %}

package:
name: {{ name }}
version: {{ version }}

source:
fn: {{ name }}-{{ version}}.tar.gz
url: https://github.com/dstreett/FLASH2/archive/{{ version }}.tar.gz
sha256: {{ hash }}

requirements:
build:
- python
- make

test:
commands:
- /root/anaconda/conda-bld/flash2_1518191100369/work_moved_flash2-2.2.00-0_linux-64/flash2 --help
about:
home: https://github.com/dstreett/FLASH2
summary: FLASH is a tool to merge paired-end reads generated from DNA fragments
#license: [the repos license (which doesn't exist)]
#license_file: [you should create a LICENSE file since the repo has none]

######################

Now it’s more complete ☺

Bala
