### ISSUE TITLE
build environment prefix is not replaced

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#2677]
If PREFIX is detected in a file it is a replaced by a sentinel which is then patched when the file is installed into a conda environment.  This logic is not applied to BUILD_PREFIX, and files containing this path may be included in the package.  These paths will be invalid when installing these packages into an environment but because the build environment is not moved prior to the testing phase, #2625, they are still valid at test time.  Running the tests post build will fail as the build environment is deleted after a successful build.

Example

meta.yaml
``` yaml
package:
  name: compiler_wrapper
  version: 1.0.0

requirements:
  build:
    - {{ compiler('c') }}
  run:
    - {{ compiler('c') }}

test:
  commands:
    - wrapper.sh --version
```

build.sh
``` bash
mkdir -p ${PREFIX}/bin

cat > ${PREFIX}/bin/wrapper.sh <<EOF
#! /bin/sh
echo "Hello from the compiler wrapper"
echo "The compiler version is:"
${CC} \$@
EOF

chmod +x ${PREFIX}/bin/wrapper.sh

echo "At build time the wrapper script is:"
echo "-----------------------------------"
cat ${PREFIX}/bin/wrapper.sh
echo "-----------------------------------"
```

Initial build:
```
$ conda build .
Adding in variants from internal_defaults
...
At build time the wrapper script is:
-----------------------------------
#! /bin/sh
echo "Hello from the compiler wrapper"
echo "The compiler version is:"
/home/jhelmus/anaconda3/conda-bld/compiler_wrapper_1518127856653/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc $@
...
TEST START: /home/jhelmus/anaconda3/conda-bld/linux-64/compiler_wrapper-1.0.0-h14c3975_0.tar.bz2
...
+ wrapper.sh --version
Hello from the compiler wrapper
The compiler version is:
x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 8a21ab48) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ exit 0
TEST END: /home/jhelmus/anaconda3/conda-bld/linux-64/compiler_wrapper-1.0.0-h14c3975_0.tar.bz2
```

Post build test:
```
$ conda build --test /home/jhelmus/anaconda3/conda-bld/linux-64/compiler_wrapper-1.0.0-h14c3975_0.tar.bz2
TEST START: /home/jhelmus/anaconda3/conda-bld/linux-64/compiler_wrapper-1.0.0-h14c3975_0.tar.bz2
...
+ wrapper.sh --version
Hello from the compiler wrapper
The compiler version is:
/home/jhelmus/anaconda3/conda-bld/compiler_wrapper_1518127960250/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/wrapper.sh: 4: /home/jhelmus/anaconda3/conda-bld/compiler_wrapper_1518127960250/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/wrapper.sh: /home/jhelmus/anaconda3/conda-bld/compiler_wrapper_1518127856653/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc: not found

Leaving build/test directories:
  Work:  /home/jhelmus/anaconda3/conda-bld/work 
  Test:  /home/jhelmus/anaconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test: source activate  /home/jhelmus/anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:        source activate  /home/jhelmus/anaconda3/conda-bld/_build_env 


TESTS FAILED: compiler_wrapper-1.0.0-h14c3975_0.tar.bz2

$ cat /home/jhelmus/anaconda3/conda-bld/compiler_wrapper_1518127960250/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/wrapper.sh
#! /bin/sh
echo "Hello from the compiler wrapper"
echo "The compiler version is:"
/home/jhelmus/anaconda3/conda-bld/compiler_wrapper_1518127856653/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc $@
```

**Comment by msarahan** [comment]
I'm totally fine fixing this so that both host_prefix and build_prefix are detected and treated similarly.  Are there any cases we foresee where doing so may break things?

**Comment by jjhelmus** [comment]
build_prefix is not filled to 255 characters so there may be issues if this is detected in a binary file.

**Comment by msarahan** [comment]
hm, yes.  That's an excellent point.  We can't just straight up replace it wholesale.  I'll need to think about that for a while.  It seems like when we get ahold of things, it'll already be too late to fix that length.

**Comment by msarahan** [comment]
Maybe the easiest thing is to make the build prefix also padded?

Conda records the prefix placeholder, no matter what it is, but the only way to reserve the space is by having the padded prefix.  I think we should pad the build prefix, then scan and replace the build prefix in all files with the host prefix, and finally let conda do the replacement of only host prefix at install time.

**Comment by jjhelmus** [comment]
The command line argument `--merge-build-host` can be used as a workaround.

**Comment by jjhelmus** [comment]
I would be alright if the build prefix was padded.  It will make the build directory a bit of an eyesore but it is needed to reserve the space in binary files.

**Comment by msarahan** [comment]
@mingwandroid @nehaljwani any comment here?

**Comment by mingwandroid** [comment]
I prefer the metadata `build/merge-build-host` instead of the command-line argument since the need to the workaround is a property of the thing being built.

**Comment by mingwandroid** [comment]
In a lot of cases of build tool paths being embedded I was able to instead use just the filename:

`CC=$(basename ${CC})`

.. when this can work it is preferable because prefix replacement comes with costs. I've yet to run into a hard need to do build prefix replacement (not saying it will not happen though).

If we need to pad to 255 then we need to pad to 255.

**Comment by msarahan** [comment]
Should we generally set CC to that value in our compiler activation scripts?  Would there be any downside to that?

**Comment by mingwandroid** [comment]
So long as it's on PATH we can do it that way I think.

**Comment by msarahan** [comment]
@jjhelmus Ray's proposal would fix your example here.  Is your example representative enough of the problems in hdf5 that you feel like changing CC would also fix the real-world breakages you saw?

**Comment by jjhelmus** [comment]
Either `CC=$(basename ${CC})` or merging the build and host environments via flags or a meta.yaml entry will fix the issue I was seeing and are fine solutions.  

I do worry that it is rather difficult to detect files which accidentally include a build prefix since the build environment is still a valid path during the test phase.  Moving the build environment prior to the test phase would result in these tests failing and easier detection of such path inclusions.

**Comment by msarahan** [comment]
Great, I think setting CC is the least disruptive (though also perhaps the most likely to break in the future, if we missed some tool that gets recorded somehow.

I will change CC and CXX for now.

Moving the build env prior to test is easy.  I'll make that change.

**Comment by mingwandroid** [comment]
We should adjust the compiler activation scripts I think?

**Comment by jjhelmus** [comment]
I'm not sure if CC should exclude the path in the activation script.  There are a few instances that I know of where tools derive the path of other toolchain components from CC and removing the path would break these.  I'm find with requiring recipe which need a path-less CC to include `CC=$(basename ${CC})` in the recipe.

**Comment by mingwandroid** [comment]
I would have opined that we should do what's right for the majority, and then use `which $CC` for the others but since `which` was broken with long paths until recently I will not opine that.

**Comment by jjhelmus** [comment]
Although if you do need the path `CC=$(type -p ${CC}` will put it back.  I don't have a strong opinion which is the better option.
