### ISSUE TITLE
conda build failed: Failed to connect to github.com port 443: Connection timed out

### ISSUE THREAD

**Issue by mingxiaoh** [conda/conda-build#2678]
when we build conda package from our code, we found that it have no access to the 3-party software  github(we need to clone the 3-party code when building of our code). However, we can build our code successfully in the terminal(not via conda), which means there is no proxy issue on my server. So, if the building process involves in "git clone" 3-party code, what should we do?   

actuall behavior:
$conda build conda
...
running install
running build_deps
Intel mkl-dnn preparing ...
Downloading ...
Cloning into 'source'...
fatal: unable to access 'https://github.com/01org/mkl-dnn.git/': Failed to connect to github.com port 443: Connection timed out
error: [Errno 2] No such file or directory: '/home/mingxiao/anaconda2/conda-bld/ideep4py_1518181178285/work/python/external/mkldnn/source'

expected behavior:
$ python setup.py install
running install
running build_deps
Intel mkl-dnn preparing ...
Downloading ...
Cloning into 'source'...
remote: Counting objects: 10643, done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 10643 (delta 248), reused 303 (delta 209), pack-reused 10234
Receiving objects: 100% (10643/10643), 3.48 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (8045/8045), done.
HEAD is now at ae00102 cpu: conv 1x1: bwd_w: fix assertion
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154    0   154    0     0    154      0 --:--:-- --:--:-- --:--:--   185
100   621    0   621    0     0    621      0 --:--:--  0:00:01 --:--:--  606k

**Comment by msarahan** [comment]
There's some instructions on configuring conda to use proxy servers at https://conda.io/docs/user-guide/configuration/use-condarc.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers

conda-build does not do any additional proxy configuration.
