### ISSUE TITLE
make data packages noarch to save space?

### ISSUE THREAD

**Issue by electronwill** [conda/conda-build#2695]
@msarahan , I was talking with @hsparra today and he had a good idea.

The conda packages with the offline docs are fairly large and updated fairly often, and soon there will be even larger packages with docs for many of the OSS packages in Anaconda, also updated often, and packages with Jupyter notebooks from training sessions, and we'll be distributing all of these to our airgap customers.

It would save a lot of space to have one of these data packages for all platforms instead of one for each platform.

Is this possible, using noarch or any similar functionality, or would it be a bad idea for some reason with conda and conda-build as they exist currently?

If it's a bad idea now, is it on the roadmap for conda or conda-build to add functionality like this at some point?

Thank you.

**Comment by msarahan** [comment]
This is basically what a ``noarch: generic`` package is.  There have been some issues with noarch packages in general, such as they don't work with Constructor.  We don't use them much internally, but we intend long-term to use that more, I think.

**Comment by electronwill** [comment]
Would it be practical to switch the every-two-weeks build of the docs packages to ``noarch: generic``?

**Comment by msarahan** [comment]
we could try.

**Comment by electronwill** [comment]
I have the info I need and am exploring this further in the docs repo. Thank you for your help!
