### ISSUE TITLE
Exclude package itself from variant files (conda-smithy/conda-build)

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2701]
In PR ( https://github.com/conda-forge/zlib-feedstock/pull/17 ), we learned a package may [include itself in variant files]( https://github.com/conda-forge/zlib-feedstock/pull/17#pullrequestreview-98679368 ) when re-rendering with `conda-smithy` 3 (proposed). While this likely has no effect on the build, it is a little confusing and has the potential to become problematic in the future. Would be better if we could exclude the package itself from the variant files. Included in the `conda-build` issue tracker based on the recommendation in the aforementioned PR.

**Comment by msarahan** [comment]
Sorry, I'm not going to fix this.  It's cosmetic in my opinion, until proven otherwise.  Feel free to PR.

**Comment by jakirkham** [comment]
Where would be the right place to look to fix this?

**Comment by msarahan** [comment]
Start here: https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L1898

I'm guessing you'll need to ultimately refine https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L1925

**Comment by jakirkham** [comment]
Think this actually got fixed at some point, but am not sure where ATM.

Here's an example of the new behavior `conda-smithy` shows. ( https://github.com/conda-forge/flann-feedstock/pull/16/commits/a0de5bf28d0ec40d5fe063a98f691bf5e5e9ad13 )

**Comment by msarahan** [comment]
great.  Glad to see it, though I'm equally unsure exactly what I did to fix it.

**Comment by jakirkham** [comment]
FWIW we know the behavior changed between `3.8.1` and `3.9.2` based on [this observation]( https://github.com/conda-forge/flann-feedstock/pull/16#issuecomment-385811338 ). If I had to guess, PR ( https://github.com/conda/conda-build/pull/2694 ) probably fixed it. Though haven't tested this explicitly.
