### ISSUE TITLE
PYTHON environment not set when using _build_env

### ISSUE THREAD

**Issue by tvandera** [conda/conda-build#2705]
When `conda build` creates a `_build_env` environment, the `$PYTHON` variable is not set. 
It seems the `if` here:
https://github.com/conda/conda-build/blob/40d8c2d64ca945393956c2f177c0bb56e6a34f25/conda_build/environ.py#L312-L315
is false.

Versions:
```
conda                     4.4.10                   py36_0
conda-build               3.5.1                    py36_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h98955d8_0
```

**Comment by msarahan** [comment]
This is by design.  The _build_env is only for build tools.  It is almost certainly not what you want.  You want the python in the host env - the really long _host_env_placehold_...

Conda-build bases its notion of what goes into a package based on snapshots of the host prefix, NOT the build prefix.  If you use python from the build prefix, any packages you install with that python will not go into your package.

More on this in our docs at https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#host

> As of conda-build 3.1.4, the build and host prefixes are always separate when both are defined, or when {{ compiler() }} jinja2 functions are used. The only time that build and host are merged is when the host section is absent, and no {{ compiler() }} jinja2 functions are used in meta.yaml. Because these are separate, you may see some build failures when migrating your recipes. For example, let’s say you have a recipe to build a python extension. If you add the compiler jinja2 functions to the build section, but you do not move your python dependency from the build section to the host section, your recipe will fail. It will fail because the host environment is where new files are detected, but because you have python only in the build environment, your extension will be installed into the build environment. No files will be detected. Also, variables such as PYTHON will not be defined when python is not installed into the host environment.

> TL;DR: If you use the new {{ compiler() }} jinja2 to utilize our new compilers, you also must move anything that is not strictly a build tool into your host dependencies. This includes python, python libraries, and any shared libraries that you need to link against in your build. Examples of build tools include any {{ compiler() }}, make, autoconf, perl (for running scripts, not installing perl software), python (for running scripts, not for installing software).

**Comment by tvandera** [comment]
Thanks for the quick and clear answer. No need to leave this issue open.
