### ISSUE TITLE
incorrect sha256 for renamed script files when converting from Linux to Windows

### ISSUE THREAD

**Issue by bug400** [conda/conda-build#2706]
### Actual Behavior

When converting the test package hello from Linux to Windows the sha256 hash for the renamed file "hello-script.py" is wrong. Installing the package on Windows throws a sha256 mismatch warning. The sha256 hash in the "info/paths.json" file is wrong for that file. If the package is generated on windows, the sha256 hash is correct.

### Expected Behavior
Correct sha256 hash value in "info/paths.json"

### Steps to Reproduce
Unpack the tar file attached into a temporary directory
Run the script "build_hello.sh" on Linux
It builds the package and converts it to several platforms
Check sha256 checksum in "info/paths.json" of the win-64 package version
[sha-problem.zip](https://github.com/conda/conda-build/files/1752522/sha-problem.zip)

##### `Output of conda info`

     active environment : None
     user config file : /home/achim/.condarc
     populated config files : /home/achim/.condarc
          conda version : 4.4.10
      conda-build version : 3.5.0
         python version : 3.6.4.final.0
       base environment : /home/achim/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/bug400/linux-64
                          https://conda.anaconda.org/bug400/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/achim/miniconda3/pkgs
                          /home/achim/.conda/pkgs
       envs directories : /home/achim/miniconda3/envs
                          /home/achim/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-36-generic neon/16.04 glibc/2.23
                UID:GID : 1101:1101
             netrc file : None
           offline mode : False

**Comment by msarahan** [comment]
Thanks for reporting this.  We will fix it, but I'm not sure what the timeline is.  Because this is only a warning, I'm afraid it might need to wait a little while.

**Comment by msarahan** [comment]
Thanks @MatthieuDartiailh - it's going to be somewhere in convert.py, I'm guessing.  Here's one place we compute hashes for windows paths: https://github.com/conda/conda-build/blob/master/conda_build/convert.py#L324

Hopefully that helps you get started.

**Comment by MatthieuDartiailh** [comment]
One quick question, is only the content of the file encoded in the sha or also its name ?

**Comment by msarahan** [comment]
I believe it is only the content of the file.  If you find otherwise, let's discuss.

**Comment by MatthieuDartiailh** [comment]
Ok thanks

**Comment by bug400** [comment]
I installed conda-build 3.6.0 and built package under Linux. Installing the converted package on Windows 64 throws a warning that the converted script file has an incorrect size. The sha256 warning does not appear any more.
