### ISSUE TITLE
recipe version not checked in dependencies, can cause infinite rebuilds

### ISSUE THREAD

**Issue by minrk** [conda/conda-build#271]
In conda/conda-recipes, I tried `conda build gcc-4.9`, which depends on cloog-0.18.1. The cloog recipe in the same repo provides 0.18.0, but in the fallback-to-recipe logic, the version isn't checked, so the build will just build cloog-0.18.0, reject it, and rebuild it again forever:

```
BUILD START: gcc-4.9.1-0
Fetching package metadata: .....
Missing dependency cloog, but found recipe directory, so building cloog first
BUILD START: cloog-0.18.0-0
...
BUILD END: cloog-0.18.0-0
Nothing to test for: cloog-0.18.0-0
# If you want to upload this package to binstar.org later, type:
#
# $ binstar upload /Users/minrk/conda/conda-bld/osx-64/cloog-0.18.0-0.tar.bz2
#
# To have conda build upload to binstar automatically, use
# $ conda config --set binstar_upload yes
BUILD START: gcc-4.9.1-0
Fetching package metadata: .....
Missing dependency cloog, but found recipe directory, so building cloog first
BUILD START: cloog-0.18.0-0
```

which continues rebuilding cloog indefinitely, apparently forever (it had done it a dozen times before I noticed).

This is on OS X 10.10.

**Comment by stuarteberg** [comment]
#393 is a duplicate of this, but that one has more discussion at this point, so this ought to be closed.
