### ISSUE TITLE
Multiple build variants ought to have different file name?

### ISSUE THREAD

**Issue by christianbrodbeck** [conda/conda-build#2717]
I'm building a package that uses numpy through Cython, so I'm [pinning numpy](https://conda.io/docs/user-guide/tasks/build-packages/variants.html) in [meta.yaml](https://github.com/christianbrodbeck/Eelbrain/blob/r/0.27/conda/eelbrain/meta.yaml)

```
...

requirements:
  build:
   ...
    - numpy  {{ numpy }}

  run:
   ...
    - numpy {{ numpy }}

```

and building against multiple versions with [conda_build_config.yaml](https://github.com/christianbrodbeck/Eelbrain/blob/r/0.27/conda/eelbrain/conda_build_config.yaml)

```
python:
  - 2.7

numpy:
  - 1.13
  - 1.11

pin_run_as_build:
    numpy:
      min_pin: x.x
      max_pin: x.x

```

### Actual Behavior

In the latest version, `conda build` builds twice, but uses the same filename (`eelbrain-0.27.2-py27_0.tar.bz2`), so the second build overwrites the first one.

### Expected Behavior

Conda used to generate two separable builds using a hash string.

This is related to https://github.com/conda/conda-build/issues/2554, but I think since I am using numpy's C API I actually need multiple builds? At least that's what the [docs](https://conda.io/docs/user-guide/tasks/build-packages/variants.html#build-variants) imply.

##### `Output of conda info`

```
     active environment : None
            shell level : 0
       user config file : /Users/christian/.condarc
 populated config files : /Users/christian/.condarc
          conda version : 4.4.11
    conda-build version : 3.5.1
         python version : 2.7.12.final.0
       base environment : /Users/christian/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/christianbrodbeck/osx-64
                          https://conda.anaconda.org/christianbrodbeck/noarch
                          https://conda.anaconda.org/ncil/osx-64
                          https://conda.anaconda.org/ncil/noarch
                          https://conda.anaconda.org/mittner/osx-64
                          https://conda.anaconda.org/mittner/noarch
          package cache : /Users/christian/anaconda/pkgs
                          /Users/christian/.conda/pkgs
       envs directories : /Users/christian/anaconda/envs
                          /Users/christian/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.11 requests/2.12.4 CPython/2.7.12 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 505:20
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
You're seeing a problem with conda-build not recognizing numpy as a "used" variable.  Sadly, because numpy was so special in the past, handling it is fragile.  I recommend that you change your recipe to this:

```
requirements:
  build:
    - numpy 1.11.*
  run:
    - {{ pin_compatible('numpy') }}
```

You don't need to loop over numpy.  You can if you really want to (aside from this bug, of course), but it is sufficient to build against an old version, and assume forward compatibility.  The ``1.11.*`` pin above is simply "the oldest numpy version that you know works with your software"

**Comment by christianbrodbeck** [comment]
Thanks! I did not know forward compatibility is that reliable.

**Comment by msarahan** [comment]
It isn't always that reliable for all libraries, but numpy maintainers are exceptional in their commitment to maintain it.
