### ISSUE TITLE
Set CONDA_BUILD_SYSROOT default value

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2719]
Appears that the Anaconda compilers will set a default `CONDA_BUILD_SYSROOT` if not otherwise set using `$(xcrun --show-sdk-path)` in commit ( https://github.com/AnacondaRecipes/aggregate/commit/09c34da6b279023dd23b1536d132ea5f0c4a8a01 ) (some time ago). Seems like it would make sense to elevate this logic to `conda-build` itself (if this hasn't already happened). Thoughts?

**Comment by mingwandroid** [comment]
You are meant to set this value in conda_build_config.yaml.

**Comment by mingwandroid** [comment]
https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml#L30-L31

**Comment by jakirkham** [comment]
Right. Asking if we can have a sensible default in `conda-build` if it is not set. Unclear why the answer is no sense the compilers do this anyways. 😕

**Comment by mingwandroid** [comment]
No, we are trying to move away from hardcoding things in conda-build.

**Comment by mingwandroid** [comment]
Maybe it's the name that's causing you to ask this question? If it had been called ANACONDA_DISTRIBUTION_CUSTOM_CLANG_COMPILER_SYSROOT would that have made it more obvious that this is not some innate feature of conda-build?

**Comment by mingwandroid** [comment]
As a further attempt at explaining this:

If you are not using our compilers then nothing will ever read CONDA_BUILD_SYSROOT so there's no value in a fallback. If you are using our compilers then the activate script contains its own fallback for when you forgot to pass conda_build_config.yaml (but actually I'm tempted to just raise an error here as not passing a sysroot risks all sorts of problems).

**Comment by jakirkham** [comment]
Wasn't asking for it to be hard coded. Was asking that if the user doesn't set this that it defaults to the macOS SDK that the user would have built with anyways. Just like what is being done in that compiler recipe.

In any event, it sounds like you are saying the environment variable is not used by anything other than those compilers? If so, great. Agree that there is little value in setting it anywhere else then. Though it was clear that `CONDA_BUILD_SYSROOT` affected the compilers, it was not clear to me that nothing else used it.

On a totally different note, it's unclear to me how to dynamically set things in `conda_build_config.yaml`. For instance what works on Travis CI may not work on different computers I or coworkers have access to. Even though they may all have the right macOS SDK, I can't see a good way to find where it is located in `conda_build_config.yaml`. Even being able to pass an environment variable in that would affect `conda_build_config.yaml` would go a long way. Though perhaps not setting it at all and expecting users to configure XCode correctly could be another solution. Thoughts?

**Comment by mingwandroid** [comment]
> it's unclear to me how to dynamically set things in conda_build_config.yaml

echo "value:" >> `conda_build_config.yaml`

> For instance what works on Travis CI may not work on different computers I or coworkers have access to.

They should download Xcode SDKs and put them in /opt, otherwise each machine will be differently configured snowflakes and things will fail differently on each.

> Though perhaps not setting it at all and expecting users to configure XCode correctly could be another solution

I have no interest in Xcode at all from a package building POV (or any other POV to be honest); I do not install it on any computers. Not only do I not install Xcode, nor do I install Apple's command line tools. These things do not help with reproducibility. That's why we use known SDKs and build our own compilers.

**Comment by mingwandroid** [comment]
> Wasn't asking for it to be hard coded. Was asking that if the user doesn't set this that it defaults to the macOS SDK that the user would have built with anyways

This is just another form of hard-coding, the only difference is that the source of the hard-coding is elsewhere.
