### ISSUE TITLE
File-less render

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#2722]
Would it be possible to have [`render`](https://github.com/conda/conda-build/blob/3.6.0/conda_build/api.py#L29-L30) take in a loaded string `meta.yaml`? The version bump bot is getting the `meta.yaml` from github and thus doesn't have a file to work from.

### Actual Behavior
`render` requires a file path to a recipe

### Expected Behavior

`render` could take in a recipe which has already loaded into a string.

**Comment by msarahan** [comment]
No, not really. There's a lot of looking around for other recipe files that goes on, and omitting that stuff completely has interesting side effects.  For example, our notion of whether we have a top-level MetaData object or an output MetaData object is basically a check on the state of the metadata's path attribute.  In the test suite, I write a temporary directory somewhere, write a temporary meta.yaml in there, and then render that temporary directory.
