### ISSUE TITLE
Add requirements to perform outputs packaging step

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2730]
One package that I'm trying to build both conda and wheel packages for requires `setuptools_scm` to run `setup.py` unfortunately. As a result, the wheel packaging step fails. Is there some way to add requirements that are only needed for the output step?

**Comment by msarahan** [comment]
Yes, outputs have their own requirements sections.  https://github.com/AnacondaRecipes/curl-feedstock/blob/master/recipe/meta.yaml#L28-L34

**Comment by jakirkham** [comment]
Thanks Mike! Had seen `requirements` used and even `requirements/run`, but not `requirements/host` and `requirements/build`. Though they did work ok for this use case. Glad to see that this is supported behavior and not me finding a neat hacky. :)
