### ISSUE TITLE
Conda Build should log the version of conda used to build a package

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2731]
Right now, if I open a tarball and peek at the top of meta.yaml, I see:
```
[nwani@somemachine 1520249712 ]$ cat info/recipe/meta.yaml 
# This file created by conda-build 3.4.2
# ------------------------------------------------
```

However, this is not sufficient to pin point the exact environment used while building the package. A lot also depends on the version of Conda being used.

**Comment by msarahan** [comment]
check info/about.json.  I think it has everything that you ask for here.
