### ISSUE TITLE
Output environment not activated on Windows

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2735]
Tried to build conda and wheel packages in PR ( https://github.com/conda-forge/numcodecs-feedstock/pull/17 ). However it seems that on Windows, despite creating an environment with the needed dependencies, `setuptools` still tries to download `setuptools_scm`. Looking at the traceback that follows, it looks like the output packaging step is being run in `root` instead of the environment with `setuptools_scm`, which would explain it. Guessing activation of the environment used for the output packaging step does not occur on Windows? Log linked below. This problem does not occur on Unix.

ref: https://ci.appveyor.com/project/conda-forge/numcodecs-feedstock/build/1.0.34/job/9d4u18qv7k6rjkcx

**Comment by jakirkham** [comment]
Thanks for the advice Mike. Gave that a try, but it still seems to not be activating the environment. That said, I'm new at this and could be making a mistake somewhere. Same PR, but a newer commit at the end. One of the logs is linked below. Any thoughts you might have would be appreciated.

ref: https://ci.appveyor.com/project/conda-forge/numcodecs-feedstock/build/1.0.36/job/r9ajndf1bbidowab

**Comment by msarahan** [comment]
I think the problem is that env activation is done in a way that doesn't affect wheels right now (only works for packaging conda packages).  That should be pretty easy to fix.

**Comment by msarahan** [comment]
@jakirkham I think #2744 will fix the issue.  If you can test, I'd appreciate it.  I did clone your numcodecs repo/branch, and it built the wheel just fine locally.

**Comment by jakirkham** [comment]
Thanks @msarahan. Happy to test.

Given what is needed for the test, I'll try to get access to a Windows machine. Should be able to do that by Friday at the earliest. Will report back what I find after. Does that work for you?

**Comment by msarahan** [comment]
Sure.  I'll probably merge it before then, but I'll still appreciate hearing whether or not it works for you.

**Comment by jakirkham** [comment]
Ok. Will do.

If there are non-Windows parts that I can test, should be able to get those sooner.

**Comment by msarahan** [comment]
The wheel stuff should have broken on non-windows, too, but what probably happened was that it fell back to the system python or something like that.  This fix was necessary on all platforms.

**Comment by jakirkham** [comment]
So the new `conda-build` worked on 64-bit, but failed on 32-bit. However I don't think the 32-bit failure is related to packaging wheels, but some other issue with `conda-build`.
