### ISSUE TITLE
`file://` or `//` Network Locations are inconsistent and possibly broken for git_url

### ISSUE THREAD

**Issue by y2kbugger** [conda/conda-build#2753]
Something about the way network locations are handled are causing me a lot of issues, different arguments/yaml config are requiring different formats. I actually have not been able to find one that works for a network location in meta.yaml for git_url.

`//` vs `file://` in the command line arguments cost me a day:

    $ conda build --override-channels --output-folder //domain/.../dt/customchannel --channel file://domain/.../dt/customchannel .

now I am trying to move from the meta.yaml source:

    source:
        git_url: ./

to 

    source:
        //domain/../dt/MyRemoteBareRepo 

which give the Error:

    Error: Attempting to mirror to C:\domain\...\dt\MyRemoteBareRepo which is outside of GIT_CACHE C:\Users\myuser\conda-bld\git_cache

and trying:

    source:
        file://domain/../dt/MyRemoteBareRepo 

causes git to error out during build.

Probably relate #2585 

### Actual Behavior

Cannot use a network drive location for git_url

### Expected Behavior

This should work using `//` or `file://` or both. `file:///` also doesn't work

##### `Output of conda info`
```
     active environment : None
       user config file : C:\Users\zdkohler\.condarc
 populated config files : C:\Users\zdkohler\.condarc
          conda version : 4.4.11
    conda-build version : 3.7.0
         python version : 3.6.0.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\zdkohler\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\zdkohler\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\zdkohler\.conda\envs
               platform : win-64
             user-agent : conda/4.4.11 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Sorry, yes, this is a known issue.  file:// urls are not currently supported.  We recommend mapping a drive letter to your network location.  PRs are welcome to fix this, but it's not very high on our priority list.  Terribly sorry it has wasted your time, but it is not a common problem/request.

**Comment by y2kbugger** [comment]
Thanks for the quick response. The `//domain/...` codepath seems very close to working, if the proper local cache path was provided. Are there deeper issues than that when dealing with file:// urls?

At least a better error message stating that they are unsupported would be helpful.
