### ISSUE TITLE
'fix_shebang' is fixing any shebang containing 'python'

### ISSUE THREAD

**Issue by jrevans** [conda/conda-build#2761]
### Actual Behavior

The pattern matching in 'conda_build/post.py:fix_shebang' will "fix" any shebang line that contains the text 'python' and cause it to be replaces with '#!/opt/anaconda1anaconda2anaconda3/bin/python'

This means that when I make a conda package where the shebang line is any of the following, then it will be replaced with an incorrect shebang line.

```#!/path/to/conda-bld/prefix/bin/my_fancy_python_wrapper```
```#!/path/to/conda-bld/prefix/bin/ipython```
```#!/path/to/conda/python/install/area/conda-bld/prefix/bin/my_script```

All three of the above lines will cause the 'fix_shebang' function to replace with a simple call to python, simply because it checks for the presence of 'python' in the shebang line.

### Expected Behavior

If python is not being invoked, the shebang line should remain untouched.

##### `Output of conda info`

``` 
      conda version : 4.4.11
conda-build version : 3.7.1
     python version : 3.6.4.final.0
           platform : linux-64
         user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Linux/3.10.0-514.2.2.el7.x86_64 rhel/7.0 glibc/2.17
         netrc file : None
       offline mode : False
```

**Comment by msarahan** [comment]
sorry about that.  I'm surprised this hasn't caused more issues.  I guess most people don't depend on shebangs for running their python scripts.  We'll fix this soon.

**Comment by msarahan** [comment]
I think #2786 might take care of this.  Please confirm @jrevans.  I'm also curious whether you think we need more work here.  It seems strange that only python would need a shebang fix.

**Comment by jrevans** [comment]
#2786 seems to address the problems I was having.
