### ISSUE TITLE
CONDA_BLD_PATH causes inclusion of extra "_placehold_placehold_[...]" files in package.

### ISSUE THREAD

**Issue by stevenengler** [conda/conda-build#2771]
Hi, when I run `conda-build` with `CONDA_BLD_PATH` set, the resulting `tar.bz2` package file contains many extra `_placehold_placehold_placehold_[...]` files.

### Actual Behavior

    $ CONDA_BLD_PATH=./build conda-build . --no-test --no-anaconda-upload --no-build-id --output-folder output-1
    $ tar -tvf output-1/linux-64/cryptography-2.1.4-py36_0.tar.bz2 | wc -l
    8675
    $ tar -tvf output-1/linux-64/cryptography-2.1.4-py36_0.tar.bz2
        <lines such as>
    -rw-rw-r-- root/root     28025 2018-03-20 08:22 info/recipe/build/_h_env_placehold_placehold_[...]_placeho/lib/python3.6/site-packages/setuptools/_vendor/packaging/specifiers.py
    -rw-rw-r-- root/root     28052 2018-03-20 08:22 info/recipe/build/_h_env_placehold_placehold_[...]_placeho/lib/python3.6/lib2to3/pytree.py

### Expected Behavior

I would expect the output to be the same as without `CONDA_BLD_PATH`.

    $ conda-build . --no-test --no-anaconda-upload --no-build-id --output-folder output-2
    $ tar -tvf output-2/linux-64/cryptography-2.1.4-py36_0.tar.bz2 | wc -l
    253
    $ tar -tvf output-2/linux-64/cryptography-2.1.4-py36_0.tar.bz2
        <looks normal, no "_placeholder_placeholder_placeholder_[...]" files>

### Steps to Reproduce

Download the conda-forge "cryptography" recipe and build it.

##### `Output of conda info`

```
     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.4.11
    conda-build version : 3.6.0
         python version : 3.6.4.final.0
       base environment : /app/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /app/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /app/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Linux/4.15.5-041505-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
This is a bug, for sure.  Unfortunately, it's also a fringe use case.  You are disabling and re-routing a lot of default behavior, and that does expose you to greater risk of bugs.  We'll fix it, but it could be a while.  PRs welcome in the meantime.  You can try ``--croot`` instead of ``CONDA_BLD_PATH`` as an env var, though they should be equivalent.  croot is more well-tested, though, as we use it in our internal CI system (but only on Windows, so that may be less relevant).

**Comment by stevenengler** [comment]
Thanks, and no problem, I'm sure there are more pressing things to work on. I'll try to take a look at this once the school term is over. Also, the same behaviour seems to occur with just `conda-build . --croot ./build` as well, so this seems to be a bug with specifically `CONDA_BLD_PATH` and `--croot`.

Do you have any thoughts or ideas on what could be causing this? If so, it would give me a place to start looking.

**Comment by msarahan** [comment]
Problems of this kind generally result from confusion around detection of "new" files.  Conda-build mostly operates around this mechanism:

1. create host prefix environment
2. take a snapshot of files in that environment
3. run the build script
4. take another snapshot of the host prefix
5. compute new files - ones that didn't exist in the earlier snapshot (we do not currently compute changed files)
6. bundle those new files

Here, looking at your output, it appears that some files are being created in the recipe directory, which is then being copied over later.  The right fix here is perhaps twofold:

1. figure out why the recipe is creating files in the recipe folders (alongside meta.yaml)
2. make conda-build recognize that situation, and warn or throw an error about it.

I think it is sane to say that recipes should never modify their recipe folder during build.  They can read and copy from the recipe folder, but writing anything into that folder leads to insanity.

**Comment by msarahan** [comment]
PS: to clarify, when I say "recipe folder," I'm talking about the original one - the one you point conda-build to in the first place.  Not the one that ends up in your package - that's a derivative.  If your original one does not end up being modified in place, then this is a more interesting conda-build bug, but I don't think the recipe folder gets copied to any temporary location before evaluating it.

**Comment by remram44** [comment]
This always looked very stupid, but now it's actually causing my build to fail so I would appreciate a fix.
```
conda.CondaError: Unable to create prefix directory '/home/remram/miniconda/conda-bld/reprozip_1522445565775/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl'.
Check that you have sufficient permissions.
```
