### ISSUE TITLE
Getting wheel paths via conda-build API

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2781]
Trying to figure out the best way to get at `*.whl` paths from the `conda-build` API. Used `get_output_file_paths`, but it seems that only returns the `conda` packages. Is there a good way to determine the file paths to the `*.whl` packages generated? Basing this off of PR ( https://github.com/conda-forge/pyfftw-feedstock/pull/16 ).

**Comment by msarahan** [comment]
I don't really know.  This hinges completely on pip or wheel's ability to generate this info.  For the time being, conda-build doesn't know enough about how a wheel filename is constructed to say anything before the build (which is required for get_output_file_paths).

**Comment by jakirkham** [comment]
That's fair. Unfortunately I don't really know how to solve this either. Maybe we can ask a wheel expert? Would you be able to advise @njsmith or be able to suggest someone that can?

**Comment by njsmith** [comment]
I don't think there is any way to predict a wheel filename without running setup.py. For example, it depends on whether the package contains any C extensions. Can you build it and then see what you got?

**Comment by msarahan** [comment]
Thanks @njsmith. conda-build can certainly return the path of the wheel file that got created, but the part of the API that @jakirkham has asked about here is pre-build.  You can ask conda-build what the file paths *would* be, and this information is obtainable without the build.  The most common usage is for uploading packages after build - build them, then get their paths, then upload them.  This is a use case that we can solve by having the build return the paths of files (the API build() function already does this; the CLI does not).  It sounds like @jakirkham is asking about some other usage, though.

**Comment by jakirkham** [comment]
So asked about predicting the name as the [conda-forge upload script currently uses `get_output_file_paths`]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/6495ba546d6c136c434b83a4fde9eba5e02b107e/recipe/upload_or_check_non_existence.py#L110 ). Though if `conda-build` can give us a list of all paths afterwards (or perhaps even replace the upload script altogether), I can't see a good reason not to do that.

There are some independent questions of how we might show badges for this sort of thing in the feedstock README, but this is icing on the cake (that we haven't finished baking yet). So we can table these for now I think.
