### ISSUE TITLE
Jinja error when using api.render for different platform

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#2785]
I am attempting to use the conda build api to render a recipe for an alternate platform (e.g. platform="win" on linux) and receiving an error:

"Undefined Jinja2 variables remain (['group']).  Please enable source downloading and try again."

The line in the recipe that triggers the error is the following, which is used to fetch a version string from a header file:
```
{% set version = load_file_regex(load_file=os.path.join(ipproot,'include/ippversion.h'), regex_pattern = ".*IPP_VERSION_STR.*?(\d+\.\d+\.\d+).*").group(1) %}
```
The group() method call in the jinja line is the culprit. The python call that results in the error when the line above is in a recipe is:
```
retval = api.render("path/to/meta.yaml",platform="win")
```
If the "platform" value passed in is the same as the native platform, there is no error and the returned results are correct. It is only when a platform other than the native platform is passed that I see the error.

##### `Output of conda info`

```

     active environment : base
    active env location : /localdisk/work/todd/miniconda3
       user config file : /nfs/site/home/todd/.condarc
 populated config files : /nfs/site/home/todd/.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 3.6.3.final.0
       base environment : /localdisk/work/todd/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /localdisk/work/todd/miniconda3/pkgs
                          /nfs/site/home/todd/.conda/pkgs
       envs directories : /localdisk/work/todd/miniconda3/envs
                          /nfs/site/home/todd/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.3 Linux/3.13.0-87-generic ubuntu/14.04 glibc/2.19
                UID:GID : 11573498:22002
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
ah, dang, sorry, you already told me.  It's the group function call.  Let me go back at it.

**Comment by msarahan** [comment]
Nope, still not failing.  I did have the .group(1) in my recipe, and I've moved it up to match the place that you have it:

```
# This recipe exercises the use of regex-supplied variables in jinja template strings,

# it uses load_file_regex from conda_build.jinja_context to populate some fields
# with values fed from meta.yaml files.

{% set data = load_file_regex(load_file='meta.yaml',
                              regex_pattern='git_tag: ([\\d.]+)',
                              from_recipe_dir=True).group(1) %}

package:
  name: conda-build-test-get-regex-data
  version: {{ data }}

source:
  git_url: ../../../../../conda_build_test_recipe
  git_tag: 1.21.0

build:
  entry_points:
    - entry = conda_version_test.manual_entry:main

requirements:
  build:
    - python {{ PY_VER }}*

```

**Comment by tomashek** [comment]
Ah, I found out what was causing the problem!

In my recipe, the "load_file" value was dependent upon another variable (ipproot) that was subject to the platform filters. The actual value of ipproot is a path that is not found on platforms other than the native one, so adding "plat=xxx" made that path not found. When load_file_regex() fails, it leaves the attached ".group(1)" unevaluated for the rest of the jinja pass, prompting jinja to report the error. Or something like that. The error message certainly doesn't help point to the error source in this case!

To replicate, you can replace the "load_file" parameter value with gibberish.

So the jinja error was a red herring.
