### ISSUE TITLE
On OSX, library install name should contain @rpath

### ISSUE THREAD

**Issue by dfroger** [conda/conda-build#279]
In order to make is easier for user to link executable (not packaged with conda) with library
installed with conda, library install names shoud contain `@rpath`.

Current situtation
==================

From what I understand looking at `pkgs/hdf5-1.8.13-1/lib/libhdf5.dylib` and
`pkgs/hdf5-1.8.13-1/bin/h5dump` here is the current situation, sorry if
I missunderstand something, or miss other source of informations:

On OS X, for a conda pakage `foo` containing a library `libfoo.dylib` and an executable `xfoo`,
`conda install foo` yields to something like (actually, the the binary files are just
extracted from the package, but it doesn't matter for the example):

    $ ROOT=$PWD
    $ mkdir -p $ROOT/miniconda/pkgs/foo/bin $ROOT/miniconda/pkgs/foo/lib
    
    $ cd $ROOT/miniconda/pkgs/foo/lib
    $ echo 'int foo(int a, int b){return a+b;}' > foo.c
    $ clang foo.c -dynamiclib -install_name libfoo.dylib -o libfoo.dylib
    
    $ cd $ROOT/miniconda/pkgs/foo/bin
    $ echo 'int foo(int,int); int main(){return foo(2,4);}' > xfoo.c
    $ clang xfoo.c -L../lib -lfoo  -o xfoo
    $ install_name_tool -change libfoo.dylib '@loader_path/../lib/libfoo.dylib' xfoo
    
Now, the directory libfoo.dylib and xfoo moved for example as:

    $ mkdir -p $ROOT/miniconda/envs/envname/lib $ROOT/miniconda/envs/envname/bin
    $ ln $ROOT/miniconda/pkgs/foo/lib/libfoo.dylib $ROOT/miniconda/envs/envname/lib/libfoo.dylib
    $ ln $ROOT/miniconda/pkgs/foo/bin/xfoo $ROOT/miniconda/envs/envname/bin/xfoo
    
safely, because in `xfoo`, the install name of the dependent shared library `foo `in relative to where `xfoo` is.
`foo` and `xfoo` are rellocatables.

Problem
=======

A user developping an executable `yfoo` needing the `foo` library will want to reuse the library `libfoo.dylib`
provided by conda, due to the easiness and flexibility of the installation with conda.

However, this require to run `install_name_tool -change` on the created executable:

    $ mkdir $ROOT/perso ; cd $ROOT/perso
    $ echo 'int foo(int,int); int main(){return foo(2,4);}' > yfoo.c
    $ clang yfoo.c -L$ROOT/miniconda/envs/envname/lib -lfoo  -o yfoo
    $ install_name_tool -change libfoo.dylib "$ROOT/miniconda/envs/envname/lib/libfoo.dylib" yfoo
   
Proposal
========

The library install name should contain `@rpath`, so `conda install foo` yields to something like this:

    $ mkdir -p $ROOT/miniconda_bis/pkgs/foo/bin $ROOT/miniconda_bis/pkgs/foo/lib
    
    $ cd $ROOT/miniconda_bis/pkgs/foo/lib
    $ echo 'int foo(int a, int b){return a+b;}' > foo.c
    $ clang foo.c -dynamiclib -install_name '@rpath/libfoo.dylib' -o libfoo.dylib
    
    $ cd $ROOT/miniconda_bis/pkgs/foo/bin
    $ echo 'int foo(int,int); int main(){return foo(2,4);}' > xfoo.c
    $ clang xfoo.c -L../lib -lfoo  -o xfoo
    $ install_name_tool -change '@rpath/libfoo.dylib' '@loader_path/../lib/libfoo.dylib' xfoo
    
    $ mkdir -p $ROOT/miniconda_bis/envs/envname/lib $ROOT/miniconda_bis/envs/envname/bin
    $ ln $ROOT/miniconda_bis/pkgs/foo/lib/libfoo.dylib $ROOT/miniconda_bis/envs/envname/lib/libfoo.dylib
    $ ln $ROOT/miniconda_bis/pkgs/foo/bin/xfoo $ROOT/miniconda_bis/envs/envname/bin/xfoo
    
So that the user can links with `libfoo.dylib` using rpath:

    $ mkdir $ROOT/perso_bis ; cd $ROOT/perso_bis
    $ echo 'int foo(int,int); int main(){return foo(2,4);}' > yfoo.c
    $ clang yfoo.c -L$ROOT/miniconda_bis/envs/envname/lib -Wl,-rpath,$ROOT/miniconda_bis/envs/envname/lib -lfoo -o yfoo

**Comment by asmeurer** [comment]
I think if we make that change we also need to add to the logic that [changes the dependent install names](https://github.com/conda/conda-build/blob/e8587bb49d47b1255d6137b273b45b94b71fb4e7/conda_build/post.py#L151-L163) to look for install names that start with @rpath.

**Comment by dfroger** [comment]
I think we only need to change the install name of library, and that install name of dependent library are already good, because **install name** are used at **link time**, and **dependant install name** are used at **load time**.

Simillary, **install name** are not used at **load time**, and **dependant install name** are not used at **link time**

Install name of `$ROOT/miniconda/pkgs/foo/lib/libfoo.dylib` would change from `libfoo.dylib` to `@rpath/libfoo.dylib`, so that when linking an executable with `libfoo.dylib`, with can use `-rpath=$ROOT/miniconda/pkgs/foo/lib`, and when the executable will load the library, in will search it in `$ROOT/miniconda/pkgs/foo/lib/libfoo.dylib` (the dependant install name) and find it, instead of `libfoo.dylib`, which require to set environment variable, or to change the dependant install name with `install_name_tool -change`. We could also use `-rpath=@executable_path/...` or `-rpath=@loader_path/..` if we want relative path.

Install name of dependant library `libfoo.dylib` in `$ROOT/miniconda/pkgs/foo/bin/xfoo` is `@loader_path/../lib/libfoo.dylib` and is good. `xfoo` will find `libfoo.dylib` because using `@loader_path../lib/libfoo.dylib`, install name `@rpath/libfoo.dylib` in `libfoo.dylib` does not play any role. **install name `@rpath/libfoo.dylib` plays a role only at link time, not at load time**.

Or if `$ROOT/miniconda/pkgs/foo/lib/libbar.dylib` tries to load `$ROOT/miniconda/pkgs/foo/lib/libfoo.dylib`, dependant install name `@load_path/./libfoo.dylib` (or something like that) is good too for the same reason. install name of `libbar.dylib` would be as `@rpath/libbar.dylib` (as for `libfoo.dylib`), so it can be linked for external executable.

Note that we know in advance the relative path between `$ROOT/miniconda/pkgs/foo/bin/xfoo` and `$ROOT/miniconda/pkgs/foo/lib/lifoo.dylib` which will never change, so install name of the dependant library `libfoo.dylib` in `xfoo` is relative, so both can be moved together.

By contrast, we don't know the path of the external executable the user want to link `libfoo.dylib` with, so we can not use a fixed relative path for the install name. So we need to let the user the possibilty to specify at link time the value of the dependant install name of `libfoo.dylib` in the executable, this is what `@rpath` is for.

Sorry for the long comment again...

**Comment by dfroger** [comment]
Indeed you're absolutely right in your last comment about the function osx_ch_link :-) I stupidely missundersand the comment, sorry.

i'm experimenting building packages with these changes, and will propose a pull request when it's ready.

**Comment by asmeurer** [comment]
See https://github.com/conda/conda-build/pull/312 (still WIP).

**Comment by ddale** [comment]
Any estimate on when this issue will be resolved? I have a project (http://github.com/praxes/sweep2png) for which I can't create conda packages, although I was able to do so a couple months ago. Or should I try with an older version of conda-build?

**Comment by asmeurer** [comment]
Hmm, why doesn't it work? Nothing should have changed in master regarding this. The issues this fixes have existed since the beginning.

**Comment by ddale** [comment]
Hmm. Maybe its a different issue. Four months ago, I was able to build this recipe, run the test, and upload the result to https://binstar.org/praxes/sweep2png/files. Now, when I try to build the recipe, it fails during the test:

```
[...]
 cp sweep2png /Users/darren/.conda/envs/_build/bin/sweep2png
number of files: 1
install_name_tool -change libpng15.15.dylib @loader_path/../lib/libpng15.15.dylib /Users/darren/.conda/envs/_build/bin/sweep2png

BUILD END: sweep2png-master-0
TEST START: sweep2png-master-0
Fetching package metadata: ............
Solving package specifications: 
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    sweep2png-master           |                0         1.1 MB

The following NEW packages will be INSTALLED:

    sweep2png: master-0

Fetching packages ...
sweep2png-mast 100% |################################| Time: 0:00:00  58.35 MB/s
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
[      COMPLETE      ] |##################################################| 100%
+ sweep2png Si_5grains_mesh.log map/Si_70 0.7 cubic
dyld: Library not loaded: @loader_path/../lib/libpng15.15.dylib
  Referenced from: /Users/darren/.conda/envs/_test/bin/sweep2png
  Reason: image not found
/Users/darren/conda-bld/test-tmp_dir/run_test.sh: line 3: 25224 Trace/BPT trap: 5       sweep2png Si_5grains_mesh.log map/Si_70 0.7 cubic
TESTS FAILED: sweep2png-master-0
```

**Comment by ddale** [comment]
This was my mistake, I must have introduced a problem in my conda recipe. Sorry for the noise. Do you want me to delete unhelpful comments?

**Comment by asmeurer** [comment]
Don't worry about it.

**Comment by denis-bz** [comment]
Is `@rpath/./libnetcdf.7.dylib` with an absolute .dylib version an error ?
After `conda install -c conda-forge pynco` on macos 10.10 I get

    ncks --version  # many nc* same
    dyld: Library not loaded: @rpath/./libnetcdf.7.dylib
      Referenced from: /opt/local/py/miniconda2/bin/ncwa
      Reason: image not found
    Trace/BPT trap

    otool -L $conda/bin/ncwa  # macos
    @rpath/./libnetcdf.7.dylib (compatibility version 10.0.0, current version 10.0.0)
    @rpath/./libhdf5_hl.10.dylib (compatibility version 11.0.0, current version 11.1.0)
    @rpath/./libhdf5.10.dylib (compatibility version 11.0.0, current version 11.1.0)
    ...
which don't exist:

    ls -l $DYLD_FALLBACK_LIBRARY_PATH/libnetcdf*.dylib
    1290160 May 20 12:04 /opt/local/py/miniconda2/lib/libnetcdf.13.dylib
         18 May 20 12:04 /opt/local/py/miniconda2/lib/libnetcdf.dylib -> libnetcdf.13.dylib

This is likely my stupid error (TL;DR all of the above),
or should it be `@rpath/./libnetcdf.dylib` instead of `libnetcdf.7.dylib` ?

Thanks, cheers

**Comment by mingwandroid** [comment]
@denis-bz, you have a simple version mismatch here. Probably mixing conda-forge and defaults or something like that?

There's nothing wrong with having the `.7.` in the `LC_LOAD_LYLIB` command.

I have no idea why you're messing about with `DYLD_FALLBACK_LIBRARY_PATH` since it doesn't do anything anymore for the vast majority of users and usecases (since SIP).

**Comment by denis-bz** [comment]
@mingwandroid, the problem is that `conda` loaded files with `@rpath/./libnetcdf.7.dylib`,
which doesn't exist; the only libnetcdf*.dylib on the machine are the 2 I listed.
(`DYLD_LIBRARY_PATH` is a red herring, historical, unsetting it has no effect.)

**Comment by mingwandroid** [comment]
Please file a bug at http://github.com/conda-forge/pynco-feedstock but before you do, do your homework so you don't waste peoples' time.

This is a packaging error by the look of it and *nothing* to do with this issue at all (which you'd have known if you didn't treat it as TL;DR).
