### ISSUE TITLE
Getting 404 Error

### ISSUE THREAD

**Issue by AaronV77** [conda/conda-build#2790]
Hello, I'm getting a 404 error when trying to create a Conda package with an existing PYPI package using the conda-build command. 

Here is what I got when running the conda skeletion pypi ncep_client:

(Package_Builder) aaron@Hermes:~/Documents$ conda skeleton pypi ncep_client
Using url https://files.pythonhosted.org/packages/06/f6/bebe6589fd5ab44951947dcaea6993c61d70d97d0263913446ea6cc02733/ncep_client-1.0.0.tar.gz (7 KB) for ncep_client.
Downloading ncep_client
PyPI URL:  https://files.pythonhosted.org/packages/06/f6/bebe6589fd5ab44951947dcaea6993c61d70d97d0263913446ea6cc02733/ncep_client-1.0.0.tar.gz
Unpacking ncep_client...
done
working in /tmp/tmpf9vgy67zconda_skeleton_ncep_client-1.0.0.tar.gz
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/aaron/miniconda3/envs/Package_Builder/conda-bld/skeleton_1522297386706/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0
    certifi:         2018.1.18-py36_0     
    libedit:         3.1-heed3624_0       
    libffi:          3.2.1-hd88cf55_4     
    libgcc-ng:       7.2.0-hdf63c60_3     
    libstdcxx-ng:    7.2.0-hdf63c60_3     
    ncurses:         6.0-h9df7e31_2       
    openssl:         1.0.2o-h20670df_0    
    pip:             9.0.1-py36_5         
    python:          3.6.4-hc3d631a_3     
    pyyaml:          3.12-py36hafb9ca4_1  
    readline:        7.0-ha6073c6_4       
    setuptools:      38.5.1-py36_0        
    sqlite:          3.22.0-h1bed415_0    
    tk:              8.6.7-hc745277_3     
    wheel:           0.30.0-py36hfd4bba0_1
    xz:              5.2.3-h55aa19d_2     
    yaml:            0.1.7-had09818_2     
    zlib:            1.2.11-ha838bed_2    

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Applying patch: '/tmp/tmpf9vgy67zconda_skeleton_ncep_client-1.0.0.tar.gz/pypi-distutils.patch'
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
Writing recipe for ncep_client
--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

------------------------------------------------------------------------------------------------------------------
This is what I get when I run the conda-build ncep_client:

(Package_Builder) aaron@Hermes:~/Documents$ conda build ncep_client
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for ncep_client
INFO:conda_build.metadata:Attempting to finalize metadata for ncep_client
Solving environment: ...working... done
Solving environment: ...working... done
BUILD START: ['ncep_client-1.0.0-py36_0.tar.bz2']
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/aaron/miniconda3/envs/Package_Builder/conda-bld/ncep_client_1522298366059/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0
    certifi:         2018.1.18-py36_0     
    libedit:         3.1-heed3624_0       
    libffi:          3.2.1-hd88cf55_4     
    libgcc-ng:       7.2.0-hdf63c60_3     
    libstdcxx-ng:    7.2.0-hdf63c60_3     
    ncurses:         6.0-h9df7e31_2       
    openssl:         1.0.2o-h20670df_0    
    pip:             9.0.1-py36_5         
    python:          3.6.4-hc3d631a_3     
    readline:        7.0-ha6073c6_4       
    setuptools:      38.5.1-py36_0        
    sqlite:          3.22.0-h1bed415_0    
    tk:              8.6.7-hc745277_3     
    wheel:           0.30.0-py36hfd4bba0_1
    xz:              5.2.3-h55aa19d_2     
    zlib:            1.2.11-ha838bed_2    

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... done
Source cache directory is: /home/aaron/miniconda3/envs/Package_Builder/conda-bld/src_cache
Downloading source to cache: ncep_client-1.0.0_904eadfa58.tar.gz
Downloading https://pypi.io/packages/source/n/ncep_client/ncep_client-1.0.0.tar.gz
Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/n/ncep_client/ncep_client-1.0.0.tar.gz>
Elapsed: 00:00.566139

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download https://pypi.io/packages/source/n/ncep_client/ncep_client-1.0.0.tar.gz
------------------------------------------------------------------------------------------------------------------
Miniconda version: 4.5.0
conda-build version:  3.7.2

Any suggestions?

**Comment by msarahan** [comment]
It looks like your python package isn't available on the new PyPI yet, and we depend on that.  Take a look at 

I see your package on the old one, at https://pypi.python.org/pypi/ncep-client/1.0.0
but I get nothing when searching for it on the new one: https://pypi.org/search/?q=ncep

This seems like a PyPI issue that you should report to them.  I thought they should be mirroring each other's content, but it looks like there is some split.

We can hack in some horrible fallback into conda-build, but I think unless this proves to be a larger problem, it is better to wait on the PyPI team, and in the meantime to hack your generated meta.yaml file to change the source url to be https://files.pythonhosted.org/packages/06/f6/bebe6589fd5ab44951947dcaea6993c61d70d97d0263913446ea6cc02733/ncep_client-1.0.0.tar.gz

The value that's there right now is meant to make it easier to update your recipe as it changes over time, but that scheme isn't working because the new PyPI just doesn't have an entry for your package (yet?)

**Comment by AaronV77** [comment]
That is what I was thinking, but I just didn't know where to replace it in my meta.yaml file. Also the documentation for uploading any new packages to the new server is really good.

**Comment by AaronV77** [comment]
@msarahan I got some new information. So it ended up being a user error on my end with my .pypirc file not including a specified repo url for PyPi. I have no clue as to where twine uploaded my file to, but I got some information from the PyPi people on what  URL I should be using. 

Here is the URL to the issue I opened up over on their repo: https://github.com/pypa/warehouse/issues/3471

Here is the URL for the new information about the migration that they wanted me to share over here for anyone else that could potentially run into this issue as well: https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html

Lastly here is an example of what a .pypirc file should look like just in case as well: 

[distutils]
index-servers =
    pypi
    test

[pypi]
repository:https://upload.pypi.org/legacy/
username:the_username
password:the_password

[test]
repository:https://test.pypi.org/legacy/
username:the_username
password:the_password


Thanks for your help @msarahan !

**Comment by msarahan** [comment]
great, thanks for posting the info on what you learned.

**Comment by brainwane** [comment]
@msarahan Just to follow up on what @AaronV77 said, we'd love more conda users to check out our PyPI announcement

https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html

which has a list of migration steps. PyPI maintainers are also hosting IRC/Twitter livechat hours this week to hear from users and help with migration:

* Tuesday, April 3rd, 8am-9am PDT, 11am-noon EDT, 17:00-18:00 CEST,
8:30pm-9:30pm India, 15:00-16:00 UTC
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Warehouse/PyPI+beta+livechat&iso=20180403T10&p1=24&ah=1

* Thursday, April 5th, 5pm-6pm PDT, 8pm-9pm EDT, (April 5th) 8am-9am
Manila, (April 5th) 10am-11am Melbourne, (April 5th) 0:00-1:00 UTC
https://www.timeanddate.com/worldclock/fixedtime.html?p1=24&iso=20180405T19&msg=Warehouse/PyPI%20beta%20livechat&ah=1&low=4

so please consider joining us! Details in the blog post.

**Comment by msarahan** [comment]
Great, thanks.  I don't think I can make the live chat at either time, but I'll read up on the blog post to make sure I understand what's going on.
