### ISSUE TITLE
Test files not working

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#28]
From the support list:

Hi,

I've added a few test cases to my build recipe. The test fail if the module is not installed in the current conda environment on the import of mymodule in test1. i.e. If "conda-build --no-tests" is ran and the generated module is installed in current environment, a following conda-build has successful tests.

in meta.yaml:

test:
  # Python imports
  imports:
    - mymodule

  files:
    - test/test1.py
    - test/test2.py

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - python test1.py
    - python test2.py

doing a conda remove mymodule in current environment makes the build tests fail again.

Should the module being built be available to the tests, and how then? now it seems like it imports it from the current environment.

**Comment by msarahan** [comment]
fixed long ago by having contained build environments.
