### ISSUE TITLE
Flow-style lists in variant YAML files are parsed as selectors

### ISSUE THREAD

**Issue by StefansM** [conda/conda-build#2809]
### Actual Behavior

If I supply a list of variants in `conda_build_config.yaml` in YAML flow style, the list is parsed as a selector and stripped. For example, `id: [50, 90, 100]\n` is stripped by [`conda_build.metadata.select_lines`][select] to just `id:\n`.

[select]: https://github.com/conda/conda-build/blob/a1935008d0bd11f6179db751f3416749ebfa902f/conda_build/metadata.py#L171

### Expected Behavior

I expected flow-style lists to be treated in the same way as block-style lists. That is,

```yaml
id: [50, 90, 100]
```
is the same as
```yaml
id:
  - 50
  - 90
  - 100
```

##### `Output of conda info`

```     
active environment : None
       user config file : /bmm/home/sm2708/.condarc
 populated config files : /bmm/home/sm2708/.condarc
          conda version : 4.5.0
    conda-build version : 3.8.0
         python version : 3.6.4.final.0
       base environment : /data/sm2708/conda  (writable)
           channel URLs : file:///bmm/phyreengine/software/conda/linux-64
                          file:///bmm/phyreengine/software/conda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /data/sm2708/conda/pkgs
                          /bmm/home/sm2708/.conda/pkgs
       envs directories : /data/sm2708/conda/envs
                          /bmm/home/sm2708/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Linux/3.10.0-514.26.2.el7.x86_64 ol/7.3 glibc/2.17
                UID:GID : 1487:500
             netrc file : None
           offline mode : False
```

**Comment by StefansM** [comment]
The current parsing system seems wonderfully flexible in theory, but in practice the three different parsers (selectors, Jinja2 and YAML) don't play very nicely together. See #2815 for another example of an anti-synergy between the parsers.

I'm sure this has been discussed before, but I haven't been following development closely: is there any discussion about the benefits of breaking backwards compatibility (with a mandatory version tag for new versions)?

**Comment by msarahan** [comment]
If you would like to architect the meta.yaml schema versioning, it would be a welcome improvement.  Conda-build is first and foremost a useful tool for us (Anaconda) to build our packages.  It is serving that purpose well, and we're happy to see that it is also useful in the community.  I'm sorry it's not playing nicely with your use cases.  We can't justify massive rewrites and breaks in compatibility for the sake of usability improvements when we are able to achieve all of our needs with the current functionality.

If there is a rewrite project in the future, I definitely agree with you, and we'll take your feedback into account.  Until then, I need to ask that you either submit PRs to make things work under the constraints that we have today (backwards compatibility included), or shoehorn your application into our current limitations.

**Comment by StefansM** [comment]
That's perfect -- I wanted to check that I wouldn't be working at cross purposes to an existing initiative, and that PRs for such a structural change might actually be accepted. For now, I'm just going to be explicit in my recipes and keep the template weirdness to a minimum. I will add this to the "potential projects" stack.

**Comment by msarahan** [comment]
Thanks.  If it's OK with you, I'm going to leave this issue open, because it is definitely something that people need to know about, and something that needs to be resolved at some point.

**Comment by jakirkham** [comment]
What if we start requiring selectors to be of the form `# [...]` only? This is already pretty widespread (enforced in conda-forge) and improves readability in some code highlighting tools. That would probably solve the user problem. Though it would be a breaking change. Deprecating `[...]` would be a start.

**Comment by msarahan** [comment]
Yes, I am all for deprecating [...] if anyone wants to submit a PR for that.  Detecting it will be annoying.  Need to tweak a regex or make a new one.
