### ISSUE TITLE
Building fails with error about -headerpad 

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2811]
The recipe used to work fine, but recently I am seeing this error about -headerpad on OSX with xcode 6.4 (travis):

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/travis/miniconda/conda-bld/halotools_1523467567598/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/site-packages/halotools/mock_observables/pair_counters/marked_cpairs/marked_npairs_3d_engine.cpython-35m-darwin.so (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```

Here is a sketch of the recipe:

https://github.com/bccp/conda-channel-bccp/blob/master/recipe-templates/halotools/meta.yaml
https://github.com/bccp/conda-channel-bccp/blob/master/recipe-templates/halotools/build.sh

halotools is a python package with some C++ and C extensions.

**Comment by mingwandroid** [comment]
I do not understand why you have filed this bug.

The error tells you more or less exactly what to do here, simply you need to add `-headerpad_max_install_names` to your `LDFLAGS` (though since ld is driven via a compiler, you need to add `-Wl,-headerpad_max_install_names`).

Also, you should use our compilers on macOS then all this stuff gets taken care of for you.

**Comment by rainwoodman** [comment]
I thought the compiling toolchain have already added these flags to LDFLAGS.

**Comment by rainwoodman** [comment]
Yes. I will. I switched back to native from the toolchain around Nov 20th 2017.  But I don't recall the reason. If anything is broken I'll re-post.
