### ISSUE TITLE
Feature Request: add option to make recipe compatible with conda-forge

### ISSUE THREAD

**Issue by rutgerhofste** [conda/conda-build#2813]
### Actual Behavior

the output of `conda skeleton` is a meta.yaml file that is not accepted "as is" by [conda forge](https://github.com/conda-forge/staged-recipes). I don't fully understand why the recipe created by `conda skeleton` is not accepted but it is not the best user experience. 

### Expected Behavior

The process of adding an existing pypi package to the conda ecossytem (default channel or conda-forge) should be as easy as possible. Ideally the user would just setup a service once that will automatically parse an update in the pypi package to conda and conda-forge. As a temporary solution it would be helpful to have a conda-forge flag that will make the meta.yaml output compatible with conda-forge. 

`conda-skeleton pypi <mypackage> --conda-forge-compatible`

### Steps to Reproduce

Just use conda skeleton and make a PR to conda forge with the output meta.yaml file

##### `Output of conda info`

```

```

**Comment by jakirkham** [comment]
Related to issue ( https://github.com/conda/conda-build/issues/1703 ).
