### ISSUE TITLE
$SP_DIR env variable doesn't seem to point to the correct Python version

### ISSUE THREAD

**Issue by moorepants** [conda/conda-build#2870]
### Actual Behavior

I used `$SP_DIR` in a conda recipe for a Python 3.6 package noarch and it points to the Python 2.7 site-packages. See:

https://github.com/conda-forge/skijumpdesign-feedstock/pull/6#issuecomment-386649293

```
mv: cannot move `/home/conda/feedstock_root/build_artifacts/skijumpdesign_1525450019672/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/static' to `/home/conda/feedstock_root/build_artifacts/skijumpdesign_1525450019672/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages/': No such file or directory
```

Build: https://circleci.com/gh/conda-forge/skijumpdesign-feedstock/7?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Recipe PR:

https://github.com/conda-forge/skijumpdesign-feedstock/pull/6

### Expected Behavior

`$SP_DIR` should expand to the correct python version's site-packages directory.

### Steps to Reproduce

Expand `$SP_DIR` in a recipe on conda forge.

##### `Output of conda info`

See the build info on CircleCI.
```

```

**Comment by msarahan** [comment]
Conda-build is doing what it's told, actually: https://github.com/conda-forge/skijumpdesign-feedstock/blob/master/.ci_support/linux_.yaml

the re-rendering looks wrong, though.  Only linux?

This python constraint is very wrong:

```
requirements:
  build:
    - python >=3.5
```

it is much better to do this instead, and not apply constraints to python in your dependencies:

```
build:
  skip: True  # [py<35]
```

Leaving this issue open, because I'm concerned about the absence of other platforms.

**Comment by moorepants** [comment]
Thanks for the help. I tried your suggestion but the conda forge linter gives:

"noarch packages can't have selectors. If the selectors are necessary, please remove noarch: python"

Note that this is noarch, that's why only circleci should be running.

**Comment by CJ-Wright** [comment]
@msarahan the python constraint method is what we currently have in the docs: https://conda-forge.org/docs/meta.html#building-noarch-packages. Should we change it?

@moorepants does the software have an internal version constraint (eg it uses python 3 only features)?

**Comment by jakirkham** [comment]
Having it in `build` and `run` works. This is in `build` only, which does not work.

cc @jjhelmus
