### ISSUE TITLE
Query: pre-link/unlink, post-link scripts in a split recipe

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2872]
Is it possible to have a split recipe with a pre-link/unlink script restricted to only certain output(s)?

**Comment by mingwandroid** [comment]
Yes it is possible. https://github.com/conda/conda-build/blob/cf65f0132732afbd44509745ca052b1c85ef97ac/conda_build/build.py#L137-L138

**Comment by msarahan** [comment]
I don't think that code has seen much use.  If you do end up trying it, please consider also adding info about it to the docs, assuming it works.
