### ISSUE TITLE
How to change entry point shebang?

### ISSUE THREAD

**Issue by j3mdamas** [conda/conda-build#2873]
Hi,

I've tried researching the most so I wouldn't have to bother with what I think it's a simple question
Is this the full documentation on how to setup entry points on `meta.yaml`: https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#python-entry-points?
I can't seem to find any documentation on how to change the shebang of the entry points. In particular, I'd like to change from `python` to `ipython`.
I found lots of issues opened on the shebang though, but mainly people seemed to be hacking it (like overriding the `conda-build/post.py`) rather than using the `meta.yaml`. Is that the way to do it?

Thank you,
João

**Comment by j3mdamas** [comment]
Any feedback here?

**Comment by msarahan** [comment]
I'm afraid I haven't run into that use case.  I'd be happy to support it if
you feel like hacking in a PR.  I think you could probably do something
like overloading the existing list of entry points (strings) with a list of
dicts, like

entry_points:
  - name: bsdiff4
    function: bsdiff4.cli:main_bsdiff4
    interpreter: ipython

We've done this kind of thing in a few places, and checking for
hasattr(list_item, 'keys') works pretty well.

To be perfectly clear, I have too much on my plate right now to implement
this.  If you want this feature and you're willing to work on it, I'll
accept it.
