### ISSUE TITLE
Notes on pyldd

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2879]
pyldd is @mingwandroid's addition that helps us figure out when linking to system packages has happened, or when linking in general just isn't quite right.  These are my notes until I can put them in the docs somewhere.

* detection of a library by pyldd requires its presence in the **run** dependencies
* ``ERROR (mkl,lib/libmkl_ao_worker.so): runpaths ['$ORIGIN/'] found in /opt/conda/conda-bld/intel_repacks_1525992052733/_h_env_/lib/libmkl_ao_worker.so`` means that the lib entry (``libmkl_ao_worker.so`` here) uses RUNPATH, when we want it to use RPATH instead.  We should be able to remove/replace RUNPATH with RPATH, but I'm not sure exactly how.

**Comment by mingwandroid** [comment]
And just when we're starting to use it I feel it's pretty important to replace it with something better, still, the code that calls pyldd should be able to remain the same!

https://github.com/ContinuumIO/anaconda/issues/1430

**Comment by msarahan** [comment]
That issue is private, but it need not be.  Here are its contents:

Source code: lief-project/LIEF
Documentation: lief.quarkslab.com/doc/index.html
License: lief-project/LIEF:LICENSE@master (apache 2)

Provided it does everything that pyldd.py does (I suspect this is the case) we should replace my pyldd.py code with it.

It can do a lot more than pyldd.py can, in order of importance to Anaconda Distribution:

1. It supports PECOFF files (Windows .exes and .dlls).
2. It can list exported and imported symbols (at least for .elf files). We could track these, either listing each one explicitly in the info/ dir and/or via a hash in info/index.json.
3. It has a C API should we need to use it.
4. It is actively maintained (though one person does the bulk of the work).

**Comment by mingwandroid** [comment]
From @stuartarchibald

hmmm, perhaps the warning messages ought to add a thing to say "you should put X into req/host?", else it kinda implies ramming it into req/run would be the solution

Can you work out if a run_exports exists and tweak the error message based on that ?

I think if that were possible it'd be really good, because it tells the user where to shove things to fix the issue, opposed to describing the meta issue and leaving it to the user to work out (which probably requires the user to know a bunch about how the internals work). Whilst it is unlikely to work 100% of the time as there's going to be weird cases, it ought to solve basic things like I've done today (zlib linked but not found in req/run, solution, as zlib has run_exports? is put it in host)

**Comment by msarahan** [comment]
From @mingwandroid 

Projects carry prebaked libtool scripts most of the time, and those libtools have a missing feature / bug where -Wl,--as-needed is not sorted to the front of the command line (this matters because it applies only to libraries seen after it). TBH libtool doesn't really know anything about -Wl,--as-needed AFAIR.

Anyway, that's fixed with our libtool, but to make sure that projects update their libtool you need to run either libtoolize -c -f (add libtool build dep) (before configure) or failing that autoreconf -vfi (add automake, autoconf, gettext (sometimes), libtool build deps)

In the example I ran into now (fontconfig) libxzma was being dragged in due to libxml2 declaring a dependency on it in its .la file, so pyldd detected that there was a missing needed DSO from the reqs, but adding this to fontconfig would have been the less good fix clearly.

If you run into a missing DSO check to see where the --as-needed flag appears relative to the -lfoo flags in the libtool-driven link line and if it's after then you can be pretty sure you need to update libtool instead of adding an un-needed requirement.

**Comment by msarahan** [comment]
Example PR of libtool reconf:

https://github.com/AnacondaRecipes/fontconfig-feedstock/commit/6167e27cce56490662f7910e766c82f8501b31a0#diff-44a73bcc045c193c3bd45da87994b03bR5
