### ISSUE TITLE
when building the r DECIPHER package, I get an error that it cannot install IRanges

### ISSUE THREAD

**Issue by cramjaco** [conda/conda-build#2884]
### Actual Behavior

I'm trying to build the r package DECIPHER for conda. I'm working a clean linux64 xubuntu system, with `andacondas` and `conda-build` installed, and `gfortran` installed with `sudo apt-get install gfortran`. I've also added the `bioconda` library with `conda config --add channels bioconda`.
I have a directory called r-decipher, in which I have the attached `meta.yaml`, `build.sh` and `build.bat` files.

[r-decipher.zip](https://github.com/conda/conda-build/files/2007104/r-decipher.zip)

I try to build with
`conda build r-decipher 1>out.r-decipher.build.txt 2>err.r-decipher.build.txt`

This returns the following

[out.r-decipher.build.txt](https://github.com/conda/conda-build/files/2007150/out.r-decipher.build.txt)
[err.r-decipher.build.txt](https://github.com/conda/conda-build/files/2007151/err.r-decipher.build.txt)

In general, the compilation fails with the error message "Error: package or namespace load failed for ‘IRanges’:" as shown in the attached err.r-decipher.build.txt file.

I have no trouble installing IRanges with conda install bioconductor-iranges, but even after doing that, I still get the same error message.

### Expected Behavior

conda should build `r-deciphe`r, which I could then install as the r package DECIPHER
I'll add that I have successfully managed to build a few other r-packages without these problems.

### Steps to Reproduce

download and extract the attached zip file to a directory called `r-decipher`
from the directory one above `r-decipher`

`sudo apt-get install gfortran`
`conda config --add channels bioconda`
`conda build r-decipher 1>out.r-decipher.build.txt 2>err.r-decipher.build.txt`

##### `Output of conda info`

```
     active environment : None
       user config file : /home/ohnoplus/.condarc
 populated config files : /home/ohnoplus/.condarc
          conda version : 4.5.0
    conda-build version : 3.8.0
         python version : 3.6.3.final.0
       base environment : /home/ohnoplus/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/ohnoplus/anaconda3/pkgs
                          /home/ohnoplus/.conda/pkgs
       envs directories : /home/ohnoplus/anaconda3/envs
                          /home/ohnoplus/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.3 Linux/4.13.0-36-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by cramjaco** [comment]
Short update -- I also tried adding the channel "r" and then repeating the process with `conda config --add channels r`. In this case, I get the same behavior.

**Comment by msarahan** [comment]
Sorry, I think you need an R expert (ask bioconda).  It looks like maybe our r-base expects something different from bioconda?  I don't think you have problems at the conda-build level.  I think they are at the R level.
