### ISSUE TITLE
PEP 566 compliance in conda-build

### ISSUE THREAD

**Issue by brainwane** [conda/conda-build#2897]
### Actual Behavior

I ran `conda skeleton` on https://pypi.org/project/econ-ark/0.8.0.dev2/ .

While running `conda-build` I got this warning:

`[redacted]/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'`

Per PEP 566 and https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi , https://github.com/brainwane/HARK/blob/71a2bbc95f01535041301489feccca7a871450d2/setup.py#L72 includes `long_description_content_type`.

### Expected Behavior

`conda-build` should accept the `long_description_content_type` in a `setup.py` file without complaint.

### Steps to Reproduce

Follow https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html but for the `econ-ark` PyPI package, i.e.,

> conda skeleton pypi econ-ark
> cd econ-ark/
> wget https://conda.io/docs/_downloads/build1.sh
> wget https://conda.io/docs/_downloads/bld.bat
> cd ..
> conda-build econ-ark

##### `Output of conda info`

```
     active environment : None
       user config file : /home/sumanah/.condarc
 populated config files : /home/sumanah/.condarc
          conda version : 4.5.3
    conda-build version : 3.10.3
         python version : 2.7.14.final.0
       base environment : /home/sumanah/Documents/opentechstrategies/HARK/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/sumanah/Documents/opentechstrategies/HARK/anaconda2/pkgs
                          /home/sumanah/.conda/pkgs
       envs directories : /home/sumanah/Documents/opentechstrategies/HARK/anaconda2/envs
                          /home/sumanah/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.3 requests/2.18.4 CPython/2.7.14 Linux/4.9.0-6-amd64 debian/9 glibc/2.24
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

```

**Comment by msarahan** [comment]
Thanks for pointing this out.  We'll try to address it soon.

**Comment by msarahan** [comment]
I took a look this morning.  It looks to me like that error message is coming from distutils, not from conda-build.  At best, I could swallow such warnings.

What would be your recommended way to address this?  Do you know if distutils itself actually respects this PEP?  If so, when did it start doing so?

**Comment by brainwane** [comment]
Hi @msarahan! *wave* Nice to get to "see" you again. :)

`distutils` here is being provided -- as I see via `conda info` -- by `python version : 2.7.14.final.0` as provided by Anaconda. [Python 2.7.14 came out on 2017-09-16](https://www.python.org/dev/peps/pep-0373/), before [PEP 566 was accepted on February 23, 2018](https://mail.python.org/mm3/archives/list/distutils-sig@python.org/message/GHJENPDX5G3FVFUKU2YTKXXAWDKALAIW/). I have not yet checked whether [Python 2.7.15, released 1 May 2018](https://mail.python.org/pipermail/python-list/2018-May/732755.html), respects PEP 566. Let me check.

**Comment by msarahan** [comment]
I tried with 2.7.15 and 3.6.5, neither seemed to show any difference here. =(

**Comment by brainwane** [comment]
@msarahan I'm sorry for sending you on a wild goose chase here. [Here's the open bug against `distutils`](https://bugs.python.org/issue33388). Closing this issue since it's upstream. Thanks for looking at it.

**Comment by brainwane** [comment]
> What would be your recommended way to address this?

@ncoghlan [wrote](https://bugs.python.org/msg316907):

> If these warnings are being emitted when using plain distutils, that's OK, since it genuinely doesn't support them (and folks should be using setuptools instead).

> Longer term, we want to get setuptools to the point of being independent of the standard library's copy of distutils: https://github.com/pypa/packaging-problems/issues/127

I think "switching from depending on `distutils` to `setuptools`" is a separate technical discussion to have, far beyond the scope I originally meant to bring up here, so please feel free to rename/reopen/move/link to/etc. this as you see fit, @msarahan!

**Comment by msarahan** [comment]
great.  If anyone else notices this warning and complains, I'll advise them to switch to setuptools.  Also good for me to see that @ncoghlan explicitly recommends setuptools over distutils.  I've seen some people who don't know which one to use, and that's helpful to point to.  Thanks!

**Comment by ncoghlan** [comment]
@msarahan https://packaging.python.org/guides/tool-recommendations/#packaging-tool-recommendations is a better reference for the `setuptools` recommendation (footnote 5 gives the rationale for the recommendation)
