### ISSUE TITLE
testing is somehow losing subdir info

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2899]
The new split numpy is having issues on win-32, but only sometimes.  It builds everything for win-32 fine, but when it goes to test, it appears to lose its mind and mixes win-32 with win-64 somehow.

**Comment by nehaljwani** [comment]
I had a similar issue with llvmlite when I was using the matrix file to build for both 32 and 64 bit. Eventually I ended up using CONDA_SUBDIR
