### ISSUE TITLE
Environment Variables related to compiler while packaging

### ISSUE THREAD

**Issue by Fk-Nikhil** [conda/conda-build#2903]
### Actual Behavior

Hi, 
       I need gfortran compiler to build the package[Openfst]. There is already a conda package but wanted to build with custom configuration. The makefile has  environment variables, ex: [$CC, $CC_FLAGS etc]. On giving the gfortran compiler as a dependency. 

When conda installs the gfortran, (using conda install ) it usually exports the environment variables related to the compiler. But mentioning the compiler as a dependency, environment variables are not getting set.  

I manually activated the build environment that is created when we run the conda-build command. I don't see these variables set.  

Am I missing out any during the build?  Please help, Thanks in advance. 

### Expected Behavior
Compiler-related environment variables have to be set in the build environment. 

### Steps to Reproduce
Link to recipe : https://drive.google.com/open?id=1Q2O-UoDlozBPJvHe3P2WgaaKOCHZxM_M

command issued: conda-build package 

##### `Output of conda info`

```
active environment : None
       user config file : /home/vagrant/.condarc
 populated config files : /home/vagrant/.condarc
          conda version : 4.5.2
    conda-build version : 3.10.2
         python version : 3.6.5.final.0
       base environment : /home/vagrant/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/vagrant/anaconda3/pkgs
                          /home/vagrant/.conda/pkgs
       envs directories : /home/vagrant/anaconda3/envs
                          /home/vagrant/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.5 Linux/3.13.0-139-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by mingwandroid** [comment]
Please share your recipe somewhere else and as text only, e.g. in a GitHub gist.

**Comment by manishbansal-fk** [comment]
Please find Github gist [link](https://gist.github.com/manishbansal-fk/0871211f0dd0f1d18721c6f1aa2df449)

**Comment by mingwandroid** [comment]
You shouldn't use `conda-forge`'s toolchain at the same time as our compilers. Also you should use the new conda-build 3 features.

```
requirements:
  build:
    - {{ compiler('cxx') }}
    - automake
```

**Comment by Fk-Nikhil** [comment]
Hi, 
I have used the changes mentioned above. Still, it's failing. The reason here I can find is the issue with the  CFLAGS, CXXFLAGS, LDFLAGS. These are set to different values when the build environment is activated. 

'''
LDFLAGS='-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath,/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib'

CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -m64'

CPP='/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_build_env/bin/x86_64-conda_cos6-linux-gnu-cpp'

CPPFLAGS='-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include'

'''

because of these flags, gcc is breaking. 

''' 
configure:3364: gcc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -m64 -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath,/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L/home/vagrant/anaconda3/conda-bld/openfst_1527060642116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib conftest.c  >&5
gcc: error: unrecognized command line option '-fstack-protector-strong'
gcc: error: unrecognized command line option '-fno-plt'

'''

**Comment by mingwandroid** [comment]
You are not using our compilers here. Pass --host=${HOST} to configure.

**Comment by Fk-Nikhil** [comment]
Hi, 

I have tried your approach. But still, it fails.

**Comment by Fk-Nikhil** [comment]
Hi, 


I have changed the build file also, 

```
 ./configure --host=${HOST}  --enable-shared --enable-far --enable-ngram-fsts
``` 
Still i can see the same values for environment variables 

```
LD='/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_build_env/bin/x86_64-conda_cos6-linux-gnu-ld'
LDFLAGS='-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-rpath,/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib'

CC='gcc'
CCDEPMODE=''
CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -m64'
CPP='/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_build_env/bin/x86_64-conda_cos6-linux-gnu-cpp'
CPPFLAGS='-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include'
CXX='g++'
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS='-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/vagrant/anaconda3/conda-bld/openfst_1527167356355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -DBOOST_MATH_DISABLE_FLOAT128 -m64'


```

Please Help, Thanks in Advance.

**Comment by mingwandroid** [comment]
Please update the gist with the latest version of the files you are working from.

**Comment by manishbansal-fk** [comment]
Updated gist 
https://gist.github.com/manishbansal-fk/0871211f0dd0f1d18721c6f1aa2df449

Please check.

**Comment by mingwandroid** [comment]
Sorry you have not updated to my advice, specifically https://github.com/conda/conda-build/issues/2903#issuecomment-391063202

I cannot help you if you do not at least try to help yourself.

**Comment by Fk-Nikhil** [comment]
@mingwandroid Really sorry. 

We have updated out meta.yaml. Now the build throws an error at make. 
gist link: https://gist.github.com/manishbansal-fk/0871211f0dd0f1d18721c6f1aa2df449
```
libtool: link: /home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -fdebug-prefix-map=/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/work=/usr/local/src/conda/openfst-1.6.1 -fdebug-prefix-map=/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl=/usr/local/src/conda-prefix -std=c++11 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-rpath -Wl,/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -o .libs/farequal farequal.o  -L/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib ./.libs/libfstfarscript.so ../../script/.libs/libfstscript.so ../../lib/.libs/libfst.so -lm -ldl -Wl,-rpath -Wl,/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_build_env/lib
/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libfstfar.so.7, needed by ./.libs/libfstfarscript.so, not found (try using -rpath or -rpath-link)
./.libs/libfstfarscript.so: undefined reference to `fst::IsSTList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./.libs/libfstfarscript.so: undefined reference to `fst::IsSTTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[4]: *** [farcreate] Error 1
make[4]: *** Waiting for unfinished jobs....
/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libfstfar.so.7, needed by ./.libs/libfstfarscript.so, not found (try using -rpath or -rpath-link)
./.libs/libfstfarscript.so: undefined reference to `fst::IsSTList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./.libs/libfstfarscript.so: undefined reference to `fst::IsSTTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
/home/vagrant/anaconda3/conda-bld/openfst_1527245725299/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../make[4]: *** [farcompilestrings] Error 1
../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libfstfar.so.7, needed by ./.libs/libfstfarscript.so, not found (try using -rpath or -rpath-link)
./.libs/libfstfarscript.so: undefined reference to `fst::IsSTList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./.libs/libfstfarscript.so: undefined reference to `fst::IsSTTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[4]: *** [farextract] Error 1
```
Once again, sincere apologies from our side.

**Comment by mingwandroid** [comment]
This is a bug in your software.  Our compilers LDFLAGS are not being used.
