### ISSUE TITLE
Add testpypi as repo for conda-skeleton

### ISSUE THREAD

**Issue by prisae** [conda/conda-build#2906]
### Feature request

It would be great to have the option to use `testpypi` in addition to 'cpan', 'cran', 'luarocks', 'pypi', 'rpm' when using `conda-skeleton`. This way one could test packages first on testpypi and see if building a conda package from it works before submitting a package actually to PyPi. 

##### `Output of conda info`
```
~/> conda skeleton testpypi empymod
usage: conda-skeleton [-h] {cpan,cran,luarocks,pypi,rpm} ...
conda-skeleton: error: argument repo: invalid choice: 'testpypi' (choose from 'cpan', 'cran', 'luarocks', 'pypi', 'rpm')
```

**Comment by prisae** [comment]
Great, `conda skeleton pypi --pypi-url https://test.pypi.io/pypi/` did the trick. Thanks for your answer and sorry for missing it in the docs.

**Comment by msarahan** [comment]
no problem.  That's in the docs, and also in the -h output.  Good luck - pay careful attention to the URLs that get generated in the recipe for you.  The pypi-url argument doesn't see much use, and may have bugs.
