### ISSUE TITLE
Replace CONDA_BUILD_SYSROOT

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2916]
### Actual Behavior

When CMake exports targets, if the target used a OSX framework, then the full path to the framework is hardcoded in `ProjectExports.cmake`. This is fine as long as we use the same CONDA_BUILD_SYSROOT throughout all projects. At conda-forge, we are using travis-ci and circle-ci both for osx and this becomes a problem.

### Expected Behavior

@mingwandroid, @msarahan, do you think it's a good idea to replace `CONDA_BUILD_SYSROOT` with the new value the same way as `PREFIX` is replaced?

**Comment by mingwandroid** [comment]
It would need to be replaced by a token that cmake knows about though and automatically performs substitution of I guess? Do you know of any way to do that?
