### ISSUE TITLE
load_file_regex() in jinja_context.py does not close the file

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#2917]
### Actual Behavior

ResourceWarning: File is not closed when using load_file_regex()

### Expected Behavior

Close the file when it is out of scope.
I opened PR#2915 but need to clear internal red-tape. The patch is trivial, so including here:
```
diff --git a/conda_build/jinja_context.py b/conda_build/jinja_context.py
index 1b45883a..e2125be0 100644
--- a/conda_build/jinja_context.py
+++ b/conda_build/jinja_context.py
@@ -184,7 +184,8 @@ def load_file_regex(config, load_file, regex_pattern, from_recipe_dir=False,
             raise RuntimeError(message)

     if os.path.isfile(load_file):
-        match = re.search(regex_pattern, open(load_file, 'r').read())
+        with open(load_file, 'r') as lfile:
+            match = re.search(regex_pattern, lfile.read())
     else:
         if not permit_undefined_jinja:
             raise TypeError('{} is not a file that can be read'.format(load_file))
```

### Steps to Reproduce

Use load_file_regex() in a jinja template

##### `Output of conda info`

```

```

**Comment by tomashek** [comment]
The PR was against master branch, this patch was against 3.10.4

**Comment by msarahan** [comment]
Should I wait to merge your PR until "red tape" is resolved?  This change
looks fine to me.
