### ISSUE TITLE
Path to test env is wrong on windows

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2918]
### Actual Behavior

In our Windows CI we test a lot of packages like this: `conda build recipe --croot $(Join-Path (pwd) builds) -t`. (powershell). In our run_test.bat is something like `%LIBRARY_PREFIX%\bin\test.exe`.

This worked great - until including 3.10.3. Unfortunately it broke with 3.10.4. The reason is `%LIBRARY_PREFIX%`:

- <= 3.10.3: `C:\ci\builds\tespkg_1527193120180\_test_env\Library\bin\Test.exe`
- \> 3.10.3: `C:\ci\builds\testpkg_1527193464534\_h_env\Library\bin\Test.exe`

So test_env changed to _h_env, which does not exist...

### Expected Behavior

LIBRARY_PREFIX should again point to the proper directory. `_h_env` doesn't even exist in my case.

### Steps to Reproduce

Build a pkg with the aforementioned command on windows.

**Comment by gabm** [comment]
@msarahan our meta.yaml does not use the build_variants feature yet...

**Comment by msarahan** [comment]
Fixed in 3.10.5.  Please update and try again.

**Comment by gabm** [comment]
@msarahan thanks for your very fast answer! I really appreciate that.. Unfortunately it doesn't change with 3.10.5... Its still pointing to the _h_env :cry:

**Comment by msarahan** [comment]
Can you please post a simple test case here, and I'll add a regression test?

**Comment by jakirkham** [comment]
Would add that all the other `LIBRARY_*` variables (e.g. `LIBRARY_BIN`) have this same problem as well. If it helps at all, ran into this issue in PR ( https://github.com/conda-forge/flann-feedstock/pull/17 ) to the `flann` feedstock recently. Switching to `PREFIX` was an effective workaround to the issue.

cc @dougalsutherland
