### ISSUE TITLE
Requiring compiler's in the test phase

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2922]
Trying to figure out the right way to include compilers in the test phase. Tried to do this in PR ( https://github.com/conda-forge/glew-feedstock/pull/5 ), but it doesn't appear to be working. Suggestions welcome.

**Comment by jakirkham** [comment]
Think we've got these working, but would be nice if someone could confirm that our usage is correct in that PR.

**Comment by msarahan** [comment]
Looks fine to me.  Nothing magic - just say you need a C compiler.

**Comment by jakirkham** [comment]
Thanks Mike :)
