### ISSUE TITLE
[conda-build 3] %LIBRARY_PREFIX% pointing to `host` instead of `test` env at test time.

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda-build#2924]
It seems that with conda-build 3, the `%LIBRARY_PREFIX%` environment variable still points to the `host` environment instead of the `test` environment at test time, which prevents testing for presence of files as part of the tests for recipes.

This came up as I was looking at updating a bunch of similar recipes to conda-build 3:

https://github.com/conda-forge/conda-forge/xtl-feedstock#35
https://github.com/conda-forge/conda-forge/xsimd-feedstock#15
https://github.com/conda-forge/conda-forge/xtensor-feedstock#75
https://github.com/conda-forge/conda-forge/xtensor-blas-feedstock#15

**Comment by isuruf** [comment]
I think this is a duplicate of https://github.com/conda/conda-build/issues/2918

**Comment by SylvainCorlay** [comment]
Thanks. Missed it!
