### ISSUE TITLE
host dependencies are not found (conda-build=3.10.5) (osx/linux)

### ISSUE THREAD

**Issue by looooo** [conda/conda-build#2930]
although these dependencies are found in the cmake step, they are not found by the linker. Again this was working previously with the old conda-forge toolchain.

the corresponding build:
linux: https://circleci.com/gh/conda-forge/staged-recipes/27522?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
osx: https://travis-ci.org/conda-forge/staged-recipes/builds/384676776?utm_source=github_status&utm_medium=notification

This came up after changing some dependencies from build to host. So maybe this is a bug with the newly added host-section...

**Comment by msarahan** [comment]
CMake is obnoxious and does not respect sysroots correctly.  See libnetcdf for an example of how we work around this: https://github.com/AnacondaRecipes/libnetcdf-feedstock/blob/master/recipe/build.sh#L5

We have tried to help Kitware fix this, but they haven't had much interest.
* https://gitlab.kitware.com/cmake/cmake/issues/17473
* https://gitlab.kitware.com/cmake/cmake/issues/17483

**Comment by jakirkham** [comment]
Maybe worth pinging those issues and/or sharing more details about our specific use case. Kitware also builds some `conda` packages. Though I don't know what overlap there is between CMake devs and people building `conda` packages there.
