### ISSUE TITLE
win: failed linking without error

### ISSUE THREAD

**Issue by looooo** [conda/conda-build#2942]
I am trying to fix a previously working build which now fails to due a linking problem (after update to conda-build3) The setup for the linking can be found here:

https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Path/libarea/CMakeLists.txt#L102L124

I wonder if conda-build does any additional steps to link to the vcruntime, ucrtd...
The linking problem can be found here:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.24930#L1950

**Comment by msarahan** [comment]
No, conda-build is not doing anything so involved.  You may need to remove -GL and perhaps -ltcg from your CC/CXX/LDFLAGS.  When we need to do this, we'll most often just unset them at the top of bld.bat.  They sometimes cause problems, but provide enough of a speed improvement that they are a sane default.  See https://github.com/AnacondaRecipes/aggregate/blob/master/vs2015/activate.bat#L41

**Comment by looooo** [comment]
thanks. this works!
for anybody who encounter the same problem:
using this st the top of the bld.bat worked for me:
```
set "CFLAGS= "
set "CXXFLAGS= "
set "LDFLAGS_SHARED= ucrt.lib"
```
