### ISSUE TITLE
INCLUDE and LIB are not set in win output scripts

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2944]
These get set automatically by conda-build to include LIBRARY_INC and LIBRARY_LIB, respectively.  However, that appears to only be true for bld.bat, not any output scripts.  Compilation of things in output scripts is likely to fail as a result.

**Comment by mingwandroid** [comment]
I have a PR mostly test to emit all env vars to all the scripts. May be worth building on that one?

**Comment by msarahan** [comment]
Probably.  This was just a crappy special case.  It was handled in the build part of windows.py, when it should have been in the part where it writes the activate content.
