### ISSUE TITLE
fail to install scripts (commands) with conda build, installing them with pip is fine

### ISSUE THREAD

**Issue by marscher** [conda/conda-build#296]
Its a setuptools based project. 

conda-build displays a warning for every script about a hardcoded path. 

This seems to be regression, as it worked before (I guess its related to setuptools upgrade from 7.0 to 11.x)

The recipe in question can be found here: 
https://github.com/marscher/omnia-conda-recipes/tree/master/pyemma

**Comment by marscher** [comment]
....
Installing mm_cluster script to /home/marscher/anaconda/envs/_build/bin
....
Detected hard-coded path in text file bin/mm_cluster
....
    + mm_cluster
    Traceback (most recent call last):
      File "/home/marscher/anaconda/envs/_test/bin/mm_cluster", line 4, in <module>
        __import__('pkg_resources').run_script('pyEMMA==1.0', 'mm_cluster')
      File "/home/marscher/anaconda/envs/_test/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 696, in run_script
      File "/home/marscher/anaconda/envs/_test/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 1606, in run_script
    pkg_resources.ResolutionError: No script named 'mm_cluster'

**Comment by marscher** [comment]
only the wrapper scripts are installed in bin/, but the source is actually missing. I've tried to add preserver_eggdir = true to meta.yml, but it does not fix the issue.

**Comment by asmeurer** [comment]
I recommend adding the setuptools entry points to the meta.yaml so that conda will create its own entry points.

**Comment by marscher** [comment]
Thanks for the recommendation. So is the 'scripts' directive of 
setuptools actually unsupported?

**Comment by asmeurer** [comment]
It should work. Your package will have to runtime depends on setuptools, though, which is unnecessary.

**Comment by marscher** [comment]
I'am already depending on setuptools during runtime, but it does not
work. Only the stub loaders are created but the actual scripts are not
copied by conda-build.

**Comment by Jorge-C** [comment]
Just wanted to comment that I was having [issues](https://github.com/biocore/qiime/issues/1759) getting scripts to work in conda packages, and enabling
```
build:
  preserve_egg_dir: True
```
and adding `setuptools` as a runtime dependency seems to have worked.

**Comment by marscher** [comment]
this is exactly what I've done. Preserving the egg-dir and runtime depending on setuptools
