### ISSUE TITLE
Compile Rust extension

### ISSUE THREAD

**Issue by milesgranger** [conda/conda-build#2966]
Good day!

I'm looking to add a conda package which uses a Rust extension for a Python package. Currently it's on [PyPI as wheels](https://pypi.org/project/gap-stat/1.5.0a2/#files), but yes, would like to have it available via Anaconda but this is giving me some trouble.

 I _think_ I've found enough info to know there is no rust compiler (specifically [Cargo](https://github.com/rust-lang/cargo)) available to use in the `conda-build` workflow. At least without writing scripts to install it for each platform (if I understood that part correctly)

I'm pretty green in the conda-build arena, but would be willing to help out in this regard if it's possible to add Cargo as a compiler. Or am I proceeding down the wrong path, and just better to leave it on PyPI?

Thanks! :+1:

**Comment by msarahan** [comment]
You're definitely on the right path.  Several of us are interested in Rust, but we haven't had the time to make it a properly-supported tool yet.  It looks like rust has been packaged over at conda-forge: https://github.com/conda-forge/staged-recipes/pull/3254

Here's a recipe that uses that package: https://github.com/conda-forge/staged-recipes/pull/5789/files

You can use additional channels, like conda-forge, by using the -c argument to conda-build, or by adding channels in condarc.  Do be careful, though - packages on conda-forge are not currently binary compatible with defaults, and mixing packages from the two doesn't always work.

If you have ideas for how conda-build can make it easier to use rust, we'd like to discuss them with you.

**Comment by milesgranger** [comment]
Great, thank you so much for the information and links; I'll keep chipping away at it and get back with any ideas on improving conda-build with rust I find along the way.

**Comment by milesgranger** [comment]
Checking back in...

The link you suggested was very informative, however my project requires the nightly channel of Rust, and this package linked to here is 1.26 stable. This in itself _seems_ problematic. If I understand correctly, I will need to maintain a separate packaging of the rust compiler I need in conda to support this project, whilst using only wheels, I can download the required version of Rust and compile the wheels on a per-commit basis via CI tools.

Regardless, I _really_ want it on Anaconda as well. So, the next best thing I see is: [using wheel files with conda](https://conda.io/docs/user-guide/tasks/build-packages/wheel-files.html)

Until there exists (or perhaps I'm unaware of another solution) a way to use a rust compiler and switch versions/channels on-demand in the conda build process/meta.yaml... It appears to be more trouble than it's worth, when the previous solution of using wheels, albeit frowned upon, can save hours of trouble. 

The only idea for a solution which I had along the way, was if you think it's possible to, instead of packaging Cargo, package [Rustup](https://rustup.rs/) and then in the `build` script specify which channel/version of rust to use for compiling? Then Rustup should be able to download the needed version/channel and happily go along. So only breaking changes in Rustup would require a new conda package, not every time a new Rust version is released.

**Comment by msarahan** [comment]
Sure, that's a decent way to do it.  We probably wouldn't do that on defaults because we need to build everything ourselves in order to make security guarantees to our customers, but it sounds like your solution would work for your use case.

**Comment by milesgranger** [comment]
Great, thank you again for the guidance!
