### ISSUE TITLE
Store build time information in the package info/recipe folder

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#2967]
### Actual Behavior

Conda build prints the build time. 

### Expected Behavior

Conda build should also write the build time to some file for later use.

xref: https://github.com/conda-forge/conda-smithy/issues/789#issuecomment-397342931

**Comment by msarahan** [comment]
I don't think this is the right place to put it.  It might give order-of-magnitude estimates, but it's not really going to be meaningful across many machines.

You can pass this argument to conda-build to have it save the time info to a json filename that you specify.

```
  --stats-file STATS_FILE
                        File path to save build statistics to. Stats are in
                        JSON format
```

**Comment by msarahan** [comment]
Going to go ahead and close this - if you wanted to discuss more, let me know.
