### ISSUE TITLE
glob TypeError in conda-build 3.10.9 in python2.7 env

### ISSUE THREAD

**Issue by joelvbernier** [conda/conda-build#2976]
conda-build fails with a TypeError in glob (unexpected kwarg 'recursive', which I think is only in python 3) for a python2.7 environment using conda-build=3.10.9.  Seems that conda-build=3.9.2 was the last working version.

Thanks!

```
     active environment : hexrd_0.5
    active env location : /home/beams/S1IDUSER/anaconda/envs/hexrd_0.5
            shell level : 1
       user config file : /home/beams/S1IDUSER/.condarc
 populated config files : /home/beams/S1IDUSER/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.9
         python version : 2.7.15.final.0
       base environment : /home/beams/S1IDUSER/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/joelvbernier/linux-64
                          https://conda.anaconda.org/joelvbernier/noarch
                          https://conda.anaconda.org/fable/linux-64
                          https://conda.anaconda.org/fable/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/beams/S1IDUSER/anaconda/pkgs
                          /home/beams/S1IDUSER/.conda/pkgs
       envs directories : /home/beams/S1IDUSER/anaconda/envs
                          /home/beams/S1IDUSER/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.13.0 CPython/2.7.15 Linux/3.10.0-862.el7.x86_64 rhel/7.5 glibc/2.17
                UID:GID : 2055:3113
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
This happened in https://github.com/conda/conda-build/pull/2937

That recursive keyword should not be there for glob2 globs.  We use glob2 to support recursive globs on python 2, and it doesn't support that keyword.

We'll fix it soon.  In the meantime, using Python 3 is a workaround, as is downgrading to 3.10.6.

CC @mbargull

**Comment by mbargull** [comment]
Ah, I looked at `glob2 0.6`'s source as a template to explicitly retain compatibility. But it turns out that parameter was not available in `glob2 <0.6`: https://github.com/miracle2k/python-glob2/blob/0.6/CHANGES#L2-L3

@joelvbernier, can you try to run `conda update glob2` or `conda install 'glob2>=0.6'` and see if the error persists?

@msarahan, would you want to restore `glob2 <0.6` compatibility or just add a `glob2 >=0.6` requirement (which could now also be `glob2 >=0.6  # [py27]` since it's not imported for Python 3 anymore)?

**Comment by msarahan** [comment]
Ah, good.  I'm more inclined to just add a version requirement for glob2 to conda-build.  Let's do that in the next release.

**Comment by isuruf** [comment]
It works with glob2. We did this in conda-forge a while back, but I forgot to check AnacondaRecipes.

https://github.com/conda-forge/conda-build-feedstock/pull/56/files

**Comment by shadowwalkersb** [comment]
> Let's do that in the next release.

Any timeline for the release that fixes this issue? Any workaround suggestions for the complaining users?
