### ISSUE TITLE
Building packages with llvm on OS X is impossible when using the anaconda compilers

### ISSUE THREAD

**Issue by abergeron** [conda/conda-build#2981]
### Actual Behavior

If I build a package with this specification:

```
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - llvmdev ==6.0.0
```

on a mac, the compiler line pulls in the llvm-4.0.1 pacakge which overrides almost all the files of llvmdev-6.0.0, so I can't use that version of llvm.  The problem is further compounded by the fact that the llvm-4.0.1 package appears to be incomplete because it leads to this error:

```
CMake Error at /Users/anakha/miniconda/conda-bld/tvm-libs_1529515465436/_build_env/lib/cmake/llvm/LLVMExports.cmake:1167 (message):
  The imported target "PollyISL" references the file

     "/Users/anakha/miniconda/conda-bld/tvm-libs_1529515465436/_build_env/lib/libPollyISL.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/Users/anakha/miniconda/conda-bld/tvm-libs_1529515465436/_build_env/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /Users/anakha/miniconda/conda-bld/tvm-libs_1529515465436/_build_env/lib/cmake/llvm/LLVMConfig.cmake:214 (include)
  cmake/util/FindLLVM.cmake:19 (find_package)
  cmake/modules/LLVM.cmake:5 (find_llvm)
  CMakeLists.txt:170 (include)


```

I can sucessfully build the package if I remove the compiler line, but then it uses the system compilers which I understand to be not desirable.

### Expected Behavior

I should be able to link with llvmdev-6.0.0 even though I'm using the ananconda-built clang.

### Steps to Reproduce

Try to build this package:

[tstpkg.tar.gz](https://github.com/conda/conda-build/files/2120450/tstpkg.tar.gz)

It doesn't actually build anything, but if that passes the "configure" phase then my problem is fixed.

##### `Output of conda info`
```
$ conda info

     active environment : None
       user config file : /Users/anakha/.condarc
 populated config files : /Users/anakha/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.9
         python version : 3.6.5.final.0
       base environment : /Users/anakha/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/anakha/miniconda/pkgs
                          /Users/anakha/.conda/pkgs
       envs directories : /Users/anakha/miniconda/envs
                          /Users/anakha/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.19.1 CPython/3.6.5 Darwin/17.6.0 OSX/10.13.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
This is not something we're going to officially support in the way that you're trying to do it.  If you want to swap in your own llvmdev, you need to create your own custom compiler packages.  See https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#customizing-the-compilers for more info.

**Comment by abergeron** [comment]
It's not my own llvmdev, it's the package from the defaults channel.  And I don't want a custom compiler, just to link with installed libraries.

This works on other platforms, it only fails on OS X because the compiler installs a broken llvm on top of the package.

**Comment by msarahan** [comment]
It fails on OSX because I don't think you understand what you're trying to do.  You are currently specifying that two llvm implementations should be installed in the same place.  Yes, that's broken.  It should not be a surprise.  It is not a bug.

When you list {{ compiler('cxx') }}, you get clang on mac, which is backed by our llvm package (not llvmdev).  There is no override for that clang package.  If you want a different llvm package, you need to create your own compiler package, as described in the link I sent you.  That package need not be a whole compiler, it's more the wrapper that sets flags and says which llvm you want to depend on.  See https://github.com/AnacondaRecipes/aggregate/tree/master/clang for how our clang package works.
