### ISSUE TITLE
Python matrix being added for build-only required Python

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2989]
### Actual Behavior

Seems that if a recipe has `build` and `host`, but no `run` in the `requirements` section. Things in `build` affect the rendering of the recipe as if they were in `host`. In particular, if `python` were in `build`, it is treated as though it was in `host`. This results in construction of a matrix of `python` versions to build against. For whatever reason, adding an empty, explicit `run` section avoids this issue. Not sure if there is more going on in this problem that I'm missing or if there is a bug.

ref: https://github.com/conda-forge/jsoncpp-feedstock/pull/9/commits/8d0295b29b28d5e39fadcd9881e74059683c0352
ref: https://github.com/conda-forge/jsoncpp-feedstock/pull/9/commits/96b31a746476c34386f755618330ee3b8a6f480b
ref: https://github.com/conda-forge/jsoncpp-feedstock/pull/9#issuecomment-401057514

### Expected Behavior

The `python` matrix in this scenario should not have existed.

### Steps to Reproduce

This [recipe]( https://github.com/conda-forge/jsoncpp-feedstock/blob/5a1b67f3c02cc7272c3b9ccc7e816a9f1668f118/recipe/meta.yaml ) will reproduce the issue. Adding an empty `requirements/run` section resolves it.

##### `Output of conda info`

Using `conda-build` 3.10.9 and `conda` 4.5.4. Can extract other info from the logs should it be needed, but unfortunately we did not run this exact command.

**Comment by jakirkham** [comment]
This also cropped up in `fftw`. ( https://github.com/conda-forge/fftw-feedstock/pull/42 )

**Comment by jakirkham** [comment]
cc @isuruf @mbargull (for awareness)

**Comment by msarahan** [comment]
Thanks for the report.  We'll try to look into it soon.

**Comment by isuruf** [comment]
Ran into this issue in https://github.com/conda-forge/staged-recipes/blob/ee93037176efbf96ff93b6937f6f561eaa458911/recipes/blis/meta.yaml

Issue here is that `build` has `python` in it and I skip `vc<14`, resulting in a mismatch in zip_keys. If `build` section's `python` was ignored then this error wouldn't show up.

Error log https://travis-ci.org/conda-forge/staged-recipes/builds/400497624

**Comment by isuruf** [comment]
Test only python adds a matrix too.

**Comment by jakirkham** [comment]
I think this was fixed at some point (at least for the build only case).

xref: https://github.com/conda-forge/jsoncpp-feedstock/pull/12
