### ISSUE TITLE
Index an empty noarch folder

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2996]
Recently CB started throwing errors when no noarch folder is present in a channel. Fine, there were warnings early enough. 

Anyway, my fix looks somehow like this:

```bash
mkdir -p $(pwd)/builds/noarch
conda index $(pwd)/builds/
```

So: I create a noarch folder (empty) and then index the whole channel.

### Actual Behavior

All subfolders are indexed, I get outputs for "win-64", "linux-64" and "channeldata" _but_ no output for noarch. Not even an empty repodata.json is created. Later in the process I get an http error, that the file "noarch/repodata.json" could not be opened.

### Expected Behavior

I'd expect conda index to create an empty repodata.json in the noarch folder, so that the channel is then recognised as valid.

I know about `touch noarch/repodata.json` but if I use index and a well known folder is present, maybe conda index could do that for me?!

**Comment by gabm** [comment]
My workaround is:

```bash
mkdir -p $(pwd)/builds/noarch
conda index $(pwd)/builds/ $(pwd)/builds/noarch
``` 

not so nice :/

**Comment by msarahan** [comment]
Let me make sure I understand correctly.  I think that there are 2 issues here.

* Conda 4.5 has begun to error out when the noarch folder is not present.  This has been a warning since 4.3.
* Conda-build is recursively indexing all subfolders, except that it seems to not recurse into noarch.  This then causes problems with the first point.

Is that accurate?  The requested fix here is to make the index recursion find the noarch folder?

**Comment by gabm** [comment]
exactly.. I looked into the code and it seems that the noarch folder is used for detection of "channels". Then if I index a _channel_, I'd expect to produce a valid channel after doing so...

Just to be clear, I'm not complaining about the deprecation of that feature - I ignored the warning long enough and thats my own fault...

**Comment by msarahan** [comment]
to be fair, conda-build should be handling this better by always creating that folder as necessary.  I know we do that during the build and test phase, but we're missing something in indexing, apparently.
