### ISSUE TITLE
Proposal: export preprocessing selector values for use in build.sh/.bat

### ISSUE THREAD

**Issue by tjd2002** [conda/conda-build#3010]
When build scripts outgrow the `build/script` section of the recipe and need to be converted to a shell script, it would be convenient to continue using the same logic as is afforded by preprocessing selectors.

I am _not_ proposing that the build script itself be preprocessed (!!), but rather that all preprocessing selectors ([listed here](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html?highlight=selectors#preprocessing-selectors)) be exported in a predictable way, to make scripts easier to port. 

Something like:
```
export SELECTOR_OSX="1"
export SELECTOR_UNIX="1"
export SELECTOR_X86="1"
export SELECTOR_X86_64="1"
export SELECTOR_WIN=""
export SELECTOR_NP="111"
export SELECTOR_PY3K="1"
[...]
``` 
...in conda_build.sh. (I'm not sure if it's more idiomatic to export an empty string for 'false' selectors, or to just leave them unset)

Some of these are already exported (like `$CONDA_NPY`, `$CONDA_PY`, and `$PY3K`, [listed here](https://conda.io/docs/user-guide/tasks/build-packages/environment-variables.html#environment-variables-set-during-the-build-process)), and some can be figured out by inspecting the build system or parsing other vars like `$target_platform`, but this is extra busywork for recipe builders, and could be prone to error (especially in the case of cross-compilation).

**Comment by msarahan** [comment]
variants already provide this in a much more general way, I think.  Have you played around with conda_build_config.yaml at all?  Every key in there is provided as an env var in build.sh/bld.bat.  They are all the same case as they are in conda_build_config.yaml.

**Comment by msarahan** [comment]
This isn't a bad idea, though.  There is a lot of crud like this floating around:  

```
if [[ ${HOST} =~ .*darwin.* ]]; then
```

and having the SELECTOR_OSX might simplify things like that, because I usually have to go find other examples to copy/paste

**Comment by mingwandroid** [comment]
It's crud and only works if you're using compilers.

```if [[ ${target_platform} == osx-64 ]]``` is better.

**Comment by tjd2002** [comment]
Yeah, that's the kind of 'crud' I found myself writing, and looking for a way to avoid. `$target_platform` seems like it is good enough, though it would still require a little shell-fu to do things like substring matches and combining conditions to capture all the logic that's already present in Selectors. 

I think if it was documented that `$host_subdir` and `$target_platform` are always available to shell scripts (along with the full list of platforms), I would close this out. If someone can point me to that list of subdirs, I will make a PR on the docs.
