### ISSUE TITLE
numpy only in test requirements triggers creation of whole build matrix

### ISSUE THREAD

**Issue by lschr** [conda/conda-build#3011]
I have a recipe for a package that does not depend on numpy but requires it for running the tests. Therefore I put numpy in the `test/requires` section of meta.yaml. This then causes the package to be built for all combinations of python and numpy in my conda_build_config.yaml as if the package had a dependency on numpy's binary interface. If I remove numpy from the `test/requires` list, the package is only built once for each version of python, as at should be.

[meta.yaml](https://github.com/conda/conda-build/files/2192495/meta.yaml.txt)
[conda_build_config.yaml](https://github.com/conda/conda-build/files/2192497/conda_build_config.yaml.txt)

##### `Output of conda info`
```
          conda version : 4.5.8
    conda-build version : 3.10.9
         python version : 3.6.6.final.0
               platform : linux-64
```

**Comment by msarahan** [comment]
PS: as a hack until we can fix this, you can use build/force_ignore_keys setting in meta.yaml to force conda-build to ignore numpy.
