### ISSUE TITLE
test/downstreams don't necessarily test with the current build

### ISSUE THREAD

**Issue by mbargull** [conda/conda-build#3016]
### Actual Behavior

ref: https://github.com/conda-forge/perl-feedstock/pull/23
From https://circleci.com/gh/conda-forge/perl-feedstock/39:
```
BUILD START: ['perl-5.26.2-h470a237_1.tar.bz2']
...
TEST START: /opt/conda/pkgs/automake-1.14-1.tar.bz2
Copying package to conda-build croot.  No packages otherwise alongside yours will be available unless you specify -c local.  To avoid this warning, your package must reside in a channel structure with platform-subfolders.  See more info on what a valid channel is at https://conda.io/docs/user-guide/tasks/create-custom-channels.html
WARNING:conda_build.build:Copying package to conda-build croot.  No packages otherwise alongside yours will be available unless you specify -c local.  To avoid this warning, your package must reside in a channel structure with platform-subfolders.  See more info on what a valid channel is at https://conda.io/docs/user-guide/tasks/create-custom-channels.html
updating: automake-1.14-1.tar.bz2

## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/perl_1530741528008/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla


The following NEW packages will be INSTALLED:

    autoconf: 2.69-pl5.22.2.1_5 conda-forge
    automake: 1.14-1            local      
    m4:       1.4.18-0          conda-forge
    perl:     5.22.2.1-0        conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ automake --help
/home/conda/feedstock_root/build_artifacts/perl_1530741528008/test_tmp/run_test.sh: /home/conda/feedstock_root/build_artifacts/perl_1530741528008/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/automake: /usr/bin/perl: bad interpreter: No such file or directory
Tests failed for automake-1.14-1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for automake-1.14-1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
removing: automake-1.14-1.tar.bz2
TESTS FAILED: automake-1.14-1.tar.bz2
Exited with code 1
```

### Expected Behavior

`conda-forge::perl=5.26.2=h470a237_1`, build that has just been created should be tested, not the older `conda-forge::perl=5.22.2.1=0` one.

**Comment by mbargull** [comment]
Expected behavior if downstream packages are pinned such that they cannot be installed alongside the newly built package:
Catch the non-satisfiable error from `conda`, print out a warning and just skip the test for that downstream package.

**Comment by mingwandroid** [comment]
A minor point, but I'd rather this defaulted to being an error. If I've explicitly listed a package as needing downstream testing then I definitely don't want to ignore it as a bog-standard warning when we mess up our pinning.

**Comment by mbargull** [comment]
> A minor point, but I'd rather this defaulted to being an error.

In case of (justified) strict pinnings this creates a bootstrapping issue. What would you suggest to get out of that "defaulted to being an error" then? I can't think of a feasible/reasonable way to do that from the top of my hat. Any ideas?

**Comment by mingwandroid** [comment]
Perhaps conda-build needs a bootstrapping mode where the default is swapped?

**Comment by msarahan** [comment]
I'd rather not have another extra flag here.  I think warnings are fine here for now.  We don't (and I think we won't) have specific constraints on downstream tests - only maybe version numbers, and skipping these things with a loud message seems sufficient to me.
