### ISSUE TITLE
Package Hash is non-deterministic?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#3017]
Contents of gen.py:
```python
import conda_build.api

metas = conda_build.api.render('.', variant_config_files=['../.ci_support/win_.yaml'])
for meta, _, _ in metas:
    fnames = conda_build.api.get_output_file_paths(meta)
    for fname in fnames:
        print(fname)
```
```bash
$ git clone https://github.com/conda-forge/go-feedstock
$ cd go-feedstock/recipe
$ python gen.py
$ python gen.py
...
```

On a single run, one will see that it outputs two names for go-core:
```
/home/wani/m3/conda-bld/linux-64/go-core-1.10.3-h22be3a3_1.tar.bz2
/home/wani/m3/conda-bld/linux-64/go-core-1.10.3-h7ee7fc2_1.tar.bz2
/home/wani/m3/conda-bld/linux-64/go_linux-64-1.10.3-h0f5337a_1.tar.bz2
/home/wani/m3/conda-bld/linux-64/go_osx-64-1.10.3-h144c09f_1.tar.bz2
/home/wani/m3/conda-bld/linux-64/go_win-64-1.10.3-h2df250f_1.tar.bz2
/home/wani/m3/conda-bld/linux-64/go-1.10.3-1.tar.bz2
```

Now, when I run conda-build on this feedstock, I see that it generates different hashes on different runs for the go-core package:
```
CONDA_SUBDIR=win-64 conda build . -m ../.ci_support/win_.yaml -c https://repo.anaconda.com/pkgs/msys2/win-64/
```
```
BUILD START: ['go-core-1.10.3-h22be3a3_1.tar.bz2', ...]
```
```
BUILD START: ['go-core-1.10.3-h7ee7fc2_1.tar.bz2', ...]
```

This can hurt reproducibility. Already hurt conda-forge at: https://ci.appveyor.com/project/conda-forge/go-feedstock/build/1.0.93

**Comment by msarahan** [comment]
Are you using python 2 or 3?  What are the contents of the hash in all of these cases?

**Comment by nehaljwani** [comment]
I had used python3 for the first post.

For python2, the hashes are same, but the order is always h7ee7fc2 coming before h22be3a3 via gen.py and when conda-build is invoked, the hash for go-core is always h22be3a3

**Comment by msarahan** [comment]
what does ``conda inspect hash-inputs <pkg name>`` show for these?

**Comment by nehaljwani** [comment]
conda-build always creates only one of the either two go-core packages. So, it would take a long time to get those two tarballs. Instead, I added the following to gen.py:

```python
    print(meta.get_hash_contents())
```

And now I see:
```
{'c_compiler': 'vs2015', 'fortran_compiler': 'flang', 'cxx_compiler': 'vs2015'}
/home/wani/m3/conda-bld/linux-64/go-core-1.10.3-h22be3a3_1.tar.bz2
{'c_compiler': 'vs2008', 'fortran_compiler': 'flang', 'cxx_compiler': 'vs2008'}
/home/wani/m3/conda-bld/linux-64/go-core-1.10.3-h7ee7fc2_1.tar.bz2
```

**Comment by msarahan** [comment]
huh?  That's confusing.  c_compiler should definitely NOT be vs2015 on linux.  That is guarded by a selector.  It seems like maybe something is going wrong with the variants.

**Comment by nehaljwani** [comment]
No, this is all Windows. I am forcing the runs using `CONDA_SUBDIR` because I am too lazy to remote into a Windows machine.

**Comment by nehaljwani** [comment]
I think we wanted to not use `compiler('c')` at all on Windows, so some jinja2 magic was used at: 

```python
      build:
        {% if not win %}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        {% else %}
        - {{ n }}toolchain
        {% endif %}
```
But conda-build still thinks that `c_compiler` is to be honored.

**Comment by msarahan** [comment]
Whoa, you're expecting way too much from the detection of used variables.  You are well into special case territory.  I recommend using the ``build/force_ignore_keys`` field for this.  Tell it to ignore c_compiler, and use a selector to limit it to windows.

I'm not going to fix this otherwise.  The juice is not worth the squeeze.  Feel free to take it on if you'd like.

**Comment by nehaljwani** [comment]
Yes, I have faced the same issue with other feedstocks like nodejs and ninja ... 

I'll stick with `build/force_ignore_keys` for now. Thanks.

**Comment by jakirkham** [comment]
FWIW we had similar hopes with selectors, which currently don't work. ( https://github.com/conda/conda-build/issues/2958 ) Though maybe that path is more tractable than supporting Jinja.
