### ISSUE TITLE
Suggestion: honor script section for Windows

### ISSUE THREAD

**Issue by ovz** [conda/conda-build#302]
At present build.py ignores script section if sys.platform == 'win32'. Assuming my custom script is cross-platform (e.g. python my_script.py) would be great to run custom script unconditionally.

**Comment by asmeurer** [comment]
Is this the same as https://github.com/conda/conda-build/pull/286?

**Comment by ovz** [comment]
Correct. #286 doesn't mention Windows, only win32, so I missed it in the search. 

The patch looks good too.
