### ISSUE TITLE
build/no_link is not honored when it has a pattern

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#3023]
I tried building the conda-forge nginx package. Recipe: https://github.com/conda-forge/nginx-feedstock

Package: https://anaconda.org/nwani/nginx/1.14.0/download/linux-64/nginx-1.14.0-h1c2f66e_0.tar.bz2

In the recipe, `build/no_link` has `/etc/*` and conda build does create a file with the contents in `info/no_link` inside the package, however conda gives more priority to `info/paths.json` and in this file, conda build doesn't put `no_links: true` for the files in `etc/*` and this causes trouble, since conda thinks that this file has to be hard linked and not copied.

**Comment by LonelyPilgrim** [comment]
conda-build 3.10.9, dated June 22, 2018 -- so I think you're right; this may fix the problem. We are running this on a closed network without ready access to updates from the Anaconda repository, but I will push an update through and see if that fixes it. Thanks!
