### ISSUE TITLE
Test environment incorrectly prioritizes local channel

### ISSUE THREAD

**Issue by Bezier89** [conda/conda-build#3036]
Scenario:

- Developer is working on two conda packages, "pkgA" and "pkgB".
- Developer builds pkgA at version 1.0
- Developer uploads pkgA=1.0 to conda channel
- Second developer (or the same developer on a different machine) works on pkgA at version 2.0.
- Second developer uploads pkgA=2.0 to conda channel
- Developer starts work on pkgB, which has a dependency on pkgA, and requires functionality only present in pkgA >= 2.0.
- Developer attempts to build pkgB but unit tests fail.

Actual behavior:

The test environment is pulling pkgA=1.0 from the local conda-bld folder, instead of the newer pkgA=2.0 from their conda channel. This causes tests to fail and the build is broken.

Expected behavior:

The test environment pulls from the user's defined set of channels before it falls back to the local channel. This will cause pkgA=2.0 to be pulled as expected and unit tests to pass.

**Comment by msarahan** [comment]
This is kind of contentious.  It is the way that it is because building has historically not been such a distributed activity.  If remote channels are higher in priority, local packages will almost never be used to fulfill dependencies.  They would only be used if a remote package didn't exist, or was otherwise unsatisfiable.

It is more intuitive to me that local be higher priority by default.  If you'd like to change that, I recommend adding ``-c yourchannel``, which I hope will take priority over local.  Unfortunately, I think local is defined as the top priority, according to https://github.com/conda/conda-build/blob/master/conda_build/index.py#L65

I'm not sure how accurate that comment actually is, though.  Give it a shot?

**Comment by Bezier89** [comment]
That comment appears to be correct, i.e. adding "-c mychannel" will NOT
cause mychannel to be prioritized over local packages. Personally, I would
expect it to be the case that "local packages will almost never be used to
fulfill dependencies" during a build (outside of the package actually being
built), but I can also understand not wanting to change the default
behavior. I would be ok with "-c mychannel -c local" as a workaround if
that actually worked. Actually what would be really cool is if we could
provide a custom environment file that conda-build would use (and
additionally install the just built package into) for creating the test
environment.

**Comment by msarahan** [comment]
#3038 should be a good compromise, I think.

For your custom environment file, I recommend a metapackage with your environment's dependencies.  You can then add that as a test/requires value.  You can use recipe_appends.yaml to add your metapackage: https://conda.io/docs/user-guide/tasks/build-packages/variants.html#appending-to-recipes

recipe_appends is not global, though.  We've been playing with the idea of making recipe_appends and clobber global, but haven't hit a strong need yet.  Maybe this is one.

**Comment by mingwandroid** [comment]
I *always* want `local` first.

**Comment by mingwandroid** [comment]
It's cost me many hours at various points when it wasn't first. I can't understand any logic whereby the new stuff you're building isn't what you want for the even newer stuff you're building.

I believe your stuff in the initial comment represents a *very* infrequent corner-case involving a race condition between two different developers and unlikely to happen often.

**Comment by Bezier89** [comment]
@mingwandroid That's why I posted an actual use case. It's not really an edge case if you work with a team. If you're using some sort of CI servers (e.g. Jenkins) to perform your builds, this becomes even more common. We actually hit this quite often, and it would be nice to have a solution better than "delete the conda-bld folder".

Anyway, thanks for pull request @msarahan. I agree that's a reasonable compromise since it will only affect those using the "-c" flag when building, and when using the "-c" it makes sense that those channels should take precedence.

**Comment by Bezier89** [comment]
@msarahan Can this issue be reopened? Looks like it was broken almost immediately after being fixed :( I've confirmed that it works in conda-build=3.12.1, but not in conda-build=3.13.0
