### ISSUE TITLE
version pin with epoch incorrectly parsed as strict

### ISSUE THREAD

**Issue by carlodri** [conda/conda-build#3037]
After the release of https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/98, recipe at https://github.com/conda-forge/ffmpeg-feedstock/pull/51 seems to pick up the `1!152` pin for `x264` as a strict pin, rather than the expected fuzzy pin like `1!152.*`.

Relevant CI: https://travis-ci.org/conda-forge/ffmpeg-feedstock/jobs/405819733#L378

This could point to a bug/inconsistent behavior somewhere in the conda toolchain handling version parsing (probably versions containing epochs?). It appears that `1!152` is not parsed in the same "fuzzy" way as, _e.g._ `1.4`.

IIUC, `1.4` allows for `1.4.1`, `1.4.2` and so on. Similarly, `1!152` should allow for `1!152.20180712`, whereas it does not (see CI linked above), and strictly pins to `1!152`.

Adding a wildcard as in `1!152.*` (see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/101) circumvented the problem.

**Comment by msarahan** [comment]
Thanks for the report.  I think this is a problem in conda-build, as I'm pretty sure conda supports epochs properly.
