### ISSUE TITLE
Conda build doesn't recognize when it can't overwrite package

### ISSUE THREAD

**Issue by Bezier89** [conda/conda-build#3044]
Repro steps:

1. Build a package (any package will do).
2. Open the package file (*.tar.bz2) in a such a way that there's a lock on writing to it. The easiest way to do this on Windows if you have 7-zip installed is to navigate to the package, right-click on it, and select "7-Zip -> Open archive".
3. Build the package again.

Actual result:

Build appears completely successful. No error messages, and if I run "echo %ERRORLEVEL%" it prints 0. However, timestamp on the file indicates that it was not updated.

Expected result:

Logs should indicate that the build failed failed (i.e. was not able to overwrite the the package at the given location). ERRORLEVEL should be non-zero.

**Comment by msarahan** [comment]
This is definitely an issue, but I'm sorry to say that we can't prioritize it highly.  We'd welcome a PR, but this is not a common enough use case to spend much of our time on right now.

If you are an enterprise user, please file a support ticket with the enterprise support desk, and they can boost its priority.

**Comment by Bezier89** [comment]
@msarahan It's admittedly not super high-priority for us either, just something I noticed. I may or may not get around to writing a PR for it :P
