### ISSUE TITLE
Additional information in package's info/about.json

### ISSUE THREAD

**Issue by mikecormier** [conda/conda-build#3046]
### Actual Behavior

The info/about.json excludes many of the keys in the package's meta.yaml. 
### Expected Behavior

That the  info/about.json includes the information of the "extra" key in the package's meta.yaml file.
Both the bioconda group and our group, Got Get Data (GGD), would like the extra information added to the about.json file in order to utilize this information for registry querying and tag based searching. Conda is also looking into adding an additional metadata channel json file, which would include a combination of the info/index.json and info/about.json with the "extra" key info included. (https://github.com/conda/conda/issues/7583)

Could you add the information from the "extra" key in the meta.yaml file to the info/about.json file?

**Comment by msarahan** [comment]
Seems reasonable.  Please consider putting up a PR.  We're too busy to work on this ourselves right now.

**Comment by mikecormier** [comment]
Hi @msarahan,

I have create a PR that includes the extra field of the meta.yaml file in the about.json file. 
https://github.com/conda/conda-build/pull/3048
