### ISSUE TITLE
License file given in about/license_file does not exist in source root dir or in recipe root dir (with meta.yaml)

### ISSUE THREAD

**Issue by bgruening** [conda/conda-build#3058]
### Actual Behavior

cb3 in conda-forge is given the following error:

```
License file given in about/license_file does not exist in source root dir or in recipe root dir (with meta.yaml)
```

For example here: https://circleci.com/gh/conda-forge/r-poilog-feedstock/3?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

According to @isuruf this is because the host env is moved before license file is copied, and therefore the license file cannot be found.

### Expected Behavior

copy the license file.

### Steps to Reproduce

rerun the build from https://github.com/conda-forge/r-poilog-feedstock/pull/1

**Comment by bkreider** [comment]
It looks like this is no longer an issue once the path was fixed in the recipe to no use escaped separators.
