### ISSUE TITLE
Conda convert fails to convert noarch:python packages

### ISSUE THREAD

**Issue by p3trus** [conda/conda-build#3059]
### Actual Behavior

Hello I tried to convert a custom pure python conda package, which was build with `noarch: python`.
The conversion fails due to an Attribute Error.

The attribute error is trigger in 
https://github.com/conda/conda-build/blob/dbe358aac2c226ca57e340187749568987b841f6/conda_build/convert.py#L69

conda info shows that the platform attribute of the noarch:python package is set to None.

**Comment by msarahan** [comment]
Why are you trying to convert a noarch package?  They install on any arch, and don't need to be converted.

**Comment by p3trus** [comment]
Because conda constructor does not work with noarch according to
https://github.com/conda/constructor/issues/86

**Comment by msarahan** [comment]
duplicate of https://github.com/conda/conda-build/issues/2611, closing

**Comment by p3trus** [comment]
By the way throwing an Attribute Error is still a bug.

**Comment by msarahan** [comment]
I won't deny that it's a bug.  We have limited resources, and we can't fix everything.  If you'd like to contribute a PR, it would be much appreciated.  This is not something we use, and we can't justify spending our time on it right now.
