### ISSUE TITLE
%PYTHON% is not present on Windows

### ISSUE THREAD

**Issue by tswicegood** [conda/conda-build#306]
While trying to build [this commit](https://github.com/conda/conda-javascript-recipes/tree/55dd25f78cf89a69839954ae563ffd86a423800c) on binstar, I got [this error](https://binstar.org/javascript/iojs/builds/6/3).  It appears that `python.exe` is not present at the expected path even though the python package was downloaded and installed.

**Comment by patricksnape** [comment]
`%PYTHON%` does exist, otherwise it wouldn't print the path out. It looks like the build is breaking earlier than that which prevents the `_build` environment from being set up correctly [(this line)](https://binstar.org/javascript/iojs/builds/6/3#L33).

**Comment by asmeurer** [comment]
Ooh, my favorite error message ever.
