### ISSUE TITLE
How to suppress adding a run dependency to statically linked libraries?

### ISSUE THREAD

**Issue by sdvillal** [conda/conda-build#3062]
### Actual Behavior

When a dependency with "run_exports", lets say a library to be statically linked,  is added to the host section, it is unconditionally added as a run dependency with appropriate pin. Since the library has been statically linked, it is not needed at runtime. Therefore, adding it can only lead to a waste of resources, in the best case, if not to other problems.

### Expected Behavior

There should be a way to disable the dependency to be added at runtime, other than, let's say, moving it to the "build" section.

### Steps to Reproduce

My use case is statically linking [libjpeg-turbo](https://github.com/loopbio/libjpeg-turbo-feedstock/blob/7d597232b30998202b02a6622f135b6039317d97/recipe/meta.yaml#L109-L112) into a custom build of opencv, but it is easily reproducible with any package adding run_exports.

**Comment by mingwandroid** [comment]
Use ignore_run_exports

**Comment by sdvillal** [comment]
Ups, overlooked that one. Works like a charm.
