### ISSUE TITLE
conda-build uses wrong environment variable for Jinja2 PrefixLoader

### ISSUE THREAD

**Issue by yevgenybezman** [conda/conda-build#3063]
In metadata.py, conda-build uses $CONDA_DEFAULT_ENV as a location for Jinja2 template loader.
In recent conda verisons, $CONDA_DEFAULT_ENV has the name of the environment rather than its path.
$CONDA_PREFIX is the variable that contains the path of the environment.

**Comment by msarahan** [comment]
Yep, that's a bug. Please consider submitting a PR. We won't get to this
soon as we don't use this particular feature right now.
