### ISSUE TITLE
Automatically remove .la files after the build

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#3075]
I could not find an issue for this but please just close it in case it is duplicate.

@mingwandroid suggested that conda-build could automatically remove `.la` after a build and I "volunteered" @justcalamari to help us implement that :stuck_out_tongue_winking_eye: 
(If he can find some free time for it after GSoC.)

Edit: it would be nice to have this before `conda-forge` starts the compiler migration so all the new packages would have its `.la` files removed.

**Comment by msarahan** [comment]
fixed by #3102

**Comment by ocefpaf** [comment]
Sorry. I forgot to cross link my own issue :flushed:
