### ISSUE TITLE
Cache compilation results such that only 'test' stage could be executed

### ISSUE THREAD

**Issue by dmitry-kabanov** [conda/conda-build#3079]
### Actual Behavior

I build a package and 'test' stage fails for weird reasons (the same commands do not fail if I just execute them after installing the package using `--use-local` flag).
Each time I change the 'test' stage to execute tests (and I have to do it multiple times because of the above weird behavior), `conda` starts compilation from the very start, which is inconvenient as the compilation takes more than 30 minutes.

### Expected Behavior

Ability to tell `conda build` to bypass download and compilation and start with 'test' stage.

**Comment by msarahan** [comment]
This is more or less the use case for the ``--dirty`` flag.  You can edit your build.sh/bld.bat file to skip compilation based on the presence of the DIRTY environment variable, or you could skip large parts of your build script based on whether some file is present.  See https://github.com/AnacondaRecipes/aggregate/blob/master/ctng-compilers-feedstock/recipe/build.sh#L63 as an example.

**Comment by dmitry-kabanov** [comment]
Thanks!
I didn't know about this flag.
