### ISSUE TITLE
String vs int type for build number in rendered recipes causes issues with conda-forge

### ISSUE THREAD

**Issue by benbovy** [conda/conda-build#3095]
### Actual Behavior

In some cases, e.g., when a recipe contains multiple outputs, the build numbers in the rendered recipe (i.e., the returned object from `conda_build.api.render`) may have different types. I guess that if present the parsed number is by default a string, but if it is absent it may be added as an int here:

https://github.com/conda/conda-build/blob/86fee985afe63d4f661332f60f6e30c652d2f894/conda_build/metadata.py#L1846

### Expected Behavior

Build numbers in a recipe with multiple outputs should have the same type. Otherwise this may cause issues with recent conda-forge where it incorrectly detects more than one build number, even if we use a unique build number value, i.e, the code here

https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/branch2.0/recipe/conda_forge_ci_setup/build_utils.py#L121-L125

doesn't work nicely with ``build_numbers = {'0', 0}``.

I'm not sure if this issue should be fixed here or in conda-forge-ci-setup, though.

### Steps to Reproduce

See https://github.com/conda-forge/fastscapelib-feedstock/pull/3

##### `Output of conda info`

```
     active environment : conda-forge-tools
    active env location : /Users/b/miniconda3/envs/conda-forge-tools
            shell level : 1
       user config file : /Users/b/.condarc
 populated config files : /Users/b/.condarc
          conda version : 4.5.10
    conda-build version : 3.10.7
         python version : 3.5.4.final.0
       base environment : /Users/b/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/b/miniconda3/pkgs
                          /Users/b/.conda/pkgs
       envs directories : /Users/b/miniconda3/envs
                          /Users/b/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.10 requests/2.18.4 CPython/3.5.4 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/25#issuecomment-418471044

If anyone wants to fix this on the conda-build side, please consider a PR (and a test would be nice, too).
