### ISSUE TITLE
Can't get conda index to work with channel_name

### ISSUE THREAD

**Issue by teake** [conda/conda-build#3112]
From the updated docs on 3.14.0, `channel_name` is now a positional argument. However, when I do
```bash
$ conda index <build_dir> <channel_name>
```
I get
```
(...)
FileNotFoundError: [Errno 2] No such file or directory: '<path_prefix>/<channel_name>'
```
instead of a custom channel name in the outputted html files. 

Am I forgetting some special `argparse` magic or did #3091 introduce a bug?

I'm on conda 4.5.11 and conda-build 3.14.0

**Comment by msarahan** [comment]
This should have been a flag, not a positional argument.  As a positional arg, it conflicts with the variable length input for the build dirs.  I will fix it.
