### ISSUE TITLE
Failure in conda build process, missing `noarch/repodata.json`

### ISSUE THREAD

**Issue by marcelotrevisani** [conda/conda-build#3114]
I have seeing some errors in ``conda-forge`` after the new ``conda-build`` release.

The error is regarding a missing ``noarch/repodata.json``.

It's possible to see the conda version and also the process in this link:

https://circleci.com/gh/conda-forge/staged-recipes/30232?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

There are at least 3 packages which are failing in ``conda-forge``, like:
https://github.com/conda-forge/staged-recipes/pull/6587
https://github.com/conda-forge/staged-recipes/pull/6623
https://github.com/conda-forge/staged-recipes/pull/6624

And there is an open issue in ``conda-forge`` regarding that:
https://github.com/conda-forge/staged-recipes/pull/6587

**Comment by marcelotrevisani** [comment]
Quoting @mbargull 

> @marcelotrevisani, I didn't take an in depth look at it, but it's possibly a bug introduced with the index changes in conda-build 3.14. If you don't find any other explanation, please raise a conda-build issue.

**Comment by marcelotrevisani** [comment]
cc: @nicoddemus

**Comment by msarahan** [comment]
It could be a problem in the new conda index, but conda index is not used by anaconda.org at all.  This seems potentially like an anaconda.org problem, which may instead be tied to a recent re-deployment that we had to do because disks were full.

**Comment by mbargull** [comment]
It's not `anaconda.org`, it's not finding the local build channel. (Though I have no idea why this gives an HTTP error :confused:.)

**Comment by msarahan** [comment]
I looked at the error more, and it's definitely a conda-build problem.  The 404 is happening on the local channel.  I'll take a look at this ASAP.

**Comment by msarahan** [comment]
This is happening because update_index was changed to operate on whole channels, not on subdirs.  https://github.com/conda-forge/staged-recipes/blob/master/.ci_support/build_all.py#L34

We probably need to fix conda-smithy in the long-term, but for the short-term, I'll put in a fix to conda-build and a deprecation warning.

Sorry for the unintentional breaking change.

**Comment by marcelotrevisani** [comment]
Hi @msarahan this is still failing with ``conda-build`` ``3.14.1``

https://circleci.com/gh/conda-forge/staged-recipes/30234?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by msarahan** [comment]
hmmm.... it is taking the new code path I put in:

```
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
```

I'll have to try again.

**Comment by marcelotrevisani** [comment]
Thanks @msarahan to fix this!  :)
