### ISSUE TITLE
How to export a build requirement?

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#3122]
I have a script that generates protobuf files for me, and I want to use it in cross compiling scenario. So the structure is somehow:

```
- executable
  - script
    - libprotobuf
    - protoc
```

so the executable depends on the script package, which has a run dependency to libprotobuf and protoc, the protobuf compiler package.

That works fine in a non-cross compiling scenario. But now we want to do cross compiling, and that would require, that during the build time of my executable, we resolve libprotobuf from the target architecture (host) and the compiler from the source architecure (protoc)...

My first shot was "run_exports", but that seems to export run dependencies, which is not what we need. Is there somehting that tells conda to resolve protoc as build requirement, without explicitly listing it in "executable"?

**Comment by msarahan** [comment]
list the thing that has protoc as a build dep, and list the thing that has libprotobuf as a host dep.

**Comment by gabm** [comment]
> list the thing that has protoc as a build dep, and list the thing that has libprotobuf as a host dep.

hmm its the same thing.. the "script" in the above example.. Ideally I would only want to list "script" as a dependency of "executable"..

**Comment by msarahan** [comment]
it's fine for the dep to be the same package.  You'll be installing different things (from different subdirs).  The build env comes first on PATH, so its protoc should get found before anything in the host env.

**Comment by gabm** [comment]
great, I didn't think about that!.. thank you!
