### ISSUE TITLE
skip-existing fails with basic auth channels

### ISSUE THREAD

**Issue by teake** [conda/conda-build#3127]
The `--skip-existing` option doesn't work for channels with basic authentication, i.e. those of the form `https://<user>:<pass>@<path>`. 

It fails to identify identical packages because the package index dictionary is indexed with canonical urls (without the `<user>:<pass>` bit), but the search url does contain `<user>:<pass>` section.

The culprit is this line: https://github.com/conda/conda-build/blob/520f858c2ce2d1cb447d4f1ded40db0845780378/conda_build/build.py#L2499

The `url` here contains the auth section, whereas the keys in the `index` dictionary are parsed from [channel urls wrapped in `Channel`](https://github.com/conda/conda/blob/21a8f3946d8cf9ce3803e2826be6e50400557f91/conda/models/channel.py#L493).

A relatively straightforward fix would be to do `str(Channel(url)) + '::' + metadata.dist())`, but `Channel` is not export by conda.

**Comment by msarahan** [comment]
@kalefranz please comment on the suggested use of conda internals here.  Conda-build definitely needs to learn about the channel syntax at some point soon.

**Comment by kalefranz** [comment]
If we were to use new apis, I'd probably recommend something like

```python
from conda.api import SubdirData

def is_package_built(metadata, env, include_local=True):
    for d in metadata.config.bldpkgs_dirs:
        if not os.path.isdir(d):
            os.makedirs(d)
        update_index(d, verbose=metadata.config.verbose)
    subdir = getattr(metadata.config, '{}_subdir'.format(env))

    urls = [url_path(metadata.config.output_folder), 'local'] if include_local else []
    urls += get_rc_urls()
    if metadata.config.channel_urls:
        urls.extend(metadata.config.channel_urls)

    spec_str = " ".join((metadata.name(), metadata.version(), metadata.build_id()))
    return bool(next(SubdirData.query_all(spec_str, channels=urls, subdirs=(subdir, "noarch")), None))

```

Notice that I de-dented `update_index(d, verbose=metadata.config.verbose)` by one level.  My guess is that with the new `conda index` code, there won't be any noticeable performance impact by not handling `index` directly.  I think it's at least worth a try in a PR to see if it dramatically impacts CI times.  Honestly, it might even be faster.

If you don't want to go this route, I'd suggest as an alternative:

```python
from .conda_interface import MatchSpec

def is_package_built(metadata, env, include_local=True):
    for d in metadata.config.bldpkgs_dirs:
        if not os.path.isdir(d):
            os.makedirs(d)
            update_index(d, verbose=metadata.config.verbose)
    subdir = getattr(metadata.config, '{}_subdir'.format(env))
    index, index_ts = get_build_index(subdir=subdir,
                                      bldpkgs_dir=metadata.config.bldpkgs_dir,
                                      output_folder=metadata.config.output_folder,
                                      channel_urls=metadata.config.channel_urls,
                                      debug=metadata.config.debug,
                                      verbose=metadata.config.verbose,
                                      locking=metadata.config.locking,
                                      timeout=metadata.config.timeout,
                                      clear_cache=True)

    spec = MatchSpec(name=metadata.name(), version=metadata.version(), build=metadata.build_id())
    return any(spec.match(prec) for prec in index.values())

```
