### ISSUE TITLE
error when using --variants CLI flag

### ISSUE THREAD

**Issue by ifmar** [conda/conda-build#3128]
When I use the --variants flag to specify variants via command line argument, as described in the documentation of build variants, I get an unrecognized arguments error:

`unrecognized arguments: --variants {'c_compiler':['gcc'], 'target_platform':['linux-aarch64']}`

Even the example from the docu produces the same error. I use conda version: 4.5.4 and conda-build version: 3.10.7.

I want to use the CLI flag to separate multiple build jobs for cross compiling in our CI instead of using a single job with a build matrix. Is there another way to achieve this?

**Comment by mingwandroid** [comment]
You should put your variants in conda_build_config.yaml and pass that with -m to the command line.

**Comment by mingwandroid** [comment]
Whether did you see those flag? The documentation is at https://conda.io/docs/user-guide/tasks/build-packages/variants.html

**Comment by ifmar** [comment]
Ok thanks for your answer. I will use the -m flag with multiple conda_build_config.yaml files.

Since the flag is also not mentioned in conda build command reference, it seems to me that the --variants may not implemented.

**Comment by msarahan** [comment]
Hmmm... it does appear that it got dropped at some point.  Sorry about that.  That was not intentional.

Anyway, I think I have some ideas for how to make it nicer.  We should be able to allow passing arbitrary arguments by using argparse's parse_known_args function, and handling any unknown args ourselves.  That would make your command something like:

``conda build recipe --target_platform linux-aarch64``

We'll put that feature request into our backlog.

**Comment by gabm** [comment]
`conda build recipe --target_platform linux-aarch64` 

Would be very useful I think... very clear syntax ...

**Comment by msarahan** [comment]
The crappy thing about it is that any typos would be totally uncaught.  Any unknown key at all would just become a variant.

``conda build recipe --pyhton 3.6``

would not raise an error...

**Comment by gabm** [comment]
because we would interpret anything unknown as variant.. thats true, not good at all...

What about something similar like this:

`conda build recipe --variant target_platform=linux-aarch64`

**Comment by gabm** [comment]
I created #3168 with a possible solution.. I think it looks quite neat and is safe

**Comment by msarahan** [comment]
Thanks to @gabm this is re-implemented.  Closing this issue.
