### ISSUE TITLE
running conda skeleton cran in an offline environment

### ISSUE THREAD

**Issue by sephib** [conda/conda-build#3142]
Hi,
We are trying to build some R cran packages  in anaconda in an offline environment.
We could not find documentation for the above issue.

### Actual Behavior
When running
> conda skeleton cran PACKAGE_NAME

the system is trying to fetch the metadata from https://cran.r-project.org
But since we are in an offline environment the system raises an error.

BTW - we have installed `CacheControl` and `lockfile`

1. Where is the metadata that conda is trying to fetch?
2. Where should we save this metadata in the offline environment in order for `conda` to find it?

Thank you in advance for your time

##### `conda info`
> active environment : None
> shell level : 0
> user config file : /home/myuser/.condarc
>  populated config files : /home/myuser/.condarc
>           conda version : 4.5.11
>     conda-build version : 3.10.5
>          python version : 3.6.5.final.0
>        base environment : /home/myuser/anaconda3  (writable)
>           package cache : /home/myuser/anaconda3/pkgs
>                           /home/myuser/.conda/pkgs
>        envs directories : /home/myuser/anaconda3/envs
>                           /home/myuser/.conda/envs
>                platform : linux-64
>              user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.4.73-5-default sles/12.3 glibc/2.22
>                 UID:GID : 1000:1000
>              netrc file : None
>            offline mode : True
> 

```

```

**Comment by msarahan** [comment]
This is something we haven't really considered.  Please feel free to explore the source code in conda_build/skeletons/cran.py, and let us know if you have questions.  We'll gladly accept a PR that adds or improves the process, if you have time.

**Comment by sephib** [comment]
Hi,
Thx for directing me to the relevant code file.
will update once I find a solution and possibly a PR
