### ISSUE TITLE
Package name/hash collision when cross-compiling

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#3155]
I'm cross-compiling a package that depends on flatbuffer on linux-64 for linux-aarch64. My flatbuffer package contains a flatc executable (compiler) and a libflatbuffers library. As suggested in #3122 I listed flatbuffers as build and host dependency, so that we get once the build-native and once the target-host-native version - once for linking and once for executing the compiler...

### Actual Behavior

Sometimes I get the aarch64 executable installed into my linux-64 build env, which leads to a failure when being executed.. I dug a bit deeper and found out that the flatbuffers package is called `flatbuffers-1.9.0p1-h75f9260_15` for _both_ platforms. It only exist _once_ in the conda package cache...

In case my build works, the flatc executable in `/root/miniconda3/pkgs/flatbuffers-1.9.0p1-h75f9260_15/bin` is an x86_64 executable, in case it doesnt work its an aarch64 file. Here is some kind of race condition. 

### Expected Behavior

It should work always... I guess either the hashes shouldn't collide - or the different architectures should be unpacked into different `/root/miniconda3/pkgs` folders for the different architectures...

##### `Output of conda info`

```

```

**Comment by gabm** [comment]
I experienced the same problem again with ncurses from conda-forge:

```
conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
conda-forge/linux-aarch64::ncurses-6.1-hf484d3e_1002
```
both get downloaded and during extraction the aarch64 ends up in the build_env on my intel64 machine...

**Comment by msarahan** [comment]
I think separate package caches for each channel and subdir in conda would be the best fix.  PRs are welcome.

**Comment by gabm** [comment]
I had a look and found that the architecture might be set in the PackageCacheData class here: https://github.com/conda/conda/blob/master/conda/core/package_cache_data.py#L65

We could enhance the calls to the public API by providing the target architecture as a new, optional parameter ike this:

```
PackageCacheData.writable_caches(target_arch=arch)
PackageCacheData.first_writable(target_arch=arch)
```

Where `target_arch` corresponds to the subchannels we use, namely `noarch`, `win-64`, `linux-aarch64` and so on.. 

The PackageCacheData object might then create separate caches in `pkgs` for each requested arch.

```
pkgs
pkgs/noarch
pkgs/win-64
...
```
Calling these functions without the new parameter - or with the your native architecture, the resulting directory will stay just `pkgs`. That way we can avoid upgrade problems. All packages of foreign architectures will be downloaded and extracted to their respective folders.

What do you think?

**Comment by msarahan** [comment]
I'm not sure that is going to be enough.  Conda-build doesn't use this API, I don't think.  It just asks conda to create environments, and conda then manages the caches in whatever way it wants.  Thus, I think it is necessary to change how conda handles its caches internally - conda should separate caches in all cases.  We'd end up with cache structure like:

pkgs/some_channel/win-64
pkgs/defaults/noarch

or maybe

pkgs/repo.anaconda.com/pkgs/main/noarch (url slashes preserved)

or

pkgs/repo.anaconda.com_pkgs_main/noarch (url slashes sanitized somehow)

and so on.  Cache lookup then also needs to be adapted to account for the more finely grained cache layout.  If any backward compatibility is found to be necessary, the root pkgs could contain copied or linked files into the more specific subdirectories.  I don't think backcompat is very important here.  Any incompatibility leads not to broken behavior, but just downloads that would otherwise be unnecessary.

**Comment by gabm** [comment]
I was afraid of something like this... you're right, the different channels should also be accounted for. Also your analysis, that compatibility is unnecessary, is totally right.

I'm afraid my knowledge of the conda internals is way too limited for a change of this scale :(

**Comment by mingwandroid** [comment]
We need to fix this. I propose the package cache is made 1 level more deep. This extra level could be a hash of the channel URL and the subdir or something more descriptive.

This would also allow conda's seldom used install-via-symlink mode to have a chance of behaving reasonably (in some cases!)

Pinging @chenghlee about this.

**Comment by mingwandroid** [comment]
.. this also turned out to be the root cause of win-32 and win-64 matrix builds failing! It would mix software for each arch happily.

**Comment by jjhelmus** [comment]
The charge proposed by @mingwandroid to make the package cache an additional level deep so that includes the subdir is the best option in my opinion.  This would require a change in conda not conda-build.

**Comment by gabm** [comment]
I think we should consider going for the "2-additional-level" solution (`<channel-name>/<platform>/`) outlined by @msarahan above, if the effort is not too much higher. That would avoid package collision altogether and the problem would disappear forever. The 1-folder solution is just a partial fix

**Comment by mingwandroid** [comment]
We can encode what we want into a single level. The other benefit of single level is that conda's install-via-symlink has a (snowball's) chance (in hell) of working :-)

**Comment by isuruf** [comment]
Should this be done in `conda` or `conda-build`? Do we care about keeping it working as it was for the case of `native` and one channel?

**Comment by mingwandroid** [comment]
I think it needs a change to conda, and some code to update old package caches. Pinging @chenghlee

**Comment by gabm** [comment]
Unfortunately this is still an issue.. any progress?
