### ISSUE TITLE
Overlinkage check should be recursive

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#3159]
The post-build overlinkage check false-reports missing dependencies.

The dependency tree of the involved libraries is: zyre (shared lib, current project) -> czmq (shared lib) -> zeromq (shared lib). That means that zyre has a run dependency to czmq which has a run dependency to zeromq.

### Actual Behavior

When building zyre, i get the following warning:

```
   INFO (zyre,lib/libzyre.so.2.0.1): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package defaults::gcc_impl_linux-64-7.2.0-habb00fd_3
WARNING (zyre,lib/libzyre.so.2.0.1): Needed DSO lib/libzmq.so.5 found in ['zeromq']
WARNING (zyre,lib/libzyre.so.2.0.1): .. but ['zeromq'] not in reqs/run, i.e. it is overlinked (likely) or a missing dependency (less likely)
   INFO (zyre,lib/libzyre.so.2.0.1): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package defaults::gcc_impl_linux-64-7.2.0-habb00fd_3
   INFO (zyre,lib/libzyre.so.2.0.1): Needed DSO lib/libczmq.so.4 found in https://xxx/conda/development::czmq-4.1.1p2-h75f9260_14
   INFO (zyre,bin/zpinger): lib/libzyre.so.2 found in this package
   INFO (zyre,bin/zpinger): Needed DSO lib/libczmq.so.4 found in https://xxx/conda/development::czmq-4.1.1p2-h75f9260_14
   INFO (zyre,bin/zpinger): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package defaults::gcc_impl_linux-64-7.2.0-habb00fd_3
Fixing permissions
```

### Expected Behavior

I would expect to get "all clear" and no warnings, since libzmq is an indirect run dependency. I _do not_ want to redeclare zeromq in zyre!

##### `Output of conda info`

```

```

**Comment by mingwandroid** [comment]
I believe zeromq is a direct dependent here despite what you claim because pyldd doesn't scan transitively nor should it.

Please run readelf -d to see this.

**Comment by mingwandroid** [comment]
WARNING (zyre,lib/libzyre.so.2.0.1): .. but ['zeromq'] not in reqs/run, i.e. it is overlinked (likely) or a missing dependency (less likely)

This indicates clearly what the problem is.

**Comment by mingwandroid** [comment]
I.e you expect it not to need to link to the c library but in fact it does therefore you need to mark it as as a dependency.

**Comment by gabm** [comment]
I see, you are right of course! zyre explicitly links to zeromq.. 

In case it wouldn't, then libzmq wouldn't be added to the elf object and libzmq would just be an _indirect_ dependency...

Thanks for pointing me to that!

**Comment by mingwandroid** [comment]
Now it could be the case that this lib needlessly links to zeromq however this unlikely since, if you use `AD` libtool or compilers we pass `--as-needed` to remove DSOs that are not needed and in general this will do the right thing so it's more likely that your lib is using zeromq directly.

**Comment by gabm** [comment]
yes, thats the first thing i checked and noticed that yes: https://github.com/zeromq/zyre/blob/b36470e70771a329583f9cf73598898b8ee05d14/CMakeLists.txt#L122
