### ISSUE TITLE
conda build reports different version numbers at the beginning and end of builds

### ISSUE THREAD

**Issue by meawoppl** [conda/conda-build#316]
```
PS C:\Users\dev-pc\3scan-shared> conda build .
BUILD START: 3scan-shared-0.2.0-py34_91
Fetching package metadata: ....

WARNING: conda-build appears to be out of date. You have version 1.9.1 but the
latest version is 1.10.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .
The following NEW packages will be INSTALLED:

    python:     3.4.2-1
    setuptools: 12.0.5-py34_0

Linking packages ...
[      COMPLETE      ] |#################################################| 100%
Removing old work directory
Copying C:\Users\dev-pc\3scan-shared to C:\Users\dev-pc\Anaconda3\conda-bld\work
Package: 3scan-shared-0.0.0-py34_0
source tree in: C:\Users\dev-pc\Anaconda3\conda-bld\work
found egg: C:\Users\dev-pc\Anaconda3\envs\_build\Lib\site-packages\setuptools-12.0.5-py3.4.egg
number of files: 2
BUILD END: 3scan-shared-0.0.0-py34_0
Nothing to test for: 3scan-shared-0.0.0-py34_0
# If you want to upload this package to binstar.org later, type:
#
# $ binstar upload C:\Users\dev-pc\Anaconda3\conda-bld\win-64\3scan-shared-0.0.0-py34_0.tar.bz2
#
# To have conda build upload to binstar automatically, use
# $ conda config --set binstar_upload yes
```

The first version number `3scan-shared-0.2.0-py34_91` reported seems to be held-over from development I was doing in a different repository.  The last one is the correct version (`3scan-shared-0.0.0-py34_0`). I am using the git-tags plus build number type recipe in the conda build explanation pages. 

I have the same problem after updating to the most recent conda-build.

**Comment by asmeurer** [comment]
If you are using the jinja2 templating, this is a known issue, which is due to the order that things are run in, it can't know the final version at the beginning of the build.

**Comment by meawoppl** [comment]
I don't think that I am. . .

**Comment by asmeurer** [comment]
I'm assuming the "git-tags plus build number" means you have something like `version: {{ environ['GIT_DESCRIBE_TAG'] }}`. This is what I am referring to (the `{{` bit is a jinja2 template).

**Comment by meawoppl** [comment]
I see, I do think if the version number can not be know it should not be
reported wrongly.

--Matthew Goodman

=====================
Check Out My Website: http://craneium.net
Find me on LinkedIn: http://tinyurl.com/d6wlch

**Comment by RutgerK** [comment]
I noticed this to, it takes the version number of the previous package which you have build, even if its a completely different package. It might be less confusing if its set to zero/empty/unknown etc.

**Comment by frol** [comment]
@asmeurer You say it is a known issue. What is the number of it? I have reported a related issue as #574

**Comment by asmeurer** [comment]
I guess this one. Also see https://github.com/conda/conda-build/issues/357 and https://github.com/conda/conda-build/pull/223.

**Comment by frol** [comment]
@asmeurer I see... So based on your reply on #223 it is broken and won't get fixed until jinja2 is replaced with more sane solution. Templating yaml configs is confusing indeed.
