### ISSUE TITLE
condo build failed because it could not write locks folder even with --no-locking set

### ISSUE THREAD

**Issue by chaoran** [conda/conda-build#3161]
### Actual Behavior

I 'm trying to use Bazel to build conda packages. Since Bazel executes the conda-build command in a sandbox, only the output directory is writable. This causes conda-build to fail with:

```
Could not write locks folder to either system location (/home/chaoran/miniconda3/locks)or user location (/home/chaoran/.conda_build_locks).  Aborting.
```

I try to disable locking by doing conda-build --no-locking. But the error persists.

conda-build --no-locking should prevent conda-build from writing locks.

### Steps to Reproduce

Maybe try to make both system location and user location for locks read-only and try to use conda-build --no-locking.

##### `Output of conda info`

```
     active environment : None
       user config file : /home/chaoran/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /home/chaoran/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/chaoran/miniconda3/pkgs
                          /home/chaoran/.conda/pkgs
       envs directories : /home/chaoran/miniconda3/envs
                          /home/chaoran/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.4.0-1062-aws ubuntu/16.04 glibc/2.23
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Sorry, we can't support this use case right now. If you'd like to submit a PR, we'd be happy to consider it.  As a workaround, you may be able to get bazel to create the locks folder for you and set permissions appropriately.

**Comment by chaoran** [comment]
Is --no-locking means something different? or is it not implemented?

**Comment by msarahan** [comment]
You are welcome to explore conda-build's source code to figure out why this is not working.  If you find a fix, a PR is welcome.
