### ISSUE TITLE
aligned_alloc previously defined here

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#3165]
Copied from PR ( https://github.com/conda-forge/gperftools-feedstock/pull/3 ).

>> @mingwandroid, any thoughts here?
>> 
>> ```
>> stdlib.h:513:21: note: 'void* aligned_alloc(size_t, size_t)' previously defined here
>>  static inline void* aligned_alloc (size_t al, size_t sz)
>>                      ^~~~~~~~~~~~~
>> ```
>> 
>> ref: https://circleci.com/gh/conda-forge/gperftools-feedstock/14
>
> If you can assign me a bug about this I'll less likely forget to look into it. Cheers.

**Comment by mingwandroid** [comment]
Not really the right place!

**Comment by mingwandroid** [comment]
It's a compiler/greed thing

**Comment by jschueller** [comment]
I'm getting a similar issue here at conda-forge/fmilib-feedstock#12:

```
[ 14%] Building C object CMakeFiles/jmutils.dir/src/Util/src/JM/jm_callbacks.c.o
In file included from /home/conda/feedstock_root/build_artifacts/fmilib_1543591870772/work/src/Util/src/JM/jm_callbacks.c:16:0:
/home/conda/feedstock_root/build_artifacts/fmilib_1543591870772/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/stdlib.h:513:15: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
 static inline void* aligned_alloc (size_t al, size_t sz)
```
xref log https://circleci.com/gh/conda-forge/fmilib-feedstock/40?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Any ideas ?

**Comment by nehaljwani** [comment]
xref: https://github.com/01org/tbb/blob/tbb_2019/src/tbbmalloc/proxy.cpp#L26-L40

**Comment by jschueller** [comment]
@nehaljwani this trick does not seem to work for a C library where it directly includes stdlib.h: https://circleci.com/gh/conda-forge/fmilib-feedstock/46

**Comment by jschueller** [comment]
Maybe it's best to patch the header, but I cant figure out which package brings the compiler files in the log, does the compiler file come with docker image or something ?

**Comment by jschueller** [comment]
I found out undefining _GNU_SOURCE did the trick

**Comment by jakirkham** [comment]
Ran into this with `serf` recently. ( https://github.com/conda-forge/staged-recipes/pull/2825 ) What is our current recommendation for working around this?

**Comment by jschueller** [comment]
remove the _GNU_SOURCE define ?

**Comment by jakirkham** [comment]
Could you please share a bit more context? Where is this being set? The compilers? I'm not seeing it in the source code. 😕

**Comment by jschueller** [comment]
I'm just seeing it in your logs, I guess this is added by your package.

**Comment by asl** [comment]
The reason is conda own's broken patch to glibc. See more information in https://github.com/bioconda/bioconda-recipes/pull/26349#issuecomment-773510782
