### ISSUE TITLE
Using mro-base rather than r-base does not build version-specific packages

### ISSUE THREAD

**Issue by kesmit13** [conda/conda-build#3177]
### Actual Behavior

I'm trying to build a package that works for r-base as well as mro-base.  When I use r-base=3.5.1 in the meta.yaml as a build/run dependency, I get a filename in the form pkg-1.0.0-r351_0.tar.bz.  However, if I use mro-base instead, I just get pkg-1.0.0_0.tar.bz.

### Expected Behavior

I would expect that the mro-base file would be named pkg-1.0.0-mro351_0.tar.bz so that I can build it for multiple versions of mro-base.

### Steps to Reproduce

Build a package with the following dependencies.  I noted this on win64, but the problem may exist on other platforms as well.

```
requirements:
    build:
        - r-base=3.5.1
    run:
        - r-base=3.5.1
```

Then build one with:

```
requirements:
    build:
        - mro-base=3.5.1
    run:
        - mro-base=3.5.1
```

#### Output of conda info

```
     active environment : base
    active env location : C:\Anaconda3
            shell level : 1
       user config file : C:\Users\kesmit\.condarc
 populated config files : C:\Users\kesmit\.condarc
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\kesmit\AppData\Local\conda\conda\pkgs
       envs directories : C:\conda\envs
                          C:\Anaconda3\envs
                          C:\Users\kesmit\AppData\Local\conda\conda\envs
                          C:\Users\kesmit\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Better to omit the version in meta.yaml, and set it via CLI:

```
  --R R_BASE            Set the R version used by conda build.
```

or via a conda_build_config.yaml file.  For special things like python and R, hardcoding the version in meta.yaml messes things up.

**Comment by kesmit13** [comment]
I thought I tried that, but I'll give it another shot.  

BTW, there wouldn't happen to be a way to specify either the standard R or MRO on the command-line?  I have to modify my recipe each time I switch, but using a command-line option would be much better.

**Comment by mingwandroid** [comment]
> BTW, there wouldn't happen to be a way to specify either the standard R or MRO on the command-line? I have to modify my recipe each time I switch, but using a command-line option would be much better.

Your use-case is, I believe, far from typical.

**Comment by msarahan** [comment]
also, update conda-build.  3.4.1 is very old.

For switching, I recommend using a conda_build_config.yaml file.  This PR is required before it can be realistically done on the CLI: https://github.com/conda/conda-build/pull/3168

**Comment by kesmit13** [comment]
@msarahan I think that was my problem.  I didn't realize that conda build was updated separately from conda.  It seems to be working now.  I'll run the rest of my packages and if they all work, I'll close out this issue.

**Comment by kesmit13** [comment]
It looks like it doesn't always work correctly with the command-line option.  If you specify --R 3.4.3 and use mro-base, you get an MRO 3.5.1 package instead.  If you specify the version in the meta.yaml, it works correctly.  I haven't gone through all of the permutations yet.

**Comment by kesmit13** [comment]
It appears as though the only way that works everywhere is to specify the version both on the command-line and in the meta.yaml file.
