### ISSUE TITLE
conda-build fails when -c anaconda-organization-name is used

### ISSUE THREAD

**Issue by stas00** [conda/conda-build#3178]
### Actual Behavior

I need to tell `conda-build`to work with two custom channels to get the correct versions of the required packages. `-c fastai` is an organization on anaconda but it blows up:

    conda-build ./conda/ -c pytorch -c fastai

```
-- Building version 1.0.2
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda/core/subdir_data.py", line 440, in fetch_repodata_remote_request
    resp.raise_for_status()
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: None for url: file:///fastai/master/fastai/noarch/repodata.json

```

There is a folder `fastai` in the project's top-level directory, which it seems to try to use an index url. I have no idea why it searches locally. It should be searching https://anaconda.org/fastai/ instead.

This workaround fixes this bug:

    conda-build ./conda/  -c pytorch -c fastai/label/main

### Expected Behavior

    conda-build ./conda/  -c pytorch -c fastai

should work.

### Steps to Reproduce

    git clone https://github.com/fastai/fastai
    cd fastai
    conda-build ./conda/ -c pytorch -c fastai

##### `Output of conda info`

```

     active environment : pytorch-dev
    active env location : /home/stas/anaconda3/envs/pytorch-dev
            shell level : 1
       user config file : /home/stas/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /home/stas/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/stas/anaconda3/pkgs
                          /home/stas/.conda/pkgs
       envs directories : /home/stas/anaconda3/envs
                          /home/stas/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.3 Linux/4.15.0-34-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

BTW, this output is a bit faulty, as there is no `/home/stas/.condarc`

Thank you.

**Comment by stas00** [comment]
Thank you, Mike

First, how can a user figure that out from this documentation from `conda-build`:
  
```
-c CHANNEL, --channel CHANNEL
                        Additional channel to search for packages. These are
                        URLs searched in the order they are given (including
                        file:// for local directories). Then, the defaults or
                        channels from .condarc are searched (unless
                        --override-channels is given). You can use 'defaults'
                        to get the default packages for conda, and 'system' to
                        get the system packages, which also takes .condarc
                        into account. You can also use any name and the
                        .condarc channel_alias value will be prepended. The
                        default channel_alias is http://conda.anaconda.org/.
```

Shouldn't you be using `file://` as it suggests for local dirs? That documentation doesn't match what you said.

Second, I am making two builds - one for pypi, another for conda, so they are in the same location. but the recipe is in its own dir "conda", so I have just tried:

    cd conda; conda-build . -c pytorch -c fastai

but it then fails, as now relative paths somehow seem to be messed up.

```

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
import: 'fastai'
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1538444775564/test_tmp/run_test.py", line 2, in <module>
    import fastai
  File "/home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1538444775564/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.7/site-packages/fastai/__init__.py", line 6, in <module>
    from .gen_doc.nbdoc import nbshow
  File "/home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1538444775564/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.7/site-packages/fastai/gen_doc/__init__.py", line 1, in <module>
    from . import gen_notebooks, nbdoc, core, convert2html
  File "/home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1538444775564/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.7/site-packages/fastai/gen_doc/convert2html.py", line 1, in <module>
    import os.path, re, nbformat, jupyter_contrib_nbextensions
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
Tests failed for fastai-1.0.2-py_1.tar.bz2 - moving package to /home/stas/anaconda3/envs/pytorch-dev/conda-bld/broken
WARNING:conda_build.build:Tests failed for fastai-1.0.2-py_1.tar.bz2 - moving package to /home/stas/anaconda3/envs/pytorch-dev/conda-bld/broken
TESTS FAILED: fastai-1.0.2-py_1.tar.bz2
```
whereas the source comes from:

```
source:
  # Source from a local path
  path: ..
```
So your suggestion unfortunately doesn't work. Any other ideas to try?

**Comment by msarahan** [comment]
I'm afraid if you need perfect documentation at all times, you'll be left wanting.  We are behind on that, and most of the users that I have helped have not contributed their gained understanding back to the docs. (Hint)

Your cd into the conda folder accomplishes what I suggested - not having the fastai folder in a place that gets interpreted as a channel.

Yes, we could construct file:// URLs.  We do not do that because we generate commands to run on our CI servers in a way where we don't know what the full file URL will be when it runs.  We depend on the current (undocumented) behavior where channels matching folder names are treated as local URLs so that we don't have to try to hard-code locations, but instead leave it up to the CI system's folder naming

**Comment by stas00** [comment]
@msarahan, I'd be happy to write a doc patch, now that you have provided a detailed explanation.

I have a feeling `-c CHANNEL, --channel` help entry is already too busy and this extra explanation will take a lot more words. Do you think it'd be sensible to make it shorter and instead add 'See "On Channels" entry below', where such expanded details can be provided?

**Comment by msarahan** [comment]
Thanks!  I agree that this entry is too busy already.  It may make more sense to put it below, or just in the online docs and put a link to it in the help output.

**Comment by stas00** [comment]
I'm having a hard time finding where that. It'd help me a lot if you could tell me which online document to edit and where do I find its source to edit. Thank you.

**Comment by msarahan** [comment]
Docs are at https://github.com/conda/conda-build/tree/master/docs/source, but I don't really see a file for this currently. Feel free to make one for this and perhaps any other cli flags that need more space than just the help blurb.

**Comment by stas00** [comment]
https://github.com/conda/conda-build/pull/3197
