### ISSUE TITLE
Conda-build should allow inclusion of a readme in the metadata

### ISSUE THREAD

**Issue by srossross** [conda/conda-build#318]
Binstar.org supports uploading a README, however conda does not allow for including a README. 
Can we add a `readme` tag in the `meta.yaml` to include a `README.*` in the info?

**Comment by asmeurer** [comment]
The README on Binstar is package level, not file level, as far as I can tell. How will it handle the readmes coming from multiple files of the same package?

**Comment by srossross** [comment]
binstar.org shows the README from the latest version. The command line client only uploads a README **once** for each version.

**Comment by asmeurer** [comment]
Does the command line client already expect it to be `info/README.*` in the package?

**Comment by srossross** [comment]
I will need to modify the client to look for it after conda includes it. So you can include it anywhere you like.

**Comment by asmeurer** [comment]
OK. I'll think I'll do what I described. I don't want to put it in the json as that could get too big for the repodata.

**Comment by asmeurer** [comment]
Another question, does Binstar actually support multiple markup formats?

**Comment by srossross** [comment]
It supports rst and markdown
