### ISSUE TITLE
dist-info check fails if package name is not the same as module name

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#3195]
The dist-info check in `post.py` uses the package name to partition the version string.  This results in an incorrect version being parsed if the package name is not the same as the name of the python module which in turn fails the build unnecessarily.  

The `dask-core` recipe from conda-forge exhibits this behavior.

**Comment by jjhelmus** [comment]
Note that this check is included in conda-build 3.16.0 but not earlier versions.  The check was added in #3163.

**Comment by jjhelmus** [comment]
This check will also fail when it finds vendored packages.  There will likely be other edges cases where this check gives false positives.  Perhaps moving this check to `conda-verify` where is can be ignored on a case by case basis would be more appropriate.

**Comment by mingwandroid** [comment]
This bug cost me ages to figure out. Is rather fatal packaging bugs are caught here personally and think we should just improve this add we run into issues. The Python 3.7 build out used my original code so the edges are few I think

**Comment by jjhelmus** [comment]
How about an option in the recipe to skip the check for some files or entirely?  That gives these edge cases an escape hatch.

**Comment by mingwandroid** [comment]
Sure, but I'm cooler with iterating on this code until it's solid, there's no reason it can't be that I know of?

**Comment by jjhelmus** [comment]
bleach 3.0.0 is a good example of a package with a [vendored .dist-info directory](https://github.com/mozilla/bleach/tree/v3.0.0/bleach/_vendor)

**Comment by pauldmccarthy** [comment]
I know nothing about the conda build internals, but [I'm being affected by this bug too](https://circleci.com/gh/conda-forge/fsleyes-widgets-feedstock/17?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). 

Could the code be re-worked to accept any [valid python project name](https://packaging.python.org/guides/distributing-packages-using-setuptools/#name)?

**Comment by msarahan** [comment]
fixed by https://github.com/conda/conda-build/pull/3206/commits/7d682bd3ceaa99184197c953e0000a62d9330297

**Comment by jakirkham** [comment]
FWIW this also affects any project that uses a `-` in the name as these are turned into `_`.

**Comment by mingwandroid** [comment]
Do you have an example of a package that does this?

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/dask-image-feedstock/pull/3

**Comment by pauldmccarthy** [comment]
And, as previously linked: [conda-forge/fsleyes-widgets-feedstock#5](https://github.com/conda-forge/fsleyes-widgets-feedstock/pull/5)

**Comment by msarahan** [comment]
Confirmed that dask-image and fsleyes-widgets both build fine after https://github.com/conda/conda-build/commit/7d682bd3ceaa99184197c953e0000a62d9330297

The horse is dead.  Please beat it no further.

**Comment by msarahan** [comment]
Tagged.  Builds going up momentarily.

**Comment by jakirkham** [comment]
Great, thanks Mike! 😄
