### ISSUE TITLE
Unsatisfiable dependency exception for Python 2.7 on Windows

### ISSUE THREAD

**Issue by vinayak-mehta** [conda/conda-build#3201]
### Actual Behavior

Building this [recipe](https://github.com/camelot-dev/staged-recipes/blob/add-camelot/recipes/camelot-py/meta.yaml) raises an exception with the following message: `Unsatisfiable dependencies for platform win-64: {'camelot-py==0.2.3=py27_0'}`. The package I'm trying to build is camelot-py, how can camelot-py be a dependency of itself? I tried installing each of the requirements to check if they were available for Python 2.7 on win-64 and they were. You can check the conda-forge [Appveyor build](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/19345955) for more details.
### Expected Behavior

The package should build successfully.
### Steps to Reproduce

Creating a directory named `camelot-py` with the [recipe](https://github.com/camelot-dev/staged-recipes/blob/add-camelot/recipes/camelot-py/meta.yaml) and run `conda build --python 2.7 camelot-py`.

##### `Output of conda info`

```
     active environment : python2.7
    active env location : C:\Users\vinayak\Anaconda3\envs\python2.7
            shell level : 2
       user config file : C:\Users\vinayak\.condarc
 populated config files : C:\Users\vinayak\.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\Users\vinayak\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\vinayak\Anaconda3\pkgs
                          C:\Users\vinayak\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\vinayak\Anaconda3\envs
                          C:\Users\vinayak\AppData\Local\conda\conda\envs
                          C:\Users\vinayak\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by vinayak-mehta** [comment]
The package builds successfully for Python 3.5 and 3.6 on Windows.

**Comment by msarahan** [comment]
You are missing dependencies.  This is not a conda-build bug.  If you need help figuring that out, please ask on the conda-forge gitter channel.

**Comment by jjhelmus** [comment]
Most likely one of the `run` requirements is missing for the specific platform and python version.  Most likely opencv is the issue as there are no Python 2.7 builds greater than 3.2.0 for windows.

**Comment by vinayak-mehta** [comment]
Thanks for pointing it out @jjhelmus! This was happening because of the opencv and numpy versions, I downgraded them and the build was successful.

The error message was confusing though (printing the name of the package that's being built), should it be improved to give out the exact requirements that aren't being satisfied?

Sorry for filing a trivial issue, should've checked the versions. Maybe this will help someone else!
