### ISSUE TITLE
allow overriding the .so check for noarch: python?

### ISSUE THREAD

**Issue by dougalsutherland** [conda/conda-build#3208]
`compas` is a pure-python package that could be made `noarch: python` except that it [ships some `.so` and `.dll` files](https://github.com/compas-dev/compas/tree/master/src/compas/numerical/fd/__fd_cpp) (that it doesn't compile, so they're the same across platforms). That's triggering [this check](https://github.com/conda/conda-build/blob/19f5d7847ee8a4c5b979680595103fa6cc21e4b1/conda_build/noarch_python.py#L60-L66) and killing the build ([PR](https://github.com/conda-forge/compas-feedstock/pull/6#issuecomment-429024394), [failed build](https://circleci.com/gh/conda-forge/compas-feedstock/37?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).

The check definitely makes sense in general. But maybe there should be a way to override it for cases like this?

**Comment by msarahan** [comment]
Sure, seems fine to me.  Please consider submitting a PR.

**Comment by mandeep** [comment]
How should this be handled? Remove this check and let --verify handle it, or should we just provide a flag to override it?

**Comment by msarahan** [comment]
the right way in my mind is to remove the check in conda-build, and leave it in conda-verify.  Then let people see the warning, or use the ``--strict-verify`` for conda-build to error out when conda-verify has any unhappy result.

**Comment by mandeep** [comment]
Sounds good, I'll submit a PR to remove the check.
