### ISSUE TITLE
Get a more useful error message when there's a space between greater than and version

### ISSUE THREAD

**Issue by chdoig** [conda/conda-build#321]
If I have something like this in my meta.yaml file:

```
run:
    - r >= 2.4.0
```

The error that I get is:

```
Error: No packages found in current osx-64 channels matching: r >= 2.4.0
```

But I really just needed to remove the space between the equal and the 2. It would be useful to get an error message that provides that hint, otherwise you might believe that there is no package.

**Comment by asmeurer** [comment]
Or just make it work, since no package will ever have inequality signs in the version.
