### ISSUE TITLE
`--no-remove-work-dir` is not respected + /tmp/ folder is not cleaned up

### ISSUE THREAD

**Issue by stas00** [conda/conda-build#3215]
### Actual Behavior

`conda-build`:

1) removes work dir when told not to.
2) leaves other build artifacts in `/tmp`

### Expected Behavior

`--no-remove-work-dir` should leave the build folder intact, yet it deletes it.

`Renaming work directory,  /home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1539402685728/work  to  /home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1539402685728/work_moved_fastai-1.0.6.dev0-py_1_linux-64_main_build_loop
`
and upon job completion it's gone. Its there if I abort the run before it completes.

instead it leaves a directory with the files from the unpacked package  in `/tmp/` for each build, which is probably an unrelated issue, but general tidyness related.

### Steps to Reproduce

`conda-build ./conda/ -c pytorch -c fastai/label/main --output-folder conda-dist --no-remove-work-dir`

##### `Output of conda info`

```

     active environment : pytorch-dev
    active env location : /home/stas/anaconda3/envs/pytorch-dev
            shell level : 1
       user config file : /home/stas/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /home/stas/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/stas/anaconda3/pkgs
                          /home/stas/.conda/pkgs
       envs directories : /home/stas/anaconda3/envs
                          /home/stas/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.3 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by stas00** [comment]
It turns out that your `conda info` is broken. So if I run the version separately, it's `3.15.1`

See for yourself:
```
$ conda-build --version
conda-build 3.15.1

$ conda info

     active environment : pytorch-dev
    active env location : /home/stas/anaconda3/envs/pytorch-dev
            shell level : 1
       user config file : /home/stas/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /home/stas/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/stas/anaconda3/pkgs
                          /home/stas/.conda/pkgs
       envs directories : /home/stas/anaconda3/envs
                          /home/stas/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.3 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
That's fun and interesting...

**Comment by stas00** [comment]
I don't even have python version : 3.6.3.final.0 installed anywhere on the system. 

I checked it's being executed with `/home/stas/anaconda3/envs/pytorch-dev/bin/python` (shebang line of conda)

$ /home/stas/anaconda3/envs/pytorch-dev/bin/python --version

`Python 3.6.6 :: Anaconda custom (64-bit)`
Python 3.6.6 :: Anaconda custom (64-bit)

**Comment by msarahan** [comment]
There's 3 things here:

1. ``--no-remove-work-dir`` keeps the workdir in place between the build and test phase **for a single output**.  It is performing normally:

```
TEST START: /tmp/cb/noarch/click-7.0-py_0.tar.bz2
Adding in variants from /var/folders/94/cb44zrcj06n_vj5zgxvjpb0h0000gp/T/tmp_1uh66qc/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /var/folders/94/cb44zrcj06n_vj5zgxvjpb0h0000gp/T/tmp_1uh66qc/info/recipe/conda_build_config.yaml
Not moving work directory after build.  Your package may depend on files in the work directory that are not included with your package
WARNING:conda_build.build:Not moving work directory after build.  Your package may depend on files in the work directory that are not included with your package
Solving environment: ...working... done
```

Conda-build still moves the workdir between outputs, because outputs should be independent of one another.  Their build orders are not currently defined, so you should not depend on state from one output to another.

2. The movement you see at the end of a test phase is the move after the output is considered done.  It is superfluous and could be cleaned up so that it only happens between outputs, and not at the end of the final output being processed.
3. ``--no-remove-work-dir`` does not affect the final cleanup of a build folder.  You want ``--dirty`` or ``--keep-old-work``.

The tmp dir stuff is a separate issue.  I'll see about filing another issue for it.

**Comment by stas00** [comment]
Thank you for explaining that, @msarahan. 

I guess it'd have been better called `--no-remove-work-dir-for-test`. I confess I didn't try to look for other options, since I thought that I'd DWIM due to its name and didn't think it wasn't the right option. Now that you mentioned the other options, and reading the descriptions it's pretty clear to use `--dirty` or `--keep-old-work`.

Thanks again.

**Comment by stas00** [comment]
Hmm, I assumed it should work since you said it should, now I had a chance to test it and it doesn't work, using `--keep-old-work`

`conda-build ./conda/ -c pytorch -c fastai/label/main --output-folder conda-dist --keep-old-work`

it doesn't say that it saved the build and there is no build to be found under `/home/stas/anaconda3/envs/pytorch-dev/conda-bld/` where usually things end up if I kill the process to preserve the build dir as a workaround for now.

and it doesn't work with `--dirty` either:

```
$ conda-build ./conda/ -c pytorch -c fastai/label/main --output-folder conda-dist --dirty
[...]
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
source tree in: /home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1539747059947/work
python: can't open file 'setup.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/pytorch-dev/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 438, in main
    execute(sys.argv[1:])
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 429, in execute
    verify=args.verify)
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda_build/build.py", line 2204, in build_tree
    notest=notest,
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda_build/build.py", line 1445, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda_build/utils.py", line 313, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/conda_build/utils.py", line 293, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/stas/anaconda3/envs/pytorch-dev/conda-bld/fastai_1539747059947/work/conda_build.sh']' returned non-zero exit status 2.
```
it builds just fine without `--dirty`

**Comment by stas00** [comment]
Alas, `--dirty` doesn't seem to fit what I need, or perhaps it's broken.

After using it for a while I discovered that it doesn't create a new unique directory for each new build. So I have been testing the wrong things for quite some time :( 

I suppose that could be by design and not a bug, but it is probably a bug since it doesn't update that directory. If I add or remove a file from the source directory it ignores this change, and doesn't adjust that dirty folder, but again perhaps this is by design.

**Comment by bluehood** [comment]
Hi,
I'm also affected. I need to inspect the build directory, but after a `conda build --keep-old-work` it is nowhere to be found (no build dir nor sources, actually).

**Comment by socec** [comment]
I'm also affected.

I believe it is due to [this line](https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1033) which is executed regardless of `--no-remove-work-dir` or `--keep-old-work`.
It was introduced to resolve [this issue](https://github.com/conda/conda-build/issues/2577).

It would be nice to only clean the produced files, like before, and keep the build directory if `--no-remove-work-dir` or `--keep-old-work` flags are set.

**Comment by cpaulik** [comment]
Same here. It would be great if `--keep-old-work` would work since I need to check which files are produced to include them in my `output` section.
