### ISSUE TITLE
libarchive failing on windows builds

### ISSUE THREAD

**Issue by cpcloud** [conda/conda-build#3226]
### Actual Behavior

`libarchive` is failing to be found during a call to `conda build`.

https://dev.azure.com/ibis-project/ibis/_build/results?buildId=207&view=logs

### Expected Behavior

I expect the call to `conda build` to not fail.

### Steps to Reproduce

https://github.com/ibis-project/ibis/blob/master/azure-pipelines.yml

**Comment by mingwandroid** [comment]
This is a conda-forge issue.

**Comment by mingwandroid** [comment]
I have no idea what this is:

> python-libarchive-c-2.8

You are also mixing:

> libarchive-3.3.2           |       h1d0d21d_1         4.0 

i.e. libarchive from defaults with py-libarchive-c from conda-forge. I suggest you drop one of either `defaults` or `conda-forge` from your channel list to prevent this mixing and to rule out binary incompatiblity between the channels. The push to improve these matters is well underway and there'll be a few pain points during the transition.

If you could report back on the results from each channel independently we'd appreciate it.

**Comment by cpcloud** [comment]
To be clear, this has been working for quite awhile so I'm guessing this is due to the transition? What exactly is in transition?

**Comment by cpcloud** [comment]
@mingwandroid Thanks for the explanation, that's very helpful.
