### ISSUE TITLE
add ability to suppress fields in about.json

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#3231]
Feature request:

I would like the ability to suppress certain fields from being included in the package's "about.json" metadata file. Now, the only recourse to remove internal information is post-build patching of the about.json file.

From MichaelS:
Here is where that info goes in: https://github.com/conda/conda-build/blob/master/conda_build/build.py#L562-L564

Adding a small bit to delete any keys that you don't want in there should be pretty easy.

for k in cc_conda_build.get("about_suppress_fields", []):
    if k in d:
        del d[k]

**Comment by hrzafer** [comment]
I agree. `about.json` exposes to much information about the environment by default. I was looking for a way of avoiding this or not generating an `about.json` file at all. 

The [official document](https://docs.conda.io/projects/conda-build/en/latest/source/resources/package-spec.html?highlight=about.json#info-about-json) says it is an optional file.

**Comment by msarahan** [comment]
A PR would be welcome.
