### ISSUE TITLE
Tests don't run if they are added to the recipe file

### ISSUE THREAD

**Issue by orbingol** [conda/conda-build#3242]
Hello,

This is my first post here :) I have been using conda-build for a short time, therefore there is a strong possibility that I might be doing the things in the wrong way. Let me start with an introduction. I created a recipe for generating a conda package from a Python module. I would like to run tests during the conda-build process and I added the tests in the recipe file (meta.yaml) like this:

```
test:
  imports:
    - geomdl
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - python -c "import geomdl; print(geomdl.__version__)"
    - pytest
```

You can find the full recipe [here](https://github.com/orbingol/NURBS-Python/blob/devmaster/conda-recipes/geomdl/meta.yaml). Please note that this is a "noarch" recipe.

### Actual Behavior

conda-build generates a `conda_test_runner.bat` file which only calls `run_test.py`. Therefore the command prompt does not display the result of the test commands.

### Expected Behavior

conda-build should generate a `conda_test_runner.bat` file which calls `run_test.py` and `run_test.bat`, and therefore it should run the test commands.

### Steps to Reproduce

I would like to explain the steps to reproduce using the conda-build recipe I created. I think it can be reproduced with any recipe which contains the "test\commands" section.

* git clone https://github.com/orbingol/NURBS-Python.git geomdl-test
* cd geomdl-test
* git checkout devmaster
* cd conda-recipes
* conda build geomdl

##### `Output of conda info`

```
     active environment : base
    active env location : C:\Miniconda3
            shell level : 1
       user config file : C:\Users\orbingol\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.16.2
         python version : 3.6.7.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\orbingol\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\orbingol\AppData\Local\conda\conda\envs
                          C:\Users\orbingol\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.7 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

```

### Possible solution

I am not sure if the following changes are correct but they worked for me.

1. Comment out lines 62 and 63 in _create_test.py_
2. Change line 2112 of _build.py_ to `if os.path.splitext(shell_file)[1] == ".bat":`

`os.path.splitext(shell_file)` seems to return a tuple.

**Comment by nehaljwani** [comment]
This is a side effect of https://github.com/conda/conda-build/pull/3236

A very small reproducer is:
```
(base) C:\Users\Wani\Downloads\scratch>type meta.yaml
package:
   name: yes_sir
   version: 0.0.1

test:
   commands:
     - echo "Hello"
```

For the time being, downgrade conda-build to 3.16.1

**Comment by orbingol** [comment]
It seems that it was fixed with the latest release.
