### ISSUE TITLE
I'm not able to build packages with an earler verison of R

### ISSUE THREAD

**Issue by cramjaco** [conda/conda-build#3245]
For at least the two packages I have tried this with, I am not able to build an R package with R version 3.4.1, rather I can only build with the newest version of R.

### Steps to Reproduce

Download an environment and pull down a pakage skeleton:

```
conda create -n test04 conda-build
source activate test04
conda skeleton cran r-bayesm
```

Build with R version 3.5.1 (works)
`conda build --R 3.5.1 r-bayesm > bayesm.351.out.txt 2> bayesm.351.err.txt`

Build with R version 3.4.1 (does not work)
`conda build --R 3.4.1 r-bayesm > bayesm.341.out.txt 2> bayesm.341.err.txt`

### Expected Behavior

Given the steps above, the package bayesm does build if I try to use R version 3.5.1, which, at the time of this writing, is the newest version of R.

[bayesm.351.out.txt](https://github.com/cramjaco/issues/blob/master/bayesm.351.out.txt)
[bayesm.351.err.txt](https://github.com/cramjaco/issues/blob/master/bayesm.351.err.txt)

This is expected behavior. I would expect that I would get the same kinds of behavior if I build with R version 3.4.1.

### Actual Behavior
Instead, when I try to build with R 3.4.1, as in the earlier "steps to reproduce" section, the installation fails with a non zero exit status, which can be seen in the following error file.

[bayesm.341.out.txt](https://github.com/cramjaco/issues/blob/master/bayesm.341.out.txt)
[bayesm.341.err.txt](https://github.com/cramjaco/issues/blob/master/bayesm.341.err.txt)

I presume I am missing some step, like pulling down an earlier version of the cran skeleton file or similar. If so, could you please direct me to an appropriate protocol? That said, the [page for the current verison of the package](https://cran.r-project.org/web/packages/bayesm/index.html) suggests that version 3.2.0 or higher should work. 

Alternatively, maybe this is supposed to work as I am executing it, in which case, please do let me know how to proceed.
Also, I have reproduced this problem with the cran package "broom" and I get similar behavior.

Thanks for your consideration.

##### `Output of conda info`

```
active environment : test0
    active env location : /home/ohnoplus/miniconda3/envs/test0
            shell level : 1
       user config file : /home/ohnoplus/.condarc
 populated config files : /home/ohnoplus/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /home/ohnoplus/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/cramjaco/linux-64
                          https://conda.anaconda.org/cramjaco/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/ohnoplus/miniconda3/pkgs
                          /home/ohnoplus/.conda/pkgs
       envs directories : /home/ohnoplus/miniconda3/envs
                          /home/ohnoplus/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.18.0-10-generic ubuntu/18.10 glibc/2.28
                UID:GID : 1000:1001
             netrc file : None
           offline mode : False

```

**Comment by mingwandroid** [comment]
Any reason to use such an old R? 3.5.1 is vastly improved.

**Comment by cramjaco** [comment]
Yes, several reasons. In my case compatability with both a legacy set up (I ran everthing in an earlier version of R and don't want to change horses mid analysis) and with other packages (dada2 and jupyter notebook only play nicely together in 3.4.1) -- see for instance  [this discussion](https://stackoverflow.com/questions/45556517/installing-dada2-into-a-version-of-r-that-was-installed-through-condas/53029393?noredirect=1#comment93043141_53029393).
