### ISSUE TITLE
build_id does take into account manual build strings for subpackages

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda-build#3248]
Namely, it does not seem to detect that a build string is set manually for a subpackage.

https://github.com/conda/conda-build/blob/a6e3a33c6588f89db4d81ec25cb637fcf54d1f78/conda_build/metadata.py#L1261

**Comment by SylvainCorlay** [comment]
This seems to be the cause of the clangdev 5.x rebuild issue here: https://github.com/conda-forge/clangdev-feedstock/issues/41

**Comment by msarahan** [comment]
yes, it is a bug.  I haven't figured out why it works for openblas and mkl, but not for you (similar concept, so it must be something strange.). I can reproduce it, but conda-build is being very finicky and often refusing to even render the recipe, saying that clangdev depends on itself somehow.  Sorry, this one may take a while to get to fixing.  If you figure it out, a PR would be very welcome.

**Comment by SylvainCorlay** [comment]
Pasting @isuruf 's patch from conda-forge gitter, which appears to fix the issue locally.

```
--- conda_build/metadata.py
+++ conda_build/metadata.py
@@ -1645,9 +1645,10 @@
         #    We have to do this on rendered data, because templates can be used in output names
         recipe_text = self.extract_outputs_text(apply_selectors=apply_selectors)
         output_matches = output_re.findall(recipe_text)
+        parent_recipe = self.meta.get('extra', {}).get('parent_recipe', {})
         try:
             output_index = [out.get('name') for out in
-                            self.meta.get('outputs', [])].index(output_name)
+                            parent_recipe.get('outputs', [])].index(output_name)
             output = output_matches[output_index] if output_matches else ''
         except ValueError:
             output = ''
```

**Comment by SylvainCorlay** [comment]
Thanks @msarahan for reproducing locally.

**Comment by SylvainCorlay** [comment]
@msarahan does @isuruf's patch look good to you?
