### ISSUE TITLE
Best practices for header-only C++ packages and pure C packages installed with cmake

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda-build#3252]
`cmake` assumes that the project is a C++ by default, and even pure C packages will have a compile-time dependency on `compiler('cxx')` because cmake will try to locate a C++ compiler. (In the `CMakeLists.txt` file, specifying the C language with `project(ProjectName C)` prevents this issue.) 

Minrk proposed to add a `ignore_run_exports` statement in the recipes of C packages built with cmake:

```
build:
  ignore_run_exports:
    - {{ compiler('cxx') }}
```

I was thinking that we may also want to do this for actual C++ packages, that happen to be **header-only**. I maintain recipes for a number of these packages. How about adding an `ignore_run_exports` section to all header-only packages?

**Comment by SylvainCorlay** [comment]
Posted this here so that there is a trace - may be included in documentation of best practices...

**Comment by SylvainCorlay** [comment]
Edit: it does not seem that 

```
build:
  ignore_run_exports:
    - {{ compiler('cxx') }}
```

works at all.

cf. https://github.com/conda-forge/metis-feedstock/issues/21

**Comment by jakirkham** [comment]
Some feedback on this would be much appreciated.

**Comment by mingwandroid** [comment]
The macOS compiler does not impose run_exports of itself, it imposes libcxx and libcxxabi deps.

```
 build:
    ignore_run_exports:
      - libcxx
      - libcxxabi
```

We could discuss formalizing some limited logic to run_exports if people think it important enough?

**Comment by SylvainCorlay** [comment]
It is surprising that even on linux, we get `libstdcxx-ng` as a runtime dependency despite of the `ignore_run_exports` statement.

**Comment by mingwandroid** [comment]
Why? https://github.com/AnacondaRecipes/aggregate/blob/master/ctng-compilers-activation-feedstock/recipe/meta.yaml#L39-L62

**Comment by mingwandroid** [comment]
It is the run export itself that you need to ignore, not the package that declares them. A package can impose run_exports on many and aribitrary packages.

**Comment by mingwandroid** [comment]
```
 build:
    ignore_run_exports:
      - libcxx  # [osx]
      - libcxxabi  # [osx]
      - libstdcxx-ng  # [linux]
```

**Comment by SylvainCorlay** [comment]
Ok yeah, this was a silly question :) I missed this.

**Comment by mingwandroid** [comment]
Sure, very rare though as run_exports are not applied transitively (for metapackages we acually need a new metadata flag to enable this too `inherit_child_run_exports`).
