### ISSUE TITLE
conda-build 3.17 failing to build go-based packages

### ISSUE THREAD

**Issue by sodre** [conda/conda-build#3292]
This issue is to pickup the parts of #3287 that did not get addressed, see:
  - `vault` issue: https://github.com/conda/conda-build/issues/3287#issuecomment-443922743
  - `ptvsd` issue: https://github.com/conda/conda-build/issues/3287#issuecomment-443953991
  - `go-bootstrap` issue: https://github.com/conda/conda-build/issues/3287#issuecomment-443965104
  - `git-lfs` issue: https://github.com/conda-forge/git-lfs-feedstock/pull/16

### Actual Behavior
Conda-build 3.17 fails to build packages that do not have dynamic linked libraries, e.g. `go`, `vault`, etc. 

### Expected Behavior
This behavior does not happen on conda-build 3.16 as can be seen when one pins conda-build to 3.16 within the conda-forge ci-scripts, see:
  - `git-lfs`: 
https://github.com/conda-forge/git-lfs-feedstock/pull/16/commits/2b5cb52fed265f4f37462e59a08b2ee89c384867
  - `vault`: 
https://github.com/conda-forge/vault-feedstock/pull/24/commits/6c4a10de48bbcf997edf401772df2946b19ae592
  - `go`: 
https://github.com/conda-forge/go-feedstock/pull/34/commits/9499072cbb18b24e5adc331b9cdcccbb1b5e6e63

### Steps to Reproduce
Build the packages above using conda-build 3.17. 

cc: @isuruf, @jakirkham

**Comment by jjhelmus** [comment]
Thanks for keeping this issue alive.  #3287 was originally about LIEF errors on Windows which #3288 addressed but the issues reported with other platforms also need to be fixed.

Is this specific to packages which use go or are packages containing C and C++ code also effected?   The `ptvsd` package does not appear to use go and is failing, although with a different error `AttributeError: 'NoneType' object has no attribute 'replace'` than the go packages, `AttributeError: '_pylief.ELF.Binary' object has no attribute 'soname'`

**Comment by jakirkham** [comment]
It sounds like anything that was statically linked. Though I could be mistaken.

**Comment by sodre** [comment]
The packages built with go definitely have the problem as I have been patching the conda-forge recipes and referencing this issue.

The ptvsd issue is outside of my scope and was reported earlier by @isuruf, I wanted to copy the problem back here for completeness. Looking back at it,  I should have split the issue into two, one handling the 'soname' issue and the other 'replace'. 

I will try to rebuild some c/c++ packages that I have access and report back.

**Comment by sodre** [comment]
I only found a negative example in conda-forge/hcephes-feedstock#13, so I don't know yet.
A basic 'hello.c' does not cause the problem either as we should expect.

**Comment by jakirkham** [comment]
Did you already inspect the libraries produced by `ptvsd`? Was there anything unusual about them?

**Comment by sodre** [comment]
Not yet, that might take longer for me to debug since I am not familiar with ptvsd.

**Comment by jakirkham** [comment]
Maybe @dhirschfeld would be able to help. 😉
