### ISSUE TITLE
conda-build doesn't handle file-uri scheme in channels correctly

### ISSUE THREAD

**Issue by henklaak** [conda/conda-build#3299]
When the .condarc file contains local channels in the form "file://" conda-build fails.
Fails in 3.17.1, worked until 3.16.1.

.condarc:
```
channels:
  -  file://myserver/mychannel
```
Exception trace:
```
...
File "C:\Localdata\anaconda3\lib\site-packages\conda_build\index.py", line 257, in get_build_index
    with open(os.path.join(location, channel.name, 'channeldata.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'myserver\\mychannel\\channeldata.json'
```

**Comment by henklaak** [comment]
Never mind. Probably solved in 5882e3249

**Comment by kuepe-sl** [comment]
I think the channel URI is wrong.

`file://` + `/myserver/mychannel` results in three forward slashes, so it should be
`
file:///myserver/mychannel
`

**Comment by henklaak** [comment]
@kuepe-sl RFC8089 says 2 slashes, see: https://tools.ietf.org/html/rfc8089

**Comment by msarahan** [comment]
> I would do a PR, but I think the maintainers will solve it better and quicker.

Don't bet on it.  A PR is always welcome.  We can improve on it after you submit it.
