### ISSUE TITLE
Conda env prefix in build, host and run environments

### ISSUE THREAD

**Issue by egpbos** [conda/conda-build#3302]
I'm writing a recipe for a package, [TiCC Utils](https://github.com/LanguageMachines/ticcutils), that uses autoconf and specifically autoconf-archives. The autoconf bootstrap script tries to detect the autoconf-archives directory. I built a [conda-forge package for autoconf-archives](https://github.com/conda-forge/autoconf-archive-feedstock) that installs the m4 scripts to share/actools. All fine and well.

However, I need to modify the TiCC Utils bootstrap script to detect the autoconf-archives scripts in the Conda environment path.

I figured this could be done by simply [adding $CONDA_PREFIX to the search paths, as I did in this commit](https://github.com/egpbos/ticcutils/commit/ee9a173012ad6eef67a9f41a9123f76f973f0430). However, this does not work from conda-build. It detects only the build environment directory, not the host environment where I have the actual autoconf-archive scripts installed. I [added a debug echo to the bootstrap script in this commit](https://github.com/egpbos/ticcutils/commit/fb19f97a9d1e21ba2f9377b3bb98485c30638d1c) to check this.

The TiCC Utils recipe, as I have it now, has only the C++ compiler in the build requirements (via jinja `{{ compiler('cxx') }}`) and in the host requirements libxml2, icu, boost, zlib, autoconf, autoconf-archive, libtool and pkg-config.

### Actual Behavior

When I run `conda-build` on the recipe, my debug echo prints that $CONDA_PREFIX is the _build_env directory.

### Expected Behavior

I want to write a bootstrap script that can detect Conda-installed autoconf-archive scripts in three situations:

1. When building from source outside of Conda, but based on the Conda-installed autoconf-archive. 
2. When building in conda-build, with autoconf-archive installed in the **build** requirements. 
3. When building in conda-build, with autoconf-archive installed in the **host** requirements.

How can I achieve this? Is there any generic environment variable like CONDA_PREFIX that would also work in situations 2 and 3? I saw somewhere mentioned that there are also build_prefix and host_prefix variables, but if I understand correctly they are only used in conda-build, so would not be generic.

##### `Output of conda info`

```
     active environment : None
       user config file : /Users/pbos/.condarc
 populated config files : /Users/pbos/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.6.7.final.0
       base environment : /Users/pbos/sw/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/pbos/sw/miniconda3/pkgs
                          /Users/pbos/.conda/pkgs
       envs directories : /Users/pbos/sw/miniconda3/envs
                          /Users/pbos/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.7 Darwin/18.2.0 OSX/10.14.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
CONDA_PREFIX is a runtime thing.  You'd use it more in your activation scripts, not in your build scripts.  For build scripts, there's $PREFIX and $BUILD_PREFIX

**Comment by mingwandroid** [comment]
> in the host requirements libxml2, icu, boost, zlib, autoconf, autoconf-archive, libtool and pkg-config.

autoconf, autoconf-archive, libtool and pkg-config are all build requirements and must be listed in the correct place.

1. is unsupported. It might work, it might not.
3. will never work and is incorrect.

**Comment by egpbos** [comment]
Thanks for your input! The thing was that I was using the prefix in the source of the code I want to package, not in the conda recipe itself.

However, it is now fixed in a different way; I was actually missing a dependency (automake).
