### ISSUE TITLE
Fix for PIP_NO_DEPENDENCIES was not made to windows.py

### ISSUE THREAD

**Issue by tjd2002** [conda/conda-build#3312]
PR #3271 fixed #3254 by inverting the value of the PIP_NO_DEPENDENCIES flag, but the fix seems to be incomplete, as it did not change the value in the `windows.py` script. Compare:

https://github.com/conda/conda-build/blob/c8eae4960242dd425f2f0eb15cfe19488497cfac/conda_build/windows.py#L308

https://github.com/conda/conda-build/blob/c8eae4960242dd425f2f0eb15cfe19488497cfac/conda_build/build.py#L1862

It's a simple fix, but I'm not in a position to test it (don't have a Windows machine), so I won't issue the PR.

**Comment by jjhelmus** [comment]
Fixed in #3319
