### ISSUE TITLE
Using same name in main package and outputs causes all kinds of problems, e.g. tests won't get run

### ISSUE THREAD

**Issue by bergtholdt** [conda/conda-build#3313]
### Actual Behavior

When re-using the name from the package in an output, all kinds of unexpected behavior can be observed. The latest issue I had was, that tests don't get run.

### Expected Behavior

One of two:

1. error out with a message that you cannot use the package name as an output name
2. any section in output overwrites corresponding package section, only the output gets built, not the parent package

My preference is the first. I implemented it in #3314

### Steps to Reproduce

Just create a test with this content

```yaml
package:
  name: pytest
  version: 1.0

outputs:
  - name: pytest
    test:
      imports:
        - re
```

and you'll get the output like

Nothing to test for: /usr/local/data/miniconda3/conda-bld/linux-64/pytest-1.0-0.tar.bz2

If you change pytest in either the package or the outputs section, the test will run.

##### `Output of conda info`

```
          conda version : 4.5.11
    conda-build version : 3.17.3+6.gc8eae496.dirty
         python version : 3.7.1.final.0
```

**Comment by bergtholdt** [comment]
In the appveyor builds of the patch there are many failing tests due to using the same name in package name and outputs, i.e. the patch works.
But since tests use that kind of naming, maybe 2. is preferred. However I remember having read many posts from @msarahan that it is discouraged to do so. Instead of discouraging I'd prefer checking and error-out since any error message for issues, like the one above, are just not helpful for a user who does not know all conda build internals and has just studied the documentation.

**Comment by msarahan** [comment]
I agree that the addition of errors here is a good thing, and we should make that separation forced.  It may break a few things in the meantime, but it will improve the situation with buggy sometimes-working attempts at merging things.  I'll try to help sort out the tests on your PR.  Forcing this error might mean that we have to cut a conda-build 4.0, but it will be worthwhile I think.

**Comment by keithj** [comment]
Hi,
I'm following this discussion with interest as we have a number of packages where the package and one of its subpackages have the same name. I was surprised that this is discouraged because the Conda documentation implies that this is permitted [1]: "

>  If you do this and you do not **define a subpackage name that matches the top-level package/name**, conda build creates a metapackage for you

If this behaviour is to change, I think the documentation would benefit from a clarification.

[1] https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#implicit-metapackages

**Comment by msarahan** [comment]
Yes, the docs need to be changed.
