### ISSUE TITLE
Better error message when version field is missing

### ISSUE THREAD

**Issue by bergtholdt** [conda/conda-build#3315]
Using a simple recipe:

```yaml
package:
  name: test
```

### Actual Behavior

I get a not very helpful error message like:

    conda_verify.errors.PackageError: Found invalid sequence "--" in package in info/index.json

### Expected Behavior

A message similar to the error for a missing package name, e.g.:

    Error: package/version missing in: 'test/meta.yaml'

### Steps to Reproduce

run conda build on the erroneous recipe above. When introducing the version field:

```yaml
package:
  name: test
  version: 1.0
```

everything works.

**Comment by marscher** [comment]
Confirmed, it is kind of confusing.
