### ISSUE TITLE
Installing conda-build with Miniconda 4.5.11 downgrades Python to 3.6

### ISSUE THREAD

**Issue by mayito** [conda/conda-build#3316]
Hi,

The main feature of Miniconda 4.5.11 is to support Python 3.7. But it seems conda-build requires Python 3.6 and downgrade the base environment. Do you plan to provide a new build supporting Python 3.7 ?

Regards.

**Comment by msarahan** [comment]
This is not an issue related to conda-build, which is a package build tool.  Please file issues on the correct repo.  The correct repo for this is probably https://github.com/continuumio/anaconda-issues
