### ISSUE TITLE
Should RPMs get extracted?

### ISSUE THREAD

**Issue by hmaarrfk** [conda/conda-build#3347]
https://github.com/conda/conda-build/blob/4fc12f8909afa9808edb456cda52e142be25b759/conda_build/utils.py#L706

I had to fall back to conda-build 3.15.1 to build CDTs.

Is that the desired behaviour?

cc: @jjhelmus

**Comment by jjhelmus** [comment]
Unpacking RPM in CDTs is fine as long as the recipe was created with conda-build 3.17.0 or newer.  Older recipes will need to be updated to include the branch from 1800fa4053ea9f2cc292f2826b63ab0886ff1949 to deal with the unpacked files.
