### ISSUE TITLE
has_prefix_files in windows with \\ path delimiter for relocation

### ISSUE THREAD

**Issue by petrushy** [conda/conda-build#3348]
I am having issues with a path that is coded in a python script under windows. In mac/linux conda-build finds the path and makes it relocatable, but not on windows. I think it may be that there are double \\ for path delimiter

### Actual Behavior

Path is hard-coded in conda package on windows (not on mac/linux). Build says that no hard coded path was found in the file, depite that there is. "Did not detect hard-coded path in Lib/site-packages/jcc/config.py from has_prefix_files"

One example text in that file is:
INCLUDES=['C:\\Users\\XXX\\AppData\\Local\\Continuum\\Anaconda3-430\\Library\\include', 'C:\\Users\\XXX\\AppData\\Local\\Continuum\\Anaconda3-430\\Library\\include\\win32']

### Expected Behavior

The hard-coded path should be replaced with the relocatable string marker.

##### `Output of conda info`
```
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.6.2.final.0


```

**Comment by seanyen** [comment]
@petrushy I think I hit the same issue you ran into. Not sure if you have figured out any workaround.

I haven't confirmed it yet but I suspected it to do with this logic:
https://github.com/conda/conda-build/blob/3.18.9/conda_build/build.py#L246-L256
