### ISSUE TITLE
anaconda.org ignores conda-build's custom channels, providing invalid instructions to users

### ISSUE THREAD

**Issue by stas00** [conda/conda-build#3352]
If conda-build is passed extra channels, those exact channels need to be given to a user to install that package. Yet, anaconda.org ignores them, and instead tells users to install packages with instructions that guaranteed to lead to failure. Package owners aren't allowed to edit those automatically generated instructions or disable their display. 

I tried to sort it out via support, but after several attempts of the person on the other side not even understanding what I was saying, the only thing I got from it is that I the developer should change my `~/.condarc`. Which is a ridiculous answer.

So what we need is this. If the package is built with:

```
conda-build -c foo -c bar ... mypackage
```
anaconda.org either 

1) needs to display:

```
conda install -c userchannel -c foo -c bar mypackage
```

2) or let the package owner edit the currently invalid instructions and not overwrite them on new package release.

3) or let the package owner remove it completely, since the description below (coming from README.md) does include the correct instructions provided by the package owner. 

I'm posting it here for two reasons:

* It's pointnless talking to anaconda.org support. It's not the first time that I attempted to contact anaconda.org support just to wait for many weeks to eventually receive a clueless reply. I will no longer entertain that folly in the future.
* Perhaps conda-build needs to provide some new metadata to whatever powers anaconda.org. If the situation about the channels is unclear, simply show no instructions based on a wrong guess.

Here are two examples of broken installation instructions provided by anaconda.org for packages I'm involved in:
```
conda install -c fastai fastai
conda install -c stason ipyexperiments
```
e.g. [fastai page](https://anaconda.org/fastai/fastai) and they will fail to find the required dependencies, because they need to be:
```
conda install -c pytorch -c fastai fastai
conda install -c fastai -c stason ipyexperiments
```

Thank you.

**Comment by msarahan** [comment]
This is a documentation change.  anaconda.org's codebase is in maintenance mode right now and will not be changed for this.  It's possible that some future codebase might include it, but it seems like a complicated thing with a lot of edge cases.

We continue to recommend that you document proper installation (as you have done) in your readme further down.  It may be more possible for us to remove the recommended install line completely, but we can't offer any timeline nor promise of eventual implementation for that feature right now.  If this is important enough to your company, please contact sales@anaconda.com to discuss consulting projects.
