### ISSUE TITLE
Document new features

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#3360]
Conda-build gained a lot of new features in the lasts month but not all of them were properly documented, for example, the `missing_dso_whitelist` and `runpath_whitelist` keys for the `meta.yaml`'s build-section. And now, with v3.17 and py-lief there seems to be an additonal setting (`prefix_owners`) which is also not documented.

These things are important for people outside of conda-forge that don't build their own c-compiler but rely on some low-level system libs (like libc).

**Comment by scopatz** [comment]
Bumping this! `missing_dso_whitelist` is still undocumented

**Comment by rrigdon** [comment]
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#whitelisting-shared-libraries

Thanks for the feedback!
