### ISSUE TITLE
rever release didn't pick up news

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#3365]
3.17.8 was the first release issued with rever.  It seems like mostly everything worked fine.

I had to edit in two things in the author file manually:

1. add a new author who hadn't previously contributed
2. add a missing github id for one author

Aside from this, the one news entry I had put in, https://github.com/conda/conda-build/pull/3364/files#diff-b600547281c878370c801cb1d439ba29 didn't appear to make it into the github changelog.  I don't know if it should have.  I'll check with @scopatz and @CJ-Wright to better understand what might have gotten mixed up.

**Comment by scopatz** [comment]
Thanks @msarahan! 

> I had to edit in two things in the author file manually

Yeah the github identification isn't perfect yet and could be improved.  Hopefully the manual author editing wasn't too much of a burden and was caught during `rever check`.

> The one news entry I had put in...

Actually it didn't seem to make it into the `CHANGELOG.txt` either.  Do you happen to know which version of rever you were running?

**Comment by scopatz** [comment]
The `.rst` extension should be fine because it only ignores certain patterns, ie [`$CHANGELOG_IGNORE`](https://regro.github.io/rever-docs/activities.html#changelog).  I'm looking into it.  Maybe I misconfigured somehow

**Comment by scopatz** [comment]
hmm this is weird.  I can't reproduce any similar errors locally and everything seems to work fine. Did you happen to release on Windows?  Maybe there are some latent path issues?

**Comment by scopatz** [comment]
It shouldn't though, because we are doing an `os.path.join()`: https://github.com/regro/rever/blob/master/rever/activities/changelog.xsh#L111

**Comment by msarahan** [comment]
I did try on windows, but I didn't get it to work with that.  I ended up using Ubuntu via WSL.  I guess I'll just try again next time and spend more time debugging more carefully.  Thanks for the clean up PR.  You're too kind.

**Comment by scopatz** [comment]
No problem! Yeah, this is a very weird error. I'd love to get to the bottom of it. Next time, if you can report the errors as you see them, that'd be great!

Alternatively, if you want to test it now, you can create a test branch, add some fake news files and then run something like:

```bash
$ rever -a authors,changelog 10000 
```

to test it, and 

```bash
$ rever -u changelog,authors 10003 
```

to revert the test.  This is what I was doing to play around with it.

**Comment by scopatz** [comment]
Now that I think about it, it might be some silly line-ending-in-regex issue.

**Comment by msarahan** [comment]
For my latest release with conda-package-handling, I edited only the parts of the template that I was changing, and left the rest of the template content.  That worked out much better.  I think I'll explain that in our PR template.  Anyway, happy releasing everyone.

**Comment by scopatz** [comment]
Hmm very interesting.  It should work even with some of the parts removed, but maybe there were subtle alterations I didn't see.  If you continue to see issues please feel free to open them on rever!
