### ISSUE TITLE
Per `output` abouts section

### ISSUE THREAD

**Issue by epruesse** [conda/conda-build#3376]
Not sure if this is possible - if so it's not mentioned in the docs. But for packages with multiple outputs, the summary/description should usually vary. E.g. `tbb`: `Intel Threaded Building Blocks library` and `tbb-devel`: `Intel Threaded Building Blocks development headers`. It's probably sufficient to allow the `about:` section to re-occurr inside an output. Alternate outputs might have alternate license too.

**Comment by msarahan** [comment]
Yes, this is possible.  All sections except ``package``, ``source``, and ``outputs`` are valid for any given output.

**Comment by epruesse** [comment]
Should this perhaps be documented then?
