### ISSUE TITLE
conda-build --output return the wrong path

### ISSUE THREAD

**Issue by hainm** [conda/conda-build#3400]
Hi, please see the description below.

### Actual Behavior

I built a package with `--py 3.7` and used `conda build --output $RECIPE_DIR --py 2.7` to get the package path for python 2.7 build.

### Expected Behavior

`conda build --output $RECIPE_DIR --py 2.7` should return correct path for python 2.7 but I got
the path for python 3.7 (which means the `--py 2.7` is not respected).
```
/Users/xyz/miniconda3/conda-bld/osx-64/amber_phenix-0.8-py37_0.tar.bz2
```
### Steps to Reproduce

Make super simple recipe:
`meta.yaml`
```
package:
  name: amber_phenix
  version: 0.8

source:
  path: ../some_folder
  
build:
  number: 0

requirements:
  build:
    - python
  run:
    - python

about:
    home: https://ambermd.org
    license: hello
    summary: hello
```

`build.sh`
```
#!/bin/sh/

package=`conda build --output $RECIPE_DIR --py 2.7`
echo "HELLO Path to py2.7 package $package"
```

##### `Output of conda info`
```

     active environment : None
            shell level : 0
       user config file : /Users/haichit/.condarc
 populated config files : /Users/haichit/.condarc
          conda version : 4.5.11
    conda-build version : 3.10.6
         python version : 3.6.7.final.0
       base environment : /Users/haichit/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          http://ambermd.org/downloads/ambertools/conda/osx-64
                          http://ambermd.org/downloads/ambertools/conda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/haichit/miniconda3/pkgs
                          /Users/haichit/.conda/pkgs
       envs directories : /Users/haichit/miniconda3/envs
                          /Users/haichit/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.7 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by hainm** [comment]
conda-build 2.7 does indeed return expected output.

**Comment by soapy1** [comment]
```conda-build version : 3.10.6```

It looks like you have a really out of date version of conda-build. I can't reproduce this issue with the latest conda-build. Please consider updating

```
conda update conda-build
```

**Comment by hainm** [comment]
hi @soapy1, I can reproduce the issue with the latest conda-build too (`conda-build version : 3.17.8`).
This is the output log I saw:
`HELLO Path to py2.7 package /Users/haichit/miniconda3/conda-bld/osx-64/amber_phenix-0.8-py36_0.tar.bz2`

The expected message should be
`HELLO Path to py2.7 package /Users/haichit/miniconda3/conda-bld/osx-64/amber_phenix-0.8-py27_0.tar.bz2` (py36 should be p27)

below is the full log if you're interested:
```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for amber_phenix
INFO:conda_build.metadata:Attempting to finalize metadata for amber_phenix
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: ['amber_phenix-0.8-py36_0.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/haichit/miniconda3/conda-bld/amber_phenix_1551656973145/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place


The following NEW packages will be INSTALLED:

    ca-certificates: 2019.1.23-0            
    certifi:         2018.11.29-py36_0      
    libcxx:          4.0.1-hcfea43d_1       
    libcxxabi:       4.0.1-hcfea43d_1       
    libedit:         3.1.20181209-hb402a30_0
    libffi:          3.2.1-h475c297_4       
    ncurses:         6.1-h0a44026_1         
    openssl:         1.1.1b-h1de35cc_0      
    pip:             19.0.3-py36_0          
    python:          3.6.8-haf84260_0       
    readline:        7.0-h1de35cc_5         
    setuptools:      40.8.0-py36_0          
    sqlite:          3.26.0-ha441bb4_0      
    tk:              8.6.8-ha441bb4_0       
    wheel:           0.33.1-py36_0          
    xz:              5.2.4-h1de35cc_4       
    zlib:            1.2.11-h1de35cc_3      

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
Copying /Users/haichit/Downloads/tmp/some_folder to /Users/haichit/miniconda3/conda-bld/amber_phenix_1551656973145/work
source tree in: /Users/haichit/miniconda3/conda-bld/amber_phenix_1551656973145/work
export PREFIX=/Users/haichit/miniconda3/conda-bld/amber_phenix_1551656973145/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
export SRC_DIR=/Users/haichit/miniconda3/conda-bld/amber_phenix_1551656973145/work
HELLO Path to py2.7 package /Users/haichit/miniconda3/conda-bld/osx-64/amber_phenix-0.8-py36_0.tar.bz2

Resource usage statistics from building amber_phenix:
   Process count: 3
   CPU time: Sys=0:00:00.4, User=0:00:04.2
   Memory: 166.6M
   Disk usage: 24B
   Time elapsed: 0:00:08.1

Packaging amber_phenix
INFO:conda_build.build:Packaging amber_phenix
Packaging amber_phenix-0.8-py36_0
INFO:conda_build.build:Packaging amber_phenix-0.8-py36_0
No files or script found for output amber_phenix
WARNING:conda_build.build:No files or script found for output amber_phenix
number of files: 0
Fixing permissions
Compressing to /var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/tmpijdvdjjs/amber_phenix-0.8-py36_0.tar.bz2
Package verification results:
-----------------------------
/var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/tmpijdvdjjs/amber_phenix-0.8-py36_0.tar.bz2: C1115 Found invalid license "hello" in info/index.json
TEST START: /Users/haichit/miniconda3/conda-bld/osx-64/amber_phenix-0.8-py36_0.tar.bz2
Adding in variants from /var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/tmpiphkjjze/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/tmpiphkjjze/info/recipe/conda_build_config.yaml
Nothing to test for: /Users/haichit/miniconda3/conda-bld/osx-64/amber_phenix-0.8-py36_0.tar.bz2
Renaming work directory,  /Users/haichit/miniconda3/conda-bld/amber_phenix_1551656973145/work  to  /Users/haichit/miniconda3/conda-bld/amber_phenix_1551656973145/work_moved_amber_phenix-0.8-py36_0_osx-64_main_build_loop
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /Users/haichit/miniconda3/conda-bld/osx-64/amber_phenix-0.8-py36_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
####################################################################################
Resource usage summary:

Total time: 0:00:29.2
CPU usage: sys=0:00:00.4, user=0:00:04.2
Maximum memory usage observed: 166.6M
Total disk usage observed (not including envs): 24B


####################################################################################
Source and build intermediates have been left in /Users/haichit/miniconda3/conda-bld.
There are currently 3 accumulated.
To remove them, you can run the ```conda build purge``` command
haichit@haimac ~/Downloads/tmp $ conda info

     active environment : None
       user config file : /Users/haichit/.condarc
 populated config files : /Users/haichit/.condarc
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.6.7.final.0
       base environment : /Users/haichit/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          http://ambermd.org/downloads/ambertools/conda/osx-64
                          http://ambermd.org/downloads/ambertools/conda/noarch
          package cache : /Users/haichit/miniconda3/pkgs
                          /Users/haichit/.conda/pkgs
       envs directories : /Users/haichit/miniconda3/envs
                          /Users/haichit/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.6.7 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

**Comment by jjhelmus** [comment]
I can replicate this with the latest conda build release.

Calling `conda build` from within a conda build environment is not a typical use case and you may run into a number of issues doing this.  Is there a particular reason you need to call conda build inside your build script?

**Comment by hainm** [comment]
We're distributing a conda packages with multiple python versions. Python code is only small part of the package.

Here is the procedure:
- Building the whole package (C/C++, Fortran and python) with python 2.7
- Use the generated conda package to build subsequent python versions. The conda build package from 1st step is needed because some python code require some libraries (which are quite expensive to rebuild)

I need to find the path from above step. (of course I can find the pattern `amber_phenix-0.8-py27_0.tar.bz2`) but `conda-build` can do that.

**Comment by hainm** [comment]
It used to work with `conda-build 2.1.17`

**Comment by msarahan** [comment]
You should be using outputs/split packages to do this, as they were explicitly designed for this purpose.  For an example, see https://github.com/AnacondaRecipes/curl-feedstock/blob/master/recipe/meta.yaml or https://github.com/AnacondaRecipes/xgboost-feedstock/blob/master/recipe/meta.yaml

when python is in an output, conda-build will use a matrix to build out all of the packages.

The Conda team won't fix this, but if you really want it, we'd take a PR.  I'll leave this issue open, but if you have no intent to fix it, please let us know and we'll close it.

**Comment by hainm** [comment]
thanks @msarahan. I just want to report here so you all can aware of the issue. I have a workaround by replacing  whatever python version string to targeted one (2.7 in this case). 

I will have a look at the recipes. Thanks.

**Comment by hainm** [comment]
> You should be using outputs/split packages to do this, as they were explicitly designed for this purpose. For an example, see https://github.com/AnacondaRecipes/curl-feedstock/blob/master/recipe/meta.yaml or https://github.com/AnacondaRecipes/xgboost-feedstock/blob/master/recipe/meta.yaml

> when python is in an output, conda-build will use a matrix to build out all of the packages.

I've read those recipes and I have impression that the procedure is opposite to what I am trying to achieve. 

Instead of "split", I want to to "combine".

Saying I have a package "foo" that has "bar" (C++/Fortran code) part and python code part.
Traditionally I will need to specify `--py version` to build "bar" with different python versions.
So I end up with foo_py27, foo_py34, foo_py36...

My workflow is to have a single package "foo" that include `bar` + python 2.7, 3.4, 3.6 ...

**Comment by msarahan** [comment]
Yes, I misunderstood.  Sorry about that.  While I'm sorry that this has broken, it was never a supported use case.  If you want this to be supported, you'll need to both fix it and implement tests to ensure that the functionality does not break.

I personally do not see much advantage to one package containing files for multiple python versions vs. multiple packages that are split appropriately.  The key is to make sure that the expensive core compiled code lies in a separate package, and then the cheap python packages depend on the expensive core.  That's what the examples I sent you do.

**Comment by hainm** [comment]
>If you want this to be supported, you'll need to both fix it and implement tests to ensure that the functionality does not break.

no worry, I have a workaround that I mentioned earlier. I think it's fine to not to fix this tiny tiny issue.

> I personally do not see much advantage to one package containing files for multiple python versions vs. multiple packages that are split appropriately. 

yeah, it's a bit complicated in the software I am contributing.  First, the software has only small Python part and many existing users of the software don't care about python or Miniconda or conda. So we need to build conda package for conda user, then repack it for non-conda users (so they can just use `wget /url/to/non-conda-package` and untar the file and just use it). It's a bit convenient to let user to download only a single package to work with any python version they have, rather than asking them to check for system python version and then download appropriate link for each python. 

There are many other reasons to keep my existing workflow but I guess you might not interested in the context. :D 

thanks @msarahan

**Comment by msarahan** [comment]
One other way to create your amalgamated package might be to use a recipe to create a split package (and upload those packages as normal), but then also do a post-processing step to combine them all.  https://github.com/conda/conda-package-handling may be a useful tool for that, between its "extract" and "create" functions.

**Comment by hainm** [comment]
Thank you. :)
