### ISSUE TITLE
Set MSSDK and DISTUTILS_USE_SDK when building

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#342]
See https://docs.python.org/2/distutils/apiref.html#module-distutils.msvccompiler. Setting these both to 1 apparently helps distutils find the Microsoft Visual C++ Compiler for Python 2.7.

**Comment by jasongrout** [comment]
For what it's worth, I had to set these variables in my bld.bat to get a windows extension compiled.

**Comment by ccordoba12** [comment]
This is already done after PR #600, which is part of conda-build 1.17.1
