### ISSUE TITLE
Binary files with prefix in wchar_t (or other encoding)

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda-build#3420]
It seems that conda-build does not handle the case of a binary file containing the full prefix as a `wchar_t` string.

This would be handy for packages that *embed* python, which often have to specify PYTHONHOME, which is encoded in `wchar_t` from Python 3 and on.

**Comment by jjhelmus** [comment]
Since the format of `wchar_t` is compiler dependent detecting string of this format in a binary might be challenging.  @SylvainCorlay Do you have any thought on how conda build could detect the presence of prefixes in binaries?

**Comment by mingwandroid** [comment]
```
for encoding in ('ascii', 'utf-16', 'utf-32'):
try:
    replacement = original.encode(encoding)
    file_contents.replace(replacement, '/opt/anaconda1anaconda2anaconda3'.encode(encoding))
except:
    pass
```

**Comment by SylvainCorlay** [comment]
Yes, one could check multiple possible encodings. It seems unlikely that one would not want to modify a hardcoded path for a certain encoding.

I picked wchar_t because it is commonly used by Python 3.

**Comment by hmaarrfk** [comment]
I'm trying to find where to start looking for this replacement, and 

https://github.com/conda/conda-build/blob/master/conda_build/inspect_pkg.py#L121

https://github.com/conda/conda-build/blob/master/conda_build/build.py#L167

Some tips:
https://github.com/conda-forge/conda-feedstock/pull/135#issuecomment-727277844
