### ISSUE TITLE
404 not found when running `conda skeleton rpm --distro centos7 ...`

### ISSUE THREAD

**Issue by zhaojack** [conda/conda-build#3423]
### Actual Behavior

I get an "HTTP Error 404: Not Found" whenever I try to run `conda skeleton rpm --distro centos7` and some rpm name. This is what the tracebacks look like:

```
Traceback (most recent call last):
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/site-packages/conda_build/api.py", line 289, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 678, in skeletonize
    override_arch, dependency_add, config)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 662, in write_conda_recipe
    config.src_cache)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 325, in get_repo_dict
    xmlstring = urlopen(repomd_url).read()
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/jackzhao/tmp/conda-test/install/envs/buildenv/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### Expected Behavior

It should work, I think?

### Steps to Reproduce

Pick an rpm, then run `conda skeleton rpm --distro centos7 <rpm_name>`

##### `Output of conda info`

```
(buildenv) [root@faa7764950a0 ~]# conda info

     active environment : buildenv
    active env location : /home/jackzhao/tmp/conda-test/install/envs/buildenv
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.6.3
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /home/jackzhao/tmp/conda-test/install  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jackzhao/tmp/conda-test/install/pkgs
                          /root/.conda/pkgs
       envs directories : /home/jackzhao/tmp/conda-test/install/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.3 requests/2.21.0 CPython/2.7.15 Linux/3.10.0-862.3.2.el7.px.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```

##### conda-build version:
```
(buildenv) [root@faa7764950a0 ~]# conda-build --version
conda-build 3.17.8
```

### What I Think Is Happening

The [CDTs list](https://github.com/conda/conda-build/blob/master/conda_build/skeletons/rpm.py#L151) hardcodes the repomd url path to `http://mirror.centos.org/altarch/...`. By default the architecture is `x86_64`, and there is no `x86_64` folder under altarch. This seems to be inconsistent with the pattern for `centos6` which goes to somewhere under the main `centos` path where the `x86_64` rpms can be found.

While I'm here, I'd like to mention that I was actually trying to run `conda-build skeleton rpm` on something located here: `http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-6/`, which I think I wouldn't be able to do even with the centos6 repo url pattern (since `os` is hardcoded in the url). I looked at the `conda skeleton rpm` flags and didn't see anything that looks like it would let me do this. If this is somehow possible today, any guidance would be appreciated.

Thanks,
Jack

**Comment by jjhelmus** [comment]
The `centos7` distribution support in `conda skeleton rpm` was added to support the linux-ppc64le platform which is not supported on CentOS 6.  Additional logic would need to be added to the skeleton command to accommodate the x86-64 architecture and RPMs from software collections.

**Comment by mingwandroid** [comment]
> http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-6/

And reason not to use our compilers? The point of cdts is not to repackage software from Linux distros for end users, it's to lock in compat. with any needed system libraries to fixed, known entities.

**Comment by zhaojack** [comment]
Currently I'm trying to build out a set of conda packages for the [vfx2018 standard](https://www.vfxplatform.com/), which specifies gcc 6.3.1, which doesn't seem to be available from conda channels. So our current plan is to use devtoolset-6 as a base and build out conda packages from there for internal use.

Anyway, thanks for the answers. It sounds like `conda skeleton rpm` is currently more catered towards building out anaconda cdt packages rather than as a general purpose "generate me a skeleton from any rpm" tool. This is not a blocker for me at all, I just didn't know what to expect, that's all.

**Comment by mingwandroid** [comment]
> It sounds like conda skeleton rpm is currently more catered towards building out anaconda cdt packages rather than as a general purpose "generate me a skeleton from any rpm" tool

It was designed for that purpose but there's no reason it cannot do what you need too. The only difference is where the files are moved to (our compiler sysroot) before repackaging.

I wouldn't object to a PR to fix CentOS7 on Intel support and to make the target prefix configurable.

**Comment by mingwandroid** [comment]
If you do move the libs to `$PREFIX/lib` and the headers to `$PREFIX/include` you need to be careful about files from these packages clobbering files from 'legitimate' conda packages.

If I were you, I would build your own cross-compilers the same way we do, but at gcc 6.3.1 (though really you should ignore this bad part of the spec and use the latest that's binary compatible with 6.3.1 which is probably 6.5).

**Comment by zhaojack** [comment]
> If I were you, I would build your own cross-compilers the same way we do, but at gcc 6.3.1 (though really you should ignore this bad part of the spec and use the latest that's binary compatible with 6.3.1 which is probably 6.5).

Thanks for the advice! I imagine if I want to try doing this, I'd be looking for all the basic compiler conda packages and follow what their recipes say were done. Is there a convenient place that lists all the relevant "compiler" packages for such a task? If not, I can always search for packages and looking at dependencies manually.

Though I'd love to work on a PR for configurable conda skeleton rpm, unfortunately I don't think I have the cycles right now.

Anyway, thanks for the help!

**Comment by jjhelmus** [comment]
The recipes for the conda compilers can be found in the [aggregate repository](https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-feedstock/recipe) and should offer a good jumping off point if you wanted to build your own compilers.  The other recipe you will want to look at is [crosstools-ng](https://github.com/AnacondaRecipes/aggregate/tree/master/crosstool-ng-feedstock/recipe) which is the conda package for [crosstool-NG](https://crosstool-ng.github.io/) which is used to build these compilers.
