### ISSUE TITLE
it is not possible to link to symlinks of libraries  #[cmake, osx]

### ISSUE THREAD

**Issue by looooo** [conda/conda-build#3426]
the cmake command:
`target_link_library(<lib> vtkCommonCore)`
fails with the strange error-report:
```
CMake Error in CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 4.0.1.
```

The problem came up in this feedstock: 
https://github.com/conda-forge/smesh-feedstock

Replacing the command with:
`target_link_library(<lib> vtkCommonCore-8.2.1)`
works.

`libvtkCommonCore.dylib` is a symlink to `libvtkCommonCore-8.2.1`. So my conclusion is that linking to symlink is somehow not possible with conda-build on osx. Does anyone know the reason for this?

**Comment by mingwandroid** [comment]
Did you debug this? Closing, it's *clearly* not an issue with conda-build!

**Comment by mingwandroid** [comment]
What you are doing wrong however, is attempting to link to a C++ library with a C compiler, AFAICT.

**Comment by looooo** [comment]
btw.:

> No known features for CXX compiler

doesn't sound like a c-compiler is checked for compile-features.

**Comment by looooo** [comment]
I get the same result for this minimal example:

```
project(test)
cmake_minimum_required(VERSION 3.10)



add_library(a a.cpp)
set_target_properties(a PROPERTIES INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override")
add_library(b b.cpp)
target_link_libraries(b a)
```

So there seems to be something wrong with the compile-feature-detection.
