### ISSUE TITLE
Conda skeleton doesn't handle special chars in string

### ISSUE THREAD

**Issue by Bezier89** [conda/conda-build#3429]
Using version 3.17.8 of conda-build, run the following command:

`conda skeleton pypi execnet --version 1.2.0`

You will be unable to build the resulting recipe because of this line in the recipe:

`summary: execnet: rapid multi-Python deployment`

Note the extra `:` in the summary. I imagine there's a handful of other special characters that would also cause problems. These strings should be quoted to avoid such issues. According the [YAML documentation](http://docs.octoprint.org/en/master/configuration/yaml.html):

> As simple rule of thumb, if your data contains any of these characters :-{}[]!#|>&%@ better quote it.

**Comment by nehaljwani** [comment]
Fixed in https://github.com/conda/conda-build/pull/3430
