### ISSUE TITLE
Windows is using the wrong Python version at test time

### ISSUE THREAD

**Issue by patricksnape** [conda/conda-build#343]
# Environment Information

```
Current conda install:

             platform : win-32
        conda version : 3.9.1
  conda-build version : 1.11.0
       python version : 2.7.8.final.0
     requests version : 2.5.3
     root environment : C:\Anaconda\32  (writable)
  default environment : C:\Anaconda\32
     envs directories : C:\Anaconda\32\envs
        package cache : C:\Anaconda\32\pkgs
         channel URLs : https://conda.binstar.org/menpo/win-32/
                        https://conda.binstar.org/menpo/noarch/
                        http://repo.continuum.io/pkgs/free/win-32/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/win-32/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\pts08\.condarc
    is foreign system : False
```
## Packages Installed In Root

```
binstar                   0.10.1                   py27_2
clyent                    0.3.2                    py27_0
conda                     3.9.1                    py27_0
conda-build               1.11.0                   py27_0
conda-env                 2.1.3                    py27_0
dateutil                  2.1                      py27_2
jinja2                    2.7.3                    py27_1
markupsafe                0.23                     py27_0
menuinst                  1.0.4                    py27_0
psutil                    2.1.1                    py27_0
pycosat                   0.6.1                    py27_0
python                    2.7.8                         0
pytz                      2014.9                   py27_0
pyyaml                    3.11                     py27_0
requests                  2.5.3                    py27_0
setuptools                14.0                     py27_0
six                       1.9.0                    py27_0
```
# Replicate

In a conda build script, try running an arbitrary Python command:

```
test:
  commands:
  - python -c "import sys; print(sys.executable)"
```

which prints the wrong Python executable path (it will print the root Python path). Previously, I had this working, so this is a regression in behaviour.
# Example issue

We are seeing this on our [Appveyor builds](https://ci.appveyor.com/project/jabooth/menpo/build/1.0.392/job/skab8naf41m0m754#L1477) when trying to run our Nose tests. This is because Nose is not installed in the root environment, and the wrong Python interpreter is being picked up. This was not happening until very recently (last couple of days).

**Comment by asmeurer** [comment]
This was probably a regression in conda-build 1.11.0, which was released on the 5th.

**Comment by asmeurer** [comment]
When I create a test recipe with 

```
package:
  name: test
  version: 1.0

test:
  commands:
    - echo %PATH%
```

The `_test` environment is first on the `PATH`.

**Comment by patricksnape** [comment]
It might be the first thing on the path, but the `python` that is getting grabbed is the wrong one for some reason? It's tough for me to check because this is happening on an automated build.

**Comment by dalcinl** [comment]
@asmeurer Please double check `PATH`, I can confirm `PREFIX\Scripts\_test` is in front, but plain `PREFIX` (where `python.exe` is located in Windows) is missing. My temporary workaround was to add the following first line in my `run_test.bat`:

`set PATH=%PREFIX%;%PATH%`
