### ISSUE TITLE
adding compiler('haskell')

### ISSUE THREAD

**Issue by notestaff** [conda/conda-build#3432]
Would the authors of compiler('c'/'c++'/'fortran') packages consider extending this to the ghc compiler for Haskell?   It has cross-compilation support ( https://ghc.haskell.org/trac/ghc/wiki/Building/CrossCompiling )  .  What is required to make this work?

**Comment by jakirkham** [comment]
This could be done today without any changes in conda-build. For example in conda-forge we handled our legacy compilers with [this recipe]( https://github.com/conda-forge/toolchain-feedstock/tree/0a1281325528fba64b6f5deb792aec52416466da/recipe ) and [lines like this in our `conda_build_config.yaml`]( https://github.com/mariusvniekerk/conda-forge-pinning-feedstock/blob/159fda30919e43b006d0778109fd930e23e27c94/recipe/conda_build_config.yaml#L11-L12 ) to add these to the C compilers. One could do this with Haskell or anything else for that matter.
