### ISSUE TITLE
How to purge cache in conda-build

### ISSUE THREAD

**Issue by carolzhou** [conda/conda-build#3434]
##### `Output of conda info`

```

```

**Comment by jjhelmus** [comment]
There are a few commands that will clear various caches:

* `conda build purge` removes old build and test intermediates.
* `conda build purge-all` removes all locally built packages, use with care as this cannot be reversed

If you want to really start fresh you can remove everything in the conda-bld directory using `rm -rf` or a similar command.

**Comment by analog-cbarber** [comment]
`conda build purge` typically does not fix this kind of problem. `conda build purge-all` works but can be overkill since it blows away everything and may force you to rebuild packages.

I have found that I can delete the offending `.cache` directories and repodata files, and reindex.

**Comment by farleylai** [comment]
The `conda-bld/git_cache` does not seem purged by `conda-build purge-all`.
What is the right command to clean that?
