### ISSUE TITLE
conda-build mixes old and new packages

### ISSUE THREAD

**Issue by carolzhou** [conda/conda-build#3435]
Previously using conda-build, I successfully built a package (multiphate, version 0.1.2). Now, Using conda-build, I am trying to build a package:  test_multiphate, version 0.1.5.
 
### Actual Behavior

Conda-build produces output in /site-packages/ consisting of test_multiphate-v0.1.5-py_1.tar.bz2 containing a site-packages/ directory containing multiphate-0.1.2.dist-info, which lists information for the package I had build previously.  It is as if conda-build cannot let go of a previous build's information, and keeps re-building that previous package. The output stream from running conda-build shows it trying to "BUILD START: ['test_multiphate-v0.1.5-py_1.tar.bz2']", but when it comes to the part where it does "running egg-info", it starts accessing the multiphate-v0.1.2 information:  "creating pip-egg-info/multiphate.egg-info", and from there it is using the old package's information. Eventually it says, "Successfully build multiphate" and "Successfully installed multiphate-0.1.2". Then it does "Packaging test_multiphate", and everything beyond that point refers to "test_multiphate".

### Expected Behavior

I am expecting conda-build to build test_multiphate version 0.1.5, not the (previously built) multiphate version 0.1.2.  I have checked all of my files etc, and I am not referencing multiphate version 0.1.2 anywhere that I can find. When I run "python setup.py egg_info" by hand at the command line, I get the correct egg output relating to test_multiphate version 0.1.5.  

### Steps to Reproduce

$ conda-build meta.yaml

meta.yaml contains:
{% set version = "v0.1.5" %}
{% set sha256 = "88b8e520a0cc1187e36e23945a48864f854cd40f85a30b65a0f971cc4e339dd7" %}
package:
  name: test_multiphate 
  version: '{{ version }}' 
source:
  url: https://github.com/carolzhou/test_multiphate/archive/v0.1.5.tar.gz
  sha256: '{{ sha256 }}' 
build:
  number: 1 
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
(etc.)

setup.py:
#!/usr/bin/env python
from setuptools import setup
setup(name='test_multiphate',
	version='0.1.5',
	description='Phage annotation pipeline',
	author='Carol Zhou',
	author_email='zhou4@llnl.gov',
	url='https://github.com/carolzhou/test_multiphate',
	packages=[],
	)

##### `Output of conda info`

```
     active environment : test_multiphate
    active env location : /Users/carolzhou/miniconda3/envs/test_multiphate
            shell level : 1
       user config file : /Users/carolzhou/.condarc
 populated config files : /Users/carolzhou/.condarc
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /Users/carolzhou/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/carolzhou/miniconda3/pkgs
                          /Users/carolzhou/.conda/pkgs
       envs directories : /Users/carolzhou/miniconda3/envs
                          /Users/carolzhou/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
The `setup.py` file in the tarball you links specified the version as 0.1.2 which is where the egg-info version is coming from.

**Comment by carolzhou** [comment]
That was it. Thank you.
