### ISSUE TITLE
ClobberWarning

### ISSUE THREAD

**Issue by carolzhou** [conda/conda-build#3439]
conda-build is returning ClobberWarning errors. Can anyone explain why this is happening and how to fix it?

### Actual Behavior

Sample output from conda-build:

Preparing transaction: ...working... done
Verifying transaction: ...working... ERROR:conda.stderr:
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h79c3c89_1002, bioconda::perl-pathtools-3.73-pl526h470a237_2
  path: 'man/man3/Cwd.3'

Executing transaction: ...working... ERROR:conda.stderr:
ClobberWarning: Conda was asked to clobber an existing path.
  source path: /Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552197205789/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/.condatmp/ca9887dc-e552-47ab-ad89-31bf91448483
  target path: /Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552197205789/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/5.26.2/darwin-thread-multi-2level/perllocal.pod

### Expected Behavior

Don't expect this error--not sure where it's coming from, or whether it is affecting the build process.

$ conda-build meta.yaml

meta.yaml:
{% set version = "v0.1.14" %}
{% set sha256 = "38f7b6ad9b99f64064a2dfde399e8e7e765f05d3b7129c9dc221cc6c8bbbccf9" %}

package:
  name: test_multiphate 
  version: '{{ version }}' 

source:
  url: https://github.com/carolzhou/test_multiphate/archive/v0.1.14.tar.gz
  sha256: '{{ sha256 }}' 

build:
  number: 1 
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - test_multiphate = test_multiphate.__main__:main

requirements:
  host:
    - python
  run:
    - python
    - biopython
    - trnascan-se
    - blast
    - glimmer
    - prodigal
    - hmmer
    - emboss
    
test:
  commands:
    - trnascan-se -h
    - blastp -version
    - prodigal -v
    - jackhmmer -h
    - transeq --version
    - test_multiphate usage

about:
  home: https://github.com/carolzhou/test_multiphate.git
  license: BSD-3
  license_family: BSD
  license_file: BSD-3.pdf
  summary: de novo annotation of phage genome sequence
  dev_url: https://github.com/carolzhou/test_multiphate

extra:
  identifiers:
    - biotools:test_multiphate
    - doi:10.1101/551010

##### `Output of conda info`

```
     active environment : None
       user config file : /Users/carolzhou/.condarc
 populated config files : /Users/carolzhou/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /Users/carolzhou/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/carolzhou/miniconda3/pkgs
                          /Users/carolzhou/.conda/pkgs
       envs directories : /Users/carolzhou/miniconda3/envs
                          /Users/carolzhou/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by shoemakerdr** [comment]
Not sure if you've already solved this issue, but it looks like these two packages are incompatible:
- conda-forge::perl-5.26.2-h79c3c89_1002
- bioconda::perl-pathtools-3.73-pl526h470a237_2

Sometimes packages don't play nice when they come from different channels. Maybe you can mess with pinning different versions/channels in your environment when building this? Maybe try this with perl from bioconda?

**Comment by carolzhou** [comment]
I’ll keep that in mind and put it on my list. I installed via Conda in order to avoid the package clash problem.

Sent from my iPhone

On May 20, 2019, at 9:28 AM, Derek Shoemaker <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if you've already solved this issue, but it looks like these two packages are incompatible:

  *   conda-forge::perl-5.26.2-h79c3c89_1002
  *   bioconda::perl-pathtools-3.73-pl526h470a237_2

Sometimes packages don't play nice when they come from different channels. Maybe you can mess with pinning different versions/channels in your environment when building this? Maybe try this with perl from bioconda?
