### ISSUE TITLE
conda index does not infer the correct dependency version range

### ISSUE THREAD

**Issue by willsALMANJ** [conda/conda-build#3441]
### Actual Behavior

`conda index` seems to infer overly restrictive version requirements. Installing a set of packages into an environment normally and then creating a channel with those packages results in a channel with dependency metadata that does not allow that environment to be installed again because some packages get dependencies pinned to versions lower than what is actually in the environment.

### Expected Behavior

I would expect that if I create a channel from the packages installed into a valid environment that I would end up with a channel that can be used to install that environment again.

### Steps to Reproduce

Here is what I tried (on a 64 bit Linux system):

1. Create a new environment with `conda create -n test yaml`.
2. Copy all of the packages installed into this environment into a `channel\linux-64` directory. One way to do this is to run `conda list -n test --export` and replace all of the `=` with `-` and add `.tar.bz2` to the end of each. Then copy this list of tar.bz2 files from the package cache into the `channel\linux-64` directory.
3. Run `conda index channel`.
4. Run `conda create -n test2 yaml --override-channels -c "file://$PWD/channel"`

For me right now, this fails with:

```
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - yaml -> libgcc-ng=7.2.0
```

because the original `test` environment created in step 1 ended up with `libgcc-ng=8.2.0=hdf63c60_1`, not vesion 7.2.0. `conda search yaml --info` lists the dependencies as `libgcc-ng >=7.2.0` However, `conda search yaml --info --override-channels -c file://$PWD/channel` lists the dependencies as `libgcc-ng 7.2.0.*`. So the version lower bound was turned into a pinned version.

##### `Output of conda info`
```
     active environment : test4
    active env location : /home/user/tmp/miniconda/envs/test4
            shell level : 2
       user config file : /home/user/.condarc
 populated config files : 
          conda version : 4.6.7
    conda-build version : 3.17.8+101.g3b7fab49
         python version : 3.7.1.final.0
       base environment : /home/user/tmp/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/tmp/miniconda/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/tmp/miniconda/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Linux/4.20.4-100.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by msarahan** [comment]
conda index does not infer anything.  It goes by what the packages tell it (which is what you're seeing), and that may be overridden with extra data.  At the time a package is built, mistakes may be made, or the author may just not know the correct compatibility bounds.  Metadata may be "hotfixed."  This is what you're seeing.  More at https://github.com/conda/conda/issues/8090

**Comment by willsALMANJ** [comment]
Thanks! The hotfix patching mentioned there got my channel working. I had said "infer" because I had untarred the yaml package and thought I had seen that it had a `>=7.2.0` specification but double checking now I just see `7.2.0.*`, so I must have been mistaken at some point.
