### ISSUE TITLE
Tests failed for <my package>... Help with structuring code: entry point

### ISSUE THREAD

**Issue by carolzhou** [conda/conda-build#3442]
conda-build seems to be working until the point of testing. The tests for dependent packages succeed, but the test for my own code fails. I am guessing that my code is structured incorrectly for packaging. Normally I run my code at the command line as follows: "python multiPhate.py usage" or "python multiPhate.py multiPhate.config". For packaging, I inserted a main.py file (see below), as an "entry point”. I modified the setup.py and meta.yaml files (see below) to reflect the entry point. It is my understanding that the code, formatted as a conda (bioconda) package, will need to have an "entry point", which can be recognized by naming the first (topmost) executable file as "main.py". If this is not the correct approach, I would appreciate advice regarding how better to structure my code so that it can be packaged and so it behaves as expected as a conda package. In my learning/test setup I name the GitHub repo and the package as "test_multiphate". GitHub.com/carolzhou/test_multiphate.git, current release for testing is v0.1.14. There is also an anomaly in the conda-build output that I cannot explain. When conda-build is “Building wheel”, it prints “test-multiphate” (with hyphen instead of underscore). I believe I have referred to the package/repo/etc consistently as “test_multiphate” (with underscore), but maybe I’m just not finding where there’s a typo. Would this explain the problem with the test?

### Actual Behavior

Tests pass for all of the dependent packages, but the test for my own code fails:

\+ test-multiphate usage
/Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552239790198/test_tmp/run_test.sh: line 12: test-multiphate: command not found
Tests failed for test_multiphate-v0.1.14-py_1.tar.bz2 - moving package to /Users/carolzhou/miniconda3/conda-bld/broken
WARNING:conda_build.build:Tests failed for test_multiphate-v0.1.14-py_1.tar.bz2 - moving package to /Users/carolzhou/miniconda3/conda-bld/broken
TESTS FAILED: test_multiphate-v0.1.14-py_1.tar.bz2

conda-build appears to successfully build the package. During the "Wheel" step, conda-build refers to "test-multiphate" (with hyphen):

Source cache directory is: /Users/carolzhou/miniconda3/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /Users/carolzhou/miniconda3/conda-bld/src_cache
Found source in cache: v0.1.14_38f7b6ad9b.tar.gz
INFO:conda_build.source:Found source in cache: v0.1.14_38f7b6ad9b.tar.gz
Extracting download
source tree in: /Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552239790198/work
export PREFIX=/Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552239790198/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export BUILD_PREFIX=/Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552239790198/_build_env
export SRC_DIR=/Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552239790198/work
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-az9ql4y0
Created temporary directory: /private/tmp/pip-req-tracker-c7o_zwor
Created requirements tracker '/private/tmp/pip-req-tracker-c7o_zwor'
Created temporary directory: /private/tmp/pip-install-fxeo6br2
Processing $SRC_DIR
  Created temporary directory: /private/tmp/pip-req-build-gvpd6gs3
  Added file://$SRC_DIR to build tracker '/private/tmp/pip-req-tracker-c7o_zwor'
    Running setup.py (path:/private/tmp/pip-req-build-gvpd6gs3/setup.py) egg_info for package from file://$SRC_DIR
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/test_multiphate.egg-info
    writing pip-egg-info/test_multiphate.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/test_multiphate.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/test_multiphate.egg-info/entry_points.txt
    writing top-level names to pip-egg-info/test_multiphate.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/test_multiphate.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/test_multiphate.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/test_multiphate.egg-info/SOURCES.txt'
  Source in /private/tmp/pip-req-build-gvpd6gs3 has version 0.1.14, which satisfies requirement test-multiphate==0.1.14 from file://$SRC_DIR
  Removed test-multiphate==0.1.14 from file://$SRC_DIR from build tracker '/private/tmp/pip-req-tracker-c7o_zwor'
Building wheels for collected packages: test-multiphate
  Created temporary directory: /private/tmp/pip-wheel-c61bw9hu
  Building wheel for test-multiphate (setup.py): started
  Destination directory: /private/tmp/pip-wheel-c61bw9hu
  Running command $PREFIX/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-gvpd6gs3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/tmp/pip-wheel-c61bw9hu --python-tag cp37
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.7-x86_64/wheel
  running install
  running install_egg_info
  running egg_info
  creating test_multiphate.egg-info
  writing test_multiphate.egg-info/PKG-INFO
  writing dependency_links to test_multiphate.egg-info/dependency_links.txt
  writing entry points to test_multiphate.egg-info/entry_points.txt
  writing top-level names to test_multiphate.egg-info/top_level.txt
  writing manifest file 'test_multiphate.egg-info/SOURCES.txt'
  reading manifest file 'test_multiphate.egg-info/SOURCES.txt'
  writing manifest file 'test_multiphate.egg-info/SOURCES.txt'
  Copying test_multiphate.egg-info to build/bdist.macosx-10.7-x86_64/wheel/test_multiphate-0.1.14-py3.7.egg-info
  running install_scripts
  creating build/bdist.macosx-10.7-x86_64/wheel/test_multiphate-0.1.14.dist-info/WHEEL
  creating '/private/tmp/pip-wheel-c61bw9hu/test_multiphate-0.1.14-cp37-none-any.whl' and adding 'build/bdist.macosx-10.7-x86_64/wheel' to it
  adding 'test_multiphate-0.1.14.dist-info/METADATA'
  adding 'test_multiphate-0.1.14.dist-info/WHEEL'
  adding 'test_multiphate-0.1.14.dist-info/entry_points.txt'
  adding 'test_multiphate-0.1.14.dist-info/top_level.txt'
  adding 'test_multiphate-0.1.14.dist-info/RECORD'
  removing build/bdist.macosx-10.7-x86_64/wheel
  Building wheel for test-multiphate (setup.py): finished with status 'done'
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-az9ql4y0/wheels/23/2f/05/45e346e6adee4109121586bd11604b5d51c97782537e9d5cc2
  Removing source in /private/tmp/pip-req-build-gvpd6gs3
Successfully built test-multiphate
Installing collected packages: test-multiphate

  changing mode of $PREFIX/bin/test_multiphate to 755
Successfully installed test-multiphate-0.1.14
Cleaning up...
Removed build tracker '/private/tmp/pip-req-tracker-c7o_zwor'

Resource usage statistics from building test_multiphate:
   Process count: 3
   CPU time: Sys=0:00:00.4, User=0:00:00.5
   Memory: 43.6M
   Disk usage: 396.6K
   Time elapsed: 0:00:04.0

Packaging test_multiphate
INFO:conda_build.build:Packaging test_multiphate
Packaging test_multiphate-v0.1.14-py_1
INFO:conda_build.build:Packaging test_multiphate-v0.1.14-py_1
number of files: 7
Fixing permissions
Packaged license file.
Compressing to /var/folders/14/zk4163996bz2mdp0n76tbq400000gn/T/tmpx4tz78hq/test_multiphate-v0.1.14-py_1.tar.bz2
Package verification results:

/var/folders/14/zk4163996bz2mdp0n76tbq400000gn/T/tmpx4tz78hq/test_multiphate-v0.1.14-py_1.tar.bz2: C1139 Found pyc file "info/recipe/__pycache__/__main__.cpython-35.pyc" in invalid directory
TEST START: /Users/carolzhou/miniconda3/conda-bld/noarch/test_multiphate-v0.1.14-py_1.tar.bz2
Adding in variants from /var/folders/14/zk4163996bz2mdp0n76tbq400000gn/T/tmpo7cb81g5/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /var/folders/14/zk4163996bz2mdp0n76tbq400000gn/T/tmpo7cb81g5/info/recipe/conda_build_config.yaml
Renaming work directory,  /Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552239790198/work  to  /Users/carolzhou/miniconda3/conda-bld/test_multiphate_1552239790198/work_moved_test_multiphate-v0.1.14-py_1_noarch
Collecting package metadata: ...working... done
Solving environment: ...working... done

### Expected Behavior

I think conda-build should build the package, and all tests should pass. I tried various ways of writing the test in meta.yaml:

\- test_multiphate usage
\- python -m test_multiphate usage
\- python test_multiphate usage
\- test-multiphate usage
and every possibility I could think of 

### Steps to Reproduce

$ conda-build meta.yaml

meta.yaml: 
{% set version = "v0.1.14" %}
{% set sha256 = "38f7b6ad9b99f64064a2dfde399e8e7e765f05d3b7129c9dc221cc6c8bbbccf9" %}

package:
  name: test_multiphate 
  version: '{{ version }}' 

source:
  url: https://github.com/carolzhou/test_multiphate/archive/v0.1.14.tar.gz
  sha256: '{{ sha256 }}' 

build:
  number: 1 
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - test_multiphate = test_multiphate.__main__:main

requirements:
  host:
    - python
  run:
    - python
    - biopython
    - trnascan-se
    - blast
    - glimmer
    - prodigal
    - hmmer
    - emboss
    
test:
  commands:
    - trnascan-se -h
    - blastp -version
    - prodigal -v
    - jackhmmer -h
    - transeq --version
    - test-multiphate usage

about:
  home: https://github.com/carolzhou/test_multiphate.git
  license: BSD-3
  license_family: BSD
  license_file: BSD-3.pdf
  summary: de novo annotation of phage genome sequence
  dev_url: https://github.com/carolzhou/test_multiphate

extra:
  identifiers:
    - biotools:test_multiphate
    - doi:10.1101/551010

setup.py:
#!/usr/bin/env python

from setuptools import setup

setup(name='test_multiphate',
	version='0.1.14',
	description='Phage annotation pipeline',
	author='Carol Zhou',
	author_email='zhou4@llnl.gov',
	url='https://github.com/carolzhou/test_multiphate',
        entry_points={
            'console_scripts': [
                'test_multiphate=test_multiphate.__main__:main',
            ],
        },
)

\_\_main\_\_.py:
import sys

from .test_multiphate import multiPhate

def main(arg=None):
    if args is None:
        arg = sys.argv[1:]
        multiPhate(args)

if __name__ == '__main__':
    sys.exit(main())

##### `Output of conda info`

```
     active environment : None
       user config file : /Users/carolzhou/.condarc
 populated config files : /Users/carolzhou/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /Users/carolzhou/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/carolzhou/miniconda3/pkgs
                          /Users/carolzhou/.conda/pkgs
       envs directories : /Users/carolzhou/miniconda3/envs
                          /Users/carolzhou/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by shoemakerdr** [comment]
Not sure if you've solved this, but it looks like your test script should be called `test_multiphate` instead of `test-multiphate` based on the `setup.py` you supplied.
```
setup(name='test_multiphate',
version='0.1.14',
description='Phage annotation pipeline',
author='Carol Zhou',
author_email='zhou4@llnl.gov',
url='https://github.com/carolzhou/test_multiphate',
entry_points={
'console_scripts': [
'test_multiphate=test_multiphate.main:main',  <--
],
},
)
```

**Comment by carolzhou** [comment]
Tried that. It seems that Conda-build is changing  underscore to dash. Conda-build seems to have bugs. Why does it misinterpret these characters and reassign the script name? Maybe I’ll try again some time, but troubleshooting this has consumed too much of my time.

Sent from my iPhone

On May 20, 2019, at 9:36 AM, Derek Shoemaker <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if you've solved this, but it looks like your test script should be called test_multiphate instead of test-multiphate based on the setup.py you supplied.

setup(name='test_multiphate',
version='0.1.14',
description='Phage annotation pipeline',
author='Carol Zhou',
author_email='zhou4@llnl.gov<mailto:author_email='zhou4@llnl.gov>',
url='https://github.com/carolzhou/test_multiphate',
entry_points={
'console_scripts': [
'test_multiphate=test_multiphate.main:main',  <--
],
},
)

**Comment by msarahan** [comment]
I think you're getting mixed up between the package name (defined in setup.py), which is where this line comes from (as pip is processing setup.py):

> Building wheel for test-multiphate (setup.py): started

Keep in mind: conda-build isn't so much a build tool as it is an environment orchestration and shell script runner tool.  The only thing conda does to "build" things is to make note of what exists in the host environment before it runs a build script, and what exists after.  Anything new gets bundled up.

Changing underscores to dashes is definitely not something conda-build does.  It does treat them equivalently in some cases, for matching purposes, but it never changes them.  I think it would be most helpful if you look in your ``<miniconda root>/conda-bld/broken`` folder for the package that failed its tests.  You can use ``conda debug <path to your pkg>`` to have conda-build create a test environment just like the one that failed.  You can then poke around in that space to try to understand what's going wrong.  Are files all where you expect?  If you run python and try to import your package, does it work?  What are the contents of the entry point script in ``<test-pkg-prefix>/bin/test_multiphate``?
