### ISSUE TITLE
`create_default_packages` used by conda-build

### ISSUE THREAD

**Issue by fcollonval** [conda/conda-build#3444]
### Actual Behavior

If some packages are defined in conda configuration for `create_default_packages`, they are included in the environments created by `conda-build`. It seems they cannot be ignored when building a recipe. The option `--no-default-packages` is not available for `conda build`.

### Expected Behavior

I think to ensure reproductibility `create_default_packages` should be ignored by `conda build`. Or at least the option `--no-default-packages` should be available for it.

### Steps to Reproduce

```
conda config --add create_default_packages prospector
conda build <any available recipe>
```

The `prospector` package will be part of the packages used for the building environments.

##### `Output of conda info`

```
     active environment : base
    active env location : C:\Users\xxx\miniconda3
            shell level : 1
       user config file : C:\Users\xxx\.condarc
 populated config files : C:\Users\xxx\.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : C:\Users\xxx\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\xxx\miniconda3\pkgs
                          C:\Users\xxx\.conda\pkgs
                          C:\Users\xxx\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\xxx\miniconda3\envs
                          C:\Users\xxx\.conda\envs
                          C:\Users\xxx\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
Yeah, i hit this too, kinda like hitting a thorn ;)

**Comment by msarahan** [comment]
@marcelotrevisani not sure if you'd be interested in this one.  Should hopefully be a quick fix, but it's not always easy to change conda settings from conda-build.  The ``context`` object doesn't behave the way you might think, because it is an instance that effectively gets copied, so changing it doesn't necessarily affect conda.

I'm happy to help someone fix this, but can't do it myself.

**Comment by marcelotrevisani** [comment]
Sure, I will take a look at it! Thanks!
:)

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani not sure if you'd be interested in this one. Should hopefully be a quick fix, but it's not always easy to change conda settings from conda-build. The `context` object doesn't behave the way you might think, because it is an instance that effectively gets copied, so changing it doesn't necessarily affect conda.
> 
> I'm happy to help someone fix this, but can't do it myself.

But, what is the right decision here? Should I add the option ``--no-default-packages`` or ``conda build`` should ignore those packages added in ``create_default_packages``?

**Comment by lewisacidic** [comment]
Just ran into this annoying issue.  From what I can see, `conda build` should not take `create_default_packages` into account as this might introduce extra issues with the reproducibility of the builds.

**Comment by mingwandroid** [comment]
@jjhelmus we should address this one ASAP.
