### ISSUE TITLE
CONDA_BUILD_SYSROOT has no effect

### ISSUE THREAD

**Issue by tovrstra** [conda/conda-build#3452]
In the conda-build documentation (https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html), the following can be found:

*On macOS, you can use the equivalent compiler packages in conjunction with the standard MACOSX_DEPLOYMENT_TARGET environment variable and set the CONDA_BUILD_SYSROOT environment variable. This will specify a folder containing a macOS SDK. This achieves backwards compatability while still providing access to C++14 and C++1z.*

As far as I can tell, the `CONDA_BUILD_SYSROOT` environment variable has no effect. (It would have been a nice feature). The only way to get this to work reliably is to make a file `conda_build_config.yaml` as explained here: https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/

(Also typo: compatability)

File to be fixed: `conda-build/docs/source/resources/define-metadata.rst`

If understand this correctly, I wouldn't mind fixing this. Just let me know.

**Comment by tovrstra** [comment]
It seems that also the `conda_build_config.yaml` does not have any effect on my system. The compiler is still using the system SDK, e.g. `-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk` Is there a way to debug this?

Steps to reproduce (in an empty Guest account):

```bash
# Start in your home dir
cd

# Install miniconda
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
chmod +x miniconda.sh
./miniconda.sh -b
source ~/miniconda3/etc/profile.d/conda.sh
conda activate

# Install conda build
conda install conda-build conda-verify

# Get the SDK
curl  -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz -o MacOSX10.9.sdk.tar.xz
tar -xJf MacOSX10.9.sdk.tar.xz

# Get a recipe for testing
git clone https://github.com/conda-forge/cppcheck-feedstock.git
cd cppcheck-feedstock

# Write the conda_build_config.yaml file
printf "CONDA_BUILD_SYSROOT:\n  - ${HOME}/MacOSX10.9.sdk\n" > conda_build_config.yaml 

# Build the package
conda build recipe
```

I tested this on macOS High Sierra (10.13.6). In the output, I see the compiler is called with the wrong `-isysroot` argument, e.g. 

```
cd $SRC_DIR/build/externals/tinyxml && $BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++  -DCFGDIR="$PREFIX/share/Cppcheck" -I$SRC_DIR/build/externals/tinyxml -I$SRC_DIR/externals/tinyxml  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cppcheck-1.87 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wall -std=c++0x -Wextra -pedantic  -Wno-four-char-constants -Wno-missing-braces -Wno-missing-field-initializers -Wno-multichar -Wno-sign-compare -Wno-unused-function -Wno-long-long -O3 -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9   -o CMakeFiles/tinyxml_objs.dir/tinyxml2.cpp.o -c $SRC_DIR/externals/tinyxml/tinyxml2.cpp
```

**Comment by tovrstra** [comment]
This is a workaround:

Add a section to the `meta.yaml` file:

```yaml

build:
  # (keep what is already present in the build section.)
  script_env:
    - SDKROOT
```

Then export this variable right before conda build in the above steps:

```bash
export SDKROOT=${HOME}/MacOSX10.9.sdk
conda build
```

With that, the compiler is called with the right `-isysroot` argument:

```bash
cd $SRC_DIR/build/externals/simplecpp && $BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++  -DCFGDIR=\"$PREFIX/share/Cppcheck\" -I$SRC_DIR/build/externals/simplecpp -I$SRC_DIR/externals/simplecpp  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cppcheck-1.87 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wall -std=c++0x -Wextra -pedantic  -Wno-four-char-constants -Wno-missing-braces -Wno-missing-field-initializers -Wno-multichar -Wno-sign-compare -Wno-unused-function -Wno-long-long -O3 -DNDEBUG  -DNDEBUG -isysroot /Users/Guest/MacOSX10.9.sdk -mmacosx-version-min=10.9   -o CMakeFiles/simplecpp_objs.dir/simplecpp.cpp.o -c $SRC_DIR/externals/simplecpp/simplecpp.cpp
```

**Comment by mingwandroid** [comment]
CMake has (unfortunately) a turing complete programming 'language'.

This means that, depsite it coming with some named conventions, authors of CMakeLists.txt files and the like are free to avoid those conventions and so any complex one needs to be handled in its own unique way.

`CMAKE_OSX_SYSROOT` is the variable you should be using from build.sh, e.g.:

`-DCMAKE_OSX_SYSROOT=${CONDA_BUILD_SYSROOT}`

**Comment by tovrstra** [comment]
@mingwandroid  Thank you for the quick reply!

I understand now how it works. So when writing a recipe that is intended to work on OSX too, one should always make sure that `${CONDA_BUILD_SYSROOT}` is passed on to the build scripts in the appropriate way. (`conda-build` will not do that automatically somehow.)

Unless there is a specific way to achieve this, e.g. as for CMake, is it wise to add the following lines to the `script:` section in `meta.yaml`?

```yaml

build:
  script:
    - export CXXFLAGS="${CXXFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"  # [osx]
    - export CFLAGS="${CFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"  # [osx]
```

**Comment by mingwandroid** [comment]
No, you should call the CMake configuration command line with `-DCMAKE_OSX_SYSROOT=${CONDA_BUILD_SYSROOT}`, and should not need to mess around with `C{,XX}FLAGS`

**Comment by tovrstra** [comment]
Thank you. How should I achieve the same result when building a Python extension with distutils?

**Comment by mingwandroid** [comment]
Please look here: https://github.com/conda-forge/cppcheck-feedstock/blob/master/recipe/build.sh#L4

What are you trying to achieve here?

**Comment by tovrstra** [comment]
That still needs to be fixed. My question regarding the Python extension is for another recipe I'm working on.

**Comment by mingwandroid** [comment]
OK, I'm taking a quick look at this now.

**Comment by mingwandroid** [comment]
CMake/Python hook-up can be particularly tricky though. It is a fairly fluid sitation, I would say! I like how it is handled in https://github.com/lief-project/LIEF though. I was able to compile that for all OSes and even using VS2008 on Windows without trouble. It mixes C++, CMake and Python very well.

**Comment by mingwandroid** [comment]
For CMake, I have some WIP stuff to define some default shell variables (just bash arrays and a CMake toolchain file basically) for use with our compilers. It's not finished yet but I think once finished it will help to simplify, isolate and accelerate some things.

https://github.com/AnacondaRecipes/cmake-feedstock/tree/3.14.0/recipe

**Comment by tovrstra** [comment]
Thank you for all the pointers! I'll check them out soon.

**Comment by tovrstra** [comment]
I'm just adding one more pointer for those who come across the same issue when building a package with distutils or setuptools. From the source code, I would guess distutils expects `-i sysroot ...` to be set via `CFLAGS`. (This for the case one is not using CMake.) See https://github.com/python/cpython/blob/800d5cd75025876d79ab05980925a05d8e36b63d/Lib/distutils/unixccompiler.py#L265

Thanks for all the helpful comments!

**Comment by tovrstra** [comment]
@mingwandroid Sorry for bothering you once more with this: after some testing, I notice that `export CONDA_BUILD_SYSROOT=...` does not affect conda build, in line with the way I first formulated the issue. Is it correct that `conda_build_config.yaml` is the only way to control `CONDA_BUILD_SYSROOT` during the build phase? In that case, the following should still be fixed, I guess:

https://github.com/conda/conda-build/blame/6604ffae5de15c10b10f3004da4907751e15379d/docs/source/resources/define-metadata.rst#L844

**Comment by mingwandroid** [comment]
Well `conda-build` does set environment variables for those things and you are meant to use those in `build.sh`. Other than that it scrubs environment variables.

If you want to make a PR to clarify this then go ahead. I cannot think of a better term though.

**Comment by tovrstra** [comment]
Before making any changes, I'll be more specific on what confused me terribly, and got me trying something that did not work. The following sentence in the documentation is not very clear:

*On macOS, you can use the equivalent compiler packages in conjunction with the standard MACOSX_DEPLOYMENT_TARGET environment variable and set the CONDA_BUILD_SYSROOT environment variable. This will specify a folder containing a macOS SDK.*

The second part of the first sentence is thus `... you can ... set the CONDA_BUILD_SYSROOT environment variable.` To me this means that conda-build expects me to set `CONDA_BUILD_SYSROOT` before running `conda build`. It works the other way around, i.e, when the user runs `conda build`, it will set the environment variable `CONDA_BUILD_SYSROOT` before running the build script in the recipe.

**Comment by mingwandroid** [comment]
Yeah, I agree it should be improved so that it mentions that conda-build scrubs env vars and sets some according to the variant matrix declared in the `conda_build_config.yaml` file(s), or something like that! Thank you very much.

**Comment by tovrstra** [comment]
Good, I'll make a PR.
