### ISSUE TITLE
pyldd disagrees with ldd/otool

### ISSUE THREAD

**Issue by notestaff** [conda/conda-build#3458]
(master_env_v106_py36) 00:39  [npth-feedstock] $ conda inspect linkages npth
WARNING: pyldd disagrees with ldd/otool. This will not cause any
WARNING: problems for this build, but please file a bug at:
WARNING: https://github.com/conda/conda-build
WARNING: and (if possible) attach file /data/n10mc3/envs/master_env_v106_py36/lib/libnpth.so.0.1.2
WARNING:
ldd/otool gives:
('librt.so.1', '/lib64/librt.so.1')
('libpthread.so.0', '/lib64/libpthread.so.0')
('libc.so.6', '/lib64/libc.so.6')
pyldd gives:
('librt.so.1', '/lib64/librt.so.1')
('ld-linux-x86-64.so.2', '/lib64/ld-linux-x86-64.so.2')
('libc.so.6', '/lib64/libc.so.6')
('libpthread.so.0', '/lib64/libpthread.so.0')

Diffs
set()
Diffs
{('ld-linux-x86-64.so.2', '/lib64/ld-linux-x86-64.so.2')}
npth
----

system:
    libc.so.6 (/lib64/libc.so.6)
    libpthread.so.0 (/lib64/libpthread.so.0)
    librt.so.1 (/lib64/librt.so.1)

not found:

**Comment by notestaff** [comment]
[libnpth.so.0.1.2.gz](https://github.com/conda/conda-build/files/3001086/libnpth.so.0.1.2.gz)

**Comment by aditya-chaturvedi** [comment]
I got the same warning on Py3.6 conda env - 

`$ conda inspect linkages --show-files -n db-jlab python
WARNING: pyldd disagrees with ldd/otool. This will not cause any
WARNING: problems for this build, but please file a bug at:
WARNING: https://github.com/conda/conda-build
WARNING: and (if possible) attach file ~/anaconda/envs/db-jlab/lib/libpython3.6m.dylib
WARNING: 
ldd/otool gives:
('libpython3.6m.dylib', '@rpath/libpython3.6m.dylib')
('libSystem.B.dylib', '/usr/lib/libSystem.B.dylib')
pyldd gives:
('libSystem.B.dylib', '/usr/lib/libSystem.B.dylib')

Diffs
{('libpython3.6m.dylib', '@rpath/libpython3.6m.dylib')}
Diffs
set()
python`

[libpython3.6m.dylib.zip](https://github.com/conda/conda-build/files/3970500/libpython3.6m.dylib.zip)
