### ISSUE TITLE
CFLAGS and CXXFLAGS set on macOS causes trouble

### ISSUE THREAD

**Issue by tovrstra** [conda/conda-build#3481]
I don't know why `conda-build` sets `CXXFLAGS` and `CFLAGS` on macOS. There is probably a good reason. The behavior is documented here: https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html However, these variables cause unpleasant and difficult-to-solve build failures, as explained below. It makes me wonder why these variables are set on macOS? Is it worth the trouble?

I've been puzzled for a few weeks by a conda package build, which only failed on OSX. (See https://travis-ci.com/theochem/cellcutoff/builds/108257061) This is a simple C++ library compiled with CMake. It turned out that the problem was caused by `CXXFLAGS` being set by `conda-build` on macOS (and not on Linux). After discovering the cause, it was easy to fix, but figuring it out was a little nightmare. I'll describe the problem here, in the hope that it may help others falling into the same rabbit hole:

* The initial symptom was that `-isystem $PREFIX/include` was missing from the clang compiler arguments during the package build. This made it impossible to include headers from dependencies installed by conda.

* The reason for this problem is that CMake incorrectly detects `$PREFIX/include` as one of the compiler's implicit include directories. CMake then strips all implicit include directories it can find from the `-I` arguments it uses later on.

* The script CMake uses to detect the implicit include dirs, calls the compiler with `CXXFLAGS`. Because `conda-build` sets `CXXFLAGS` to a value containing an argument `-I$PREFIX/include`, the compiler reports this directory as one of the include dirs. CMake then decides it must be an implicit include directory.

In general, adding rudendant `-I...` arguments to `CXXFLAGS` before calling CMake, will have the opposite effect due to the above mechanism: these include paths will be forcibly omitted when compiling the source code. The same could happen with `CFLAGS`, maybe also `FFLAGS`.

**Comment by msarahan** [comment]
conda-build does not set CFLAGS and friends.  The compiler activation scripts set CFLAGS.  https://github.com/AnacondaRecipes/aggregate/blob/master/clang/build.sh

**Comment by tovrstra** [comment]
@msarahan Thanks for explaining. Why do I only see this problem on macOS? The activation scripts for clang and gnu compilers are very similar:

https://github.com/AnacondaRecipes/aggregate/blob/master/clang/activate-clang%2B%2B.sh#L84

https://github.com/AnacondaRecipes/aggregate/blob/master/ctng-compilers-activation-feedstock/recipe/activate-g%2B%2B.sh#L84

(There are some differences, but these don't seem relevant to the problem I ran into.)

**Comment by tovrstra** [comment]
Related issue: https://gitlab.kitware.com/cmake/cmake/issues/17966
