### ISSUE TITLE
Conda-build deactivating package before running tests, causing tests to fail

### ISSUE THREAD

**Issue by aguzmanballen** [conda/conda-build#3484]
### Actual Behavior

On Linux, icc-activation-recipe that was written works perfectly. I added `echo "Activation"` and `echo "Deactivation"` for respective activation scripts. When I run conda-build, I only see "Activation" before it runs the one-line compiler test. On Windows, same thing happens, only I see it say "Deactivation" right before running the tests, and the test fails because it cannot find icl.exe, which of course is because the icc-activation package was deactivated right before the test.

### Expected Behavior

When I run conda-build on Linux and Windows, I should only see "Activation" before it runs the one-line compiler test. 

### Steps to Reproduce

I just run the following: conda-build icc-activation-recipe -m satconfig\cbc_global.yaml -m satconfig\cbc_icc.yaml. 

### Output of conda info
Linux:
     active environment : None
       user config file : /nfs/site/home/aguzmanb/.condarc
 populated config files :
          conda version : 4.6.12
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /localdisk/work/aguzmanb/Development/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /localdisk/work/aguzmanb/Development/miniconda3/pkgs
                          /nfs/site/home/aguzmanb/.conda/pkgs
       envs directories : /localdisk/work/aguzmanb/Development/miniconda3/envs
                          /nfs/site/home/aguzmanb/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.12 requests/2.21.0 CPython/3.7.3 Linux/4.4.0-141-generic ubuntu/16.04.5 glibc/2.23
                UID:GID : 11574275:22002
             netrc file : None
           offline mode : False

Windows:
C:\Users\aguzmanb\Development\SAT>conda info

     active environment : None
       user config file : C:\Users\aguzmanb\.condarc
 populated config files : C:\Users\aguzmanb\.condarc
          conda version : 4.6.12
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : C:\Users\aguzmanb\Development\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\aguzmanb\Development\Miniconda3\pkgs
                          C:\Users\aguzmanb\.conda\pkgs
                          C:\Users\aguzmanb\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aguzmanb\Development\Miniconda3\envs
                          C:\Users\aguzmanb\.conda\envs
                          C:\Users\aguzmanb\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.12 requests/2.21.0 CPython/3.6.8 Windows/2012ServerR2 Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False

**Comment by msarahan** [comment]
The activation stuff is pretty similar between windows and unix: 

https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1935-L1946

It would help if you could show us the contents of the test env vars script that gets written to above.  https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1930-L1931

That code uses the "old" style activation.  It should work, but it differs from how we are activating the build/host envs.  It might be better for us to go through similar code for the build-time activation.  It's more complicated, because it has to support activating both host and build envs.

Activation stuff branching into platform specificity:
https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1157-L1169

Unix addition:
https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1095-L1154

Windows addition:
https://github.com/conda/conda-build/blob/master/conda_build/windows.py#L210-L256

**Comment by aguzmanballen** [comment]
This is all that appears in that test env vars script (and I used import pdb to find that it runs activate and deactivate all in just one command in conda_build's utils.py's self._execute(*args, **kwargs)) :
```
call "C:\Users\aguzmanb\Development\Miniconda3\Scripts\activate.bat" "C:\Users\aguzmanb\Development\Miniconda3\conda-bld\icc-activation_1556057687139\_test_env"
IF %ERRORLEVEL% NEQ 0 exit 1
```

Very strange that line is the culprit; I don't see any "deactivate" in here. All that line seems to do at the end of the day is call Miniconda3\condabin\conda.bat, passing the user parameter. Does this help at all?

**Comment by aguzmanballen** [comment]
@msarahan Just a friendly ping :) Does the comment I wrote a few days ago help you understand where the issue can be coming from?

**Comment by aguzmanballen** [comment]
Oh nooo, it looks like I was copying the deactivate script to activate.d! Silly, silly me. I will close this ticket now. Thanks Michael!
