### ISSUE TITLE
Conda build variant doesn't with different python versions & zip_keys

### ISSUE THREAD

**Issue by SumeetJindal** [conda/conda-build#3489]
### Actual Behavior
Hi, I am trying to create two conda build versions using python 2.7 and 3.6 
Here is the conda_build_config:

python:
   \- 2.7.13
   \- 3.6.2

pyodbc:
   \- 3.0.10
  \- 4.0.24

future:
  \- 0.16.0
  \- 0.17.0

zip_keys:
   \- pyodbc
   \- future
   \- python

META.YAML:

package:
  name: my_package_example
  version: "1.0a0"

source:
  path: ..

build:
  noarch: python

requirements:
  build:
    \- python
    \- pyodbc
    \- future

  run:
    \- {{ pin_compatible('python', min_pin='x.x.x', max_pin='x.x') }}
    \- {{ pin_compatible('pyodbc', min_pin='x.x.x', max_pin='x.x') }}
    \- {{ pin_compatible('future', min_pin='x.x.x', max_pin='x.x') }}

test:
  files:
    \- pylintrc
  requires:
    \- pytest ==3.1.1
    \- pylint ==1.6.4

"conda build . "should generate two conda versions but it only generates one. 

### Expected Behavior
If I use the same python version in conda_build_config.yaml, then it generates two conda versions

python:
   \- 2.7.13
   \- 2.7.13
one for {pyodbc: 3.0.10 , future : 0.16.0} and one for {pyodbc: 4.0.24, future : 0.17.0} 

but it doesn't work for different python versions

### Steps to Reproduce

I have tried all the permutation combination for build and run section under requirement, nothing seems to be working.

##### `Output of conda info`

```
```

**Comment by msarahan** [comment]
I think zip_keys should be a list of lists:

```
zip_keys:
- 
  - pyodbc
  - future
  - python
```

**Comment by SumeetJindal** [comment]
Thanks. I tried that as well but it didn't work.

**Comment by nehaljwani** [comment]
@SumeetJindal Remove: `noarch: python` and it will build 2 conda packages.

**Comment by SumeetJindal** [comment]
Thanks!
