### ISSUE TITLE
Incorrect handling of unicode in git log files

### ISSUE THREAD

**Issue by jochym** [conda/conda-build#349]
The binstar build service crashes on UTF git log entries (https://github.com/jochym/Elastic.git):

The output from `git log -n1` reads:

---

git log -n1
commit caf4906ee99fa816a0e14114815d42e7cf6f7d2d
Author: Paweł T. Jochym pawel.jochym@ifj.edu.pl
Date:   Mon Feb 9 00:53:34 2015 +0100

```
Build number.
```

---

The output from conda-build (1.11.0-py27_0):

---

Initialized empty Git repository in /opt/miniconda/conda-bld/git_cache/__github.com_jochym_Elastic.git/
Initialized empty Git repository in /opt/miniconda/conda-bld/work/.git/
==> git log -n1 <==

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/opt/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 112, in main
    args_func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 321, in args_func
    args.func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 280, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 347, in build
    source.provide(m.path, m.get_section('source'))
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 250, in provide
    git_source(meta, recipe_dir)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 134, in git_source
    git_info()
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 162, in git_info
    print(stdout + u'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 60: ordinal not in range(128)
command exited with status 1

**Comment by asmeurer** [comment]
The workaround is to use Miniconda3.

**Comment by jochym** [comment]
Not an option for me. Another option is to remove my first name from the git log message... ;)

**Comment by asmeurer** [comment]
Note that you can still build Python 2 packages with Miniconda3 using `conda build --python 2.7 recipe`. The only difference between Miniconda2 and Miniconda3 is the version of Python that conda runs in.

**Comment by asmeurer** [comment]
I am unable to reproduce this.

**Comment by kpurdon** [comment]
I was able to replicate this:

```
git log -n1
commit 4168e55b49e4c0a86c2d5a47d59be5d439f6b8c5
Author: Jenkins <jenkins@vverglas.apps.int.nsidc.org>
Date:   Wed Mar 25 08:17:58 2015 -0600

    Bump version: 1.0.7dev15 → 1.0.7dev16
```

Note the --> character in the version bump string. I was able to correct the issue by changing the default commit string in bumpversion. (removing the -->)

conda 3.10.0, conda-build 1.11.0, Python 2.7.9, Ubuntu 14.04

**Comment by jochym** [comment]
The option with conda3 is good. I am only not sure it will work on binstar CI build system.

**Comment by mmarchetti** [comment]
We have the same problem causing binstar builds to fail. https://binstar.org/wakari/wakari-app-ipython/builds/6/0. I don't think using python3 is an option for us.

```
128  File "/home/binstar/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 163, in git_info
129    print(stdout + u'\n')
130 UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 83: ordinal not in range(128)
131 command exited with status 1
```

**Comment by asmeurer** [comment]
I think the fix here is to remove the `u` from the string literals. But I want to be sure because this function has a history of issues with Unicode characters. 

And again, you can still build Python 2 packages using Miniconda 3 using the `--python=2.7` flag to conda-build.

**Comment by asmeurer** [comment]
@mmarchetti I'm not able to reproduce this. Can you put a `conda info` call at the top of your binstar build?

**Comment by gdementen** [comment]
For the record, this is probably related to #170, #360, #456 (and associated PR #458)  and 
https://github.com/conda/conda/issues/1486

**Comment by gdementen** [comment]
My own issue is the same as https://github.com/conda/conda/issues/1486, but since this issue seems to be the most recent, open issue on conda-build (which is where the bug is, I figured this would be the most appropriate place to comment -- sorry if this is not the case).

Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : 1.17.0
       python version : 3.4.1.final.0

I tracked it down to git_info code (in source.py).

The problem is that on my Windows 7 box (and I think it is pretty much the default for all Windows boxes, but I could be wrong) locale.getpreferredencoding() returns 'cp1252', however, the string from git is encoded in 'utf8' (and I think that is the default for all recent versions of Git for Windows) and sys.stdout.encoding is 'cp437' for cmd.exe. What this means is that after:
```python
        encoding = locale.getpreferredencoding() or 'utf-8'
        stdout = stdout.decode(encoding, 'ignore')
```
stdout contains garbage, and, below:
```python
            print(stdout + u'\n')
```
crashes because it cannot encode the garbage to 'cp437'.

The best (read: the least horrible) solution **on Windows** is IMO:
```python
        stdout = stdout.decode('utf8', 'ignore')
```
and
```python
        encoding = sys.stdout.encoding
        print((stdout + u'\n').encode(encoding, 'ignore'))
```
which would produce the expected result in the default case and would produce garbage but would not crash in case of encoding problems, including the current bug report.

As a side note, I usually prefer "replace" to "ignore", because it makes it slightly more obvious that something was wrong, yet it does not crash...

**Comment by gdementen** [comment]
@asmeurer, @pitrou: do you want a PR with this?

**Comment by gdementen** [comment]
Oh well, this does not look good either because print() is too clever and does not output raw bytes even if given a byte string. Grrrr...

**Comment by pitrou** [comment]
If you want to output a byte string, you have to use `sys.stdout.buffer.write`. That said, I'm not sure what the purpose is here: if it's simply an informative message, it can just use a "safe" representation.

**Comment by gdementen** [comment]
the purpose is to be able to build on Windows (it currently crashes).

**Comment by pitrou** [comment]
I meant the purpose of printing out the result of "git log".

**Comment by gdementen** [comment]
oups :). Yeah, well, that seems to be indeed just an informative message, that's why I am not too concerned about using ('ignore' or 'replace') in encoding/decoding operations.

**Comment by asmeurer** [comment]
If you know how to actually fix this please send a PR.

**Comment by gdementen** [comment]
I know
* how to make it "not crash" in all cases (for encoding issues) (by using
'replace' or 'ignore') on encode. That's probably a win in all cases.
* how to make it display proper stuff on my box (by using 'utf8' in all
cases instead of getpreferredencoding())
The problem is that it might display gibberish on other boxes, possibly
some which are working now. Are you ready to take that risk or not?
Alternatively, we could try to decode utf8 without 'ignore' and if it
raises, try getpreferredencoding(). But there is still the risk of uft8
being a bad encoding but returning gibberish instead of raising. What do
you think?

**Comment by asmeurer** [comment]
Not crashing is more important than showing the right thing.

**Comment by goanpeca** [comment]
Hi @gdementen do you plan to submit a PR on this :-) ?

I am also experiencing problems...

**Comment by gdementen** [comment]
Yes, but it will probably take a few days... so if you want to tackle this,
feel free... just tell me if you plan to do it.

**Comment by mcg1969** [comment]
PING. We need a solution here, if for no other reason than Anaconda's own build workers suffer from it. (And they're not going to be moving to Python 3, I don't think.)

**Comment by msarahan** [comment]
@mcg1969 have you tried this code?  Does it fix your issue?  I'm happy to merge it - the code looks fine at a glance.

**Comment by pitrou** [comment]
> And they're not going to be moving to Python 3, I don't think

They should...

**Comment by mcg1969** [comment]
@msarahan, are you referring to gdementen's PR? No I haven't. I'll give it a go and report there.

**Comment by msarahan** [comment]
I don't think it's actually a PR, yet.  You should still be able to pull it in, though.  I have asked him to submit it.

**Comment by mcg1969** [comment]
This isn't it? https://github.com/conda/conda-build/pull/688
(But it's not working for me, no.)

**Comment by msarahan** [comment]
Sorry, I missed that.  Thanks for pointing it out.

**Comment by gdementen** [comment]
@msarahan and other owners:  what should I do about my PR? I really want to have this issue fixed once and for all as it is very painful for me. I am ready to update my PR as you see fit, but I don't really know in what direction. Depending on how quickly you answer, I might be unavailable for a few weeks (my wife will give birth any day now).

**Comment by msarahan** [comment]
Yikes! That's motivation for us!  I want to work with @mcg1969 today to
figure out his error.  Assuming that it is separate and not something that
can be improved in this PR, I will merge.  If there is any test you can
add, that would help.

If you do go AFK for a while, please give us a heads up, and we'll try to
finish up whatever is left.
