### ISSUE TITLE
ignore_run_exports warnings: is it safe to rely on them?

### ISSUE THREAD

**Issue by notestaff** [conda/conda-build#3494]
When building a conda-forge package, I get these warnings:

```
WARNING (git-annex): dso library package defaults::libstdcxx-ng-8.2.0-hdf63c60_1 in requirements/run but it is not used (i.e. it is ov\
erdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (git-annex): run-exports library package conda-forge::sqlite-3.26.0-h67949de_1001 in requirements/run but it is not used (i.e.\
 it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (git-annex): run-exports library package conda-forge::dbus-1.13.6-he372182_0 in requirements/run but it is not used (i.e. it i\
s overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

Are there situations where it would _not_ be a good idea to add the packages causing the warnings to ignore_run_exports?  Thanks!

**Comment by mingwandroid** [comment]
> Are there situations where it would not be a good idea to add the packages causing the warnings to ignore_run_exports? Thanks!

Most likely you don't want to use `ignore_run_exports` on these. Instead you probably want to remove them from the `requirements/hosts` section, unless you are sure that either 1. the library is being statically linked or 2. you are sure that something other than shared libraries are depended upon by your package and you are happy with that.

Do you have a link to your recipe?

**Comment by notestaff** [comment]
Yes, the recipe is https://github.com/conda-forge/git-annex-feedstock

**Comment by mingwandroid** [comment]
I tried to build it but ran into:
```
--  While building package Cabal-2.4.1.0 using:
      /opt/conda/conda-bld/git-annex_1556976415389/work/stack_root/setup-exe-cache/x86_64-linux-gmp4/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.2 --builddir=.stack-work/dist/x86_64-linux-gmp4/Cabal-2.2.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)
    Logs have been written to: /opt/conda/conda-bld/git-annex_1556976415389/work/.stack-work/logs/Cabal-2.4.1.0.log
```

Going to try with more memory. This seems to be building all of GHC though, is that expected? Do we not have a GHC we can depend upon instead?

**Comment by mingwandroid** [comment]
Here is the error information that I get; it is different from yours. Mine doesn't complain about `dbus`. `sqlite` is not used because `persistent-sqlite-2.9.2` bundles its own `sqlite` C code, so you need to remove that. Am I correct in assuming you added `libxml2` due to [this](http://git-annex.branchable.com/install/fromsource/#comment-352db5832a815f24ac090f791586537b) comment? That comment pertains to macOS only. Also, I see no references to `xml-sax` in the source code these days so the right thing to do is to remove this dependency.

```
   INFO (git-annex,bin/git-annex): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libm.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_1
   INFO (git-annex,bin/git-annex): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_1
   INFO (git-annex,bin/git-annex): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libdl.so.2 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_1
   INFO (git-annex,bin/git-annex): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_1
   INFO (git-annex,bin/git-annex): Needed DSO lib/libmagic.so.1 found in conda-forge::libmagic-5.36-h14c3975_0
   INFO (git-annex,bin/git-annex): Needed DSO x86_64-conda_cos6-linux-gnu/sysroot/lib/librt.so.1 found in CDT/compiler package conda-forge::gcc_impl_linux-64-7.3.0-habb00fd_1
   INFO (git-annex,bin/git-annex): Needed DSO lib/libz.so.1 found in conda-forge::zlib-1.2.11-h14c3975_1004
   INFO (git-annex,bin/git-annex): Needed DSO lib/libgmp.so.10 found in conda-forge::gmp-6.1.2-hf484d3e_1000
  ERROR (git-annex): run-exports library package conda-forge::sqlite-3.26.0-h67949de_1001 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
  ERROR (git-annex): run-exports library package conda-forge::libxml2-2.9.9-h13577e0_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (git-annex): dso library package defaults::libstdcxx-ng-8.2.0-hdf63c60_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
overdepending check failed
```

**Comment by mingwandroid** [comment]
> Are there situations where it would not be a good idea to add the packages causing the warnings to ignore_run_exports? Thanks!

Has this been answered to your satisfaction? Do you have questions still about these checks? I'm happy to answer them if you have.

**Comment by notestaff** [comment]
@mingwandroid yes, thanks a lot.

"This seems to be building all of GHC though" -- it uses Haskell 'stack' tool to download a GHC binary distribution, and then downloads many dependencies from Hackage, some of which it locally compiles; but it does not build GHC itself.  However, if git-annex starts requiring a more recent GHC, I do have to build it from scratch ( see https://github.com/conda-forge/git-annex-feedstock/pull/44 ).  Ideally of course there'd be a conda GHC package we could depend on, but I haven't been able to make that work, despite much trying.   If someone with better knowledge of GHC/conda-forge could make that work, that'd be great.
