### ISSUE TITLE
CRAN skeleton fails for GitHub pkgs that link to multiple Rcpp pkgs

### ISSUE THREAD

**Issue by jdblischak** [conda/conda-build#3499]
### Actual Behavior

When I try to create a recipe for an R package on GitHub that links to RcppGSL, it fails with `KeyError: 'cached_path'`, which is generated by the line below:

https://github.com/conda/conda-build/blob/63b1f0b98cfdff96e389e5015ba72b67ba06cc22/conda_build/skeletons/cran.py#L1171-L1172

I am using `conda-build 3.17.8`.

### Expected Behavior

I think it should create a recipe.

### Steps to Reproduce

To reproduce the error, try to create a recipe for any R package on GitHub that links to RcppGSL. Two examples are [mashr](https://github.com/stephenslab/mashr/blob/master/DESCRIPTION#L35) and [coga](https://github.com/ChaoranHu/coga/blob/master/DESCRIPTION#L22).

```
conda skeleton cran https://github.com/stephenslab/mashr
conda skeleton cran https://github.com/ChaoranHu/coga
```

In contrast, none of the following situations generates this error:

```
# An R package on GitHub with no compiled code
conda skeleton cran https://github.com/yihui/knitr
# An R package on GitHub that links to Rcpp
conda skeleton cran https://github.com/r-lib/fs
# An R package on CRAN that links to RcppGSL
conda skeleton cran r-coga
```

## Details

<details>
  <summary>Complete error message</summary>
<pre>
$ conda skeleton cran https://github.com/stephenslab/mashr
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Fetching metadata from https://cran.r-project.org
/home/jdb-work/miniconda3-conda-forge/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Parsing input package https://github.com/stephenslab/mashr:
.. name: mashr location: https://github.com/stephenslab/mashr new_location: /home/jdb-work/repos/jdb-conda/recipes/r-mashr
Making/refreshing recipe for mashr
Cloning into '/home/jdb-work/miniconda3-conda-forge/conda-bld/skeleton_1557407384282/work'...
done.
checkout: 'HEAD'
Your branch is up to date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit afe65b585b8067b51d52a6cd6ba776eb444c77e7
Author: Peter Carbonetto <peter.carbonetto@gmail.com>
Date:   Mon May 6 14:40:38 2019 -0500

    Updated pkgdown site.

==> git describe --tags --dirty <==

v0.2-11-19-gafe65b5

==> git status <==

On branch _conda_cache_origin_head
Your branch is up to date with 'origin/_conda_cache_origin_head'.

nothing to commit, working tree clean

Using tag v0.2-9
Note: checking out 'v0.2-9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b64a851 update docs

Leaving build/test directories:
  Work:
 /home/jdb-work/miniconda3-conda-forge/conda-bld/skeleton_1557407384282/work 
  Test:
 /home/jdb-work/miniconda3-conda-forge/conda-bld/skeleton_1557407384282/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/jdb-work/miniconda3-conda-forge/conda-bld/skeleton_1557407384282/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac 
  Build:
source activate  /home/jdb-work/miniconda3-conda-forge/conda-bld/skeleton_1557407384282/_build_env 

Traceback (most recent call last):
  File "/home/jdb-work/miniconda3-conda-forge/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/home/jdb-work/miniconda3-conda-forge/lib/python3.6/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/jdb-work/miniconda3-conda-forge/lib/python3.6/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "/home/jdb-work/miniconda3-conda-forge/lib/python3.6/site-packages/conda_build/api.py", line 289, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/home/jdb-work/miniconda3-conda-forge/lib/python3.6/site-packages/conda_build/skeletons/cran.py", line 1172, in skeletonize
    with tarfile.open(available['source']['cached_path']) as tf:
KeyError: 'cached_path'

</pre>
</details> 

<details>
  <summary>Output of conda info</summary>
<pre>
$ conda info

     active environment : None
       user config file : /home/jdb-work/.condarc
 populated config files : /home/jdb-work/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : /home/jdb-work/miniconda3-conda-forge  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/jdblischak/linux-64
                          https://conda.anaconda.org/jdblischak/noarch
          package cache : /home/jdb-work/miniconda3-conda-forge/pkgs
                          /home/jdb-work/.conda/pkgs
       envs directories : /home/jdb-work/miniconda3-conda-forge/envs
                          /home/jdb-work/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Linux/4.15.0-48-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
</pre>
</details>

**Comment by jdblischak** [comment]
**Update:** I don't think it is specific to RcppGSL. Now I think it might be anytime that a library links to more than just Rcpp.

As an example, a previous version of mashr does not link to RcppGSL. Only to Rcpp and RcppArmadilo. This still fails.

```
conda skeleton cran https://github.com/stephenslab/mashr --git-tag v0.2-9
```

https://github.com/stephenslab/mashr/blob/v0.2-9/DESCRIPTION#L26

**Comment by aksarkar** [comment]
This still happens on conda-build version 3.18.11

```
$ conda skeleton cran https://github.com/stephenslab/mashr --git-tag v0.2-9
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Parsing input package https://github.com/stephenslab/mashr:
.. name: mashr location: https://github.com/stephenslab/mashr new_location: /scratch/midway2/aksarkar/r-mashr
Making/refreshing recipe for mashr
Cloning into '/scratch/midway2/aksarkar/miniconda3/conda-bld/skeleton_1581543024409/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit 8ba5bea7723e933ec5f8e98754a197a6efb05cf7
Author: Gao Wang <gaow@uchicago.edu>
Date:   Sun Feb 9 18:53:06 2020 -0500

    Ignore attribute check for symmetric matrix

==> git describe --tags --dirty <==

v0.2-11-30-g8ba5bea

==> git status <==

Note: checking out 'v0.2-9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b64a851... update docs

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
nothing to commit, working tree clean

Reading package metadata from /scratch/midway2/aksarkar/miniconda3/conda-bld/skeleton_1581543024409/work/DESCRIPTION

Leaving build/test directories:
  Work:
 /scratch/midway2/aksarkar/miniconda3/conda-bld/skeleton_1581543024409/work 
  Test:
 /scratch/midway2/aksarkar/miniconda3/conda-bld/skeleton_1581543024409/test_tmp 
Leaving build/test environments:
  Test:
source activate  /scratch/midway2/aksarkar/miniconda3/conda-bld/skeleton_1581543024409/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla 
  Build:
source activate  /scratch/midway2/aksarkar/miniconda3/conda-bld/skeleton_1581543024409/_build_env 


Traceback (most recent call last):
  File "/scratch/midway2/aksarkar/miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/scratch/midway2/aksarkar/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/scratch/midway2/aksarkar/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "/scratch/midway2/aksarkar/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 290, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/scratch/midway2/aksarkar/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/cran.py", line 1230, in skeletonize
    with tarfile.open(available['source']['cached_path']) as tf:
KeyError: 'cached_path'
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/aksarkar/.condarc
 populated config files : /home/aksarkar/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.5.final.0
       virtual packages : __glibc=2.17
       base environment : /scratch/midway2/aksarkar/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /scratch/midway2/aksarkar/miniconda3/pkgs
                          /home/aksarkar/.conda/pkgs
       envs directories : /scratch/midway2/aksarkar/miniconda3/envs
                          /home/aksarkar/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.5 Linux/3.10.0-957.12.2.el7.x86_64 scientific/7.4 glibc/2.17
                UID:GID : 577522659:577522659
             netrc file : None
           offline mode : False
```

**Comment by kfuku52** [comment]
This error still occurs in conda-build 3.21.4.
```
(r3) Singularity gfe:~/docker_img> conda skeleton cran https://github.com/stephenslab/mashr --git-tag v0.2-9
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Parsing input package https://github.com/stephenslab/mashr:
.. name: mashr location: https://github.com/stephenslab/mashr new_location: /home/kef74yk/docker_img/r-mashr
Making/refreshing recipe for mashr
Cloning into bare repository '/opt/conda/conda-bld/git_cache/github.com/stephenslab/mashr'...
remote: Enumerating objects: 6415, done.
remote: Counting objects: 100% (720/720), done.
remote: Compressing objects: 100% (472/472), done.
remote: Total 6415 (delta 487), reused 415 (delta 244), pack-reused 5695
Receiving objects: 100% (6415/6415), 49.46 MiB | 19.67 MiB/s, done.
Resolving deltas: 100% (4466/4466), done.
Cloning into '/opt/conda/conda-bld/skeleton_1623674362099/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/master'.
==> /usr/bin/git log -n1 <==

commit 195b2cda69297f0c9717705f50f04f75d98de6aa
Author: Peter Carbonetto <peter.carbonetto@gmail.com>
Date:   Mon May 24 09:14:59 2021 -0500

    Bumped up version.

==> /usr/bin/git describe --tags --dirty <==

0.2.49-2-g195b2cd

==> /usr/bin/git status <==

Note: checking out 'v0.2-9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b64a851... update docs

On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

Reading package metadata from /opt/conda/conda-bld/skeleton_1623674362099/work/DESCRIPTION

Leaving build/test directories:
  Work:
 /opt/conda/conda-bld/skeleton_1623674362099/work 
  Test:
 /opt/conda/conda-bld/skeleton_1623674362099/test_tmp 
Leaving build/test environments:
  Test:
source activate  /opt/conda/conda-bld/skeleton_1623674362099/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:
source activate  /opt/conda/conda-bld/skeleton_1623674362099/_build_env 


Traceback (most recent call last):
  File "/opt/conda/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 277, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/skeletons/cran.py", line 1253, in skeletonize
    with tarfile.open(available['source']['cached_path']) as tf:
KeyError: 'cached_path'
```
