### ISSUE TITLE
test/source_files recursive glob doesn't work

### ISSUE THREAD

**Issue by teake** [conda/conda-build#3504]
The following recipe snippet doesn't work as I expect:
```yaml
test:
  source_files:
    - tests/**/*.py
```
Namely, it doesn't find the files of the form `tests/test_something.py`, but does find files similar to `tests/subdir/test_somethingelse.py`.

This is because the code in question, https://github.com/conda/conda-build/blob/63b1f0b98cfdff96e389e5015ba72b67ba06cc22/conda_build/build.py#L396
uses the stdlib glob (without recursion):
https://github.com/conda/conda-build/blob/63b1f0b98cfdff96e389e5015ba72b67ba06cc22/conda_build/build.py#L8
There's a PR that introduced glob2 (#2146) but that somehow overlooked the above line.

I myself am bit hesitant to write a PR that simply changes the above import to glob2 since it also touches other glob statements in `build.py`. Hence this issue.

As a side note, there's a generic `glob` definition in `conda-build/conda_build/utils.py` that turns recursion on by default. But using that won't work for Python < 3.5 since glob recursion was introduced in the stdlib in 3.5.

**Comment by msarahan** [comment]
The function in utils.py should fall back to glob2 on python 2, I believe.  https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L51-L75

The right fix here is to change build.py to import the glob function from utils.py

Is python <3.5 even relevant anymore?  I don't think so.  Everything older than 3.5 is already EOL, and Anaconda and Conda-forge don't even build packages for 3.5 anymore.  https://devguide.python.org/#status-of-python-branches
