### ISSUE TITLE
Git clone fails for repo with submodule with relative URL

### ISSUE THREAD

**Issue by wulmer** [conda/conda-build#3505]
### Actual Behavior

We recently switched to relative URLs for our Git submodules to make them more easily accessible through either HTTPS or SSH clone URLs.

In case of a conda recipe for such a repo which uses the SSH URL, conda build fails with a strange error message:

```
Relative submodule venv-tools found: url is ../../proj/myrepo.git, submod_mirror_dir is C:\path\to\conda-bld\git_cache\git@server_7999\proj\myrepo.git
fatal: repository '../../proj/myrepo.git' does not exist
fatal: repository '../../proj/myrepo.git' does not exist
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['C:\\Program Files\\Git\\cmd\\git.exe', 'clone', '--mirror', '../../proj/myrepo.git', 'C:\\path\\to\\conda-bld\\git_cache\\git@server_7999\\proj\\myrepo.git']' returned non-zero exit status 128.
Failed to download or patch source. Please see build log for info.
```

I verified that manually cloning the repo with the submodules works as expected (which was the reason why we switched to relative submodule URLs).

### Expected Behavior

Cloning this repo via `conda build` should succeed as it does with a manual `git clone` (including submodules).

### Steps to Reproduce

1. Create a repo and add a submodule with a relative URL (you might have to manually edit the `.gitmodules` file after adding the submodule, because some tools require an absolute submodule URL). The relative URL should not contain a protocol, just a path, e.g. `../../other/proj.git`.
2. Create a conda recipe for this repo and use the SSH URL for `git_src`.
3. Try to build this recipe with `conda build`.
4. Conda will fail to clone the submodule as it isn't able to correctly derive the checkout URL for the submodule.

### Analysis

The reason why this fails (and why it succeeds with HTTPS URLs) is that the `urljoin` method, called in `conda_build.source`, see
https://github.com/conda/conda-build/blob/ecd8508e2108136054e836b171068c34782ba003/conda_build/source.py#L276) 
doesn't properly treat `ssh://` URLs (or at least not how Git treats them).

The `urljoin` function treats SSH URLs like they don't support relative paths (which they normally don't do), when replacing the `ssh://` by `https://`, everything works fine.

See these examples:

```python
In [3]: from urllib.parse import urljoin

In [4]: urljoin('ssh://git@server/some/subdir.git', '../otherdir.git')
Out[4]: '../otherdir.git'

In [5]: urljoin('https://git@server/some/subdir.git', '../otherdir.git')
Out[5]: 'https://git@server/otherdir.git'
```

The treatment of the different protocols is defined by some feature flags, namely `uses_relative` and `uses_netloc` inside `urllib.parse` module.

A (temporary) workaround is to monkeypatch the `urllib.parse` module by running:

```python
import urllib.parse
urllib.parse.uses_relative.append('ssh')
urllib.parse.uses_netloc.append('ssh')
```

I am not sure how to proceed: Patching the stdlib looks wrong as it behaves correctly (for normal SSH URLs). 
There even exists (partial) support for the `git+ssh` protocol (in `uses_netloc`), however it still doesn't join SSH URLs correctly: 

```python
In [1]: from urllib.parse import urljoin

In [2]: urljoin('git+ssh://git@server/some/subdir.git', '../otherdir.git')
Out[2]: '../otherdir.git'
```

Funnily, the `svn+ssh` protocol is correctly joined (as it is in both feature lists `uses_relative` *and* `uses_netloc`):

```python
In [1]: from urllib.parse import urljoin

In [2]: urljoin('svn+ssh://git@server/some/subdir.git', '../otherdir.git')
Out[2]: 'svn+ssh://git@server/otherdir.git'
```

So what should we do here?
* Try to fix stdlib to include `git+ssh` in the list of `uses_netloc` protocols?
* Temporarily patch stdlib to support `ssh://` or `git+ssh://` with relative paths?
* Temporarily (for calling `urljoin`) replace the protocol `ssh://` (or `git+ssh://`) by `https://` ?
* Warn the user that `ssh://` is not support for relative submodule URLs? But what alternative does the user have? He must then use `https://`.

**Comment by mingwandroid** [comment]
> Temporarily patch stdlib to support

Why temporarily? Wouldn't the fox be valid for upstream?

**Comment by wulmer** [comment]
Hm.. following https://tools.ietf.org/id/draft-salowey-secsh-uri-00.html#sshsemantics, it is not clear how such a path part in an `ssh://` URL should be treated:

> The SSH URI does not define a usage for a non-empty path element. If a non-empty path element is included in an SSH URI then it SHOULD be ignored. 

What does *ignore* mean in the context of a `urljoin`? 

For `git+ssh://` the semantics are more clear (as there is a directory structure behind the URI target) so the most realistic approach IMO is to make `git+ssh://` part of `uses_netloc` in the stdlib. However this then will only work in future Python versions, not for future `conda-build` versions.

Do you see a way for getting this fixed for existing Python versions?
