### ISSUE TITLE
[FeatureRequest] Support PEP-518

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda-build#3507]
If `setup.py` requires dependencies not available in the conda build environment then `load_setup_py_data` will fail to parse the `setup.py` file.

***xref:*** #2458

This seems to be the exact problem that [PEP-518](https://www.python.org/dev/peps/pep-0518/#build-system-table) was designed to solve. If `conda-build` parsed the `[build-system]` table in the `pyproject.toml` it could then create an initial environment with the *`setup_requires`* dependencies such that it could then parse the `setup.py` and add the extra dependencies specified there in a second pass.

**Comment by jakirkham** [comment]
I wonder what other ways there might be to solve this problem.

**Comment by MosheVai** [comment]
What's the status of this? 
I am managing my code with [`poetry`](https://python-poetry.org/)  but I have a single package thats only available on `conda`.

I would like for my `pyproject.toml` to contain also the conda instructions.

**Comment by dhirschfeld** [comment]
I think this has been resolved by #4480
