### ISSUE TITLE
KeyError: 'PROJ_LIB'

### ISSUE THREAD

**Issue by ReimarBauer** [conda/conda-build#3518]
### new feedstock release merge shows success but after merge it fails

all checks have succeeded 

I merged 1.8.0 https://github.com/conda-forge/mss-feedstock and have errors on building the package https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=36698

```
Traceback (most recent call last):
  File 
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
Tests failed for mss-1.8.0-py36_0.tar.bz2 - moving package to 
```

### Expected Behavior

The env var PROJ_LIB is usually setup by conda activate env

**Comment by ocefpaf** [comment]
xref.: https://github.com/conda-forge/mss-feedstock/pull/53

**Comment by ocefpaf** [comment]
https://github.com/conda/conda-build/pull/3515 should fix this.
