### ISSUE TITLE
False errors on checking rpath

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#3520]
`get_rpaths_raw()=['$BUILD_PREFIX/lib:$PREFIX/lib'] and patchelf=$BUILD_PREFIX/lib:$PREFIX/lib disagree for $PREFIX/lib/libopenblasp-r0.3.6.so`

(I replaced the PREFIX and BUILD_PREFIX above for readability)

**Comment by beenje** [comment]
This was fixed in version 3.18.9 and can be closed.
