### ISSUE TITLE
provide ENVs at build time to point to $PREFIX/etc/conda/[de]activate.d folders

### ISSUE THREAD

**Issue by tacaswell** [conda/conda-build#353]
It would be great if conda build provided the ENV variables `$CONDA_ACTIVATE` and `$CONDA_DEACTIVATE` with the paths to the `etc/conda/activate.d` and and `etc/conda/decativate.d` and ensure that those directories exist.  Basically to prevent having to put

```
# deal with env export
mkdir -p $PREFIX/etc/conda/activate.d
mkdir -p $PREFIX/etc/conda/deactivate.d

ACTIVATE=$PREFIX/etc/conda/activate.d/epics_base.sh
DEACTIVATE=$PREFIX/etc/conda/deactivate.d/epics_base.sh
ETC=$PREFIX/etc
```

in every `build.sh`

**Comment by ccordoba12** [comment]
Pinging @tswicegood to know his thoughts on this one

**Comment by tswicegood** [comment]
Hmm.  No reason not to add them.  You would still need to do `mkdir -p $CONDA_ACTIVATE` (or whatever it's called) to make sure they exist.  Is that a problem?

**Comment by tacaswell** [comment]
Yeah, that seems fine to me.  Much easier than putting the logic to strip those empty directories some where else or always bundling empty directories.

**Comment by tswicegood** [comment]
Yeah -- definitely if we handle it fully on the build side.  I'm starting to think that it might be worthwhile to create them at creation time even if they are empty.

**Comment by dan-blanchard** [comment]
Sorry to hijack the conversation, but I've never once needed to add something like this to a build.sh.  Have I been doing something wrong?

**Comment by tacaswell** [comment]
Related, at activation time it would be good to expose this as an ENV, something like https://github.com/tacaswell/conda-prescriptions/tree/conda_etc/releases/conda_etc .

My use case is I am deploying the same software a bunch of places (some of which are centrally managed, some of which are not), but each needs to look at it's own server.  I am trying to deal with this by having a configuration package which dumps yaml into $PREFIX/etc and having the software include that in it's configuration search cascade.

@dan-blanchard This is to support a new-ish feature (that I am not sure is fully documented yet?) that lets you install activate/deactivate hooks.

**Comment by tswicegood** [comment]
@tacaswell -- that's interesting.  That'd be kind of cool as part of a recipes list.

---

@dan-blanchard -- this is a new feature.  It's only needed if you want to create a package that adds activation / deactivation scripts that work kind of like virtualenv postactivate hooks.

**Comment by dan-blanchard** [comment]
Oh, interesting.  I've occasionally wanted that feature.  I remember some people being pretty adamantly opposed to things that only work when activated though.

**Comment by ccordoba12** [comment]
I agree with @tswicegood when he said

>  I'm starting to think that it might be worthwhile to create them at creation time even if they are empty.

There is no harm in doing it. If the recipe don't put anything in there, those dirs will be dismissed when creating the final tar.bz2

Pinging @asmeurer for his thoughts.

----

@dan-blanchard, the problem is that (for now) this only works when you explicitly *activate/deactivate* an environment. So it doesn't work for packages installed in the root environment.

**Comment by tacaswell** [comment]
Well, you shouldn't be doing anything interesting in the root environment _anyway_.

**Comment by ccordoba12** [comment]
@tacaswell, I tried to something interesting but I was limited by root not being a *real* env :-)

**Comment by lsorber** [comment]
+1

**Comment by msarahan** [comment]
This is fine by me.  I don't have time to do this right now, but if anyone submits a PR, I will merge it.
