### ISSUE TITLE
paths to sysroot libraries (build_Env) in cmake-config are not replaced

### ISSUE THREAD

**Issue by looooo** [conda/conda-build#3538]
### Actual Behavior
PR: https://github.com/conda-forge/smesh-feedstock/pull/24
issue: https://github.com/conda-forge/vtk-feedstock/issues/86

### Expected Behavior
replacing the path to build-env with "${BUILD_ENV}"?

### Steps to Reproduce
via ci (PR https://github.com/conda-forge/smesh-feedstock/pull/24)

**Comment by looooo** [comment]
The same problem also occurs int this PR (linux):
https://github.com/conda-forge/freecad-feedstock/pull/26

```
ninja: error: '/home/conda/feedstock_root/build_artifacts/vtk_1559962684947/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/librt.so', needed by 'Mod/Fem/Fem.so', missing and no known rule to make it
```

**Comment by timsnyder** [comment]
Hi @looooo .  I think that I might be running into this same type of thing.  It appears you were able to work around this somehow in the PR's you mentioned above.  Could you point to the detail what you had to do or give updated steps to reproduce?

**Comment by marcelotrevisani** [comment]
It seems that ``cmake`` (as usual) is not working well with sysroot. 
Could you please provide a minimal example to reproduce it?

I think the best person to give some explanations/instructions about this, is @mingwandroid

**Comment by looooo** [comment]
I am currently using these commands:
https://github.com/conda-forge/smesh-feedstock/blob/master/recipe/build.sh#L8L9

**Comment by looooo** [comment]
@marcelotrevisani Maybe rebuilding vtk already solves this problem. I have seen some problems with librt and libm (which I think this was about) in other libraries which magically went away after a recent rebuild.
