### ISSUE TITLE
Lief is broken on ppc64le

### ISSUE THREAD

**Issue by tjakob** [conda/conda-build#3545]
Files written using Lief throw a seg fault on ppc64le. This issue was introduced in https://github.com/conda/conda-build/commit/c0f248a2bbc9ea2a306e03f9a80ed847387abd67 when `patchelf` was replaced with `binary.write()` (from py-lief). 
### Actual Behavior
Segmentation fault when attempting to use binaries create from py-lief.
https://travis-ci.org/conda-forge/mpich-feedstock/builds/546773674#L9377 has an example of the seg fault.

### Expected Behavior
https://travis-ci.org/conda-forge/mpich-feedstock/builds/546789694#L4993 show a success. The only change to this PR between these runs was downgrading conda-build to 3.17.8 from 3.18.2

### Steps to Reproduce
This simplified script illustrates the issue:
```
conda install -c conda-forge py-lief -y
echo "int main(){return 0;}" > test.c
gcc test.c -o test
./test # this works
python -c 'import lief; test=lief.parse("test"); test.write("broken")'
chmod +x broken
./broken # seg faults
```
allows the generated binaries to work.
##### `Output of conda info`
```
     active environment : base
    active env location : /opt/anaconda3
            shell level : 1
       user config file : /home/builder/.condarc
 populated config files : /home/builder/.condarc
          conda version : 4.6.14
    conda-build version : 3.18.2
         python version : 3.6.8.final.0
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-ppc64le
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-ppc64le
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-ppc64le
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-ppc64le
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /home/builder/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /home/builder/.conda/envs
               platform : linux-ppc64le
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Linux/4.14.0-115.6.1.el7a.ppc64le rhel/7.6 glibc/2.17
                UID:GID : 1084:1500
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
Please report this to the LIEF project too: https://github.com/lief-project/LIEF

**Comment by tjakob** [comment]
Related LIEF issue: https://github.com/lief-project/LIEF/issues/304

**Comment by jjhelmus** [comment]
#3570 allows recipe to declare which method should be used to patch RPATHS by setting the `build/rpaths_patcher` variable.  Valid options are `patchelf` (the default for now) and `LIEF`.

I think this issue should remain open until LIEF works on ppc64le but #3570 gives a workaround in the meantime.
