### ISSUE TITLE
specify maximum version in meta.yaml

### ISSUE THREAD

**Issue by florian-wagner** [conda/conda-build#358]
I am aware that one can specify minimal versions in the meta.yaml such as

```
    - gcc    >=4.8 
```
but is it also possible to define a maximum version somewhere, e.g. when a package has a known issue with newer versions of a certain dependency? i.e.

```
    - gcc    <=4.9
```

Thanks a lot.

**Comment by asmeurer** [comment]
Yes, any kind of inequality is supported. `<`, `>`, `<=`, `>=`, `!=`, and `==`.

**Comment by asmeurer** [comment]
See http://conda.pydata.org/docs/spec.html#package-match-specifications.

**Comment by florian-wagner** [comment]
Sorry, my bad. Got the spaces mixed up. Thanks a lot.

Am 06.04.2015 um 22:47 schrieb Aaron Meurer:
