### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by njzjz** [conda/conda-build#3584]
### Actual Behavior

[Here for the full log](https://ci.appveyor.com/project/conda-forge/pybase64-feedstock/builds/25663641/job/pmguykdec87tq4us).
```
TEST END: C:\bld\win-64\pybase64-1.0.0-py37hfa6e2cd_0.tar.bz2
Renaming work directory,  C:\bld\pybase64_1561989032296\work  to  C:\bld\pybase64_1561989032296\work_moved_pybase64-1.0.0-py>=35hfa6e2cd_0_win-64_main_build_loop
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\pybase64_1561989032296\\work' -> 'C:\\bld\\pybase64_1561989032296\\work_moved_pybase64-1.0.0-py>=35hfa6e2cd_0_win-64_main_build_loop'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2378, in build_tree
    shutil.move(metadata.config.work_dir, dest)
  File "C:\Miniconda36-x64\lib\shutil.py", line 555, in move
    symlinks=True)
  File "C:\Miniconda36-x64\lib\shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "C:\Miniconda36-x64\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\pybase64_1561989032296\\work_moved_pybase64-1.0.0-py>=35hfa6e2cd_0_win-64_main_build_loop'
Command exited with code 1
```

### Expected Behavior

why `py>=35` but not `py37`?

### Steps to Reproduce

conda-forge/pybase64-feedstock#2

##### `Output of conda info`

```
  active environment : base
    active env location : C:\Miniconda36-x64
            shell level : 1
       user config file : C:\Users\appveyor\.condarc
 populated config files : C:\Users\appveyor\.condarc
          conda version : 4.7.5
    conda-build version : 3.18.6
         python version : 3.6.5.final.0
       virtual packages : 
       base environment : C:\Miniconda36-x64  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\.conda\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\.conda\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.18.4 CPython/3.6.5 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by njzjz** [comment]
duplicated of #3544

**Comment by nick-youngblut** [comment]
I seem to be running into this issue with my [lasagne package recipe](https://github.com/conda-forge/staged-recipes/pull/9532):

```
TEST END: C:\bld\win-64\lasagne-0.1-py36_0.tar.bz2
Renaming work directory,  C:\bld\lasagne_1568825063486\work  to  C:\bld\lasagne_1568825063486\work_moved_lasagne-0.1-py<=36_0_win-64_main_build_loop
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\lasagne_1568825063486\\work' -> 'C:\\bld\\lasagne_1568825063486\\work_moved_lasagne-0.1-py<=36_0_win-64_main_build_loop'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".ci_support\build_all.py", line 134, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support\build_all.py", line 124, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2408, in build_tree
    shutil.move(metadata.config.work_dir, dest)
  File "C:\Miniconda36-x64\lib\shutil.py", line 555, in move
    symlinks=True)
  File "C:\Miniconda36-x64\lib\shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "C:\Miniconda36-x64\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\lasagne_1568825063486\\work_moved_lasagne-0.1-py<=36_0_win-64_main_build_loop'
```

It seems to be due to `- python <=3.6` in my meta.yaml, which then seems to create a bad file path that includes "<=", but if I don't include `- python <=3.6` for the `host:` and `run:` sections of the meta.yaml, other tests fail.

**Comment by marcelotrevisani** [comment]
Could you please share the recipe?

**Comment by marcelotrevisani** [comment]
Or a minimum example to reproduce it

**Comment by nick-youngblut** [comment]
Just follow the link in my last post or go [straight to the build](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/27501553)

**Comment by njzjz** [comment]
> I seem to be running into this issue with my [lasagne package recipe](https://github.com/conda-forge/staged-recipes/pull/9532):
> 
> ```
> TEST END: C:\bld\win-64\lasagne-0.1-py36_0.tar.bz2
> Renaming work directory,  C:\bld\lasagne_1568825063486\work  to  C:\bld\lasagne_1568825063486\work_moved_lasagne-0.1-py<=36_0_win-64_main_build_loop
> Traceback (most recent call last):
>   File "C:\Miniconda36-x64\lib\shutil.py", line 544, in move
>     os.rename(src, real_dst)
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\lasagne_1568825063486\\work' -> 'C:\\bld\\lasagne_1568825063486\\work_moved_lasagne-0.1-py<=36_0_win-64_main_build_loop'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File ".ci_support\build_all.py", line 134, in <module>
>     build_all(args.recipes_dir, args.arch)
>   File ".ci_support\build_all.py", line 68, in build_all
>     build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
>   File ".ci_support\build_all.py", line 124, in build_folders
>     conda_build.api.build([recipe], config=get_config(arch, channel_urls))
>   File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 209, in build
>     notest=notest, need_source_download=need_source_download, variants=variants)
>   File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2408, in build_tree
>     shutil.move(metadata.config.work_dir, dest)
>   File "C:\Miniconda36-x64\lib\shutil.py", line 555, in move
>     symlinks=True)
>   File "C:\Miniconda36-x64\lib\shutil.py", line 315, in copytree
>     os.makedirs(dst)
>   File "C:\Miniconda36-x64\lib\os.py", line 220, in makedirs
>     mkdir(name, mode)
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\lasagne_1568825063486\\work_moved_lasagne-0.1-py<=36_0_win-64_main_build_loop'
> ```
> 
> It seems to be due to `- python <=3.6` in my meta.yaml, which then seems to create a bad file path that includes "<=", but if I don't include `- python <=3.6` for the `host:` and `run:` sections of the meta.yaml, other tests fail.

You can use `skip: True  # [py37]` instead of `- python <=3.6` to skip this issue, but I think it is still a bug that needs to be resolved.

**Comment by jjhelmus** [comment]
`skip: True # [py37]` will not work since there is [no py37 pre-processor selector](https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors).  Use `skip: True  # [py==37]` as suggested on the linked documentation page.

**Comment by seanyen** [comment]
I hit the same problem in my [recipe](https://github.com/conda-forge/staged-recipes/pull/9787). Here is the error message:

```
Renaming work directory,  C:\Miniconda\conda-bld\colcon-core_1570769496978\work  to  C:\Miniconda\conda-bld\colcon-core_1570769496978\work_moved_colcon-core-0.4.0-py>=35_0_win-64_main_build_loop
Traceback (most recent call last):
  File "C:\Miniconda\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Miniconda\\conda-bld\\colcon-core_1570769496978\\work' -> 'C:\\Miniconda\\conda-bld\\colcon-core_1570769496978\\work_moved_colcon-core-0.4.0-py>=35_0_win-64_main_build_loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".ci_support\build_all.py", line 134, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support\build_all.py", line 124, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2408, in build_tree
    shutil.move(metadata.config.work_dir, dest)
  File "C:\Miniconda\lib\shutil.py", line 555, in move
    symlinks=True)
  File "C:\Miniconda\lib\shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "C:\Miniconda\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Miniconda\\conda-bld\\colcon-core_1570769496978\\work_moved_colcon-core-0.4.0-py>=35_0_win-64_main_build_loop'

```

**Comment by dhirschfeld** [comment]
This is happening in the `wsproto` feedstock
https://github.com/conda-forge/wsproto-feedstock/pull/6

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=87920&view=logs&jobId=f97ca392-d626-52d0-4b2e-4b27aa319a77&taskId=3002d0ca-d910-5264-f0e4-809a5057fac4&lineStart=406&lineEnd=407&colStart=1&colEnd=1

**Comment by astrofrog** [comment]
I'm seeing this with https://github.com/conda-forge/reproject-feedstock/pull/16

**Comment by astrofrog** [comment]
Ok in my case it was because I had ``python >=3.5`` in the recipe. It would be nice if the linter could warn about not doing this?
