### ISSUE TITLE
Error building package on Windows

### ISSUE THREAD

**Issue by Bezier89** [conda/conda-build#3597]
### Actual Behavior

The following error is produced (note that it happens rather early in the process, within a few seconds) when building any conda package. I've attached a [trivial recipe](https://github.com/conda/conda-build/files/3374762/conda.recipe.zip) where this still reproduces.

```
Traceback (most recent call last):
  File "[CONDA_ROOT]\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "[CONDA_ROOT]\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "[CONDA_ROOT]\lib\concurrent\futures\process.py", line 270, in _queue_management_worker
    ready = wait([reader] + sentinels)
  File "[CONDA_ROOT]\lib\multiprocessing\connection.py", line 859, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "[CONDA_ROOT]\lib\multiprocessing\connection.py", line 791, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 64
```

### Expected Behavior

No error when building conda package.

### Steps to Reproduce

Build any conda package. This doesn't seem to reproduce on every Windows machine. The common aspect among machines where I've seen it reproduce is that they're all Windows Server 2012 R2 machines. It does not reproduce on the Windows Server 2008 R2 or Windows Server 2016 machines I've tested, but there's possibly other aspects at play (e.g. number of cores on the machine).

##### `Output of conda info`

```
     active environment : None
          conda version : 4.7.5
    conda-build version : 3.18.5
         python version : 3.6.8.final.0
       virtual packages :
               platform : win-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.6.8 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by Bezier89** [comment]
Note: This issue is only present in conda-build 3.18. I've confirmed that the issue is resolved if I downgrade to conda-build 3.17.8.

**Comment by cometchaser** [comment]
I observe the same error #3576

**Comment by Bezier89** [comment]
@msarahan I was hoping https://github.com/conda/conda-build/commit/cd20cc6194cf07fb6316b971764e66e4f7a4e248 would fix this but the issue is still present in conda-build 3.18.7

**Comment by Bezier89** [comment]
@msarahan After more investigation, I'm not sure this is related to Windows Server 2008 vs 2012 vs 2016. I believe this issue will happen on any Windows machine that has performed a sufficient number of  builds. If I change the [conda-build root-dir](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-conda-build-output-root-directory-root-dir) to a different (empty) directory, packages build fine, presumably until that new directory gets too full. Note that I'm not talking about ridiculous number of packages, ~70 packages in the conda-bld folder is enough to cause this error.

**Comment by dhirschfeld** [comment]
I saw this problem also and think it's related to the broken `multiprocessing.cpu_count` 

I'm on a VM with 4 vCPUs and this is what I see:
```python
In [6]: import multiprocessing
   ...: import psutil

In [7]: multiprocessing.cpu_count()
Out[7]: 64

In [8]: psutil.cpu_count()
Out[8]: 4

```

**Comment by dhirschfeld** [comment]
Maybe patching the below function to always use `psutil` would fix the problem:
https://github.com/conda/conda-build/blob/dd74b17f4e7cb4286fe9a403895f9d34feb8e071/conda_build/environ.py#L479-L491


...assuming that function was called to set the number of threads in the first place.

**Comment by Bezier89** [comment]
@dhirschfeld You're on to something, although it looks like the exact culprit is in another file. I've opened a PR.
