### ISSUE TITLE
conda & pyenchant

### ISSUE THREAD

**Issue by sirpercival** [conda/conda-build#360]
Conda suggested I post this traceback here. I tried both ``$ conda pipbuild pyenchant`` and ``$ conda build conda-recipes/pyenchant``, and got the same error.

    Traceback (most recent call last):
      File "/Users/gray/anaconda/bin/conda-build", line 5, in <module>
        sys.exit(main())
      File "/Users/gray/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 112, in main
        args_func(args, p)
      File "/Users/gray/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 321, in args_func
        args.func(args, p)
      File "/Users/gray/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 228, in execute
        arg = arg.decode(getpreferredencoding())
    LookupError: unknown encoding: 

conda info:
    Current conda install:

                 platform : osx-64
            conda version : 3.10.1
      conda-build version : 1.11.0
           python version : 2.7.9.final.0
          requests version : 2.6.0
         root environment : /Users/gray/anaconda  (writable)
      default environment : /Users/gray/anaconda
         envs directories : /Users/gray/anaconda/envs
            package cache : /Users/gray/anaconda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/osx-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

**Comment by asmeurer** [comment]
What does

```py
import locale
locale.getpreferredencoding()
```

give you in a Python session?

**Comment by asmeurer** [comment]
Also what is `echo $LANG` in your shell?

**Comment by sirpercival** [comment]
>>> import locale
    >>> locale.getpreferredencoding()
    ''

    bash-3.2$ echo $LANG
    en_US

**Comment by asmeurer** [comment]
I just pushed a change that should hopefully fix this. I'm not sure why your LANG is not en_US.UTF-8. Perhaps you don't have your terminal set to fully support Unicode.

**Comment by sirpercival** [comment]
Awesome, thanks! I'm using XQuartz/X11, maybe that's the problem?

So, uh... how do I apply this fix?

**Comment by asmeurer** [comment]
We will be doing a release of conda-build soon with the fix. Until then, it's possible that setting `LANG` to `en_US.UTF-8` will fix it. I'm not entirely clear how getpreferredencoding works, though, so I could be wrong.
