### ISSUE TITLE
Unable to build with tar.Z source archive

### ISSUE THREAD

**Issue by vitale232** [conda/conda-build#362]
I'm attempting to install [HDF-EOS2](http://hdfeos.org/software/library.php) from source using conda-build.
  fn: HDF-EOS2.19v1.00.tar.Z
  url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS2.19v1.00.tar.Z

conda-build does not seem to extract the tar.Z archive properly, thus there is no ./configure file when the build.sh script is invoked.

Is there a workaround to perhaps convert the tar.Z archive to a tar.gz archive in the beginning of the build script?

Here is the conda build output:
----
$ conda build hdf-eos2/
Removing old build directory
Removing old work directory
BUILD START: hdf-eos2-2.19.1-py27_0
Fetching package metadata: ........
Solving package specifications: .
The following NEW packages will be INSTALLED:

    hdf4:       4.2.11-py27_0
    jpeg:       8d-0         
    openssl:    1.0.1k-1     
    pip:        6.1.1-py27_0 
    python:     2.7.9-2      
    readline:   6.2-2        
    setuptools: 15.0-py27_0  
    sqlite:     3.8.4.1-1    
    system:     5.8-2        
    tk:         8.5.18-0     
    zlib:       1.2.8-0      

Linking packages ...
[      COMPLETE      ]|####################################################################################################################################| 100%
This is an install message from the hdf4 package.
Removing old work directory
Source cache directory is: /home/vitale232/miniconda/conda-bld/src_cache
Found source in cache: HDF-EOS2.19v1.00.tar.Z
Extracting download
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
Package: hdf-eos2-2.19.1-py27_0
source tree in: /home/vitale232/miniconda/conda-bld/work
\+ echo 'This is the prefix: ' /home/vitale232/miniconda/envs/_build
This is the prefix:  /home/vitale232/miniconda/envs/_build
\+ ./configure --with-jpeg=/home/vitale232/miniconda/envs/_build --with-zlib=/home/vitale232/miniconda/envs/_build --with-hdf4=/home/vitale232/miniconda/envs/_build
/home/vitale232/Documents/conda_ledaps-build/hdf-eos2/build.sh: line 5: ./configure: No such file or directory
Command failed: /bin/bash -x -e /home/vitale232/Documents/conda_ledaps-build/hdf-eos2/build.sh

Here is conda info:
-----
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/vitale232/miniconda  (writable)
  default environment : /home/vitale232/miniconda
     envs directories : /home/vitale232/miniconda/envs
        package cache : /home/vitale232/miniconda/pkgs
         channel URLs : https://conda.binstar.org/jgomezdans/linux-64/
                        https://conda.binstar.org/jgomezdans/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/vitale232/.condarc
    is foreign system : False

Here is the meta.yaml:
----
package:
  name: hdf-eos2
  version: 2.19.1

source:
  fn: HDF-EOS2.19v1.00.tar.Z
  url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS2.19v1.00.tar.Z

requirements:
  build:
    - python
    - jpeg
    - zlib
    - hdf4
  run:
    - python
    - jpeg
    - zlib
    - hdf4

And here is the build.sh script:
----
#!/usr/bash
echo 'This is the prefix: ' ${PREFIX}

\# zcat HDF-EOS2.19v1.00.tar.Z | gzip > HDF-EOS2.19v1.00.tar.gz
./configure --with-jpeg=${PREFIX} \
	--with-zlib=${PREFIX} \
	--with-hdf4=${PREFIX}

make -j 10
make install

Thanks for any suggestions!

**Comment by asmeurer** [comment]
You can manually decompress it at the top of your build script. 

What is .Z?

**Comment by vitale232** [comment]
I truly don't know.

What directory should it be decompressed in?

Here is the output when I try to decompress without specifying a directory:
----
$ conda build hdf-eos2/
Removing old build directory
Removing old work directory
BUILD START: hdf-eos2-2.19.1-py27_0
Fetching package metadata: ........
Solving package specifications: .
The following NEW packages will be INSTALLED:

    hdf4:       4.2.11-py27_0
    jpeg:       8d-0         
    openssl:    1.0.1k-1     
    pip:        6.1.1-py27_0 
    python:     2.7.9-2      
    readline:   6.2-2        
    setuptools: 15.0-py27_0  
    sqlite:     3.8.4.1-1    
    system:     5.8-2        
    tk:         8.5.18-0     
    zlib:       1.2.8-0      

Linking packages ...
[      COMPLETE      ]|####################################################################################################################################| 100%
This is an install message from the hdf4 package.
Removing old work directory
Source cache directory is: /home/vitale232/miniconda/conda-bld/src_cache
Found source in cache: HDF-EOS2.19v1.00.tar.Z
Extracting download
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
Package: hdf-eos2-2.19.1-py27_0
source tree in: /home/vitale232/miniconda/conda-bld/work
\+ echo 'This is the prefix: ' /home/vitale232/miniconda/envs/_build
This is the prefix:  /home/vitale232/miniconda/envs/_build
\+ tar -xvf HDF-EOS2.19v1.00.tar.Z
tar (child): cannot run compress: No such file or directory
tar (child): trying gzip
./hdfeos/
./hdfeos/lib/
./hdfeos/lib/dec/
./hdfeos/lib/hp/
./hdfeos/lib/ibm/
./hdfeos/lib/sgi/
./hdfeos/lib/sgi32/
./hdfeos/lib/sgi64/
./hdfeos/lib/sun4/
./hdfeos/lib/sun5/
./hdfeos/lib/tmp/
./hdfeos/lib/tmp/geolibDEC.a
./hdfeos/lib/tmp/geolibHP.a
./hdfeos/lib/tmp/geolibIBM.a
./hdfeos/lib/tmp/geolibIRIX53.a
./hdfeos/lib/tmp/geolibIRIX62-32.a
./hdfeos/lib/tmp/geolibIRIX62-64.a
./hdfeos/lib/tmp/geolibSOL24.a
./hdfeos/lib/tmp/geolibSUN4.a
./hdfeos/lib/tmp/geolibIRIX62-n32.a
./hdfeos/lib/tmp/geolibIRIX62-64mips3.a
./hdfeos/lib/tmp/geolibIRIX65-64.a
./hdfeos/lib/tmp/geolibLINUX.a
./hdfeos/lib/tmp/geolibHP11.a
./hdfeos/lib/tmp/geolibIRIX65-n32.a
./hdfeos/lib/tmp/geolibSOL28.a
./hdfeos/lib/tmp/geolibLINUX64.a
./hdfeos/lib/tmp/geolibLINUXIA64.a
./hdfeos/lib/tmp/geolibMAC.a
./hdfeos/lib/tmp/geolibSOL210.a
./hdfeos/lib/tmp/geolibSOL29.a
./hdfeos/lib/tmp/geolibCYGWIN.a
./hdfeos/lib/tmp/geolibMACIntel.a
./hdfeos/lib/tmp/geolibMACIntel64.a
./hdfeos/lib/hp10
./hdfeos/lib/irix65/
./hdfeos/lib/sun5.8/
./hdfeos/lib/linux/
./hdfeos/lib/macintosh/
./hdfeos/lib/sun5.10/
./hdfeos/lib/sun5.9/
./hdfeos/lib/linux32/
./hdfeos/lib/linux64/
./hdfeos/lib/macintel/
./hdfeos/make/
./hdfeos/make/CLSInstall.sh
./hdfeos/make/Makefile.instr
./hdfeos/make/Makefile.template
./hdfeos/make/make.options
./hdfeos/make/make.targets
./hdfeos/make/makeidl.include
./hdfeos/make/makeidlxx.include
./hdfeos/make/makerec.include
./hdfeos/make/makerec.template
./hdfeos/obj/
./hdfeos/obj/dec/
./hdfeos/obj/hp/
./hdfeos/obj/ibm/
./hdfeos/obj/sgi/
./hdfeos/obj/sgi32/
./hdfeos/obj/sgi64/
./hdfeos/obj/sun4/
./hdfeos/obj/sun5/
./hdfeos/obj/irix65/
./hdfeos/obj/sun5.8/
./hdfeos/obj/linux/
./hdfeos/obj/macintosh/
./hdfeos/obj/sun5.10/
./hdfeos/obj/sun5.9/
./hdfeos/obj/linux32/
./hdfeos/obj/linux64/
./hdfeos/obj/macintel/
./hdfeos/src/
./hdfeos/src/EHapi.c
./hdfeos/src/GDapi.c
./hdfeos/src/PTapi.c
./hdfeos/src/SWapi.c
./hdfeos/src/make_IT/
./hdfeos/src/make_IT/makeDEC4.0r1
./hdfeos/src/make_IT/makeHP4.0r1
./hdfeos/src/make_IT/makeIBM4.0r1
./hdfeos/src/make_IT/makeSGI4.0r1
./hdfeos/src/make_IT/makeSUN4.0r1
./hdfeos/src/make_IT/makeinc
./hdfeos/src/Makefile_CM
./hdfeos/src/Makefile
./hdfeos/src/Makefile_alt
./hdfeos/src/Makefile.am
./hdfeos/src/Makefile.in
./hdfeos/src/CMakeLists.txt
./hdfeos/samples/
./hdfeos/samples/AppendField.c
./hdfeos/samples/DefineFields.c
./hdfeos/samples/DefineGDflds.c
./hdfeos/samples/DefineLevels.c
./hdfeos/samples/InquireGrid.c
./hdfeos/samples/InquireSwath.c
./hdfeos/samples/ReadFields.c
./hdfeos/samples/ReadGDflds.c
./hdfeos/samples/ReadLevels.c
./hdfeos/samples/SetupGrid.c
./hdfeos/samples/SetupPoint.c
./hdfeos/samples/SetupSwath.c
./hdfeos/samples/SubsetGrid.c
./hdfeos/samples/SubsetPoint.c
./hdfeos/samples/SubsetSwath.c
./hdfeos/samples/UpdateLevels.c
./hdfeos/samples/WriteFields.c
./hdfeos/samples/WriteGDflds.c
./hdfeos/samples/WriteLevels.c
./hdfeos/samples/appendfield.f
./hdfeos/samples/definefields.f
./hdfeos/samples/definegdflds.f
./hdfeos/samples/definelevels.f
./hdfeos/samples/inquiregrid.f
./hdfeos/samples/inquireswath.f
./hdfeos/samples/readfields.f
./hdfeos/samples/readgdflds.f
./hdfeos/samples/readlevels.f
./hdfeos/samples/setupgrid.f
./hdfeos/samples/setuppoint.f
./hdfeos/samples/setupswath.f
./hdfeos/samples/subsetgrid.f
./hdfeos/samples/subsetpoint.f
./hdfeos/samples/subsetswath.f
./hdfeos/samples/updatelevels.f
./hdfeos/samples/writefields.f
./hdfeos/samples/writegdflds.f
./hdfeos/samples/writelevels.f
./hdfeos/samples/fixedBuoy0.txt
./hdfeos/samples/fixedBuoy1.txt
./hdfeos/samples/fixedBuoy1s.txt
./hdfeos/samples/floatBuoy0.txt
./hdfeos/samples/floatBuoy1.txt
./hdfeos/samples/simple.txt
./hdfeos/samples/README
./hdfeos/samples/RunSamples
./hdfeos/samples/make.com
./hdfeos/samples/make_Csamples
./hdfeos/samples/Makefile.am
./hdfeos/samples/Makefile.in
./hdfeos/samples/ReadDimscaleGrid.c
./hdfeos/samples/ReadDimscaleSwath.c
./hdfeos/samples/WriteDimscaleGrid.c
./hdfeos/samples/WriteDimscaleSwath.c
./hdfeos/samples/make.com_F
./hdfeos/samples/make_Fsamples
./hdfeos/samples/readdimscalegrid.f
./hdfeos/samples/readdimscaleswath.f
./hdfeos/samples/writedimscalegrid.f
./hdfeos/samples/writedimscaleswath.f
./hdfeos/samples/WriteAllDimscaleGrid.c
./hdfeos/samples/WriteAllDimscaleSwath.c
./hdfeos/samples/CMakeLists.txt
./hdfeos/bin/
./hdfeos/bin/dec/
./hdfeos/bin/hp/
./hdfeos/bin/ibm/
./hdfeos/bin/sgi/
./hdfeos/bin/sgi32/
./hdfeos/bin/sgi64/
./hdfeos/bin/sun4/
./hdfeos/bin/sun5/
./hdfeos/bin/tmp/
./hdfeos/bin/tmp/hdfeos_env.csh.tmp
./hdfeos/bin/tmp/hdfeos_env.ksh.tmp
./hdfeos/bin/INSTALL-HDFEOS
./hdfeos/bin/hp10
./hdfeos/bin/sun5.5/
./hdfeos/bin/sgi6n32/
./hdfeos/bin/irix65/
./hdfeos/bin/linux/
./hdfeos/bin/macintosh/
./hdfeos/bin/sun5.10/
./hdfeos/bin/sun5.9/
./hdfeos/bin/linux32/
./hdfeos/bin/linux64/
./hdfeos/bin/macintel/
./hdfeos/bin/INSTALL
./hdfeos/bin/INSTALL-Scripts/
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDF
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDF4.2r6
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDF5
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDF5-1.8.8
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDFEOS-Wrap
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDFEOS5-Wrap
./hdfeos/bin/INSTALL-Scripts/INSTALL-JPEG
./hdfeos/bin/INSTALL-Scripts/INSTALL-JPEGSRC.v6b
./hdfeos/bin/INSTALL-Scripts/INSTALL-SZIP
./hdfeos/bin/INSTALL-Scripts/INSTALL-SZIP2.1
./hdfeos/bin/INSTALL-Scripts/INSTALL-ZLIB
./hdfeos/bin/INSTALL-Scripts/INSTALL-ZLIB-1.2.5
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDF4.2r10
./hdfeos/bin/INSTALL-Scripts/INSTALL-HDF5-1.8.12
./hdfeos/bin/INSTALL-Scripts/INSTALL-ZLIB-1.2.8
./hdfeos/include/
./hdfeos/include/HdfEosDef.h
./hdfeos/include/cfortHdf.h
./hdfeos/include/HDFEOSVersion.h
./hdfeos/include/ease.h
./hdfeos/include/HdfEosDef.f
./hdfeos/include/HE2_config.h.in
./hdfeos/include/Makefile.am
./hdfeos/include/Makefile.in
./hdfeos/doc/
./hdfeos/doc/HDFEOS-DEFINITION.TXT
./hdfeos/doc/README
./hdfeos/doc/AUTOCONF_INSTALL
./hdfeos/doc/Compile_WIN.readme.txt
./hdfeos/doc/Install_HDFEOS_WIN.readme.txt
./hdfeos/Makefile
./hdfeos/gctp/
./hdfeos/gctp/Makefile
./hdfeos/gctp/database/
./hdfeos/gctp/database/nad1927.dat
./hdfeos/gctp/database/nad1983.dat
./hdfeos/gctp/database/nad27sp
./hdfeos/gctp/database/nad83sp
./hdfeos/gctp/database/nad27sp_be
./hdfeos/gctp/database/nad27sp_le
./hdfeos/gctp/database/nad83sp_be
./hdfeos/gctp/database/nad83sp_le
./hdfeos/gctp/doc/
./hdfeos/gctp/doc/README
./hdfeos/gctp/include/
./hdfeos/gctp/include/bcea.h
./hdfeos/gctp/include/cproj.h
./hdfeos/gctp/include/isin.h
./hdfeos/gctp/include/proj.h
./hdfeos/gctp/include/cproj_prototypes.h
./hdfeos/gctp/include/gctp_prototypes.h
./hdfeos/gctp/include/Makefile.am
./hdfeos/gctp/include/Makefile.in
./hdfeos/gctp/lib/
./hdfeos/gctp/lib/dec/
./hdfeos/gctp/lib/hp/
./hdfeos/gctp/lib/hp11/
./hdfeos/gctp/lib/ibm/
./hdfeos/gctp/lib/irix65/
./hdfeos/gctp/lib/linux/
./hdfeos/gctp/lib/sgi/
./hdfeos/gctp/lib/sgi32/
./hdfeos/gctp/lib/sgi64/
./hdfeos/gctp/lib/sun5/
./hdfeos/gctp/lib/sun5.8/
./hdfeos/gctp/lib/linux64/
./hdfeos/gctp/lib/linuxia64/
./hdfeos/gctp/lib/macintosh/
./hdfeos/gctp/lib/sun5.10/
./hdfeos/gctp/lib/sun5.9/
./hdfeos/gctp/lib/winnt98/
./hdfeos/gctp/lib/linux32/
./hdfeos/gctp/lib/macintel/
./hdfeos/gctp/lib/macintel32/
./hdfeos/gctp/lib/macintel64/
./hdfeos/gctp/src/
./hdfeos/gctp/src/alberfor.c
./hdfeos/gctp/src/alberinv.c
./hdfeos/gctp/src/alconfor.c
./hdfeos/gctp/src/alconinv.c
./hdfeos/gctp/src/azimfor.c
./hdfeos/gctp/src/aziminv.c
./hdfeos/gctp/src/bceafor.c
./hdfeos/gctp/src/bceainv.c
./hdfeos/gctp/src/br_gctp.c
./hdfeos/gctp/src/cproj.c
./hdfeos/gctp/src/eqconfor.c
./hdfeos/gctp/src/eqconinv.c
./hdfeos/gctp/src/equifor.c
./hdfeos/gctp/src/equiinv.c
./hdfeos/gctp/src/for_init.c
./hdfeos/gctp/src/gctp.c
./hdfeos/gctp/src/gnomfor.c
./hdfeos/gctp/src/gnominv.c
./hdfeos/gctp/src/goodfor.c
./hdfeos/gctp/src/goodinv.c
./hdfeos/gctp/src/gvnspfor.c
./hdfeos/gctp/src/gvnspinv.c
./hdfeos/gctp/src/hamfor.c
./hdfeos/gctp/src/haminv.c
./hdfeos/gctp/src/imolwfor.c
./hdfeos/gctp/src/imolwinv.c
./hdfeos/gctp/src/inv_init.c
./hdfeos/gctp/src/isinusfor.c
./hdfeos/gctp/src/isinusinv.c
./hdfeos/gctp/src/lamazfor.c
./hdfeos/gctp/src/lamazinv.c
./hdfeos/gctp/src/lamccfor.c
./hdfeos/gctp/src/lamccinv.c
./hdfeos/gctp/src/make.com
./hdfeos/gctp/src/makedec
./hdfeos/gctp/src/makehp
./hdfeos/gctp/src/makehp11
./hdfeos/gctp/src/makeibm
./hdfeos/gctp/src/makelinux
./hdfeos/gctp/src/makesgi32
./hdfeos/gctp/src/makesgi64
./hdfeos/gctp/src/makesgi65_64
./hdfeos/gctp/src/makesgi65_n32
./hdfeos/gctp/src/makesgin32
./hdfeos/gctp/src/makesol25
./hdfeos/gctp/src/makesol28
./hdfeos/gctp/src/merfor.c
./hdfeos/gctp/src/merinv.c
./hdfeos/gctp/src/millfor.c
./hdfeos/gctp/src/millinv.c
./hdfeos/gctp/src/molwfor.c
./hdfeos/gctp/src/molwinv.c
./hdfeos/gctp/src/obleqfor.c
./hdfeos/gctp/src/obleqinv.c
./hdfeos/gctp/src/omerfor.c
./hdfeos/gctp/src/omerinv.c
./hdfeos/gctp/src/orthfor.c
./hdfeos/gctp/src/orthinv.c
./hdfeos/gctp/src/paksz.c
./hdfeos/gctp/src/polyfor.c
./hdfeos/gctp/src/polyinv.c
./hdfeos/gctp/src/psfor.c
./hdfeos/gctp/src/psinv.c
./hdfeos/gctp/src/report.c
./hdfeos/gctp/src/robfor.c
./hdfeos/gctp/src/robinv.c
./hdfeos/gctp/src/sinfor.c
./hdfeos/gctp/src/sininv.c
./hdfeos/gctp/src/somfor.c
./hdfeos/gctp/src/sominv.c
./hdfeos/gctp/src/sphdz.c
./hdfeos/gctp/src/spload.f
./hdfeos/gctp/src/sterfor.c
./hdfeos/gctp/src/sterinv.c
./hdfeos/gctp/src/stplnfor.c
./hdfeos/gctp/src/stplninv.c
./hdfeos/gctp/src/tmfor.c
./hdfeos/gctp/src/tminv.c
./hdfeos/gctp/src/untfz.c
./hdfeos/gctp/src/utmfor.c
./hdfeos/gctp/src/utminv.c
./hdfeos/gctp/src/vandgfor.c
./hdfeos/gctp/src/vandginv.c
./hdfeos/gctp/src/wivfor.c
./hdfeos/gctp/src/wivinv.c
./hdfeos/gctp/src/wviifor.c
./hdfeos/gctp/src/wviiinv.c
./hdfeos/gctp/src/ceafor.c
./hdfeos/gctp/src/ceainv.c
./hdfeos/gctp/src/makelinux64
./hdfeos/gctp/src/makelinuxia64
./hdfeos/gctp/src/makemacintosh
./hdfeos/gctp/src/makesol210
./hdfeos/gctp/src/makesol29
./hdfeos/gctp/src/makecygwin
./hdfeos/gctp/src/makemacintel
./hdfeos/gctp/src/Makefile.am
./hdfeos/gctp/src/Makefile.in
./hdfeos/gctp/src/makelinux32
./hdfeos/gctp/src/makemacintel32
./hdfeos/gctp/src/makemacintel64
./hdfeos/gctp/src/CMakeLists.txt
./hdfeos/gctp/Makefile.am
./hdfeos/gctp/Makefile.in
./hdfeos/gctp/CMakeLists.txt
./hdfeos/util/
./hdfeos/util/GDconvert_ij2ll.c
./hdfeos/util/make.com
./hdfeos/util/makefile
./hdfeos/Makefile.am
./hdfeos/Makefile.in
./hdfeos/aclocal.m4
./hdfeos/autom4te.cache/
./hdfeos/config/
./hdfeos/config/config.guess
./hdfeos/config/config.sub
./hdfeos/config/depcomp
./hdfeos/config/include.am
./hdfeos/config/install-sh
./hdfeos/config/ltmain.sh
./hdfeos/config/missing
./hdfeos/config/cmake/
./hdfeos/config/cmake/CPack.cmake
./hdfeos/config/cmake/CTestCustom.cmake
./hdfeos/config/cmake/CheckTypeSize.cmake
./hdfeos/config/cmake/ConfigureChecks.cmake
./hdfeos/config/cmake/EOSMacros.cmake
./hdfeos/config/cmake/EOSTests.c
./hdfeos/config/cmake/FindEOS.cmake.in
./hdfeos/config/cmake/FindHDF4.cmake.in
./hdfeos/config/cmake/FindMPI.cmake
./hdfeos/config/cmake/FindSZIP.cmake
./hdfeos/config/cmake/HDF4Macros.cmake
./hdfeos/config/cmake/HDF4UseFortran.cmake
./hdfeos/config/cmake/HDFEOSMacros.cmake
./hdfeos/config/cmake/HE2_config.h.in
./hdfeos/config/cmake/NSIS.InstallOptions.ini.in
./hdfeos/config/cmake/NSIS.template.in
./hdfeos/config/cmake/cacheinit.cmake
./hdfeos/config/cmake/hdfeos-config-version.cmake.in
./hdfeos/config/cmake/hdfeos-config.cmake.build.in
./hdfeos/config/cmake/hdfeos-config.cmake.install.in
./hdfeos/config/cmake/runTest.cmake
./hdfeos/config/cmake/xlatefile.c
./hdfeos/configure
./hdfeos/configure.ac
./hdfeos/CMakeLists.txt
./hdfeos/CTestConfig.cmake
\+ ./configure --with-jpeg=/home/vitale232/miniconda/envs/_build --with-zlib=/home/vitale232/miniconda/envs/_build --with-hdf4=/home/vitale232/miniconda/envs/_build
/home/vitale232/Documents/conda_ledaps-build/hdf-eos2/build.sh: line 6: ./configure: No such file or directory
Command failed: /bin/bash -x -e /home/vitale232/Documents/conda_ledaps-build/hdf-eos2/build.sh

Here is the build.sh script:
----
#!/usr/bash
echo 'This is the prefix: ' ${PREFIX}

tar -xvf HDF-EOS2.19v1.00.tar.Z 

./configure --with-jpeg=${PREFIX} \
	--with-zlib=${PREFIX} \
	--with-hdf4=${PREFIX}

make -j 10
make install

**Comment by asmeurer** [comment]
The current directory of the build script is fine.

**Comment by vitale232** [comment]
Thanks for the tips. This seems to get it going:

#!/usr/bash
echo 'This is the prefix: ' ${PREFIX}

tar -xvf HDF-EOS2.19v1.00.tar.Z 

./hdfeos/configure --with-jpeg=${PREFIX} \
	--with-zlib=${PREFIX} \
	--with-hdf4=${PREFIX}

make -j 10
make install

**Comment by jjhelmus** [comment]
Unfortunately 0131f71 doesn't seem to fix this issue, at least for me.

.Z files (including the HDF-EOS2 file mentioned here) are typically compressed with the UNIX [compress program](http://en.wikipedia.org/wiki/Compress) and must be decompressed with **uncompress**.  Although the gzip library and utilities can decompress these files such functionality is explicitly mentioned as not being available in the [Python gzip module](https://docs.python.org/2/library/gzip.html) and therefore cannot be used with the tarfile module.

I do not believe it is possible to decompress .Z files in Python without calling `uncompress` or `zcat` from a shell.  Perhaps such a call could be implemented in the same manner as the call to unxz?

**Comment by asmeurer** [comment]
I just pushed a fix that should work (I tested it against the HDF-EOS2 file).

**Comment by jjhelmus** [comment]
Thanks for the fix.  FYI, I did a bit more digging and uncompress is just an alias for gunzip that was not added until gzip 1.3.11.  This means that the check for uncompress will fail on some older Linux systems, for example CentOS 5.  Changing the check to gunzip will allow this functionality to work even on these systems.
