### ISSUE TITLE
host env requirements ignored for multiple output builds?

### ISSUE THREAD

**Issue by beckermr** [conda/conda-build#3624]
### Actual Behavior

This bug is not reproducible yet, but I keep seeing the host env requirements for the top-level build ignored for this build of xgboost (https://github.com/conda-forge/xgboost-feedstock/pull/30). In particular, conda does not seem to be installing `llvm-openmp` in the host section.

Further, I tried adding extra packages besides `llvm-openmp` to the host section and those are ignored. However, packages I add to the build section seem to be installed.

### Expected Behavior

It should be installing `llvm-openmp`. 

### Steps to Reproduce

I cannot reproduce this locally in a simple case, not for lack of trying though.

##### `Output of conda info`

I don't have this from the CI, but this is conda-build 3.18.8 and conda 4.7.10.

```

```

**Comment by beckermr** [comment]
@isuruf @jjhelmus for viz

**Comment by beckermr** [comment]
Here are some relevant outputs from azure.

```
## Package Plan ##

  environment location: /usr/local/miniconda/conda-bld/xgboost_1563580806262/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place


The following NEW packages will be INSTALLED:

    ca-certificates: 2019.6.16-hecc5488_0 conda-forge
    libcxx:          8.0.0-4              conda-forge
    libcxxabi:       8.0.0-4              conda-forge
    libffi:          3.2.1-h6de7cb9_1006  conda-forge
    ncurses:         6.1-h0a44026_1002    conda-forge
    openssl:         1.1.1c-h01d97ff_0    conda-forge
    python:          3.6.7-h94afb7f_1005  conda-forge
    readline:        8.0-hcfe32e1_0       conda-forge
    sqlite:          3.29.0-hb7d70f7_0    conda-forge
    tk:              8.6.9-h2573ce8_1002  conda-forge
    xz:              5.2.4-h1de35cc_1001  conda-forge
    zlib:            1.2.11-h01d97ff_1005 conda-forge
```

Notice no `llvm-openmp`.

It is in the build env

```
## Package Plan ##

  environment location: /usr/local/miniconda/conda-bld/xgboost_1563580806262/_build_env


The following NEW packages will be INSTALLED:

    ca-certificates: 2019.6.16-hecc5488_0       conda-forge
    cctools:         895-h7512d6f_0             conda-forge
    clang:           4.0.1-h662ec87_0           defaults   
    clang_osx-64:    4.0.1-h1ce6c1d_16          defaults   
    clangxx:         4.0.1-hc9b4283_0           defaults   
    clangxx_osx-64:  4.0.1-h22b1bf0_16          defaults   
    compiler-rt:     4.0.1-h5487866_0           conda-forge
    curl:            7.65.3-h22ea746_0          conda-forge
    expat:           2.2.5-h6de7cb9_1003        conda-forge
    gettext:         0.19.8.1-h46ab8bc_1002     conda-forge
    git:             2.22.0-pl526hbdf3604_0     conda-forge
    krb5:            1.16.3-hcfa6398_1001       conda-forge
    ld64:            274.2-h7c2db76_0           conda-forge
    libcurl:         7.65.3-h16faf7d_0          conda-forge
    libcxx:          4.0.1-h579ed51_0           defaults   
    libcxxabi:       4.0.1-hebd6815_0           conda-forge
    libedit:         3.1.20170329-hcfe32e1_1001 conda-forge
    libffi:          3.2.1-h6de7cb9_1006        conda-forge
    libiconv:        1.15-h01d97ff_1005         conda-forge
    libssh2:         1.8.2-hcdc9a53_2           conda-forge
    llvm:            4.0.1-hc748206_0           conda-forge
    llvm-lto-tapi:   4.0.1-h6701bc3_0           conda-forge
    llvm-openmp:     8.0.0-h770b8ee_0           conda-forge
    make:            4.2.1-h1de35cc_2004        conda-forge
    ncurses:         6.1-h0a44026_1002          conda-forge
    openssl:         1.1.1c-h01d97ff_0          conda-forge
    perl:            5.26.2-haec8ef5_1006       conda-forge
    tk:              8.6.9-h2573ce8_1002        conda-forge
    zlib:            1.2.11-h01d97ff_1005       conda-forge
```

**Comment by jjhelmus** [comment]
In the example `xgboost` is both the name of the top level package and an output.  Merging the requirements is often problematic and it is unclear how this should be done.  Likely the easiest solution is to rename the top level package, for example to xgboost_split, to more cleanly differentiate the requirements needed for the sub-package and top-level package.

**Comment by beckermr** [comment]
Ohhhh. I did not realize conda is attempting to merge the requirements. I’ll try changing the top-level name to test.

**Comment by beckermr** [comment]
Should the default behavior be to not merge the requirements? I think this is less surprising to users and eliminates weird merges of envs.

I'm guessing y'all wanted this but there was some technical issue?

**Comment by beckermr** [comment]
FYI, I was nervous about renaming the top-level package (due to `conda-smithy` and rerendering). Instead, I went ahead and added `llvm-openmp` to the host env of the output with the same name and this worked great!

I am interested in the conversation above, but am closing this issue for now since it appears to not be a bug. Cheers and thanks for the help!
