### ISSUE TITLE
Load environment variables already for env setup

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#3629]
I'm trying to build some conda-packages behind a firewall, and not all links to the great wide internet work. In particular, installing a package like cudatools-dev requires downloading the cuda-installer. I [patched](https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/11) the recipe to allow for proxies, and now the installation works (provided the environment variables `PROXY_DEV_NVIDIA` and `PROXY_DEV_DOWNLOAD_NVIDIA` and the respective proxies are set up correctly).

However, I cannot use this package in another recipe and then build it, because conda build is very careful about reproducibility and therefore injection of environment variables. The [documentation](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#inherited-environment-variables) mentions how to inherit environment variables into the different build environment through adding `script_env` to `meta.yaml`, but they are not yet active during the *creation* of the environment.

Is it possible to load the `script_vars` already for the installation of the environment? And if not by default, would it be possible to add a switch (or some other way) to have them active already for the package installation stage?

**Comment by h-vetinari** [comment]
May I ask for a comment on this (pings based on recent [commits](https://github.com/conda/conda-build/commits/master))?
@rrigdon @jjhelmus @Bezier89 @jakirkham @mbargull 

Would a PR to enable this be accepted?

**Comment by jakirkham** [comment]
@h-vetinari, I don't review/merge PRs here. So will defer to others on whether it is reasonable.

**Comment by jjhelmus** [comment]
I would be in favor of a PR that made `script_env` variable active during environment creation.
