### ISSUE TITLE
xxxx@Robs-iMac:~> conda skeleton pypi imread --- error report

### ISSUE THREAD

**Issue by RobBW** [conda/conda-build#363]
Processing dependencies for imread==0.5.1
Finished processing dependencies for imread==0.5.1
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

The following NEW packages will be INSTALLED:

```
pyyaml: 3.11-py27_0
yaml:   0.1.4-1    
```

Linking packages ...
[                    ]|                                                  |   0%
[yaml                ]|                                                  |   0%
[pyyaml              ]|#########################                         |  50%
[      COMPLETE      ]|##################################################| 100%
Applying patch: '/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/tmpumdjlUconda_skeleton_imread-0.5.1.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/Users/robw/anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/Users/robw/Anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 188, in main
    args_func(args, p)
  File "/Users/robw/Anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/Users/robw/Anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 202, in execute
    pypi.main(args, parser)
  File "/Users/robw/Anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 376, in main
    get_package_metadata(args, package, d, data)
  File "/Users/robw/Anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 433, in get_package_metadata
    with open(join(tempdir, 'pkginfo.yaml')) as fn:
IOError: [Errno 2] No such file or directory: '/var/folders/jj/x_wp_0257_nfp529qm60f90h0000gn/T/tmpumdjlUconda_skeleton_imread-0.5.1.tar.gz/pkginfo.yaml'
robw@Robs-iMac:~> conda info
conda info
Current conda install:

```
         platform : osx-64
    conda version : 3.10.1
```

  conda-build version : 1.12.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /Users/robw/anaconda  (writable)
  default environment : /Users/robw/anaconda
     envs directories : /Users/robw/anaconda/envs
        package cache : /Users/robw/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by jiangxiluning** [comment]
it is same for me to build package
