### ISSUE TITLE
Creating a conda package with a custom install command

### ISSUE THREAD

**Issue by hgrecco** [conda/conda-build#3639]
I am trying to create a conda package for a python package that has a custom installation command. Running `python setup.py install` creates files that are then installed with the python package. But this does not happen when creating a wheel and therefore these files are not installed with conda. What is suggested way to deal with this?

**Comment by msarahan** [comment]
run `python setup.py install` in your conda recipe?

**Comment by hgrecco** [comment]
I am calling `pip install` in the conda recipe. Shouldn't that be the same?
