### ISSUE TITLE
Fully activate test environment prior to executing tests

### ISSUE THREAD

**Issue by tswicegood** [conda/conda-build#364]
For packages that rely on custom environment variables that are set as part of the activate / deactivate scripts you can't run tests and get reliable results without fully activating the environment.

**Comment by asmeurer** [comment]
I'm not saying we shouldn't implement this, but this is a perfect example of why making packages require to be activated to be usable is a bad thing.

**Comment by tswicegood** [comment]
@asmeurer it can be read both ways -- the linked GDAL issue is also a perfect example of why this is needed.  Without `GDAL_DATA` being set, we're shipping a gdal package that's partially broken.

**Comment by tacaswell** [comment]
I am trying to use conda packages to ship configuration data (which I have dumped into $PREFIX/etc) and am using a second package to export the real path to $PREFIX/etc as an ENV.
