### ISSUE TITLE
Enterprise users should be told to use anaconda-enterprise-cli

### ISSUE THREAD

**Issue by timsnyder** [conda/conda-build#3644]
### Actual Behavior

When I'm done building a package, conda-build tells me to use anaconda to upload to anaconda.org. 

### Expected Behavior

I'd like a few things:
1. be able to configure conda-build to tell users to use anaconda-enterprise-cli to upload to my internal AE server
1. be able to disable telling users about using anaconda cli to upload to anaconda.org (because it violates our security policy and we won't have it installed)
1. be able to automatically upload to the internal AE when configured to use it.

Since there may be AE users who might be able to upload to use both internal and external, I wouldn't want to assume that they are mutually exclusive.

If this is of interest to you guys, I would consider putting a PR together.

**Comment by msarahan** [comment]
Yep, this definitely sounds like a good improvement for enterprise users.  Any PR you have would be much appreciated, but I think we should do this regardless.

**Comment by timsnyder** [comment]
@msarahan do you also want a support ticket filed for this or is this issue enough?

**Comment by msarahan** [comment]
This is enough for me, but I'm not sure if a support ticket would also help any metrics that anyone is tracking.
