### ISSUE TITLE
conda-verify warning even with --no-verify

### ISSUE THREAD

**Issue by bryevdv** [conda/conda-build#3646]
### Actual Behavior

Running a conda build with `--no-verify` and without `conda-verify` installed produces a spurious warning:

> Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
928WARNING:conda_build.build:Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
929WARNING conda_build.build:bundle_conda(1042): Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.

### Expected Behavior

If `--no-verify` is supplied, there is no reason for this warning.

### Steps to Reproduce

Run a conda build with `--no-verify` and without `conda-verify` installed

### Output of `conda info`

```
CONDA_REQS="conda=4.7.10 conda-build=3.18.9" 
```
used on TravisCI

**Comment by marcelotrevisani** [comment]
Do you have a recipe which I can use as an example just to reproduce this problem?

**Comment by bryevdv** [comment]
Just the Bokeh one:

https://github.com/bokeh/bokeh/blob/master/conda.recipe

But to use this you'd have to build BokehJS first. I expect this happens with any recipe at all, even e.g. `conda skeleton` output from some simple PyPI package.
