### ISSUE TITLE
Add coveralls or codecov

### ISSUE THREAD

**Issue by marcelotrevisani** [conda/conda-build#3647]
Hi guys,

I am thinking to add [coveralls](https://coveralls.io/) or [codecov](https://codecov.io/) to ``conda-build``. Both are free for opensource projects and it might help to increase the test coverage and to have some insights about the code quality.

Should I add then?

If you see any PR on ``pytest`` you will see the ``codecov`` in action! It is pretty interesting!
:)

cc: @ocefpaf @msarahan

**Comment by marcelotrevisani** [comment]
I think I was not clear, but I would like to configure the ``codecov`` bot to every time to have insights about the PR which contributors will create

**Comment by msarahan** [comment]
We do have codecov set up.  https://codecov.io/gh/conda/conda-build

I personally find the messages in the comments a bit annoying, but a status indicator alongside the other CI's would be fine.

**Comment by msarahan** [comment]
Also, the work you are doing to help get back to passing tests is essential for getting the coverage info.  So thank you!
