### ISSUE TITLE
Compiled packages have over linking errors on windows

### ISSUE THREAD

**Issue by soapy1** [conda/conda-build#3655]
### Actual Behavior

build fails for packages requiring compilation when providing the `--error-overlinking` flag 

### Expected Behavior

package should build

### Steps to Reproduce
on windows
```
conda build numpy --error-overlinking 
```

**Comment by msarahan** [comment]
need more detail here - probably would be helpful to post a link.  That's probably to our internal CI, so no good for outside people, but the team can see it.

**Comment by jjhelmus** [comment]
I basic example is building [zlib](https://github.com/AnacondaRecipes/zlib-feedstock) on Windows.  Using conda build 3.18 with `--error-overlinking` result in a failed build with the following:
```
Packaging zlib
10:51:37
INFO:conda_build.build:Packaging zlib-1.2.11-h3cc03e0_4
10:51:37
INFO conda_build.build:bundle_conda(891): Packaging zlib-1.2.11-h3cc03e0_4
10:52:01
Packaging zlib-1.2.11-h3cc03e0_4
10:52:01
number of files: 9
10:52:01
  ERROR :: MSVCR90.dll not in prefix_owners
10:52:01
  ERROR (zlib,Library\bin\zlib.dll): MSVCR90.dll not found in any packages
10:52:01
   INFO (zlib,Library\bin\zlib.dll): Needed DSO $SYSROOT\System32\KERNEL32.dll found in the whitelist
10:52:01
overlinking check failed 
10:52:01
['  ERROR (zlib,Library\\bin\\zlib.dll): MSVCR90.dll not found in any packages']

**Comment by msarahan** [comment]
Yeah, I think that's a duplicate of https://github.com/conda/conda-build/issues/3650

**Comment by soapy1** [comment]
Link to ci for numba build https://concourse.build.corp.continuum.io/teams/main/pipelines/autobot_numba/jobs/numba-0.45.1-cxx_compiler_vs2008-python_2.7-c_compiler_vs2008-on-winbuilder/builds/1

**Comment by jjhelmus** [comment]
> Yeah, I think that's a duplicate of #3650

Agreed, the case sensitivity is the the issue.  

The other change is that prior to 3.18 overlinking checks were not done on Windows regardless of the setting of `--error-overlinking`.  This new behavior is good it will catch overlinking and missing dependencies but might trip up a few users.
