### ISSUE TITLE
Shebang in console scripts has changed

### ISSUE THREAD

**Issue by bretttully** [conda/conda-build#3670]
I'm creating a C++/python package using conda build. The console scripts that worked the last time I built the package (3 months ago) now no longer work because of the shebang.

### Actual Behavior

3 months ago, after installing with `conda create -n toffee-0-14-2-dev -c cmriprocan/label/dev toffee=0.14.2`, the console script looked like this:

```
#!/bin/sh
'''exec' /home/user/conda/envs/toffee-0-14-2-dev/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys

from toffee.conversion import mzml_to_toffee

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(mzml_to_toffee())
```

where `/home/user/conda/envs/toffee-0-14-2-dev/bin/python` is the environment into which the package was **installed**

Now, after installing with `conda create -n toffee-0-14-3-dev -c cmriprocan/label/dev toffee=0.14.3`, the console script looks like this:

```
#!/home/circleci/project/miniconda/conda-bld/toffee_1565647912068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from toffee.conversion import mzml_to_toffee

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(mzml_to_toffee())
```

where `/home/circleci/project/miniconda/conda-bld/toffee_1565647912068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python` is the path to the directory where the package was **built**. As you can imagine, when you try and run this script, an error is raised because that path no longer exists.

### Expected Behavior

Console scripts to continue to run.

### Output of `conda info`

Version 0.14.2 packages 
```
python:                 3.6.8-h0371630_0
conda:                  4.6.14-py36_0
setuptools:             41.0.1-py36_0
conda-build:            3.17.8-py36_0
```

Version 0.14.3 packages 
```
python:                 3.6.9-h265db76_0
conda:                  4.7.11-py36_0
pip:                    19.1.1-py36_0
setuptools:             41.0.1-py36_0
conda-package-handling: 1.3.11-py36_0
conda-build:            3.18.9-py36_0
```

**Comment by bretttully** [comment]
If I pin `conda=4.6.14` and `conda-build=3.17.8`, the console script during the **build** phase of `0.14.3` looks as follows:
```
#!/usr/bin/env python

# -*- coding: utf-8 -*-
import re
import sys

from toffee.conversion import mzml_to_toffee

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(mzml_to_toffee())
```

**Comment by jjhelmus** [comment]
Can you share the recipe you are using to build this package?  It looks like the build prefix is not being detected and/or marked.

**Comment by bretttully** [comment]
The main repo is here: https://bitbucket.org/cmriprocan/toffee -- the recipe is in the `.conda` directory, and the setup of the cached circleci environment is here: https://bitbucket.org/cmriprocan/toffee/src/dev/.circleci/setup.sh (note this is the now passing version that pins conda and conda-build).
