### ISSUE TITLE
"Could not locate executable cl.exe" when building package for Python 3.6 on Windows

### ISSUE THREAD

**Issue by seibert** [conda/conda-build#3673]
We discovered that building Numba using our usual development recipe:

https://github.com/numba/numba/tree/master/buildscripts/condarecipe.local

is failing with conda-build 3.18.x on our Windows build server only when we try to build Python 3.6 or 3.7, but not 2.7  We get this error at the end of the build process:
```
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I%PREFIX%\include -I%PREFIX%\include -I%PREFIX%\Library\include -I%PREF     IX%\Library\include /Tcnumba/_dynfuncmod.c /Fobuild\temp.win-amd64-3.6\Release\numba/_dynfuncmod.obj -g
Could not locate executable cl.exe
Executable cl.exe does not exist
```
Stepping back through released versions of conda build, we have determined that with conda build 3.17.8:
* works: `conda build --no-test --python=2.7 --numpy=1.11 buildscripts/condarecipe.local/`
* works:  `conda build --no-test --python=3.6 --numpy=1.11 buildscripts/condarecipe.local/`

conda-build 3.18.5:
* works: `conda build --no-test --python=2.7 --numpy=1.11 buildscripts/condarecipe.local/`
* _doesn't work_:  `conda build --no-test --python=3.6 --numpy=1.11 buildscripts/condarecipe.local/`

In all cases, this is with conda 4.7.11 installed.

**Comment by seibert** [comment]
Edits to make it clear that I'm talking about Windows builds.

**Comment by msarahan** [comment]
VS 2017 recipe was reworked a bit this past week to use Microsoft's "vswhere" tool.  @seibert if you could verify whether your problem is still present, it would be helpful.

**Comment by seibert** [comment]
Which conda-build do I need to install?  Latest from `conda-canary`?

**Comment by msarahan** [comment]
no change to conda-build is necessary.  It's just which compiler package gets pulled in at build time.  The latest is version 19.16.27032.1

**Comment by jjhelmus** [comment]
The default compiler used when building a Python 3 package on Windows changed in #3517 from **vs2015** to **vs2017**.  This change is present in conda-build 3.18.3 and later.  

If only VS 2015 is installed and not VS 2017 then a build would succeed using conda-build <3.18.3 but fail with conda-build >=3.18.3 as the `vs2017_win-64` package will attempt to activate the VS 2017 tools not the VS 2015 ones.

The compilers used can be specified explicitly in a `conda_build_config.yaml` file in the recipe directory or [other locations](https://conda.io/projects/conda-build/en/latest/resources/variants.html#creating-conda-build-variant-config-files).  The following specifies a matrix of three builds for Python 2.7, 3.6 and 3.7 with vs2008 being used for the Python 2.7 build and vs2015 for the 3.6 and 3.7 builds:

``` yaml
c_compiler:
  - vs2008
  - vs2015
  - vs2015
cxx_compiler:
  - vs2008
  - vs2015
  - vs2015
python:
  - 2.7
  - 3.6
  - 3.7
zip_keys:
  - c_compiler
  - cxx_compiler
  - python
```

**Comment by oleg-alexandrov** [comment]
Here getting the same issue. I have conda-build 3.22.0. In conda_build_config.yaml I see vs2017. Python version is 3.9.12. This is from a fresh install of miniconda for Windows.
