### ISSUE TITLE
Docs on activation scripts

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#3676]
Was looking for docs about activation scripts for conda recipes, but wasn't able to find anything in the conda-build docs. Not sure if I'm just overlooking things. If this is actually missing, it would be good to add. We could just copy over [the activate script section from the conda-forge docs]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#activate-scripts ). Otherwise if it is there and I missed it, would be good to add a link to that section from [Resources]( https://docs.conda.io/projects/conda-build/en/latest/resources/index.html ) where many other recipe features are discussed (including link scripts).

**Comment by jjhelmus** [comment]
This sounds like a great idea.  

@rrigdon can you take a look at this when you are back from vacation?

**Comment by rrigdon** [comment]
https://docs.conda.io/projects/conda-build/en/latest/resources/activate-scripts.html
