### ISSUE TITLE
Conda hijacks MACOSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by jfowkes** [conda/conda-build#3682]
What is the rationale for forcing `MACOSX_DEPLOYMENT_TARGET=10.9`? Xcode/Command Line Tools sets a perfectly good default that literally everything else uses. Why are you forcing compilation to a 6 year old OS version? Do you really think that by default users want to target Mavericks when everything else on their system almost surely uses the Xcode default and does not?

**Comment by mingwandroid** [comment]
Hi @jfowkes 

Conda doesn't 'hijack' anything really. Our compiler activation scripts, *when in use* (for they are optional) set this variable.

We do it to retain compatibility with macOS 10.9 for our users' benefit (though really people should update their systems).

> Why are you forcing compilation to a 6 year old OS version?

No one is forcing anyone to do anything here, everything is by choice. Can you explain that?

> Do you really think that by default ...

This is not in any sense 'by default', can you explain what you mean by that? This is what we do for the conda ecosystem (which I define as Anaconda Distribution, conda-forge and their downstreams).

To use system compilers, tools and SDKs you should avoid activating any conda environment that contains our compilers or else deactivate conda. If any of theis works then please give details.

**Comment by jfowkes** [comment]
Sorry I should have been clearer here: if I install Anaconda followed by a python package that compiles a python extension, then by default that extension is compiled for macOS 10.9.

This then causes major issues if that package links to something, let's say a fortran library, compiled with the system compiler, leading to many warnings of the form:
```
ld: warning: object file was built for newer OSX version (10.14) than being linked (10.9)
``` 

Are you saying then that Anaconda does not support linking to system compiled libraries?

**Comment by mingwandroid** [comment]
> Are you saying then that Anaconda does not support linking to system compiled libraries?

It does yes, to those from macOS 10.9 (though actually conda_build_config.yaml that both Anaconda Distribution and conda-forge uses now-a-days override this to 10.10 AFAIK).

Sorry this is only supportable on a best-effort basis and PRs to improve the situtation would be gratefully accepted (but this involves meddling with `cctools` and `ld64` which is a fair bit to learn and not for the feint of heart!), still, I shouldn't make any assumptions, maybe you know these things and would like to help out?

Do you have any concerns outside of not being able to use newer SDK libs?

**Comment by jfowkes** [comment]
Ah I see, thanks for the clarification. So you're saying that Anaconda doesn't require any SDKs to be installed and so chooses macOS 10.9/10.10 as the oldest supported for compatibility? 

My main concern is with setting 10.9/10.10 as the targeted SDK, I would have thought that a more sane default would be simply to target the currently installed OS version (as e.g. homebrew does).

**Comment by mingwandroid** [comment]
> would have thought that a more sane default would be simply to target the currently installed OS version (as e.g. homebrew does).

I don't use homebrew much, but last time I did, I saw that:

1. By and large (with the exception of bottles or whatever) homebrew compiles things from source on the end-users machine. This isn't what the Anaconda Distribution does, we're a we-make-the-binaries-for-you distro,

2. Homebrew *does* support binaries, in the form of bottles, and they compile them against a range of macOS SDKs so that people with old machines can use them.

If you're using our compilers you've in a way switched from a casual user to more of a developer and in that case you need to take some care. Our compilers and linkers pretty much pay attention only to the value of `CONDA_BUILD_SYSROOT` which I set to `/opt/MacOSX10.10.sdk` which you can get from phracker on github (though it'd be better if you can find a more official source, I cannot provide that for you).

**Comment by jfowkes** [comment]
I see thank you very much for the clarification, I wasn't aware that you were primarily a make-the-binaries-for-you distro and that your compilers were mostly intended for developers rather than casual users. In numerical computing we often need to link against legacy fortran code and so using the compilers is often inescapable. For this reason I generally use homebrew, although many of the users of my package use Anaconda as their python distribution of choice.

**Comment by mingwandroid** [comment]
We have Python. conda-forge is more up to date than Anaconda Distribution at present.

**Comment by jfowkes** [comment]
Thanks! I'll look into this as a potential way to go for my Anaconda users.
