### ISSUE TITLE
Patching sources does not allow moving files on OS X

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda-build#3690]
It seems that conda-build is using a different tool to apply patches on OS X from windows or linux, which does not support moving files.

**Linux:**

```
patching file atk/kernel.json.in (renamed from atk/kernel.json)
patching file setup.py
```

**OS X**

```
patching file atk/kernel.json
patching file setup.py
```

and then the build fails over the `kernel.json.in` missing.

CF Azure build https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=66493

**Comment by marcelotrevisani** [comment]
Unfortunately, I don't have a ``osx`` machine with which I can't reproduce this problem and debug it.
But as far as I know, the ``patch`` get the executable based on the path to the build prefix 
https://github.com/conda/conda-build/blob/4964e3b92df9ea319a1f4c82f1deb8539160c07b/conda_build/source.py#L579


This problem might be related to the ``patch`` tool on ``osx``. I might be wrong.

Probably @msarahan or @jjhelmus can give you more information about it

**Comment by mingwandroid** [comment]
As @marcelotrevisani pointed out
