### ISSUE TITLE
Requirements Section .a vs .so/.dylib/.dll

### ISSUE THREAD

**Issue by ax3l** [conda/conda-build#3694]
The requirements-section in [the user guide](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#run-exports) could maybe be improved with the following points.

I read it from the perspective of a C/C++ programmer and wonder at each point: does this apply for a) a shared lib b) a static library c) an executable. And what if a package builds all three of them?

**Export runtime requirements**: When it starts with "Export runtime requirements" please put in that a *static* library does not need "run_exports". Only dynamic/shared ones do. Also, one should write immediately that these exports are describing *oneself* for downstream consumers.

*Strong* exports are a corner-case that is absolutely too early in the docs, since users have not read yet the section below that introduces `build:`, `host:` and `run:`. Maybe change the order alltogether? First "Requirements section", then the additonal info on "Export runtime requirements" for dynamic packages/DSOs, etc.

**Requirements section**:
It misleadingly only makes comments about *shared libraries* which have to go into `host:` and *must be fitting the target architecture*. Both aspects are *also* true for static libraries and should be mentioned. Furthermore, one should state that *library dependencies* (both shared and static) go *exclusively* in `host:`. The current phrasing leaves open if *shared* library dependencies might also need to go into `run:`, which they don't.

As a recap for the Python-native reader, mention that binary python import modules are *always* shared libraries at this point.

Maybe also add explicitly a paragraph that `run_exports` are derived into each dependency of a dependency with the `ignore_run_exports` counter measure that is mentioned. Can go in the "Export runtime requirements" section that should follow now, *after* the "requirements section".

Thanks a lot for Q&A in the channel!

**Comment by ax3l** [comment]
@rrigdon thank you so much for the update in #3771, reads great!

**Comment by rrigdon** [comment]
Glad to hear it's helpful! I appreciate your input. :)
