### ISSUE TITLE
DOC: activate_in_script

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#3695]
Currently appears `activate_in_script` is not documented. Would be nice to have a brief blurb explaining its behavior.

**Comment by rrigdon** [comment]
This issue may provide useful info: https://github.com/conda/conda-build/issues/2735

**Comment by rrigdon** [comment]
We don't recommend using the activate_in_script option -- activation is the default and preferred path.

**Comment by jakirkham** [comment]
Ah ok. Good to know. Thanks! 😄
