### ISSUE TITLE
Tutorial Building Anaconda Navigator applications fails

### ISSUE THREAD

**Issue by spara** [conda/conda-build#3697]
**version:** conda 4.5.9
**description:** 

creating skeleton files fails
```
conda skeleton pypi roded
```
**error:**
`Request to fetch https://pypi.io/pypi/rodeo/json failed with status: 404`

yhat was acquired by alteryx and the package is no longer maintained.

**Comment by rrigdon** [comment]
This tutorial has been reworked and is functional - https://github.com/ContinuumIO/docs/pull/2300
https://docs.anaconda.com/anaconda/navigator/tutorials/nav-app/
