### ISSUE TITLE
Improved documentation on the version comparison code

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#3711]
_From @mcg1969 on March 23, 2016 21:19_

The current conda docs imply that the version comparison code mimics PEP 386:

http://conda.pydata.org/docs/spec.html#build-version-spec

This is out of date. In fact, thanks to @ukoethe, it mimics PEP 440, with some deliberate exceptions.

The [docstring for the VersionOrder class](https://github.com/conda/conda/blob/4.3.18/conda/version.py#L26) is probably the best documentation we have for the current implementation, and should be added to the documentation somehow, preferably in its own section.

cc: @jseabold @cel4 @ukoethe conda/conda#1107 conda/conda#2297 conda/conda#2300 conda/conda#1601

_Copied from original issue: conda/conda#2304_

**Comment by mcg1969** [comment]
@rrigdon PEP-440, actually, but yes, that's a start!

**Comment by rrigdon** [comment]
Dur, thank you!
