### ISSUE TITLE
Update conda skeleton pypi command

### ISSUE THREAD

**Issue by marcelotrevisani** [conda/conda-build#3716]
Should we use 
```
{{ PYTHON }} -m pip install . -vv
```
https://github.com/conda-forge/staged-recipes/#7-when-or-why-do-i-need-to-use--python---m-pip-install---vv

Instead of 
```
{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
```

on the conda skeleton pypi to generate the recipes?

Related to 
https://github.com/conda-forge/staged-recipes/pull/9444#discussion_r321696835

cc: @CJ-Wright

**Comment by CJ-Wright** [comment]
I'm thinking of doing something on the bot side which will also update existing pip commands using https://github.com/regro/cf-scripts/pull/577

**Comment by marcelotrevisani** [comment]
> I'm thinking of doing something on the bot side which will also update existing pip commands using [regro/cf-scripts#577](https://github.com/regro/cf-scripts/pull/577)

I might take a look at it as well. Thanks!

**Comment by marcelotrevisani** [comment]
Closing this in favor of #3717
