### ISSUE TITLE
Try to unquote the entries in the conda-skeleton generated recipe

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#3718]
I don't know when or why it was introduced but all the values are quoted now. That breaks conda-forge update bot. I believe that we can, at least, unquote the checksum, to make it easier for the bot to update it.

Ping @marcelotrevisani

**Comment by marcelotrevisani** [comment]
Would you like to unquote just the checksum or there are other fields which would be good to unquote as well?

**Comment by marcelotrevisani** [comment]
Closing it in favor of #3720
