### ISSUE TITLE
Prefer local builds over downloads

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#373]
Due to the well documented issues with Accelerate and forking ( https://github.com/ContinuumIO/anaconda-issues/issues/133 ), ( https://github.com/numpy/numpy/issues/4776 ) ( https://groups.google.com/forum/#!topic/comp.lang.python/b2Ayc8bQzMQ ), I tried to build `numpy` with a different BLAS that does not suffer from this problem. When an additional library was built, which required linkages to `numpy` and the BLAS, instead of using the built version of `numpy` that I had locally it downloaded a completely new version that was linked to Accelerate. Now, maybe there is a way to do this and I have missed it, but I think there should be a setting to prefer local builds over remote downloads. If there is, please let me know. If not, I really think this would be a nice feature to have as an end user.

**Comment by jakirkham** [comment]
@hajs, it seems that you may know something about how to do this. Do you have any thoughts?

**Comment by dan-blanchard** [comment]
You can specify `--use-local` as an argument to `conda install`.  You could also upload it to binstar and put your channel first in your `.condarc` file.

**Comment by jakirkham** [comment]
Thanks @dan-blanchard. I am aware of `--use-local` for `conda install` and am using this. You're probably right that I should upload the binaries.

So, to make sure I understand what you are suggesting are you saying I should install `numpy` and the BLAS into the `_build` environment before proceeding? I thought it should already be there from building them previously or am I mistaken?

I think part of the problem is I am using a slightly older version of `numpy` so it is upgrading (e.g. 1.9.0 to 1.9.2). Is there a good way to disallow that? I tried pinning the version, but seemed unable to find them.

**Comment by jakirkham** [comment]
Also, I have been trying to use this channel restriction on `conda build`, but it doesn't seem to find it. For example, `--override-channels -c file:///zopt/conda/conda-bld/`. I have tried one less `/`, but in both cases I get the following error:

    BUILD START: numpy-1.9.0-py27_1
    Fetching package metadata: ....
    Error: No packages found in current osx-64 channels matching: conda-build

**Comment by jakirkham** [comment]
I guess I am hoping to see something along the lines of prefer local when building if something already exists use it, but by all means find missing packages and install if necessary.

**Comment by asmeurer** [comment]
conda build does use effectively `--use-local` automatically, but it still prefers the newest version that it can find.

**Comment by jakirkham** [comment]
Is there some way that we can specify his this build of `numpy` is different? I wouldn't want to rename the package because if something requires `numpy` it wouldn't be met. However, I would prefer not to be surprised by a download of `numpy` linked to Accelerate.

**Comment by asmeurer** [comment]
I would use the `features` feature to indicate that this is a different numpy. This is how we already do it for the mkl-linked numpy. See http://conda.pydata.org/docs/build.html#features. You can also see how the mkl numpy works by looking through http://repo.continuum.io/pkgs/pro/osx-64/repodata.json.

**Comment by jakirkham** [comment]
Ok, that sounds like a good idea. I did notice features. However, I didn't have a great notion as to how this effects the dependencies. For instance, could I have a dependency that requires numpy with mkl or openblas instead of the vanilla version? Would this mean they have the feature, as well?

**Comment by asmeurer** [comment]
It should work correctly. The features seamless switches out the numpy installed in the environment, so that conda will always prefer versions with the given feature.

**Comment by jakirkham** [comment]
I think features solves this. Thanks again for your help.
