### ISSUE TITLE
Skipping selectors in description

### ISSUE THREAD

**Issue by xhochy** [conda/conda-build#3751]
In https://github.com/conda-forge/autotools_clang_conda-feedstock we are using `# [win]` selectors in the description of the package. They are used there to highlight the usage of the package itself, not to render a platform-specific README. Is there a way to avoid rendering the selectors / Jinja in the description and rather pass it as-is to the README?

**Comment by marcelotrevisani** [comment]
You can try to put it in quotes to avoid it, but I think the result will be the same.
But indeed that is unusual behavior, since it is just description
