### ISSUE TITLE
What object does `source.provide` expect as input?

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#3763]
It seems that https://github.com/conda/conda-build/blob/master/conda_build/source.py#L628 wants something special, what type is that?

**Comment by msarahan** [comment]
recipe metadata dictionary.  MetaData.meta

You're pretty deep in internals, there - be careful.

**Comment by CJ-Wright** [comment]
I needed something to find and extract the source code associated with a recipe.
