### ISSUE TITLE
subpackage tests are not installing parent requirements in 3.18.10

### ISSUE THREAD

**Issue by beckermr** [conda/conda-build#3777]
### Actual Behavior

The tests of the multiple outputs in package `d` do not install the parent test requirements per the documentation.

### Expected Behavior

The tests of the multiple outputs in package `d` should install the parent test requirements per the documentation.

### Steps to Reproduce

See this package here: https://github.com/beckermr/conda-tests/tree/master/recipes/pkg_d

Build packages `a`, `b` and `x` colocated with `pkg_d` above. Then build package `d`. You will see that it does not install package `x` when testing the package `d` outputs.

##### `Output of conda info`

```
     active environment : base
    active env location : /home/circleci/miniconda
            shell level : 1
       user config file : /home/circleci/.condarc
 populated config files : /home/circleci/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.10
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/circleci/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/circleci/miniconda/pkgs
                          /home/circleci/.conda/pkgs
       envs directories : /home/circleci/miniconda/envs
                          /home/circleci/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-1043-aws debian/8 glibc/2.19
                UID:GID : 3434:3434
             netrc file : None
           offline mode : False
```

**Comment by beckermr** [comment]
Well this is rather frustrating. The documentation is just wrong relative to the code. Outputs simple have a test section that contains any of the fields from the parent plus the script field.

From this line here:

https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L1923

you can see the test section is simply copied in.

As far as I can tell, it is never modified to inherit from the parent one. The docs say

> Test requirements for subpackages are not supported. Instead,
subpackage tests install their runtime requirements---but not the
run requirements for the top-level package---and the test-time
requirements of the top-level package.

around here https://github.com/conda/conda-build/blob/master/docs/source/resources/define-metadata.rst#subpackage-tests.

**Comment by beckermr** [comment]
I made a pr to fix the docs since the current behavior is totally fine.

**Comment by marcelotrevisani** [comment]
Related to #3778
