### ISSUE TITLE
DOC: copy/paste issue?

### ISSUE THREAD

**Issue by michaelaye** [conda/conda-build#3781]
https://github.com/conda/conda-build/blob/master/docs/source/user-guide/recipes/debugging.rst#usage has twice a very similar looking section, is this a copy/paste mistake? I cannot make sense of it otherwise.

**Comment by marcelotrevisani** [comment]
I was taking a look a bit further on that and I think it is ok
Those messages are different. The first one is regarding the build env and the second is about the test environment
their output might be similar but they are slight different

Should I close this or do you want to discuss it? Or do you think there is something wrong there?

**Comment by michaelaye** [comment]
Well, I tried “conda debug .” and I only get the 2nd block? That’s what creates the confusion.
