### ISSUE TITLE
really long prefix path

### ISSUE THREAD

**Issue by yannpaul** [conda/conda-build#379]
I'm trying to create an environment in a path that is 166 characters long. This is longer than the 'long_prefix_build_path' value used for building conda packages. There appears to be a discussion of this issue in several places, specifically #40, #123, #163 

The last change is here: https://github.com/conda/conda-build/commit/e883b7317da3b8407c4f9c949eacea3947e67524#diff-ba343c116f2df712f571a28c16577543

Why aren't several subdirectories used, as suggested in #123?

Replace https://github.com/conda/conda-build/blob/master/conda_build/config.py#L44 with something like:

```
# somewhere near top of module
# arbitrary values, but as constants avoids magic numbers
MAX_PATH_LEN = 256 
N_PREFIX_SUBDIRS = 20
# at line 44
long_build_prefix = max(short_build_prefix, join(*([short_build_prefix,] + ['_placeholder',] * N_PREFIX_SUBDIRS))[:MAX_PATH_LEN])
```

**Comment by asmeurer** [comment]
We need to merge https://github.com/conda/conda-build/pull/351. It hasn't been done yet because it would require rebuilding anything built with the older setting.

**Comment by yannpaul** [comment]
I might be mistaken, but that change still has a limit that is too short for my case. I currently have a work around where I point `CONDA_ENS_PATH` to a really really long path. This makes `short_build_prefix` really long, and therefore `long_build_prefix` as well (because of the `max` call).

**Comment by yannpaul** [comment]
Also, I don't understand why it affects old builds? Are you saying #351 only affects package builds going forward and does not solve the issue for already built packages, or is there something else I'm missing? If it is the case, then I don't thing the merge will affect any of the old packages and could probably be accepted, but I still think it's not a solution in my case.

**Comment by asmeurer** [comment]
Anything longer than that will cause issues on Linux, where shebang lines cannot exceed 127 characters (see http://www.in-ulm.de/~mascheck/various/shebang/#length). So any entry point that gets installed will basically be broken.  On OS X the limit is much larger, but we haven't considered that such things would be necessary (and anyway on OS X there can be other issues if you try to use paths that are too long without setting the right compiler flags).

**Comment by asmeurer** [comment]
If we merge #351, any new package that is built with binary prefix replacement will not be able to build depend on an old package that was built with the shorter long prefix. All the build dependencies would have to be rebuilt.

**Comment by asmeurer** [comment]
It's something that should be done. It's just something I was putting off because it will be a little bit of work to do it.

**Comment by yannpaul** [comment]
I see, thanks for the clarification....

**Comment by msarahan** [comment]
This should be resolved with conda-build 2.  Closing.
