### ISSUE TITLE
Feature request: show rendered run dependencies

### ISSUE THREAD

**Issue by minrk** [conda/conda-build#3798]
This is a feature request for easier auditing/debugging, especially on CI.

I've made some mistakes over the years in packages that resulted in the wrong runtime dependencies, for example:

- assuming deps use run_exports
- unusual results from using the wrong one of pin_run_as_build or pin_subpackage
- pinning build but not version *overrides* version pinning on conda_build_config (e.g. `hdf5 * mpi_*`)

These are all my mistakes (to varying degrees), but result in successfully built and tested packages that don't have the dependencies I expect or intend. Often these mistakes don't turn up until much later when a dependency package is updated. I'd have an easier time catching these if I could see the resulting dependencies of the recipe.

One simple version is to explicitly do `conda render` in conda-forge CI, but it might be nice to include some or all of this in conda-build output by default, particularly `requirements.run` and `build.run_exports`, which cannot currently be tested properly.

**Comment by msarahan** [comment]
Sure, that seems like totally reasonable output after the rendering phase completes.  A PR would be welcome, and otherwise we'll try to work it in.

**Comment by marcelotrevisani** [comment]
I think that is nice indeed
Should we add an option like ``conda build . --verbose`` and it will show those extra info ?

**Comment by msarahan** [comment]
I'd be fine with this being new default behavior, and having a flag to squelch it if so desired.

**Comment by minrk** [comment]
I'll definitely do this eventually if nobody else gets to it, but I'd love to be beaten to the punch since I'm currently half-time on parental leave and falling further behind every week.

**Comment by wolfv** [comment]
we have something like this in boa now -- you can check the screencast in the readme. github.com/thesnakepit/boa
