### ISSUE TITLE
Test against multiple python versions

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#3827]
It would be nice if we could do something like:

```
conda build --test --python 2.7  /path/to/noarch/foo-1.0.0-py_0.tar.bz2
conda build --test --python 3.7  /path/to/noarch/foo-1.0.0-py_0.tar.bz2
```

and test a `noarch` package built with one Python version with another Python version.

See https://github.com/conda-forge/kombu-feedstock/issues/24 for some context.

Pinging @marcelotrevisani here who may be interested in looking into this.

**Comment by marcelotrevisani** [comment]
That is interesting indeed! But this is just for those ``noarch`` packages right? or do you think "normal" packages will be good to have this feature as well?

I am thinking that we might use a new subsection in ``tests`` which we can specify python versions in the recipe which will run the tests for ``noarch`` pkgs, or is it too much? haha

**Comment by marcelotrevisani** [comment]
Or maybe the ``tests`` for ``noarch`` should test the whole python versions available for that package
