### ISSUE TITLE
Publish py38 build of conda-build?

### ISSUE THREAD

**Issue by aldanor** [conda/conda-build#3835]
Now that conda 4.8.0 is available for py38, could conda-build be possibly released as py38 as well (so e.g. it could be installed into py38 root environments).

(Skimming over the list of dependencies, it looks like the only package that will need updating is lief / py-lief)

**Comment by aldanor** [comment]
@msarahan Any plans in regards to this? Given that conda is now published as py38 in anaconda channel, could conda-build catch up as well? Thanks.

**Comment by marcelotrevisani** [comment]
I think we can release it to Python 3.8 as well.
However, it would be better to enable our tests for Python 3.8 first. After that, I think we can generate the packages for Python 3.8
