### ISSUE TITLE
GCC from conda does not work on CentOS 6.3

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#384]
It appears the `gcc` version provided by `conda` does not play well on CentOS 6.3. In particular, it seems to be searching for some symbol `__locale_t`, which is not present. This may be a consequence of building `gcc` on CentOS 5.x; however, there could be other causes. ( https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52922 ) Here is a particular instance of this problem, which occurs when trying to build `numpy`. However, this error can be found when building other packages, as well.

    Removing old build directory
    Removing old work directory
    BUILD START: numpy-1.9.2-py27_2
    Fetching package metadata: ......
    Solving package specifications: .
    The following packages will be downloaded:
    
        package                    |            build
        ---------------------------|-----------------
        openblas-0.2.14            |              670         6.7 MB
    
    The following NEW packages will be INSTALLED:
    
        cloog:      0.18.0-0    
        gcc:        4.8.2-2     
        gmp:        5.1.2-2     
        isl:        0.12.2-0    
        mpc:        1.0.1-0     
        mpfr:       3.1.2-0     
        openblas:   0.2.14-670  
        openssl:    1.0.1k-1    
        pip:        6.1.1-py27_0
        python:     2.7.9-2     
        readline:   6.2-2       
        setuptools: 15.1-py27_1 
        sqlite:     3.8.4.1-1   
        system:     5.8-2       
        tk:         8.5.18-0    
        zlib:       1.2.8-0     
    
    Fetching packages ...
    openblas-0.2.1 100% |################################################################################################################################| Time: 0:00:00 145.99 MB/s
    Extracting packages ...
    [      COMPLETE      ]|###################################################################################################################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|###################################################################################################################################################| 100%
    Removing old work directory
    Source cache directory is: /home/vagrant/miniconda/conda-bld/src_cache
    Found source in cache: numpy-1.9.2.tar.gz
    Extracting download
    Package: numpy-1.9.2-py27_2
    source tree in: /home/vagrant/miniconda/conda-bld/work/numpy-1.9.2
    ++ uname
    + [[ Linux == \D\a\r\w\i\n ]]
    + DYLIB_EXT=so
    + CC=gcc
    + CXX=g++
    + export LAPACK=/home/vagrant/miniconda/envs/_build/lib/libopenblas.so
    + LAPACK=/home/vagrant/miniconda/envs/_build/lib/libopenblas.so
    + export BLAS=/home/vagrant/miniconda/envs/_build/lib/libopenblas.so
    + BLAS=/home/vagrant/miniconda/envs/_build/lib/libopenblas.so
    + test -f /home/vagrant/miniconda/envs/_build/lib/libopenblas.so
    + test -f /home/vagrant/miniconda/envs/_build/lib/libopenblas.so
    + unset LDFLAGS
    + CC=gcc
    + CXX=g++
    + /home/vagrant/miniconda/envs/_build/bin/python setup.py install
    Running from numpy source directory.
    /home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
      warnings.warn(msg)
    non-existing path in 'numpy/distutils': 'site.cfg'
    non-existing path in 'numpy/f2py': 'docs'
    non-existing path in 'numpy/f2py': 'f2py.1'
    /bin/sh: svnversion: command not found
    F2PY Version 2
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['/home/vagrant/miniconda/envs/_build/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    openblas_info:
      FOUND:
        libraries = ['openblas']
        library_dirs = ['/home/vagrant/miniconda/envs/_build/lib']
        language = f77
    
      FOUND:
        libraries = ['openblas']
        library_dirs = ['/home/vagrant/miniconda/envs/_build/lib']
        language = f77
    
    /bin/sh: svnversion: command not found
    non-existing path in 'numpy/lib': 'benchmarks'
    lapack_opt_info:
    openblas_lapack_info:
    C compiler: cc
    
    creating /tmp/tmpBBnXol/tmp
    creating /tmp/tmpBBnXol/tmp/tmpBBnXol
    compile options: '-c'
    cc: /tmp/tmpBBnXol/source.c
    cc /tmp/tmpBBnXol/tmp/tmpBBnXol/source.o -L/home/vagrant/miniconda/envs/_build/lib -lopenblas -o /tmp/tmpBBnXol/a.out
      FOUND:
        libraries = ['openblas']
        library_dirs = ['/home/vagrant/miniconda/envs/_build/lib']
        language = f77
    
      FOUND:
        libraries = ['openblas']
        library_dirs = ['/home/vagrant/miniconda/envs/_build/lib']
        language = f77
    
    /home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.linux-x86_64-2.7
    creating build/src.linux-x86_64-2.7/numpy
    creating build/src.linux-x86_64-2.7/numpy/distutils
    building library "npymath" sources
    customize Gnu95FCompiler
    Found executable /home/vagrant/miniconda/envs/_build/bin/gfortran
    customize Gnu95FCompiler
    customize Gnu95FCompiler using config
    C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
    
    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/vagrant/miniconda/envs/_build/include/python2.7 -c'
    gcc: _configtest.c
    gcc _configtest.o -o _configtest
    success!
    removing: _configtest.c _configtest.o _configtest
    C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
    
    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/vagrant/miniconda/envs/_build/include/python2.7 -c'
    gcc: _configtest.c
    _configtest.c:1:5: warning: conflicting types for built-in function 'exp' [enabled by default]
     int exp (void);
         ^
    gcc _configtest.o -o _configtest
    _configtest.o: In function `main':
    /home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/_configtest.c:6: undefined reference to `exp'
    collect2: error: ld returned 1 exit status
    _configtest.o: In function `main':
    /home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/_configtest.c:6: undefined reference to `exp'
    collect2: error: ld returned 1 exit status
    failure.
    removing: _configtest.c _configtest.o
    C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
    
    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/vagrant/miniconda/envs/_build/include/python2.7 -c'
    gcc: _configtest.c
    _configtest.c:1:5: warning: conflicting types for built-in function 'exp' [enabled by default]
     int exp (void);
         ^
    gcc _configtest.o -lm -o _configtest
    success!
    removing: _configtest.c _configtest.o _configtest
    creating build/src.linux-x86_64-2.7/numpy/core
    creating build/src.linux-x86_64-2.7/numpy/core/src
    creating build/src.linux-x86_64-2.7/numpy/core/src/npymath
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npymath/npy_math.c
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npymath/ieee754.c
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npymath/npy_math_complex.c
    building library "npysort" sources
    creating build/src.linux-x86_64-2.7/numpy/core/src/npysort
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npysort/quicksort.c
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npysort/mergesort.c
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npysort/heapsort.c
    creating build/src.linux-x86_64-2.7/numpy/core/src/private
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/private/npy_partition.h
      adding 'build/src.linux-x86_64-2.7/numpy/core/src/private' to include_dirs.
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npysort/selection.c
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/private/npy_binsearch.h
    conv_template:> build/src.linux-x86_64-2.7/numpy/core/src/npysort/binsearch.c
    None - nothing done with h_files = ['build/src.linux-x86_64-2.7/numpy/core/src/private/npy_partition.h', 'build/src.linux-x86_64-2.7/numpy/core/src/private/npy_binsearch.h']
    building extension "numpy.core._dummy" sources
    Generating build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h
    C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
    
    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/vagrant/miniconda/envs/_build/include/python2.7 -c'
    gcc: _configtest.c
    In file included from /home/vagrant/miniconda/envs/_build/include/python2.7/Python.h:38:0,
                     from _configtest.c:1:
    /usr/include/string.h:548:5: error: unknown type name '__locale_t'
         __locale_t __loc)
         ^
    /usr/include/string.h:552:18: error: unknown type name '__locale_t'
          size_t __n, __locale_t __loc)
                      ^
    In file included from /home/vagrant/miniconda/envs/_build/include/python2.7/Python.h:38:0,
                     from _configtest.c:1:
    /usr/include/string.h:548:5: error: unknown type name '__locale_t'
         __locale_t __loc)
         ^
    /usr/include/string.h:552:18: error: unknown type name '__locale_t'
          size_t __n, __locale_t __loc)
                      ^
    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "setup.py", line 251, in <module>
        setup_package()
      File "setup.py", line 243, in setup_package
        setup(**metadata)
      File "/home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/numpy/distutils/command/install.py", line 60, in run
        r = old_install.run(self)
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/numpy/distutils/command/build.py", line 39, in run
        old_build.run(self)
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/numpy/distutils/command/build_src.py", line 153, in run
        self.build_sources()
      File "/home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/numpy/distutils/command/build_src.py", line 170, in build_sources
        self.build_extension_sources(ext)
      File "/home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/numpy/distutils/command/build_src.py", line 329, in build_extension_sources
        sources = self.generate_sources(sources, ext)
      File "/home/vagrant/miniconda/conda-bld/work/numpy-1.9.2/numpy/distutils/command/build_src.py", line 386, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 432, in generate_config_h
        moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
      File "numpy/core/setup.py", line 42, in check_types
        out = check_types(*a, **kw)
      File "numpy/core/setup.py", line 293, in check_types
        "Cannot compile 'Python.h'. Perhaps you need to "\
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

**Comment by jakirkham** [comment]
This may fix it. ( https://github.com/conda/conda-recipes/pull/279 )

**Comment by jakirkham** [comment]
Correction, this does fix it. ( https://github.com/conda/conda-recipes/pull/279 ) Tested on CentOS 6.3.

**Comment by asmeurer** [comment]
How did you test it? Did you build it on an earlier CentOS and run it on 6.3?

**Comment by jakirkham** [comment]
Fair question. By tested I mean, I used the `gcc` compiler from @stuarteberg's channel.

**Comment by stuarteberg** [comment]
@asmeurer, specifically, he used the `gcc-no-fixincludes` package from my channel, which is simply a copy of your `gcc` package, except for the removal of the "fixincludes" headers.

**Comment by jakirkham** [comment]
I think it include your linking steps, as well. Correct?

**Comment by stuarteberg** [comment]
It depends on when you downloaded it.  I don't think the `post-link.sh` step will help or hurt in the CentOS case.  It was added for Ubuntu's benefit.

**Comment by msarahan** [comment]
@jakirkham is this really a conda-build issue?  Or should it be moved over to anaconda-issues?

**Comment by jakirkham** [comment]
This is year old issue. Let me revisit and determine its relevance

**Comment by jakirkham** [comment]
Yeah, I think this is already solved as @stuarteberg's work was merged and is included in the current `gcc` package. In any event, I don't build `numpy` this way any more.
