### ISSUE TITLE
Intermittent ChecksumMismatchError for locally built package

### ISSUE THREAD

**Issue by jontwo** [conda/conda-build#3859]
### Actual Behavior

We build a conda package and distribute it internally on our own conda channel. We use Jenkins CI to create a new build and update the channel for each commit. 

Every so often, a user tries to `conda install` the package and it fails with a ChecksumMismatchError.

```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'http://channelserver:85/prod/win-64/jbagdal-2.2.0-py36_vc14h830ac7b_0.tar.bz2'.
  download saved to: C:\bin\Miniconda3\pkgs\jbagdal-2.2.0-py36_vc14h830ac7b_0.tar.bz2
  expected sha256: 82240e245a1a3e2931f2c2a80a4a6f729d18da544d127f96591706bcdd70b182
  actual sha256: 2a7a320f8e606224dfd4bba03d81c6e6b817ce3f95089d418103ca17d310fa73
```

### Expected Behavior

`conda install` should install the package without error.

### Steps to Reproduce

It's a tricky one to reproduce, because sometimes the checksums are ok and sometimes they are not. We've tried reindexing the channel, with
```
conda index \\path\to\conda\channel -c
```
and this sometimes fixes the problem and sometimes does not. I ran it this morning and it seems that `index.html` in the `win-64` subdirectory was not updated. Maybe this is the problem?

```
09/12/2019  18:32    <DIR>          .
09/12/2019  18:32    <DIR>          ..
09/12/2019  18:32           101,235 repodata2.json
13/01/2020  14:57            41,908 index.html
29/01/2020  09:19            89,568 repodata.json
29/01/2020  09:19            10,674 repodata.json.bz2
             119 File(s)    649,870,617 bytes
               3 Dir(s)  498,415,505,408 bytes free
```

Eventually, the problem does go away, I think when Jenkins does another build and updates the channel. So, sorry I can't give a better repro case, but as far as I can tell the problem is that sometimes `conda build` and/or `conda index` do not update the expected checksums properly.

##### `Output of conda info`

```
     active environment : c:\jenkins2\env\Farmmap_conda_windows
    active env location : c:\jenkins2\env\Farmmap_conda_windows
            shell level : 1
       user config file : C:\Users\jontwo\.condarc
 populated config files : C:\bin\Miniconda3\.condarc
                          C:\Users\jontwo\.condarc
                          c:\jenkins2\env\Farmmap_conda_windows\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\bin\Miniconda3  (writable)
           channel URLs : http://channelserver:85/prod/win-64
                          http://channelserver:85/prod/noarch
                          http://channelserver:85/dev/win-64
                          http://channelserver:85/dev/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\bin\Miniconda3\pkgs
                          C:\Users\jontwo\.conda\pkgs
                          C:\Users\jontwo\AppData\Local\conda\conda\pkgs
       envs directories : C:\bin\Miniconda3\envs
                          C:\Users\jontwo\.conda\envs
                          C:\Users\jontwo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Windows/201
2ServerR2 Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False

```
Not sure why it says conda-build is not installed (this is info for base conda?), because `conda list` says
```
conda                     4.6.14                   py37_0    conda-forge
conda-build               3.17.8                   py37_1    conda-forge
conda-verify              3.1.1                 py37_1000    conda-forge
```

**Comment by jontwo** [comment]
We're still getting this error occasionally. Has no-one else at all seen it? Calling `conda build` again to update the channel index seems to fix it, but I've no idea why we should have to do this.

**Comment by forrestwaters** [comment]
If you are building a new package but keeping the version the same, you really should bump the build number in the recipe to avoid this. If you keep the version and build number the same, but change the package contents, there are a lot of reasons why you could end up with this error(caching, conda index not detecting an update being needed for repodata.json, etc).

**Comment by jontwo** [comment]
That makes sense. You would have thought running another build would cause the problem, not fix it.

**Comment by jontwo** [comment]
We have a workaround for this issue - using the `--skip-existing` parameter when we call `conda build`. This prevents the CI from mistakenly trying to build a package that has already been done.

This is not a fix though - I think if conda is going to rebuild an existing package, it should also update the channel index with the new checksum.
