### ISSUE TITLE
Conda-build imposes undesired version constraints on Qt libraries.

### ISSUE THREAD

**Issue by dschreij** [conda/conda-build#3864]
### Actual Behavior

When qtpy is a dependency, conda build appears to automatically add version constraints that result in incompatibility. For example, building one of our packages [python-qnotifications](https://github.com/dschreij/opensesame-conda-recipes/blob/master/python-qnotifications/meta.yaml) results in the following index.json:

{
  "arch": null,
  "build": "py_2",
  "build_number": 2,
  "depends": [
    "pyqt >=5.12.3,<5.13.0a0",
    "python",
    "qt >=5.12.5,<5.13.0a0",
    "qtpy"
  ],
  "license": "GNU General Public License v3 (GPLv3)",
  "name": "python-qnotifications",
  "noarch": "python",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 1577968165878,
  "version": "2.0.3"
}
This is incompatible with Python 2, for which these versions of PyQt are not available. This happens for all packages that have qtpy as a run dependency, which right now are [python-qnotifications](https://github.com/dschreij/opensesame-conda-recipes/blob/master/python-qnotifications/meta.yaml) and [python-qdatamatrix](https://github.com/dschreij/opensesame-conda-recipes/tree/master/python-qdatamatrix). I'm building with conda-build 3.18.11 and conda 4.7.12 on Ubuntu 19.10.

As a (deeply unsatisfying) workaround, I'm manually removing these version constraints before uploading the package. That works.

### Expected Behavior

Conda-build should not impose version constraints on Qt libraries.

### Steps to Reproduce
- Clone [our repo with conda recipes](https://github.com/dschreij/opensesame-conda-recipes/) (used in channel cogsci)
- Build one of [python-qnotifications](https://github.com/dschreij/opensesame-conda-recipes/tree/master/python-qnotifications), [python-qosf](https://github.com/dschreij/opensesame-conda-recipes/tree/master/python-qosf) or [python-qdatamatrix](https://github.com/dschreij/opensesame-conda-recipes/tree/master/python-qdatamatrix).

##### `Output of conda info`

```

```

**Comment by forrestwaters** [comment]
Where are you getting pyqt from? If from conda-forge, those version constraints are being added because of https://github.com/conda-forge/pyqt-feedstock/blob/master/recipe/meta.yaml#L33

**Comment by marcelotrevisani** [comment]
If you are using ``conda-forge`` channel, I would recommend you to add your package to the ``conda-forge`` as well
https://github.com/conda-forge/staged-recipes/

**Comment by dschreij** [comment]
Thanks @forrestwaters for that mention. So we could circumvent this pinning by ignoring the run_exports statement?

@marcelotrevisani I didn't want to clutter conda-forge with many personal packages, although OpenSesame is a very popular experiment builder that installs really well from conda. So you're right as to say that it probably belongs there to. I will push the required recipes to `staged-recipes`

**Comment by forrestwaters** [comment]
Yes, ignoring run exports would likely work. Though it is there for compatibility reasons so you'll need to be sure the package still works with older versions..
