### ISSUE TITLE
Unable to force the Visual Studio 2017 compiler for a python 2.7.15 build of yt

### ISSUE THREAD

**Issue by ianww** [conda/conda-build#3873]
Following an initial problem solved at #3872, I have built yt against python 2.7.15 using `conda build --python 2.7.15 yt` followed by `conda install --use-local yt`.

However, I realised that `conda build` compiled yt's python 2.7.15 using Visual Studio 2008, when I need it to be compiled with Visual Studio 2017 (to be compatible with the python 2.7.15 running in Houdini, into which I want to import yt).

I therefore followed the instructions here:
```
https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#using-your-customized-compiler-package-with-conda-build-3
```

I edited the `conda_build_config.yaml` inside `C:\ProgramData\Miniconda2\pkgs\yt-3.5.1-py27hc997a72_0\info\recipe` to replace `c_compiler: vs2008 ` with `c_compiler: vs2017` and `cxx_compiler: vs2008 ` with `cxx_compiler: vs2017` and `vc: '9'` with `vc: '14.16'`.

However, when I then ran `conda build --python 2.7.15 yt`, I noticed the following messages during the build:
```
%SRC_DIR%>set "vc=9"
%SRC_DIR%>set "cxx_compiler=vs2008"
%SRC_DIR%>echo "Found VS2008 at"
"Found VS2008 at"
%SRC_DIR%>echo "C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\"
"C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\"
%SRC_DIR%>SET "VS_VERSION=9.0"
%SRC_DIR%>SET "VS_MAJOR=9"
%SRC_DIR%>SET "VS_YEAR=2008"

```
So, the build was using `Visual Studio 2008` rather than the `Visual Studio 2017` that I specified in the `conda_build_config.yaml` edits.

I'm obviously doing something wrong but I don't know what!  

During the build, I've noticed that the entire `yt-3.5.1-py27hc997a72_0` directory in `C:\ProgramData\Miniconda2\pkgs` disappears and then is overwritten with a fresh version.  Inside that, the `conda_build_config.yaml` in `C:\ProgramData\Miniconda2\pkgs\yt-3.5.1-py27hc997a72_0\info\recipe` has reverted back to its original Visual Studio 2008 settings.

I don't know how to stop that happening.  

I'm not even sure how `yt-3.5.1-py27hc997a72_0` gets into `C:\ProgramData\Miniconda2\pkgs` in the first place.  I've tried deleting it prior to restarting my sequence of commands leading up to `conda build` again and have noticed that it reappears when I install prerequisite dependencies:
```
conda install -c conda-forge cython git sympy ipython numpy matplotlib netCDF4
```
For some reason, yt is also getting installed with these, even though it's not specified.  I don't know why.  It might be because of something I've done way back and now forgotten...

The overwriting of `yt-3.5.1-py27hc997a72_0` with a fresh version seems to be wiping out the `conda_build_config.yaml` edits, preventing the compiler being changed from Visual Studio 2008 to Visual Studio 2017.

Alternatively, could the reversion to Visual Studio 2008 be because I'm editing the wrong `conda_build_config.yaml` file?  But I can't find another one - for example, there's no yt package in my env's `.../Lib/site-packages.`  Or maybe I need to do an edit to my env's `meta.yaml` file as well as to the `conda_build_config.yaml`?

I'd appreciate your suggestions.

**Comment by mingwandroid** [comment]
> when I need it to be compiled with Visual Studio 2017 (to be compatible with the python 2.7.15 running in Houdini, into which I want to import yt)

If you need yt to run in houdini's python interpreter then the anaconda distribution should not be used for this task. It comes with its own interpreters.

**Comment by msarahan** [comment]
It's hard to say exactly from only your description, but I think you have
your conda_build_config.yaml file in a place that conda-build is not
finding it.  There are docs on the search paths here:
https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#creating-conda-build-variant-config-files

**Comment by ianww** [comment]
Thanks for those suggestions.

> If you need yt to run in houdini's python interpreter then the anaconda distribution should not be used for this task. It comes with its own interpreters.

Yes, Houdini has its own python 2.7.15 interpreter compiled with Visual Studio 2017, which is why I need to build yt against a VS2017-compiled python 2.7.15, so that I can import yt into Houdini and run it using the Houdini interpreter.

>  I think you have your conda_build_config.yaml file in a place that conda-build is not
finding it

Thanks, that was my lack of understanding.  I've now moved my `conda_build_config.yaml` file to be next to my `meta.yaml` file.  It looks like conda-build now sees it because I get this message:
```
INFO:conda_build.variants:Adding in variants from C:\ProgramData\Miniconda2\envs\myyt3\yt\conda_build_config.yaml
```
I now get this conflicts error:
```
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from C:\ProgramData\Miniconda2\envs\myyt3\yt\conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from C:\ProgramData\Miniconda2\envs\myyt3\yt\conda_build_config.yaml
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for yt
INFO:conda_build.metadata:Attempting to finalize metadata for yt
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
```
My interpretation of this is that conda-build is matching up package metadata from the three variant sources of `internal defaults`, my `conda_build_config.yaml` and `config.variant` and finds conflicts between the three.

After the above output, conda-build then outputs:
```
Examining vs2015_runtime[version='>=14.16.27012,<15.0a0']:  86%|ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûî | 6/7 [00:01<00:00,  4.47it/
Examining vs2015_runtime[version='>=14.16.27012,<15.0a0']: 100%|ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûê| 7/7 [00:01<00:00,  4.32i
Examining conflict for numpy python cython vc setuptools vs2015_runtime:  14%|ΓûêΓûì        | 1/7 [00:00<00:00,  9.62it/
Examining conflict for numpy python cython vc setuptools vs2015_runtime:  29%|ΓûêΓûêΓûè       | 2/7 [00:00<00:00, 19.23i
Examining conflict for cython setuptools numpy:  29%|ΓûêΓûêΓûè       | 2/7 [00:00<00:00, 19.23it/s] failed , 12.44it/s]
```
followed by this error traceback:
<details><p><summary>Error traceback</summary>

```

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\cli\main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\cli\main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\build.py", line 2344, in build_tree
    notest=notest,
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\build.py", line 1335, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\render.py", line 746, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\metadata.py", line 2048, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\metadata.py", line 722, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\render.py", line 527, in finalize_metadata
    exclude_pattern)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\render.py", line 412, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\render.py", line 378, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda_build\environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\resolve.py", line 1318, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
    bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
    root, search_node, dep_graph, num_occurances)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
    last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\models\match_spec.py", line 481, in union
    return cls.merge(match_specs, union=True)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\models\match_spec.py", line 475, in merge
    reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
    reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
    final = this_component.union(that_component)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\models\match_spec.py", line 764, in union
    return '|'.join(options)
TypeError: sequence item 0: expected string or Unicode, Channel found

```
</p></details>

I suspected that a/the source of the conflicts was that conda-build is using `vs2015_runtime` while I'm specifying a VS2017 compiler in my `conda_build_config.yaml` file.

I therefore installed `vs2017_runtime` to my env using `conda install -c peterjc123 vs2017_runtime` in accordance with [https://anaconda.org/peterjc123/vs2017_runtime](url), and reran conda-build but conda-build still used `vs2015_runtime` and I got the same errors.

I thought about using the `.condarc` file to somehow force conda-build to use `vs2017_runtime` but I couldn't find any command to do this with.

So, I'm at a loss as to how to overcome my errors.

FYI, here are my `meta.yaml` and `conda_build_config.yaml` files.

<details><p><summary>meta.yaml</summary>

```

{% set version = "3.5.1" %}
{% set sha256 = "c8ef8eceb934dc189d63dc336109fad3002140a9a32b19f38d1812d5d5a30d71" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: http://yt-project.org/sdist/yt-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py -q install --single-version-externally-managed --record=record.txt
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython >=0.24.0
    - setuptools >=19.6
  run:
    - setuptools
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - sympy
    - matplotlib
    - ipython

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - munkm


```
</p></details>

<details><p><summary>conda_build_config.yaml</summary>

```

c_compiler: vs2017
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- ignore_build_only_deps
- extend_keys
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python- numpy
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: 2.7.15
r_base: '3.4'
target_platform: win-64
vc: '14.16' #matches MSVC++ 14.16 _MSC_VER == 1916 (Visual Studio 2017 version 15.9)
#Also tried 15.4 to match vs2017_runtime-15.4.27004.2010-1


```
</p></details>


I'd be grateful for further help!

**Comment by mingwandroid** [comment]
> Yes, Houdini has its own python 2.7.15 interpreter compiled with Visual Studio 2017, which is why I need to build yt against a VS2017-compiled python 2.7.15, so that I can import yt into Houdini and run it using the Houdini interpreter.

The anaconda distribution is of no use for this then. You should use the houdini interpreter only and ask the company that made it about your issues.

**Comment by ianww** [comment]
Sorry, I know you've closed this off but can I trouble you with this question please - why wouldn't a conda build of yt with python 2.7.15 compiled using VS2017 allow me to import it into Houdini (or any other python software) which also uses python 2.7.15 compiled with VS2017?

**Comment by mingwandroid** [comment]
Each installation of Python is built slightly differently, but actually, the Houdini one is built very differently, electing to use a different newer C-Runtime than is standard for Python 2.7.

These C-Runtimes are incompatible. Objects cannot be passed between them safely because their layouts and sizes differ.

For that reason, you should not load both into the same process.

But, that's just another gotcha here specific to Windows.

The Python software building ecosystem (such that that is something we could define) uses the running python executable for two reasons, both to drive the build (and compilation of any C/C++) and as the final install location for packages (the site-packages dir).

Mixing two very different Pythons here is not something you should do. The houdini Python should be the interpreter in charge of building the software that it will eventually run. This applies to any 3rd party interpreters.

The only way I see to reasonably use `conda-build` to _help_ you (as opposed to introduce a whole set of different problems) - though I also question if this is necessary in the first place, why not just pip install yt from source from the houdini Python interpreter? - would be if you were to make a special `houdini-python` package and use that in your host env during the build.

**Comment by mingwandroid** [comment]
For sure, closed doesn't mean discussion cannot continue, nor is it permanent. In this case I currently see this as inadvisable and out-of-scope.

**Comment by ianww** [comment]
OK, many thanks for that advice - another big learning step for me!  I'll look into the pip approach.  Windows seems to be quite a problem with Houdini - building OpenVDB for it was a real effort, although I got there in the end.

Another option I have is to dual boot and do it all with Linux, which seems to be more straight forward.

I've got some thinking and more learning to do!

Thanks again.
