### ISSUE TITLE
MD5 checking argument not passed to update_index

### ISSUE THREAD

**Issue by desilinguist** [conda/conda-build#388]
I was happy to see that there was a `-c` argument to `conda index` which forces it to use md5 hashes instead of file modification times. However, looks like `main_index.py` never passes that argument on to the `update_index()` function, i.e., 

```python
...
update_index(path, verbose=(not args.quiet), force=args.force)
...
````

should actually be:

```python
...
update_index(path, verbose=(not args.quiet), force=args.force, check_md5=args.check_md5)
...
```

**Comment by asmeurer** [comment]
@dan-blanchard

**Comment by dan-blanchard** [comment]
Okay, I just submitted a PR to fix it.  Sorry about that.
