### ISSUE TITLE
Post-link script output is ill-formatted

### ISSUE THREAD

**Issue by leofang** [conda/conda-build#3883]
Hello, we were working on conda-forge/openmpi-feedstock#56 and we noticed that the messages from our post-link script were not shown when the CI finished building and entered the testing phase. We tried writing directly to `stdout` and also to `$PREFIX/.messages.txt`,  but none succeeded. Can someone take a look for us and see what we may did wrong? Thanks!

cc: @jakirkham

**Comment by jakirkham** [comment]
Sorry had forgotten about the manual installation of the post-link scripts. 😅 Thanks for bearing with me Leo 🙂

Some thoughts on how we might improve this process after revisiting it.

Would be helpful if `[pre|post]-link.[sh|bat]` scripts were automatically installed (saves the user figuring out this step).

Also it appears that writing to `$PREFIX/.messages.txt` is expected, but undocumented (as Leo found). So it would be helpful to have some docs on this subject for users unfamiliar.

**Comment by leofang** [comment]
Alright, I read the doc again: 
https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html
and apparently both things (the installation path of the pre-/post- link scripts and the output to `$PREFIX/.messages.txt`) are documented. 

But, it didn't say explicitly that the recipe maintainers must install the pre-/post- link scripts in the recipe; I thought this is an automatic thing and this is what I failed to recognize...

**Comment by leofang** [comment]
Another issue is that if the link scripts print out multi-lines, it'd be concatenated to a one-liner, see  https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=126303&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=21371 for the PR conda-forge/openmpi-feedstock#56.

**Comment by leofang** [comment]
> Another issue is that even if the link scripts print out multi-lines, it'd still be concatenated to a one-liner, see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=126303&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=21371
> for the PR [conda-forge/openmpi-feedstock#56](https://github.com/conda-forge/openmpi-feedstock/pull/56).

See the example here: https://github.com/conda-forge/openmpi-feedstock/pull/56#issuecomment-610443656

**Comment by leofang** [comment]
Migrated this issue to conda/conda#9819 as Matt suggested it is the right place. Closing this one...
