### ISSUE TITLE
--python option ignored in certain cases

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda-build#3902]
I have the following in my `meta.yaml` file (conda-build 3.18.11):
```
requirements:
  host:
    - python >=3.6
```
Now, when I run the recipe using `conda-build --python=3.6`, I would expect that the most recent python 3.6 is used.  However, python 3.8 is being used, and I get a package with `py38` in the build string.  When I remove the version spec, that is:
```
requirements:
  host:
    - python
```
The `--python 3.6` option is respected.

**Comment by msarahan** [comment]
This goes back to how conda-build special-cases Python, which I'm pretty
sure goes back to "abts".  I remember this tripped me up when I first
started at Continuum.  It hasn't changed since then.  Version constraints
on python work on noarch packages, but not elsewhere.

**Comment by ilanschnell** [comment]
Thanks, yes this probably goes back a long time.  Anyhow, it's a low priority issue which hopefully one day will get addressed.
