### ISSUE TITLE
REGR: Conda build breaks in presence of pyproject.toml on aarch/ppc64le

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#3919]
There were weird build-errors in conda-forge/cvxpy-feedstock#30 and conda-forge/cvxpy-feedstock#31, where the aarch/ppc64le builds would seemingly try to install (and compile!) numpy/scipy etc.

Turns out that they were listed under `pyproject.toml`, and now the build tried to install them from scratch. Note that this was swallowed silently before, because the same [underlying files](https://github.com/cvxgrp/cvxpy/blob/v1.0.27/pyproject.toml) went through on conda-forge/cvxpy-feedstock#29.

Now however it actually breaks on aarch/ppc64le, with errors that were fairly hard to figure out. Could it be that conda-build upgraded its internal `pip`-version or something?

I first tried to comment out the affected requirements in `pyproject.toml`, but even the presence of an empty file, the build will then try to install setuptools/wheel (see [here](https://www.python.org/dev/peps/pep-0518/#build-system-table), also xref #3507). This resulted in the even weirder error that `numpy` wasn't found _despite_ being listed as a build requirement.

On a side-note, I seem to remember getting errors when setuptools tried to install [dependencies](https://github.com/cvxgrp/cvxpy/blob/master/setup.py#L72-L77). This has also not produced an error in the cvxpy-build for some time at least.

CC @scopatz, since you were caught off guard by it as well.

**Comment by isuruf** [comment]
Might be a duplicate of https://github.com/conda/conda-build/issues/2951

**Comment by jjhelmus** [comment]
Did this end up being cause by a non-activated environment rather than conda-build?

**Comment by h-vetinari** [comment]
@jjhelmus 
these jobs failed on azure in the linked PR. Not sure how the mechanism failed exactly, but it was reproducibly only in case that `pyproject.toml` existed.
