### ISSUE TITLE
python packages using setuptools not updating shebang with conda prefix

### ISSUE THREAD

**Issue by sugdms** [conda/conda-build#3920]
### Actual Behavior

Python packages that use setuptools (setup.py) do not install properly if built with 3.19. The file that gets installed to `$CONDA_PREFIX/bin/scriptname` (setup.py specifies `entry_points` with `console_scripts` pointing to a python file) is not getting the shebang line updated to match the CONDA_PREFIX, so it cannot find the python interpreter. After extracting the tarball and comparing to the same code built with 3.18.12, the info/paths.json does not have the `prefix_placeholder` key for the script file which I suspect is the problem.

### Expected Behavior

The installed $CONDA_PREFIX/bin/scriptname file has the shebang line updated to point to the python interpreter in the containing environment.

### Steps to Reproduce

Build a conda python package that uses setuptools with conda-build 3.19 or 3.19.1 such that the package test invokes the installed script file, e.g. if setuptools installs a python script called `my-test` as a console script, the test should invoke `my-test`. The script should fail to find the python interpreter.

I tried downgrading setuptools to 46.0 from 46.1.3 and it made no difference. I tried conda-build 3.19 and 3.19.1 and neither worked. It works with conda-build 3.18.12.

##### `Output of conda info`

```
     active environment : base
    active env location : /home/user/miniconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.1
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /home/user/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/3.10.0-1062.12.1.el7.x86_64 rhel/7.7 glibc/2.17
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by gonzalocasas** [comment]
We tried rebuilding our conda-forge feedstock ([compas](https://anaconda.org/conda-forge/compas/)) with the newly released 3.19.2; but the problem persists:
1. Installed `compas 0.15.5` on a newly created conda env on Windows. Conda resolves to use `win-64::compas-0.15.5-py38h32f6830_1` which was built with 3.19.2
2. Execute one of the console entry points: `compas_rpc start`
3. Fails with the following error (indicating a hard coded path still present in the build): 
```
Fatal error in launcher: Unable to create process using '"d:\bld\compas_1585838190617\_h_env\python.exe"  "C:\Users\gcasas\Anaconda2\envs\test-compas-015\Scripts\compas_rpc.exe" start': The system cannot find the file specified.
```

Should we re-open this issue or open a new one?
