### ISSUE TITLE
running conda index gives different list of dependencies

### ISSUE THREAD

**Issue by tathagata** [conda/conda-build#3923]
### Actual Behavior
Running `conda index` on a local mirror produces a different `depends` section in `repodata.json` and `current_repodata.json`. I would like them to be the same as what is served from https://repo.continuum.io/pkgs/main/linux-64/, with the obvious exception of packages released during running `conda index` locally.
Am I missing a step or any flag while creating the index?

```
{'build': 'hdf63c60_0',
 'build_number': 0,
 'depends': [],
 'license': 'GPL',
 'md5': '238f19c803a6ba7bd6dbd6989e03cbf1',
 'name': 'libgcc-ng',
 'sha256': 'c6fafbe73d2f93b91b6f4b65829f925f52a8f84746a57abd216b39da9ce8c494',
 'size': 8496776,
 'subdir': 'linux-64',
 'timestamp': 1560112207081,
 'version': '9.1.0'}
```

### Expected Behavior

```
{'build': 'hdf63c60_0',
 'build_number': 0,
 'depends': ['_libgcc_mutex * main'],
 'license': 'GPL',
 'md5': '80a23105874059534307086faae566c5',
 'name': 'libgcc-ng',
 'sha256': '9f867b7bf107d4999f91b7f6a4f930c25e82a859013fba4ded608d78f7da5aa9',
 'size': 5304005,
 'subdir': 'linux-64',
 'timestamp': 1560112207081,
 'version': '9.1.0'}
```
As see on https://anaconda.org/main/libgcc-ng/files
<img width="918" alt="Screen Shot 2020-03-31 at 7 40 48 PM" src="https://user-images.githubusercontent.com/68151/78085195-43e44000-7388-11ea-9d3c-d8d6075d9869.png">

### Steps to Reproduce
- download all `tar.bz2` and `.conda` packages from https://repo.continuum.io/pkgs/main/
- run `conda index ` on `path/to/main` to generate the following files in `linux-64` directory
```
current_repodata.json
current_repodata.json.bz2
repodata.json
repodata.json.bz2
repodata_from_packages.json
repodata_from_packages.json.bz2
```
- create a new conda environment
```
(base) ubuntu@ip-10-0-0-174:~$ conda create -n env1 python=3.6.10 --dry-run
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /ubuntu/anaconda3/envs/env1

  added / updated specs:
    - python=3.6.10


The following NEW packages will be INSTALLED:

  ca-certificates    main/linux-64::ca-certificates-2020.1.1-0
  certifi            main/linux-64::certifi-2019.11.28-py36_1
  ld_impl_linux-64   main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             main/linux-64::libffi-3.2.1-h4deb6c0_3
  libgcc-ng          main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            main/linux-64::ncurses-6.2-he6710b0_0
  openssl            main/linux-64::openssl-1.1.1f-h7b6447c_0
  pip                main/linux-64::pip-20.0.2-py36_1
  python             main/linux-64::python-3.6.10-hcf32534_1
  readline           main/linux-64::readline-8.0-h7b6447c_0
  setuptools         main/linux-64::setuptools-46.1.3-py36_0
  sqlite             main/linux-64::sqlite-3.31.1-h7b6447c_0
  tk                 main/linux-64::tk-8.6.8-hbc83047_0
  wheel              main/linux-64::wheel-0.34.2-py36_0
  xz                 main/linux-64::xz-5.2.4-h14c3975_4
  zlib               main/linux-64::zlib-1.2.11-h7b6447c_3



DryRunExit: Dry run. Exiting.

```

- `wget` the `repodata.json`, `current_repodata.json` etc. files listed above from https://repo.continuum.io/pkgs/main/linux-64/ and replace the existing ones in `linux-64`, with these remote `repodata.json`, `current_repodata.json` etc. files

```
(base) ubuntu@ip-10-0-0-174:~$ conda create -n env1 python=3.6.10 --dry-run
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /ubuntu/anaconda3/envs/env1

  added / updated specs:
    - python=3.6.10


The following NEW packages will be INSTALLED:

  _libgcc_mutex      main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    main/linux-64::ca-certificates-2020.1.1-0
  certifi            main/linux-64::certifi-2019.11.28-py36_1
  ld_impl_linux-64   main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            main/linux-64::ncurses-6.2-he6710b0_0
  openssl            main/linux-64::openssl-1.1.1f-h7b6447c_0
  pip                main/linux-64::pip-20.0.2-py36_1
  python             main/linux-64::python-3.6.10-hcf32534_1
  readline           main/linux-64::readline-8.0-h7b6447c_0
  setuptools         main/linux-64::setuptools-46.1.3-py36_0
  sqlite             main/linux-64::sqlite-3.31.1-h7b6447c_0
  tk                 main/linux-64::tk-8.6.8-hbc83047_0
  wheel              main/linux-64::wheel-0.34.2-py36_0
  xz                 main/linux-64::xz-5.2.4-h14c3975_4
  zlib               main/linux-64::zlib-1.2.11-h7b6447c_3



DryRunExit: Dry run. Exiting.
```
`_libgcc_mutex` is now added to the list of packages needed to create the virtual environment.
Comparing the `packages` section of `repodata.json` that is generated by running `conda index` locally, with the one served from https://repo.continuum.io/pkgs/main/linux-64/repodata.json, there are1 `14282` have same `depends` section, while `1869` do not have the same. Some examples:

```
['libstdcxx-ng >=7.2.0', 'numpy >=1.9.3,<2.0a0', 'python >=3.5,<3.6.0a0']
['libstdcxx-ng 7.2.0.*', 'numpy >=1.9.3,<2.0a0', 'python >=3.5,<3.6.0a0']
********
['libgcc-ng >=7.3.0', 'openssl >=1.1.1a,<1.1.2a', 'readline >=7.0,<8.0a0', 'unixodbc >=2.3.7,<2.4.0a0']
['libgcc-ng >=7.3.0', 'openssl >=1.1.1,<1.1.2.0a0', 'readline >=7.0,<8.0a0', 'unixodbc >=2.3.7,<2.4.0a0']
```

##### `Output of conda info`

While the above was done with `3.18.9`, I upgraded to `3.19.1` from `conda-canary` channel. 
```
(base) ubuntu@ip-10-0-0-174:~$ conda info

     active environment : base
    active env location : /ubuntu/anaconda3
            shell level : 1
       user config file : /ubuntu/.condarc
 populated config files : /ubuntu/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.1
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.23
       base environment : /ubuntu/anaconda3  (writable)
           channel URLs : file:///conda/conda110/main/linux-64
                          file:///conda/conda110/main/noarch
          package cache : /ubuntu/anaconda3/pkgs
                          /ubuntu/.conda/pkgs
       envs directories : /ubuntu/anaconda3/envs
                          /ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.4 Linux/4.4.0-1002-fips ubuntu/16.04.2 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

I tested running `conda index` with just two packages  -  `libffi-3.2.1-hd88cf55_4.tar.bz2` and `libgcc-ng-9.1.0-hdf63c60_0.tar.bz2`. These two packages are necessary for creating a new environment, and have different values in `packages` section in `repodata.json`. The behavior is same in 3.8.11 and 3.19.1.

In case it helps, the following snippet will list out the package depends same and different.
`repodata_local` is `json.loads` of the `repodata.json` generated locally by `conda index` and `repodata_remote` is what we get 

```
same_dependency_count, diff_dependency_count=0,0
for pkg, metadata in repodata_local['packages'].items():
    if repodata_remote['packages'][pkg]['depends']==metadata['depends']:
        same_dependency_count+=1
        print("No DIFF!!!", pkg)
        print(sorted(repodata_remote['packages'][pkg]['depends']))
        print(sorted(metadata['depends']))
        print("*"*10)
    else:
        print("MISMATCH!!!", pkg)
        diff_dependency_count+=1
        print(sorted(repodata_remote['packages'][pkg]['depends']))
        print(sorted(metadata['depends']))
        print("*"*10)
```

**Comment by tathagata** [comment]
For future reference, if people get into this situation trying to create a local mirror, here are some notes.
 
Creating an index on your local mirror is not complete if you don't patch the package metadata (held in `repodata.json`).
  From the README of https://github.com/AnacondaRecipes/repodata-hotfixes

_When packages are created, authors do their best to specify constraints that make their package work. Sometimes things change, and their constraints are not accurate for making things work. This results in broken environments. People need to be able to patch the package metadata long after the packages are built, so that we can prevent conda from creating broken environments. This repository holds python scripts that generate JSON files, which are then applied on top of the repodata.json index files that are generated from the original package content._

In order to patch the metadata, `conda index` provides two flags  

```
  -p PATCH_GENERATOR, --patch-generator PATCH_GENERATOR
                        Path to Python file that outputs metadata patch
                        instructions
  --hotfix-source-repo HOTFIX_SOURCE_REPO
                        URL of git repo that hosts your metadata patch
                        instructions
```
For me `--hotfix-source-repo` did not work, so I had to use the `-p` option.

- The patched metadata is stored in the [repodata-hotfixes](https://github.com/AnacondaRecipes/repodata-hotfixes) repository mentioned above.  checkout t
the repository locally.
```
git clone https://github.com/AnacondaRecipes/repodata-hotfixes
```
_If you are not immediately running `conda index`, after this step, then make sure your checkout is not stale, i.e. do a `git pull` if it has been a few days since you last checked out._

- run indexing
```
conda index --verbose --threads 10 -p /path/to/repodata-hotfixes/main.py /path/to/main
```
This should generate `patch_instructions.json` under each of the platforms you have under `main` directory i.e. `linux-64`, `noarch` etc.

Note this has to be done for each channel your mirror servers. For my `r` channel,
```
conda index --verbose --threads 10 -p /path/to/repodata-hotfixes/r.py /path/to/r
```  

`repodata-hotfixes` has patches for packages from `free`, `main`, `msys2`, `r` and `pro` channels. For `conda-forge` channels you'll need to download the latest version of [conda-forge-repodata-patches](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) and then index with `-p`.

```
conda install -c  conda-forge conda-forge-repodata-patches
```
This downloads the packages to /path/to/anaconda3/pkgs/conda-forge-repodata-patches-20200330-py38_0.tar.bz2.
```
conda index --verbose -p /path/anaconda3/pkgs/conda-forge-repodata-patches-20200330-py38_0.tar.bz2 conda-forge
```
Its not obvious from the docs, however the `-p` takes .tar.bz2 as well ... thanks to @jjhelmus for pointing this out on the gitter channel.

**Comment by jjhelmus** [comment]
I've updated the help text in the conda index cli in #3931 to better describe these two flags.

**Comment by tathagata** [comment]
#3877 does a great job of enhancing the documentation on indexing.
