### ISSUE TITLE
[python] console script entry points not working / include hardcoded path

### ISSUE THREAD

**Issue by gonzalocasas** [conda/conda-build#3927]
### Actual Behavior

Python projects containing console script entry points can end up in with some paths hardcoded from the conda-build environment. See [this issue](https://github.com/compas-dev/compas/issues/503) for a concrete example.

Trying to run the entry point script returns an error indicating the file cannot be found, and the path indicated seems to be coming from the conda build CI environment:

```
(test-entry-point-script) C:\Users\gcasas>compas_rpc start
Fatal error in launcher: Unable to create process using '"d:\bld\compas_1585838190617\_h_env\python.exe"  "C:\Users\gcasas\Anaconda2\envs\test-entry-point-script\Scripts\compas_rpc.exe" start': The system cannot find the file specified.
```

`d:\bld\compas_1585838190617\_h_env\` -> that looks like carried over from the CI where the package was built.

I thought this bug was fixed in `conda build 3.19.2` (based on bug #3920), but even after having rebuilt the package with it, the issue still persists.

### Expected Behavior

The console script should work. ;)

### Steps to Reproduce

For one example of this behavior as of today, try the `compas` package:
1. Install `compas` in a fresh environment with `conda create -n test-entry-point-script compas python=3.8`.  **Make sure the installed build number of at least `1` (eg `compas-0.15.5-py38h32f6830_1`), which was built with `conda build 3.19.2`.**
2. Activate the environment: `conda activate test-entry-point-script`
2. Try to run the entry point script: `compas_rpc start`

##### `Output of conda info`
```
     active environment : test-entry-point-script
    active env location : C:\Users\gcasas\Anaconda2\envs\test-entry-point-script
            shell level : 2
       user config file : C:\Users\gcasas\.condarc
 populated config files : C:\Users\gcasas\.condarc
          conda version : 4.6.3
    conda-build version : 3.17.5
         python version : 2.7.14.final.0
       base environment : C:\Users\gcasas\Anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\gcasas\Anaconda2\pkgs
                          C:\Users\gcasas\.conda\pkgs
                          C:\Users\gcasas\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\gcasas\Anaconda2\envs
                          C:\Users\gcasas\.conda\envs
                          C:\Users\gcasas\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.3 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
This bug is eluding me at present. I did fix an issue with prefix replacement on Windows, but it's not actually something I believe we have ever done on Windows, even in these launcher scripts. I think it's more likely that we are losing the creation of `-script.py` trampoline programs and I'm trying to figure out where or why that's happened.

It is claimed that the problems started with version 0.15.5, but I tested the previous version as follows and had the same issue:

```
conda create -n compas-cf0154 -c conda-forge compas=0.15.4
conda activate compas-cf0154
compas_rpc
Fatal error in launcher: Unable to create process using '"d:\bld\compas_1583449331556\_h_env\python.exe"  "C:\opt\conda\envs\compas-cf0154\Scripts\compas_rpc.exe" ': The system cannot find the file specified.
```

Can anyone verify this and point me to a working old build? There's likely something else at play here though. We *should not* and *can not* replace prefixes in binaries on Windows.

**Comment by gonzalocasas** [comment]
@mingwandroid thanks for checking this out. I checked practically every single `compas` build from 0.15.5 down to 0.11.0 (in which the `compas_rpc` entry point was introduced), and in none of them is this script working. That makes little sense to me, but now I'm questioning whether this ever worked in a conda install, and perhaps I've only seen it working in `pip -e install`s ?

**Comment by mingwandroid** [comment]
@jjhelmus pointed out to me earlier that this is because you are required to identify the entry points to conda-build when using setuptools.

I would like to do something more automatic though when we have time, but I'm not sure what exactly. At the very least, setuptools could avoid emitting the full path to the python interpreter into the stub executables.

**Comment by gonzalocasas** [comment]
Sorry for the confusion then, this was never a `conda-build` bug, the entry points were not declared in the `compas` recipe and this was never tested properly on a conda non-source install, it seems.
