### ISSUE TITLE
Infinite loop due to subtle difference between version spec "==0.1" and "0.1"

### ISSUE THREAD

**Issue by stuarteberg** [conda/conda-build#393]
I accidentally found a way to make `conda build` enter an infinite loop.  Specify an "exact" build dependency version in meta.yaml (e.g. `mydependency 0.1`), but then provide a corresponding recipe that *almost* matches the version requirement (e.g. `version: "0.1.0"`).

Enter these commands into your own terminal to trigger the infinite loop:

```
$ mkdir aaa bbb

$ cat > aaa/meta.yaml
package:
    name: aaa
    version: "0.1.0"

$ cat > bbb/meta.yaml
package:
    name: bbb
    version: "0.1"
requirements:
    build:
      - aaa 0.1

$ conda build bbb # INFINITE LOOP
```

The loop can be avoided by using a relational operator (`aaa ==0.1`) to specify the version of the dependency:

```
requirements:
    build:
      - aaa ==0.1
```

I guess a possible fix to conda-build might be to assume that "exact" version specifications are treated as if there were an implicit `==` present.  I'm not exactly sure what the repercussions of that would be.

**Comment by asmeurer** [comment]
Yeah, I've known about this for some time. We should check in the main_build recursive dependency loop that we don't try to rebuild a recipe more than once.

**Comment by stuarteberg** [comment]
Here's another way (slightly different) to trigger the loop, involving a custom build string (might make a good test case when this bug is eventually fixed):

```
$ mkdir aaa bbb

$ cat > aaa/meta.yaml
package:
    name: aaa
    version: "0.1.0"
build:
    string: custom_string

$ cat > bbb/meta.yaml
package:
    name: bbb
    version: "0.1"
requirements:
    build:
      - aaa ==0.1.0 custom_string

$ conda build bbb # INFINITE LOOP
```

Unlike the case above, the loop here can be avoided by *removing* the relational operator:

```
requirements:
    build:
      - aaa 0.1.0 custom_string
```

**Comment by pelson** [comment]
Incidentally, I think the naive dependency resolution can be drastically improved, as I have done in conda-build-missing. See https://github.com/pelson/conda-build-missing/blob/master/conda_build_missing/__init__.py#L100-L125. I'd be happy to integrate this properly into conda-build.

**Comment by asmeurer** [comment]
Improvements to it are welcome.

**Comment by rmcgibbo** [comment]
@pelson: i wrote a similar thing that does toposort on the recipes in a directory, and builds in a good order the packages that don't currently exist on anaconda.org. might be useful to consolidate efforts  https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all
