### ISSUE TITLE
Testing scripts in `bdist_conda`

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#394]
It would be nice if there were an automatic way to test scripts with `python setup.py bdist_conda`. I am thinking running each one with `--help`. Any thoughts?

**Comment by asmeurer** [comment]
There is a way to do this. Use 

```py
setup(
...
distclass=distutils.command.bdist_conda.CondaDistribution,
conda_command_tests=['command --help'],
...
)
```

See http://conda.pydata.org/docs/bdist_conda.html#setup-options.

**Comment by jakirkham** [comment]
Ah ok, great. Sorry for my ignorance. Thanks for the link.

**Comment by jakirkham** [comment]
So, what I had in mind was something more along the lines of this ( https://github.com/conda/conda-build/pull/400 ). If you want it disabled by default for backwards compatibility or have other feedback, I'm happy to make changes to it.
