### ISSUE TITLE
Use consistent prefix for intermediate files

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#3948]
### Actual Behavior

I am building a Python package. My recipe is templating the build version using `load_setup_py_data`. My `setup.py` is dynamically calculating the version from `git describe --tags --dirty`. Yes, the dirty state is critical for us as that's how we detect whether a build was done from an uncommited state or from a clean committed state.

I've found that a number of intermediate files are generated on the fly by `conda-build`. Given that my recipe depends on a dynamic version which also checks for a project's dirty/stale state these intermediate files pose a problem. I have previously found the following intermediate files:

- `_load_setup_py_data.py`
- `build_env_setup.sh`
- `conda_build.sh`
- `metadata_conda_debug.yaml`

And today I found these since I recently started using the `outputs` keyword:

- `conda_build_loaded_setup_py.json`
- `output_script.sh`

### Expected Behavior

I don't have an issue with these files being made but it would be ideal if these temporary files are either dumped into some `.conda-build` directory or at the very least use a consistent prefix for the files such that all of these files can be safely ignored.

### Steps to Reproduce

N/A

##### `Output of conda info`

```

     active environment : REDACTED
    active env location : REDACTED
            shell level : 1
       user config file : REDACTED
 populated config files : REDACTED
          conda version : 4.7.10
    conda-build version : 3.18.11
         python version : 3.7.1.final.0
       virtual packages : __cuda=9.1
       base environment : REDACTED  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          REDACTED
                          REDACTED
          package cache : REDACTED
       envs directories : REDACTED
                          REDACTED
                          REDACTED
                          REDACTED
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-693.11.6.el7.x86_64 centos/7.4.1708 glibc/2.17
                UID:GID : 54690:702
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
Those intermediate files are quite integrated into conda build and may be difficult to move to a new location although if anyone wants to put together a PR that moves this around I would be happy to review it.

A workaround would be to specify a [destination path for the source in the work directory](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#destination-path) using a `source/folder` entry in the recipe.  This should give you a clean version of the source from which the version can be determined.
