### ISSUE TITLE
conda dependencies for locally built packages

### ISSUE THREAD

**Issue by sntgluca** [conda/conda-build#3950]
Dear all,

I have built a conda package with a list of run dependencies, following the official documentation in https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/building-conda-packages.html and the like. The built seems correct, as far as I can tell.

I expect running
```shell
conda install /path/to/package.tar.bz
```
would install the package and its dependencies.
Instead, it only installs the package and ignores the dependencies list.

Is there any way I can enforce installing the dependencies from the local package? Am I missing anything in the documentation?

I am working with conda 4.8.3
Thank you

PS I can share any file if you find it useful.

**Comment by jjhelmus** [comment]
This behavior is a feature of conda, not conda build.  Specifying the full path to a package skips dependency resolution in conda.  If you do not want this behavior you should refer to the local directory as a channel.  
Conda special cases the `local` channel to be the default location where conda build stores packages that have been built.  `conda install -c local package` will install from the default conda build location.  You can also specify a local directory as a channel using the `file://` prefix, for example `conda install -c file:///home/jhelmus/conda/conda-bld package`

**Comment by sntgluca** [comment]
Thank you @jjhelmus ,

this is indeed what I was missing.

I hope this wasn't too much of a trivial question, and hopefully it helps others.
