### ISSUE TITLE
RuntimeError: Failed to disconnect signal currentIndexChanged(int)

### ISSUE THREAD

**Issue by CarlosAMosquera** [conda/conda-build#3955]
### Actual Behavior

 The navigator launches but Anaconda3 Individual edition does not launch at all in Windows 10 X-64.

### Expected Behavior

 There is an error but I cannot fix it. The starting icon is shown but the program stalls and does not launch the GUI.

### Steps to Reproduce

I installed Anaconda (run) as Administrator in Windows 10 X64.
Installation steps
- Install for: All users
- Destination Folder: C:\ProgramData\anaconda3.
- Advanced Options: Register Anaconda3 as my default Python 3.7

I run the Anaconda Prompt (with Administrator permissions) the following: anaconda-navigator
Errors that appear to me:
- ModuleNotFoundError: No module named 'PySide'
- PythonQtError ('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

I proceed to install PySide: pip install PySide2
Successfully installed: Successfully installed PySide2-5.14.2.1 shiboken2-5.14.2.1

Within the environment variables, in system variables I have configured the following:
Variable: Path
Value: C: \ ProgramData \ anaconda3 \ Lib \ site-packages \ PySide2 \

Variable: QT_PLUGIN_PATH
Value: C: \ ProgramData \anaconda3 \ Lib \ site-packages \ PySide2 \ plugins

OR after installing PySide2, you actually replace the plugins with the ones from PySide2:
Copy
...\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qminimal.dll
...\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qoffscreen.dll
...\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qwindows.dll
(actually all files)
files to
...\Anaconda3\Library\plugins\platforms\

I reset the navigator successfully (anaconda-navigator --reset) and run anaconda-navigator (anaconda-navigator) again from cmd. From desktop icons, the behavior is the same, just that I cannot interrupt the execution due to the error. In cmd, you just type ctrl+C and interrupt the error.

##### `Output of conda info`

I see the Anaconda icon, when it starts to load the applications it appears to me:

```
Message: (base) C:\WINDOWS\system32>anaconda-navigator
Traceback (most recent call last):
  File "C:\…\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 541, in setup
    self.post_setup(conda_data=conda_data)
  File "C:\ …\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 578, in post_setup
    self.tab_home.setup(conda_data)
  File "C:\…\anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 168, in setup
    self.set_environments(environments)
  File "C:\…\anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 175, in set_environments
    self.combo.currentIndexChanged.disconnect()
RuntimeError: Failed to disconnect signal currentIndexChanged(int).
```
I hope you can help me.

Regards,
Carlos Mosquera

**Comment by UniversalJack** [comment]
i got the same issue, but i haven't added anaconda to path

**Comment by AlphaLabs2302** [comment]
The solution is to open anaconda prompt and type in 'pip install spyder'
then they will install the missing packages and fix the issue

**Comment by shankartmv** [comment]
@AlphaLabs2302  - That didn't solve my problem. I have the exact issue on windows 10 - 64 bit Anaconda and does anyone have a fix  ?

**Comment by nderrick** [comment]
I have the very problem and its so persistent
Can anyone help with this?

Best

**Comment by Hiteshldt** [comment]
I am having the same issue, could you please guide me

**Comment by Hiteshldt** [comment]
> I have the very problem and its so persistent Can anyone help with this?
> 
> Best

Is your problem fixed?

**Comment by littlelight-e** [comment]
> The solution is to open anaconda prompt and type in 'pip install spyder' then they will install the missing packages and fix the issue

thank you ，it is very help
