### ISSUE TITLE
python_abi <ver>.* *_cp<ver>m dep is added to noarch built with conda-forge

### ISSUE THREAD

**Issue by s22chan** [conda/conda-build#3956]
### Actual Behavior

When building with defaults conda-build and the conda-forge channel, an extra abi dependency is being added. This breaks noarch packages:

```json
cat $(conda info --base)/conda-bld/noarch/repodata.json
{
  "info": {
    "subdir": "noarch"
  },
  "packages": {
    "test-0.0.1-py_0.tar.bz2": {
      "build": "py_0",
      "build_number": 0,
      "depends": [
        "python",
        "python_abi 3.7.* *_cp37m"
      ],
      "md5": "c173123a362c4699c7597c0dc5565d2f",
      "name": "test",
      "noarch": "python",
      "sha256": "00421a660b7fd1dda1e1d46d2dd5c880d0112e0c6142cab1278225236c576355",
      "size": 2152,
      "subdir": "noarch",
      "timestamp": 1590013617859,
      "version": "0.0.1"
    }
  },
  "packages.conda": {},
  "removed": [],
  "repodata_version": 1
}
```

### Expected Behavior

If using conda-forge's conda+conda-build via `conda update -n base -c conda-forge --all`, there is no abi dependency for noarch packages, and they can be installed for any python environment.

### Steps to Reproduce

With `conda-recipe/meta.yaml`
```yaml
package:
  name: test
  version: 0.0.1

source:
  path: .

build:
  number: 0
  noarch: python
  script: echo "hello"

requirements:
  build:
    - python
  run:
    - python
```

1. docker run -v $(pwd):/conda-recipe --rm -it continuumio/miniconda3
2. conda install conda-build
3. conda config --prepend channels conda-forge
4. conda build conda-recipe
5. grep abi $(conda info --base)/conda-bld/noarch/repodata.json

##### `Output of conda info`
```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/4.19.76-linuxkit debian/10 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
This is because of run_exports data from conda-forge. You can probably use ignore_run_exports to avoid the issue. Perhaps you could put up a PR to automatically handle an ignore_run_exports setting in the presence of noarch: python.

Regardless, this is a problem that conda-forge metadata has added, and any "fix" here is actually a feature addition.

**Comment by s22chan** [comment]
Isn't it just https://github.com/conda/conda-build/pull/3868 that was reviewed?

**Comment by isuruf** [comment]
conda-build 3.18.11 is old. Use a newer version.

**Comment by s22chan** [comment]
@isuruf when making a breaking change like this:
1) there's no global notification of this happening
2) difficult to get thousands/millions(?) of users to do something at the same time

but at the very least the defaults conda channel needs the new conda build to prevent future users from hitting this

**Comment by isuruf** [comment]
We added a new `run_exports` type and there was no way to make older conda-builds error out. Can you send a PR to conda-build to check that all the `run_exports` types of a package is understood by `conda-build` and if not error out? That way this won't happen in the future.

We've made it clear time and time again that if you are using conda-forge, you have to go all in, but you seem to ignore that and use `conda-build` from defaults and use packages from `conda-forge`. If this is not clear from conda-forge docs, please make a PR to make it clear.

**Comment by s22chan** [comment]
@isuruf if you look at https://github.com/conda/conda-build/issues/3938, you'll see that using the correct version of conda-build isn't always transparent (such as python=3.8 being in your conda-build env)

**Comment by isuruf** [comment]
You can install conda-build from git if you want to contribute.

**Comment by cmutel** [comment]
For those still struggling with this, one can use the suggestion from @msarahan to get something that works, though it feels like a kludge. Add the following to the `build` section of your recipe:

```yaml
ignore_run_exports:
  - python_abi
```
