### ISSUE TITLE
ImportError: cannot import name 'parse_url'

### ISSUE THREAD

**Issue by fallen** [conda/conda-build#396]
When trying to generate skeleton for pyelftools I get this:

yann@pcqu1r0x:~$ conda skeleton pypi pyelftools
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/yann/anaconda3/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/yann/anaconda3/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 188, in main
    args_func(args, p)
  File "/home/yann/anaconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/home/yann/anaconda3/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 192, in execute
    import conda_build.pypi as pypi
  File "/home/yann/anaconda3/lib/python3.4/site-packages/conda_build/pypi.py", line 40, in <module>
    from requests.packages.urllib3.util.url import parse_url
ImportError: cannot import name 'parse_url'

Here is the conda info:

yann@pcqu1r0x:~$ conda info
Current conda install:

```
         platform : linux-32
    conda version : 3.12.0
```

  conda-build version : 1.12.1
       python version : 3.4.3.final.0
     requests version : 2.4.3
     root environment : /home/yann/anaconda3  (writable)
  default environment : /home/yann/anaconda3
     envs directories : /home/yann/anaconda3/envs
        package cache : /home/yann/anaconda3/pkgs
         channel URLs : https://conda.binstar.org/pypi/linux-32/
                        https://conda.binstar.org/pypi/noarch/
                        https://conda.binstar.org/binstar/linux-32/
                        https://conda.binstar.org/binstar/noarch/
                        https://conda.binstar.org/fallen/linux-32/
                        https://conda.binstar.org/fallen/noarch/
                        https://repo.continuum.io/pkgs/free/linux-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        http://conda.binstar.org/fallen/channel/dev/linux-32/
                        http://conda.binstar.org/fallen/channel/dev/noarch/
          config file : /home/yann/.condarc
    is foreign system : False

**Comment by asmeurer** [comment]
Your requests version is too old. Try running `conda update requests`.

**Comment by fallen** [comment]
It says it's already up to date at version 2.7.0 (p34_0)

**Comment by fallen** [comment]
Ah it takes the system's requests:
`>>> requests.__path__`
`['/usr/lib/python3/dist-packages/requests']`

Did I miss to setup some path env variable in my .bashrc ?

**Comment by asmeurer** [comment]
You probably need to unset PYTHONPATH in your bashrc.
