### ISSUE TITLE
Travis-CI build is failing for flake "3.8.2"(latest) version.

### ISSUE THREAD

**Issue by odidev** [conda/conda-build#3961]
Build is failing when "conda install -q flake8" (In travis.yml) installs "3.8.2" version of flake8.  We are getting following errors:
`/conda_build/conda_interface.py:58:1: E402 module level import not at top of file
./conda_build/source.py:541:13: E741 ambiguous variable name 'l'
./conda_build/utils.py:44:1: E402 module level import not at top of file
./conda_build/utils.py:46:1: E402 module level import not at top of file
./conda_build/utils.py:47:1: E402 module level import not at top of file
./conda_build/utils.py:48:1: E402 module level import not at top of file
./conda_build/utils.py:49:1: E402 module level import not at top of file
./conda_build/utils.py:50:1: E402 module level import not at top of file
./conda_build/utils.py:51:1: E402 module level import not at top of file
./conda_build/utils.py:52:1: E402 module level import not at top of file
./conda_build/utils.py:53:1: E402 module level import not at top of file
./conda_build/utils.py:54:1: E402 module level import not at top of file
./conda_build/utils.py:55:1: E402 module level import not at top of file
./conda_build/utils.py:56:1: E402 module level import not at top of file
./conda_build/utils.py:59:1: E402 module level import not at top of file
./conda_build/utils.py:60:1: E402 module level import not at top of file
./conda_build/build.py:274:12: E741 ambiguous variable name 'l'
./conda_build/skeletons/cran.py:1143:56: E741 ambiguous variable name 'l'
./conda_build/os_utils/ldd.py:64:64: E741 ambiguous variable name 'l'`

Please have a look at below travis-CI run:
https://travis-ci.com/github/odidev/conda-build/jobs/340444022

Resolution: If we mention the exact version for flake8, i.e. "conda install -q flake8==3.7.9". It is getting passed. Please have a look at below travis-CI Run: 
https://travis-ci.com/github/odidev/conda-build/jobs/340447155

It is failing for latest flake versions, can I  raise PR for the same or please suggest any other possible resolution. 
Thanks.

**Comment by kenodegard** [comment]
Thanks for reporting this; however, since conda-build no longer uses Travis CI, this is moot.
