### ISSUE TITLE
Support for powershell build scripts on windows?

### ISSUE THREAD

**Issue by duncanmmacleod** [conda/conda-build#3967]
Is it reasonable for conda-build to support build scripts written for PowerShell rather than batch, on Windows? I am happy to attempt to write this up if the idea is acceptable.

**Comment by qingfengxia** [comment]
I would also like it.  powershell can read  registry easily

**Comment by mingwandroid** [comment]
It would be a fair bit of effort but if it's done cleanly I wouldn't mind. On this point if we are supporting bash, cmd and powershell we'd want to tidy things up a bit as it's ugly enough already (if/else no longer cuts it!)

But I'd rather see WSL2 or MSYS2 (upstream) supported better before powershell. Personally, I would just want to use bash on all platforms.

Accessing the registry is easy from any of them though IMHO. But accessing the registry suggests external dependencies which while sometimes necessary, are not good for reproducibility.
