### ISSUE TITLE
ENH: skeleton --version-compare for latest versions

### ISSUE THREAD

**Issue by westurner** [conda/conda-build#397]
a naieve ``--version-compare`` routine in ``skeleton`` would make comparing recipe version metadata with e.g. PyPI version metadata more simple

seeAlso: https://github.com/conda/conda-recipes/issues/291

potentially: UBY (usability), SEC (security) due to packaging latency

**Comment by asmeurer** [comment]
I don't understand what is being requested here.

**Comment by westurner** [comment]
As a package maintainer / package installer, when I need to review whether there are new versions (to be re-templated and diff'd) I must manually go to e.g. https://pypi.python.org/pypi/conda to check the version.

I believe the ``conda skeleton`` utilities should already have scraping / parsing logic for the the version field.

**Comment by asmeurer** [comment]
Oh, I see. So what is really needed are some better features for dealing with updates for packages. @hargup, this is related to the work you are doing.

**Comment by westurner** [comment]
Thanks! Where would the tests for this go?

**Comment by westurner** [comment]
Tested this feature with https://github.com/conda/conda-recipes/pull/308 ("ENH: pip 7.0.0, setuptools 16.0, virtualenv 13.0.0, wheel 0.24.0, virtualenvwrapper 4.5.1, peep 2.4.1")
