### ISSUE TITLE
How does post-link.sh/.bat determine the conda environment name?

### ISSUE THREAD

**Issue by briantoby** [conda/conda-build#3970]
When installing a package, I want to create scripts to run it, but if the package is being installed other than to the base environment, the scripts need to activate that environment. After reading the docs, I was not able to find a way to determine this (https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html). It seems to me that one needs an environment variable with the name of the conda environment. It would be nice to also have an environment variable that includes the name of the activate script.

**Comment by mingwandroid** [comment]
Hi @briantoby. Link scripts are not the same thing as pre- and post- install scripts. Link scripts happen when a package in installed into conda's internal *package cache*. Pre- and post- install scripts are the ones called when a package in being installed into an environment.
