### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tellts** [conda/conda-build#3983]
Hello. Installed in March in Lubuntu. I decided to write here just now.
$ anaconda-navigator
anaconda-navigator: not found

$ source ~/anaconda3/bin/activate root
bash: /home/alex/anaconda3/bin/activate: No such file or directory

$ source ~/anaconda3/bin/activate root
bash: /home/alex/anaconda3/bin/activate: No such file or directory

At the end of the installation, the following was written:

Do you wish the installer to initialize Anaconda3
by running conda init? [yes|no]
[no] >>> yes
Anaconda3-2020.02-Linux-x86_64.sh: 486: Anaconda3-2020.02-Linux-x86_64.sh: [[: not found
no change /root/anaconda3/condabin/conda
no change /root/anaconda3/bin/conda
no change /root/anaconda3/bin/conda-env
no change /root/anaconda3/bin/activate
no change /root/anaconda3/bin/deactivate
no change /root/anaconda3/etc/profile.d/conda.sh
no change /root/anaconda3/etc/fish/conf.d/conda.fish
no change /root/anaconda3/shell/condabin/Conda.psm1
no change /root/anaconda3/shell/condabin/conda-hook.ps1
no change /root/anaconda3/lib/python3.7/site-packages/xontrib/conda.xsh
no change /root/anaconda3/etc/profile.d/conda.csh
modified /root/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

If you'd prefer that conda's base environment not be activated on startup,
set the auto_activate_base parameter to false:

conda config --set auto_activate_base false

Thank you for installing Anaconda3!

**Comment by tellts** [comment]
I found instructions. I will try to reinstall. I speak Russian.
https://medium.com/@parbatibudhathoki/installation-of-anaconda-on-ubuntu-18-04-step-by-step-4eb8078cd830
https://www.digitalocean.com/community/tutorials/how-to-install-the-anaconda-python-distribution-on-ubuntu-20-04-quickstart-ru

**Comment by jjhelmus** [comment]
This issue tracker is for problems with conda build not Anaconda or conda.  If you are having issues with either of those please open an issue in the appropriate issue tracker either:
* [anaconda-issues](https://github.com/ContinuumIO/anaconda-issues/issues) for problems with Anaconda 
* [conda](https://github.com/conda/conda/issues) for issues with conda.
