### ISSUE TITLE
Docs for building with different SDKs on OSX?

### ISSUE THREAD

**Issue by jeanconn** [conda/conda-build#3989]
Is there a doc somewhere for actually using the other MacOSX SDKs and/or correctly using the MACOSX_DEPLOYMENT_TARGET ?  For example I tried to follow the [doc](https://github.com/conda/conda-build/blob/881d73a8990c040f6496506ef4f06d4f4170e249/docs/source/resources/compiler-tools.rst that suggested that I just set CFLAGS manually (though maybe that advice was just for a python package that uses distutils?):

```
export CFLAGS="${CFLAGS} -i sysroot ${CONDA_BUILD_SYSROOT}"
```
And my build attempts there then just fail with that CFLAGS and it looks like the MACOSX_DEPLOYMENT_TARGET in my conda_build_config.yaml does nothing:
```
x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/xija-4.18.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -i sysroot /opt/MacOSX10.13.sdk -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem $PREFIX/include -I$PREFIX/include/python3.6m -c xija/core_1.c -o build/temp.macosx-10.9-x86_64-3.6/xija/core_1.o
clang-10: error: unknown argument: '-i'
clang-10: error: no such file or directory: 'sysroot'
clang-10: warning: /opt/MacOSX10.13.sdk: 'linker' input unused [-Wunused-command-line-argument]
```

If I don't explicitly set anything in CFLAGS, it looks like I *if* /opt/MacOSX10.9.sdk exists on my system, that the build for the module seems to use that (seems to just ignore the conda_build_config.yaml).  If just a newer one exists in /opt, that isn't used.

I appear to be using conda-build 3.18.11 . 

### Actual Behavior

Variables I hoped would have some effect in the build environment seem to do nothing, and the directions to explicitly define CFLAGS don't seem compatible with clang or the options that are already in there.

### Steps to Reproduce

At this point, I don't have a good, reproducible sequence of events or a bug to report.  Mostly I'm just looking for guidance for best practices first.

##### `Output of conda info`

```

```

**Comment by mingwandroid** [comment]
Just set the special env var we added to the macOS compilers: `CONDA_BUILD_SYSROOT`. If you do that then no flags are needed.

**Comment by jeanconn** [comment]
Thanks!  

With a pip-installed conda-build from recent master (3.19.3+97.gf100a1ce)  if I don't set anything in conda_build_config.yaml, CONDA_BUILD_SYSROOT is not announced and, it looks like the default is set to:

CONDA_BUILD_SYSROOT=/opt/MacOSX10.10.sdk

which doesn't exist on my system and the build fails.  If I set CONDA_BUILD_SYSROOT to /opt/MacOSX10.13.sdk in conda_build_config.yaml (which I then printenv out as a build step), I see

CONDA_BUILD_SYSROOT=/opt/MacOSX10.13.sdk

but the call to clang later as part of the extension build looks to use the 10.9 sdk and marcos-version-min=10.9 (are these set from a *different* default?).


> x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -isysroot /opt/MacOSX10.9.sdk -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -isysroot /opt/MacOSX10.9.sdk -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/xija-4.18.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem $PREFIX/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/xija/core_1.o -o build/lib.macosx-10.9-x86_64-3.6/xija/core_1.cpython-36m-darwin.so

It looks like some part of the build knows about the sysroot I've set as I later see:

> Partially parsed some '.tbd' files in sysroot, pretending .tbds are their install-namesAdding support to 'conda-build' for parsing these in 'liefldd.py' would be easy and useful:/opt/MacOSX10.13.sdk ...WARNING:conda_build.post:Partially parsed some '.tbd' files in sysroot, pretending .tbds are their install-namesAdding support to 'conda-build' for parsing these in 'liefldd.py' would be easy and useful:/opt/MacOSX10.13.sdk ...WARNING conda_build.post:check_overlinking_impl(1134): Partially parsed some '.tbd' files in sysroot, pretending .tbds are their install-namesAdding support to 'conda-build' for parsing these in 'liefldd.py' would be easy and useful:/opt/MacOSX10.13.sdk ...   INFO: sysroot: '/opt/MacOSX10.13.sdk/' files: '['usr/share/man/mann/zero.n', 'usr/share/man/mann/yencode.n', 'usr/share/man/mann/yaml.n', 'usr/share/man/mann/xsxp.n']'   INFO (xija,lib/python3.6/site-packages/xija/core_1.cpython-36m-darwin.so): Needed DSO /opt/MacOSX10.13.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT   INFO (xija,lib/python3.6/site-packages/xija/core_2.cpython-36m-darwin.so): Needed DSO /opt/MacOSX10.13.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT


So is that how it is supposed to work?  I would have expected the clang calls to use the 10.13 sdk.

Honestly, I probably don't even need the 10.13 SDK, I had just set some stuff in previous builds to try to use MACOSX_DEPLOYMENT_TARGET 10.13 and I'll have to see if those use cases for more modern stuff still exist or if everything is fine with 10.9.
