### ISSUE TITLE
IndexError when using python variants with outputs requiring python

### ISSUE THREAD

**Issue by jpoeppel** [conda/conda-build#4023]
Hi everyone, as mentioned on the gitter channel already, I am running into a strange problem when combining multipe outputs with variants (at least when these are python variants), where the recipee rendering fails, if the recipe contains on outputs requirering python either as host or run requirement.

I may just be using varaints and outputs wrong, but I could not find my mistake after reading through the relevant documentation multiple times and it appears to be tied to some special case for "python" in build variants.

### Actual Behavior

When I create a build matrix by specifying versions python in my conda_build_config.yaml, I get an 
```
...
File "/Users/jpoeppel/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 2173, in _get_used_vars_meta_yaml_helper
    apply_selectors=apply_selectors))
  File "/Users/jpoeppel/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 1698, in extract_single_output_text
    output = output_matches[output_index] if output_matches else ''
IndexError: list index out of range
```
when trying to build a recipe that contains an output and requires python anywhere (either in the output, or in the main requirements). For recipes without outputs, but that do require python it appears to work fine.

### Expected Behavior

I would expect all outputs to be build with all variants successfully, including different python versions.

### Steps to Reproduce

A minimal example, that allows me to reproduce the error would be this recipe:
```
package:
        name: outputvariants
        version: "0.1"

build:
        number: 1

requirements:
        run:
                - out_a

outputs:
      - name: out_a
        requirements:
                host:
                    - python
                run:
                    - python
```

With a conda_build_config.yaml such as 
```
boostcpp: 
   - 1.68
   - 1.69
```
it will build the (pointless) artifact correctly, but if I specify more than 1 python variant, either alone:
```
python:
   - 3.7
   - 3.8
```

or in addition to the bosst versions to get an entire build matrix such as
```
boostcpp: 
   - 1.68
   - 1.69
   - 1.70
   - 1.71
python:
   - 3.7
   - 3.8
```
I get the aforementioned IndexError.

The error would also occur, if I rename "python" to e.g. "py_version" and use it in the recipe as in `python {{ py_version }}`. 
I would assume, this has to do with special casing of python (where the variant is always used, even without the jinja variable setting the version, if a variant is found. 

I also found out, that the IndexError occurs, because the output_index is taken for the "meta-package", i.e. "outputvariants" in this example, which was added since it is an implicit meta-package but has no corresponding entry in the "output_matches", but I could not figure out, why this appears to only be a problem when specifying python...

##### `Output of conda info`

```
(base) macbook:condaVariants jpoeppel$ conda info

     active environment : base
    active env location : /Users/jpoeppel/miniconda3
            shell level : 1
       user config file : /Users/jpoeppel/.condarc
 populated config files : /Users/jpoeppel/.condarc
          conda version : 4.8.4
    conda-build version : 3.19.2
         python version : 3.7.3.final.0
       virtual packages : __osx=10.15.5
       base environment : /Users/jpoeppel/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jpoeppel/miniconda3/pkgs
                          /Users/jpoeppel/.conda/pkgs
       envs directories : /Users/jpoeppel/miniconda3/envs
                          /Users/jpoeppel/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.3 Darwin/19.5.0 OSX/10.15.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
(This does however also occur on linux, so it is not an osx error).

**Comment by mcg1969** [comment]
@conda/conda-core FYI, I encountered this issue in during our official build process. I'll investigate

**Comment by mcg1969** [comment]
I have found that a workaround for this is not to use the [implicit metapackage](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#implicit-metapackages) feature of conda-build. Instead, just create an output for the metapackage.

**Comment by mcg1969** [comment]
cc: @bkreider FYI
