### ISSUE TITLE
What's the plan for `py` preprocessing selector for python 3.10?

### ISSUE THREAD

**Issue by analog-cbarber** [conda/conda-build#4032]
The `py` preprocessing selector is an integer that currently equal to major version * 10 + minor version. This works fine as long as minor versions are <10, but that is soon not going to be true any longer. So a selector like:

```
foo # [py > 38]
```

may or may not work depending on what `py` is defined to be.

I suppose you could just number it 310 and thenceforth always use 3 digit values to maintain
the version ordering semantics. For example, if there were ever to be a python 4.0 it would be 400 instead of 40.

**Comment by njalerikson** [comment]
Not sure where else in conda-build this may be duplicated but in `conda_build.metadata.ns_cfg` it is joining the major and minor together:

https://github.com/conda/conda-build/blob/ee381c460ca3cf6b8b130a950389f5db7af738da/conda_build/metadata.py#L98-L112

Without additional changes we'd be dealing with this:

|Python|`py`|
|---|---|
|3.8|38|
|3.10|310|
|4.0|40|

Which would clearly cause a number of cascading issues.

**Comment by analog-cbarber** [comment]
Joining the major/minor versions like that is fine until we get to 4.0 and given that there are no plans for Python 4.0, in practice that will work for a long time.

**Comment by mingwandroid** [comment]
Using these vars is deprecated and something we hope to remove for conda-build 4. Instead, add `python` to your conda_build_config.yaml then use the jinja2 `python` variable.

**Comment by mingwandroid** [comment]
We only maintained support for them when the jinja2 stuff came along because of old recipes.

**Comment by analog-cbarber** [comment]
The documentation explicitly says that you should use the `py` variable and makes no mention of the jinja python variable.  the variables like `py27` are deprecated, but that is not what I am talking about. 

If you mean to deprecate the `py` selector variable, then you should say so in the documentation. 

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors

**Comment by mingwandroid** [comment]
Well, I mean really we hope to deprecate them. I will try to get some time to go over what we want to deprecate and make some announcement and maybe add warnings to the builds when we find them.

Cheers!
