### ISSUE TITLE
 AssertionError if custom channel URL path is special token

### ISSUE THREAD

**Issue by wilsonmr** [conda/conda-build#4057]
Sorry in advance if this isn't the right place to open the issue, the error surfaces using `conda build` but the special case which causes it to fire is in `conda`

### Actual Behavior

Our builds were breaking because the following assertion error was firing:
https://github.com/conda/conda-build/blob/017bfdeea88dc797b4465d36c5e84fd10e0fa5a0/conda_build/post.py#L583

which I found was because some of the build dependencies come from a custom channel which we host: https://packages.nnpdf.science/conda/

and it turns out there is a special case in `conda` which took me a while to find:
https://github.com/conda/conda/blob/a78a2387f26a188991d771967fc33aa1fb5bb810/conda/models/channel.py#L437

That if a channel URL path has first token `/conda` (as ours does) then it's treated as a special case and removed from the channel name. But for us that means the channel name is left empty because that's the entirety of our path.

I was wondering if there was a potential workaround other than us renaming the channel?

At the moment we've pinned `conda-build` on our CI to a version before the assertion was added.

Thanks!

cc @zaharid

##### `Output of conda info`

```
conda info -a

     active environment : base

    active env location : /Users/travis/miniconda3

            shell level : 1

       user config file : /Users/travis/.condarc

 populated config files : /Users/travis/.condarc

          conda version : 4.8.4

    conda-build version : 3.20.2

         python version : 3.8.3.final.0

       virtual packages : __osx=10.14.4

       base environment : /Users/travis/miniconda3  (writable)

           channel URLs : https://packages.nnpdf.science/conda-private/osx-64

                          https://packages.nnpdf.science/conda-private/noarch

                          https://packages.nnpdf.science/conda/osx-64

                          https://packages.nnpdf.science/conda/noarch

                          https://repo.anaconda.com/pkgs/main/osx-64

                          https://repo.anaconda.com/pkgs/main/noarch

                          https://repo.anaconda.com/pkgs/r/osx-64

                          https://repo.anaconda.com/pkgs/r/noarch

                          https://conda.anaconda.org/conda-forge/osx-64

                          https://conda.anaconda.org/conda-forge/noarch

          package cache : /Users/travis/miniconda3/pkgs

                          /Users/travis/.conda/pkgs

       envs directories : /Users/travis/miniconda3/envs

                          /Users/travis/.conda/envs

               platform : osx-64

             user-agent : conda/4.8.4 requests/2.23.0 CPython/3.8.3 Darwin/18.5.0 OSX/10.14.4

                UID:GID : 501:20

             netrc file : /Users/travis/.netrc

           offline mode : False

# conda environments:

#

base                  *  /Users/travis/miniconda3

sys.version: 3.8.3 (default, May 19 2020, 13:54:14) 

...

sys.prefix: /Users/travis/miniconda3

sys.executable: /Users/travis/miniconda3/bin/python

conda location: /Users/travis/miniconda3/lib/python3.8/site-packages/conda

conda-build: /Users/travis/miniconda3/bin/conda-build

conda-convert: /Users/travis/miniconda3/bin/conda-convert

conda-debug: /Users/travis/miniconda3/bin/conda-debug

conda-develop: /Users/travis/miniconda3/bin/conda-develop

conda-env: /Users/travis/miniconda3/bin/conda-env

conda-index: /Users/travis/miniconda3/bin/conda-index

conda-inspect: /Users/travis/miniconda3/bin/conda-inspect

conda-metapackage: /Users/travis/miniconda3/bin/conda-metapackage

conda-render: /Users/travis/miniconda3/bin/conda-render

conda-skeleton: /Users/travis/miniconda3/bin/conda-skeleton

user site dirs: 

CIO_TEST: <not set>

CONDAPATH: /Users/travis/miniconda3

CONDA_BUILD_SYSROOT: /Users/travis/miniconda3/MacOSX10.9.sdk

CONDA_DEFAULT_ENV: base

CONDA_EXE: /Users/travis/miniconda3/bin/conda

CONDA_PREFIX: /Users/travis/miniconda3

CONDA_PROMPT_MODIFIER: (base) 

CONDA_PY: 37

CONDA_PYTHON_EXE: /Users/travis/miniconda3/bin/python

CONDA_ROOT: /Users/travis/miniconda3

CONDA_SHLVL: 1

CURL_CA_BUNDLE: <not set>

GEM_PATH: /Users/travis/.rvm/gems/ruby-2.6.4:/Users/travis/.rvm/gems/ruby-2.6.4@global

PATH: /Users/travis/miniconda3/bin:/Users/travis/miniconda3/condabin:/Users/travis/.rvm/gems/ruby-2.6.4/bin:/Users/travis/.rvm/gems/ruby-2.6.4@global/bin:/Users/travis/.rvm/rubies/ruby-2.6.4/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/Users/travis/.nvm/versions/node/v13.0.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

REQUESTS_CA_BUNDLE: <not set>

SSL_CERT_FILE: <not set>

TRAVIS_APT_PROXY: <set>

rvm_bin_path: /Users/travis/.rvm/bin

rvm_path: /Users/travis/.rvm
```

**Comment by jedfrechette** [comment]
I think we're hitting this same bug although for a slightly different reason. In our case one of the dependencies is provided by a channel defined as `file://...` The same assertion noted by @wilsonmr is thrown and downgrading to conda-build 3.19 solved the issue for us.

**Comment by pmspire** [comment]
I'm also hitting this assertion, having changed nothing in a recipe that formerly built successfully.

**Comment by wilsonmr** [comment]
Hi both, note in the original comment that we specifically hit this assertion because our own channel is called `*/conda` which as noted is handled differently in `conda` itself.

I wouldn't necessarily call this a bug in our case, it's just undocumented anywhere that you shouldn't name your own custom channel `conda`

Is the assertion firing for you for the exact same reason, or is it just that the same assertion is firing?

**Comment by pmspire** [comment]
It's just the same assertion. In our case, we're also using a custom channel, a simple FQDN like `https://foo.bar.baz.com`. I actually didn't test enough to confidently say that it's that channel that is triggering the assertion, but the issue likewise disappeared when I downgraded to `conda-build=3.19`.

**Comment by jedfrechette** [comment]
Likewise, it's the same assertion but firing for a different reason.
