### ISSUE TITLE
docs on conda-build shortcuts?

### ISSUE THREAD

**Issue by gilescope** [conda/conda-build#4059]
Are there any specific docs on fleets of recommended settings to use in some example use cases that might speed up conda-build. When conda is ones packaging format, conda-build is called a lot by CIs. I know that it tries to save me from everything that could possibly go wrong, but I don't want to wait all day for conda builds.

I have some pre-built files that I would like conda-build to package and for conda-build to stay out of the way as much as computerly possible... is there a recommended combination of flags that will tell conda-build to chillax and just accept the files in the prefix dir as they are? I am fully willing to tick a box saying 'Are you ok with the sky falling in?' if the end result is that conda build builds things faster.

I know I can't expect pkzip performance as it wants to do so much more, but I would to see if the adjective snappy could be used and would be happy to trade features for performance.

Yours sincerely,

someone who's life seems to mostly involve waiting around for conda-builds.

**Comment by mingwandroid** [comment]
You need to explain exactly what parts of conda-build are slow for you. The only clue you give is something about chillaxing and accepting files in the prefix dir, I don't really know what that means but it sounds inadvisable.
 
You also didn't fill in any of the information asked of you in this issue tracker's template. Closing. Feel free to add these details and I'll re-open but for now this is not actionable.

**Comment by gilescope** [comment]
Hi, sorry, let me start again.

Actionable: Can we collate and document what flags tell conda-build to do the least amount of work possible to create a package?

E.g. this config is necessary to have a minimal conda-build but is not sufficient:
```
build:
  ignore_prefix_files: True
  binary_relocation: False
```
There must be a minimum configuration where conda-build tries not to do anything funky like trying to detect overlinking and instead just tries to create a conda package in the most computationally efficient manor possible?

And then then the corollary, are there additional config flags that could be added to tell conda-build to do less than it currently does.

For specifics let's take a concrete example:

### Actual Behavior
conda-build of intellij community edition takes 45 min on a 4 core machine for conda-build to build the package - it is given existing binaries and runs no tests so in theory there should be not much to do. There are lots of files in that package though.

### Expected Behavior
To be able to configure conda-build so that it efficiently creates a package in a reasonable timeframe (E.g. under 10 mins).

I alas don't see a intellij CE in conda-forge that would make a good example in open source land. Most of the stuff we package with conda is propriety, but regardless of what have been packaged it always seems to take a long time.
 That said, we do have antivirus and run on virtualised hardware, but those are normal constraints these days. 

The mambo direction of rewriting things in a faster language will help, but I don't think we need to be as drastic as that - if we could configurably pair back conda-build's responsibilities to just trying to do the essentials of creating a package with metadata in it specifying the dependencies, then we would be able to build packages without considerable overheads. I know the defaults for conda-build are batteries-included but a page on what batteries-excluded looks like would be helpful.

Sorry if this all comes across the wrong way - I think conda makes a lot of sense, its just conda-build tries to solve a lot of (non-trivial) problems and build times suffer from this.
