### ISSUE TITLE
Post-build fails on bad system symlinks in MacOS 10.13.6

### ISSUE THREAD

**Issue by ndevenish** [conda/conda-build#4064]
### Actual Behavior

Attempting to build my WIP package with conda build fails in postprocessing trying to read some badly setup system libraries on MacOS 10.13.6. The error is:
```
Traceback (most recent call last):
  File "/Users/nickd/dials/conda/conda-build/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/api.py", line 209, in build
    return build_tree(sorted(absolute_recipes), config, stats, build_only=build_only, post=post,
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/build.py", line 3012, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/build.py", line 2299, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/build.py", line 1598, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/build.py", line 1444, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/post.py", line 1315, in post_build
    check_overlinking(m, files, host_prefix)
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/post.py", line 1221, in check_overlinking
    return check_overlinking_impl(m.get_value('package/name'),
  File "/Users/nickd/dials/conda/conda-build/lib/python3.8/site-packages/conda_build/post.py", line 1118, in check_overlinking_impl
    with open(os.path.join(sysroot, f), 'rb') as tbd_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/Frameworks/System.framework/Versions/B/System.tbd'
```
Now, I don't know how it's gotten into this state, but this path contains `.tbd` symlinks that are invalid:
```
~ $ ls -l /System/Library/Frameworks/System.framework/Versions/B
total 0
drwxr-xr-x  5 root  wheel  160 17 Aug 15:07 Resources
lrwxr-xr-x  1 root  wheel   43  3 Nov  2017 System -> ../../../../../../usr/lib/libSystem.B.dylib
lrwxr-xr-x  1 root  wheel   41 17 Apr 22:01 System.tbd -> ../../../../../../usr/lib/libSystem.B.tbd
lrwxr-xr-x  1 root  wheel   48 30 Mar 13:54 System_asan -> ../../../../../../usr/lib/libSystem.B_asan.dylib
lrwxr-xr-x  1 root  wheel   46 17 Apr 22:01 System_asan.tbd -> ../../../../../../usr/lib/libSystem.B_asan.tbd
```
I didn't do this - and a backup as of march doesn't seem to have them. Given it's also owned by root, I can only conclude that some recent system update has placed these links here. I can't find any information about this happening elsewhere or even why these files might have been made by the system.

Problem is, every file in this folder is opened by conda-build, presumably in case it's used somewhere:
https://github.com/conda/conda-build/blob/017bfdeea88dc797b4465d36c5e84fd10e0fa5a0/conda_build/post.py#L1115-L1119

### Expected Behavior

Ideally, conda build would ignore the bad links. However, I imagine this might be likely to hide errors in cases where they are actually corrupted?

### Steps to Reproduce

I don't think this is easily reproducible without making the bad links explicitly.

##### Output of `conda info`
```
     active environment : /Users/nickd/dials/conda/conda-build
    active env location : /Users/nickd/dials/conda/conda-build
            shell level : 4
       user config file : /Users/nickd/.condarc
 populated config files : /Users/nickd/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.15.final.0
       virtual packages : __osx=10.13.6
       base environment : /usr/local/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda3/pkgs
                          /Users/nickd/.conda/pkgs
       envs directories : /usr/local/miniconda3/envs
                          /Users/nickd/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/2.7.15 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
despite what this says, conda build is installed in the active environment:
```
$ conda build --version
conda-build 3.20.2
```

I'm aware that I'm using an old major version of an OS with a situation that may be some unique function of integrated system history, but posting in case anyone else encounters this in the future. I'm going to attempt to remove the broken symlinks myself to fix this, since it didn't have the links before and assume they aren't doing anything for anything in the system.

**Comment by ChrisBarker-NOAA** [comment]
I'm seeing the same error.

Running 10.13.6 as well. I have not dug nearly as far into this as you have -- but any luck?

Can we have confirmation that this is an issue with newer conda-build and older OS version?

In which case, would downgrading conda-build solve this?

**Comment by mingwandroid** [comment]
If you are using the Anaconda compilers then you should be setting CONDA_BUILD_SYSROOT (usually in conda_build_config.yaml) to a valid macOS SDK.

If you aren't using our/conda-forge's compilers then the system's real sysroot will get used and whether that works or not depends on what version you have installed and how good a job Apple did of creating the system packages. While I'm loathe to add hacks to workaround this, I guess I will have to. But ideally (and in the meantime) I would suggest you use our compilers and pick your macOS baseline compatibility by pointing those compilers to a working SDK.

**Comment by ChrisBarker-NOAA** [comment]
Thanks Ray.

I've got {{ compiler('cxx') }} in the meta.yaml -- but I guess that means it's looking for something in conda_build_config.yaml -- but I'm still unclear on:

1) where do I put conda_build_config.yaml?
2) set CONDA_BUILD_SYSROOT (usually in conda_build_config.yaml) to a valid macOS SDK.

if I use the standard `pip install .` it builds fine outside of conda-build -- so how do I find the SDK path?

**Comment by mingwandroid** [comment]
No problem Chris, here's the latest docs on both:

https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#build-variants
https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#macos-sdk

Cheers!

**Comment by mingwandroid** [comment]
MacOS SDKs can be found [here](https://github.com/phracker/MacOSX-SDKs)

**Comment by ChrisBarker-NOAA** [comment]
Thanks! that's all working now -- with conda compilers.

**Comment by mingwandroid** [comment]
Great suff!
