### ISSUE TITLE
sign osx binaries and dylibs

### ISSUE THREAD

**Issue by beckermr** [conda/conda-build#4073]
It appears that on osx-arm64, all native binaries will need to be signed. We need conda-build to do this since it calls install_name_tool on the binaries and so invalidates any signatures from the compilers or linkers.

**Comment by beckermr** [comment]
cc @erykoff @isuruf

**Comment by erykoff** [comment]
I would like to add that only the v12 clang compilers do the auto-signing (and conda compilers are currently going from v10 to v11).  So for the time being the binaries that are built with the conda compilers will be _unsigned_ and even without the `install_name_tool` call we need to sign the binaries/`dylib`s/`so`s.  Details are here: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-universal-apps-beta-release-notes

Note that the signing is very easy. If you are on a macos machine with Mojave (10.14.6) or later that has Xcode 11 or later command-line tools installed, then you can run `codesign -s - -f filename` to create a valid signature.  To verify if a binary/dylib/so has a valid signature run `codesign -v filename`.  The x86_64 binaries can also be signed, but the OS (up through Big Sur) does not check if the signatures are valid, it only checks arm64 binaries.

**Comment by isuruf** [comment]
(btw: XCode clang is a fork of LLVM clang with a different versioning scheme)

**Comment by erykoff** [comment]
Oh, so https://en.wikipedia.org/wiki/Xcode#Toolchain_versions says that the Xcode 12 is from LLVM 10.0.0?  I didn't realize that.  As for whether the binaries are auto-signed, I can say for sure that the arm64 binaries that are currently on `conda-forge/osx-arm64` are _not_ signed, not that they have invalid signatures.  I assume the auto-signing is only on the Apple fork.

**Comment by beckermr** [comment]
If we add signing to conda-build at the end, we will resolve all of these issues. Even if our compilers did sign, the binaries would have to be resigned post-rpath changes anyways. For people using our compilers outside of conda-build, they will need to implement the signing themselves at least for now or use the system linker maybe.

**Comment by erykoff** [comment]
100% agree that just adding the signing at the end is the straightforward and correct path.  The question of what to do for people using the compilers outside of conda-build is trickier.

**Comment by beckermr** [comment]
> The question of what to do for people using the compilers outside of conda-build is trickier.

If you build the DM stack inside of conda-build like I do, then you don't need to do anything! ;p

**Comment by beckermr** [comment]
looks like here is the right spot: https://github.com/conda/conda-build/blob/017bfdeea88dc797b4465d36c5e84fd10e0fa5a0/conda_build/post.py#L1265

link from @erykoff and @isuruf

**Comment by beckermr** [comment]
We should use `find_apple_cctools_executable` to get the codesign binary per @isuruf

**Comment by beckermr** [comment]
We will likely patch install_name_tool instead so that this change is not needed.
