### ISSUE TITLE
Log error mentioned "Windows" in non-Windows-specific context

### ISSUE THREAD

**Issue by mgoldshteyn** [conda/conda-build#4085]
https://github.com/conda/conda-build/blob/ef7ef9865f008e539916ae05180c01253495a45e/conda_build/utils.py#L2099

Uhm, you might want to check what OS we're running on, before blaming every bug in the code on Windows. (Hint: Linux)

**Comment by mbargull** [comment]
This is fixed in `conda-build >=3.20.4`.
Also, use the issue template and don't use undescriptive issue titles.
