### ISSUE TITLE
scipy bad build: ImportError: cannot import name '_ccallback_c'

### ISSUE THREAD

**Issue by pseudotensor** [conda/conda-build#4089]
https://anaconda.org/conda-forge/scipy/1.4.1/download/linux-64/scipy-1.4.1-py36h832618f_3.tar.bz2

This package is bad and leads to

```
(base) $ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import stats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon/minicondadai/lib/python3.6/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/jon/minicondadai/lib/python3.6/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c'
```

However the  build https://anaconda.org/conda-forge/scipy/1.4.1/download/linux-64/scipy-1.4.1-py36h2d22cac_3.tar.bz2 has no such problem.  But conda chooses the latest build.

The build https://anaconda.org/conda-forge/scipy/1.4.1/download/linux-64/scipy-1.4.1-py36h832618f_3.tar.bz2 should be removed.

Question: How does conda-forge test builds?  This is a basic import that should fail.

**Comment by marcelotrevisani** [comment]
That is related to conda-forge and not conda-build itself.
Could you please raise this error on the scipy feedstock and ping the ``conda-forge/core``  there?
https://github.com/conda-forge/scipy-feedstock

**Comment by pseudotensor** [comment]
Thanks, I couldn't find out where that was, just getting used to conda...

**Comment by marcelotrevisani** [comment]
> Thanks, I couldn't find out where that was, just getting used to conda...

No worries! :)
Any problem please feel free to reach us again!
