### ISSUE TITLE
conda test and strange PATH on windows

### ISSUE THREAD

**Issue by petrushy** [conda/conda-build#41]
Hi,

While trying to troubleshoot some testing issues, I found that the path environment variable during test (printed from run_test.py) contains an unexpanded %PATH%

PATH = C:\Anaconda32\envs_test\Scripts;C:\Anaconda32\envs_test\Library\bin;C:\Anaconda32\envs_test;C:\Anaconda32\envs_test\Scripts;%PATH%

My PATH when executing the conda-build looks "normal".

**Comment by asmeurer** [comment]
FYI, this commit has been reverted. We definitely need to use `%PATH%` and not `os.getenv("PATH")` as the latter overrides the PATH additions from vcvarsall.
