### ISSUE TITLE
osx: macho.otool() can't handle multi-architecture binaries

### ISSUE THREAD

**Issue by stuarteberg** [conda/conda-build#411]
This is related to issue #206.

The [`otool()`](https://github.com/conda/conda-build/blob/f20ee8dd64d4e1177d23db64aafc0899ae305b31/conda_build/macho.py#L56) function parses the output of `otool -L`, but it expects a very specific format.  Typical output of `otool -L` might look like this:

```
$ otool -L /miniconda/lib/libpython2.7.dylib 
/miniconda/lib/libpython2.7.dylib:
    libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.0.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

... but if the file contains code for more than one architecture (such as a "universal binary"), then the output looks like this:

```
$ otool -L /miniconda/envs/_build/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/apptemplate/prebuilt/main-fat
/miniconda/envs/_build/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/apptemplate/prebuilt/main-fat (architecture i386):
    /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 11.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.10)
    /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 18.0.0)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 368.33.0)
/miniconda/envs/_build/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/apptemplate/prebuilt/main-fat (architecture ppc):
    /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 11.0.0)
    /usr/lib/libmx.A.dylib (compatibility version 1.0.0, current version 47.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.10)

```

When `conda build` runs the post-link logic on a package that happens to contain a multi-architecture binary, it crashes, thanks to a well-placed assertion in `otool()`:

```
Finished processing dependencies for py2app==0.9
number of files: 162
Fixing permissions
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 118, in main
    args_func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 288, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 410, in build
    post_build(m, sorted(files2 - files1))
  File "/miniconda/lib/python2.7/site-packages/conda_build/post.py", line 325, in post_build
    mk_relative(m, f)
  File "/miniconda/lib/python2.7/site-packages/conda_build/post.py", line 294, in mk_relative
    mk_relative_osx(path)
  File "/miniconda/lib/python2.7/site-packages/conda_build/post.py", line 215, in mk_relative_osx
    s = macho.install_name_change(path, osx_ch_link)
  File "/miniconda/lib/python2.7/site-packages/conda_build/macho.py", line 86, in install_name_change
    for link in otool(path):
  File "/miniconda/lib/python2.7/site-packages/conda_build/macho.py", line 62, in otool
    assert line[0] == '\t', path
AssertionError: /miniconda/envs/_build/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/apptemplate/prebuilt/main-fat
```

One easy fix might be to simply ignore lines that don't begin with `\t`, though that would return results for all architectures.  A more thorough solution could be to only include those lines that apply to the host architecture.  After all, generating universal binaries is generally outside the scope of `conda-build`.

**Comment by asmeurer** [comment]
What does install_name_tool do for such binaries? 

Note that conda itself doesn't really support ppc at all (and even if it did, it would do so with distinct packages, so universal packages would never be necessary to build). Even so, we should try to support them if we can, because conda build can also be used to build packages from pre-built binaries, which might be universal.

**Comment by stuarteberg** [comment]
>What does install_name_tool do for such binaries?

For example:

    install_name_tool -change old.dylib new.dylib my_universal.dylib

If both architectures in `my_universal` refer to `old.dylib`, then the path is updated in both places.  If only one architecture refers to `old.dylib`, then only that one is updated.

>Note that conda itself doesn't really support ppc at all (and even if it did, it would do so with distinct packages, so universal packages would never be necessary to build).

Exactly.  That's what I was trying to say when I said "generating universal binaries is generally outside the scope of conda-build."

>Even so, we should try to support them if we can, because conda build can also be used to build packages from pre-built binaries, which might be universal. 

For now, recipe authors have the option of stripping unneeded code from their pre-built binaries in `build.sh` using the `ditto`tool.

**Comment by asmeurer** [comment]
If `install_name_tool` does the right thing for Universal binaries then I think we should just fix the otool code.

**Comment by ovz** [comment]
Would be good to have this issue resolved.

**Comment by stuarteberg** [comment]
I'm not a conda dev, so I can't answer your question about plans.  But for now, I recommend using the `ditto` tool in your recipe's `build.sh` script to strip the offending code from the universal binary that's causing trouble.

I don't have much experience with `ditto` myself, but it looks like this old link explains how to do it:
http://hints.macworld.com/article.php?story=20050810112422666
