### ISSUE TITLE
Overlinking check of runtime requirements is space-sensitive

### ISSUE THREAD

**Issue by ndevenish** [conda/conda-build#4130]
### Actual Behavior

Trying to write a [recipe](https://github.com/ndevenish/staged-recipes/blob/3095663587ac99d10e2c348b24ef5019f5456b35/recipes/cbflib/meta.yaml#L42-L43)  for conda-forge with a runtime requirement. While doing so, I'm running directly with conda-build. At runtime, I have a max version dependency on HDF5 which I expressed as:
```
run:
- hdf5<1.12
```
And got overlinking errors (warnings, but conda-forge converts these to errors so need to eliminate):
```
  ERROR (cbflib,lib/libcbf.3.0.1.dylib): Needed DSO lib/libhdf5.103.dylib found in ['hdf5']
  ERROR (cbflib,lib/libcbf.3.0.1.dylib): .. but ['hdf5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```
I found that removing the runtime version requirement (so just plain "hdf5") made these go away, but then had the wrong version on installation. However, after instrumenting the responsible code:
https://github.com/conda/conda-build/blob/7efdb8a569639c55c969a5dc354dab27917cab2c/conda_build/post.py#L935
I found that `pkg.quad[0]=hdf5` and `requirements_run=["hdf5<1.12"]`, so I tried inserting a space:
```
run:
- hdf5 <1.12
```
and then the warning disappeared.

### Expected Behavior

I'd expect this to work with a version specifier here. Indeed, the same version specifier works in the requirements/host section. Or, I'd expect this to work in neither without a space. Ideally, I'd be warned about the behaviour if it remains this way, or have the case checked for/noted as a possible reason in the overlinking error.

### Steps to Reproduce

Build above recipe.

##### `Output of conda info`
```
     active environment : /Users/nickd/dials/conda/conda-build
    active env location : /Users/nickd/dials/conda/conda-build
            shell level : 1
       user config file : /Users/nickd/.condarc
 populated config files : /Users/nickd/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.15.final.0
       virtual packages : __osx=10.13.6
       base environment : /usr/local/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda3/pkgs
                          /Users/nickd/.conda/pkgs
       envs directories : /usr/local/miniconda3/envs
                          /Users/nickd/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.25.0 CPython/2.7.15 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
Thanks for the report!

> - hdf5<1.12

This is not the correct way to do it, the space is necessary. The error could be detected and a helpful message given elsewhere, earlier. A PR for something like that would be welcome.

**Comment by Anthchirp** [comment]
If the presence and absence of spaces has such an impact here then conda build should probably strictly enforce the match specification as documented on https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#package-match-specifications, and reject any recipes that do not have the mandatory spaces.

I have to note though that the final example on that page lists `numpy=1.8.1=py27_0` as a valid match specification although it violates the specification given in the section.
