### ISSUE TITLE
Build recipes in given order, not alphabetically sorted order

### ISSUE THREAD

**Issue by kurtschelfthout** [conda/conda-build#4133]
### Actual Behavior

`conda build recipeB/ recipeA/` first builds recipeA, then recipeB.

### Expected Behavior

It should build in the order given, i.e. recipeB first.

This is important if recipeA has a dependency on recipeB - in that case with the sorted order the build fails.

This happens because of the `sorted` here: https://github.com/conda/conda-build/blob/ef7ef9865f008e539916ae05180c01253495a45e/conda_build/api.py#L187

It should just be left out.

This behavior changed in 3.20 and upwards, was working fine in 3.19 and before.

**Comment by mingwandroid** [comment]
I agree with you here; though actually conda-build could do even better, it could do a topological sort on the (rendered) recipes' dependencies.

Pinging @njalerikson for his thoughts.

**Comment by kurtschelfthout** [comment]
Thanks for the prompt attention.

> it could do a topological sort on the (rendered) recipes' dependencies.

I suggest making sure conda-build respects the order of the given _positional_ arguments first ;) I classify current behavior as a bug, and topological sort as a new feature.

Generally it's intuitive if `conda build A B` is the same as `conda build A & conda build B`.

**Comment by njalerikson** [comment]
I agree.

I would remove the sorting and if we do look into topological (or other) sorting that would be a new feature and likely hidden behind a flag (`--sort=[none,alpha,topo,...]`).

**Comment by kenodegard** [comment]
Resolved in https://github.com/conda/conda-build/pull/4134
