### ISSUE TITLE
Using pin_subpackage to pin to the same build, but not the same build ID

### ISSUE THREAD

**Issue by duncanmmacleod** [conda/conda-build#4142]
I maintain a recipe with multiple outputs, one of which (package `A`) is built in a matrix across `boost` versions (by conda-forge). The final output of the recipe (package `B`) is a metapackage that (currently) pins exactly to each of the others, mainly as a convenience for the user. Because `B` doesn't depend on `boost` it only gets built once, and the `pin_subpackage('A', exact=True)` usage pins it to _one_ of the boost variants of `A`, so there is no way to install package `B` and the _other_ `boost` variant.

The `pin_subpackage` function does have a `skip_build_id` kwarg that reduces the pin to just the build number, which sounds like exactly what I want, but it produces pins that look like `A 1.2.3 0` (where `0` is the build number):

https://github.com/conda/conda-build/blob/cb78dd913b65dad3d82f3ba99f667a8c0c939681/conda_build/jinja_context.py#L292

What I think I am looking for is something like this:

```python
    sp_m.build_id() if not skip_build_id else '*_{}'.format(sp_m.build_number())]) 
```

to produce pins like `A 1.2.3 *_0`. Is this already supported somehow, or is this a resonable feature request?

**Comment by mingwandroid** [comment]
Sounds reasonable. Can you submit a xfail test as a first step?

**Comment by duncanmmacleod** [comment]
> Sounds reasonable. Can you submit a xfail test as a first step?

I'm not 100% sure what you're asking for; do you want me to provide a test that _should_ return the `A 1.2.3 *_0` as I want, but doesn't? I am presuming that I will have to modify the API for `pin_subpackage` so am not sure how to construct the test. I am happy to provide the test function(s) when I get around to actually providing the change.

**Comment by h-vetinari** [comment]
Pity this got closed. This is still relevant in all places which wrap around something that gets built several times. Currently the only reliable way to make this work (that I know of) is to mirror the respective dependencies in the host deps of the wrapper, to ensure that they get built as often as the outputs they wrap.
