### ISSUE TITLE
Could not parse url for certifi

### ISSUE THREAD

**Issue by hargup** [conda/conda-build#415]
`conda-skeleton` not working for package https://pypi.python.org/pypi/certifi/2015.4.28
```
$ conda-skeleton pypi certifi
Error: Could not parse url for certifi: UNKNOWN
```

Though I `pip` install for the package passed.

**Comment by asmeurer** [comment]
certifi doesn't have an upload or a url on PyPI. I wonder how pip installs it.

**Comment by ilanschnell** [comment]
We have certifi in Anaconda, so we should not worry about it.  In general, if a package is officially supported by us (see http://docs.continuum.io/anaconda/pkg-docs.html) (I can easily compile a list of package names for you if desired), then we should skip that package.

**Comment by kgullikson88** [comment]
I am having the same issue in a package I just uploaded to Pypi: https://pypi.python.org/pypi/TelFit/1.3.0

Any ideas why it doesn't work?

**Comment by asmeurer** [comment]
For me, TelFit requires `--python 2.7`, and then I have to `conda install -n _build cython requests` to install some things that are imported in the setup.py. But then it works. I get a recipe that I think is correct. The license is "UNKNOWN", which just means it couldn't find any license anywhere in the metadata.
