### ISSUE TITLE
pip does not get correct flags in env for outputs

### ISSUE THREAD

**Issue by beckermr** [conda/conda-build#4157]
##### `Output of conda info`

```

```

It appears that pip is not getting flags like `--no-deps` when used in outputs. See this recipe: https://github.com/conda-forge/google-cloud-bigquery-storage-feedstock and this build: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=238367&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by beckermr** [comment]
Not stale.

**Comment by jakirkham** [comment]
Agree this is still an issue

Wonder if this is the same as issue ( https://github.com/conda/conda-build/issues/3993 )

**Comment by jaimergp** [comment]
Yes, I think it's a duplicate. Closing in favor of #3993.
