### ISSUE TITLE
Conda-build omits empty directories?

### ISSUE THREAD

**Issue by briantoby** [conda/conda-build#4166]
### Actual Behavior

It seems that somewhere between conda-build and conda-constructor, empty directories downloaded or created by the build script are not appearing in the final tar package. This appears to be happening in conda-build 3.20.5 on OS X and probably Linux. I have not yet fully diagnosed this, and may not get to that, but wanted to record this observation. 

### Expected Behavior

Removing empty directories is not something that should happen or at least should be optional. At least in some cases these are needed for software to run properly. 

##### `Output of conda info`

```

```

**Comment by mingwandroid** [comment]
Hi @briantoby, thanks for the report. I think it shouldn't remove empty directories. If you didn't want them, you wouldn't have created them (or else can delete them before conda-build does its packaging bit).

**Comment by kenodegard** [comment]
Closing in favor of duplicate https://github.com/conda/conda-build/issues/1014
