### ISSUE TITLE
Conda build of symlink fails since 5f46fdd06ebb19a69a2a0b779ac40fbc6772db32

### ISSUE THREAD

**Issue by Tiksagol** [conda/conda-build#4178]
Build failed due to commit https://github.com/conda/conda-build/commit/5f46fdd06ebb19a69a2a0b779ac40fbc6772db32#

### Actual Behavior
Build is aborted with: "TODO :: Nested symlinks not handled yet".

### Expected Behavior
Build should pass as it used to be prior to last update of conda-build.

### Steps to Reproduce
Build directory that contains symlink to symlink to symlink of file.

##### `Output of conda info`
Not relevant - it's conda 4.8.2

**Comment by beckermr** [comment]
We hit the same issue when building the conda-forge compilers. This regression is really painful.

**Comment by beckermr** [comment]
https://github.com/conda-forge/ctng-compilers-feedstock/pull/47
