### ISSUE TITLE
add ps: syntax in commands

### ISSUE THREAD

**Issue by xoviat** [conda/conda-build#4192]
Similar to appveyor, use the following syntax:

replace this:
```
  commands:
    - powershell -Command "Invoke-WebRequest -Uri https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz -OutFile {{ name }}-{{ version }}.tar.gz"  # [win]
```

with this:

```
  commands:
    - ps: Invoke-WebRequest -Uri https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz -OutFile {{ name }}-{{ version }}.tar.gz  # [win]
```

this is a feature request.

**Comment by mingwandroid** [comment]
Sorry, `commands:` entries on Windows are executed via the `cmd.exe` prompt and that's not going to change. Also I would not be willing to implement some hack of detecting `ps:` or anything like that.

Also, why would we want to follow AppVeyor here? What benefit does this bring us? If you are proposing being able to script `commands` with `powershell`, then OK I don't mind that so much, but we'd do that by identifying a `script_interpreter` as `powershell` and then directly coding the commands in powershell.

Personally I'd rather add support for something like `nushell` and side-step all vendor-invented technologies when picking the 'recommended' scripting language for conda-build recipes. Then no one would have to write batch files.

**Comment by xoviat** [comment]
`script_interpreter` is fine. powershell has many useful functions that cmd does not.
