### ISSUE TITLE
Bug in conda-pipbuild

### ISSUE THREAD

**Issue by PierFio** [conda/conda-build#420]
Hello

I had an execution error with conda-pipbuild command.
Detailed information follows.
Regards
Pierre
# 

MacBook-Pro-de-Pierre:~ Pierre$ conda pipbuild cassandra-driver
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/Pierre/anaconda/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/Users/Pierre/anaconda/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 77, in main
    args_func(args, p)
  File "/Users/Pierre/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 321, in args_func
    args.func(args, p)
  File "/Users/Pierre/anaconda/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 342, in execute
    print('Package search: %s' % r_name[0])
TypeError: 'filter' object is not subscriptable
MacBook-Pro-de-Pierre:~ Pierre$ conda info
Current conda install:

```
         platform : osx-64
    conda version : 3.12.0
```

  conda-build version : 1.11.0
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /Users/Pierre/anaconda  (writable)
  default environment : /Users/Pierre/anaconda
     envs directories : /Users/Pierre/anaconda/envs
        package cache : /Users/Pierre/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by hargup** [comment]
The command was successful on my `linux-64` machine, @asmeurer can you reproduce the issue on a mac?

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
