### ISSUE TITLE
Add a load_pyproject_toml_data() template function

### ISSUE THREAD

**Issue by bryevdv** [conda/conda-build#4207]
The Bokeh project currently uses the `install_requires` of a `setup.py` to specify the single source of truth for runtime dependencies. We use the existing `load_setup_py_data()` function that conda-build supplies to pull those dependencies into conda recipes automatically. 

We would like to move build information in to a `pyproject.toml` file, but also still keep ability to automatically pull information in to our recipes without manually duplicating it. I propose adding a `load_pyproject_toml_data()` alongside the existing `load_setup_py_data()`. 

Note: I did also find https://github.com/conda/conda-build/issues/3507 which seems possibly related, but I think the proposal here is narrower in scope, and aligned to a different use-case.

**Comment by mingwandroid** [comment]
Sounds good, but I don't think anyone will have time to do this. A PR would be appreciated though.

**Comment by bryevdv** [comment]
I'm not sure I'd be able to sign the CLA

**Comment by mingwandroid** [comment]
Ok thanks Brian. Is it worth asking, just so we know for the future whether it is allowed?

**Comment by bryevdv** [comment]
@mingwandroid We would have to execute the Corporate CLA mentioned in para 4, not the individual CLA at https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement Can you provide the CCLA for me to send to NV legal?

**Comment by mingwandroid** [comment]
Hi Brian.
My health has deteriorated and i don't think I'll get round to this or much else. Ping @chenghlee

**Comment by bryevdv** [comment]
Take care of yourself!

**Comment by jezdez** [comment]
> @mingwandroid We would have to execute the Corporate CLA mentioned in para 4, not the individual CLA at https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement Can you provide the CCLA for me to send to NV legal?

Hey Bryan, I'll try to find this document for you.

**Comment by chenghlee** [comment]
@bryevdv: here's a [direct link](https://anaconda.na2.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhAzPD8JNseGxXBNSY55tQ9ZE65FLEa2B-rUNAEYEjfxph-KGE3uSbu0fvR5cTRRCnY*&hosted=false) to the updated CLA that covers both individuals and organizations.

**Comment by bryevdv** [comment]
I'll pass it along to NV legal, I can't guarantee any specific outcome form them and I also don't know when I might be able to work on this personally.

**Comment by abrahammurciano** [comment]
I spent ages trying to use poetry for a proect that I also wanted to publish for conda. I searched high and low and couldn't find any satisfactory way to avoid repetition, so I made #4465 which would fix this issue in an even more general way. Hope it gets merged soon and it solves your problem!
