### ISSUE TITLE
disallow target_platform in conda_build_config.yaml?

### ISSUE THREAD

**Issue by wolfv** [conda/conda-build#4210]
I am currently working on boa, an implementation for an "alternative frontend" to conda-build.

As part of that, I have recently added proper support for the `target_platform` variable to the new-style boa recipes.

During that development, I started to wonder if there is some sort of recursive parsing needed for the `conda_build_config.yaml` file since it can contain the `target_platform` value(s) as well as selectors that may depend on the `target_platform`.

I have given some examples over in this issue: https://github.com/mamba-org/boa/issues/138

To avoid the recursive dependencies, it might be a good idea to have `target_platform` at a hierarchically higher level (e.g. as a command line flag)? And forbid its usage in conda_build_config.yaml?

I'd be happy to hear the thoughts of others on this. cc @isuruf

**Comment by mingwandroid** [comment]
We moved these things out of being hard-coded into config files as that seemed cleaner. The variables should just be conventions and everything should be as declarative as possible was the idea. But having some enforced structure is OK by me too. You can at present override any CBC config vars from the command line btw. Grepped from some scripts:

```
conda-build
  ..
  --variants={'target_machine':['"$(uname_to_arch)"']}
  --variants={'ctng_target_platform':['"$(uname_to_subdir)"']}
```

**Comment by mingwandroid** [comment]
Is conda_build_config.yaml overused? Should we split it up? Can we come up with some inclusion scheme? I'd still like to be able to stick a matrix dimension round these critical vars easily. Maybe! Can re reign in creativity when things are so (confusingly sometimes) flexible?

How goes boa these days?

**Comment by wolfv** [comment]
@mingwandroid I'd be more than happy to give you a proper update on boa, e.g. by video :)

But here is a quick write-down: we have a collection of recipes in the "boa-forge" that is derived from conda-build recipes and uses the updated recipe spec: https://github.com/mamba-org/boa-forge (although these recipes are a bit quick-n-dirty, i need to improve them). 

We have some support for "compile-time" features using `--features=[bzip2, tinyxml, ~zlib]` syntax inspired by vcpkg and we forward these as environment vars to the build script. I've also tried to make everything as straight-forward as possible and give as much information as possible about configuration files and picked variants using tables etc.

At the end of a build you'll get a table like this:
