### ISSUE TITLE
Compare meta.yaml specs against requirements in setup.py

### ISSUE THREAD

**Issue by pseudoyim** [conda/conda-build#4220]
Sometimes a project's `setup.py` will specify requirements and version specs that differ or deviate from those specified in the conda recipe (`meta.yaml`). It would be very useful to have a feature in `conda-build` that can check for any such differences/deviations (including version pinnings) to help avoid problems due to dependency incompatibilities.

**Comment by mingwandroid** [comment]
Hi Paul. You need to investigate the code in skeletons/pypi.pi to figure this out.

**Comment by mingwandroid** [comment]
Also a concrete example of this would be very helpful
