### ISSUE TITLE
Error signing shared-object on OXs-arm

### ISSUE THREAD

**Issue by tdegeus** [conda/conda-build#4256]
In applying the ARM OSX migrator my Python API of a C++ code compiles fine, but I then get:
```none
file not in an order that can be processed (code signature data out of place)
```

Here is the PR on conda-forge: https://github.com/conda-forge/gmattensor-feedstock/pull/13

**Comment by tdegeus** [comment]
This issue might be related @beckermr ? https://github.com/conda/conda-build/issues/4073

**Comment by beckermr** [comment]
I don't think that is related. Our tools sign and something must be going wrong their.

**Comment by tdegeus** [comment]
OK @beckermr  so then I should probably close this. At the same time I simply don't know how to proceed. 
* Where is the right place to report the bug?
* Is there a work-around such that I can start using the feedstock?

**Comment by beckermr** [comment]
Leave this open please. We'll need to ask @isuruf.

**Comment by Tobias-Fischer** [comment]
Hiya - I just ran into this issue and it took me a very long while to debug it ;).

The solution seems to be to simply bump the compiler version from 11 to 12. Should I create a PR in the pinnings feedstock that does this for osx-arm64? I am guessing more people will run into this problem in the future.

/cc @isuruf @wolfv

**Comment by isuruf** [comment]
What? That's just wrong. Please give more details if you are pinging me.

**Comment by beckermr** [comment]
Sorry for the noise here!

**Comment by Tobias-Fischer** [comment]
Sorry for not providing enough details. I was running into the same issue as described here, namely `file not in an order that can be processed (code signature data out of place)` (see https://github.com/conda-forge/gmattensor-feedstock/pull/13). After bumping the `c_compiler_version` and `cxx_compiler_version` from 11 to 12 the issue went away. This can also be observed in https://github.com/conda-forge/gmattensor-feedstock/pull/13

**Comment by isuruf** [comment]
That's because the cctools that comes with compiler in 12 is not signing at all which you want if you want to run a binary in osx-arm64.

**Comment by isuruf** [comment]
I meant that came with compiler 12. That cctools_osx-arm64 version was pulled because of that issue.
