### ISSUE TITLE
Conda skeleton pypi click fails; appears to be a version mismatch somewhere in conda-build

### ISSUE THREAD

**Issue by MattTriano** [conda/conda-build#4267]
### Actual Behavior

```
(dwh_env) matt@matt:~/projects/conda_forging$ conda skeleton pypi click
Warning, the following versions were found for click
0.1
0.2
0.3
 ...
8.0.0
8.0.1
Using 8.0.1
Use --version to specify a different version.
Using url https://files.pythonhosted.org/packages/21/83/308a74ca1104fe1e3197d31693a7a2db67c2d4e668f20f43a2fca491f9f7/click-8.0.1.tar.gz (320 KB) for click.
Downloading click
PyPI URL:  https://files.pythonhosted.org/packages/21/83/308a74ca1104fe1e3197d31693a7a2db67c2d4e668f20f43a2fca491f9f7/click-8.0.1.tar.gz
Unpacking click...
done
working in /tmp/tmp8qum3k3vconda_skeleton_click-8.0.1.tar.gz
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/matt/miniconda3/envs/dwh_env/conda-bld/skeleton_1628830340199/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main                
    _openmp_mutex:    4.5-1_gnu               
    ca-certificates:  2021.7.5-h06a4308_1     
    certifi:          2021.5.30-py39h06a4308_0
    ld_impl_linux-64: 2.35.1-h7274673_9       
    libffi:           3.3-he6710b0_2          
    libgcc-ng:        9.3.0-h5101ec6_17       
    libgomp:          9.3.0-h5101ec6_17       
    libstdcxx-ng:     9.3.0-hd4cf53a_17       
    ncurses:          6.2-he6710b0_1          
    openssl:          1.1.1k-h27cfd23_0       
    patch:            2.7.6-h7b6447c_1001     
    pip:              21.2.2-py39h06a4308_0   
    python:           3.9.6-h12debd9_0        
    pyyaml:           5.4.1-py39h27cfd23_1    
    readline:         8.1-h27cfd23_0          
    setuptools:       52.0.0-py39h06a4308_0   
    sqlite:           3.36.0-hc218d9a_0       
    tk:               8.6.10-hbc83047_0       
    tzdata:           2021a-h52ac0ba_0        
    wheel:            0.36.2-pyhd3eb1b0_0     
    xz:               5.2.5-h7b6447c_0        
    yaml:             0.2.5-h7b6447c_0        
    zlib:             1.2.11-h7b6447c_3       

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Applying patch: /tmp/tmp8qum3k3vconda_skeleton_click-8.0.1.tar.gz/pypi-distutils.patch
Applying patch: /tmp/tmp8qum3k3vconda_skeleton_click-8.0.1.tar.gz/pypi-distutils.patch with args:
['-Np0', '-i', '/tmp/tmp7hp1ttk5/pypi-distutils.patch.native', '--binary']
checking file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).

Leaving build/test directories:
  Work:
 /home/matt/miniconda3/envs/dwh_env/conda-bld/skeleton_1628830340199/work 
  Test:
 /home/matt/miniconda3/envs/dwh_env/conda-bld/skeleton_1628830340199/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/matt/miniconda3/envs/dwh_env/conda-bld/skeleton_1628830340199/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place 
  Build:
source activate  /home/matt/miniconda3/envs/dwh_env/conda-bld/skeleton_1628830340199/_build_env 


Traceback (most recent call last):
  File "/home/matt/miniconda3/envs/dwh_env/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 60, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 317, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 734, in get_package_metadata
    list_deps = get_dependencies(requires, is_setuptools_enabled(pkginfo))
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 840, in get_dependencies
    dep, marker = parse_dep_with_env_marker(dep_orig)
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 709, in parse_dep_with_env_marker
    env_mark = env_mark_lookup(match.group("env_mark_name"),
  File "/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 697, in env_mark_lookup
    marker = " ".join((env_mark_table[env_mark_name]["repl"],
KeyError: 'platform_system'
```

### Expected Behavior

It to just produce the example recipe skeleton .

### Steps to Reproduce

I tried with my prior working install of anaconda (from fall last year, although I keep conda up to date (ie it was at 4.10.3)) and it produced this error. To confirm I had a clean slate, installed and ran anaconda-clean, deleted ~/anaconda3/, and removed the `>>> conda initialize >>>` section from my ~/.bashrc file (then confirmed ~/.conda/, ~/.condarc, ~/.jupyter, ~/.ipython, and ~/anaconda3 were gone).

I reinstalled anaconda3, installed conda-build (into base), updated conda, and updated conda-build, but running `conda skeleton pypi click` produced the same issue. 

I cleared everything out again, but this time I:
* installed miniconda3, 
* created and activated a conda env (with the only env-establishing command being `$ conda create --name dwh_env python=3.9`)
* installed conda-build (`conda install conda-build`; installed conda-build               3.21.4           py39h06a4308_0, per conda list)

And it still produced the issue.

##### `Output of conda info`

```
conda info

     active environment : dwh_env
    active env location : /home/matt/miniconda3/envs/dwh_env
            shell level : 2
       user config file : /home/matt/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.11.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/matt/miniconda3  (writable)
      conda av data dir : /home/matt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/matt/miniconda3/pkgs
                          /home/matt/.conda/pkgs
       envs directories : /home/matt/miniconda3/envs
                          /home/matt/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/5.11.0-25-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False



```

In the location on my own machine indicated by the error message ("/home/matt/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/skeletons/pypi.py"), I noticed that the key ("platform_system") from the env_mark_table dict isn't anywhere in the vicinity of the lines throwing the error, but it does exist [right here](https://github.com/conda/conda-build/blob/580862030df2e811dc1b5135da1fa35802c571d0/conda_build/skeletons/pypi.py#L718
)(last commit was on June 3rd) in the corresponding file in the conda-build repo.

Also, per `ls -la` of the dir indicated in the recent paranthetical, I noticed the last modified date for the `pypi.py` file was Jan 15, 2021, but the [info page](https://anaconda.org/anaconda/conda-build/files/modal/info/6100fb7dee2e669d466792b2) for the build of my conda-build package (py39h06a4308_0) indicates that build was pushed up on July 28, 2021.

```
~/miniconda3/envs/dwh_env/lib/python3.9/site-packages/conda_build/skeletons$ ls -la
total 216
drwxrwxr-x 3 matt matt  4096 Aug 12 23:51 .
drwxrwxr-x 7 matt matt  4096 Aug 12 23:51 ..
-rw-rw-r-- 2 matt matt 40983 Jan 15  2021 cpan.py
-rw-rw-r-- 2 matt matt 64999 Jan 15  2021 cran.py
-rw-rw-r-- 2 matt matt  1209 Jan 15  2021 _example_skeleton.py
-rw-rw-r-- 2 matt matt     0 Jan 15  2021 __init__.py
-rw-rw-r-- 2 matt matt 12145 Jan 15  2021 luarocks.py
drwxrwxr-x 2 matt matt  4096 Aug 12 23:51 __pycache__
-rw-rw-r-- 2 matt matt 48172 Jan 15  2021 pypi.py
```
So, can anyone help me make sense of what I'm seeing? Was my build of conda-build built wrong?

**Comment by elmjag** [comment]
A possible workaround is to use older version of 'click' package, for example version 7.1.2:
Following command worked for me:

    conda skeleton pypi click --version 7.1.2

This is using conda-build 3.21.4 and conda 4.10.3.

**Comment by MattTriano** [comment]
Thanks, that did get me to my intermediate goal (which was to work through this [trivial example in the conda-build documentation](https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html)). I was able to pull that recipe, and I was also able to build it, but installing the locally created build was a bit of a pain as conda kept ignoring the `--use-local` flag when I tried to install the build (causing conda to keep proposing "package plans" that involved downloading the most recent version of click from conda-forge). I tried
* unsuccessful attempt 1 (hypothesis: strict channel_priority in .condarc overriding --use-local):
   * deleted my `.condarc` file
   * opened a new terminal 
   * created and activating a new env (`conda create --name smithy_env python=3.9`),
   * `conda install conda-build`,
   * `conda skeleton pypi click --version 7.1.2`
   * `conda-build click`
   * `conda install --use-local click`  
* unsuccessful attempt 2 (hypothesis: keep strict channel_priority, but with `local` as the highest priority channel)
   * Removed, recreated, and activated `smithy_env` (as above)
   * made an env-specific config (`conda config --env --set channel_priority strict`),
   * added `local` as the highest priority channel (`conda config --env --add channels local`),
   * same skeleton, build, and install --use-local steps as above
* successful-ish attempt:
   * Reset my regular global `.condarc` settings (just adding conda-forge and setting channel_priority as strict),
   * `conda skeleton pypi click --version 7.1.2`
   * `conda-build click`
   * `conda install --use-local ~/miniconda3/envs/smithy_env/pkgs/click-7.1.2-py39_0.tar.bz2`

My main goal is to learn enough about packaging for conda-forge that I can update the [geoalchemy2-feedstock](https://github.com/conda-forge/geoalchemy2-feedstock) that appears to be abandoned/unmaintained, as it's required for some geopandas functionality and I dislike using pip to install packages into my conda envs.
 
I don't have any prior experience building or distributing packages using conda (I've made a couple personal packages via pip), so when I tried to [locally test](https://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally) my changes to that feedstock, I ran into (presumably) the issues that caused the reviews to fail on the [most recent pull-request](https://github.com/conda-forge/geoalchemy2-feedstock/pull/15). Hopefully the knowledge gained in this afternoon of yak-shaving will pay off.

Anyway, I assume the conda-build tutorial gets a small-but-steady amount of traffic, so I'll assume that the relative scarcity of other issues indicates it's probably a quirk of my setup or something vs a reproducible issue that everyone working through the tutorial will encounter, so I'll close this out.

Thanks again for the tip.
