### ISSUE TITLE
Add warning in conda build documentation that recipe files are put into the package

### ISSUE THREAD

**Issue by seibert** [conda/conda-build#427]
Although I would consider this bad practice, it is possible that someone will put login credentials or other sensitive items into their conda-build recipe files (meta.yaml, build.sh, etc), not realizing those files are also saved in the final package archive they plan to distribute.

I think the recipe-saving behavior should be highlighted with a warning in the conda-build documentation somewhere.

**Comment by asmeurer** [comment]
@kerrywatson1 @electronwill
