### ISSUE TITLE
Allow simple regex with `always_include_files`

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#428]
At present, it appears an exact filename must be supplied here and if they are not found a failure occurs. However, this is a problem if a library is kept via this method (e.g. `dylib` on mac and `so` on linux). Alternatively, if I want to save a library and don't care about the version, this would be very helpful, as well.

**Comment by asmeurer** [comment]
You can use selectors to handle that case (see for instance https://github.com/conda/conda-recipes/blob/master/libgcc/meta.yaml). Matching a glob wouldn't be a bad idea, though.

**Comment by jakirkham** [comment]
Thanks for the suggestion. I did try selectors and they worked fine.

However, I think regex could help with make `meta.yml` a bit more terse. For example, if I have `lib/libquadmath.so.0.0.0`, it follows that I will want `lib/libquadmath.so.0` and `lib/libquadmath.so`.

**Comment by ilanschnell** [comment]
With #484 being merged, I think we can close this issue.
