### ISSUE TITLE
Noarch packages are placed into the wrong directory on build

### ISSUE THREAD

**Issue by srossross** [conda/conda-build#429]
When I build a noarch package it still gets placed in the `osx-64` subdirectory.

```
# If you want to upload this package to binstar.org later, type:
#
# $ binstar upload /Users/sean/anaconda/conda-bld/osx-64/flask-0.10-py_1.tar.bz2
#
# To have conda build upload to binstar automatically, use
# $ conda config --set binstar_upload yes
```

`/Users/sean/anaconda/conda-bld/osx-64/flask-0.10-py_1.tar.bz2` should be `/Users/sean/anaconda/conda-bld/noarch/flask-0.10-py_1.tar.bz2`

**Comment by hargup** [comment]
@ilanschnell @asmeurer I'm also facing the same issue, any hints on solving it?
