### ISSUE TITLE
`py3k` selector is broken for Python 3.10

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#4324]
### Actual Behavior

Tried building a recipe that used the `py3k` selector on conda-forge for Python 3.10. The selector evaluated to `False` which meant, in combination with the other selectors, that there was no build script, so the build failed.

### Expected Behavior

`py3k` should evaluate to `True` for Python 3.10.

### Steps to Reproduce

I can't reproduce this locally (don't have a Windows machine handy) but:

+ The recipe line that failed is here: https://github.com/conda-forge/galpy-feedstock/pull/24/commits/0a11b4d77dd1c5031e67c57240703f860efa5ae0#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR19
+ This caused the build failure here: `https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=411270&view=logs&j=2d03c380-16cc-53df-474d-81b5b5dc65ac&t=4f8f475c-3e8e-56b8-f5aa-7599dd696a73&l=142`

Changing the selector from `py3k` to `py>=3.6` fixed it (and covered the python versions that needed to be covered).

The problematic line of code in `conda build` is here: https://github.com/conda/conda-build/blob/0a6efdcfa02484954e7a3fdf5c2ec4bb3cb6682e/conda_build/metadata.py#L103

Unfortunately, I don't see an straightforward fix when `py` is `310`...

##### `Output of conda info`

Unfortunately, I can't easily get that....

**Comment by kenodegard** [comment]
Duplicates of #4297 and #4032 

The `py*` selectors are technically deprecated (we are aware this has not been officially communicated/formalized via documentation) so please use the `py>=*` selectors moving forward.
