### ISSUE TITLE
conda pipbuild Dabo - build failure on Windows 7 64-Bit, Python 2.7.9

### ISSUE THREAD

**Issue by ReddyKilowatt** [conda/conda-build#433]
While installing Dabo on Windows 7 with Conda, the following error occurred

C:\Users\ReadyK>conda pipbuild Dabo
Package search: {'_pypi_ordering': False, 'version': '0.9.6', 'name': 'Dabo', 'summary': 'Dabo 3-tier Application Framework'}
Fetching package metadata: ....
Creating standard recipe for dabo-0.9.6
Using url https://pypi.python.org/packages/source/D/Dabo/Dabo-0.9.6.tar.gz (617 KB) for Dabo.
Downloading Dabo (use --no-download to skip this step)
Using cached download
Unpacking Dabo...
done
working in c:\users\ReadyK\appdata\local\temp\tmpppfqz0conda_skeleton_Dabo-0.9.6.tar.gz
Fetching package metadata: ......
Solving package specifications: .
Applying patch: 'c:\users\ReadyK\appdata\local\temp\tmpppfqz0conda_skeleton_Dabo-0.9.6.tar.gz\pypi-distutils.patch'
Error:
    Did not find 'patch' in: C:\Anaconda\envs_build\Scripts;C:\Anaconda\Scripts;C:\cygwin\bin;C:\Program Files\SlickEdit Pro 19.0
.2\win\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPow
erShell\v1.0\;C:\Anaconda;C:\Anaconda\Scripts;C:\Program Files\010 Editor;
    You can install 'patch' using apt-get, yum (Linux), Xcode (MacOSX),
    or conda, cygwin (Windows),

conda create -n _pipbuild_ --yes python pip
Error: prefix already exists: C:\Anaconda\envs_pipbuild_
C:\Anaconda\envs_pipbuild_/bin/pip install Dabo==0.9.6
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-pipbuild-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 77, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 329, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 363, in execute
    build_package(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 307, in build_package
    directory, dependencies = make_recipe(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 250, in make_recipe
    depends = get_all_dependencies(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 218, in get_all_dependencies
    ret = subprocess.Popen(cmd2.split()).wait()
  File "C:\Anaconda\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Current conda install:

```
         platform : win-64
    conda version : 3.11.0-dirty
```

  conda-build version : 1.13.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by remram44** [comment]
Did you install patch as requested by the error message?

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
