### ISSUE TITLE
How do you update conda channel's meta data 

### ISSUE THREAD

**Issue by achapkowski** [conda/conda-build#4342]
Following this guide: https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html

I created my package using first conda skeleton then build.  To get the packages for other operating systems I used conda convert.  My question is this:

How do I update a local conda channel to pick up these new builds for the various OS?  

My win-64 contains all the expected files:
![image](https://user-images.githubusercontent.com/5131271/144655002-502f2fed-4a28-4a05-b19a-db0d492bdf68.png)

But the other OS only contains the files:

![image](https://user-images.githubusercontent.com/5131271/144655171-45b2e1d3-4b54-445f-a9dc-343d723d2cd2.png)

Is there a way to rebuild the channel's `json` files?

**Comment by kenodegard** [comment]
Use [`conda index`](https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-index.html) see https://conda.io/projects/conda-build/en/latest/concepts/generating-index.html for more info.

**Comment by achapkowski** [comment]
Thank you
