### ISSUE TITLE
conda-pipbuild fails for django

### ISSUE THREAD

**Issue by hargup** [conda/conda-build#436]
```
$ conda pipbuild django
Error:  PyPI does not have a package named django
```

The xmlrpc client fails to find releases for lowercase `django` because the name of the package on PyPI is `Django`. We need to follow `conda-skeleton` style name normalization to fix this problem.

**Comment by jakirkham** [comment]
So, this actually works with the latest version of `conda`. Though it sounds like `pipbuild` is deprecated and scheduled for removal. Turns out `conda skeleton pypi` works. In any event, this issue should be closed.
