### ISSUE TITLE
ENH add option to test run env for solvability only

### ISSUE THREAD

**Issue by beckermr** [conda/conda-build#4367]
We've encountered a case where we want to test that an env is solvable but not actually run the tests because we are cross-compiling. It'd be nice to be able to test that run envs are solvable without actually running the tests. I cannot current seem to configure conda-build to work this way.

**Comment by chenghlee** [comment]
Is the ask here being able to run something like `conda create --dry-run -p ${CONDA_TEST_PREFIX} <your host + test deps>` using conda build and the recipe?

**Comment by beckermr** [comment]
I'd like to run the test during a feedstock build. So basically a finer grained version of the --no-test option.
