### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4370]
### Description

Need to investigate changes necessary to support Python 3.11.

```[tasklist]
- [x] distutils is deprecated in stdlib
- [x] Get Python 3.11 build (even if alpha) to test conda and conda-build
- [x] Review 3.11 release notes to see if other (packaging) related changes are expected
- [ ] https://github.com/conda/conda/issues/11170
- [ ] https://github.com/conda/conda-build/pull/4852
```

**Comment by jezdez** [comment]
@chenghlee Can you ask the packaging team to look into whether we can/should build a Python 3.11 early release package to a separate channel (conda-canary?) to try this out? We could set up the CI system to use the channel while it hasn't officially been released yet to be part of defaults.

**Comment by kenodegard** [comment]
if the package is released as a beta version, it won't be selected for installation unless explicitly requested, so per that understanding, it shouldn't be problematic to release to `main` either? making the beta releases generally available should help other packages with their testing too

**Comment by kenodegard** [comment]
Depends on conda/conda#11170
