### ISSUE TITLE
pymol-open-source -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

### ISSUE THREAD

**Issue by biotech70** [conda/conda-build#4371]
Hi, I encounter an error while installing the Pymol with the following command:
conda install -c tpeulen pymol-open-source
![conda error](https://user-images.githubusercontent.com/73783725/151453715-c3b32212-6e63-4aaa-8127-98ae58697d33.png)

**Comment by jezdez** [comment]
Your environment is based on Python 3.9 but the package you're trying to install needs a Python version between 3.8 and 3.9.0a0, the latter being the alpha version of Python 3.9. That alpha version isn't included in the supported version range of the package, basically. I'd suggest filing a ticket in the pymol-open-source project to update the Python version range to include Python 3.9.*.

Hope that helps!
