### ISSUE TITLE
Unable to use Nvidia cudnn and x86_64-conda_cos6-linux-gnu-g++ together

### ISSUE THREAD

**Issue by snnn** [conda/conda-build#4390]
### Actual Behavior

Build fails

```
/opt/miniconda/x86_64-conda-linux-gnu/sysroot/usr/include/wctype.h:289:37: error: 'wctype_t' has not been declared
  289 | extern int iswctype_l (wint_t __wc, wctype_t __desc, __locale_t __locale)
```
### Expected Behavior

Build pass

### Steps to Reproduce
Create a simple c++ file
```c++
#include <sstream>

int main(){
  return 0;
}
```
The compile it by:
```bash
/opt/miniconda/bin/x86_64-conda_cos6-linux-gnu-g++  -I/usr/include/x86_64-linux-gnu    -o t test.cpp
```
You may curious why I added "/usr/include/x86_64-linux-gnu" there. This is just because it is where CUDNN(or TensorRT) header files were installed.
TO verify, you can try their docker images:
```
docker run --rm nvcr.io/nvidia/cuda:11.5.1-cudnn8-devel-ubuntu20.04 ls /usr/include/x86_64-linux-gnu
```
The document of conda-build says: "Anaconda 5.0 switched from OS-provided compiler tools to our own toolsets". So, is it a must? What if I continue to use the system gcc to produce Anaconda packages? 

##### `Output of conda info`
It was installed from Miniconda3-py39_4.11.0-Linux-x86_64.sh

**Comment by beeankha** [comment]
@snnn , could you please post the output you get from `conda list`? Also, do you have a `conda` recipe?

**Comment by snnn** [comment]
No, I don't have.  I think the point is conda compiler doesn't want me to use header files from /usr/include/x86_64-linux-gnu, but it is where CUDNN installed.

**Comment by snnn** [comment]
Thanks. I will close it.
