### ISSUE TITLE
Feature request: Allow conda-build to verify downloaded packages against a signature

### ISSUE THREAD

**Issue by teh** [conda/conda-build#44]
A signature looks e.g. like:

http://cvc4.cs.nyu.edu/builds/src/cvc4-1.3.tar.gz.asc

and can be verified like this:

```
$ gpg --verify cvc4-1.3.tar.gz.asc  ~/conda-bld/src_cache/cvc4-1.3.tar.gz
```

I'm unclear on how to best implement this. Checking against  a key requires e.g. importing said key via `gpg --recv-keys`. I don't know where in the process this should happen.

**Comment by orodbhen** [comment]
Has any progress been made on this?
