### ISSUE TITLE
Setuptools' `read_configuration` used in `load_setup_py_data` deprecated

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#4428]
Currently in `load_setup_py_data`, the `read_configuration` function from Setuptools is used

https://github.com/conda/conda-build/blob/0a6efdcfa02484954e7a3fdf5c2ec4bb3cb6682e/conda_build/_load_setup_py_data.py#L50

However when this `import` is encountered the following warning comes up

```python
/opt/conda/lib/python3.9/site-packages/setuptools/config/__init__.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
`setuptools.config.read_configuration` became deprecated.

For the time being, you can use the `setuptools.config.setupcfg` module
to access a backward compatible API, but this module is provisional
and might be removed in the future.

  warnings.warn(dedent(msg), SetuptoolsDeprecationWarning)
```

Potentially `setupcfg` could be used for the time being. Though as noted in the warning this may go away.

**Comment by jakirkham** [comment]
Maybe [PEP 650]( https://peps.python.org/pep-0650/ ) would be relevant?

**Comment by jakirkham** [comment]
@marcelotrevisani mentioned this issue is cropping up in Grayskull as well. Do you have more context (perhaps an issue link), Marcelo? No worries if not. Just trying to track all the pieces 🙂

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda/conda-build/pull/4430 ) to fix the deprecation warning. That is relatively straightforward.

The longer term question is how we handle `setupcfg` going away in the future. Don't have a clear answer there. Maybe someone else does?

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani mentioned this issue is cropping up in Grayskull as well. Do you have more context (perhaps an issue link), Marcelo? No worries if not. Just trying to track all the pieces 🙂

hey, I do not have an open issue for that :/
