### ISSUE TITLE
Documentation: conda index --no-remove in docs, not in program

### ISSUE THREAD

**Issue by dholth** [conda/conda-build#4441]
### Actual Behavior

Documentation shows `conda index --no-remove` but running `conda index --help` does not

### Expected Behavior

Documentation should match program behavior.

**Comment by travishathaway** [comment]
Hi @dholth,

Thanks for reporting this. It appears as if the docs for conda index (https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-index.html?highlight=conda%20index) and the output from running `conda index --help` have actually drifted considerably. The date of `June 2018` near the bottom of that page is also concerning. >_<

I'm going to create another issue describing this and hopefully tie it into a greater "our documentation needs some TLC" epic.

**Comment by dholth** [comment]
@travishathaway of course there are tools for this. https://sphinx-argparse.readthedocs.io/en/stable/ was the first one I found.

**Comment by travishathaway** [comment]
@dholth, I am pretty sure that https://github.com/conda/conda is already using this or something very similar to it. I believe the best route forward may simply be to copy that repo's approach.
