### ISSUE TITLE
Conda build should have several stages to be called independently

### ISSUE THREAD

**Issue by oleg-alexandrov** [conda/conda-build#4471]
### Summary

The conda-build toolset is nice and save work, but can be a pain to use because it is very slow. Then, if it fails, one has to restart everything, wait for a long time, and then likely fail again, and having to restart.

It should have the ability to resume a failed build, and also to resume at packaging, if that step failed. This would really save a lot of work. 

### Linked Issues & PRs

None

**Comment by LtDan33** [comment]
Thanks for the suggestion! Can you please open this via: https://github.com/conda/conda/issues/new?assignees=&labels=type%3A%3Afeature&template=feature-request.yml? This issue type is used to group things on the conda-core team.

**Comment by LtDan33** [comment]
The `epic` label and issue is used to group tickets together by the conda-core devs, so removing for now.

**Comment by oleg-alexandrov** [comment]
To add, it would be nice if this tool would have stages, such as:

 conda-build --resume-build (resume latest build where it used to fail before, do not get dependencies) 

 conda-build --package (start at packaging, so after build/install)

This way the programmer can try to fix things then let conda-build take over.

**Comment by oleg-alexandrov** [comment]
Hoping this is looked into. Conda is so awfully slow, and debug cycles take a very long time. Conda should have a way of using a given environment without having to solve dependencies each time, and it should be able to resume where it failed.
