### ISSUE TITLE
Split conda index into separate package

### ISSUE THREAD

**Issue by jezdez** [conda/conda-build#4472]
### Actual Behavior

conda-index is quite the complex functionality that would profit from a evolution (e.g. https://github.com/dholth/conda-build/pull/3) independent from the rest of the conda-build repo. That's the same reason as https://github.com/conda/conda/issues/11234.

### Expected Behavior

There should be a conda-index repo under the conda-incubator GitHub org with an own dedicated project team following the [conda governance policy](https://github.com/conda-incubator/governance).

I'd be happy to facilitate the necessary administrative steps to make this happen.

/cc @chenghlee @dholth

**Comment by dholth** [comment]
Yes we need to do this.

**Comment by jezdez** [comment]
We've kickstarted this process by creating a project in the conda-incubator: https://github.com/conda-incubator/conda-index

If anyone is interested in being part of that project team, please let me know!

**Comment by jezdez** [comment]
Closing as this has been done.
