### ISSUE TITLE
does conda-build need to index as a side effect

### ISSUE THREAD

**Issue by dholth** [conda/conda-build#4474]
This calls update_index which is a little surprising. https://github.com/conda/conda-build/blob/1ed8da062f123e1fbca604df26b064b267a3d094/conda_build/build.py#L3394

**Comment by chenghlee** [comment]
In certain cases, yes; e.g., if you're building up a set of related packages like distributed/dask-core/dask, you'll need `conda index` so the appropriate version in the dependency chain is available in the `local` channel. Multi-output recipes may also need to run `conda index` as an intermediate step if one output depends on another, either as a build- or test-time dependency.

**Comment by dholth** [comment]
@chenghlee I think I understand https://github.com/conda/conda-build/blob/master/conda_build/index.py#L173 a little better, but not enough to replace it with new conda index. It downloads some things, and it also updates an index of a local directory. The updating part might happen in a subprocess so that `conda-index` can use different Python & dependencies?
