### ISSUE TITLE
ImportError: cannot import name 'itervalues' from 'conda.common.compat'

### ISSUE THREAD

**Issue by tonigi** [conda/conda-build#4481]
This line https://github.com/conda/conda-build/blob/1ed8da062f123e1fbca604df26b064b267a3d094/conda_build/utils.py#L2085 references `from conda.common.compat import itervalues` which was   removed from conda 4.13. See also https://github.com/conda/conda/pull/11364

**Comment by kenodegard** [comment]
@tonigi thanks for reporting this, working on a fix in #4482

**Comment by ngam** [comment]
Does this necessitate a patch/minor release in conda-build or what's the timeline for releasing this fix widely?
