### ISSUE TITLE
Add support for shared libraries that require multiple paths in RPATH.

### ISSUE THREAD

**Issue by tpn** [conda/conda-build#45]
This is primarily required for R, although it could very well be applicable to other projects or libraries that have a similar situation.

**Comment by pelson** [comment]
FWIW the PR didn't add the ability to have multiple rpaths - what was implemented was a blanket replacement of current RPATH with ``$ORIGIN/../../lib``. In some cases, that isn't wholly desirable IMHO - e.g. I'm currently building numpy on a HPC which has MKL shipped in a specific vendor specified location.

**Comment by tpn** [comment]
That doesn't sound right.  I remember adding support for adding whatever RPATHs were necessary, which would sometimes include more than one.

**Comment by pelson** [comment]
> That doesn't sound right. I remember adding support for adding whatever RPATHs were necessary, which would sometimes include more than one.

Ah - I've just realized that you need to specify ``build/rpaths``. So the rpaths do get nuked, but you can control what they get nuked with.

Sorry for the noise!

**Comment by pelson** [comment]
> but you can control what they get nuked with.

Except, it looks like they can't be absolute paths. Am I missing something or is this an uncommon requirement?

**Comment by asmeurer** [comment]
I think absolute rpaths weren't thought of when this change was made. We can add support for them.

**Comment by asmeurer** [comment]
See https://github.com/conda/conda-build/pull/347. Let me know if that works for you.

**Comment by pelson** [comment]
> I think absolute rpaths weren't thought of when this change was made. We can add support for them.

Thanks @asmeurer. I haven't tested, but it looks good. I'll try to take it for a spin in the next couple of days.

**Comment by sandhujasmine** [comment]
Looking at the [code changes](https://github.com/asmeurer/conda-build/commit/0148df3d08cdb240e9b820a404249a0711377205), conda detects user wants an absolute path if the path begins with a '/' else it must be relative. This is a subtle difference and should be added to [documentation](http://conda.pydata.org/docs/building/meta-yaml.html#rpaths)
