### ISSUE TITLE
Inconsistency of language around dependencies

### ISSUE THREAD

**Issue by birdcolour** [conda/conda-build#4500]
It's a pretty small problem, but I was curious why there are so many different names in different places to specify what is essentially the same thing: a list of packages that are needed to do something.

If I just want to make a conda environment, I can specify this list under the key _`dependencies`_ in `environment.yml`:
```
name: some_env
dependencies:
  - foo
  - bar
```

If I want to specify a list for building my package, these go under the specific build step under the key _`requirements`_ in `meta.yml`:
```
requirements:
  run:
    - foo
    - bar
```

If I need a list of packages to run tests, then this goes under the separate test section under the key _`requires`_:

```
test:
  requires:
    - foo
    - bar
```

... what gives? Is there some subtle difference between `dependencies`, `requirements`, and `requires` that I'm not appreciating? If not, I would propose that one if these is picked to replace the others, to minimise confusion.

**Comment by skupr-anaconda** [comment]
`Requirements` can be different in `meta.yaml`: `build` (for building a package), `host` (e.x., for installing a package), and `run` (for running a package).
In the `test` environment you can see in logs all `run` dependencies but sometimes the package `requires` other packages to test it (for example, pytest, pytest-cov, etc.)
In `environment.yml` a package has different `dependencies` (for running, testing, and so on).
