### ISSUE TITLE
ImportError: cannot import name 'itervalues' from 'conda.common.compat'

### ISSUE THREAD

**Issue by kejang** [conda/conda-build#4509]
### Summary

Hello all,

I'm getting the following message when I try to use conda build:
```code
File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/utils.py", line 2070, in linked_data_no_multichannels
    from conda.common.compat import itervalues
ImportError: cannot import name 'itervalues' from 'conda.common.compat'
```

I looked over `conda/common/compat.py`, and couldn't find any code related to `itervalues`.

You can reproduce this error by running following codes:
```bash
conda create -n bug_report python=3.8
conda activate bug_report
git clone https://github.com/pybind/python_example.git
cd python_example/conda.recipe
conda build .
```

This example is included in Pybind11 repository.

### Linked Issues & PRs

- ImportError: cannot import name 'itervalues' from 'conda.common.compat'

**Comment by kenodegard** [comment]
Duplicate of #4481
