### ISSUE TITLE
Sporadic failures on Windows when trying to create test-tmp_dir

### ISSUE THREAD

**Issue by rekcahpassyla** [conda/conda-build#452]
Sometimes when building local packages on windows, I get this error:

``` python
Traceback (most recent call last):
  File "C:\dev\bin\Anaconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\dev\bin\Anaconda\lib\site-packages\conda_build\main_build.py", line 112, in main
    args_func(args, p)
  File "C:\dev\bin\Anaconda\lib\site-packages\conda_build\main_build.py", line 321, in args_func
    args.func(args, p)
  File "C:\dev\bin\Anaconda\lib\site-packages\conda_build\main_build.py", line 309, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\dev\bin\Anaconda\lib\site-packages\conda_build\build.py", line 442, in test
    os.makedirs(tmp_dir)
  File "C:\dev\bin\Anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: 'C:\\dev\\bin\\Anaconda\\conda-bld\\test-tmp_dir'
```

Looking at the source of [`build.py`](https://github.com/conda/conda-build/blob/72254e0f31f02ffd8157a7bbc40237ba43f14ac6/conda_build/build.py#L442-L443), I believe this is triggering this condition:

http://stackoverflow.com/questions/16373747/permission-denied-doing-os-mkdird-after-running-shutil-rmtreed-in-python%E2%80%8B

Output of `conda info`:

```
Current conda install:

             platform : win-64
        conda version : 3.13.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\dev\bin\Anaconda  (writable)
  default environment : C:\dev\bin\Anaconda
     envs directories : C:\dev\bin\Anaconda\envs
        package cache : C:\dev\bin\Anaconda\pkgs
         channel URLs : 
                        http://repo.continuum.io/pkgs/dev/win-64/
                        http://repo.continuum.io/pkgs/dev/noarch/
                        http://repo.continuum.io/pkgs/gpl/win-64/
                        http://repo.continuum.io/pkgs/gpl/noarch/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        file:///c:/testrepo/win-64/
                        file:///c:/testrepo/noarch/
          config file : C:\Users\username\.condarc
    is foreign system : False
```

I have a local fix which I'm happy to submit but I can't test it on non-windows platforms.

**Comment by ccordoba12** [comment]
Yes, please submit it.

**Comment by rmcgibbo** [comment]
I get this `Access is denied` repeatedly on Appveyor and on my local Win8 machine from `conda.install.rm_rf`, and unfortunately it's not fixed by #453.

**Comment by rmcgibbo** [comment]
FWIW, it always happens for me with markupsafe's _speedups.pyd, which presumably is loaded when jinja2 is imported.

**Comment by asmeurer** [comment]
See https://github.com/conda/conda-build/pull/520#issuecomment-127407660. I think this is a separate issue (unfortunately, Windows error messages don't do a very good job of separating distinct errors). In this issue, there is a race condition between deleting a directory and re-creating it. In the _speedups.pyd case, it's the Windows file lock preventing a running DLL from being removed.
