### ISSUE TITLE
Skipping check_overlinking

### ISSUE THREAD

**Issue by moqmar** [conda/conda-build#4533]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I want to completely disable the check_overlinking function, or provide a list of files that shouldn't be checked at all (i.e. exclude them from files_to_inspect).

### Why is this needed?

I have a package that's basically lots of binary DLLs which should stay exactly as they are. When running "conda build", those DLLs are all checked for overlinking, a process that takes more than two hours (at least that's when I cancelled it).

I'm guessing the overlinking check can be quite important especially when not knowing the target environment perfectly, but it also most definitely shouldn't take two hours, so having a workaround for large binary packages makes sense IMO.

### What should happen?

There should be either a command-line option `--skip-overlinking`, or an option `build.skip_check_overlinking` in meta.yaml similar to skip_compile_pyc.

**Comment by skupr-anaconda** [comment]
If you add `abs.yaml` inside the recipe folder with this content:
```
# the conda-build parameters to use
build_parameters:
  - "--no-error-overlinking"
```

can it resolve your issue?
