### ISSUE TITLE
Docs: s390x selector missing from docs

### ISSUE THREAD

**Issue by bkreider** [conda/conda-build#4536]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This page in the documenation: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors is missing the `s390x` selector.

It just needs the s390x selector added to the table.

**Comment by skupr-anaconda** [comment]
@bkreider The issue was resolved, see https://github.com/conda/conda-build/pull/4550
