### ISSUE TITLE
Docs: `~=` is missing as valid specifier 

### ISSUE THREAD

**Issue by BastianZim** [conda/conda-build#4553]
According to the [docs](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#build-version-spec) `~=` is not supported as a specifier but it seems to have been introduced in https://github.com/conda/conda-build/releases/tag/3.20.5

Note: This came up in https://github.com/conda-incubator/grayskull/issues/348

**Comment by BastianZim** [comment]
Still an issue

**Comment by ryanskeith** [comment]
I can work this.
