### ISSUE TITLE
SPIKE: Investigate `python -m` usage

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4561]
### What happened?

While working on recent issues:

- https://github.com/conda/conda/pull/11589
- https://github.com/conda/conda/issues/11698
- https://github.com/conda/conda-build/pull/4556
- https://github.com/conda/conda/pull/11704
- https://github.com/conda/conda/pull/11700
- https://github.com/conda/conda/pull/11709
- https://github.com/conda/conda/pull/11666
- https://github.com/conda/conda/issues/11724
- https://github.com/conda/conda/pull/11720

we found that conda-build invokes conda via `python -m` in a few instances, causing issues when building conda itself:

- https://github.com/conda/conda/actions/runs/2820051398
- https://github.com/conda/conda/actions/runs/2835251119

Instead of invoking and using the installed conda to build the new package, conda-build manages to invoke the source code. This appears to be a result of the `python -m` side-effect.

**Comment by dholth** [comment]
```[-I](https://docs.python.org/3/using/cmdline.html#cmdoption-I) option can be used to run the script in isolated mode where [sys.path](https://docs.python.org/3/library/sys.html#sys.path) contains neither the current directory nor the user’s site-packages directory. All PYTHON* environment variables are ignored, too.``` 

https://docs.python.org/3/using/cmdline.html#cmdoption-m

**Comment by kenodegard** [comment]
# `python -m`

https://github.com/conda/conda-build/blob/6a1cea0111f53417aeb631aa54d7cc26d26d6628/conda_build/skeletons/pypi.py#L368

https://github.com/conda/conda-build/blob/6a1cea0111f53417aeb631aa54d7cc26d26d6628/conda_build/build.py#L1825

https://github.com/conda/conda-build/blob/6a1cea0111f53417aeb631aa54d7cc26d26d6628/conda_build/build.py#L2740

# `_CE_M`: shell activation `--dev` "feature"

https://github.com/conda/conda-build/blob/6a1cea0111f53417aeb631aa54d7cc26d26d6628/conda_build/build.py#L2731-L2738
