### ISSUE TITLE
Fix `python -m` issue

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4572]
We currently have failing canary builds, and we are seeing two different types of errors:

-  [ModuleNotFoundError: No module named 'tlz'](https://github.com/conda/conda/runs/7731850991?check_suite_focus=true#step:10:803)
- [ModuleNotFoundError: No module named 'conda'](https://github.com/conda/conda/runs/7774814177?check_suite_focus=true#step:10:2152)

To address this, we first need to recreate these errors outside of CI and then implement a fix based on our findings. A fair amount of research has already been accomplished in this issue #4561.

One thing to keep in mind is that there are several different places where a fix could potentially be implemented:

- [conda itself](https://github.com/conda/conda)
- [conda-build](https://github.com/conda/conda-build)
- [conda-feedstock](https://github.com/AnacondaRecipes/conda-feedstock)

**Comment by travishathaway** [comment]
We need to get this test working: https://github.com/conda/conda/blob/main/conda.recipe/run_test.sh

**Comment by travishathaway** [comment]
Looks like the fix may be adding this line near the top of the `run_test.sh` script:

```bash
conda init --all
```

The important operation that this command performs is modifying the entry point scripts. I got the following output after testing it successfully locally:

```bash
modified      $PREFIX/condabin/conda
modified      $PREFIX/bin/conda
modified      $PREFIX/bin/conda-env
# remaining output truncated...
```

We can assume that it modified the entry point script to actually point at the Python interpreter we care about. This solution still isn't 100% satisfactory though as I really wish I knew what was causing this to be created incorrectly in the first place. But, I also fear that may be a rabbit hole not worth venturing down, so I will propose this solution in a separate pull request for our [conda feedstock](https://github.com/AnacondaRecipes/conda-feedstock).

**Comment by travishathaway** [comment]
I'm going to block this issue until we do our release this week. There were some issues with the build on [conda-feedstock](https://github.com/AnacondaRecipes/conda-feedstock) that will be resolved after this upcoming release.

**Comment by travishathaway** [comment]
This issue has been resolved by recent updates to the [AnacondaRecipe/conda-feedstock](https://github.com/AnacondaRecipes/conda-feedstock/pull/14)
