### ISSUE TITLE
Documentation: `load_file_regex`

### ISSUE THREAD

**Issue by dholth** [conda/conda-build#4585]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When using `load_file_regex` to load the version number for a package, I had to use it as follows:

```
{% set version_match = load_file_regex(
  load_file="conda_package_streaming/__init__.py", 
  regex_pattern='^__version__ = "(.+)"') %}
{% set version = version_match[1] %}
```

Differences from the documentation:

* Jinja2 won't allow a r'' raw string
* `version_match.string` is the entire line (the 0'th match). The match object can be indexed, or `.groups()` or `.group(n)` to get the desired match.

[Documentation here](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files)

**Comment by alchem0x2A** [comment]
Thx @dholth  ! hope this issue get fixed as I had the exact error following the official doc and found solution in this issue.
