### ISSUE TITLE
conda build folder naming inconsistant for noarch packages

### ISSUE THREAD

**Issue by meawoppl** [conda/conda-build#462]
Noarch package files created by conda build end up in the operating system specific build folder.  

For my linux machine noarch packages end up in the ```anacondaRoot/conda-bld/linux-64``` directory.  To be consistent with the schema used to serve packages, it ought to be put in something like ```anacondaRoot/conda-bld/noarch``` 

This makes automated scripts to merge multi-platform repositories need to consider the repodata of each and reassign package locations.

**Comment by meawoppl** [comment]
Also it seems that conda update will become angry if there is only noarch folder structures.  In general the noarch settings family seems to need some more thought/support.

**Comment by hargup** [comment]
@meawoppl This issue was reported at https://github.com/conda/conda-build/issues/429  and was fixed at https://github.com/conda/conda-build/pull/443 . Please use the latest master to use these changes and then let us know if they work for you.

**Comment by meawoppl** [comment]
The current conda-build package seems to reflect these changes.  Much thanks.  

The other note about noarch install issues stands.  There is an easy workaround by adding a empty package repodata.json file, but it seems strange that noarch and linux-64 channels are handled differently.  Should I start a issue on conda?

**Comment by hargup** [comment]
Sure, open an issue, a PR is also welcomed.

**Comment by meawoppl** [comment]
Thanks @hargup I mentioned a couple solutions in the issue I opened above.  Any opinions on the proposed fixes?
