### ISSUE TITLE
conda-build's documentation should mention the .conda format and not just .tar.bz2

### ISSUE THREAD

**Issue by dholth** [conda/conda-build#4633]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

[conda-build](https://github.com/conda/conda-build)/[docs](https://github.com/conda/conda-build/tree/main/docs)/[source](https://github.com/conda/conda-build/tree/main/docs/source)/[resources](https://github.com/conda/conda-build/tree/main/docs/source/resources)/package-spec.rst should mention the ".conda" format. I think we have better documentation in the main conda documentation? that we could link to, replacing at least part of this page.

We recently updated the documentation about how to configure conda-build to produce .conda by default.

**Comment by ryanskeith** [comment]
I would like to work on this.
