### ISSUE TITLE
conda-build 3.23 needs (conda.auxlib) only present in newer conda (>4.10.3, at least), but still only requires conda>=4.5

### ISSUE THREAD

**Issue by ConceptualWempa** [conda/conda-build#4634]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

after installing conda-build==3.23 in an environment with conda pinned to 4.10.3, following error when running 'conda build':

> Traceback (most recent call last):
>   File "C:\ProgramData\Miniconda\Scripts\conda-build-script.py", line 6, in <module>
>     from conda_build.cli.main_build import main
>   File "C:\ProgramData\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 12, in <module>
>     from conda.auxlib.ish import dals
> ModuleNotFoundError: No module named 'conda.auxlib'

the installation should have upgraded conda (or, in this case, since conda was pinned, held back conda-build to 3.22), but didn't because conda-build==3.23 requirements still list "conda >=4.5"

**Comment by kenodegard** [comment]
@ConceptualWempa thanks for reporting, a new build is in the works

**Comment by jezdez** [comment]
Closing this as this has been fixed here and in the feedstocks.
