### ISSUE TITLE
Remove Conda less than 4.13 codes and versions in conda-build (conda-interface.py)

### ISSUE THREAD

**Issue by sven6002** [conda/conda-build#4641]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

`conda_43 = parse_version(CONDA_VERSION) >= parse_version("4.3.0a0")
conda_44 = parse_version(CONDA_VERSION) >= parse_version("4.4.0a0")
conda_45 = parse_version(CONDA_VERSION) >= parse_version("4.5.0a0")
conda_46 = parse_version(CONDA_VERSION) >= parse_version("4.6.0a0")
conda_47 = parse_version(CONDA_VERSION) >= parse_version("4.7.0a0")
conda_48 = parse_version(CONDA_VERSION) >= parse_version("4.8.0a0")
conda_411 = parse_version(CONDA_VERSION) >= parse_version("4.11.0a0")`

are older version which is not supported anymore.. we will need add any version of conda above 4.13 and removes these codes from the `code_interface.py`

### Why is this needed?

Supporting new version of conda across the board

### What should happen?

reformatting of codes and versions

**Comment by dholth** [comment]
I also thought this was pretty weird. In theory code that requires conda_45 or greater would say `if: conda_45 (do something)` but it's strange.

**Comment by dholth** [comment]
Edit recipe/meta.yaml to require conda >=4.13, set all those to True to be paranoid about API compatibility, and remove all checks for if conda < 4.13 to remove the “what do we do if conda is older than that” cases.

Find code that checks these and delete the if/else, keeping only the if True: case.

```python
    if conda_45:
        from conda.api import SubdirData
        return bool(SubdirData.query_all(spec, channels=urls, subdirs=(subdir, "noarch")))
    else:
        index, _, _ = get_build_index(subdir=subdir, bldpkgs_dir=metadata.config.bldpkgs_dir,
                                      output_folder=metadata.config.output_folder, channel_urls=urls,
                                      debug=metadata.config.debug, verbose=metadata.config.verbose,
                                      locking=metadata.config.locking, timeout=metadata.config.timeout,
                                      clear_cache=True)
        return any(spec.match(prec) for prec in index.values())
```

**Comment by sven6002** [comment]
Now that will entail reformatting of the code as well.. not just removing the older version code..

**Comment by dholth** [comment]
It would be OK to start with updating meta.yaml and setting all of the old conda_## to True, and only later change the if: statements.
