### ISSUE TITLE
Re-Evaluating `test.yml` file to remove old installations

### ISSUE THREAD

**Issue by sven6002** [conda/conda-build#4646]
### What is the idea?

Re-evaluate `test.yml` to remove older `setup` steps/versions.

Adding test summary reports as artifact (Using Allure-Multi report) 

### Why is this needed?

Updating the source code to support newer version of Operating systems and Conda

### What should happen?

The run should increase performance and reduce time of execution. 

```[tasklist]
- [x] https://github.com/conda/conda-build/pull/4621
- [x] https://github.com/conda/conda-build/pull/4648
```

**Comment by kenodegard** [comment]
The `test.yml` has been aggressively refreshed (updated Python matrix, updated conda matrix, standardized all setups to use `setup-miniconda`), so this is completed.
