### ISSUE TITLE
conda build failed to find conda-bld/linux-64

### ISSUE THREAD

**Issue by mpesavento** [conda/conda-build#466]
In trying to build our in-house package on ubuntu 14.04, `conda build .` fails:
    $ conda build .
Removing old build directory
Removing old work directory
BUILD START: 3scan-shared-0.0.0-py_0
Fetching package metadata: .......Error: Could not find URL: file:///home/mpesavento/anaconda3/conda-bld/linux-64/

This was fixed by manually creating the linux-64/ directory and running `conda index .` inside it to build the empty repodata.json, repodata.json.bz2, and .index.json files.
The next run of `conda build .` worked.

This seems like this check for an existing directory in the build for the distro should be included as a check in conda build. It is likely a holdover from updating conda from 1.2 to 1.4.

**Comment by asmeurer** [comment]
I can't reproduce this. conda index should be called automatically by conda build. Do you have the latest version of conda build (`conda update conda-build`)?

**Comment by mpesavento** [comment]
Yes, using conda-build 1.14.1 with py34_0. It seems that there might have been a collision as a result of the update in conda and/or conda-build, so difficult to reproduce. 

The only build architecture that was initially present was the noarch/ folder, which has the repodata* files populated with the necessary build info for our package. After calling `conda build .` the repodata* files in linux-64 are still unpopulated with package requirements.
If we are building a package with no specific architecture requirements on linux-64, I'm unclear on why conda-build would still need the build directory for linux-64 and not populate it.

**Comment by mpesavento** [comment]
Update: Similar error on a Macbook Pro, running OS10.9.5.
This just happened again with osx-64. We were building a totally different package on a different computer, using conda-build 1.16.0 on python 3.4.3, using conda 3.16.0.
When we ran `conda build .`, it failed because it could not find the URL file://<anaconda_home>/conda-bld/osx-64. When we manually created the directory and populated it with a manual call to `conda index .`, the build succeeded. 
Again, this seems like it is an error in conda-build for noarch packages. In the meta.yaml file, under "build:" we are setting "noarch_python: True". It is unclear why conda-build requires a built index in the host computer's architecture directory, when the package is 'noarch'.

**Comment by meawoppl** [comment]
I think this is from making noarch packages, the indexing fails because the bit-platform directory dosen't exist where it expects it to be made earlier.

**Comment by fallen** [comment]
Here is an example of the fail: https://travis-ci.org/fallen/artiq/builds/77121609
This is from a fresh miniconda install since each time travis spawns a clean VM

**Comment by meawoppl** [comment]
To calrify, this is an issue that only affects people building a noarch package without ever having built a package for their platform first.

**Comment by fallen** [comment]
Indeed.

**Comment by meawoppl** [comment]
The workaround I currently use is:
mkdir [conda root]/conda-bld/linux-64
conda index [conda root]/conda-bld/linux-64

Or replacing with your platform (osx-64 etc)

**Comment by sbourdeauducq** [comment]
Can you please fix this, and maybe have a look into the other 247 open issues just for conda-build? It's pretty baffling how buggy conda is.

**Comment by meawoppl** [comment]
This problem arises only when you first build noarch conda packages.  The support of these packages remains second class in my option, despite the fact that they are capable of wrapping pure-python packages simply in a cross platform fashion.  

The fix needed is to have the install of conda-build create expected folders and indices at time of installation if they do not exist.  If you do not, these locations must be checked for existence/validity/integrity each time, and are prone to other flavors of dumb.

**Comment by msarahan** [comment]
I think https://github.com/conda/conda-build/pull/798 fixes this.  Please let us know if this doesn't fix this issue.

**Comment by sbourdeauducq** [comment]
> The support of these packages remains second class in my option

So you recommend that a developer installs Windows, Linux and OSX VMs, possibly more for proper 32/64 bit support, when packaging a simple and pure Python library?

**Comment by msarahan** [comment]
I don't think he meant that.  Rather, he was pointing out that Conda does not currently handle noarch packaging well, and that for pure python, it should be dead simple.  We recognize that, and we're working to improve it.  Unfortunately, there's only so much time in a day.

**Comment by meawoppl** [comment]
@sbourdeauducq There are a bunch of small issues with "noarch" packages at present, which individually are somewhat annoying but in ensemble make it pretty obnoxious.  I can get more concrete on this if desired, but searching conda-build for noarch issues will give a flavor.

**Comment by sbourdeauducq** [comment]
You are making my point.
