### ISSUE TITLE
Adding Py3.7 to PyArrow / Arrow-cpp Conda-forge Build is disabling Py3.11 builds

### ISSUE THREAD

**Issue by rxm7706** [conda/conda-build#4666]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

w.r.t to https://github.com/conda-forge/arrow-cpp-feedstock/pull/896

When Python 3.7 was added to conda-build-config, existing python 3.11 got disabled .

        So the problem here is that despite https://github.com/conda-forge/arrow-cpp-feedstock/pull/896/commits/3d7347341f88c55021541e43289b5684dc9add53 being purely additive (in terms of config), it somehow disables the builds for py311:
```
anaconda upload \
    /home/conda/feedstock_root/build_artifacts/linux-64/apache-arrow-proc-4.0.0-cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/libarrow-10.0.1-h9ff0032_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/arrow-cpp-10.0.1-h3e2b116_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/arrow-cpp-proc-4.0.0-cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-10.0.1-py37he8182db_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-10.0.1-py310ha7322a8_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-10.0.1-py39h4d4a1a0_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-10.0.1-py38h1fd4ed9_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-tests-10.0.1-py37h82fcdeb_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-tests-10.0.1-py310h50e40b8_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-tests-10.0.1-py39h947458c_0_cuda.conda \
    /home/conda/feedstock_root/build_artifacts/linux-64/pyarrow-tests-10.0.1-py38hbf57a63_0_cuda.conda
anaconda_upload is not set.  Not uploading wheels: []
```

This has nothing to do with this feedstock, but is a problem of `conda-build` it seems. FWIW, I've tried the following patch to cbc, and nothing changes (the rerender is already correct):
```diff
diff --git a/recipe/conda_build_config.yaml b/recipe/conda_build_config.yaml
index cd4b5d8..ed8457f 100644
--- a/recipe/conda_build_config.yaml
+++ b/recipe/conda_build_config.yaml
@@ -5,13 +5,16 @@ python:
   - 3.8.* *_cpython
   - 3.9.* *_cpython
   - 3.10.* *_cpython
+  - 3.11.* *_cpython
 python_impl:
   - cpython           # [not (osx and arm64)]
   - cpython
   - cpython
   - cpython
+  - cpython
 numpy:
   - 1.20              # [not (osx and arm64)]
   - 1.20
   - 1.20
   - 1.21
+  - 1.23
```

As it stands, someone can fix what's causing the missing py311 builds (not me), or this PR is dead.

_Originally posted by @h-vetinari in https://github.com/conda-forge/arrow-cpp-feedstock/issues/896#issuecomment-1336373244_

**Comment by mbargull** [comment]
This is no `conda-build` issue.
See https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7

**Comment by mbargull** [comment]
Ah sorry, missed a detail there.

**Comment by mbargull** [comment]
Values from the recipe's `conda_build_config.yaml` take precedence over those from other config files.
Note they are not additive but replace higher priority ones.
