### ISSUE TITLE
Honor repository .gitignore contents when packaging

### ISSUE THREAD

**Issue by scdub** [conda/conda-build#4680]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

When working on a recipe that is part of a Git repository, it would be nice to be able to have the build process know to ignore files that are already ignored in the repository. Specifically, I am often evaluating contents of files in vim, which in turn generates files like `meta.yaml.swp` which are ignored at the repository level. However, `conda build` will see these files as valid content to be included in the `info\recipe` output.

### Why is this needed?

I mention this as a "nice to have" because it would be a minor improvement, but its cost should be evaluated since typically the impact of these files is minimal. There are cases where the IDE / editor specific files may include personal information that should be excluded, and the `.gitignore` is a widely practiced approach to avoiding committing files. Probably this would make sense as a flag or setting to modify behavior, I would argue it would make sense to be on by default by there may be counterarguments or use-cases where that wouldn't make sense and would be considered a breaking change.

### What should happen?

`.gitignore` filtered files don't show up in the recipe output.

### Additional Context

I can work on a PR if this is considered useful work, wanted to start a discussion before proceeding.

**Comment by travishathaway** [comment]
Hi @scdub,

Thanks for this feature request. For this specific feature, I would like to pursue the more conservative approach of making it an opt-in feature that is turned on or off in the `meta.yaml` file for the recipe (something like `use_gitignore: true` at the top level).

You are welcome to beginning working on a prototype if you like. I will share this with my colleagues to see what their thoughts are too and encourage them to respond on this issue.

**Comment by wolfv** [comment]
That seems like a super niche issue since most of the time you are running either `pip install` or some sort of `make install` to copy files into the prefix that has nothing to do with a git repository. 

Additionally, files that are `gitignore'd` should also not be part of the repository in the first place. 

I would be curious to hear more about how the build process works for this particular package where this is a problem.

**Comment by scdub** [comment]
@travishathaway The more conservative approach makes sense, though ideally it'd be something that could be propagated across recipes. In our case we have a single repo similarly laid out to https://github.com/ContinuumIO/anaconda-recipes and it'd be nice to have this set once instead of per-recipe.

@wolfv Right, in the case of the contents of the `SRC_DIR` this is typically handled by the process of creating the package artifacts. However, the contents of `RECIPE_DIR` are also inserted into the build within the `info/recipe` directory, and any files will be included in the output builds. Because all files from `RECIPE_DIR` are included, it can include any extra files independently if they are used in the recipe output. If you're using an external builder or CI then this isn't an issue because the recipe itself has to be synced before deployment. But if you're building locally or just testing something, they end up in the output package.
