### ISSUE TITLE
[DOC] Add `BUILD_PREFIX`

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#4682]
Currently `BUILD_PREFIX` is not documented (though already relied on heavily). Would be good to add it to [this environment variable table]( https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html ) and possibly other places where `PREFIX` or cross-compiling are referenced.

**Comment by marcelotrevisani** [comment]
Related to https://github.com/conda/conda-build/issues/3700#issue-488836798 that was closed

**Comment by jakirkham** [comment]
Actually this was done in PR ( https://github.com/conda/conda-build/pull/5065 )
