### ISSUE TITLE
SPIKE: Validity of the Free channel for either `http://repo.anaconda.com/pkgs/free/`deprecation/support

### ISSUE THREAD

**Issue by sven6002** [conda/conda-build#4687]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

SPIKE: Validity of the Free channel for either `http://repo.anaconda.com/pkgs/free/`deprecation/support

This is to find a reason to keep the free package channels. as the versions that is in the system is very old. 
these are the currently packages that are available on the channel 
![image (1)](https://user-images.githubusercontent.com/110486050/210402752-9151b019-7827-4fe1-a294-31554faa6c97.png)

### Why is this needed?

This spike to remove or re-use these test cases that test platform converts.. in `test-api-convert.py` test cases..  in `conda-build`

**Comment by travishathaway** [comment]
@sven6002, I think we just need to update the package versions to a later version of Python. I looked at the two tests in [test_api_convert.py](https://github.com/conda/conda-build/blob/main/tests/test_api_convert.py) which reference these older Python packages and they both look valid.

So, I would personally just update it to the most recent version of Python and then mark these as integration tests.
