### ISSUE TITLE
Error Code: conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'python=None'}

### ISSUE THREAD

**Issue by gregorywaynepower** [conda/conda-build#4688]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When trying follow the instructions for [Building a Simple Package using conda skeleton](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html#building-a-simple-package-with-conda-skeleton-pypi). I found that I get the error code.

`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'python=None'}`

What resolved this problem was that I had nothing under the `default_python:` in my `.condarc` file.

### Conda Info

```shell
active environment : pypi_build_test
    active env location : C:\Users\gpower\Anaconda3\envs\pypi_build_test
            shell level : 6
       user config file : C:\Users\gpower\.condarc
 populated config files : C:\Users\gpower\.condarc
          conda version : 22.11.1
    conda-build version : 3.23.3
         python version : 3.9.12.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\gpower\Anaconda3  (writable)
      conda av data dir : C:\Users\gpower\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\gpower\Anaconda3\pkgs
                          C:\Users\gpower\.conda\pkgs
                          C:\Users\gpower\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\gpower\Anaconda3\envs
                          C:\Users\gpower\.conda\envs
                          C:\Users\gpower\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : True
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\gpower\.condarc <==
channels:
  - defaults
  - conda-forge
```

**Comment by travishathaway** [comment]
Hi @gregorywaynepower,

Thank you for you bug submission. We are currently debating whether to deprecate `conda skeleton` entirely and instead encouraging users to use the [Grayskull project](https://github.com/conda-incubator/grayskull).

I highly encourage you to check out that project and cannot promise that any bug involving `conda skeleton` will be addressed anytime soon.

Again, thank you for this submission, and happy package building! 📦 😄

**Comment by gregorywaynepower** [comment]
I thought that the issue that I ran into was more of an issue of me not understanding some nuance in conda skeleton.

Does grayskull support redefining dependencies for PyPi modules? This may be a very niche issue: I ran into a problem with a package not having the dependencies properly set up on PyPi by a module maintainer.
