### ISSUE TITLE
Set up build tools team under the conda governance policy

### ISSUE THREAD

**Issue by jezdez** [conda/conda-build#4698]
We've followed a similar strategy recently with the [constructor](https://github.com/conda/constructor) project (plus [conda-standalone](https://github.com/conda/conda-standalone), [conda-pack](https://github.com/conda/conda-pack), [menuinst](https://github.com/conda/menuinst)). This led to an increase of maintenance velocity, because expert stakeholders outside of the conda maintainer team were enabled to contribute directly to the bootstrapping/installer story of conda.

conda-build is another pillar in the conda ecosystem that would benefit from more expert practitioners to more actively participate in the maintenance. There needs to be a balance struck between required maintenance ("keeping the lights on") and enabling new features ("building new shiny things").

The people I suggest adding to this team:

| User | Invited | Added | Matrix (#conda-build-tools:matrix.org) |
|------|---------|-------|--------|
| @chenghlee | | x | x |
| @beeankha | | x | x |
| @kenodegard | | x | x |
| @dholth | | x | x |
| @dbast | | x | x |
| @wolfv | | x | x |
| @msarahan |  | x | x |
| @isuruf |  | x | x |
| @jakirkham |  | x | x |
| @jaimergp | | x | x |
| @mbargull | | x | x |
| @jezdez | | x | x |
| @travishathaway | | x | x |
| @ryanskeith | | x | x |
| @JeanChristopheMorinPerso | | x | x |
| @callek | | x | x |
| @danpetry | | x | |
| @marcelotrevisani | | x | |

**Comment by jezdez** [comment]
Hey all, just an FYI, I've decided to commit to creating this team, so we can take the next steps for build-tools like conda-build.

From the list of people above in the issue description, I added a number already and have checked them off because I knew they had shown interest in the past.

Anyone else I haven't spoken to in person yet and would be happy to meet and talk about it.

If anyone has mistakenly made it to the list or changed their mind, I apologize and would be happy to fix it, just let me know.

**Comment by jezdez** [comment]
@ryanskeith @JeanChristopheMorinPerso I don't have your Matrix username to invite you to the public channel there, let me know if you want to join in the first place!

**Comment by jakirkham** [comment]
FWIW joined the Matrix room

**Comment by jezdez** [comment]
@jakirkham Would you also like to join the build tools team?

**Comment by jakirkham** [comment]
Yes please feel free to add me :)

**Comment by jezdez** [comment]
> Yes please feel free to add me :)

Invite sent, please check your emails from GitHub.

**Comment by danpetry** [comment]
Hi @jezdez @beeankha, I'd like to join the team too, please.

**Comment by jakirkham** [comment]
> > Yes please feel free to add me :)
> 
> Invite sent, please check your emails from GitHub.

Accepted 🙌  Thanks Jannis! 🙏

**Comment by jezdez** [comment]
@danpetry Invited!

**Comment by danpetry** [comment]
Thanks Jannis, accepted :)

**Comment by marcelotrevisani** [comment]
Can you add me as well please?

**Comment by jezdez** [comment]
> Can you add me as well please?

Sorry, I was out on PTO, yes!

**Comment by jezdez** [comment]
@marcelotrevisani Added to the team and invited to the public Matrix channel.

**Comment by jezdez** [comment]
Closing this as done 🥳

**Comment by jakirkham** [comment]
Thanks Jannis! 👏
