### ISSUE TITLE
rewriting symlinks

### ISSUE THREAD

**Issue by bkreider** [conda/conda-build#470]
I'm not sure what part of the conda-build code is doing this, but something is breaking the symlink and then later on the build breaks:

```
Making absolute symlink bin/nc -> netcat relative
...
...
  File "/Users/bkreider/src/conda-build/conda_build/build.py", line 157, in create_info_files
    files_with_prefix = sorted(have_prefix_files(files))
  File "/Users/bkreider/src/conda-build/conda_build/build.py", line 97, in have_prefix_files
    with open(path, 'rb') as fi:
IOError: [Errno 2] No such file or directory: '/opt/anaconda/envs/_build/bin/nc'
```

The workaround is to remove the symlink in build.sh and then actually copy the binary, because no matter how i symlink it, it says "making it relative" and then breaking the build process.

**Comment by asmeurer** [comment]
What is the before and after of the symlink?

**Comment by jakirkham** [comment]
I think I have just now seen something similar to this but on Mac only.
