### ISSUE TITLE
BUG: "ERROR [...] $PATH/lib/libgcc_s.so.1 found in build prefix" does not fail build

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#4703]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Builds on the ray feedstock in conda-forge have:
```
ERROR (ray-core,lib/python3.10/site-packages/ray/_raylet.so): $PATH/lib/libgcc_s.so.1 found in build prefix; should never happen
```
in the link check, but the build does not fail, so this flew under the radar and builds got published anyway.

Also happens with the latest available versions. The particular error is obviously linux-specific (there are no osx builds on that feedstock yet), but that doesn't mean ERROR-does-not-fail-the-build couldn't happen elsewhere too.

See https://github.com/conda-forge/ray-packages-feedstock/issues/88

**Comment by travishathaway** [comment]
Hi @h-vetinari,

Thanks for filing this bug report. We have acknowledged it and will organize it accordingly.

**Comment by h-vetinari** [comment]
> but that doesn't mean ERROR-does-not-fail-the-build couldn't happen elsewhere too.

Though the issue doesn't appear anymore in current ray builds, it is stil potentially dangerous and should not be closed without at least an analysis into what happened IMO.

Could someone reopen this issue please? CC @travishathaway @kenodegard
