### ISSUE TITLE
Flaky test `tests/test_api_build.py::test_overlinking_detection`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4708]
### What happened?

This test became pretty flaky once we merged in #4648:

- https://github.com/conda/conda-build/actions/runs/3877704137/jobs/6618833838
- https://github.com/conda/conda-build/actions/runs/3864273288/jobs/6618833174
- https://github.com/conda/conda-build/actions/runs/3877833892/jobs/6628232107

**Comment by kenodegard** [comment]
It looks like @sven6002 figured it out. The test needs to be run serially, there's some issue with using two different macOS SDK versions simultaneously.

https://github.com/conda/conda-build/actions/runs/3894069030/jobs/6647538228

**Comment by kenodegard** [comment]
Nope, it's still flaky: https://github.com/conda/conda-build/actions/runs/3895486083/jobs/6650863009

**Comment by sven6002** [comment]
Tht is literally the only test I'll debugging it and check
