### ISSUE TITLE
`numpy` version for conda-build is pointing to 1.16 on MacOS (M1 only)

### ISSUE THREAD

**Issue by beeankha** [conda/conda-build#4717]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When running `tests/test_variants.py::test_numpy_used_variable_looping`, the following error pops up:

```
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {'numpy=1.16'}
```

`conda-build/tests/test-recipes/variants/numpy_used/conda_build_config.yaml` contains the following:

```
[snippet]
numpy:
    - 1.16
    - 1.19
```

We should either upgrade the `numpy` version for M1 Mac systems or we need to skip this test for now; after the fix, we'll remove the `skipif` decorator.

### Additional Context

Release notes from `numpy`'s latest version for M1 support: https://numpy.org/doc/stable/release/1.21.4-notes.html

**Comment by skupr-anaconda** [comment]
@beeankha`numpy` should be **1.19** for `osx-arm64` platform, see https://github.com/AnacondaRecipes/aggregate/blob/b655086f99139bf951d7a59ce1315249d969c58d/conda_build_config.yaml#L158-L162
