### ISSUE TITLE
`setuptools 66` breaks conda-build

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-build#4733]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Setuptools has dropped `pkg_resources.parse_version` legacy behaviour, so it doesn't use `LegacyVersion` under the hood anymore. This results in some `InvalidVersion` errors in the test suite: https://github.com/conda/conda-build/pull/4732

See:
- https://github.com/pypa/setuptools/issues/2497
- https://github.com/pypa/packaging/pull/407

### Conda Info

```shell
See CI https://github.com/conda/conda-build/pull/4732
```

### Conda Config

```shell
See CI https://github.com/conda/conda-build/pull/4732
```

### Conda list

```shell
See CI https://github.com/conda/conda-build/pull/4732
```

### Additional Context

This affects `conda-smithy rerender` too: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3973

**Comment by jakirkham** [comment]
Wonder if we are able to drop `pkg_resources` altogether

**Comment by jaimergp** [comment]
xref https://github.com/conda/conda-build/pull/4443

**Comment by jakirkham** [comment]
Lol had forgotten that 🤦‍♂️

**Comment by ReimarBauer** [comment]
fixating setuptools helps meanwhile

setuptools ==65.5.1

https://github.com/conda-forge/mss-feedstock/pull/140/commits/6fab5f006afe3898b02e548f1b9e7dda4d9792d8

**Comment by ReimarBauer** [comment]
I have currently a follow up problem.
Usually we install our dependencies for developers by:
```
mamba install mss python --only-deps
````

The result is a broken environment. mamba is missing, conda faces inconsistancy.

We have to do now. 

```
mamba install mss python
conda remove mss --force
```

Maybe this will vanish also when I fixed our version string.

**Comment by jakirkham** [comment]
We need a repodata fix in `conda-forge` (`defaults` may need a similar fix)

Please see PR ( https://github.com/conda-forge/boa-feedstock/pull/61 ). In particular comment ( https://github.com/conda-forge/boa-feedstock/pull/61#issuecomment-1414231733 ). Help making this change would be welcome :)
