### ISSUE TITLE
Write and vote on CEP to specify the next-gen recipe format

### ISSUE THREAD

**Issue by jezdez** [conda/conda-build#4755]
This is currently called the “[boa format](https://github.com/conda-forge/conda-forge.github.io/issues/1612)” and has been discussed between @wolfv, @chenghlee, @jaimergp and me before in context of conda-build. There is also lots of prior discussion to consider (e.g. in the ticket mentioned above), to make sure the work on boa is appropriately ported.

It would be excellent to get started with the specification process (via a CEP) to formalize the format as a foundation for implementing it in conda-build directly.

**Comment by jezdez** [comment]
https://github.com/conda-incubator/ceps/pull/54 is that CEP and Wolf has been working on it

**Comment by wolfv** [comment]
I guess this can be closed! 🚀 Currently writing the blog post about the ongoing conda-forge integration of the new recipe format :)
