### ISSUE TITLE
DistributionNotFound Error: The 'tomltqdm’ distribution was not found

### ISSUE THREAD

**Issue by divastar** [conda/conda-build#4758]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am working on offline centos7 machine. I run conda index command in order to index the packages in my folder after installing conda-build then I got this requirement error
For tomltqdm which cannot be found on the net
```
File "/home/k/mambaforge/lib/python3.10/site-packages/pkgresources/ init .py• line 501, in _build master
ws. require ( requires ) - - '
File "/home/k/mambaforge/lib/python3.10/site-packages/pkgresources/ init .py• tine 909, in require needed= self.resolve(parse requirements( requirements)) - - •
File • /home/k /mambaforge/lib/python3. 10/site-packages/pkg resources/ init .py•. line 795, in resolve raise DistributionNotFound(req, requirers) - - -
pkg_resources.DistributionNotFound: The 'tomltqdm’ distribution was not found and is required by conda
```

### Conda Info

```shell
active environment : : base 3

active env location : : /home/k/mambaforge

shell level : 1
 
user config file : /home/k/.condarc

populated config files : : /home/k/mambaforge/.condarc

conda version : 22.9.8

conda-build version : 3.23. +34.ga449148.dirty


python version : 3.10.8.final.0
: 3.18.8.final.0
virtual packages : __linux=3.10.8= 0
glibc=2. 17=0
unix=8=8
_archspec=l=x86_64

base environment : /home/k/mambaforge (writable)

conda av data dir : /home/k/mambaforge/ete/conda

conda av metadata url : None

channel URLs : https://conda.anaconda.org/conda-forge/linux-64
https://conda.anaconda.org/conda-forge/noarch


package cache : /home/aiuser/mambaforge/pkgs

envs directories :  /home/k /. contfa/ p kgs

platform linux-64 .

user-agent conda/22.9.0 requests/2.28.1 CPython/3.18.8 Linux/3.18.1

UID:GID 1808:1989

netrc file None

offline mode False
```

### Conda Config

```shell
/home/k/mambaforge/.condarc <==
channels:
   - conda-forge
```

### Additional Context

![image](https://user-images.githubusercontent.com/50579056/215135645-8f3d3eb3-9061-4bb9-a2a1-b585704960f3.png)
![image](https://user-images.githubusercontent.com/50579056/215135920-21abdb1b-5422-4411-82d9-40d08a0b64bf.png)
![image](https://user-images.githubusercontent.com/50579056/215136130-a9645f0a-74a3-4ff3-9785-27c7b27ef1ac.png)

**Comment by divastar** [comment]
yes right.
I cloned the official repo
and installed conda-build with:
python setup.py install --single-version-externally-managed --record=record.txt

ls -alh .     gives me :

![conda_index](https://user-images.githubusercontent.com/50579056/216982447-3497df61-c7fd-4762-9b59-71e2923abefa.jpg)
Thank you

**Comment by divastar** [comment]
yes I will try. thank you.
Thant is the exact error: pkg_resources.DistributionNotFound: The 'tomltqdm’ distribution was not found and is required by conda

**Comment by divastar** [comment]
Hi [jaimergp](https://github.com/jaimergp),
Thank you for your response . I removed this file. But this error still pops
I get this error in any folder in vertual env as weel as in base when I use conda index command.

**Comment by divastar** [comment]
the issue is still reproducible: I am working on offline centos7 machine. I run conda index command in order to index the packages in my folder after installing conda-build then I got this requirement error
For tomltqdm which cannot be found on the net

**Comment by jaimergp** [comment]
That `tomltqdm` string must be coming from somewhere:

- It might be present verbatim in a file somewhere. Can you `grep` recursively on your conda installation, and/or the location you are indexing, to see if it's mentioned in a file we should be aware of?
- Maybe it's a composition of two adjacent strings, `toml` and `tqdm` (given how close they are in alphabetic sort). Can you grep again, but this time with a regex accounting for a newline or some separator in between the two words?

Thanks!

**Comment by divastar** [comment]
Hi [jaimergp](https://github.com/jaimergp),
thank you for your response.
I run both grep -r "tomltqdm" .
and grep -r "toml.*tqdm" .
and didn't get any results

Thank you

**Comment by jaimergp** [comment]
At this point all I can offer is to get in a call and see where this is coming from, sorry.

You can book a 30-min slot here: https://calendly.com/jaimergp-quansight/30-min-call?month=2023-04

**Comment by divastar** [comment]
Hi, Do we have a meeting now?
Thank you

**Comment by jaimergp** [comment]
I am waiting at https://meet.google.com/pmd-rszf-rzt. Link is also in the calendar invite.

**Comment by divastar** [comment]
Ok one moment
