### ISSUE TITLE
Retrieve project version via setuptools_scm

### ISSUE THREAD

**Issue by wvreeven** [conda/conda-build#4774]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

As is the case with the `load_setup_py_data`, the function `load_file_data` should be able to retrieve the version of the project via setuptools_scm.

### Why is this needed?

In pyproject.toml we rely on setuptools_scm to retrieve the version of the project. I have tried to use the new `load_file_data` function to load our project.toml file but Jinja doesn't retrieve the version via that file. We have followed the instructions [here](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) and [here](https://github.com/pypa/setuptools_scm) to set up project.toml but whatever I try, `load_file_data` returns the literal string as defined in `pyproject.toml` and doesn't call setuptools_scm to get the project version.

### What should happen?

It should be possible to use the directive `{% set data= load_file_data() %}` to retrieve the dynamically determined project version via setuptools_scm.

**Comment by dholth** [comment]
Some recipes use `version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}` in `meta.yaml`; does this work for your projects?

**Comment by wvreeven** [comment]
Thanks for the suggestion. It turns out that those GIT variables give a different version than setuptools_scm. Using the GIT variables in one of my projects, I get `v0.5.0+100_g32547c3` while setuptools_scm gives `0.5.1.dev100+g32547c3.d20230216`. It is the latter version that we use with all our projects.

**Comment by tomrutter** [comment]
Would it work to allow conda build to pick up version information from the wheel or installed package after the build.sh scripts have run pip install?

**Comment by wvreeven** [comment]
We don't use build.sh scripts nor do we run pip install.

**Comment by wvreeven** [comment]
Is there any update for this request?
