### ISSUE TITLE
ENH: Allow specifying an alternative location for conda_root/conda-bld 

### ISSUE THREAD

**Issue by mariusvniekerk** [conda/conda-build#48]
If we can pass an argument to conda build allowing an override to conda/conda-bld, then we should be able to have concurrent builds happen without the lock files getting in the way, and without needing a bunch of miniconda installs.

**Comment by msarahan** [comment]
Fixed by conda-build 2.0.  Closing.  Each build has its own separate build folder by default.  You can also specify root folders where these build folders live with the ``--croot`` CLI argument.
