### ISSUE TITLE
Make Git LFS pulls optional - disabled by default.

### ISSUE THREAD

**Issue by cwharris** [conda/conda-build#4809]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Provide the Git LFS support implemented in #4318 as an opt-in feature _only_.

### Why is this needed?

Git LFS support was implemented in #4318, forcing all LFS users to pull all content during each build. This can have negative monetary implications :money_with_wings: for users utilizing LFS in their repositories.

### What should happen?

Add an option to `meta.yaml` which allows users to explicitly enable or disable Git LFS support, defaulting to disabled if the option is not present.

### Additional Context

https://github.com/conda/conda-build/pull/4318#issuecomment-1468637969

**Comment by travishathaway** [comment]
Hi @cwharris,

Thanks for suggesting this feature request. We will leave this issue open for those wishing to discuss it. If the feature request gains enough traction and somebody submits a pull request, we will considering adding it to conda-build.
