### ISSUE TITLE
Which CDT package provides the `GL/glu.h` file?

### ISSUE THREAD

**Issue by capn-freako** [conda/conda-build#4811]
And is there a map listing the contents of the various CDT packages somewhere?

Command line based way of getting at this information?

Thanks!

Is the following sufficient to claim that no CDT package includes the `glu.h` file?
Asked differently, is every file that is included in, at least, one CDT package mentioned somewhere within the `conda-forge/cdt-builds` repo.?

```
$ git clone https://github.com/conda-forge/cdt-builds.git
Cloning into 'cdt-builds'...
{snip}

$ pushd cdt-builds/

$ git grep 'glu\.h'

$
```

Oh, I think I just answered my own question:

```
$ git grep 'gl\.h'

$
```

I know that the `GL/gl.h` file _is_ provided by the `mesa-libgl-devel` package.  
So, then, `git grep ...`ing is _not_ a reliable way to determine whether a particular file is provided by a CDT package?  
**How _can_ I determine if a particular file is provided and by which CDT package?**

**Comment by travishathaway** [comment]
Seems like this issue can be closed now. Please re-open if necessary.
