### ISSUE TITLE
cph transmute tarbz -> conda and repodata_builds.json

### ISSUE THREAD

**Issue by barabo** [conda/conda-build#4824]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

When using conda build, I would like:

- [ ] the option to generate a `repodata_builds.json` that includes only the built packages (but otherwise this file could be used as a miniature `repodata.json` file).
- [ ] when transmuting a built tarbz file to a conda file, I would like the transmuted conda package also included in the `packages.conda` section of the `repodata_builds.json` file

### Why is this needed?

This would simplify my build process.  Currently I'm using conda build to build tarbz packages, transmuting them to conda packages, and (in a hacky way) inserting entries into my `repodata_builds.json` file in the `packages.conda` section.

### What should happen?

Perhaps something like: `conda build --repodata-builds --transmute` would do all the things described in the idea section above.

### Additional Context

This is a nice-to-have feature.  I'm currently able to work with my existing setup, even though it's a bit hacky.

**Comment by dholth** [comment]
Do you think it is too slow to re-index the local channel after conda-build or (a separate project) cph transmute?

**Comment by dholth** [comment]
We do have a nice conda-index API that separates out the "os.listdir" step; the class is designed to be overridden so that the list of files to be indexed can be controlled.

**Comment by barabo** [comment]
I'll look into using `conda-index` on the local build output dir (or on the individual files).  I'm not sure `conda-index` is already included in my build worker, so there may be some wrinkles getting it deployed wherever we're building - but if it works that may be the way we go.

**Comment by dholth** [comment]
Not planned.
