### ISSUE TITLE
Include virtual packages in hash contents

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#4861]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Quoting from https://github.com/conda/conda-build/pull/4606:

> Noarch packages that use virtual packages have the virtual packages added to the hash contents of the package. This facilitates the building of noarch packages multiple times for different platforms with platform specific dependencies.
> 
> If we build `noarch` packages with diverging run dependencies for different platforms, the hash in the build string stayed the same prior to this PR, i.e., the built variants got the exact same build strings and thus package file names didn't change. With this PR we can build different variants for, e.g., `__linux`/`__osx`/`__win`, and get distinguished, non-clashing package file names.

### Why is this needed?

To move https://github.com/conda/conda-build/pull/4606 & https://github.com/conda-forge/conda-forge.github.io/pull/1839 & and much work based on that in conda-forge forward.

### What should happen?

Review & merge https://github.com/conda/conda-build/pull/4606

### Additional Context

More noarch packages = less unnecessary builds = less unnecessary downloads = less resources waste 🌍 = savings 💸

**Comment by jaimergp** [comment]
These are the code review comments (in the conda-forge docs PR) that triggered the need for this issue:

- https://github.com/conda-forge/conda-forge.github.io/pull/1839#discussion_r1004545742
- https://github.com/conda-forge/conda-forge.github.io/pull/1839#discussion_r1008679066
