### ISSUE TITLE
Locations for shared objects in cross-platform packages

### ISSUE THREAD

**Issue by ovz** [conda/conda-build#487]
Hi,

I'm building a package and distributes compiled shared objects for Windows (.dll) and Linux (.so). Where should my conda recipe install these shared objects?

My shared objects are 
- C++ libraries
- Boost.Python C++ libraries, thus loadable by import statement in Python
- Binary Python modules produced by nuitka. 

I need to make all the shared objects automatically discoverable by both C++ and Python clients. 

After running the commands below I see that on Windows I can place all my shared objects to the root of the repository, 'C:\Anaconda\Win64\envs\sys_path_test'. It is a part of both PATH and sys.path. On Linux, on other hand, I only have /home/ovz/miniconda/envs/sys_path_test/bin in my $PATH and it is not clear
- Where should my conda recipe deploy Shared Objects loadable from Python?
- How do I make sure Python Shared Objects can locate C++ ones? 
# Windows

<pre>
C:\Users\BuildMaster>conda --version
conda 3.14.1

C:\Users\BuildMaster>conda create -n sys_path_test
Error: too few arguments, must supply command line package specs or --file

You can specify one or more default packages to install when creating
an environment.  Doing so allows you to call conda create without
explicitly providing any package names.

To set the provided packages, call conda config like this:

    conda config --add create_default_packages PACKAGE_NAME

C:\Users\BuildMaster>conda create -n sys_path_test python
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment C:\Anaconda\Win64\envs\sys_path_tes
t:

The following NEW packages will be INSTALLED:

    pip:        7.1.0-py27_0
    python:     2.7.10-0
    setuptools: 18.0.1-py27_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate sys_path_test
#

C:\Users\BuildMaster>activate sys_path_test
Activating environment "sys_path_test"...

[sys_path_test] C:\Users\BuildMaster>python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 16:44:52) [MSC
v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import sys
>>> sys.path
['', 'C:\\Anaconda\\Win64\\envs\\sys_path_test\\python27.zip', 'C:\\Anaconda\\Wi
n64\\envs\\sys_path_test\\DLLs', 'C:\\Anaconda\\Win64\\envs\\sys_path_test\\lib'
, 'C:\\Anaconda\\Win64\\envs\\sys_path_test\\lib\\plat-win', 'C:\\Anaconda\\Win6
4\\envs\\sys_path_test\\lib\\lib-tk', 'C:\\Anaconda\\Win64\\envs\\sys_path_test'
, 'C:\\Anaconda\\Win64\\envs\\sys_path_test\\lib\\site-packages', 'C:\\Anaconda\
\Win64\\envs\\sys_path_test\\lib\\site-packages\\setuptools-18.0.1-py2.7.egg']
>>> quit()

[sys_path_test] C:\Users\BuildMaster>PATH
PATH=C:\Anaconda\Win64\envs\sys_path_test;C:\Anaconda\Win64\envs\sys_path_test\S
cripts;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Common Files\Intel\
Shared Libraries\redist\intel64\mpirt;C:\Program Files (x86)\Common Files\Intel\
Shared Libraries\redist\ia32\mpirt;C:\Program Files (x86)\Common Files\Intel\Sha
red Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Intel\
Shared Libraries\redist\ia32\compiler;C:\Windows\system32;C:\Windows;C:\Windows\
System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)
\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server
\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Too
lkit\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Git\cmd;C:\Program Fi
les (x86)\GitExtensions\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C
:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\
Web Platform Installer\;C:\Anaconda\Win64;C:\Anaconda\Win64\Scripts;C:\Program F
iles (x86)\CodeMeter\DevKit\bin\;C:\tools\sysinternals;C:\Program Files\kdiff3;C
:\Qt\5.4\msvc2013_64\bin;C:\spm\git\clones\SPM80_dll\MSBuild\x64\dll_debug
</pre>

# Linux

<pre>
ovz@host:~$ conda --version
conda 3.14.1
ovz@host:~$
ovz@host:~$ conda create -n sys_path_test python -y
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/ovz/miniconda/envs/sys_path_test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1
    pip:        7.1.0-py27_0
    python:     2.7.10-0
    readline:   6.2-2
    setuptools: 18.0.1-py27_0
    sqlite:     3.8.4.1-1
    system:     5.8-2
    tk:         8.5.18-0
    zlib:       1.2.8-0

Linking packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate sys_path_test
#
# To deactivate this environment, use:
# $ source deactivate
#
ovz@host:~$ source activate sys_path_test
discarding /home/ovz/miniconda/bin from PATH
prepending /home/ovz/miniconda/envs/sys_path_test/bin to PATH
(sys_path_test)ovz@host:~$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import sys
>>> sys.path
['', '/home/ovz/miniconda/envs/sys_path_test/lib/python27.zip', '/home/ovz/miniconda/envs/sys_path_test/lib/python2.7', '/home/ovz/miniconda/envs/sys_path_test/lib/python2.7/plat-linux2', '/home/ovz/miniconda/envs/sys_path_test/lib/python2.7/lib-tk', '/home/ovz/miniconda/envs/sys_path_test/lib/python2.7/lib-old', '/home/ovz/miniconda/envs/sys_path_test/lib/python2.7/lib-dynload', '/home/ovz/miniconda/envs/sys_path_test/lib/python2.7/site-packages', '/home/ovz/miniconda/envs/sys_path_test/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg']
>>> quit()
(sys_path_test)ovz@host:~$ echo $PATH
/home/ovz/miniconda/envs/sys_path_test/bin:/opt/intel/composer_xe_2015.2.164/bin/intel64:/opt/intel/composer_xe_2015.2.164/debugger/gdb/intel64_mic/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/intel/bin:/usr/local/salford/bin:/usr/local/Scripts:/usr/local/StatTransfer13

</pre>

**Comment by asmeurer** [comment]
On Windows, shared objects need to be on the PATH, but on Linux, the PATH is only used for looking up commands in the terminal.

**Comment by frol** [comment]
On Windows, you put "native" DLLs into `%PREFIX%\DDLs` folder, and "Unix-style" libraries into `%LIBRARY_LIB%` (which will expand into `%PREFIX%\Library\lib`).

On Linux and OS X, you put static (`.a`/`.la`) and shared (`.so`/`.dylib`) libraries into `$PREFIX/lib`.

However, conda activate will not propagate libraries folders into your command line on any platform! On Windows, I believe, conda python modifies `PATH` on start, so you can see that `DLLs` folder is in your `sys.paths`. On Linux and OS X, binaries are modified while conda build final stage so they use relative [`rpath`](https://en.wikipedia.org/wiki/Rpath) option.

**Comment by shadowwalkersb** [comment]
@ovz, thanks for pointing out a very critical issue!

> 1. Where should my conda recipe deploy Shared Objects loadable from Python?
> 2. How do I make sure Python Shared Objects can locate C++ ones?

@frol 's answer solves only the problem of finding the native binaries, (2). But, they are not importable by Python, if their location is not in `sys.path`. AFAIK, `$PREFIX/lib` is not in `sys.path` and I am not aware of any ways to add to `sys.path`. However, the binaries can be placed within the python modules, which also may be preferable, if the binaries are intended only for "private" use by python modules rather than being exposed in `$PREFIX/lib`. Then, they are importable. In this case, (2) becomes a problem, because conda sets `RPATH` to `$PREFIX/lib`. Correct me if I'm wrong, but even if `RPATH`s are set correctly during building, I think conda-build will override them. If I am wrong and conda-build doesn't override the `RPATH`s, it is still undesirable to have to jump through extra hoops. Especially, if `RPATH`s can be set in the recipe. Good news is, I think, we have [build/rpaths](https://conda.io/docs/building/meta-yaml.html#rpaths). Unfortunately, currently this works only for Linux. So, why not allow setting `RPATH`s for OSX as well? Or, maybe, just add `@loader_path/.` and `$ORIGIN/.` to `RPATH`s on OSX and Linux. Or, is there a better strategy that is possible and recommended for this use case?

**Comment by shadowwalkersb** [comment]
@msarahan , any input here? Or, someone else that can help, please?

**Comment by msarahan** [comment]
You can avoid conda-build changing RPATH with https://conda.io/docs/building/meta-yaml.html#binary-relocation

I'd certainly accept a PR to allow setting RPATH on OSX as well, but do not have time to implement this right now.

**Comment by shadowwalkersb** [comment]
Thanks, @msarahan !
