### ISSUE TITLE
Add type annotations to conda-build 

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#4879]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Type annotations/hints can make code more explicit, easier to understand and by using a static checker can be used to find potential bugs and errors. Support for type annotation has grown considerably in recent released of Python. Many popular library in the Python ecosystem have added type annotation in the last few years.

Adding type annotations to conda-build has a number of benefits including:
- Making the code base more approachable to new contributors.
- Making the API, functions and classes more explicit. 
- Finding bugs and errors by using a static type checker like `mypy`.

Types can be manually added to a code base gradually over time.  Another option is to use a a tool that automatically generates type annotations such as [MonkeyType](https://monkeytype.readthedocs.io/en/stable/index.html) or [PyAnnotate](https://github.com/dropbox/pyannotate). I ran the former to generate the type annotations in #4878.

**Comment by travishathaway** [comment]
Here's a link to a pull request containing my thoughts on this:

https://github.com/conda/conda-build/pull/4878#issuecomment-1543416104
