### ISSUE TITLE
Allow `pkg_format` to be configured via a command line option on `conda build`

### ISSUE THREAD

**Issue by travishathaway** [conda/conda-build#4890]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

If I want `conda build` to output the `.conda` file format, I current have to set the following in my `.condarc`:

```yaml
conda-build:
   pkg_format: 2
```

On top of that, I think this should be configurable with a command line option.

### What should happen?

I really don't like having to specify `pkg_format: 2` for the `.conda` file type in the `.condarc` file. I think it would make more sense to add something like `--pkg-format=conda` and have it default `--pkg-format=tar.bz2`.

**Comment by jakirkham** [comment]
Just bumped into this recently
