### ISSUE TITLE
Cannot Install packages on MacBook Air M1

### ISSUE THREAD

**Issue by peflanag** [conda/conda-build#4919]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi, I'm not a coder/bioinformatician and am self thought in command line for genomic sequence analysis. I was previously working on an intel iMac Pro and bought a MacBook Air M1 recently. I installed conda yesterday and treated an environment but when I go to install the package in the environment it doesn't work. I have read online about stuff relating to Ventura and M1 but I don't understand the solutions/work arounds and I am wondering is there a "dummies" guide available? Below is the error I keep getting when I try to instal any package in any library. It works on Ventura on an intel Mac so it makes me think the M1 chipset is the issue? The plan is to buy a Mac Studio too which will have an M2 chipset in it so will I have the same problem there? When I try to install the channels it says they're installed and moved to the top

I am running the latest conda 23.5.0

Cheers in advance!

<img width="777" alt="Screenshot 2023-06-23 at 09 21 37" src="https://github.com/conda/conda-build/assets/32863969/121563e6-39f1-4e3c-90dc-d040bc228e87">

### Conda Info

```shell
(base) {9:22}~ ➭ conda info

     active environment : base
    active env location : /Users/drflanman/miniconda3
            shell level : 1
       user config file : /Users/drflanman/.condarc
 populated config files : 
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.4=0
                          __unix=0=0
       base environment : /Users/drflanman/miniconda3  (writable)
      conda av data dir : /Users/drflanman/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/drflanman/miniconda3/pkgs
                          /Users/drflanman/.conda/pkgs
       envs directories : /Users/drflanman/miniconda3/envs
                          /Users/drflanman/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.5.0 requests/2.29.0 CPython/3.10.11 Darwin/22.5.0 OSX/13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False


(base) {9:22}~ ➭
```

### Conda Config

```shell
(base) {9:22}~ ➭ conda config --show-sources

(base) {9:23}~ ➭
```

### Conda list

```shell
(base) {9:23}~ ➭ conda list --show-channel-urls
# packages in environment at /Users/drflanman/miniconda3:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0          py310hca03da5_0    defaults
brotlipy                  0.7.0           py310h1a28f6b_1002    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
ca-certificates           2023.05.30           hca03da5_0    defaults
certifi                   2023.5.7        py310hca03da5_0    defaults
cffi                      1.15.1          py310h80987f9_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.5.0          py310hca03da5_0    defaults
conda-content-trust       0.1.3           py310hca03da5_0    defaults
conda-package-handling    2.1.0           py310hca03da5_0    defaults
conda-package-streaming   0.8.0           py310hca03da5_0    defaults
cryptography              39.0.1          py310h834c97f_2    defaults
idna                      3.4             py310hca03da5_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
libffi                    3.4.4                hca03da5_0    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   3.0.9                h1a28f6b_0    defaults
packaging                 23.0            py310hca03da5_0    defaults
pip                       23.0.1          py310hca03da5_0    defaults
pluggy                    1.0.0           py310hca03da5_1    defaults
pycosat                   0.6.4           py310h1a28f6b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0          py310hca03da5_0    defaults
pysocks                   1.7.1           py310hca03da5_0    defaults
python                    3.10.11              hb885b13_3    defaults
python.app                3               py310h1a28f6b_0    defaults
readline                  8.2                  h1a28f6b_0    defaults
requests                  2.29.0          py310hca03da5_0    defaults
ruamel.yaml               0.17.21         py310h1a28f6b_0    defaults
ruamel.yaml.clib          0.2.6           py310h1a28f6b_1    defaults
setuptools                65.6.3          py310hca03da5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
toolz                     0.12.0          py310hca03da5_0    defaults
tqdm                      4.65.0          py310h33ce5c2_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py310hca03da5_0    defaults
wheel                     0.38.4          py310hca03da5_0    defaults
xz                        5.4.2                h80987f9_0    defaults
zlib                      1.2.13               h5a0b063_0    defaults
zstandard                 0.19.0          py310h80987f9_0    defaults
(base) {9:24}~ ➭
```

**Comment by maddenp** [comment]
Hi @peflanag. I'm not a maintainer, just a user.

I think the issue is that there is no `osx-arm64` build of `kraken2` in the `bioconda` channel, as you can see here: https://anaconda.org/bioconda/kraken2 (note the `linux-64` and `osx-64` icons in the _Installers_ section, or in the filenames if you click the _Files_ tab on that page -- these are builds for Intel CPUs).

But if you do a search from anaconda.org for `kraken2`, you'll find https://anaconda.org/search?q=kraken2, and this build: https://anaconda.org/nanoporetech/kraken2, which is available for `osx-arm64`, which I think should work on your M1 system. So, you could replace `-c bioconda` with `-c nanoporetech`, but you might want to take a quick look at https://anaconda.org/nanoporetech and see if this is an organization you're willing to trust. (Due diligence and all -- I have no reason to think they're not trustworthy! But anyone, including me, can create a public channel on anaconda.org.)

I hope this helps. This probably isn't a `conda-build` bug, unless the maintainers of `conda-build` are also responsible for maintaining the `bioconda` channel, in which case maybe it could be considered a bug that's there's no `osx-arm64` package for this code.

Best wishes & good luck.

**Comment by peflanag** [comment]
Hi @maddenp and cheers for explaining that to me. I will look at the nanoporetech channel but I assume it's legit and belonging to ONT?

Anyway, I'm just wondering is M1 and M2 a known issue across programs? I would have assumed since the chips have been out a while that programs would have been updated. I only ask because I am purchasing a new MacStudio for work to replace an old intel iMac Pro. But if M1 and M2 are known issues I might have to rethink my game plan!

**Comment by peflanag** [comment]
Thanks again for your help, I tried with -c nanoporetech and got the following error. I guess I'll still have to continue googling and testing with other programs!

<img width="781" alt="Screenshot 2023-07-14 at 09 13 54" src="https://github.com/conda/conda-build/assets/32863969/40164620-9960-4dc7-a0c0-dc692c760f2f">

**Comment by maddenp** [comment]
I have an M2 Air and, starting from scratch, was able to create a `kraken2` environment without issue:
```
(base) ~ % conda create --yes --name kraken2 --channel nanoporetech kraken2

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/paul.madden/sw/conda/envs/kraken2

  added / updated specs:
    - kraken2


The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-arm64::ca-certificates-2023.5.7-hf0a4a13_0 
  gettext            conda-forge/osx-arm64::gettext-0.21.1-h0186832_0 
  kraken2            nanoporetech/osx-arm64::kraken2-2.1.2-pl5321hcb8d3e5_3 
  libcxx             conda-forge/osx-arm64::libcxx-16.0.6-h4653b0c_0 
  libiconv           conda-forge/osx-arm64::libiconv-1.17-he4db4b2_0 
  libidn2            conda-forge/osx-arm64::libidn2-2.3.4-h1a8c8d9_0 
  libunistring       conda-forge/osx-arm64::libunistring-0.9.10-h3422bc3_0 
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h53f4e23_5 
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-16.0.6-h1c12783_0 
  lz4-c              conda-forge/osx-arm64::lz4-c-1.9.4-hb7217d7_0 
  openssl            conda-forge/osx-arm64::openssl-3.1.1-h53f4e23_1 
  perl               conda-forge/osx-arm64::perl-5.32.1-3_hf2054a2_perl5 
  popt               conda-forge/osx-arm64::popt-1.16-h61edf1b_2002 
  rsync              conda-forge/osx-arm64::rsync-3.2.7-hcdef6ba_0 
  tar                conda-forge/osx-arm64::tar-1.34-h7cb298e_1 
  wget               conda-forge/osx-arm64::wget-1.20.3-h470526e_1 
  xxhash             conda-forge/osx-arm64::xxhash-0.8.0-h27ca646_3 
  zlib               conda-forge/osx-arm64::zlib-1.2.13-h53f4e23_5 
  zstd               conda-forge/osx-arm64::zstd-1.5.2-h4f39d0f_7 



Downloading and Extracting Packages

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate kraken2
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
If you already have an environment called `kraken2`, you can first remove it with `conda env remove -n kraken2`, or use a different `--name`. The command I used above creates an environment containing _only _ `kraken2` and its dependencies. You could then try to `conda install` other packages into that new envrionment and hopefully will not run into any conflicts.

I think that, since much of the conda package ecosystem is supported by volunteers, and because the Apple Silicon chips are fairly new (but you're right, they've been out for a while now), it will just take some time before people are able to rebuild all packages for the M1/M2 chips. The source code of the programs doesn't need to be changed, but they have to be recompiled on M1/M2 chips, which means you have to have that hardware / OS available to you. If you poke around the package ecosystem, you may find that programs available for Linux and OSX are not always available for Windows, for similar reasons .

**Comment by maddenp** [comment]
Hmm, I should maybe add that I'm starting from a Miniforge (https://github.com/conda-forge/miniforge) installation of conda, which is like Miniconda (https://docs.conda.io/en/latest/miniconda.html) but uses the `conda-forge` channel as the default source for packages. So, experience could be different with Miniconda (or Anaconda, or another conda distro). Unfortunately, I don't have time at the moment to install one of those to test, but you could fairly easily install a Miniforge and get `kraken2` they way I have, I think.
