### ISSUE TITLE
Pre-activate hook?

### ISSUE THREAD

**Issue by tpn** [conda/conda-build#50]
In order for R to be relocatable and to also work with our tcl/tk libs, TCL_CONFIG and TK_CONFIG environment variables need to be exported at runtime to point to the correct locations (which will be environment-dependent).

The only option now is to remember to alter your shell's startup scripts and manually export the necessary envvars.  That's not a good long-term solution.  (It took me forever to figure out that R needed those envvars set explicitly; we can't expect other users to know they need to be set.)

So, I think there's a need for a pre-activate.sh-type script that allows a package to customize an environment as part of 'activation'.  This would also entail having the root environment automatically run any pre-activate.sh scripts, which isn't possible with our current (simple) .bashrc alteration.

**Comment by bkreider** [comment]
I believe this is solved by conda-env, but maybe not documented well?  https://github.com/conda/conda-env/blob/develop/bin/activate#L78

**Comment by msarahan** [comment]
activate.d scripts can be used for this.  Closing.

https://conda.io/docs/using/envs.html#saved-environment-variables
