### ISSUE TITLE
`INCLUDE_PATH` and `LIBRARY_PATH` not set when building

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#509]
I wrote some recipes that relied on these environment variables and am now discovering that they have been removed. Is there a reason for this?

**Comment by groutr** [comment]
From the changelog
```
* removing LIBRARY_PATH and INCLUDE_PATH build environment variables on
  Unix, they where originally added in #228, but are causing problem for
  some people and are not really necessary
```

**Comment by ccordoba12** [comment]
@groutr, in what version were these varaibles removed?

**Comment by jakirkham** [comment]
Glad to see this was mentioned in the Changelog at least.

@ccordoba12, it appears this was version `1.14.0`.
@groutr, could you elaborate on what problem this was causing for people?

> They are equivalent to `$PREFIX/include` and `$PREFIX/lib` respectively.

I am aware that these can be easily produced, but it was a little surprising to see this change.

**Comment by jakirkham** [comment]
All I can find is this ( https://github.com/conda/conda-build/pull/228#issuecomment-103676097 ) by @ilanschnell stating that there was a problem.

**Comment by ilanschnell** [comment]
I don't remember the exact problem, but (as mentioned) we also want to keep the number of defined variables as small as possible, and those two are completely redundant.

**Comment by asmeurer** [comment]
You can set them manually in the build.sh. The removal came from an internal request from a customer. It had to do with some behavior of cmake that made setting these variables automatically undesirable http://www.cmake.org/pipermail/cmake/2014-September/058644.html.

In general, I think it's a bad idea for conda build to automatically set variables that change the way that build tools work, unless they are needed for them to work at all in the build prefix (like $PKG_CONFIG_PATH).

**Comment by jakirkham** [comment]
My concern here is less that it can be easily worked around or that it made sense.

Instead, my concern is that a feature that had been around for several months was unceremoniously removed with little record. For a breaking change like this, it would be greatly appreciated in the future to see a new pull request at a bare minimum with some mention of the reason.

**Comment by asmeurer** [comment]
We log all changes in the CHANGELOG. Beyond that, we don't really have any other channels that all changes go through. I agree we should have shared the reasoning behind the change in the original issue, though. I also agree that it would be better to push more changes through pull requests.

**Comment by jakirkham** [comment]
> We log all changes in the CHANGELOG.

Of course, and it is great that you are doing this.

> Beyond that, we don't really have any other channels that all changes go through.

`conda` is already a very powerful and functional tool; however, it still is evolving quite a bit and I am happy to see that continue. A more complex review process of changes would slow down development and, unless I am mistaken, I don't think any of us want this.

> I agree we should have shared the reasoning behind the change in the original issue, though. I also agree that it would be better to push more changes through pull requests.

Then I think we are on the same page.
