### ISSUE TITLE
Add support for `bdist_conda` in all environments

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#517]
It would be nice if this `setup.py` subcommand were available in every environment. This way one could build a package comfortably without having to switch to the `root` environment every time.

**Comment by asmeurer** [comment]
Unfortunately this would not be an easy change, as bdist_conda currently relies pretty heavily on the conda-build code, which itself relies on conda, which can only be installed into the root environment.

**Comment by jakirkham** [comment]
From what I have seen, I believe this is true. I had noticed this ( https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment ) and wondered if that change may still happen. If so, maybe this change would be easier after that change has occurred.
