### ISSUE TITLE
Incorrect library load paths due to rpath patcher run on symlinks

### ISSUE THREAD

**Issue by mbargull** [conda/conda-build#5179]
### What happened?

In `conda-build>=3.28.0`, https://github.com/conda/conda-build/pull/5040/commits/1dc24708cae103bd1c3913520df91bb53de17c87 replaced `.os_utils.pyldd.is_codefile`/`.os_utils.*.codefile_type` by direct calls to `.os_utils.*.codefile_class` which those functions wrapped.
For `is_codefile`/`codefile_type` the `skip_symlinks` parameter defaults to `True` whereas it is `False` for `codefile_class` which induced some unintended changes.
Notably, `.post.post_process_shared_lib` runs the rpath patcher on symlinks in `conda-build>=3.28`, which leads to invalid entries being set for the symlink targets in case the symlinks are located in different directories.

Case analysis at https://github.com/conda-forge/openmpi-feedstock/pull/142#issuecomment-1936503202 ff.
In that specific case, we have a `lib/<target>` and `lib/<subfolder>/<symlink> -> lib/<target>` for which `lib/<target>` gets rpath set to `$ORIGIN/..:$ORIGIN/.` instead of `$ORIGIN/..:$ORIGIN/.` if the symlink is processed after the actual target.
The issue was noticed because we ran into an bug with in `patchelf` which I could pinpoint to being introduced in https://github.com/NixOS/patchelf/pull/430/commits/42394e880bc5524122234fe2c2eaa043063ac581 (i.e., affecting `patchelf>=0.17.0`.
(Others have run into issues introduced with that change; see https://github.com/NixOS/patchelf/issues/446 ).

----
Test and patch incoming.

**Comment by h-vetinari** [comment]
We ran into an apparent rpath [problem](https://github.com/conda-forge/boost-feedstock/pull/189#issuecomment-1938176588) when building boost with conda-build 3.28, which went away with conda-build 3.27. I cannot guarantee that it's the same bug, but it sounds related, and it would be good to verify/test that #5181 also fixes that issue.

**Comment by mbargull** [comment]
@h-vetinari, hm.. `libboost` doesn't have these subfolder issues since it's all flat in `lib/`.
This might be another bug :/ ...
Let me try if I can somewhat quickly find which change might've caused that issue.

**Comment by mbargull** [comment]
> @h-vetinari, hm.. `libboost` doesn't have these subfolder issues since it's all flat in `lib/`. This might be another bug :/ ... Let me try if I can somewhat quickly find which change might've caused that issue.

For some reason this started to fail for me after the change from gh-5031 ...

**Comment by kenodegard** [comment]
Resolved in #5181, upcoming `conda-build 24.1.2` patch release will include the fix
