### ISSUE TITLE
 Make `.conda` the default format for future `conda-build` versions

### ISSUE THREAD

**Issue by mbargull** [conda/conda-build#5183]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

This is in the same vein as the suggestion for `rattler-build`: [Make .conda the default format for rattler-build](https://github.com/prefix-dev/rattler-build/issues/628)

Support for the `.conda` package format was introduced in `3.18.0` (2019-05-17) and has been the default format used at conda-forge since 2022-11-18:
- https://github.com/conda-forge/conda-forge.github.io/issues/1586
- https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/212

### Why is this needed?

`.conda` uses Zstandard instead of bzip2 for compression and also separates metadata from packages' files making it more efficient in terms of package sizes, package extraction times, and metadata extraction.

### What should happen?

We should consider marking a change of the default from the old `.tar.bz2` format to `.conda` for a future `conda-build` version.

My suggestion would be "next release"+2, i.e., `conda-build=24.7`, as the earliest; it would be sensible in my opinion to schedule this change for sometime in the later half of this year.
The change itself is probably not very controversial since we'd only change the default, but still continue to support `.tar.bz2`.
But we should give enough time/notice such that downstream tooling can be updated beforehand.

### Additional Context

[Make .conda the default format for rattler-build](https://github.com/prefix-dev/rattler-build/issues/628)

**Comment by jakirkham** [comment]
So `conda-build` version `24.7` shipped as did `24.9`. Do we want this in `24.11`?

**Comment by jaimergp** [comment]
I'll open a PR!
