### ISSUE TITLE
conda skeleton pypi package does not grab latest package version

### ISSUE THREAD

**Issue by ericmjl** [conda/conda-build#522]
That's been the issue I've had with conda skeleton. For example, my own package:

	ericmjl@rous:~$ conda skeleton pypi GenotypeNetwork
	Using url https://pypi.python.org/packages/source/G/GenotypeNetwork/GenotypeNetwork-0.1.0.tar.gz (2 KB) for GenotypeNetwork.
	Downloading GenotypeNetwork
	Using cached download
	Unpacking GenotypeNetwork...
	done
	working in /tmp/tmphk25mk43conda_skeleton_GenotypeNetwork-0.1.0.tar.gz
	Fetching package metadata: ......
	Solving package specifications: .
	Applying patch: '/tmp/tmphk25mk43conda_skeleton_GenotypeNetwork-0.1.0.tar.gz/pypi-distutils.patch'
	patching file core.py
	Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
	Traceback (most recent call last):
	  File "setup.py", line 16, in <module>
	    with open(path.join(here, 'README.md'), encoding='utf-8') as f:
	  File "/home/ericmjl/miniconda3/envs/_build/lib/python3.4/codecs.py", line 891, in open
	    file = builtins.open(filename, mode, buffering)
	FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphk25mk43conda_skeleton_GenotypeNetwork-0.1.0.tar.gz/GenotypeNetwork-0.1.0/README.md'
	$PYTHONPATH = /tmp/tmphk25mk43conda_skeleton_GenotypeNetwork-0.1.0.tar.gz/GenotypeNetwork-0.1.0::/home/ericmjl/miniconda/bin/python
	Error: command failed: /home/ericmjl/miniconda3/envs/_build/bin/python setup.py install

I have made fixes to the setup scripts in version 0.1.1 and 0.1.2, but none of them are grabbed by `conda skeleton`. Only the first uploaded version is - that is 0.1.0.

**Comment by asmeurer** [comment]
I think there is an issue with PyPI. The xmlrpc interface is only returning 0.1.0:

```
In [1]: import xmlrpc.client as xmlrpclib

In [2]: client = xmlrpclib.ServerProxy('https://pypi.python.org/pypi')

In [3]: client.package_releases('GenotypeNetwork')
Out[3]: ['0.1.0']
```

**Comment by ericmjl** [comment]
Is there a way in `conda skeleton` to specify the package version to grab?

**Comment by asmeurer** [comment]
There is, `--version`, but if it doesn't show up in the package_releases it's not going to work.

**Comment by ericmjl** [comment]
Got it. Filed a bug report with the PyPI folks.

**Comment by ericmjl** [comment]
Interesting enough, I see a JSON interface being mentioned: https://bitbucket.org/pypa/pypi/issues/300/xmlrpc-search-api-doesnt-does-not-found

Any chance conda skeleton might be able to use the JSON interface instead? Or is the XMLRPC interface an "official" interface?

**Comment by asmeurer** [comment]
We can't use the json interface because of https://bitbucket.org/pypa/pypi/issues/171/ordering-of-releases-in-json. I'd like to, though.

**Comment by ericmjl** [comment]
I see, got it. Sounds like it's truly an interface bug on PyPI's part. Gonna close this issue.
