### ISSUE TITLE
AppVeyor: Commit message with braces -> failed build

### ISSUE THREAD

**Issue by dalcinl** [conda/conda-build#525]
https://ci.appveyor.com/project/mpi4py/mpi4py/build/2.0.0a0-13/job/0q0w2g5o32qk3m94#L522

PS: I got a warning about conda-build being outdated. Isn't ``conda update --all`` supposed to update it? Maybe conflicting versions with dependencies?

**Comment by asmeurer** [comment]
I don't understand why update --all didn't seem to update anything.

**Comment by dalcinl** [comment]
Well, the thing is that you don't see the output just because the way the PowerShell script invokes conda. I've added an explicit conda update conda-build, now things seems to be working. However, the issue with commit messages and braces is probably still there.

**Comment by asmeurer** [comment]
I guess we need to quote the environment variables better.

**Comment by asmeurer** [comment]
https://github.com/conda/conda-build/pull/526
