### ISSUE TITLE
AppVeyor: AttributeError: 'module' object has no attribute 'get_pid_list

### ISSUE THREAD

**Issue by dalcinl** [conda/conda-build#527]
https://ci.appveyor.com/project/mpi4py/mpi4py/build/2.0.0a0-17/job/965h1pw9k7476768#L1187

conda info:
https://ci.appveyor.com/project/mpi4py/mpi4py/build/2.0.0a0-17/job/965h1pw9k7476768#L1076

Please note a few lines above I ran:
``C:\Anaconda\Scripts\conda.exe install --yes --quiet anaconda-client conda-build jinja2``

**Comment by dalcinl** [comment]
OK, I found the problem. Looking at the ``meta`.yaml` file https://github.com/conda/conda-build/blob/master/conda_build.recipe/meta.yaml, it seems you are missing a ``- psutil [win]`` line in the ``requirements/run:`` section.

**Comment by dalcinl** [comment]
Oh, sorry, I got it totally wrong. Now I see ``conda-build`` uses ``psutil`` optionally. However, it is attempting to invoke ``psutil.get_pid_list()``. That method is not available in recent versions of ``psutils``, I guess you have to use ``psutil.pids()``, or perhaps better refactor the code and just use ``psutil.process_iter()`` http://pythonhosted.org/psutil/#processes

**Comment by fallen** [comment]
hey @dalcinl I am having the same issue with a normal `conda build` on the following package https://github.com/m-labs/migen/tree/master/conda/migen
Did you find any workaround so that I can build my package without waiting conda-build to be fixed?

**Comment by dalcinl** [comment]
@fallen At this point I don't remember what I did. After a lot of refactoring of my conda builds in AppVeyor, the problem disappeared . Perhaps you could workaround by forcing an install of the old version of ``psutil``.

**Comment by fallen** [comment]
all right, fixed with conda install psutil=2.2.1

**Comment by ivoflipse** [comment]
While installing the older version of psutil solved the problem for me too, it would be nice if the call to get_pid_list got fixed.

**Comment by jan-glx** [comment]
:+1:

**Comment by vttran** [comment]
Quick fix is to replace psutil.get_pid_list() call in pscheck.py with psutil.pids(). Works ok for me.

**Comment by asmeurer** [comment]
https://github.com/conda/conda-build/pull/570
