### ISSUE TITLE
http://docs.continuum.io/conda/build.html referenced many places, but URL is a 404

### ISSUE THREAD

**Issue by jasongrout** [conda/conda-build#528]
Searching the source, you see http://docs.continuum.io/conda/build.html referenced many places, but the URL is a 404 (This webpage has a redirect loop, ERR_TOO_MANY_REDIRECTS).

Rather than fixing the URL, it may be better to fix the redirect.

**Comment by stuarteberg** [comment]
That url works for me....

**Comment by groutr** [comment]
I also have no problems see that page.

**Comment by jasongrout** [comment]
Yep, works now.  It didn't before.  So I guess the issue is fixed.
