### ISSUE TITLE
GIT_DESCRIBE_TAG isn't set when the .git is a file

### ISSUE THREAD

**Issue by jasongrout** [conda/conda-build#529]
Sometimes the .git directory is actually a file.  This happens, for example, when you have a git submodule.  This causes this test to fail incorrectly: https://github.com/conda/conda-build/blob/master/conda_build/environ.py#L36

Unfortunately, the .git file might point to a real git repo in a relative URL, so just moving the directory to the conda build directory can break it being a git repo.

**Comment by asmeurer** [comment]
https://github.com/conda/conda-build/pull/537
