### ISSUE TITLE
Ability to not include recipe in package

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda-build#534]
conda-build always includes the recipe in the conda package that is created.  There should be the ability to not do that, eg. an option `--no-recipe-include`.

**Comment by asmeurer** [comment]
Should it be a command line flag or a meta.yaml option?

**Comment by ilanschnell** [comment]
I think this should not be in the `meta.yaml`, it should be an option like `--no-recipe-include`.

**Comment by asmeurer** [comment]
This should be very easy to fix. The flag is already there internally.

**Comment by ilanschnell** [comment]
Yes, I saw that, https://github.com/conda/conda-build/blob/master/conda_build/build.py#L442
When is `bool(m.path)` ever not `True`?

**Comment by asmeurer** [comment]
In `conda metapackage`. It creates a Metadata object without a physical recipe.

**Comment by ilanschnell** [comment]
Ahh, I see.

**Comment by asmeurer** [comment]
https://github.com/conda/conda-build/pull/535
