### ISSUE TITLE
Add license metadata to packages

### ISSUE THREAD

**Issue by jasongrout** [conda/conda-build#541]
As discussed at https://groups.google.com/a/continuum.io/forum/#!topic/conda/ycHz2QLGUkE, provide a way to include license information in a package:
- [x] standardize and document an optional info/license.txt file that will contain license information for the package
- [x] make a meta.yaml build option for the license file name.  A missing value or `None` means no license information should be included
- [ ] Add explicit output to the conda-build output telling the user which file was used for the license file of the package, or that no license file was added (with maybe a pointer to docs about how to add the license file).  Preferably this output will be at the very bottom of the output, so it is prominent and visible to the user after the conda-build script is run.  We want to make it easy for the user to catch mistakes in this, with all the legal ramifications involved.
- [x] Add this meta.yaml key to the build documentation and the examples.

_Edit: as noted in the discussion, it's probably better to not have a default license file._

**Comment by ilanschnell** [comment]
Thanks Jason for writing this down.

**Comment by ilanschnell** [comment]
I've created this PR: https://github.com/conda/conda-build/pull/545
