### ISSUE TITLE
tests_require doesn't seem to work with bdist_conda

### ISSUE THREAD

**Issue by Legomaniac** [conda/conda-build#544]
Hello,

I have been building packages with setup.py bdist_conda and it has been incredibly convenient so far, as we have a large number of legacy modules that we need to convert into conda packages.

However, I seem to be having issues when trying to require a module to be included for testing. I see in the source for bdist_conda on line 176 ( https://github.com/conda/conda-build/blob/master/bdist_conda.py#L176 ) that it appears to be parsing this value out of the setup.py, however when I try to build the package, the import test fails.

For example, in my setup.py file:

```
from setuptools import setup, Extension
import distutils.command.bdist_conda

setup(  name='module_name',
        description='Module Description',
        version='1.2.1',
        distclass=distutils.command.bdist_conda.CondaDistribution,
        author='Name Redacted',
        author_email='redacted@redacted.com',
        tests_require=['yaml'],
        py_modules =  [ 'moduledir.module1', 'moduledir.module2', 'moduledir.module3', 'moduledir.module4' ]
     )
```

However, when I go to build the package, I receive the following error:

```
sudo /opt/anaconda/bin/python2.7 setup.py bdist_conda
........
import yaml
ImportError: No module named yaml
TESTS FAILED: module_name-1.2.1-py27_0
```

I can get around this by using `conda_import_tests=False`, but I would really rather have the import test as part of the packaging process. 

Has anyone run into this before, or is there something that I am simply missing? Any help is greatly appreciated!

**Comment by oronnavon** [comment]
Might be related to #4007
