### ISSUE TITLE
ABI conflict in test suite on `osx-64`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#5470]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Some of the tests are failing due to an ABI conflict on the `osx-64` runners, see https://github.com/conda/conda-build/actions/runs/10602558349/job/29384860323.

This is caused by channel mixing where we end up getting the following installed which causes a conflict:

```
pkgs/main::conda-libmamba-solver
conda-forge::libmambapy
conda-forge::libmamba
...
```

The channel mixing is unintentional as the only package we need from conda-forge is `xdoctest`. There are a few possible solutions here:
1. explicitly require `defaults::libmamba[py]`, see #5468
2. set `channel_priority: strict` for the test environment creation, see #5469
3. use `conda-forge` instead of `defaults`
4. request `xdoctest` be built for `defaults`
5. do we need `xdoctest` in the first place, maybe we just remove it? see #5471

**Comment by kenodegard** [comment]
even though we specify:

https://github.com/conda/conda-build/blob/a666e346249f211f9ecc88332d43f8f75e01323c/pyproject.toml#L110-L111

we aren't actually running `xdoctest` on the source code since `pytest` by default only crawls the `tests` directory

**Comment by h-vetinari** [comment]
Extracting out something from the logs:
```
Error while loading conda entry point: conda-libmamba-solver (dlopen(/Users/runner/miniconda3/envs/test/lib/python3.8/site-packages/libmambapy/bindings.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: <4AC18A07-59AA-3912-83CA-AD44A086503C> /Users/runner/miniconda3/envs/test/lib/libmamba.2.0.0.dylib
  Reason: tried: '/Users/runner/miniconda3/envs/test/lib/libarchive.13.dylib' (no such file), '/Users/runner/miniconda3/envs/test/lib/python3.8/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/runner/miniconda3/envs/test/lib/python3.8/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/runner/miniconda3/envs/test/bin/../lib/libarchive.13.dylib' (no such file), '/Users/runner/miniconda3/envs/test/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file, not in dyld cache))
```

The latest `libmamba 1.5.8` in conda-forge was built against `libarchive 3.7.2`, which has a different SOVER than 3.6; default doesn't have 3.7 yet, and so their latest `libmamba` is built against 3.6; that means the different pieces cannot be co-installed.

I wanted to check where the ABI break came from, because despite channel mixing not being really supported, it does happen frequently, and a lot of effort had gone into making things compatible.
