### ISSUE TITLE
`tests/test_api_build.py::test_sysroots_detection` failure

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#5475]
> `tests/test_api_build.py::test_sysroots_detection` implemented here is now failing on `main`, see https://github.com/conda/conda-build/actions/runs/10671805383/job/29578195906

_Originally posted by @kenodegard in https://github.com/conda/conda-build/issues/5404#issuecomment-2327186745_

**Comment by kenodegard** [comment]
Is this caused by https://github.com/conda-forge/ctng-compilers-feedstock/pull/148?

cc @h-vetinari @isuruf

**Comment by isuruf** [comment]
> Is this caused by https://github.com/conda-forge/ctng-compilers-feedstock/pull/148?

Yes, the solution was to add an empty `host` section

**Comment by kenodegard** [comment]
> > Is this caused by https://github.com/conda-forge/ctng-compilers-feedstock/pull/148?
>
> Yes, the solution was to add an empty `host` section

Already attempted to do that and it [doesn't resolve the failure](https://github.com/conda/conda-build/actions/runs/10689453621/job/29631595354?pr=5476) (see https://github.com/conda/conda-build/pull/5476)

I've gotten the tests to pass again by adding `ignore_run_exports_from` (see https://github.com/conda/conda-build/pull/5471) inspired by changes done to other conda-forge recipes (https://github.com/conda-forge/ctng-compilers-feedstock/pull/148#issuecomment-2292895748)

**Comment by isuruf** [comment]
Oh we have https://github.com/conda/conda-build/blob/abb3f18d26fe7166eb3daa2159a4cd59009fc6c7/conda_build/post.py#L1327-L1328. We can just add `libgcc` too

**Comment by kenodegard** [comment]
Wouldn't it be more appropriate to add a selector to `conda-forge::libgcc`'s `run_exports` instead of adding more hardcoded conditions into conda-build?

**Comment by isuruf** [comment]
> Wouldn't it be more appropriate to add a selector to conda-forge::libgcc's run_exports instead of adding more hardcoded conditions into conda-build?

What do you mean?

**Comment by kenodegard** [comment]
Can't we just do something like the following in https://github.com/conda-forge/ctng-compilers-feedstock:

```yaml
outputs:
  - name: gcc_impl_{{ cross_target_platform }}
    run_exports:                      # [not linux]
      strong:                         # [not linux]
        - libgcc >={{ gcc_version }}  # [not linux]
```

**Comment by kenodegard** [comment]
oops, I was checking stuff on the wrong platform

gotcha, we want the overlinking/overdepending checks to be run on a subset of `run_exports`, and this cannot be achieved in the upstream package, so either every downstream package defines their own `ignore_run_exports_from` or we make your suggested change in conda-build
