### ISSUE TITLE
conda skeleton ignores the proxy environment variables

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda-build#550]
When an Enterprise client is operating from behind a proxy server, the conda skeleton command appears to ignore the availability of proxy settings in the $HTTP_PROXY, $HTTPS_PROXY and $NO_PROXY environment variables and fails connecting to pypi unless proxy settings are specified in the conda configuration file (observed with conda 3.16.0 on linux rhel6).

It would be really great if this behavior could be fixed and conda skeleton made use of the environment settings (as conda already does in most cases).

**Comment by PeterDSteinberg** [comment]
@JeremyEnns I'm working on this.   It looks to me like we need to be explicit in the version of requests that gets installed with conda.  I see there are changes in requests from version to version recently with respect to 
 * whether proxy variables can be taken from the environment, 
 * whether the request scheme has to be included in the proxy variable, and 
 * whether NO_PROXY env variable is respected for domains excluded from the HTTP_PROXY.  

See [http://docs.python-requests.org/en/latest/community/updates/#id29](http://docs.python-requests.org/en/latest/community/updates/#id29)

In conda, there is an ```install_requires``` entry in ```setup.py``` for requests but we don't have a requirements file to specify which version. Would adding a recent requests version to a requirements file fix this, @csoja ?

**Comment by PeterDSteinberg** [comment]
Do you know @JeremyEnns whether this bug occurred when using Miniconda-based install or Anaconda.  My guess is Miniconda because Anaconda would have included the most recent requests version that does proxy environment variables.

**Comment by filmor** [comment]
I have version 2.9.1 of requests installed. I think the offending part is the function `get_xmlrpc_client` in `pypi.py`:

    proxies = get_proxy_servers()

    if proxies:
        transport = RequestsTransport()
    else:
        transport = None

If I unconditionally use the `RequestsTransport` here, then it will use the proxy servers defined in the environment variables correctly.

**Comment by Data-drone** [comment]
I can't seem to find pypi.py? where is located?

**Comment by filmor** [comment]
Ahm ... `conda_build/pypi.py`. Check the pull request.

**Comment by rvianello** [comment]
thanks @filmor @msarahan
