### ISSUE TITLE
Trouble building with `python setup.py bdist_conda`

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#555]
See the following error.

    error: [Errno 2] No such file or directory: '/zopt/conda/envs/_build/info/index.json'

It appears the `info` directory is missing here.

I am seeing this with `conda-build` version 1.17. To get an example try using this repo ( https://github.com/jakirkham/nanshe ) and in the `root` environment try running `python setup.py bdist_conda`. This problem does not occur with `conda-build` version 1.16.

**Comment by mbalasso** [comment]
+1

**Comment by asmeurer** [comment]
I think 7954a9dfae7bca7a131cb5ba6fca6ca29f6a2f9c fixed this.

**Comment by jakirkham** [comment]
Thanks @asmeurer. I went to build that change and ran into this issue ( https://github.com/conda/conda-build/issues/556 ).
