### ISSUE TITLE
Trouble building `conda-build` from included recipe

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#556]
Ran the following.

    $ conda build conda_build.recipe

Long log included in gist. Shortened traceback below.

      File "/zopt/conda/envs/_test/lib/python2.7/site-packages/conda_build/config.py", line 24, in Config
        CONDA_NPY = int(os.getenv('CONDA_NPY', '0').replace('.', '')) or None
    ValueError: invalid literal for int() with base 10: 'None'
    TESTS FAILED: conda-build-1.17.0+7.g7954a9d-py27_15_gb92750e

See more details here ( https://gist.github.com/jakirkham/c7719e85ad4540d9b032 )

**Comment by asmeurer** [comment]
Can you show me the meta.yaml?

**Comment by jakirkham** [comment]
I applied this diff to this commit b92750ea52232a2c64a4b658c8eac2e3df0dafb4. However, if I remove it, I get the same issue. I have added the unpatched log to the gist.

    $ git diff
    diff --git a/conda_build.recipe/meta.yaml b/conda_build.recipe/meta.yaml
    index c445e54..aa21be0 100644
    --- a/conda_build.recipe/meta.yaml
    +++ b/conda_build.recipe/meta.yaml
    @@ -1,6 +1,6 @@
     package:
       name: conda-build
    -  version: 1.10alpha.0
    +  version: 1.17.0+7.g7954a9d
     
     source:
       git_url: ../

**Comment by asmeurer** [comment]
Oh it's the included recipe for conda build. I didn't catch that.

**Comment by asmeurer** [comment]
See https://github.com/conda/conda-build/pull/569.

**Comment by jakirkham** [comment]
Ah, sorry, I could have been clearer.

So, I tried building that and ran into a different issue. Log added to the gist referencing the PR.
