### ISSUE TITLE
`noarch_python` doesn't switch local repository path

### ISSUE THREAD

**Issue by frol** [conda/conda-build#557]
Building a package with `noarch_python` option (#317) in a clean conda-bld installation leads to an error:

```
$ conda build invoke
Removing old build environment
Removing old work directory
BUILD START: invoke-current-py_0
Fetching package metadata: .....Error: Could not find URL: file:///home/username/conda-bld/linux-64/
```

It creates `repodata.json` and `repodata.json.bz2` in `conda-bld/noarch`, but tries to load local repo information from `conda-bld/linux-64`.

**Comment by henningpeters** [comment]
I got the same issue, see build log here:

```https://travis-ci.org/henningpeters/text-unidecode-conda/jobs/84062596```

**Comment by frol** [comment]
This seems to be solved. BTW, a new syntax for noarch packages was introduced: https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages (`noarch: python`)
