### ISSUE TITLE
Baking the visual studio version

### ISSUE THREAD

**Issue by pelson** [conda/conda-build#562]
There are some details which mean that some distributions cannot be used if they have been built with different VS versions. One such example was discovered in https://github.com/SciTools/conda-recipes-scitools/issues/94. 

Has any consideration been made for putting the VS version in the build string, or some such thing?

Incidentally, if anybody else wants to work around the problem, just put python as a run dependency, and the VS is effectively baked (by virtue that the Python it is built against is baked).

**Comment by pelson** [comment]
Thanks @asmeurer.

> We pretty much assume that things are using the standard versions

A perfectly valid assumption, but what do you do when you have a non python library which needs to be linked to from py2 and py3 packages? At the moment, I've just put an artificial run dependency on Python on a completely non-Python package.

Is there much appetite to look at the possibility of baking the VS studio version into the build string for non-Python packages? I'm guessing you guys haven't seen this crop up on any of the shipped anaconda distributions?

**Comment by asmeurer** [comment]
It's certainly something you can do manually. I'm not sure if it's worth doing automatically. I hasn't really come up before, though.

**Comment by pelson** [comment]
>  I'm not sure if it's worth doing automatically. I hasn't really come up before, though.

Ok. Thanks @asmeurer. If doing automatically there are some challenges which need to be handled (e.g. you may be using mingw) - fixing this may not be worth the effort, as you say.

**Comment by pelson** [comment]
Looks like this has been done with some of the anaconda distributions (e.g. proj4, geos, libpng etc.). Was that done using conda-build @ilanschnell, and if not, is there some magic I can add to conda-build to deal with VS versions?

**Comment by ilanschnell** [comment]
Yes, this was done using conda-build.

**Comment by msarahan** [comment]
@pelson, this is done using "features" in Conda.  Python is set to track vc features now.  To have your module/library provide and install the correct MSVC-compiled version, you need a section like this in your meta.yaml:

```
build:
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]
```

Libraries/modules that depend on Python and this library you're building need nothing more.  If a consumer of this library does not depend on Python as a build-time dependency, you need to tell it to track it differently (something I don't understand well enough to tell you how here.)  Our internal hack for now has simply been to add Python as a build dependency, even where it is not used in build, just to have the feature tracked.  We'll be fleshing out these docs after the Anaconda 2.4 release.

**Comment by pelson** [comment]
Super. Thanks to the both of you. Sounds like a sensible workaround. I'll bear that in mind when developing non-Python distributions.
