### ISSUE TITLE
"conda build --python x.y" does not work as advertised

### ISSUE THREAD

**Issue by ikalev** [conda/conda-build#565]
Using the ``CONDA_PY`` environment variable works as expected. If it is set to ``34``, conda builds a Python 3.4 package using Visual Studio 2010. 

However, ``conda build --python 3.4`` does not produce the same result. Conda picks Visual Studio 2008, because ``config.PY3`` is incorrectly set to 0 and ``msvc_env_cmd()`` relies on this constant to determine the correct version of VS: 

  https://github.com/conda/conda-build/blob/master/conda_build/windows.py#L64

**Comment by asmeurer** [comment]
https://github.com/conda/conda-build/pull/568
