### ISSUE TITLE
source/path should work with a file

### ISSUE THREAD

**Issue by RJT1990** [conda/conda-build#567]
I have a custom package I've built in a regular Python environment - I now have it sourced in a tar file widget-1.0.tar. I am trying to get this installed in my Anaconda environment. I've build a meta.yaml file as follows to install from a local path:

```
package:
  name: widget

source:
  fn: widget-1.0.tar
  path: C:\Users\user\Documents\widget\dist\widget-1.0.tar

build:
  number: 0
```

But when I run conda build widget I get the following unexpected error:

C:\Users\user\Documents\Biv Pois>conda build widget
Removing old build environment
Removing old work directory
BUILD START: widget--0
Removing old work directory
Source cache directory is: C:\Users\user\Anaconda\conda-bld\src_cache
Downloading source to cache: widget-1.0.tar
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\user\Anaconda\Scripts\conda-build-script.py", line 4, in <modul
e>
    sys.exit(main())
  File "C:\Users\user\Anaconda\lib\site-packages\conda_build\main_build.py", lin
e 190, in main
    args_func(args, p)
  File "C:\Users\user\Anaconda\lib\site-packages\conda_build\main_build.py", lin
e 429, in args_func
    args.func(args, p)
  File "C:\Users\user\Anaconda\lib\site-packages\conda_build\main_build.py", lin
e 384, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe
)
  File "C:\Users\user\Anaconda\lib\site-packages\conda_build\build.py", line 384
, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Users\user\Anaconda\lib\site-packages\conda_build\source.py", line 25
1, in provide
    unpack(meta)
  File "C:\Users\user\Anaconda\lib\site-packages\conda_build\source.py", line 74
, in unpack
    src_path = download_to_cache(meta)
  File "C:\Users\user\Anaconda\lib\site-packages\conda_build\source.py", line 49
, in download_to_cache
    if not isinstance(meta['url'], list):
KeyError: 'url'

**Comment by asmeurer** [comment]
The error message could probably be better here, but `path` only works when referring to a directory. To use a local tarball, use a `file:///` url.

**Comment by RJT1990** [comment]
Thank you - I suspected it was a stupid mistake on my part.

**Comment by asmeurer** [comment]
We could probably make `path` work as a file.

**Comment by jehturner** [comment]
Is there a way to give it a relative path to a tarball? The docs say that "path" can be relative to the recipe directory but I can't see how to do that with "url" and I need some way of abstracting the local path to source tarballs for building the same recipe at different sites that have different directories. Ideally that would be achieved via something like an environment variable in meta.yaml (which doesn't seem to work) but using "../" would also avoid hard-coding site-specific paths. Also, more generally, I would like to figure out a way of keeping local copies of tarballs (eg. on an NFS mount) without every build machine having to download and cache them all separately, since our Internet connection is slow & unreliable where we are based, in Chile. Thanks for any info. or suggestions.

**Comment by jehturner** [comment]
PS. That was probably a bit much background -- I'm mainly commenting in this issue to see whether the changes proposed are also the solution to specifying a relative path to a tarball, if it's not already possible.

**Comment by msarahan** [comment]
yes, we should be able to add this.  I'll mark this as a feature for the next minor release.

I don't know about NFS, but you can just download a bunch of packages and put them behind a webserver.  The ```conda index``` command will create the repository information that conda needs.  Then you just serve up that folder.  You add the URL to that server as a channel in condarc, or specify it on the command line with -c.

**Comment by jehturner** [comment]
OK, great & thanks for the pointer; I'll look into doing something like that.
