### ISSUE TITLE
Tests 'numpy_build_run' and 'numpy_run' fail

### ISSUE THREAD

**Issue by ukoethe** [conda/conda-build#576]
... both on my local machine and on Travis.

The problem is that the test expects the package name to match
```
conda-build-test-numpy-build-run-1.0-nppy*0
```
but the actual package name is 
```
conda-build-test-python-build-run-1.0-py27_0
```
(without `np`). Did someone change the default build string and forgot to update the test? Or is there something wrong with my conda installation?

**Comment by asmeurer** [comment]
I think this is fixed now.
