### ISSUE TITLE
Error while building pywin32

### ISSUE THREAD

**Issue by ivoflipse** [conda/conda-build#591]
I tried building a package for pywin32 using conda skeleton, but I keep getting the following error:

```
C:\Development\Projects\conda-recipes> conda skeleton pypi pywin32
Warning, the following versions were found for pywin32
214
210
Using 214
Use --version to specify a different version.
Using url https://sourceforge.net/projects/pywin32/files/pywin32/ (0 B) for pywin32.
Downloading pywin32
Error: Could not rename 'C:\\Anaconda64\\conda-bld\\src_cache\\.part' to 'C:\\Anaconda64\\conda-bld\\src_cache\\': WindowsError(183, 'Cann
ot create a file when that file already exists')`
```

I tried removing the .part file, but I reckon its a partial download of the pywin32 package and therefore keeps coming back.

I'm running Windows 10 using 64-bit Python. Any suggestions on what to do?

**Comment by msarahan** [comment]
try using conda clean --packages --tarballs

Otherwise, maybe delete folders in conda-bld manually, and let conda recreate them?

**Comment by asmeurer** [comment]
It's trying to download a file that doesn't exist (pywin32 doesn't have any files on PyPI).

**Comment by ivoflipse** [comment]
@asmeurer Thanks for figuring out what the probable culprit is. It would be helpful if it told you that was the reason. 

Sadly the package does a lot of weird stuff that building from source (from sourceforge) may not behave so well anyway.

**Comment by asmeurer** [comment]
This is a bug. conda shouldn't have tried to download anything.

**Comment by asmeurer** [comment]
I guess it does have a download url, but it doesn't link to a file (it links to a sourceforge page).
