### ISSUE TITLE
Documentation: post-link.sh

### ISSUE THREAD

**Issue by bkreider** [conda/conda-build#592]
I'm sorry if i missed this, but i cannot find documentation around post-link.sh in the docs.  If i missed it where is it?  I was looking to see what ENV variables are available in post-link scripts.  From the conda source i see this:

```
    env = os.environ
    env['PREFIX'] = str(env_prefix or prefix)
    env['PKG_NAME'], env['PKG_VERSION'], env['PKG_BUILDNUM'] = \
                str(dist).rsplit('-', 2)
    if action == 'pre-link':
        env['SOURCE_DIR'] = str(prefix)
```

That is confusing to me though.  I thought the environment was wiped clean first and then added to.  The code implies that it inherits os.environ?

**Comment by bollwyvl** [comment]
Here's the doc!

http://conda.pydata.org/docs/building/build-scripts.html

When I last looked, it was:

var | description
------------ | -------------
`PREFIX` | The install prefix.
`PKG_NAME` | The name of the package.
`PKG_VERSION` | The version of the package.
`PKG_BUILDNUM` | The build number of the package.
`RECIPE_DIR` | Path to the recipe files.

Not sure about the larger question, but thought this might be useful!

**Comment by bkreider** [comment]
Thanks!
