### ISSUE TITLE
build leaves files in conda-bld/work/ that other users cannot remove

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda-build#593]
When running conda build under linux, there is a global work directory created under conda-bld/work/ This is shared by anyone using the same anaconda root environment. The problem is that the files and directories under it are created with permissions set to 755, only the person who created it has write permissions. At least some files remain under this directory after the cleanup step in the build.

Once someone has created a package, no one else is able to build another package until the folder has been removed by the person who did the first build or an admin.

Could you please make sure all files are removed in the first cleanup step, so more than one person can make builds?

Error stack:

> conda build pandas-highcharts
> Removing old build directory
> Removing old work directory
> An unexpected error has occurred, please consider sending the
> following traceback to the conda GitHub issue tracker at:
> https://github.com/conda/conda-build/issues
> Include the output of the command 'conda info' in your report.
> Traceback (most recent call last):
> 
> File "/auto/energymdl2/anaconda/bin/conda-build", line 5, in <module> 
> sys.exit(main())
> File "/auto/energymdl2/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 118, in > main args_func(args, p)
> File "/auto/energymdl2/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 329, in > args_func args.func(args, p)
> File "/auto/energymdl2/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 288, in > execute channel_urls=channel_urls, override_channels=args.override_channels)
> File "/auto/energymdl2/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 336, in build
> rm_rf(source.WORK_DIR)
> File "/auto/energymdl2/anaconda/lib/python2.7/site-packages/conda/install.py", line 186, in rm_rf
> shutil.rmtree(path)
> File "/auto/energymdl2/anaconda/lib/python2.7/shutil.py", line 247, in rmtree
> rmtree(fullname, ignore_errors, onerror)
> File "/auto/energymdl2/anaconda/lib/python2.7/shutil.py", line 252, in rmtree
> onerror(os.remove, fullname, sys.exc_info())
> File "/auto/energymdl2/anaconda/lib/python2.7/shutil.py", line 250, in rmtree
> os.remove(fullname)
> OSError: [Errno 13] Permission denied: '/auto/energymdl2/anaconda/conda-bld/work/pyModis-1.0.2/.gitignore'

**Comment by JeremyEnns** [comment]
http://conda.pydata.org/docs/config.html#specify-conda-build-output-root-directory current workaround, might be a good idea to default to ~/conda-bld/ in a future release

**Comment by jakirkham** [comment]
`conda-build` uses multiple build directories now and can be run in parallel without blocking on the old `work` directory. Given this, this issue should be closed as resolved.
