### ISSUE TITLE
source fn default

### ISSUE THREAD

**Issue by jasongrout** [conda/conda-build#594]
In the meta.yaml, when the source is specified with a url, it seems that the `fn` key is required.  Can we make the default `fn` be the filename in the url (perhaps obtained using urlparse)?That's probably what the `fn` key will be in the vast majority of cases.

Something like this (in python 2):

``` python
from urlparse import urlparse
import posixpath
import urllib
path = urllib.unquote(urlparse(url).path)
fn = posixpath.split(path)[1]
```

**Comment by asmeurer** [comment]
Sure.

**Comment by jakirkham** [comment]
This has since happened. Should be closed I think.
