### ISSUE TITLE
%PREFIX% in bld.bat points to /opt/anaconda1anaconda2anaconda3 on Windows but not in the console output

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#597]
I wrote this in a recipe's `bld.bat`:

`for %%f in ("%PREFIX%\packagename\subdir\*.exe") do echo %%f %%* >> "%SCRIPTS%\%%~nf.bat"`

And the console shows that it evaluates correctly:

`echo C:\Users\korijn\Miniconda\envs\_build\packagename\subdir\foo.exe %*  1>>"C:\Users\korijn\Miniconda\envs\_build\Scripts\foo.bat"`

And when I open that file, this is what it contains:

`/opt/anaconda1anaconda2anaconda3\packagename\subdir\foo.exe %* `

How did that happen?!

**Comment by Korijn** [comment]
Nevermind, I feel silly already.

**Comment by msarahan** [comment]
Could you please post what your mistake was, so others might learn from it?

Thanks!

**Comment by Korijn** [comment]
Well, turns out I was writing absolute paths, and I read that Anaconda internally performs all their builds in `/opt/anaconda1anaconda2anaconda3`, so I guess they replace absolute paths with that so they can perform some post processing there, or something like that. I guess we'd have to ask someone who works at Continuum about that!

It would never work anyway, once installed on a different machine the absolute path are bogus, obviously!

I changed it to:

`for %%f in ("%PREFIX%\packagename\subdir\*.exe") do echo .\..\packagename\subdir\%%~nxf %%* >> "%SCRIPTS%\%%~nf.bat"`

**Comment by msarahan** [comment]
Thanks for posting back!

**Comment by Korijn** [comment]
Well, I still didn't get it right, turns out, there's a special feature for this sort of stuff, and you have to leave the hardcoded paths in there, but mark them in the meta.yaml file so conda will replace them upon install (if I understand correctly).

See https://github.com/conda/conda-build/pull/195

**Comment by asmeurer** [comment]
If they are in plain text files you don't have to do anything. Conda will replace them automatically. 

For binary files you do need to enable it manually.

**Comment by Korijn** [comment]
Awesome!

**Comment by asmeurer** [comment]
Yes, that is right. conda build replaces the build path with the magic string so that your username doesn't end up in the final package, but when conda installs it, it gets replaced with the install prefix.
