### ISSUE TITLE
Copy recipe

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#6]
The recipe should be copied during the build. If something modifies the recipe during the build, it modifies the original recipe. This happens even for things like the new `script` parameter, which writes a build script to the recipe itself.

**Comment by msarahan** [comment]
This is how things work now.  Copies of the original recipe are included by default in the info/recipe folder.  This can be disabled with the --no-include-recipe flag:

```
--no-include-recipe   Don't include the recipe inside the built package.
```
