### ISSUE TITLE
Build fails for pymongo 3.0.3 - Winx64 - Python 3.4.3

### ISSUE THREAD

**Issue by bmcguirk** [conda/conda-build#610]
Hi guys - I feel like I'm coming up with a lot of these, but here you go: 

    PS C:\Anaconda3\pkg_assembly> conda skeleton pypi pymongo
    Warning, the following versions were found for pymongo
    3.0.3
    3.0.2
    3.0.1
    3.0
    2.8.1
    2.8
    2.7.2
    2.7.1
    2.7
    2.6.3
    2.6.2
    2.6.1
    2.6
    2.5.2
    2.5.1
    2.5
    2.4.2
    2.4.1
    2.4
    2.3
    2.2.1
    2.2
    2.1.1
    2.1
    2.0.1
    2.0
    1.11
    1.10.1
    1.10
    1.9
    1.8.1
    1.8
    1.7
    1.6
    1.5.2
    1.5.1
    1.5
    1.4
    1.3
    1.2.1
    1.2
    1.1.2
    1.1.1
    1.1
    1.0
    0.16
    0.15.2
    0.15.1
    0.15
    0.14.2
    0.14.1
    0.14
    0.13
    0.12
    0.11.3
    0.11.2
    0.11.1
    0.11
    0.10.3
    0.10.2
    0.10.1
    0.10
    0.9.7
    0.9.6
    0.9.5
    0.9.4
    0.9.3
    0.9.2
    0.9.1
    0.9
    0.8.1
    0.8
    0.7.2
    0.7.1
    0.7
    0.6
    0.5.3pre
    0.5.2pre
    0.5.1pre
    0.5pre
    0.4pre
    0.3.1pre
    0.3pre
    0.2pre
    0.1.2pre
    0.1.1pre
    0.1pre
    Using 3.0.3
    Use --version to specify a different version.
    Using url https://pypi.python.org/packages/source/p/pymongo/pymongo-3.0.3.tar.gz (410 KB) for pymongo.
    Downloading pymongo
    Unpacking pymongo...
    done
    working in C:\Users\BRIAN~1.MCG\AppData\Local\Temp\tmp9l129y88conda_skeleton_pymongo-3.0.3.tar.gz
    Fetching package metadata: ......
    Solving package specifications: ........
    The following NEW packages will be INSTALLED:

        numpy:  1.9.3-py34_0
        pyyaml: 3.11-py34_2

    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Applying patch: 'C:\\Users\\BRIAN~1.MCG\\AppData\\Local\\Temp\\tmp9l129y88conda_skeleton_pymongo-3.0.3.tar.gz\\pypi-distutils.patch'
    patching file `core.py'
    Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
    Writing recipe for pymongo
    Done
    PS C:\Anaconda3\pkg_assembly> conda build pymongo
    Removing old build environment
    Removing old work directory
    BUILD START: pymongo-3.0.3-py34_0
    Fetching package metadata: ......
    Solving package specifications: ........
    The following NEW packages will be INSTALLED:

        pip:        7.1.2-py34_0
        python:     3.4.3-0
        setuptools: 18.3.2-py34_0
        wheel:      0.26.0-py34_1

    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Removing old work directory
    Source cache directory is: C:\Anaconda3\conda-bld\src_cache
    Found source in cache: pymongo-3.0.3.tar.gz
    Extracting download
    Package: pymongo-3.0.3-py34_0
    source tree in: C:\Anaconda3\conda-bld\work\pymongo-3.0.3

    C:\Anaconda3\conda-bld\work\pymongo-3.0.3>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64
    Setting environment for using Microsoft Visual Studio 2008 x64 tools.

    C:\Anaconda3\conda-bld\work\pymongo-3.0.3>REM ===== end generated header =====

    C:\Anaconda3\conda-bld\work\pymongo-3.0.3>"C:\Anaconda3\envs\_build\python.exe" setup.py install
    running install
    running bdist_egg
    running egg_info
    writing dependency_links to pymongo.egg-info\dependency_links.txt
    writing top-level names to pymongo.egg-info\top_level.txt
    writing pymongo.egg-info\PKG-INFO
    reading manifest file 'pymongo.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pymongo.egg-info\SOURCES.txt'
    installing library code to build\bdist.win-amd64\egg
    running install_lib
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    creating build\lib.win-amd64-3.4\bson
    copying bson\binary.py -> build\lib.win-amd64-3.4\bson
    copying bson\code.py -> build\lib.win-amd64-3.4\bson
    copying bson\codec_options.py -> build\lib.win-amd64-3.4\bson
    copying bson\dbref.py -> build\lib.win-amd64-3.4\bson
    copying bson\errors.py -> build\lib.win-amd64-3.4\bson
    copying bson\int64.py -> build\lib.win-amd64-3.4\bson
    copying bson\json_util.py -> build\lib.win-amd64-3.4\bson
    copying bson\max_key.py -> build\lib.win-amd64-3.4\bson
    copying bson\min_key.py -> build\lib.win-amd64-3.4\bson
    copying bson\objectid.py -> build\lib.win-amd64-3.4\bson
    copying bson\py3compat.py -> build\lib.win-amd64-3.4\bson
    copying bson\regex.py -> build\lib.win-amd64-3.4\bson
    copying bson\son.py -> build\lib.win-amd64-3.4\bson
    copying bson\timestamp.py -> build\lib.win-amd64-3.4\bson
    copying bson\tz_util.py -> build\lib.win-amd64-3.4\bson
    copying bson\__init__.py -> build\lib.win-amd64-3.4\bson
    creating build\lib.win-amd64-3.4\pymongo
    copying pymongo\auth.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\bulk.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\client_options.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\collection.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\command_cursor.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\common.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\cursor.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\cursor_manager.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\database.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\errors.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\helpers.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\ismaster.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\message.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\mongo_client.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\mongo_replica_set_client.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\monitor.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\monotonic.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\network.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\operations.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\periodic_executor.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\pool.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\read_preferences.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\response.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\results.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\server.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\server_description.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\server_selectors.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\server_type.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\settings.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\son_manipulator.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\ssl_context.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\ssl_match_hostname.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\ssl_support.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\thread_util.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\topology.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\topology_description.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\uri_parser.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\write_concern.py -> build\lib.win-amd64-3.4\pymongo
    copying pymongo\__init__.py -> build\lib.win-amd64-3.4\pymongo
    creating build\lib.win-amd64-3.4\gridfs
    copying gridfs\errors.py -> build\lib.win-amd64-3.4\gridfs
    copying gridfs\grid_file.py -> build\lib.win-amd64-3.4\gridfs
    copying gridfs\__init__.py -> build\lib.win-amd64-3.4\gridfs
    running build_ext
    building 'bson._cbson' extension
    creating build\temp.win-amd64-3.4
    creating build\temp.win-amd64-3.4\Release
    creating build\temp.win-amd64-3.4\Release\bson
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ibson -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /Tcbson/_cbsonmodule.c /Fobuild\temp.win-amd64-3.4\Release\bson/_cbsonmodule.obj
    _cbsonmodule.c
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ibson -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /Tcbson/time64.c /Fobuild\temp.win-amd64-3.4\Release\bson/time64.obj
    time64.c
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ibson -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /Tcbson/buffer.c /Fobuild\temp.win-amd64-3.4\Release\bson/buffer.obj
    buffer.c
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ibson -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /Tcbson/encoding_helpers.c /Fobuild\temp.win-amd64-3.4\Release\bson/encoding_helpers.obj
    encoding_helpers.c
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Anaconda3\envs\_build\libs /LIBPATH:C:\Anaconda3\envs\_build\PCbuild\amd64 /EXPORT:PyInit__cbson build\temp.win-amd64-3.4\Release\bson/_cbsonmodule.obj build\temp.win-amd64-3.4\Release\bson/time64.obj build\temp.win-amd64-3.4\Release\bson/buffer.obj build\temp.win-amd64-3.4\Release\bson/encoding_helpers.obj /OUT:build\lib.win-amd64-3.4\bson\_cbson.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\bson\_cbson.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\bson\_cbson.pyd.manifest
    _cbsonmodule.obj : warning LNK4197: export 'PyInit__cbson' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.4\Release\bson\_cbson.lib and object build\temp.win-amd64-3.4\Release\bson\_cbson.exp
    building 'pymongo._cmessage' extension
    creating build\temp.win-amd64-3.4\Release\pymongo
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ibson -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /Tcpymongo/_cmessagemodule.c /Fobuild\temp.win-amd64-3.4\Release\pymongo/_cmessagemodule.obj
    _cmessagemodule.c
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ibson -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /Tcbson/buffer.c /Fobuild\temp.win-amd64-3.4\Release\bson/buffer.obj
    buffer.c
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Anaconda3\envs\_build\libs /LIBPATH:C:\Anaconda3\envs\_build\PCbuild\amd64 /EXPORT:PyInit__cmessage build\temp.win-amd64-3.4\Release\pymongo/_cmessagemodule.obj build\temp.win-amd64-3.4\Release\bson/buffer.obj /OUT:build\lib.win-amd64-3.4\pymongo\_cmessage.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\pymongo\_cmessage.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\pymongo\_cmessage.pyd.manifest
    _cmessagemodule.obj : warning LNK4197: export 'PyInit__cmessage' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.4\Release\pymongo\_cmessage.lib and object build\temp.win-amd64-3.4\Release\pymongo\_cmessage.exp
    creating build\bdist.win-amd64
    creating build\bdist.win-amd64\egg
    creating build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\binary.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\code.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\codec_options.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\dbref.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\errors.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\int64.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\json_util.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\max_key.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\min_key.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\objectid.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\py3compat.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\regex.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\son.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\timestamp.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\tz_util.py -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\_cbson.pyd -> build\bdist.win-amd64\egg\bson
    copying build\lib.win-amd64-3.4\bson\__init__.py -> build\bdist.win-amd64\egg\bson
    creating build\bdist.win-amd64\egg\gridfs
    copying build\lib.win-amd64-3.4\gridfs\errors.py -> build\bdist.win-amd64\egg\gridfs
    copying build\lib.win-amd64-3.4\gridfs\grid_file.py -> build\bdist.win-amd64\egg\gridfs
    copying build\lib.win-amd64-3.4\gridfs\__init__.py -> build\bdist.win-amd64\egg\gridfs
    creating build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\auth.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\bulk.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\client_options.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\collection.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\command_cursor.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\common.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\cursor.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\cursor_manager.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\database.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\errors.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\helpers.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\ismaster.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\message.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\mongo_client.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\mongo_replica_set_client.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\monitor.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\monotonic.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\network.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\operations.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\periodic_executor.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\pool.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\read_preferences.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\response.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\results.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\server.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\server_description.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\server_selectors.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\server_type.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\settings.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\son_manipulator.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\ssl_context.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\ssl_match_hostname.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\ssl_support.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\thread_util.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\topology.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\topology_description.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\uri_parser.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\write_concern.py -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\_cmessage.pyd -> build\bdist.win-amd64\egg\pymongo
    copying build\lib.win-amd64-3.4\pymongo\__init__.py -> build\bdist.win-amd64\egg\pymongo
    byte-compiling build\bdist.win-amd64\egg\bson\binary.py to binary.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\code.py to code.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\codec_options.py to codec_options.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\dbref.py to dbref.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\errors.py to errors.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\int64.py to int64.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\json_util.py to json_util.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\max_key.py to max_key.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\min_key.py to min_key.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\objectid.py to objectid.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\py3compat.py to py3compat.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\regex.py to regex.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\son.py to son.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\timestamp.py to timestamp.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\tz_util.py to tz_util.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\bson\__init__.py to __init__.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\gridfs\errors.py to errors.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\gridfs\grid_file.py to grid_file.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\gridfs\__init__.py to __init__.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\auth.py to auth.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\bulk.py to bulk.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\client_options.py to client_options.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\collection.py to collection.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\command_cursor.py to command_cursor.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\common.py to common.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\cursor.py to cursor.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\cursor_manager.py to cursor_manager.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\database.py to database.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\errors.py to errors.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\helpers.py to helpers.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\ismaster.py to ismaster.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\message.py to message.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\mongo_client.py to mongo_client.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\mongo_replica_set_client.py to mongo_replica_set_client.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\monitor.py to monitor.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\monotonic.py to monotonic.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\network.py to network.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\operations.py to operations.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\periodic_executor.py to periodic_executor.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\pool.py to pool.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\read_preferences.py to read_preferences.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\response.py to response.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\results.py to results.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\server.py to server.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\server_description.py to server_description.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\server_selectors.py to server_selectors.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\server_type.py to server_type.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\settings.py to settings.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\son_manipulator.py to son_manipulator.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\ssl_context.py to ssl_context.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\ssl_match_hostname.py to ssl_match_hostname.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\ssl_support.py to ssl_support.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\thread_util.py to thread_util.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\topology.py to topology.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\topology_description.py to topology_description.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\uri_parser.py to uri_parser.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\write_concern.py to write_concern.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\__init__.py to __init__.cpython-34.pyc
    creating stub loader for bson\_cbson.pyd
    creating stub loader for pymongo\_cmessage.pyd
    byte-compiling build\bdist.win-amd64\egg\bson\_cbson.py to _cbson.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\pymongo\_cmessage.py to _cmessage.cpython-34.pyc
    creating build\bdist.win-amd64\egg\EGG-INFO
    copying pymongo.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
    copying pymongo.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
    copying pymongo.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
    copying pymongo.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
    writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
    zip_safe flag not set; analyzing archive contents...
    bson.__pycache__._cbson.cpython-34: module references __file__
    pymongo.__pycache__._cmessage.cpython-34: module references __file__
    creating dist
    creating 'dist\pymongo-3.0.3-py3.4-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
    removing 'build\bdist.win-amd64\egg' (and everything under it)
    Processing pymongo-3.0.3-py3.4-win-amd64.egg
    creating c:\anaconda3\envs\_build\lib\site-packages\pymongo-3.0.3-py3.4-win-amd64.egg
    Extracting pymongo-3.0.3-py3.4-win-amd64.egg to c:\anaconda3\envs\_build\lib\site-packages
    Adding pymongo 3.0.3 to easy-install.pth file

    Installed c:\anaconda3\envs\_build\lib\site-packages\pymongo-3.0.3-py3.4-win-amd64.egg
    Processing dependencies for pymongo==3.0.3
    Finished processing dependencies for pymongo==3.0.3

    C:\Anaconda3\conda-bld\work\pymongo-3.0.3>if errorlevel 1 exit 1
    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda-build/issues

    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
      File "C:\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
        sys.exit(main())
      File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 190, in main
        args_func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 429, in args_func
        args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 384, in execute
        override_channels=args.override_channels, include_recipe=args.include_recipe)
      File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 417, in build
        windows.build(m)
      File "C:\Anaconda3\lib\site-packages\conda_build\windows.py", line 127, in build
        kill_processes()
      File "C:\Anaconda3\lib\site-packages\conda_build\windows.py", line 92, in kill_processes
        for n in psutil.get_pid_list():
    AttributeError: 'module' object has no attribute 'get_pid_list'
    PS C:\Anaconda3\pkg_assembly>

Conda Info Output: 

    PS C:\Anaconda3\pkg_assembly> conda info
    Current conda install:

                 platform : win-64
            conda version : 3.18.1
      conda-build version : 1.17.0
           python version : 3.4.3.final.0
         requests version : 2.7.0
         root environment : C:\Anaconda3  (writable)
      default environment : C:\Anaconda3
         envs directories : C:\Anaconda3\envs
            package cache : C:\Anaconda3\pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/win-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : C:\Users\brian.mcguirk\.condarc
        is foreign system : False

    PS C:\Anaconda3\pkg_assembly>

**Comment by jakirkham** [comment]
I believe this has already been added to the `defaults` channel. So, you should just be able to run `conda install pymongo`.

**Comment by msarahan** [comment]
Furthermore, the error is related to an out-of-date conda-build version.  Please update that and try again.

psutil changed their API, and it messed up a lot of stuff.

**Comment by bmcguirk** [comment]
Works like a charm. Sorry for not closing this sooner.
