### ISSUE TITLE
broken vcvarsall selection logic for legacy python

### ISSUE THREAD

**Issue by rvianello** [conda/conda-build#623]
in version 1.18.0 and on the current tip of the master branch, when searching for the vcvarsall script and trying the Microsoft Visual C++ Compiler for Python 2.7, multiple paths are checked but the 'not_vcvars' variable is never updated, making the selection logic ineffective.

**Comment by JanSchulz** [comment]
See also https://github.com/conda/conda-build/issues/729

**Comment by msarahan** [comment]
Closed by @patricksnape in #861
