### ISSUE TITLE
Build Failure - conda skeleton pypi spur - Winx64 - Python 3.4

### ISSUE THREAD

**Issue by bmcguirk** [conda/conda-build#624]
Yet another build error, unfortunately. This time for [Spur](https://github.com/mwilliamson/spur.py).

PS C:\Anaconda3\pkg_assembly> conda skeleton pypi spur
Warning, the following versions were found for spur
0.3.14
0.3.13
0.3.12
0.3.11
0.3.10
0.3.9
0.3.8
0.3.7
0.3.6
0.3.5
0.3.4
0.3.3
0.3.2
0.3.1
0.3.0
0.2.4
0.2.3
0.2.2
0.2.1
0.2.0
0.1.5
0.1.4
0.1.3
0.1.2
0.1.1
0.1.0
Using 0.3.14
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/s/spur/spur-0.3.14.tar.gz (12 KB) for spur.
Downloading spur
Using cached download
Unpacking spur...
done
working in C:\Users\BRIAN~1.MCG\AppData\Local\Temp\tmp_8d010njconda_skeleton_spur-0.3.14.tar.gz
Fetching package metadata: ......
Solving package specifications: ........
Applying patch: 'C:\\Users\\BRIAN~1.MCG\\AppData\\Local\\Temp\\tmp_8d010njconda_skeleton_spur-0.3.14.tar.gz\\pypi-distutils.patch'
patching file `core.py'
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
patch: **** can't rename `core.py' to `core.py.orig' : File exists
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 272, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 741, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 788, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Anaconda3\lib\site-packages\conda_build\source.py", line 254, in apply_patch
    check_call([patch, ] + patch_args, cwd=src_dir)
  File "C:\Anaconda3\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Anaconda3\\Scripts\\patch.exe', '-p0', '-i', 'C:\\Users\\BRIAN~1.MCG\\AppData\\Local\\Temp\\tmp_8d010njconda_skeleton_spur-0.3.14.tar.gz\\pypi-distutils.patch_unix']' returned non-zero exit status 2

**Comment by bmcguirk** [comment]
Turns out uninstalling `patch` solved this issue for me. Found out via #119 .

**Comment by msarahan** [comment]
I believe these issues are fixed with the patch package, version 2.5.9, build 1. This bundles the GnuWin32 patch executable with a manifest that tells Windows to not require elevation when running patch.exe.

If you have patch.bat in your scripts folder, please remove it. All tracebacks using the proper program should show "patch.exe" not "patch.bat" - and patch.exe should live in Library/bin, not in Scripts/

You have fixed this another way, but just for information purposes, the patch.exe that you seem to have is probably the wrong version, since it is showing up in Scripts.  Please delete it, install the patch package, and try again.
