### ISSUE TITLE
OS X: python.app shebang causes various misbehavior

### ISSUE THREAD

**Issue by minrk** [conda/conda-build#628]
scripts from conda packages have a peculiar shebang on OS X:

    #!/bin/bash $PREFIX/bin/python.app

We have had recent reports of problems on IPython, where changing this shebang causes various problems. So far, we have diagnosed two bugs as being caused by this:

- ipython/ipython#8878: the conda entrypoint clears DYLD_LIBRARY_PATH
- ipython/ipython#8872: resuming backgrounded processes doesn't work

In both cases, circumventing the conda shebang by reverting to the normal `#!$PREFIX/bin/python` and/or launching with `python -m IPython` do not exhibit the problematic behavior.

**Comment by pluskid** [comment]
Same issue here

**Comment by ccordoba12** [comment]
Pinging @ilanschnell and @msarahan. Is there something we can do about this for Anaconda 2.4?

**Comment by jlmaccal** [comment]
Bumping this, as it has caused us problems trying to work with CUDA libraries, which requires setting `DYLD_LIBRARY_PATH`.

**Comment by mjuric** [comment]
@ilanschnell, @msarahan -- it looks like IPython the recipe has `osx_is_app=True` set. I found an [old discussion](https://www.bountysource.com/issues/7188214-changing-the-shebang-line-to-use-python-app) by @asmeurer saying this was done to work around some issues with `qtconsole`. 

Does this rationale still apply? `jupyter` shebang directly points to Python, and things appear to be working as expected.

**Comment by ilanschnell** [comment]
Yes, I just removed the strange shebang from `ipython` (4.1.2) and all still seems to work.

**Comment by ilanschnell** [comment]
New conda packages are available.

**Comment by rhiannonlynne** [comment]
This seems to be broken again with ipython 4.2.0 / conda 4.1.6.
