### ISSUE TITLE
Modified files are omitted from built packages

### ISSUE THREAD

**Issue by dan-blanchard** [conda/conda-build#63]
If you have a package that modifies some file that is part of some other package, this modification is not bundled along with the conda package that gets built.  This is because [build.py](https://github.com/conda/conda-build/blob/master/conda_build/build.py#L240-L276) only includes the difference in the set of files in the prefix before building a package and after building a package.

This may be intentional behavior, but it can be frustrating for things like Perl, where newer versions of core modules sometimes overwrite the included modules.

**Comment by msarahan** [comment]
restated in https://github.com/conda/conda-build/issues/2762 - closing this issue to consolidate there.
