### ISSUE TITLE
Incorrect behavior with numpy 1.10 using --numpy flag

### ISSUE THREAD

**Issue by mariusvniekerk** [conda/conda-build#631]
When building against numpy 1.10 --numpy and CONDA_NPY produce different results

```
CONDA_NPY=1.10 conda build .
```

works

```
CONDA_NPY=110 conda build .
```

fails

```
conda build --numpy=1.10 .
Error: CONDA_NPY must be major.minor, like 1.9, not 110
```

also fails

**Comment by mpharrigan** [comment]
I find that options (1) and (2) above behave the same way, which is broken. Based on my reading of the code, the version string is first stripped of `'.'`s and then a `'.'` is added between each digit:
```python
".".join(str(conda_npy))
```

This makes conda-build look for numpy 1.1.0, which predates conda :)

I haven't tried `--numpy`

**Comment by rmcgibbo** [comment]
This is fixed in the master branch, post 1.18.

**Comment by jakirkham** [comment]
If it was fixed @rmcgibbo, do you mind sharing what fixed it for you?

**Comment by marscher** [comment]
I think he meant the git master of conda-build, since 1.18 is the latest version of it.

**Comment by jakirkham** [comment]
Sure, I was just hoping we could narrow it down to a commit and/or PR that was responsible for the fix. Anyways, it's not a big deal. It just would be nice to have the record for later should it be needed.

**Comment by mpharrigan** [comment]
Looks like #626 is the relevant pr

**Comment by stuarteberg** [comment]
In addition to that PR, one last related issue was handled recently in #660, so I'd say this can be closed.

**Comment by jakirkham** [comment]
This should be closed.
