### ISSUE TITLE
--build-only doesn't do what you would expect, and produces misleading output

### ISSUE THREAD

**Issue by gmarkall** [conda/conda-build#632]
Originally spotted as: https://twitter.com/whitequark/status/652542223444275200

From `conda build --help`:

```
  -b, --build-only      Only run the build, without any post processing or
                        testing. Implies --no-test and --no-anaconda-upload.
```

This at least implies to me that a conda package will be built. Running `conda build --build-only` results in the following output at the end of the build (for a particular package):

```
STOPPING BUILD BEFORE POST: mypkg-2.0a0-py34_69
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/gmarkall/miniconda3/conda-bld/linux-64/mypkg-2.0a0-py34_69.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
```

The file that it tells you to upload, `/home/gmarkall/miniconda3/conda-bld/linux-64/mypkg-2.0a0-py34_69.tar.bz2` does not exist. So it seems as if `--build-only` does not even build a package. I think there are two separate issues:
1. The documentation doesn't explain what `--build-only` does, and it doesn't do what you'd expect from its name.
2. When you use `--build-only`, it should not print out the message telling you to upload the non-existent package.

**Comment by adriendelsalle** [comment]
Anyone could help about this issue?
It seems that no one had a look on it since 4 years.
Thanks!

**Comment by marcelotrevisani** [comment]
I might take a look at it a bit further on the upcoming days. Sorry for the delay, it might happen sometimes :(

**Comment by adriendelsalle** [comment]
Thanks a lot @marcelotrevisani ! There are so many things to deal with.. don't worry!
As I proposed in #1966, the option should probably better named `dry-run`.

**Comment by adriendelsalle** [comment]
ping @marcelotrevisani, did you had the opportunity to have a look on that one please?
Thanks!

**Comment by marcelotrevisani** [comment]
> ping @marcelotrevisani, did you had the opportunity to have a look on that one please?
> Thanks!

Sorry, I had tons of things those past days to deal with. Sometimes I might not respond (because I might forget or might because I didn't see the notification) but feel free to send me a message on gitter or marking me again! Sorry about it!
I'm rescheduling my tasks and this will be on that! Thanks again and sorry about the delay!

**Comment by adriendelsalle** [comment]
Hi @marcelotrevisani, 
Any plan to progress on that?
Do you need a proposition? Has a PR any chance to be merged?
Thanks

**Comment by peetw** [comment]
Can this be re-opened?

We were able to achieve a similar result with the following combination of arguments, but it feels odd that `--build-only` doesn't in fact actually **build** the package...

```
conda build --no-anaconda-upload --no-verify --no-test conda.recipe
```
