### ISSUE TITLE
--numpy and CONDA_NPY seem to be ignored with conda-build 1.18

### ISSUE THREAD

**Issue by seibert** [conda/conda-build#639]
We just noticed that our conda packages are not being built with a specific version of NumPy when we use the `--numpy` flag, or if we use the `CONDA_NPY` environment variable.  They are instead built with whatever the latest NumPy package is for that version of Python.  If we downgrade to conda-build 1.17, the problem goes away.

**Comment by ilanschnell** [comment]
We added the ability to be explicit about whether or not the numpy version should be part of the dependencies in 1.18.0, see https://github.com/conda/conda-build/pull/573

**Comment by groutr** [comment]
should this be reflected in the documentation?

**Comment by ilanschnell** [comment]
yes
