### ISSUE TITLE
conda-build munges run_test.py and breaks `__future__` imports

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#643]
If you add `from __future__ import something` at the top of your `run_test.py`, conda prepends some code to its copy of the file and Python will thus fail with a `SyntaxError: from __future__ imports must occur at the beginning of the file`. See e.g. generated file:

https://gist.github.com/pitrou/6c8c2152ba1a38abeca6

**Comment by msarahan** [comment]
Munging occurs at https://github.com/conda/conda-build/blob/62894e75be02e4d048d6180ce9de250a46cd37fa/conda_build/create_test.py#L53

**Comment by groutr** [comment]
conda build shouldn't be munging run_test.py.  It looks like it is just throwing the test/imports at the top.  That should be run separately.
