### ISSUE TITLE
--numpy flag or CONDA_NPY have no effect

### ISSUE THREAD

**Issue by Juanlu001** [conda/conda-build#648]
I'm trying to force a specific NumPy version but neither `--numpy 1.9` nor `CONDA_NPY=19` have effect: no suffix is added and still downloads NumPy 1.10. I am using the latest version of every package, including `conda-build`.

**Comment by Juanlu001** [comment]
For the record, I'm trying to build this package: https://github.com/Juanlu001/fenics-recipes/blob/f929f3a27e8137a6cd46da33bbb17e36f74c899b/petsc4py/meta.yaml

**Comment by msarahan** [comment]
That recipe needs to pin the numpy version.  See

https://github.com/conda/conda-build/pull/573

**Comment by Juanlu001** [comment]
Fair enough @msarahan, thanks for the pointer. I guess this can be closed.
