### ISSUE TITLE
`bdist_conda` option for generating a recipe instead of building

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#651]
Would allow one to do something similar to what is done with `conda skeleton pypi` except on a local package with `setup.py`. May be a little trick with the source argument, but generally should be doable.

**Comment by groutr** [comment]
Are you suggesting something `python setup.py bdist_conda`?

**Comment by wikiped** [comment]
`python setup.py bdist_conda` sounds like a good option considering that currently there seem to no way (except for manual) to make a skeleton for local source folder and then build it later.

**Comment by jakirkham** [comment]
Yes, sorry, should have been more explicit. Was thinking of using `bdist_conda` to accomplish this.
