### ISSUE TITLE
conda skeleton pypi pkginfo fails

### ISSUE THREAD

**Issue by pbrod** [conda/conda-build#658]
C:\conda_recipes>conda skeleton pypi pkginfo
Warning, the following versions were found for pkginfo
1.2.1
1.2
1.2b1
1.1
1.1b1
1.0
1.0b2
1.0b1
0.9.1
0.9
0.8
0.7
0.6
0.5
0.4.1
0.4
0.3
0.2
0.1.1
0.1
Using 1.2.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/pkginfo/pkginfo-1.2.1.tar.gz (30 KB) for pkginfo.
Downloading pkginfo
Using cached download
Unpacking pkginfo...
done
working in c:\users\pab\appdata\local\temp\tmpclnywhconda_skeleton_pkginfo-1.2.1.tar.gz
Fetching package metadata: ..................
Solving package specifications: .............
The following NEW packages will be INSTALLED:

```
msvc_runtime: 1.0.0-vc9_0   [vc9]
numpy:        1.10.1-py27_0
pip:          7.1.2-py27_0
python:       2.7.10-3
pyyaml:       3.11-py27_2
setuptools:   18.4-py27_0
wheel:        0.26.0-py27_1
```

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Applying patch: 'c:\users\pab\appdata\local\temp\tmpclnywhconda_skeleton_pkginfo-1.2.1.tar.gz\pypi-distutils.patch'
patching file `core.py'
Hunk #1 succeeded at 169 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\python\Anaconda2_3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\python\Anaconda2_3\lib\site-packages\conda_build\main_skeleton.py", line 272, in main
    args_func(args, p)
  File "C:\python\Anaconda2_3\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\python\Anaconda2_3\lib\site-packages\conda_build\main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "C:\python\Anaconda2_3\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\python\Anaconda2_3\lib\site-packages\conda_build\pypi.py", line 527, in get_package_metadata
    d['entry_points'] = INDENT.join([''] + entry_list)
TypeError: sequence item 1: expected string, list found

C:\pab\workspace\pythonxy_updates\conda_recipees>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.18.3
```

  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\python\Anaconda2_3  (writable)
  default environment : C:\python\Anaconda2_3
     envs directories : C:\python\Anaconda2_3\envs
        package cache : C:\python\Anaconda2_3\pkgs
         channel URLs : https://conda.anaconda.org/pbrod/win-64/
                        https://conda.anaconda.org/pbrod/noarch/
                        https://conda.anaconda.org/ioos/win-64/
                        https://conda.anaconda.org/ioos/noarch/
                        https://conda.anaconda.org/prkrekel/win-64/
                        https://conda.anaconda.org/prkrekel/noarch/
                        https://conda.anaconda.org/pypi/win-64/
                        https://conda.anaconda.org/pypi/noarch/
                        https://conda.anaconda.org/qinves/win-64/
                        https://conda.anaconda.org/qinves/noarch/
                        https://conda.anaconda.org/pyzo/win-64/
                        https://conda.anaconda.org/pyzo/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\pab.condarc
    is foreign system : False

**Comment by ianneilmacleod** [comment]
Try running from an administrator command shell.

**Comment by janschulz** [comment]
This is still happening:

```
λ conda skeleton pypi pkginfo --version 1.2.1
Using url https://files.pythonhosted.org/packages/a9/52/f6f41c68625a79bc037d8d75b5a5aa5f525ce2831152be81b5fdb5150175/pkginfo-1.2.1.tar.gz (30 KB) for pkginfo.
Downloading pkginfo
Using cached download
Unpacking pkginfo...
done
working in C:\Users\jschulz\AppData\Local\Temp\tmpn07w75p7conda_skeleton_pkginfo-1.2.1.tar.gz
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..................
Solving package specifications: .........

Applying patch: 'C:\\Users\\jschulz\\AppData\\Local\\Temp\\tmpn07w75p7conda_skeleton_pkginfo-1.2.1.tar.gz\\pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_skeleton.py", line 300, in main

    args_func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_build.py", line 373, in args_func
    args.func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_skeleton.py", line 315, in execute
    pypi.main(args, parser)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\pypi.py", line 353, in main
    get_package_metadata(args, package, d, data)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\pypi.py", line 534, in get_package_metadata
    d['entry_points'] = INDENT.join([''] + entry_list)
TypeError: sequence item 1: expected str instance, list found
```

```
λ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.6
  conda-build version : 1.20.3
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : C:\portabel\miniconda  (writable)
  default environment : C:\portabel\miniconda
     envs directories : C:\portabel\miniconda\envs
        package cache : C:\portabel\miniconda\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/ioos/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/ioos/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/janschulz/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/janschulz/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/r/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/krisvanneste/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/krisvanneste/noarch/
                        https://conda.anaconda.org/janschulz/win-64/
                        https://conda.anaconda.org/janschulz/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\jschulz\.condarc
    is foreign system : False
```
