### ISSUE TITLE
PY3K environment variable not set during build

### ISSUE THREAD

**Issue by zivy** [conda/conda-build#669]
my environment:
osx 10.10.5 
bash

When attempting to build a recipe against Python 3.4 ( following these instructions: Optional - Build for a different Python version http://conda.pydata.org/docs/build_tutorials/pkgs.html):

conda build --python 3.4 conda-problem

I expect the PY3K environment variable to be set to 1. It is not.

If I run the following commandline:

CONDA_PY=34 conda build conda-problem

The PY3K variable is set to 1 as expected (and the build is against Python 3.4).

**Comment by msarahan** [comment]
Does it have anything to do with this: https://github.com/conda/conda-build/issues/103, or totally unrelated

If unrelated, looks like a bug to me.  We will investigate.  If you can post your recipe, that might be helpful, in case we can't immediately reproduce with our recipes.

**Comment by zivy** [comment]
I do not think this is related to that issue as the recipe I am using requires python. This is the [simpleitk recipe] (https://github.com/conda/conda-recipes/tree/master/simpleitk). As I can't attach files (requires write permission to repo) I am pasting a version of the meta.yaml and build.sh scripts which illustrate the problem without compiling the whole toolkit:

build.sh:

#!/bin/bash

CORES=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu || 1)
if [ `uname` == Darwin ]; then
    SO_EXT='dylib'
else
    SO_EXT='so'
fi

BUILD_DIR=${SRC_DIR}/build
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}

MY_PY_VER=${PY_VER}
if [ $PY3K -eq "1" ]; then
    MY_PY_VER="${MY_PY_VER}m"
fi

echo '*********'$PY3K'**********************'


meta. yaml:

package:
  name: simpleitk
  version: "0.9.1"

source:
  git_url: http://itk.org/SimpleITK.git
  git_tag:  v0.9.1

requirements:
  build:
    - python
    - cmake    >=2.8.11       # [not win]
    - libtiff  4.0.* # [not win]
    - libpng   1.6.* # [not win]
    - jpeg     8*    # [not win]
    - zlib     1.* # [not win]
    - setuptools
  run:
    - python
    - libtiff  4.0.* # [not win]
    - libpng   1.6.* # [not win]
    - jpeg     8*    # [not win]
    - zlib     1.* # [not win]

about:
  home: http::/www.simpleitk.org
  license: Apache 2.0
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation
