### ISSUE TITLE
Recipe metadata.yaml should include a "maintainer" field

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda-build#670]
Currently, a number of community-driven conda recipes and package collections are being maintained, such as [omnia-md/conda-recipes](https://github.com/omnia-md/conda-recipes), [ioos/conda-recipes](https://github.com/ioos/conda-recipes), [conda-forge](https://github.com/conda-forge), [conda-recipes-scitools](https://github.com/SciTools/conda-recipes-scitools), [bioconda/recipes](https://github.com/bioconda/recipes), and I presume others, which is pretty cool.

Based on my experience with these collections, I think one thing that could really help is if the recipe metadata.yaml file were capable of having (and encouraged to have, through conda skeleton and the docs) a "maintainer" field. As they mature, having the capability of storing a maintainer field would be useful for the community repos to help keep track of ownership and responsibilities for upkeep and maintenance.

**Comment by msarahan** [comment]
Huge +1 on this.  I'll try to see where it might fit - this might require a pretty broad set of changes across anaconda.org and all that to properly support this, but this is an excellent idea.
