### ISSUE TITLE
Check that test/requires packages are available before building

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda-build#671]
I have some packages whose builds fail on certain platforms because packages required for the tests are not available. Currently, the failure is only reported after the package has been completely built. If possible, it would be nice to check if the test dependencies are satisfiable before running the build.

**Comment by msarahan** [comment]
+1 - have encountered this a fair bit myself.  I will investigate.

**Comment by marscher** [comment]
Are there any updates on this issue? My package has a ton of dependencies and it is really a big hassle to figure this out manually

**Comment by marscher** [comment]
At least a proper exception would be nice

**Comment by msarahan** [comment]
I believe we added a proper exception in https://github.com/conda/conda-build/commit/ffde7b7eec94941b4124555cff2a0e1d6f129305

Still, it would be much nicer to check the satisfiability of the test env at the same time that we check the satisfiability of the build env, to fail earlier.  @mandeep let's take a look at this.
