### ISSUE TITLE
How to uninstall conda on mac?

### ISSUE THREAD

**Issue by machinelliummavericks** [conda/conda-build#672]

**Comment by ericdill** [comment]
See here: http://docs.continuum.io/anaconda/install#os-x-uninstall

You also might want to check your `~/.bash_profile` (or whatever shell you are using) for references to anaconda or miniconda and remove those additions to the path variable.
Something like this:
```
# add miniconda to path
export PATH=/Users/edill/mc/bin:$PATH
```
