### ISSUE TITLE
Build error using conda skeleton (win64)

### ISSUE THREAD

**Issue by heathmills** [conda/conda-build#673]
C:\Users\heath>conda skeleton pypi gitdb
Warning, the following versions were found for gitdb
0.6.4
0.6.3
0.6.2
0.6.1
0.6.0
0.5.4
0.5.3
0.5.2
0.5.1
0.5.0
Using 0.6.4
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/g/gitdb/gitdb-0.6.4.tar.gz (391 KB) for gitd.
Downloading gitdb
Using cached download
Unpacking gitdb...
done
working in c:\users\heath\appdata\local\temp\tmptrfkuiconda_skeleton_gitdb-0.6.4.tar.gz
Fetching package metadata: ..........
Solving package specifications: ...............
Applying patch: 'c:\\users\\heath\\appdata\\local\\temp\\tmptrfkuiconda_skeleton_gitdb-0.6.4.tr.gz\\pypi-distutils.patch'
patching file `core.py'
Hunk #1 succeeded at 169 with fuzz 2 (offset 2 lines).
patch: **** can't rename `core.py' to `core.py.orig' : File exists
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda_build\main_skeleton.py", line 272, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda_build\main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 741, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 788, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Anaconda2\lib\site-packages\conda_build\source.py", line 253, in apply_patch
    check_call([patch, ] + patch_args, cwd=src_dir)
  File "C:\Anaconda2\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Anaconda2\\Scripts\\patch.exe', '-p0', '-i', 'c:\\users\\heath\\appdata\\local\\temp\\tmptrfkuiconda_skeleton_gitdb-0.6.4.tar.gz\\pypi-distutils.patch_unix']' returned non-zero exit status 2

$ conda info
Current conda install:

             platform : win-64
        conda version : 3.18.5
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/athenstiger/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/athenstiger/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/r/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\heath\.condarc
    is foreign system : False

**Comment by msarahan** [comment]
I believe these issues are fixed with the patch package, version 2.5.9, build 1. This bundles the GnuWin32 patch executable with a manifest that tells Windows to not require elevation when running patch.exe.

If you have patch.bat in your scripts folder, please remove it. All tracebacks using the proper program should show "patch.exe" not "patch.bat" - and patch.exe should live in Library/bin, not in Scripts/

The patch.exe that you seem to have is probably the wrong version, since it is showing up in Scripts.  Please delete it, install the patch package, and try again.

Closing this issue. If there are further issues with patch, please post new issues with tracebacks.
