### ISSUE TITLE
build/script unused on windows

### ISSUE THREAD

**Issue by pelson** [conda/conda-build#682]
The build/script section is not used when building a recipe on Windows.

**Comment by jakirkham** [comment]
See this PR ( https://github.com/conda/conda-build/pull/620 ) for a potential fix.

**Comment by msarahan** [comment]
fixed by https://github.com/conda/conda-build/pull/799 - closing.

**Comment by jakirkham** [comment]
Yep, must have gotten the wrong link. Thanks for getting this fixed.

**Comment by pelson** [comment]
Thanks to @almarklein for solving this one! 🎉
