### ISSUE TITLE
Build fail on mac with conda-build 0.18.2

### ISSUE THREAD

**Issue by joelvbernier** [conda/conda-build#684]
<old-iMac:hexrd joelvbernier$ conda build conda.recipe/
Removing old build environment
Removing old work directory
BUILD START: hexrd-0.3.1-np19py27_8
Fetching package metadata: ..........
Solving package specifications: ...............
The following NEW packages will be INSTALLED:

    numpy:      1.9.3-py27_0  defaults
    openssl:    1.0.2d-0      defaults
    pip:        7.1.2-py27_0  defaults
    python:     2.7.10-2      defaults
    readline:   6.2-2         defaults
    setuptools: 18.4-py27_0   defaults
    sqlite:     3.8.4.1-1     defaults
    tk:         8.5.18-0      defaults
    wheel:      0.26.0-py27_1 defaults
    zlib:       1.2.8-0       defaults

Linking packages ...
[      COMPLETE      ]|######################################################################################################################################################| 100%
Removing old work directory
checkout: u'master'
==> git log -n1 <==

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/joelvbernier/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/joelvbernier/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/joelvbernier/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/joelvbernier/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/joelvbernier/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 392, in build
    source.provide(m.path, m.get_section('source'))
  File "/Users/joelvbernier/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 266, in provide
    git_source(meta, recipe_dir)
  File "/Users/joelvbernier/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 135, in git_source
    git_info()
  File "/Users/joelvbernier/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 160, in git_info
    print(stdout + u'\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 165: ordinal not in range(128)
old-iMac:hexrd joelvbernier$ git --version
git version 2.4.9 (Apple Git-60)
old-iMac:hexrd joelvbernier$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.6
  conda-build version : 1.18.2
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /Users/joelvbernier/anaconda  (writable)
  default environment : /Users/joelvbernier/anaconda
     envs directories : /Users/joelvbernier/anaconda/envs
        package cache : /Users/joelvbernier/anaconda/pkgs
         channel URLs : https://conda.binstar.org/joelvbernier/osx-64/
                        https://conda.binstar.org/joelvbernier/noarch/
                        https://conda.binstar.org/praxes/osx-64/
                        https://conda.binstar.org/praxes/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/joelvbernier/.condarc
    is foreign system : False

old-iMac:hexrd joelvbernier$ 
>

**Comment by stuarteberg** [comment]
This error was discussed in #170. See [the end of the thread](https://github.com/conda/conda-build/issues/170#issuecomment-62040750).  In that thread, the user found a problem with his own terminal settings, which resolved his problem.

**Comment by stuarteberg** [comment]
Update: OK, I ran into this issue myself today, on both mac and linux.

This bug seems to be caused by #621.  Apparently that PR introduced problems with reading git repo information.  When I revert that PR in my local copy of conda, the bug goes away.
