### ISSUE TITLE
turn off pyc compilation?

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda-build#686]
Is there a way to do this? why?! you may ask?, well

we build conda packages to deploy jobs
we build fat packages (meaning, they contain lots of stuff, which might not be used for one thing or the other)
So the pyc compilation process actually adds alot of overhead to deploying jobs, also, pacakge builds break if we have invalid python in the package

thanks

**Comment by stuarteberg** [comment]
From what I can tell, there's no way to do this right now.  Should be easy enough to add a [field](https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L254) to `meta.yaml`, and then conditionally skip the [`compile_missing_pyc`](https://github.com/conda/conda-build/blob/master/conda_build/post.py#L151) step.

I would think this would be an easy PR to review, but I suppose you would also be expected to update the docs before it could be accepted.

**Comment by hhuuggoo** [comment]
ok thanks I'll take care of this

**Comment by jakirkham** [comment]
Maybe instead of adding some new feature to `meta.yaml` the existing python environment variable [`PYTHONDONTWRITEBYTECODE`]( https://docs.python.org/2/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE ) can be used.

**Comment by jakirkham** [comment]
It turns out there is more to the story as conda is doing its own additional compilation internally, which seems a bit counterintuitive IMHO. I wonder if it is worthwhile to just permanently remove this internal compilation step. It seems to cause problems with complex packages like Django and Pylint (and friends) that template Python files. This will allow users to actually control compilation in their recipes the way Python intended.

**Comment by groutr** [comment]
@jakirkham I'm +1 on removing the compilation of pyc files entirely.  There is no need to distribute them in the package.  They can be compiled just as easily at install time (because write permissions are guaranteed).

**Comment by pelson** [comment]
> They can be compiled just as easily at install time

True. I know RPMs do pyc compilation at build time, and they even hardlink pyc and pyo files when they are the same. The advantage of doing the compilation at build time is that environments can share (through hard links) the pyc files, whereas if they are compiled at install time, that adds an extra complexity to the currently trivial linking step.

**Comment by jakirkham** [comment]
Do you have an example of this @pelson?

**Comment by jakirkham** [comment]
Also, should add that this variable `sys.dont_write_bytecode` does the same as the aforementioned environment variable.

**Comment by jakirkham** [comment]
On a more general note, `conda` has grown to support many languages for building and install (I saw Lua support being added recently). Personally, I'd like to avoid cluttering `meta.yaml` with more language specific stuff than necessary. I would prefer to follow the "one right way to do things mantra" and use  Python's already supported mechanism for this behavior (incorporating it into our logic, if needed) or simply disable `.pyc` generation given the various problems it has caused.

**Comment by kalefranz** [comment]
I agree that we can probably avoid adding anything additional to `meta.yaml`.  I'd think that `PYTHONDONTWRITEBYTECODE` should suffice.

Can someone with more history here, maybe @ilanschnell or @stuarteberg, talk to the purpose of [`compile_missing_pyc`](https://github.com/conda/conda-build/blob/master/conda_build/post.py#L130)?

`pyc` files exist for a reason, and in production environments, it's likely that they won't be able to be written by the running process.  They either need to be built at build time or at install time.  For conda packages with a python version attached, they should be built *appropriately* at build time.  For noarch python conda packages, they need to be built at install time. (Correct me if I'm wrong, but I think py3 bytecode has differences from py2 bytecode.)

**Comment by jakirkham** [comment]
That function has been there for as long as this code has been public AFAICT. Here it is in the second commit of the repo, first commit with code ( https://github.com/conda/conda-build/commit/fe7f773010f4c8c200298c83a4164ca404626d52#diff-60400bbbdb51124a0a8a06ca17ecec5cR106 ).

**Comment by jakirkham** [comment]
Also, you are correct on pyc files. Though they can differ between minor Python versions too. There is good background on how this work in this PEP ( https://www.python.org/dev/peps/pep-3147/ ).

**Comment by ilanschnell** [comment]
`compile_missing_pyc` has actually even been around longer.  The first public version of conda-build was part of conda itself, and was added in June 2013 in conda version 1.7.  That first conda-build had `compile_missing_pyc` already.  It wasn't till January 2014 that conda-build became its own project.

**Comment by jakirkham** [comment]
If we replace [this call]( https://github.com/conda/conda-build/blame/4fa519d4c448c2edd81d7355e859c9e25755d35a/conda_build/utils.py#L56 ) with `Popen`, we can at least pass an environment variable to disable compilation optionally, which would solve the original issue.

**Comment by jakirkham** [comment]
Any thoughts on this one? Would be really nice to come to a solution here.

**Comment by mdengler** [comment]
:+1:

**Comment by msarahan** [comment]
As of #1169 you can add files to ignore to your meta.yaml.  This will be in the next release, within the next couple of days.

**Comment by mdengler** [comment]
@msarahan #1169 achieves the intent of this issue (#686) but in a different way than discussed in this issue.  Would you accept a patch that changed [conda_build.post.compile_missing_pyc's first few lines](https://github.com/conda/conda-build/blob/d9ae8921bb4b05579e0862b02dc4d161fad646f1/conda_build/post.py#L193) to something like:

    if (not os.path.isfile(python_exe)) or os.environ.get("PYTHONDONTWRITEBYTECODE"):
        return
   
...?  As well as @jakirkham 's suggestion about Popen, if necessary.

I think the pros and cons are:

Pro.1: less meta.yaml language-specific intrusion
Pro.2: the standard Python way to inhibit byte code compilation
Con.1: if someone wants to control the python executable that's doing the compilation to not write bytecode, but still have it compile .pyc files, they will have to use `python -B` as the compilation command, since setting `PYTHONDONTWRITEBYTECODE` would now not get them what they want.


PS - I totally appreciate that there are many, good reasons to compile .pycs/.pyos at package build times.  This request is about how that process is disabled, and I think above there are a number of reasons why PYTHONDONTWRITEBYTECODE is a useful and conventional way to do it.

**Comment by bilderbuchi** [comment]
I just ran into this issue. I want to ship cookiecutter/jinja template files with a conda package, and get syntaxt errors (of course) during the byte-compiling stage of `python setup.py bdist_conda`.

So far I have not needed a recipe, as my setup.py is sufficient, and I want to keep it that way (to avoid duplicating info like version, dependencies, etc. Unfortunately, `python setup.py bdist_conda` does not observe `sys.dont_write_bytecode` like `python setup.py bdist` does. 

Is there a way do supply this information to `python setup.py bdist_conda`? The [setup options](https://conda.io/docs/user-guide/tasks/build-packages/build-without-recipe.html#setup-options) documentation does not indicate a way to supply generic build config, would it be feasible to add that?

**Comment by msarahan** [comment]
Sure, it's feasible to add that.  Making it observe sys.dont_write_bytecode seems like the best fix.  That code is at https://github.com/conda/conda-build/blob/master/bdist_conda.py - PRs welcome.

**Comment by msarahan** [comment]
@mdengler I'm terribly sorry I missed your message here ages ago.  PRs for what you propose are reasonable, and would be welcome.
