### ISSUE TITLE
rewrite_file_with_new_prefix case insensitive str replacement on Windows

### ISSUE THREAD

**Issue by gabrielcnr** [conda/conda-build#687]
For some reason when my scripts with entry points are written on the _build environment they have the prefix as `#!c:\dev\bin\Anaconda\envs\_build\python.exe` (note Anaconda starting with uppercase A).

This makes the function `rewrite_file_with_new_prefix` not do its job properly on Windows because it does a basic string replace looking for `c:\dev\bin\anaconda\envs\_build` (note anaconda here is all lowercase).

I think we should use regex to make that replacement on Windows, since it's OS paths are not case sensitive.

![image](https://cloud.githubusercontent.com/assets/209902/11394405/c25a823e-935c-11e5-99e9-d9530c4e031c.png)

**Comment by gabrielcnr** [comment]
This is how I patched here locally. Please let me know if you'd like me to submit a Pull Request.

```python

def rewrite_file_with_new_prefix(path, data, old_prefix, new_prefix):
    if sys.platform == 'win32':
        old_prefix = old_prefix.replace('\\', '\\\\')
        data = re.sub(old_prefix, new_prefix, data, flags=re.IGNORECASE)
    else:
        # Old and new prefix should be bytes
        data = data.replace(old_prefix, new_prefix)

    st = os.stat(path)
    # Save as
    with open(path, 'wb') as fo:
        fo.write(data)
    os.chmod(path, stat.S_IMODE(st.st_mode) | stat.S_IWUSR) # chmod u+w
    return data
```

**Comment by groutr** [comment]
Submitting a PR would be welcome and then we can review it from there.
