### ISSUE TITLE
CONDA_BLD_PATH is resolved when it is a symlink

### ISSUE THREAD

**Issue by gqmelo** [conda/conda-build#689]
I'm trying to make sure that debug packages does not contain source paths with the username.
So I set CONDA_BLD_PATH to /usr/local/conda-bld

But as conda-bld can take too much disk space I created /usr/local/conda-bld as a symlink to /home/guilherme/miniconda/conda-bld, which is normally on a larger partition.

Doing this on build.sh:

```
echo $PWD
```

The output is:

```
source tree in: /usr/local/conda-bld/work/bison-3.0.4
+ echo /home/guilherme/miniconda/conda-bld/work/bison-3.0.4
/home/guilherme/miniconda/conda-bld/work/bison-3.0.4
```
The symlink is being resolved when running the commands. This makes the compiled objs contain the path with my home.

Is this an expected behaviour?

**Comment by ilanschnell** [comment]
Nothing special is done the the source code of conda-build regarding symbolic links.  The behavior your seeing might also be specific to the `bash` shell you are running.
