### ISSUE TITLE
--use-local or --offline mode required

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-build#695]
Building conda packages should have the option of `--use-local` or the equivalent of `--offline` so the package build will rely exclusively on the local package cache.  AFAICT at the moment this is not possible.

**Comment by pelson** [comment]
> AFAICT at the moment this is not possible.

It is possible to just change your condarc's channels. Also, it is possible to do:

```
conda build ... -c file://my_local_channel --override-channels
```

Of course, none of this is automatic to filter all of the ```http``` channels as ```--offline``` does.

**Comment by phumke** [comment]
+1 to this.

Looping in #282 since it is a related request.

**Comment by ezyang** [comment]
Note that if you have a local build of a package, conda-build will automatically pick it up (so you don't need `--use-local` in the traditional `conda install` sense)

**Comment by aldanor** [comment]
It would be really handy to have an `--offline` version at the very least; not being able to run conda build when disconnected (although all the dependencies are already cached and/or are locally built anyways) is pretty sad.
