### ISSUE TITLE
"--perl" option mis-parses multi-digit versions

### ISSUE THREAD

**Issue by chenghlee** [conda/conda-build#696]
The `--perl` option for `conda build` separates each digit in a version string with a ".", instead of keeping multi-digit numbers together:
```bash
$ conda build --perl 5.22.0 perl-try-tiny
Removing old build environment
Removing old work directory
BUILD START: perl-try-tiny-0.22-pl5.2.2.0_1
# "conda build" now attempts to find and/or build a Perl 5.2.2.0 package,
# instead of using an existing Perl 5.22.0 package.
```

This is a major problem as the recent releases of Perl 5 all have double-digit minor numbers. Note that setting the `CONDA_PERL` environment variable works around this problem:

```bash
$ CONDA_PERL="5.22.0" conda build perl-try-tiny
Removing old build environment
Removing old work directory
BUILD START: perl-try-tiny-0.22-pl5.22.0_1
```

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.6
  conda-build version : 1.18.2
```
This problem has also been observed with version 1.18.0 of conda-build.

**Comment by stuarteberg** [comment]
Implemented #700, which fixes this issue.

Details: The dots were getting stripped when `---perl` was originally parsed and copied into `config.CONDA_PERL`, which later caused *too many* dots to be reinserted via [`handle_config_version()`][1].

[1]: https://github.com/conda/conda-build/blob/03c75c0597370c5ef1b0356c16f3beab1f417413/conda_build/metadata.py#L370
