### ISSUE TITLE
Add a --anaconda-user option 

### ISSUE THREAD

**Issue by ivoflipse** [conda/conda-build#702]
We're using an organization account on Anaconda Cloud to manage all our packages. But when building packages I constantly have to provide `--no-anaconda-upload` and then separately call  `anaconda upload <pkg_name> --u <org_name>`. This get's especially annoying when I'm building packages for all Python versions.

While I'm a member of the organization and can upload to the organization, I can't use the regular anaconda upload feature, because it would upload it to my account, not that of my organization.

So I'd like more control over where the package get's uploaded, possibly by providing the anaconda-user as an option or perhaps it should parse --channel as <user>/<channel>

**Comment by Korijn** [comment]
:+1:

Maybe it should be part of conda config?

Disclaimer: I'm @ivoflipse's colleague.

**Comment by stuarteberg** [comment]
+1 -- I have the same problem and would appreciate such a feature.  Disclaimer: I'm **not** one of @ivoflipse's colleagues. :-)

**Comment by groutr** [comment]
Seems like a reasonable thing to do.  I'm think I'm in agreement with @Korijn in that "permanent" command options to conda-build should reside in a config file somewhere.
