### ISSUE TITLE
[Feature Request] Add an option to write build scripts in Python

### ISSUE THREAD

**Issue by frol** [conda/conda-build#706]
I do understand that I can write `build.sh` and `bld.bat` where I would call my Python build script (just like it is usually done with `setup.py`), but it adds at least 2 unnecessary `exec`s ((1) - conda-build running `build.sh`/`bld.bat`, and (2) - `build.sh`/`bld.bat` running `python setup.py install` or "my python build script").

Calling Python functions from Python would save a couple of `exec`/`fork`s and would make writing build scripts nicer. Providing simple wrappers around `subprocess.Popen`, and other common `sh` functionality (e.g. `rm -rf`, `ls`) will make build scripts clean and simple, without need to write `sh` and `bat` separately.

NOTE: I don't suggest to implement all those nice utils from scratch. There are already a couple of projects out there:

* Python 3.4 introduced `pathlib` module: https://docs.python.org/3/library/pathlib.html
* PyFilesystem (it might be an overkill): http://docs.pyfilesystem.org/en/latest/introduction.html
* python-fs (it might be "too elementary"): https://github.com/chaosmail/python-fs
* PyInvoke (it has a nice `run` command): http://www.pyinvoke.org/
* python-sh (it might not work on Windows, but it might be still useful): https://amoffat.github.io/sh/

NOTE: I have contemplated this feature while reading the discussion about OpenBSD support here #705, where was suggested to downgrade `bash` to `sh`.

**Comment by frol** [comment]
I would like to invite @ccordoba12, @ilanschnell, @msarahan, @stuarteberg, @NewbiZ to this discussion. I'm sorry, if this topic was already discussed, I could find it.

**Comment by ilanschnell** [comment]
Thanks for your suggestion.  From my experience, Python is not a language to write build scripts in.  Tasks which are simple in bash are often rather cumbersome in Python.  I'm not saying that Python is a bad language, it just hasn't been designed for this particular use case.

I'm not totally against your suggestion.  However, calling just Python functions (without adding subprocess) seems problematic, mostly because then all your importable Python build tools need to be installed into the root environment where (conda-build) is living.  I don't see speed as a big problem.
Maybe having something along the lines:
```
build_py = join(src_dir, 'build.py')
if exists(build_py):
    subprocess.call([join(build_prefix, 'bin', 'python'), build_py], env=env, cwd=src_dir)
else:
    # whatever was already done, i.e. call bash build.sh (or bld.bat)
```
This way, you would only have one additional subprocess (instead of two).  Also, you can easily access all the build environment variables (which conda-build sets up) inside your Python build script.

**Comment by frol** [comment]
> Thanks for your suggestion. From my experience, Python is not a language to write build scripts in. Tasks which are simple in bash are often rather cumbersome in Python. I'm not saying that Python is a bad language, it just hasn't been designed for this particular use case.

I though like this also. However, recently, we (in the company where I work) gave up on trying to use `bash` scripts as our internal build scripts due to the fact that we always hit `sed`/`awk`/`grep` differences on Linux, OS X, and Windows (we used bash there also). Once I switched to PyInvoke, our build process became clean, cross-platform (without quirks), and maintainable. I don't really see a big issue in writing build scripts in Python. Lets see an example of how a bash build script of a regular `configure` + `make` + `make install` can be reimplemented:

Bash:
```bash
#!/bin/bash

./configure --prefix="$PREFIX"

make
make install
```

Python:
```Python
def build(context):
    context.build_utils.configure("--prefix=%s" % context.PREFIX)

    context.build_utils.make()
    context.build_utils.make("install")
```

NOTE: `--prefix` can be even automatically implemented in `context.build_utils.configure`.

IMHO, Python code looks fine. If we assume that there is no `context.build_utils`, or there is no support for `./configure`, `make` (for the sake of an example), then we can write the following code:

```Python
def build(context):
    context.run("./configure", "--prefix=%s" % context.PREFIX)

    context.run("make")
    context.run("make", "install")
```

> However, calling just Python functions (without adding subprocess) seems problematic, mostly because then all your importable Python build tools need to be installed into the root environment where (conda-build) is living.

You can update `sys.path`, but I agree that it may turn-out to be an overkill. Yet it is not impossible, and even not very hard to implement, but it may introduce something unexpected.

**Comment by ilanschnell** [comment]
You don't have to convince me that in some cases Python might be OK to use (although I find the bash code in your example shorter and more readable).  Like I said, I'm not totally against this, but would like help find a clean solution.  I just commented on https://github.com/conda/conda-build/pull/705, and maybe something like (in the `meta.yaml`):
```
build:
  shell_cmd: python
  build_script: build.py
```
would solve your problem (as well as https://github.com/conda/conda-build/pull/705) at once.

**Comment by frol** [comment]
@ilanschnell I'm not trying to convince you; I've just clarified my point and provided some examples. I'm fine with `bash`, but I have a hard time with `bat` and I think Python can make build scripts better maintainable and also make adding new platforms easier (if all recipes get moved to Python instead of `bash`+`bat`, though I don't see such a massive work done any time soon, but it might be a stranegy for the future).

**Comment by NewbiZ** [comment]
Guys, there are 2 things to differentiate here:
- What `conda-build` relies on
- What each and every recipe rely on

Currently both are tied together, since `conda-build` decides the interpreter used for the recipes. If you want more freedom, then enforce the executable mode on `build.sh` and let people choose their interpreter.

This way `conda-build` will be portable on any unix flavor, and it will be the recipe responsibility to describe what is needed to build. For instance, you can state on the `conda-recipes` repository that bash is required.

All I need for portability is that `conda-build` is free of hardcoded shell path.

**Comment by ilanschnell** [comment]
Having something like:
```
build:
  shell_cmd: /bin/sh
```
would also make conda-build free of hard coded paths (without breaking existing recipes).  In addition, you could have a selector (depending on the system you are on).  For example:
```
build:
  shell_cmd: /bin/sh       [bsd]
```

**Comment by frol** [comment]
@NewbiZ Having shebang in a `build.sh` script doesn't look correct when you would like to write a build script in Python.

@ilanschnell I don't see much point in `shell_cmd` as there is already a `script` option there (at least [the documentation metions it](http://conda.pydata.org/docs/building/meta-yaml.html#script)):

```yaml
build:
  script: python setup.py install
```

**Comment by NewbiZ** [comment]
> @NewbiZ Having shebang in a build.sh script doesn't look correct when you would like to write a build script in Python.

What do you mean?

    #!/usr/bin/env python
    print "Hello from python"

Shebangs were _made_ to do that...

**Comment by frol** [comment]
@NewbiZ shebangs is made, but it IS confusing to write Python code in a file with a `.sh` extension.

**Comment by ilanschnell** [comment]
@frol I didn't realize that there is already a `build/script` option.  Since that is the case, doesn't that already solve the problem?

**Comment by frol** [comment]
@ilanschnell I don't have a problem, actually. My original proposition was to make Python build scripts first citizen and to advertize this way of build script writing.

**Comment by groutr** [comment]
The `build/script` is pretty cumbersome if your build step is more than a single line.

**Comment by msarahan** [comment]
I think that's fine: you just have arbitrary Python commands in some separate script, shipped with your recipe.  Sort of how bld.bat and build.sh work, but more explicit: you have to specify what that file is.  You have the opportunity to specify other stuff, though: perhaps Jinja2 output?

**Comment by ilanschnell** [comment]
@groutr Yes, `build/script` is cumbersome if it is more than a single line.  This is why `build.sh` is normally used.  I was never an advocate of `build/script`, and never use it myself, even if the script *is* only a single line.

**Comment by jakirkham** [comment]
Maybe I don't get it, but I don't this is a problem that needs to be solved.

It seem that if you want a build a recipe using Python or anything else for that matter, one simply can create some very basic `bld.bat` and `build.sh` that calls your Python build script. I agree with @ilanschnell that Python isn't a great build language. Anyone who has worked with `setup.py` in the ugly cases that `conda` solves knows this.

As for the weird corner cases of `bash` and `sh`, maybe the better strategy here is to make a breaking change that does not launch the build scripts with `bash`, but simply runs them as executables. To do this, I think a warning should be dropped in that this change is expected in the next minor release of this and if no one complains or all complaints are resolved we switch. This should allow one to use the shebang as intended. Probably most people are writing their `build.sh` with this in mind anyways.
