### ISSUE TITLE
Where did `GIT_DESCRIBE_HASH` go?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#708]
So there use to be `GIT_DESCRIBE_HASH`. Is that just gone? I seem unable to find it in the codebase and it is now just an empty string in `build.sh`.

**Comment by stuarteberg** [comment]
>there use to be `GIT_DESCRIBE_HASH`. Is that just gone?

Hmm, it does seem to be broken in the current release of `conda-build` (1.18.2), but it is fully functional in the latest version of the conda-build master branch.  (Not sure what the difference is, but I don't care.)  So, it will be fixed again when conda-build 1.18.3 is released.

>I seem unable to find it in the codebase and it is now just an empty string in `build.sh`.

FWIW, That variable is assigned in [environ.py][1].

[1]: https://github.com/conda/conda-build/blob/093a648c3e40995554c72b6513d630356950cfc7/conda_build/environ.py#L50

**Comment by jakirkham** [comment]
Thanks for that point @stuarteberg. When I played around with `git blame` I found the cause was due to this ( https://github.com/conda/conda-build/pull/621 ). So, I guess I have fixed this issue by reverting it ( https://github.com/conda/conda-build/pull/694 ).

**Comment by jakirkham** [comment]
Fixed by ( https://github.com/conda/conda-build/pull/694 ).
