### ISSUE TITLE
Conda convert misses some files

### ISSUE THREAD

**Issue by gomyhr** [conda/conda-build#712]
When running "conda convert <package> -p win-64" on linux-64, one of my entry-points were missing in the windows-package. It turns out that the problematic code line is

```
files = files.replace(oldpath, newpath)
```

in `conda-build/convert.py`where files is a string containing the whole info/files file. When I have two entry points (scripts) where one is a the first part of the other, e.g. `bin/foo` and `bin/foo-bar`, the latter may be converted to Scripts/foo-script.py-bar in the same round that the first is converted to Scripts/foo-script.py (this only happens if bin/foo comes before bin/foo-bar). This makes the wrong file name end up in info/files, and therefore linking of that file does not work.

A minimal fix is probably to add a newline to each of the strings in the call to replace(). I have suggested a slightly more elaborate fix at https://github.com/gomyhr/conda-build/commit/a9e987e79cfb3f02918ca0b5b2ac1cd5cb29216e, where files is a list of strings (one per line) and is then converted back to a string once the comparison is done. The large string is anyway converted to a list, sorted and converted to a string again, so this only does the conversion to list earlier in order to simplify the manipulation. At the same time, it prints a warning if the file name it tries to replace is not present in the file (which I guess means that the package is corrupt). Feel free to use all or parts of that commit to fix the issue, or to fix it in an entirely different manner.

**Comment by groutr** [comment]
Thanks for the report and suggestion.  We will investigate this further.

**Comment by gomyhr** [comment]
This seems to have been fixed with commit dd04ea90b1f740a928b7cc8304c847910efa2c47

**Comment by msarahan** [comment]
Thanks for following up on this!

**Comment by gomyhr** [comment]
It turns out that the bug was not fixed, only that the consequences changed. The bug in generation of info/files previously meant that the files were not copied into the package. Now, the files are generated correctly, but info/files is still wrong, making the converted packages uninstallable.
I have submitted PR #1609 to change a test so that it will detect this issue, along with a fix.

**Comment by gomyhr** [comment]
Fixed in PR #1609.
