### ISSUE TITLE
conda-build tutorial provides incorrect instructions for finding recipie

### ISSUE THREAD

**Issue by cswarth** [conda/conda-build#716]
The tutorial "Building conda packages from scratch" provides incorrect instructions to find an existing recipe.

http://conda.pydata.org/docs/build_tutorials/pkgs2.html#edit-a-similar-conda-recipe

> In your browser, go to https://github.com/conda/conda-recipes/ .
> 
> In the top search box, search for the package named “pyfaker.” In the search results, you will see a link to the pyfaker/meta.yaml file. Open that file.

searching for "pyfaker" returns no results!

As of Nov 6 2015, @wikiped committed a change 8aedbf2d1a2e3fbdcce8347e45555b659c939bec to `meta.yaml` that changed the name of the package from `pyfaker` to just `faker`.   This broke the tutorial instructions.   (Also github repo search only indexes the contents of files so it also does not see the directory named 'pyfaker')

Either the tutorial instructions should be modified to search for 'faker' or the package's yaml file should again reference the package name as 'pyfaker'

**Comment by jakirkham** [comment]
It got moved to the [`python`]( https://github.com/conda/conda-recipes/tree/master/python/pyfaker ) subdirectory.
