### ISSUE TITLE
conda convert doesn't seem to respect selectors

### ISSUE THREAD

**Issue by moorepants** [conda/conda-build#721]
I built a simple metapackage on linux-64. I used a selector in the meta.yaml file to skip a dependency if you were to build it on Windows because that dep isn't available in the standard anaconda repos. I would have expected conda convert to respect this selector when I converted the package to other os's but it didn't. The dependency appears in the info.json file for the Windows packages.

**Comment by groutr** [comment]
I don't think conda convert uses the recipe.  It looks like it only uses the stuff in the info directory, which I don't think contain selector information.

**Comment by moorepants** [comment]
My use case is that I'd like to have different dependencies depending on the OS for a metapackage. I had to manually edit all the info.json files that are generated from the conda convert command. It would be nice if I didn't have to manually edit those.

**Comment by groutr** [comment]
I don't think `conda convert` was designed to do that.  However, that's not to say it couldn't.  In many cases, the recipe is packaged inside the info/ directory, though `conda convert` couldn't always assume the presence of a recipe.

**Comment by moorepants** [comment]
That's fine. It's just a use case that I hit and I have to currently do some manual fiddling. I could write some code to post process the tar balls, just haven't had time yet.
