### ISSUE TITLE
Permissions error when running as su - some_user

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda/conda-build#722]
With a package, anaconda-build, I can do `conda build conda.recipe` fine while working as root user in a root miniconda install at /opt/anaconda.  I cannot currently run that command as `su - some_user` because of permissions error adjusting requires.txt.

Here is my attempted command:

```
su -c "cd /home/peter/Desktop/continuum/AS/anaconda-build && export PATH=/opt/anaconda/bin:$PATH && conda build conda.recipe/" --login - user5
```

The build ends unsuccessful with:

```
running install_egg_info
running egg_info
writing requirements to anaconda_build.egg-info/requires.txt
error: [Errno 13] Permission denied: 'anaconda_build.egg-info/requires.txt'
Command failed: /bin/bash -x -e /opt/conda-build-dir/user5/work/conda_build.sh
```

A fix is needed in order to merge [anaconda-build PR 88](https://github.com/Anaconda-Server/anaconda-build/pull/88)

**Comment by pelson** [comment]
If you don't have permission to write to /opt/conda-build-dir, it is possible to target conda-build to build in a directory you do have permissions for: http://conda.pydata.org/docs/config.html#specify-conda-build-output-root-directory-conda-build

That would effectively mean either setting up your condarc appropriately, or:

```
export CONDA_BLD_PATH=$HOME/conda-build-directory
conda build ...
```
