### ISSUE TITLE
Patching should detect patch level

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#737]
Currently conda-build only accepts patches applicable with `patch -p0`. Since modern VCSes (git, mercurial...) by default produce diffs applicable with `patch -p1`, it would be nice to detect those and accept them too.

**Comment by jakirkham** [comment]
Believe @mingwandroid fixed this at some point. So this should probably be closed.

**Comment by mingwandroid** [comment]
Yeah one of my first tasks at anaconda! -p0? What on Earth?

**Comment by ltalirz** [comment]
Can this be closed? 

I guess this is being handled in 
https://github.com/conda/conda-build/blob/e458431a7f4becc6d786af6f1a11ee06f64c1513/conda_build/source.py#L514-L538

**Comment by jakirkham** [comment]
I think so. @chenghlee would you be able to close this?
