### ISSUE TITLE
Error in help message for --numpy

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#738]
See below: `11.0` is listed as a known version while it should be `1.10`.

```
  --numpy NUMPY_VER     Set the NumPy version used by conda build. Can be
                        passed multiple times to build against multiple
                        versions. Can be 'all' to build against all known
                        versions (['1.6', '1.7', '1.8', '1.9', '11.0'])
```

**Comment by pelson** [comment]
Looks like the offending line is https://github.com/conda/conda-build/blob/master/conda_build/main_build.py#L174, which is doing https://github.com/conda/conda-build/blob/master/conda_build/main_build.py#L53.

**Comment by jakirkham** [comment]
Related ( https://github.com/conda/conda-build/issues/631 ).
