### ISSUE TITLE
conda build doesn't allow passing anaconda token for upload

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#755]
The `anaconda` client has a `--token` option to pass an authentication token. However, `conda build` doesn't reflect that option, making it more tedious to upload files in a CI system.

**Comment by pitrou** [comment]
@jakirkham

**Comment by jakirkham** [comment]
Definitely a good idea.

**Comment by ivoflipse** [comment]
You also can't upload to any other account than your own, which is a pain if you want to add packages to an Organization account

**Comment by pitrou** [comment]
> You also can't upload to any other account than your own, which is a pain if you want to add packages to an Organization account 

Excellent point too.

**Comment by jakirkham** [comment]
Isn't there a user flag that solves this when uploading normally?

**Comment by jakirkham** [comment]
Token should resolve the organization account, as well.

**Comment by kalefranz** [comment]
I'm not sure we should address this with conda-build. It seems like this is the job of the anaconda client. If it's not already, the anaconda client should be looking for an `ANACONDA_TOKEN` environment variable or something similar. At most, conda-build should be simply shelling out to the anaconda client here. 

If I remember right, there's a ticket somewhere to make conda-build more robust in how it gives file paths for the anaconda client to upload.  I think that would be more in scope here.

**Comment by pitrou** [comment]
Perhaps @stephenakearns wants to chime in here.
