### ISSUE TITLE
Unconditionally putting cygwin at the front of the path is a bad idea

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda-build#757]
On Windows, `conda.utils.find_executable` searches through a couple directories before looking through the `PATH`. One of those is `'C:\\cygwin\\bin` (relevant [code](https://github.com/conda/conda-build/blob/c2c1e3a798c6564793fe3b8f27f240de3c48cb2d/conda_build/external.py#L19)). But because cygwin executables often only work _inside_ a cygwin shell, this a problem.

For example, using conda-build on Appveyor-CI to build a recipe from a `git_url` (where a proper, working installation of git is installed in the `PATH`, but a cygwin version is also installed in `C:\\cygwin\\bin` but _not_ on the `PATH`, conda-build will mistakenly chose the wrong one and then everything breaks.

See e.g.: https://github.com/omnia-md/conda-dev-recipes/blob/master/appveyor.yml#L51-L60

**Comment by pelson** [comment]
@ocefpaf and myself have also seen this. Would be great to fix. :+1:

**Comment by msarahan** [comment]
+1 - I'll look into this.  No ETA, though.  PRs very welcome.

**Comment by mingwandroid** [comment]
Removing cygwin from there would seem sensible to me, Cygwin isn't very interested in POSIX<->native interop. If you want that, replace it with MSYS2 where we'll fix bug reports of interop issues. Defaults would be:
`C:\\msys64\\usr\\bin` and `C:\\msys32\\usr\\bin`

**Comment by jakirkham** [comment]
Seems to be dropped since. Should we close?

ref: https://github.com/conda/conda-build/blob/7dac1cbad5195f719bde1eaeb0d5795186dc0eb0/conda_build/os_utils/external.py#L10
