### ISSUE TITLE
Permissions not set when extracting from zipfile.

### ISSUE THREAD

**Issue by dfroger** [conda/conda-build#778]
When extracting source code from a `zipfile`, permissions are lost, and for example:

```
./configure
```

will fail, because the file is no more executable.

This was solved in [Distribute](https://pythonhosted.org/distribute/) (deprecated fork of the Setuptools project) with this [pull request](https://bitbucket.org/tarek/distribute/pull-requests/14/set-permissions-when-extracting-from/diff).

Currently, [Setuptools](http://pythonhosted.org/setuptools) has a [unpack_zip](https://bitbucket.org/pypa/setuptools/src/0d80c1398b1901def27014ec91230103d0830188/setuptools/archive_util.py?at=default&fileviewer=file-view-default#archive_util.py-88:122) function that manage permissions, while the `conda-build` [unzip](https://github.com/conda/conda-build/blob/7a6a0d3a791acd94c680769b6e470add7db5a462/conda_build/utils.py#L86-L97) function do not.

We may update the `conda-build` `unzip` function, or maybe remove it and use `archive_util.py` module of`Setuptools` instead?

**Comment by jjhelmus** [comment]
Just ran into this issue as well when unpacking the bazel zip archive.

**Comment by msarahan** [comment]
I'd be in favor of adding setuptools as a runtime dependency and using their function.  PRs welcome.  I can't get to this right away.

**Comment by jjhelmus** [comment]
I'm not sure if the setuptools `unpack_zipfile` function is part of setuptools public API so I do not think using it in this manner would be wise.  I can put together a PR that adds the few lines from the mentioned distribute pull request.
