### ISSUE TITLE
build failure on appveyor

### ISSUE THREAD

**Issue by jreback** [conda/conda-build#780]
since I switched to the new recipe listed in #773 now appveyor is failing to build: https://ci.appveyor.com/project/jreback/pandas/build/1.0.1776/job/y11tdf2rllysu2hy

builds work fine on local vm for windows / macosx

switching back to the old recipe https://github.com/jreback/pandas/commit/be29514dd3b35b8de9b6e937e7522c6025ce828d works, but then this fails locally.

I though it was the ``clone_depth`` (as I had a problem on Travis with that as well, but resolved).

any ideas?

@stuarteberg @msarahan @jakirkham

**Comment by jakirkham** [comment]
So, number of possibilities.

As you have seen there were some problems with GIT_* variables in jinks templates. Using the old environment variables may help.

Another thing to consider is, as you have said, most CIs do shallow git clones. Unfortunately, how your recipe works now it must clone from the directory it resides in. I do a similar thing with a project I use with CI. However, git won't let you clone from a shallow clone. There are two options. First, you tell the CI somehow to make the clone not shallow or you do so manually if you have a version git on your CI that supports it (`git fetch --unshallow`). Second you trick git into thinking it is a normal clone. This can be done by removing a file called `.git/shallow`. Very new versions of git can be told to clone from the shallow repo anyways, but this is not something we should assume to be true for most use cases.

**Comment by jreback** [comment]
I don't think it's the clone depth as the tags look ok 

just trying to have a single recipe that builds everywhere

**Comment by jreback** [comment]
So I got this to work by just having an appveyor only recipe. https://github.com/jreback/pandas/commit/711e2db74ae52f269f8cb38f75d6aeb858478d5a

not very elegant, and I think conda-build should just work with the indicated recipe above

**Comment by JanSchulz** [comment]
@jreback not sure if that helps, but here is another way to get the version set 

```
{% set data = load_setuptools()%}
	
	package:
[...]
	    version: {{data.get('version')}}
```

-> it executes setup.py with a monkey-pacthed version of `setup()`, so if that gets the right name in a shallow clone, it should work...

**Comment by jreback** [comment]
do u have a recipe that uses this?

**Comment by JanSchulz** [comment]
https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy.recipe/meta.yaml

**Comment by jakirkham** [comment]
If you remove the clone depth, does it still work?

**Comment by jreback** [comment]
ironically I had to increase it even more (to get Travis to not bork). https://github.com/pydata/pandas/commit/fe584e7829dc4dd9fa585a7fbf5fd47fc6f4b057

even though I tagged (an rc1), not really sure why.

**Comment by jakirkham** [comment]
How was the tag created (annotated? signed? etc?)?

Also, something to consider would be to use `git fetch --unshallow`. If there isn't a new enough copy of `git` with a working copy of this command, you could try installing `git` with `conda`, which should work as there appear to copies of `git` 2.6.4 that are available.

**Comment by stuarteberg** [comment]
>I though it was the clone_depth (as I had a problem on Travis with that as well, but resolved).

Older versions of git can't handle "shallow" repositories at all, even if you set the `depth` to be pretty high (er, deep).  So if the appveyor VM is using an old version of git (say, 1.8), then you'll still see this error.  I suggest configuring your appveyor buiild to "unshallow" the git repo before running conda:

```
git fetch --unshallow
```

Cross-refs: #357 (just the last few comments), and #803.

**Comment by msarahan** [comment]
Closing this issue, as I believe @stuarteberg identified the real problem.  Please reopen or comment here if you believe this issue should be reconsidered.
