### ISSUE TITLE
Setting `noarch_python: False` seems to have no effect

### ISSUE THREAD

**Issue by almarklein** [conda/conda-build#787]
Setting `noarch_python` to `False` in the recipe still builds a noarch package.

**Comment by jakirkham** [comment]
Confused. Could you provide a little more information about what is happening here? An example recipe, a command call, version info, and a log would be really nice. :)

**Comment by almarklein** [comment]
I mean that `m.get_value('build/noarch_python')` yields the string `"False"`, which still evaluates to `True`. E.g. here https://github.com/conda/conda-build/blob/master/conda_build/build.py#L222

What would be a good way to fix this (surely there are other possible bools in a recipe)? I could include a fix in the noarch-related PR that I'm working on.

**Comment by jakirkham** [comment]
So, using `false` doesn't work too?

**Comment by almarklein** [comment]
Nope

**Comment by almarklein** [comment]
In the [code](https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L96), the yaml is decoded using `yaml.load(data, Loader=BaseLoader)`. Testing this:
``` python
>>> yaml.load('- foo: false', Loader=BaseLoader)
[{'foo': 'false'}]

>>> open BaseLoader

>>> yaml.load('- foo: false', Loader=yaml.Loader)
[{'foo': False}]
```

... so it seems that with BaseLoader, everything is a string. I just checked [the docs](http://conda.pydata.org/docs/building/meta-yaml.html) and it seems boolean values in a recipe are: `build/osx_is_app`, `build/preserve_egg_dir`, `build/binary_relocation`, `build/detect_binary_files_with_prefix`, `build/skip`, `app/own_environment`. Strangely, these do seem to work.

**Comment by almarklein** [comment]
Aha! https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L179-L187
