### ISSUE TITLE
Compiling pyc files without python dependency fails with stacktrace

### ISSUE THREAD

**Issue by danielfrg** [conda/conda-build#789]
This is a really annoying bug and the exit from `conda-build` is far from ideal.

If you are building a python package and don't have `python` on the dependencies in the `meta.yaml` you are going to get a stacktrace error because `conda-build` will try to compile the `.py` files to `.pyc` files: https://github.com/conda/conda-build/blob/master/conda_build/post.py#L130-L144

This will trigger a subprocess at https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L54-L58 and it will just fail because `python` is not on the `_build` environment.

I am ok with all this issues, I am ok with `conda-build` trying to execute a python command when python is not a dependency and I am even ok with the stacktrace but please just print the command that `conda-build` is executing in [_check_call](https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L54) so its easier to reproduce and see that `python` was a missing dependency on the `meta.yaml`.

**Comment by kalefranz** [comment]
Would be happy to accept a PR with your proposal :-p
