### ISSUE TITLE
Unable to build `bob.measure` with `conda build`

### ISSUE THREAD

**Issue by 183amir** [conda/conda-build#792]
You can use some of the channels that I have in my system to ease the installation.

    Traceback (most recent call last):
      File "/home/amir/miniconda3/bin/conda-build", line 5, in <module>
        sys.exit(main())
      File "/home/amir/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 192, in main
        args_func(args, p)
      File "/home/amir/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 486, in args_func
        args.func(args, p)
      File "/home/amir/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 409, in execute
        include_recipe=args.include_recipe)
      File "/home/amir/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 476, in build
        post_process(sorted(files2 - files1), preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
      File "/home/amir/miniconda3/lib/python3.5/site-packages/conda_build/post.py", line 148, in post_process
        remove_easy_install_pth(files, preserve_egg_dir=preserve_egg_dir)
      File "/home/amir/miniconda3/lib/python3.5/site-packages/conda_build/post.py", line 105, in remove_easy_install_pth
        utils.copy_into(join(egg_path, fn), join(sp_dir, fn))
      File "/home/amir/miniconda3/lib/python3.5/site-packages/conda_build/utils.py", line 34, in copy_into
        shutil.copytree(srcname, dstname)
      File "/home/amir/miniconda3/lib/python3.5/shutil.py", line 309, in copytree
        os.makedirs(dst)
      File "/home/amir/miniconda3/lib/python3.5/os.py", line 241, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/home/amir/miniconda3/envs/_build/lib/python3.5/site-packages/bob/__pycache__'

Current conda install:

                 platform : linux-64
            conda version : 3.19.3
      conda-build version : 1.19.0
           python version : 3.5.1.final.0
         requests version : 2.9.1
         root environment : /home/amir/miniconda3  (writable)
      default environment : /home/amir/miniconda3
         envs directories : /home/amir/miniconda3/envs
            package cache : /home/amir/miniconda3/pkgs
             channel URLs : https://conda.anaconda.org/t/<TOKEN>/alexbw/linux-64/
                            https://conda.anaconda.org/t/<TOKEN>/alexbw/noarch/
                            https://conda.anaconda.org/t/<TOKEN>/amir183/linux-64/
                            https://conda.anaconda.org/t/<TOKEN>/amir183/noarch/
                            https://conda.anaconda.org/t/<TOKEN>/jakirkham/linux-64/
                            https://conda.anaconda.org/t/<TOKEN>/jakirkham/noarch/
                            https://repo.continuum.io/pkgs/free/linux-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/linux-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : /home/amir/.condarc
        is foreign system : False

And here is my meta.yaml for bob.measure:

    package:
      name: bob.measure
      version: "2.1.0"

    source:
      fn: bob.measure-2.1.0.zip
      url: https://pypi.python.org/packages/source/b/bob.measure/bob.measure-2.1.0.zip
      md5: d65e40fb5442c740a7f6b926a75b5944
    #  patches:
       # List any patch files here
       # - fix.patch

    build:
      # noarch_python: True
      # preserve_egg_dir: True
      entry_points:
        # Put any entry points (scripts to be generated automatically) here. The
        # syntax is module:function.  For example
        #
        # - bob.measure = bob.measure:main
        #
        # Would create an entry point called bob.measure that calls bob.measure.main()

        - bob_compute_perf.py = bob.measure.script.compute_perf:main
        - bob_eval_threshold.py = bob.measure.script.eval_threshold:main
        - bob_apply_threshold.py = bob.measure.script.apply_threshold:main
        - bob_plot_cmc.py = bob.measure.script.plot_cmc:main

      # If this is a new build for the same version, increment the build
      # number. If you do not include this key, it defaults to 0.
      # number: 1

    requirements:
      build:
        - python
        - setuptools
        - bob.extension
        - bob.blitz
        - bob.core >2.0.4
        - bob.math
        - bob.io.base
        - matplotlib

      run:
        - python
        - bob.extension
        - bob.blitz
        - bob.core >2.0.4
        - bob.math
        - bob.io.base
        - matplotlib

    test:
      # Python imports
      imports:
        - bob
        - bob.measure
        - bob.measure.script

      commands:
        # You can put test commands to be run here.  Use this to test that the
        # entry points work.

        - bob_compute_perf.py --help
        - bob_eval_threshold.py --help
        - bob_apply_threshold.py --help
        - bob_plot_cmc.py --help
        - nosetests -sv bob.measure

      # You can also put a file called run_test.py in the recipe that will be run
      # at test time.

      requires:
        # Put any additional test requirements here.  For example
        - nose

    about:
      home: http://github.com/bioidiap/bob.measure
      license: BSD License
      summary: "Bob's evalution metrics"

    # See
    # http://docs.continuum.io/conda/build.html for
    # more information about meta.yaml

**Comment by pelson** [comment]
May be related to #718 given the pycache error.

**Comment by 183amir** [comment]
I am not sure if it is related but it is only happening in Python 3.5 builds and not in Python 2.7 builds.
You can see another example here:
https://travis-ci.org/bioidiap/bob.conda/jobs/112070232

**Comment by 183amir** [comment]
When I use `python setup.py install --single-version-externally-managed --record record.txt` instead of just `python setup.py install` I don't see this problem anymore. I tested this here:
https://github.com/conda-forge/staged-recipes/pull/817

**Comment by 183amir** [comment]
should be fixed in this pull: https://github.com/conda/conda-build/pull/1090
