### ISSUE TITLE
Make conda build smarter

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#794]
As a conda-build user, I want to be able to run `conda build .` in the root directory of my project, and have it build a conda package in addition to the possibility of an sdist and wheels.

In the case of a "simple" pure-python package, I don't want to have to write _any_ additional files other than my typical `setup.py` that I already know. If there is no `meta.yaml` file in my project directory, and there is no `conda.recipe` directory in my project directory, I want conda to recognize that a `setup.py` file exists and invoke setuptools to pull all the metadata it needs to from that file to.  The result is a "noarch" conda package, and again optionally an sdist and universal wheel.  The result of `conda build --sdist --wheel .` would be three new files in a `build` directory in my project.

In the case of a more complicated package that requires platform specificity, I'm going to want to write my conda recipe with `build.sh` and `bld.bat`.  In this case, `conda build .` would see a `conda.recipe` directory and, for the current platform the build is running on, be able to build a specified array of conda packages. Standards-compliant wheels would also be nice. The big difference here is that `conda build` is able to fall back to the `setup.py` file to get metadata so that I don't have to duplicate it in `meta.yaml`.  Basically any information in `meta.yaml` both supplements and masks anything already in `setup.py`.

**Comment by pelson** [comment]
Seems odd to overload conda-build to build anything other than a conda recipe. Why not ```python setup.py conda```? The metadata is coming from setup.py, and makes more sense to me.

> in addition to the possibility of an sdist and wheels.

Why does conda need to do these? There are already commands that work perfectly well to build sdist and wheels - is there an advantage to conda doing them for me?

> Basically any information in meta.yaml both supplements and masks anything already in setup.py

:+1:

**Comment by jakirkham** [comment]
There is already `python setup.py bdist_conda`. I would use that. Besides you can combine multiple targets with `python setup.py` so that really seems like the way to go. Though I haven't combined `bdist_conda` with multiple targets so unless someone else has that should be checked.

**Comment by bilderbuchi** [comment]
I am wondering if there currently is a way to build `noarch` packages using `bdist_conda` (without introducing a whole recipe)? I only ever get `win-64` packages when I build with `python setup.py bdist_conda`. I don't mind too much since all my users are on windows, but it feels strangely/unnecessarily specific.
