### ISSUE TITLE
While compiling pyinstrument

### ISSUE THREAD

**Issue by marqueewinq** [conda/conda-build#804]
Following this tutorial: http://conda.pydata.org/docs/build_tutorials/pkgs.html

After command `conda skeleton pypi pyinstrument`:

```
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda_build\main_skeleton.py", line 272, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda_build\main_build.py", line 486, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda_build\main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 741, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Anaconda2\lib\site-packages\conda_build\pypi.py", line 788, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Anaconda2\lib\site-packages\conda_build\source.py", line 259, in apply_patch
    check_call([patch] + patch_args, cwd=src_dir)
  File "C:\Anaconda2\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Anaconda2\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 740]
```

Current conda install:

```
             platform : win-64
        conda version : 3.19.3
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by msarahan** [comment]
Looks like you might have an old version of the patch package.  Try

Conda update patch

Then try your skeleton command again.

**Comment by kevinxzhu** [comment]
Hi,
I have the same error.
I update the patch and get the same.

C:\Users\xxxx>conda skeleton pypi pyinstrument
Warning, the following versions were found for pyinstrument
0.13.1
0.13
0.12
0.11
0.10.1
Using 0.13.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/pyinstrument/pyinstrument-0.
13.1.tar.gz (44 KB) for pyinstrument.
Downloading pyinstrument
Using cached download
Unpacking pyinstrument...
done
working in C:\Users\kzhu\AppData\Local\Temp\tmpyx0h8mo3conda_skeleton_pyinstrume
nt-0.13.1.tar.gz
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Applying patch: 'C:\\Users\\kzhu\\AppData\\Local\\Temp\\tmpyx0h8mo3conda_skeleto
n_pyinstrument-0.13.1.tar.gz\\pypi-distutils.patch'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 272,
in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 478, in
args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 286,
in execute
    pypi.main(args, parser)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 478, in get_pa
ckage_metadata
    python_version=args.python_version)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 741, in get_pk
ginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Anaconda3\lib\site-packages\conda_build\pypi.py", line 788, in run_se
tuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Anaconda3\lib\site-packages\conda_build\source.py", line 271, in appl
y_patch
    check_call([patch] + patch_args, cwd=src_dir)
  File "C:\Anaconda3\lib\subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Anaconda3\lib\subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Anaconda3\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
OSError: [WinError 740] The requested operation requires elevation

C:\Users\xxxx>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.19.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\Users\xxxx>conda list
# packages in environment at C:\Anaconda3:
#
alabaster                 0.7.7                    py35_0
anaconda                  2.5.0               np110py35_0
anaconda-client           1.2.2                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.1.1               np110py35_0
babel                     2.2.0                    py35_0
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.9.0                     <pip>
blaze-core                0.9.0                    py35_0
bokeh                     0.11.0                   py35_0
boto                      2.39.0                   py35_0
bottleneck                1.0.0               np110py35_0
bzip2                     1.0.6                    vc14_2  [vc14]
cffi                      1.2.1                    py35_0
clyent                    1.2.0                    py35_0
colorama                  0.3.6                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.0.5                    py35_0
conda-build               1.19.2                   py35_0
conda-env                 2.4.5                    py35_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
cryptography              1.0.2                    py35_0
curl                      7.45.0                   vc14_1  [vc14]
cycler                    0.9.0                    py35_0
cython                    0.23.4                   py35_0
cytoolz                   0.7.5                    py35_0
datashape                 0.5.0                    py35_0
decorator                 4.0.6                    py35_0
docutils                  0.12                     py35_1
dynd                      f641248                   <pip>
dynd-python               0.7.1                    py35_0
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_0
flask                     0.10.1                   py35_1
freetype                  2.5.5                    vc14_0  [vc14]
futures                   3.0.3                    py35_0
greenlet                  0.4.9                    py35_0
h5py                      2.5.0               np110py35_4
hdf5                      1.8.15.1                 vc14_4  [vc14]
idna                      2.0                      py35_0
ipykernel                 4.2.2                    py35_0
ipython                   4.0.3                    py35_0
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_3
ipython-qtconsole         4.0.1                    py35_4
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.1                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_0
jedi                      0.9.0                    py35_0
jinja2                    2.8                      py35_0
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.4.0                    py35_0
jupyter                   1.0.0                    py35_1
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0
jupyter_console           4.1.0                    py35_0
jupyter_core              4.0.6                    py35_0
launcher                  1.0.0                         4
libdynd                   0.7.1                         0
libpng                    1.6.17                   vc14_1  [vc14]
libsodium                 1.0.3                         0
libtiff                   4.0.6                    vc14_1  [vc14]
llvmlite                  0.8.0                    py35_0
lxml                      3.5.0                    py35_0
markupsafe                0.23                     py35_0
matplotlib                1.5.1               np110py35_0
menuinst                  1.3.2                    py35_0
mistune                   0.7.1                    py35_0
mkl                       11.3.1                        0
mkl-service               1.1.2                    py35_0
msvc_runtime              1.0.1                    vc14_0  [vc14]
multipledispatch          0.4.8                    py35_0
nbconvert                 4.1.0                    py35_0
nbformat                  4.0.1                    py35_0
networkx                  1.11                     py35_0
nltk                      3.1                      py35_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py35_0
notebook                  4.1.0                    py35_0
numba                     0.23.1              np110py35_0
numexpr                   2.4.6               np110py35_1
numpy                     1.10.4                   py35_0
odo                       0.4.0                    py35_0
openpyxl                  2.3.2                    py35_0
pandas                    0.17.1              np110py35_0
patch                     2.5.9                         1
path.py                   8.1.2                    py35_1
patsy                     0.4.0               np110py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.5                      py35_0
pillow                    3.1.0                    py35_0
pip                       8.1.0                    py35_0
ply                       3.8                      py35_0
psutil                    3.4.2                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_0
pycparser                 2.14                     py35_0
pycrypto                  2.6.1                    py35_3
pyflakes                  1.0.0                    py35_0
pygments                  2.1                      py35_0
pyopenssl                 0.15.1                   py35_1
pyparsing                 2.0.3                    py35_0
pyqt                      4.11.4                   py35_4
pyreadline                2.1                      py35_0
pytables                  3.2.2               np110py35_1
pytest                    2.8.5                    py35_0
python                    3.5.1                         2
python-dateutil           2.4.2                    py35_0
pytz                      2015.7                   py35_0
pywin32                   219                      py35_2
pyyaml                    3.11                     py35_3
pyzmq                     15.2.0                   py35_0
qt                        4.8.7                    vc14_5  [vc14]
qtconsole                 4.1.1                    py35_0
requests                  2.9.1                    py35_0
rope                      0.9.4                    py35_1
rope-py3k                 0.9.4.post1               <pip>
scikit-image              0.11.3              np110py35_0
scikit-learn              0.17                np110py35_2
scipy                     0.17.0              np110py35_0
setuptools                20.2.2                   py35_0
simplegeneric             0.8.1                    py35_0
sip                       4.16.9                   py35_2
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.1                    py35_0
sphinx                    1.3.5                    py35_0
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py35_0
spyder                    2.3.8                    py35_0
spyder-app                2.3.8                    py35_0
sqlalchemy                1.0.11                   py35_0
statsmodels               0.6.1               np110py35_0
sympy                     0.7.6.1                  py35_0
tables                    3.2.2                     <pip>
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.7.4                    py35_0
tornado                   4.3                      py35_0
traitlets                 4.1.0                    py35_0
unicodecsv                0.14.1                   py35_0
unxutils                  14.04.03                      0
werkzeug                  0.11.3                   py35_0
wheel                     0.29.0                   py35_0
xlrd                      0.9.4                    py35_0
xlsxwriter                0.8.4                    py35_0
xlwings                   0.6.4                    py35_1
xlwt                      1.0.0                    py35_0
zlib                      1.2.8                    vc14_2  [vc14]

**Comment by msarahan** [comment]
unxutils has a patch executable that requires elevation.  We need to remove
that.

Please go into your C:\Anaconda3\Scripts folder and delete patch.exe.  The
correct one is in Library\bin.

**Comment by kevinxzhu** [comment]
Yes, it works fine after rename patch.exe from  C:\Anaconda3\Scripts.
thanks!

**Comment by jakirkham** [comment]
Looks resolved. Should it be closed?
