### ISSUE TITLE
Grant access to native OS X header + libraries

### ISSUE THREAD

**Issue by croth1** [conda/conda-build#806]
Unlike linux, OS X does not ship any header files in `/usr/include` - Building with conda's gcc therefore requires setting the include and library path manually.

See https://github.com/bioconda/bioconda-recipes/pull/956 for a formula where this is necessary. 

These are the important bits for c++:
```
 if [ $(uname) == "Darwin" ]; then
     CXXFLAGS="$CXXFLAGS -I$(xcrun --show-sdk-path)/usr/include"
     LDFLAGS="$LDFLAGS -L$(xcrun --show-sdk-path)/usr/lib"
 fi
```

Not setting these variables leads to gcc not being able to find headers like `pthread.h` which are provided by OS X, not gcc.

I think it could make sense to add the native include and library variables automatically in the build environment for OS X. This would make building gcc formulas on mac much easier.

**Comment by jakirkham** [comment]
@stuarteberg, is there a way to add this information to `gcc` recipe?

**Comment by stuarteberg** [comment]
>Unlike linux, OS X does not ship any header files in `/usr/include`

That directory is populated if you install the Xcode command-line tools.  If someone wants to build packages on their machine, I think it's reasonable to expect that they'll have the command-line tools installed.

For the record, you can install them by typing this into a terminal:

    xcode-select --install

... which will open a dialog and ask for a password.

Apparently *checking* to see if a user already has the command-line tools installed is not easy:
http://stackoverflow.com/questions/15371925/how-to-check-if-command-line-tools-is-installed


>is there a way to add this information to the gcc recipe?

I'm not in favor of modifying `CXXFLAGS` unless it's absolutely necessary and we understand the consequences of doing so.  For example, on my machine, the contents of `/usr/include` and `$(xcrun --show-sdk-path)/usr/include` are *almost* identical, but not quite.  What are the consequences of switching between them?

BTW, it's safer to use [`-isystem`](https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html) than `-I` for system headers:

    CXXFLAGS="$CXXFLAGS -isystem$(xcrun --show-sdk-path)/usr/include"

**Comment by croth1** [comment]
@stuarteberg you are right. Installing the command-line tools also creates `/usr/include` - So probably not a real issue.

**Comment by jakirkham** [comment]
What differences did you notice?

**Comment by stuarteberg** [comment]
These are the differences in the directory contents on my machine.  But it's probably not worth investigating this further.  I think this issue can be closed for now.

```bash
$ ls /usr/include > /tmp/usrinclude
$ ls $(xcrun --show-sdk-path)/usr/include > /tmp/sdkinclude
$ diff /tmp/usrinclude /tmp/sdkinclude
39a40
> compression.h
40a42
> corpses/
125a128
> module.modulemap
148d150
< openssl/
173d174
< reboot2.h
199d199
< stdbool.h
221a222
> tgmath.h
```

**Comment by croth1** [comment]
Not an issue after installing the command-line tools. Closing.
