### ISSUE TITLE
CI: Python 3.3 has unsatisfiable dependencies

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#810]
Running into failures on Python 3.3. Should we be dropping support for it as it is no longer supported for `conda`?

**Comment by jakirkham** [comment]
See ( https://github.com/conda/conda-build/pull/812 ) for the fix for CI.

**Comment by groutr** [comment]
What is the output from conda?  I'm not getting unsatisfied dependencies?

**Comment by jakirkham** [comment]
The issue occurs when trying to install the latest version of `conda` into the root environment without enforce dependency constraints as is done with Travis CI. Here is an example of the error as seen [on Travis]( https://travis-ci.org/conda/conda-build/jobs/114597276#L172-L174 ). This has been fixed by ( https://github.com/conda/conda-build/pull/812 ), which has already been merged so it is a non-issue now.
