### ISSUE TITLE
fn + url in meta.yaml is redundant

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#829]
_From @majidaldo on June 28, 2013 16:36_

fn does need to be specified if the url is specified.

_Copied from original issue: conda/conda#177_

**Comment by kalefranz** [comment]
_From @asmeurer on June 28, 2013 17:2_

The filename might not come directly from the url, depending on the url scheme.

**Comment by kalefranz** [comment]
_From @asmeurer on June 28, 2013 17:2_

It does seem odd, though. Can't it just check what file was downloaded?

**Comment by jakirkham** [comment]
`fn` is optional at this point. So this issue should be closed.

**Comment by marscher** [comment]
when was this released?

**Comment by mingwandroid** [comment]
Years ago.
