### ISSUE TITLE
Development vs Production: Selecting a different source/version/git_tag

### ISSUE THREAD

**Issue by jhunkeler** [conda/conda-build#839]
Hi,

I am aware of conda-build's selectors and I use them quite often:

```
build:
    - number: 2 [osx]
    - number: 1 [linux]
```

I enjoy this ability, however I have gotten myself into a situation where I need a bit more power/control.

I've been forced fork my recipes into two separate categories. I have a development recipe that pulls the latest git master and automatically assigns a version to the package according to the last known tag. On the other hand, in production, I have a recipe that defines a fixed `git_tag` and `version` in order to produce a "proper" release package.

Is there a way to construct a single recipe to perform a build based on, let's say, an environment variable?

```
#pseudo-preprocessor-code
package:
    %if ENV['DEVELOPMENT']:
    - version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'
    %else:
    - version: 1.0.0
    %endif
```

If I missed something in the documentation please let me know. I also did a quick "issue" search and didn't find much.

Thanks,
Joe

**Comment by stuarteberg** [comment]
>Is there a way to construct a single recipe to perform a build based on, let's say, an environment variable?

Yes.  You can use jinja templates within `meta.yaml`, and conda-build gives those jinja templates access to your environment variables.  jinja supports if/else statements and [various other control structures][1].

[1]: http://jinja.pocoo.org/docs/dev/templates/#list-of-control-structures

This seems to work:

```yaml
package:
  name: my-package
  {% if DEV_MODE == "DEVELOPMENT" %}
  version: {{ GIT_DESCRIBE_TAG }}
  {% else %}
  version: 0.1
  {% endif %}
```

Depending on your tastes, it might look cleaner to separate the logic out from the rest of the template:

```yaml
{% if DEV_MODE == "DEVELOPMENT" %}
  {% set version = GIT_DESCRIBE_TAG %}
{% else %}
  {% set version = '0.1' %}
{% endif %}

package:
  name: my-package
  version: {{ version }}
```

Hmm... In both cases, `DEV_MODE` must exist in your environment.  OK, here's a way to avoid that requirement:

```yaml
{% if DEV_MODE is defined %}
  {% set version = GIT_DESCRIBE_TAG %}
{% else %}
  {% set version = '0.1' %}
{% endif %}

package:
  name: my-package
  version: {{ version }}
```

**Comment by pelson** [comment]
If this is a python package, one option is to inspect the version through setuptools. For example:

```
{% set data = load_setuptools() %}

package:
    name: conda-build-all
    version: {{data.get('version')}}
```
(from https://github.com/SciTools/conda-build-all/blob/master/conda-build-all.recipe/meta.yaml)

Of course, that means your setup.py should reflect the dev version correctly (conda-build-all does this through versioneer, but it is possible to use the GIT_DESCRIBE info).

**Comment by jhunkeler** [comment]
Thank you both very much for answers.
I've definitely learned something new :+1:

**Comment by msarahan** [comment]
Looks like this is resolved.  Closing.  Thanks all for your insights.  Please reopen or comment as necessary.
