### ISSUE TITLE
C extension packages build on OSX 10.7 don't work on 10.10 (and up) anymore

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda-build#841]
It used to be that when building packages on OSX 10.7, they would work on 10.7 and up.  This issue https://github.com/ContinuumIO/anaconda/issues/485 was the first one which indicated a problem, although we didn't at first realize that this is a problem in `conda-build`.  Upon further inspection, it turns out that some change between `1.19.0` and `1.19.1` broke this, probably related to https://github.com/conda/conda-build/pull/808/files.

CC @kalefranz @mingwandroid

**Comment by ilanschnell** [comment]
It should also be noted that the problem only appears to occur with Python 3.x extension files.

**Comment by stuarteberg** [comment]
Since ContinuumIO/anaconda#485 is private, would you mind pasting some details about the error here?

**Comment by ilanschnell** [comment]
Oh, sorry.  Basically is explains how `psutil` was broken on OSX 10.11 for Python 3.4 with the error message:
```
$ python -c 'import psutil'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ksmith/anaconda/envs/test-psutil/lib/python3.4/site-packages/psutil/__init__.py", line 134, in <module>
    from . import _psosx as _psplatform
  File "/Users/ksmith/anaconda/envs/test-psutil/lib/python3.4/site-packages/psutil/_psosx.py", line 14, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Users/ksmith/anaconda/envs/test-psutil/lib/python3.4/site-packages/psutil/_psutil_osx.so, 2): no suitable image found.  Did find:
        /Users/ksmith/anaconda/envs/test-psutil/lib/python3.4/site-packages/psutil/_psutil_osx.so: malformed mach-o image: load command #14 length (0) too small in /Users/ksmith/anaconda/envs/test-psutil/lib/python3.4/site-packages/psutil/_psutil_osx.so
```

**Comment by ilanschnell** [comment]
The packages affect by this bug were: mistune, psutil, pykerberos, spacy and thinc
They are all fixed now, i.e. recompiled using `conda-build 1.19.0`.

**Comment by stuarteberg** [comment]
It would be useful to see the output of:

```
otool -l /Users/ksmith/anaconda/envs/test-psutil/lib/python3.4/site-packages/psutil/_psutil_osx.so
```

... if that file still exists anywhere.  Is there a particular version (with build number) that I can pull from anaconda.org for inspection?

If not, can you provide a link to the particular recipe that's causing trouble?.  I don't know where the official `psutil` recipe can be found.

**Comment by ilanschnell** [comment]
Well you can (using the default channel) say:
```
conda create -n broken_psutil python=3.5 psutil=4.1.0=py35_0
```
And then you can reproduce the error and inspect the broken binary.

**Comment by stuarteberg** [comment]
I'm not sure, my guess is that it's [this line](https://github.com/conda/conda-build/blob/master/conda_build/post.py#L261):

```python
        # .. and remove config.build_prefix/lib which was added in-place of
        # DYLD_FALLBACK_LIBRARY_PATH since El Capitan's SIP.
        macho.delete_rpath(path, config.build_prefix + '/lib', verbose = True)
```

I can reproduce the error on my machine (OSX 10.10), but only using the package you mentioned above.  When I build the recipe myself, the resulting package seems to work just fine.

I wonder if the version of `install_name_tool` that ships with OS 10.7 is somehow broken, at least for the  `-delete_rpath` option.  Googling around turns up other threads involving this error, and they also used `install_name_tool -delete_rpath`.  (Obviously, I'm just grasping at possible explanations here...)

**Comment by mingwandroid** [comment]
That's my theory as well.

When we have time to implement it, hopefully soon,  we need a solution that works and is tested across all OSXen that we support.

**Comment by stuarteberg** [comment]
Just for reference, this is what I see with `otool -l [...] | tail`.  Obviously, the last couple lines look bad.

```
$ otool -l /miniconda/envs/broken_psutil/lib/python3.5/site-packages/psutil/_psutil_osx.so \
> | tail -n12
Load command 12
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 31144
 datasize 0
Load command 13
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/../../../ (offset 12)
Load command 14
      cmd ?(0x00000000) Unknown load command
  cmdsize 0
Load command 13
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/../../../ (offset 12)
Load command 14
      cmd ?(0x00000000) Unknown load command
  cmdsize 0
```

**Comment by patricksnape** [comment]
Just from googling around, I found [this](https://cmake.org/gitweb?p=cmake.git;a=commit;h=08141a5). Is it possible we are adding multiple rpath paths that are identical?

Haven't gone deep enough into this to really help - would be good to have a copy of the psutil recipe for debugging.

**Comment by ilanschnell** [comment]
The recipe is here: https://github.com/ContinuumIO/anaconda-recipes/tree/master/psutil
In fact, we made all conda recipes we use for building packages in Anaconda available in that repository.

**Comment by patricksnape** [comment]
Unfortunately, I don't have an OSX 10.7 image kicking around to really test this out. As mentioned by @mingwandroid, would it be possible to get the output of `strings $(install_name_tool 2>&1 | cut -d' ' -f2) | grep cctools` and also the output of `md5 /usr/bin/install_name_tool `? I've got the XCode that provides the 10.7 SDK file, and it contains an older `install_name_tool`, but I'm not sure if it is the correct one or not. I'm not able to replicate the error at the moment so I assume it isn't.
