### ISSUE TITLE
Docs on what jinja can do ATM

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#845]
I know I have seen numerous changes to extend jinja in various interesting and promising ways. However, it is difficult for me to remember what it can or cannot do and why this is. Could we have some updated docs that reflect the current state of jinja templating in conda build?

**Comment by jakirkham** [comment]
cc @stuarteberg @msarahan @ukoethe

**Comment by stuarteberg** [comment]
This ought to wait until after #848, etc. is resolved.

**Comment by msarahan** [comment]
Agree with Stuart, but might start a PR now to be finalized later.

**Comment by jakirkham** [comment]
Though there should be some simple things that one can say. Does PR ( https://github.com/conda/conda-build/pull/848 ) or now PR ( https://github.com/conda/conda-build/pull/966 ) actually break anything that is currently possible? It was my impression that it merely extended it substantially.

In any event, as long as it is on people's minds (particularly those making most of these additions 😉) and does get documented, I'm happy.

**Comment by jakirkham** [comment]
This is pretty well covered with Conda-Build 3
