### ISSUE TITLE
Combined pre-processing selectors are not behaving as expected

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#846]
Forgive me if I am using it wrong, but my logic tells me that if I use the pre-processing selectors like `# [not win and not py35]` that would be evaluate to `True` only when both are `True`. Is that correct? Instead I get all that Python 3.5 builds canceled instead of only  Windows and Python 3.5.

See https://github.com/conda-forge/staged-recipes/pull/96#discussion_r57327799

**Comment by pelson** [comment]
Is this consistent with your expectations?

```
>>> for win in [True, False]:
...   for py35 in [True, False]:
...     print(win, py35, not win, not py35, not win and not py35)
... 
(True, True, False, False, False)
(True, False, False, True, False)
(False, True, True, False, False)
(False, False, True, True, True)
```

The line which does this is at https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L83 - there is nothing special, it is just a python eval. Therefore, I'd assume that the values of the selectors are wrong. You could do something like putting those values in the package name (with jinja) to see that they are what you expect?

**Comment by ocefpaf** [comment]
Makes sense. I guess I am doing it wrong. I had:

`- gdal >=1.11.2,<2.0  # [not win and not py35]`

Meaning that I do want that line to be True everywhere but Windows and Python 3.5.

I take a second look at it.
