### ISSUE TITLE
conda skeleton pypi logstash_formatter : OSError: [WinError 740]

### ISSUE THREAD

**Issue by pjc42** [conda/conda-build#851]
When running:

    conda skeleton pypi --version 0.5.2 logstash_formatter

I get the following output:

--------------------------------- begin snip ---------
Using url https://pypi.python.org/packages/source/l/logstash_formatter/logstash_formatter-0.5.2.tar.gz (3 KB) for logstash_formatter.
Downloading logstash_formatter
Unpacking logstash_formatter...
done
working in d:\temp\tmp0bvuvag4conda_skeleton_logstash_formatter-0.5.2.tar.gz
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Applying patch: 'd:\\temp\\tmp0bvuvag4conda_skeleton_logstash_formatter-0.5.2.tar.gz\\pypi-distutils.patch'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "b:\python\anaconda3_2.5.0\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\main_skeleton.py", line 298, in main
    args_func(args, p)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\main_build.py", line 493, in args_func
    args.func(args, p)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\main_skeleton.py", line 313, in execute
    pypi.main(args, parser)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\pypi.py", line 741, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\pypi.py", line 788, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda_build\source.py", line 271, in apply_patch
    check_call([patch] + patch_args, cwd=src_dir)
  File "b:\python\anaconda3_2.5.0\lib\subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "b:\python\anaconda3_2.5.0\lib\subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "b:\python\anaconda3_2.5.0\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "b:\python\anaconda3_2.5.0\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
OSError: [WinError 740] The requested operation requires elevation

----- end snip ------------------------------------------

    conda info

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : b:\python\anaconda3_2.5.0  (writable)
  default environment : b:\python\anaconda3_2.5.0
     envs directories : b:\python\anaconda3_2.5.0\envs
        package cache : b:\python\anaconda3_2.5.0\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

---------------------------------------------------------------------------------------------------------------
I get the same errors with the [pyinstrument](http://conda.pydata.org/docs/build_tutorials/pkgs.html)

    conda skeleton pypi pyinstrument

**Comment by msarahan** [comment]
You probably have unxutils installed.  That package includes a version of patch that does not include a manifest file that tells Windows that elevation is not required.  The ```patch``` package does include that manifest, but the executable lives in a different place (Library/bin rather than Scripts)

You can either manually delete patch.exe from the Scripts folder, or ```conda remove unxutils``` and it should go back to working.

**Comment by pjc42** [comment]
Mike, thank you, removing unxutils with  `conda remove unxutils` did indeed fix the issue.

I'm a little confused by this issue and the documentation at [conda-build tutorial](http://conda.pydata.org/docs/build_tutorials/pkgs.html) which explicitly says win users need `unxutils` installed. Is the doc just out of date or are there some other areas in building conda packages that win users need `unxutils`?

**Comment by msarahan** [comment]
The doc is out of date.  We need to fix that.  conda-build on Windows depends on the patch package, which does the right thing.  Unxutils is deprecated, but we're still settling on the best way to provide unix utilities on Windows.  Currently the git package installs git for windows, which includes many unix utlities.  We will soon also provide MSYS2.  If you don't need these utilities, then you need not worry about them at all.

Ping @kerrywatson1 @electronwill

**Comment by electronwill** [comment]
@msarahan, would you please review this change? https://github.com/conda/conda-docs/pull/264

**Comment by electronwill** [comment]
OK, this change is live at http://conda.pydata.org/docs/build_tutorials/pkgs.html . Thank you for the review, Mike.
