### ISSUE TITLE
Mac relative paths to dynamic libraries not converted to rpaths 

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#865]
If a library links to another library, but does not contain the full prefix and instead includes some relative path, then this path will not be corrected to an rpath. Instead it remains a relative path. This causes issues when trying to load dynamic libraries. Here is an [example](https://travis-ci.org/conda-forge/staged-recipes/jobs/120711298#L2731-L2735) of this behavior.

**Comment by patricksnape** [comment]
One adhoc way to fix this would be to change the logic that if `install_name_tool` finds either `@loader_path` or a relative path then it tries two things:

  1) Resolve the path and see if the library exists - if so then change it
  2) Just try and see if the library exists in the `$PREFIX/lib` directory and if it does then change it

**Comment by jakirkham** [comment]
It seems like 1 is a good choice. With 2, there are some situations where that might break.
