### ISSUE TITLE
Improve local git source repository handling

### ISSUE THREAD

**Issue by frol** [conda/conda-build#876]
Right now, either you use a remote git repo or a local one, conda build executes `git clone` and that is it. This works in some cases, it works slowly in other cases, and it may not work at all on access-restricted repos or while you are offline.

Once you have a submodule (obviously listed in `.gitmodules` with an external link), `git clone` of a local repo will require network access, "read" permissions to the submodule, and some network traffic. There are a few use-cases when this will be a show-stopper:
1. CI server, which clones private repositories with its own credentials and you cannot re-clone the submodules on conda build stage due to the lack of credentials.
2. Offline mode development is not possible without manual modifications (e.g. changing `git_url` to `path` in `meta.yaml`).

Even if it is not a show-stopper for you, you may suffer from a slow internet connection, so downloading all submodules on every build will be frustrating and completely unnecessary.

I used to use `source/path` option, but it was "fixed" in #745. I have also noticed #753, but it doesn't solve the issue at all since it will only work for the cases when you don't need submodules. 

/cc @ilanschnell @jasongrout @stuarteberg @gmarkall @jakirkham @groutr

**Comment by stuarteberg** [comment]
>I used to use `source/path` option, but it was "fixed" in #745.

IIUC, I think the behavior of `source/path` within git repos was recently improved by @groutr via #801.  I haven't tested the new behavior myself, though.

**Comment by frol** [comment]
@stuarteberg The PR makes the code look much better. Yet, it doesn't change the fact that having `GIT_DESCRIBE_*` env variables requires `source/git_url` setting, which results in `git clone`.

Since we have our automated build scripts on top of conda-build, I have managed to auto-discover `GIT_DESCRIBE_*` information before conda-build run, and pass it via env variables to conda-build execution, so we continue using `GIT_DESCRIBE_*` with `source/path` setting in `meta.yaml`.

**Comment by groutr** [comment]
@frol, if `source/path` isn't defining `GIT_*` variables, then it's very likely a bug that needs to be fixed.  The test for `source/path` specifically checks that these `GIT_*` variables are defined when `source/path` is used.

**Comment by frol** [comment]
@groutr This "bug" was introduced as a fix in #745. (I have mentioned this in the first message.)

**Comment by stuarteberg** [comment]
>This "bug" was introduced as a fix in #745

As I mentioned above, I think it was probably fixed by @groutr in #801.  Can you confirm, @frol?
