### ISSUE TITLE
Conda-build: Remove dependency on setuptools and setup.py for python packages. (redundant meta.yaml)

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#884]
_From @telson on April 8, 2016 21:42_

All the information is in the meta.yaml.  Why not do away with setuptools and setup.py?

Build.sh can already replace setup.py by:
- Extracting tarball into site-packages
- Add package to conda.pth
- Add entrypoints to bin/
- ... etc

... so why have so much information duplicated in both meta.yaml and setup.py, requiring manual transcription?

(If it's absolutely necessary, why not have a conda-build step that generates one from the other)

_Copied from original issue: conda/conda#2341_

**Comment by kalefranz** [comment]
_From @msarahan on April 9, 2016 23:50_

This is a good idea, but I don't think the answer is to totally remove setup.py.  That would further divide the two packaging communities.  As it is, we need to find ways to better interoperate with pip, not toss them aside.  A tool for updating conda recipes from PyPI/pip would be really nice - we have conda skeleton pypi, but that is only for creating new recipes.  We welcome any thoughts you have on the matter.

**Comment by kalefranz** [comment]
_From @marscher on April 13, 2016 10:11_

I think a tool for updating this information would be a great improvement. Removing setup.py is an absolute no-go since it is a well established way of distributing packages.

**Comment by kalefranz** [comment]
Related to #794

**Comment by orodbhen** [comment]
Is there a tool for that takes `setup.py` as input and generates a `conda` recipe? Seems like `skeleton` only works on package repos.

**Comment by msarahan** [comment]
not that I know of, but you can use load_setup_py_data in jinja2 and have a very minimal conda recipe.  See this for an example: https://github.com/gerrymandr/adjacency-graphs/blob/master/conda.recipe/meta.yaml
