### ISSUE TITLE
Option to generate static `meta.yaml` file(s)

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#887]
We have some options to do this with tools in [conda-forge]( https://conda-forge.github.io/ ), but I am wondering if it wouldn't be valuable to have this in conda-build proper. The idea here is we complete the required jinja passes and fill in all selectors, but never actually build anything (though we may need to download stuff temporarily (`GIT_*` vars). All we do is generate a static `meta.yaml` (maybe called `meta_static.yaml`). This allows for the final product to be observed and used in other process where reasoning about this result is necessary to proceed.

I think this would be incredibly powerful in debugging recipes. Particular ones using these dynamic features like the jinja passes. This might also prove very useful in combination with highly dynamic recipes like those proposed in this PR ( https://github.com/conda/conda-build/pull/848 ). Though other strategies to handle this ( https://github.com/conda/conda-build/issues/857 ) could also benefit from a clean static output. Other strategies of pinning while maybe less dynamic ( https://github.com/conda/conda-build/pull/728 ) ( https://github.com/conda/conda-build/pull/747 ) could at least be turned into their components. Also, this could play a role in generating final product recipes of a variety of different potential combinations that are used in matrix builds (potentially with exclusion) for example.

While I am proposing this, I don't want it to distract from efforts of fixing API/ABI in packages. Though I do want us to keep this in mind as a potential part of a more general solution. Also, this may tease out one of the important issues with regards to how this pinning happens and is used in later steps.

Then again maybe this totally off base. Please let me know your thoughts.

cc @pelson @ukoethe @stuarteberg @msarahan @johanneskoester @kalefranz

**Comment by stuarteberg** [comment]
>All we do is generate a static meta.yaml (maybe called meta_static.yaml).

Currently, there is such a fully-rendered file, but (as you say) it's not created until the recipe is fully built.  The file is named `index.json`.  It's not in the same exact structure as `meta.yaml`, but it contains the same information.  See further discussion in #781.

>The idea here is we complete the required jinja passes and fill in all selectors, but never actually build anything

I can see how this might be useful.  The file can't be created accurately until after the source is downloaded.  At the moment, conda-build can be told to stop early using `conda build --source myrecipe`.  Maybe the simplest way to support your idea would be to write `index.json` immediately after the source is downloaded, and then change the `--source` behavior so conda-build exits immediately after that.
