### ISSUE TITLE
Windows: too long path prevents `.trash` from being cleaned

### ISSUE THREAD

**Issue by dsludwig** [conda/conda-build#891]
When the trash contains files with path names that are too long, they are not deleted, causing a disk space leak.

```
WARNING:conda.install:Cannot remove, unknown reason: C:\Users\binstar\Miniconda\pkgs\.trash\tmpsevsb8\conda-bld\work\work\**********\ui\node_modules\flow-bin\node_modules\bin-wrapper\node_modules\download-status\node_modules\lpad-align\node_modules\meow\node_modules\read-pkg-up\node_modules\read-pkg\node_modules

WARNING:conda.install:Cannot remove, not empty: C:\Users\binstar\Miniconda\pkgs\.trash\tmpsevsb8\conda-bld\work\work\**********\ui\node_modules\flow-bin\node_modules\bin-wrapper\node_modules\download-status\node_modules\lpad-align\node_modules\meow\node_modules\read-pkg-up\node_modules\read-pkg
```
[0] https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath
[1] #260

**Comment by kalefranz** [comment]
I guess should be discussed along with #877.  Need input from @msarahan and @mingwandroid for a technical solution.

**Comment by mingwandroid** [comment]
I will fix this in 4.0.x.

**Comment by ccordoba12** [comment]
It's probably worth saying that this is really important for Anaconda build because the Windows workers are running out of space by being unable of cleaning everything under `.trash`.

**Comment by mingwandroid** [comment]
ok, thanks @ccordoba12.

**Comment by mingwandroid** [comment]
Will close the bug when the next release is made.

**Comment by msarahan** [comment]
closed by https://github.com/conda/conda/issues/2452

**Comment by msarahan** [comment]
thanks @mingwandroid!
