### ISSUE TITLE
Recent change affected handling of empty sections in meta.yaml

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#894]
A change made in 3bd490d (part of #801) seems to have changed how `conda build` handles empty metadata sections. These cases are, admittedly, odd; I hit it in a recipe where I had commented out an import test that expected to fail, leaving a `test:` section with only comments. Previous this built just fine but now generates the error `Error: The test field should be a dict, not unicode`.

As a minimal example to reproduce, put this (and only this) in your meta.yaml:

```
package:
```

In conda-build 1.20.0 this raises a sensible error, `Error: package/name missing in: u'/Users/.../meta.yaml'`; same behavior in the commit before 3bd490d. 

After that commit (e.g. conda-build 1.20.1) the result is the less helpful: `Error: The package field should be a dict, not unicode`

**Comment by ccordoba12** [comment]
Pinging @groutr about this one.

**Comment by msarahan** [comment]
closed by #919
