### ISSUE TITLE
Two problems building when a requirement leads to a version conflict: infinite loop and incorrect reporting of error 

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#896]
In trying to build a package on Windows x64 for python 3.4 I hit an infinite build loop. See [this Appveyor log](https://ci.appveyor.com/project/mwcraig/vpython-jupyter/build/1.0.4/job/399kjoo8irmx22su) for an example of the output (though it is not particularly informative).  

It turns out the same thing happens on my mac if I set `CONDA_PY=34`. I don't think the version of python is actually significant, except that one of the dependencies isn't built for python 3.4.

The repo I was trying to build is at https://github.com/BruceSherwood/vpython-jupyter; full steps to reproduce are at the end of this.

Some git bisect revealed that the infinite loop behavior was introduced in d3f31c2, part of #826 by @kalefranz.

The build fails  in `conda-build=1.19.1` (more on that in a moment), but runs in an infinite loop if CONDA_PY is 3.4  in `conda-build=1.19.2`.

While looking into this I noticed that the error message that I should have received (and did receive in `conda-build=1.19.0`) was no longer produced in 1.19.1. If this is a separate issue from the infinite loop I can open a separate issue, but I suspect both are related to error handling. This error was introduced in f85fd760 according to git bisect.

The error produced in 1.19.0 is below and clearly indicates the underlying problem, a version conflict:

```
Solving package specifications: ....
Error: The following specifications were found to be in conflict:
  - python 3.4*
  - vpnotebook -> python 2.7*|3.5*
Use "conda info <package>" to see the dependencies for each package.
```

After f85fd760 this message is below, with no build conflict reported; it gives the appearance of the build having succeeded even though it did not:

```
Solving package specifications: ....
Nothing to test for: vpython-0.3.6-py34_0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload C:\Users\mcraig\AppData\Local\Continuum\Miniconda2-new\conda
-bld\win-64\vpython-0.3.6-py34_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
```

To reproduce these, do this:

```
git clone https://github.com/BruceSherwood/vpython-jupyter.git
cd vpython-jupyter
export CONDA_PY=34
conda build vpython.recipe
```

For the infinite loop, run with `conda-build>=1.19.2`. For no loop, but also no error, run with `conda-build=1.19.1`. To produce the error that should be produced, run with `conda-build=1.19.0`

**Comment by ericdill** [comment]
"... the underlying problem, a version conflict:"

:+1: Would also like to see this infinite loop resolved.  Terribly confusing behavior for a version conflict.

**Comment by mwcraig** [comment]
I think this has also been resolved, so closing.
