### ISSUE TITLE
dependencies (requirements) not installed when source/ is empty

### ISSUE THREAD

**Issue by brentp** [conda/conda-build#899]
I have some recipes where I put everything in `pre-link.sh` so there is no source. However, the stuff in `pre-link.sh` has requirements. Those do not get built without a source section. 

Is it possible to force the install of the requirements even without source? And/or is there a way to get around this other than putting a small token download into source/fn ?

**Comment by msarahan** [comment]
Have you tried putting just the requirements section of meta.yaml in?  I think the source section and the requirements section should be independent.  If they're not, I think it's a bug.

**Comment by brentp** [comment]
I'm probably misusing conda. I'm trying to specify a dependency for the pre-link.sh script. It seems like a PATH is not set correctly. Here's a meta.yaml (where samtools is in bioconda channel):

```
# fake/meta.yaml
package:
  name: fake
  version: '123'

requirements:
  build:
  - samtools
  run:
  - samtools
```
and a pre-link.sh
```
samtools --help
```

when I run `conda build ./fake` there are no problems and it installs `samtools` and the dependencies into $CONDA_ROOT/envs/_build/bin/samtools
It builds the .bz2, when I run: 
```
conda install $CONDA_ROOT/conda-bld/linux-64/fake-123-0.tar.bz2
```

then it shows:
```
/pkgs/fake-123-0/bin/.fake-pre-link.sh: line 1: samtools: command not found
Error: pre-link failed: fake-123-0
```

**Comment by msarahan** [comment]
So, this is a silly issue with conda right now.  Pre-link and post-link scripts happen on a per-package basis, and depend on package installation order, which is currently alphabetical, not dependency-ordered.  Thus samtools has not yet been installed when fake's pre-link script runs.

This is obviously not sane.  Conda should install packages in dependency order.  We have that in master, but I'm not sure which release this will go into - maybe the pending 4.1 release.  https://github.com/conda/conda/blob/master/conda/plan.py#L443

**Comment by brentp** [comment]
ok. thanks. with conda@master, I get:
```
anaconda/lib/python2.7/site-packages/conda/install.py", line 717, in extract
    rec = package_cache()[dist]
KeyError: 'fake-123-0'
```

The actual key seems to be `<unknown>::fake-123-0`

**Comment by msarahan** [comment]
yeah, sorry, that's something different that I've seen, but don't understand.  @kalefranz @mcg1969 can you help @brentp know the best path forward here?

**Comment by brentp** [comment]
I think this might be related to: https://github.com/conda/conda/issues/2358 and https://github.com/conda/conda/pull/2369

**Comment by mcg1969** [comment]
Master is broken, I'm afraid. We're still working on this.

**Comment by mcg1969** [comment]
Actually, it looks like my fixes to master have been merged, which is good. But conda-build has some catching up to do. @mingwandroid has been working on some things. @kalefranz, I do think this is something that may need some attention before we release a new conda.

**Comment by mingwandroid** [comment]
@brentp you could *probably* work around this if you installed it with just `conda install fake`, which should give it a `local::` prefix instead of `<unknown>::` which I've not encountered yet.

If that doesn't work, you should be able to upload it to anaconda.org then install it from there, yes, somewhat round the houses.

**Comment by mcg1969** [comment]
Yeah I think we need a special `build` prefix to refer to packages in the build directory.

**Comment by brentp** [comment]
I am able to get conda master to work with these changes. Is there a better way to address this upstream?

```patch
$ git diff
diff --git a/conda/install.py b/conda/install.py
index 86a6c7b..98785d8 100644
--- a/conda/install.py
+++ b/conda/install.py
@@ -693,6 +693,9 @@ def is_extracted(dist):
     for fn in package_cache().get(dist, {}).get('dirs', ()):
         return fn
 
+    if not dist.startswith("<unknown>::"):
+        return is_extracted("<unknown>::" + dist)
+
 def rm_extracted(dist):
     """
     Removes any extracted versions of the given package found in the cache.
@@ -713,7 +716,11 @@ def extract(dist):
     Extract a package, i.e. make a package available for linkage. We assume
     that the compressed package is located in the packages directory.
     """
-    rec = package_cache()[dist]
+    try:
+        rec = package_cache()[dist]
+    except KeyError:
+        rec = package_cache()["<unknown>::" + dist]
+
     url = rec['urls'][0]
     fname = rec['files'][0]
     assert url and fname
```

I see lots of "unknown" packages in my package cache, e.g.
```
'<unknown>::conda-3.19.0-py27_0', '<unknown>::conda-env-2.4.5-py27_0', '<unknown>::fake-123-0', '<unknown>::openssl-1.0.2d-0', '<unknown>::pip-7.1.2-py27_0', '<unknown>::pycosat-0.6.1-py27_0', '<unknown>::pycrypto-2.6.1-py27_0', '<unknown>::python-2.7.11-0', '<unknown>::pyyaml-3.11-py27_1', '<unknown>::readline-6.2-2', '<unknown>::requests-2.9.0-py27_0', '<unknown>::setuptools-18.8.1-py27_0', '<unknown>::sqlite-3.8.4.1-1', '<unknown>::tk-8.5.18-0', '<unknown>::wheel-0.26.0-py27_1', '<unknown>::yaml-0.1.6-0'
```

**Comment by mcg1969** [comment]
It is certainly a decent stopgap but we need to figure out why some of the packages aren't getting a proper channel assignment (even `local::1st)

**Comment by brentp** [comment]
not sure if this helps, but those are likely the ones I installed with `python setup.py install` or `pip`.

**Comment by mcg1969** [comment]
OK, here's a "proper" fix. :-) Thanks for reporting this!
https://github.com/conda/conda/pull/2428

**Comment by brentp** [comment]
cheers.

**Comment by msarahan** [comment]
@brentp - is this fixed to your satisfaction?  If so, please close this issue - otherwise, what needs to be done?

**Comment by brentp** [comment]
actually, with the example above, I still get:

```
Traceback (most recent call last):
  File "/data/miniconda2/bin/conda", line 9, in <module>
    load_entry_point('conda==3.19.1.dev654+g91847aa', 'console_scripts', 'conda')()
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/install.py", line 193, in install
    misc.explicit(args.packages, prefix, verbose=not args.quiet)
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/misc.py", line 123, in explicit
    execute_actions(actions, index=index, verbose=verbose)
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/plan.py", line 554, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/instructions.py", line 47, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
KeyError: 'local::fake-123-0.tar.bz2'
```

the commands to reproduce are just:
```
conda build ./fake
conda install $(conda info --root)/conda-bld/linux-64/fake-123-0.tar.bz2
```

for me `state['index']` is empty at that point.

**Comment by msarahan** [comment]
@mcg1969 I don't know what to make of this issue.  Is it a conda issue?  Conda-build?  Both?  I'm asking because I want to do a conda-build release today or tomorrow, and I'm wondering if this issue should be fixed before that release.

**Comment by brentp** [comment]
here is a standalone bash script to recreate:

```
set -eo pipefail

rm -rf fake && mkdir -p fake
echo "
package:
  name: fake
  version: '123'

" > fake/meta.yaml

echo "ls -lh" > fake/pre-link.sh

conda build fake
conda install $(conda info --root)/conda-bld/*/fake-123-0.tar.bz2
```

**Comment by brentp** [comment]
any update on this? it breaks how I was testing things in my setup before uploading to anaconda.org

or if you have any pointers on where I should look, I can try to dig in.

**Comment by msarahan** [comment]
I'm adding your standalone example as a test, and will dig in from there.

**Comment by msarahan** [comment]
Great, I can't repeat your failure.  What versions of conda/conda build are you using?  Mine are:

```
Current conda install:

             platform : osx-64
        conda version : 4.0.6
  conda-build version : 1.20.3+0.gd33e1ac.dirty
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/msarahan/anaconda2  (writable)
  default environment : /Users/msarahan/anaconda2
     envs directories : /Users/msarahan/anaconda2/envs
        package cache : /Users/msarahan/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/msarahan/.condarc
    is foreign system : False
```

**Comment by brentp** [comment]
weird:
```
brentp@x1:~$ conda update conda
Fetching package metadata ...........
# All requested packages already installed.
# packages in environment at /data/miniconda2:
#
conda                     4.0.6                    py27_0  
```
then:
```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.19.1.dev713+6d15ac6
  conda-build version : 1.19.0+303.g16c5ba5
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /data/miniconda2  (writable)
  default environment : /data/miniconda2
     envs directories : /data/miniconda2/envs
        package cache : /data/miniconda2/pkgs
         channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/brentp/.condarc
    is foreign system : False
```

so force the update:

```
$ conda update -f conda
Fetching package metadata ...........
Solving package specifications .............
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/data/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/local/src/conda/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/usr/local/src/conda/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/usr/local/src/conda/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "/usr/local/src/conda/conda/cli/install.py", line 309, in install
    update_deps=args.update_deps)
  File "/usr/local/src/conda/conda/plan.py", line 450, in install_actions
    force=force, always_copy=always_copy)
  File "/usr/local/src/conda/conda/plan.py", line 309, in ensure_linked_actions
    elif install.try_hard_link(fetched_dir, prefix, dist):
  File "/usr/local/src/conda/conda/install.py", line 553, in try_hard_link
    assert isfile(src), src
AssertionError: /data/python-2.7.11-0/info/index.json
```

this is a fresh install of conda from: http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh

**Comment by msarahan** [comment]
You are picking up weird development versions somehow.  Your versions point at some development version of both conda and conda-build.  Do you have PYTHONPATH set?  Are there any other funky .pth files around?  What does ```which conda``` say?

**Comment by brentp** [comment]
hmm, my install seems fine.

when I install conda from git, it gets version == 3.19.1.dev769+74f8958

**Comment by brentp** [comment]
```
brentp@x1:/usr/local/src/conda$ git rev-parse HEAD
74f89589893556afb6f8707d71884019649c7a17
brentp@x1:/usr/local/src/conda$ python setup.py install | tail -1
warning: no files found matching 'versioneer.py'
Finished processing dependencies for conda==3.19.1.dev769+74f8958
```

**Comment by brentp** [comment]
that works. thanks.

**Comment by brentp** [comment]
I had to completely remove my conda install to get it to work...

**Comment by msarahan** [comment]
development installs can be evil sometimes.

sometimes

```python setup.py develop uninstall```

works.

Can I close this issue?

**Comment by brentp** [comment]
closing. thanks for the help.
