### ISSUE TITLE
Cygwin is inappropriately prepended to PATH; causes git crash

### ISSUE THREAD

**Issue by tritemio** [conda/conda-build#902]
Hi,

I'm trying to build conda packages for a pure python library ([phconvert](https://github.com/Photon-HDF5/phconvert/)) using appveyor. They already have multiple versions of miniconda installed so the setup for testing is really easy.

While trying to build a the recipe I get an error when conda-build is trying to call "git clone" on my repo:

```
Extracting packages ..Cloning into bare repository '/cygdrive/c/Miniconda-x64/conda-bld/git_cache/__github.com_Photon-HDF5_phconvert.git'...
C:/cygwin/usr/libexec/git-core/git-remote-https.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

....

Traceback (most recent call last):
  File "C:\Miniconda-x64\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda-x64\lib\site-packages\conda_build\main_build.py", line 208, in main
    args_func(args, p)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\main_build.py", line 493, in args_func
    args.func(args, p)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\main_build.py", line 438, in execute
    include_recipe=args.include_recipe)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 429, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Miniconda-x64\lib\site-packages\conda_build\source.py", line 291, in provide
    git_source(meta, recipe_dir)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\source.py", line 133, in git_source
    check_call(args + [git_url, cache_repo_arg],  cwd=recipe_dir)
  File "C:\Miniconda-x64\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\cygwin\\bin\\git.exe', 'clone', '--mirror', u'https://github.com/Photon-HDF5/phconvert.git', u'/cygdrive/c/Miniconda-x64/conda-bld/git_cache/__github.com_Photon-HDF5_phconvert.git']' returned non-zero exit status 3328
```
The full output is [here](https://ci.appveyor.com/project/tritemio/phconvert/build/1.0.40/job/bnupah7epdml059w#L487).

The PATH variable is printed [a few lines before](https://ci.appveyor.com/project/tritemio/phconvert/build/1.0.40/job/bnupah7epdml059w#L448). Also you can [see](https://ci.appveyor.com/project/tritemio/phconvert/build/1.0.40/job/bnupah7epdml059w#L453) that git is in the PATH at:

```
 where git
C:\Program Files\Git\cmd\git.exe 
```

but conda-build somehow tries to load a version from cygwin folder. Shouldn't conda build first try to use the git found in the PATH?

As a relate note, as suggested in appveyor docs, I activate the miniconda installation for current build with:

```
"set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
```

i.e. adding root and Scripts miniconda dirs to the PATH.  When I activate environments, I see that also the Library/bin folder is added to PATH. Should I also add Libray/bin when activating the root environment? In which order (relative to root and scripts folders)?

Thanks

**Comment by msarahan** [comment]
Relevant conda build code is https://github.com/conda/conda-build/blob/dd7e325f6882765b12c12f9b0bb1b1c294385084/conda_build/external.py#L14-L24

We do prepend the build environment folders, as well as C:\cygwin.  I don't like that cygwin prepend at all - I'm changing this issue to reflect the fact that this is almost certainly not something we should do.  If people need cygwin utilities, they can put them on PATH themselves.

**Comment by tritemio** [comment]
Thanks @msarahan for the quick fix! Is there a workaround I can use on appveyor in the meanwhile before the new conda-build version is released? Or is a release scheduled soon?

**Comment by msarahan** [comment]
You can force-hack the master of conda-build into appveyor.yml: https://github.com/conda-forge/icu-feedstock/commit/35e7f1676f5d1dccf9f182d4b4a754c339b1926b

That's pretty ugly, though.  @kalefranz what do you think about a bugfix release in the next day or two?  Between this issue and https://github.com/conda/conda-build/issues/895 I think we could use one.

**Comment by tritemio** [comment]
@msarahan, @kalefranz, is a conda-build release happening soon?
