### ISSUE TITLE
More pluggable/flexible conda skeleton (aka Refactoring to use #908)

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#914]
Given all the nice work in PR ( https://github.com/conda/conda-build/pull/908 ), it would be nice if we could restructure `conda skeleton` to use this. We could leverage a strategy like this [one](https://github.com/conda/conda-build/pull/908#issuecomment-216679510) to do the generation of the `meta.yaml`. It would require some new functions that encapsulate the remaining different pieces from the different provider. Would propose they be `use_pypi`, `use_cran`, `use_cpan`, and `use_luarocks`. These would be available to call in `meta.yaml`. This should keep the code base a little simpler and allow people to do some very interesting things with it.

**Comment by msarahan** [comment]
Sounds like a good idea to me.  Don't work on it utnil #908 is merged, though, just in case.

**Comment by jakirkham** [comment]
Sure, I wanted to see a bit more buy-in before going anywhere with it.

**Comment by jakirkham** [comment]
@mingwandroid and @ocefpaf, I'm bringing this one to both of your attentions as I saw there was some discussion about using `conda skeleton` with R packages and possibly updating it with a different template in the PR ( https://github.com/conda-forge/staged-recipes/pull/586 ) at [staged-recipes]( https://github.com/conda-forge/staged-recipes ).

I tried playing with some of @msarahan's work in PR ( https://github.com/conda/conda-build/pull/908 ), which has since been merged. Using it, I could autogenerate recipes from Python a totally generic jinja-based `meta.yaml` template as described in this [comment]( https://github.com/conda/conda-build/pull/908#issuecomment-216679510 ). We were discussing using this same functionality to transform recipe generation into an automated process by using re-rendering and a function like `use_setuptools` for other supported languages. This would be a good path for automating and standardizing recipe generation. It could be leveraged in the future to maintain recipes in an automated fashion.

Thoughts either of you have on this would be greatly appreciated.

**Comment by jakirkham** [comment]
Maybe of some interest to you as well, @pmlandwehr.

**Comment by pmlandwehr** [comment]
I'd particularly like it if `skeleton` could recursively check a list of channels (e.g. conda-forge and default) and could
* report which dependencies aren't present in those repositories
* recursively skeleton those dependencies as well

**Comment by msarahan** [comment]
I agree that this would be very useful, but IMHO that's a separate
capability, and should be a separate program, or at least a separate
function.  Separating loops from other logic has always helped my programs
stay cleaner.

**Comment by pmlandwehr** [comment]
That's fair - though I might beef a bit about point A. On a *different* note, I'd like it if `conda skeleton` and `conda build` followed an identical practice for labeling python versions. Right now `skeleton` uses decimals (`--python 2.7`) while `build` doesn't (`--python 27`).

**Comment by msarahan** [comment]
@pmlandwehr for the sake of tracking, please separate each complaint/request into another issue.  Tacking onto this issue makes things more likely to get accidentally overlooked.
