### ISSUE TITLE
"Error cound not match entry point: 'jupyter-kernelspec"

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#918]
Not really sure why I am seeing this issue, but I am seeing it reliably on Linux only. Here is the build [log]( https://circleci.com/gh/conda-forge/jupyter_client-feedstock/3 ). The error is at the end. Using conda to build this [recipe]( https://github.com/conda-forge/jupyter_client-feedstock/blob/a3924563452c19235f552404d84c5c1f2e33ab70/recipe/meta.yaml ). I have not confirmed that this is not a `jupyter_client` error at this point so that is not completely out. Mainly am looking for some more ideas on what could be going on here.

xref: https://github.com/jupyter/jupyter_client/issues/158

**Comment by takluyver** [comment]
That error appears to come from conda-build (the misspelling 'cound' makes it easy to find), and means it is failing to match this regex:

```python
entry_pat = re.compile('\s*([\w\-\.]+)\s*=\s*([\w.]+):([\w.]+)\s*$')
```

https://github.com/conda/conda-build/blob/dd7e325f6882765b12c12f9b0bb1b1c294385084/conda_build/scripts.py#L28

**Comment by jakirkham** [comment]
The fact that we only see in on our Linux build is very strange. Maybe it is an encoding error?

**Comment by takluyver** [comment]
Maybe, but it's all ascii characters, unless one of those sneaky unicode lookalikes has snuck in there somehow.

**Comment by takluyver** [comment]
Aha, I think it's because the build is running with an old version of conda-build, 1.18.2, which was released before conda/conda-build#690 landed. That PR is needed to recognise dots after the colon, which this uses.

So it should be just a matter of using a recent version of conda-build.

**Comment by jakirkham** [comment]
Yep, I think you are right. Thanks for the detective work @takluyver. Will try upgrading and report back.

**Comment by jakirkham** [comment]
So, we had been pinned to `conda-build` 1.18.2 for some time due to some faulty assertion `conda-build` when working with a build from a `git` source. This issue doesn't appear to be affecting us any more so we have unpinned it in `conda-smithy`. Shouldn't be an issue going forward. Thanks again for figuring this out @takluyver.
