### ISSUE TITLE
conda-build no longer prints upload instructions

### ISSUE THREAD

**Issue by stuarteberg** [conda/conda-build#936]
At the end of `conda build`, the user typically sees a helpful message explaining how to upload the package, like this:

```
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /miniconda/conda-bld/osx-64/my-package-1.0-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
```

It looks like that was accidentally removed via b83d9c87b895c7c83d881195e4eeb05f4ecb706f.

(At the moment, this affects the master branch, but not the release yet.)

Counter-intuitively, it looks like the old code expected `handle_binstar_upload()` to always get called, regardless of what the user passed in on the command-line. Now that it only gets called conditionally, the friendly message doesn't get printed.

Ping: @msarahan

**Comment by msarahan** [comment]
Thanks, I'll put that back in.  I didn't like that it was always true.  There must be a better way to express this logic.
