### ISSUE TITLE
Create a new info/about.json file

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#939]
This file will hold information we don't want to put in index.json.  It will basically be everything in the `about` field in `meta.yaml`.

```
'about': [
    'home', 'dev_url', 'doc_url', 'license_url',           # these are URLs
    'license', 'summary', 'description', 'license_family', # text
]
```

Anaconda-Platform/anaconda-server#2167

**Comment by ilanschnell** [comment]
I created https://github.com/conda/conda-build/pull/941 to add `info/about.json`.

**Comment by kalefranz** [comment]
Also we should consider adding the contents of the `info/files` file here.  Basically this is an "extra" file for anaconda.org to read to populate information about the package.  Here's an example where files are listed: https://pkgs.org/centos-5/centos-x86_64/zlib-1.2.3-7.el5.x86_64.rpm.html
