### ISSUE TITLE
__conda_???__.txt files for post-build assignment of metadata need deprecation

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#951]
I don't see a reason for these that Jinja templates do not fulfill in better ways.

If anyone can point out use cases for post-build version/build string, I'm happy to consider them.

Otherwise, I'm marking these as deprecated, and will remove them in 2.0.

**Comment by jakirkham** [comment]
Well, one use case is in development builds. Take a look at how NumPy does versioning for instance. This is extremely complex. Basically, you would have to reimplement it with Jinja and I'm not sure it would be as nice or be possible. Not to mention, one would now be maintaining duplicated code. However, it is very easy to spit out version info. Take a look at this PR ( https://github.com/numpy/numpy/pull/7036 ) over at NumPy for some more context.

**Comment by jakirkham** [comment]
If you're point is this can't be captured by rendering, I completely agree. Maybe one could be allowed to run a command or small script to get the version info independent of the build. This way one could have the best of both worlds. Complex versioning schemes can be captured without duplicated effort and it would not have to happen in the build step.

**Comment by msarahan** [comment]
Yeah - if you can't reason about what the build string will be before you actually build the source, then that breaks a lot of tools.  Your ideas are good ones.

Numpy is confusing to me though.  The version is in setup.py, but is it not also in the git tags?  If it's in the git tags, then just use Jinja?

I just don't understand any use case where the version would somehow be determined *during* a build - so why is a post-build step to process metadata necessary?

**Comment by jakirkham** [comment]
> Numpy is confusing to me though. The version is in setup.py, but is it not also in the git tags? If it's in the git tags, then just use Jinja?

I tried that. I had edited the comment above so you may have missed this part, but the first outdated diff was just this attempt. It unfortunately is not so simple as they branch out for a release and may not tag it for sometime. So, `git` can't look in the history and find those tags and whatever tags it does find are almost certainly wrong. Hence why they have such complicated logic to figure this out. 😄

> I just don't understand any use case where the version would somehow be determined during a build - so why is a post-build step to process metadata necessary?

Again. If we separate out the version determination to work with the source independent of the build, I think we are fine. Is this question whether we can do this in all cases? I would certainly hope the answer is yes and don't have any reason at this time to believe otherwise.

**Comment by msarahan** [comment]
OK, fair enough.  I did find that outdated diff, but I guess I didn't fully grok it.  I think jinja might be able to import setup.py and get the version - but that doesn't really matter.  Separating out the version determination to be independent of the build is the ultimate solution.

**Comment by jakirkham** [comment]
Yeah, if you know some jinja magic that would make that work, I would definitely be curious to hear.

I agree that these files are a hindrance. Mainly just wanting to make sure we provide a path for those in more complex situations to follow.

**Comment by kalefranz** [comment]
I can definitely see people not knowing this information until after the package is built. For example maybe you have an automated build system that can perfectly rebuild packages, to the point where hashes are similar, and if you get a new hash that's different than the previous, you bump the build number. You can definitely only do that after most of the package is built.

**Comment by msarahan** [comment]
@kalefranz I don't see this example - could you point to a concrete example of this?

Here is how I interpreted your example:

If you have an automated build system that can perfectly rebuild packages, then the only thing that changes the output is input (source) - at which point, a post-build build number is far less informative than a revision control system.

**Comment by jakirkham** [comment]
Added the aforementioned point of having a command get version info to this issue ( https://github.com/conda/conda-build/issues/1110 ).
