### ISSUE TITLE
Regression regarding `[]` in jinja

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#955]
Running into a regression when using the `[]` operator in jinja. This functionality was added by @stuarteberg in this PR ( https://github.com/conda/conda-build/pull/771 ). However, this appears to now be broken in `conda-build` 1.20.2. The current workaround would be to downgrade to `conda-build` 1.20.1, which does not have this problem. Here are some examples.

```
Error: Invalid selector in meta.yaml line 40:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
```

See this [comment]( https://github.com/conda-forge/hdf5-feedstock/pull/13#issuecomment-219302083 ) and PR for more details.

```
Error: Invalid selector in meta.yaml line 12:
  fn:  graphviz-{{ version[:-2] }}.zip  # [win]
```

Also see this [comment]( https://github.com/conda-forge/staged-recipes/pull/568#issuecomment-219250321 ) for context.

cc @ccordoba12 @msarahan

**Comment by stuarteberg** [comment]
See PR #957 for the fix.

**Comment by stuarteberg** [comment]
BTW, @jakirkham, the PR you mentioned (#771) does not related to bracket syntax `[]` or selectors.  Are you sure that's the commit that caused this "regression"?  As far as I can tell, the problem you're seeing should have been an issue in previous versions, too.  How did selectors ever work on lines with other `[]` characters in them?

Anyway, I'm pretty sure #957 fixes the issue, so maybe it's not important.

**Comment by msarahan** [comment]
I agree that this is a regression in behavior, though I am also confused as to how it ever worked.  I think I brought this issue out by changing the order of operations for the sake of separating rendering.  Thanks @stuarteberg for the fix.  I'm traveling today, but will merge it when I arrive.  Please see my small comment about adding one more test in test_metadata.py for this.

**Comment by jakirkham** [comment]
> Are you sure that's the commit that caused this "regression"?

Sounds like some wires got crossed here. I was not saying that you caused the regression.

In fact, I was saying that I believe you added the functionality that was recently broken. The problem did not exist in 1.20.1, but appeared in 1.20.2. So, no, I don't think you had anything to do with it. Yes, it is a regression. I don't have any idea why it happened. I merely thought you would be concerned by this break.

> BTW, @jakirkham, the PR you mentioned (#771) does not related to bracket syntax [] or selectors.

Really? The PR specifically mentions fixing this case.

> We also avoid choking even if the undefined variable is used in an expression involving various operators:

> ```yaml
build:
  string: {{ GIT_FULL_HASH[:7] + "_hello" }}
```

I guess it didn't have a selector if that is your point. However, my understanding was selectors were processed first at which point it would resolve down to this anyways. Though I don't muck with this code as much as you do; so, I could be totally misunderstanding how these steps are performed.

**Comment by stuarteberg** [comment]
>I was not saying that you caused the regression.

I wasn't worried about that, but thanks. :smile:  I didn't mean to sound defensive.

I was worried that I might have misunderstood the problem, and that therefore I had "fixed" the wrong thing.  If you know for certain that #771 really caused this particular regression, then I'm totally stumped.  But it sounds like that's not the case, so we're probably in good shape.

>The PR specifically mentions fixing this case.

Alas, sorry if that PR was poorly worded.  In that PR, I was attempting to say "Right now we already support cases X and Y, but we forgot Z. This PR fixes Z".  You probably know me well enough to know that succinct explanations are not my strong suit. :-P

**Comment by jakirkham** [comment]
> I wasn't worried about that, but thanks. :smile: I didn't mean to sound defensive.

> I was worried that I might have misunderstood the problem, and that therefore I had "fixed" the wrong thing. If you know for certain that #771 really caused this particular regression, then I'm totally stumped. But it sounds like that's not the case, so we're probably in good shape.

Yes, we are in good shape I think. Sorry for the confusion.

> Alas, sorry if that PR was poorly worded. In that PR, I was attempting to say "Right now we already support cases X and Y, but we forgot Z. This PR fixes Z". You probably know me well enough to know that succinct explanations are not my strong suit. :-P

...appears I was confused too.

![enhanced-buzz-22200-1286995714-22](https://cloud.githubusercontent.com/assets/3019665/15304563/09c01fbe-1b8c-11e6-9d1c-eb7a04209949.png)

**Comment by jakirkham** [comment]
So, I tested this in a known problem case ( https://github.com/conda-forge/jpeg-feedstock/pull/3 ) and it works great everywhere I tried. Thanks for fixing this.
