### ISSUE TITLE
Feature request: custom actions for conda-build

### ISSUE THREAD

**Issue by tadeu** [conda/conda-build#971]
The idea is to add some hooks where it is possible to run custom scripts between conda build steps. This would be specially useful for doing extra checks that are "site-specific", e.g., checking that the runtime libraries being used by the output library is correct, or checking that the recipe is following best practices.

It could work like this:

```
export CONDA_BUILD_PRE_BUILD=/usr/local/conda-recipes/pre-build-check.sh
export CONDA_BUILD_POST_BUILD=...
export CONDA_BUILD_PRE_TEST=...

conda build ...
```

(or equivalently, in Windows, using `set` and `.bat`)

And `conda build` would call the scripts at the right time (if the env var is defined), and possibly verify the returned error code.

We are willing to work on a pull request. What do you think?

**Comment by msarahan** [comment]
Interesting idea.  It could go a lot of different directions.  Do you see these being site-specific global files, or per-recipe things?  How familiar are you with conda's tools along these lines ( http://conda.pydata.org/docs/using/envs.html#saved-environment-variables and http://conda.pydata.org/docs/building/build-scripts.html )?  How would your idea be similar or different?

**Comment by tadeu** [comment]
I see it as being site-specific global files, since "per-recipe" things could already be added to the recipes themselves.  It would be mostly to avoid duplicating checks in recipes.

I use ["Pre/Post link/unlink scripts"](http://conda.pydata.org/docs/building/build-scripts.html#pre-post-link-unlink-scripts) from `conda` sometimes, it is awesome in how it's simple and powerful. The idea is for something similar, but to be done at `build` or `test` time (instead of `link` or `activate`), and globally configured via environment variables.

**Comment by msarahan** [comment]
Cool.  I'm curious to see how you will generalize it, but it could definitely be a very useful tool.  Please include a simple example as part of this PR - ideally in the code somewhere, but in comments here would be OK too.

**Comment by tadeu** [comment]
cc @nicoddemus @edisongustavo

**Comment by tadeu** [comment]
A very simple example:

This goes in our CI job that builds packages:
```
export CONDA_BUILD_PRE_BUILD=~/conda-recipes/pre-build-check.sh
cd ~/conda-recipes
conda build $PACKAGE
```

This could be `pre-build-check.sh`:
```
#!/bin/bash

python $RECIPE_DIR/../lint_recipe.py $RECIPE_DIR
```

And it would verify a lot of things in the recipe (such as is done by conda-forge's [lint_recipe.py](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py)]), exiting with 1 if there are errors.

**Comment by tadeu** [comment]
Another example: use a `pre-test-check.bat` in Windows to verify that the `.dll`'s are using the correct runtime via dependency walker (this is extremely site-specific, since it would need to depend on `dependency walker`)

**Comment by msarahan** [comment]
I think both of these are examples of things that should come standard with conda-build.  We might not be able to redistribute dependency walker right away. Linting and other sanity checks are certainly important enough to be core functionality, while also maintaining extensibility by site-specific desires.

**Comment by tadeu** [comment]
Cool, I agree that they should come standard, but while they are not, this would come useful even if done on user side. Anyway, we would still need site-specific extensibility, since we do some weird things like using Python 2.7 with MSVC 2010. ;)

**Comment by msarahan** [comment]
Cool - please build that functionality into your PR, if you can.  Something like the activate.d/deactivate.d directories for conda?

**Comment by tadeu** [comment]
By "something like the activate.d/deactivate.d directories for conda", you mean to point into a directory full of scripts, instead of a single script?  Where do you think this should be configured?  Are environment variables ok, or perhaps should they go in `.condarc` or somewhere else?

**Comment by msarahan** [comment]
yes, a directory.  I think that's the best way to get extensibility.

I would like default directories in the root prefix's folder structure, with either .condarc or environment variable overrides.  I'm not picky, but perhaps .condarc is better in keeping with established pattern.

**Comment by gqmelo** [comment]
I like the idea of having a single directory with all scripts. And I think it is more consistent with the way how recipes works, where conda-build automatically finds/executes/includes run_test.py, post-link.sh, etc.

And +1 for being able to configure through .condarc and env var.
