### ISSUE TITLE
conda skeleton should follow best practises

### ISSUE THREAD

**Issue by jankatins** [conda/conda-build#972]
I used conda skeleton to build a few recipes intended to be deployed on conda forge and had to change a few things:
- The file should be on `https://pypi.io/packages/source/<letter>/<packagename>/<file>`
- the version number should only be specified once in a `{% set version = "1.2.1" %}` clause and the be reused
- Same licenses were "incomplete": `Python` -> `PSF`; `BSD license` -> `BSD 3 clause`
- there should be a `build:\n  number: 0` clause
- for simple scripts the build should just include the python call under build: `build:\n script: python setup.py install --single-version-externally-managed --record record.txt`

**Comment by msarahan** [comment]
This is a pretty easy rework of https://github.com/conda/conda-build/blob/master/conda_build/pypi.py#L43-L126 - maybe a good project for sprints at SciPy.
