### ISSUE TITLE
conda build fails when copying relative path source

### ISSUE THREAD

**Issue by oyse** [conda/conda-build#982]
When doing conda build where the source is set to a relative path the build fails on 1.20.3. It works on 1.20.1.

Conda recipe that is being used is

package:
  name: a-name
  version: 1.0
requirements:
  build:
    - python
  run:
    - python

source:
  path: ../

The error message is:

Traceback (most recent call last):
  File "D:\Anaconda3\64\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Anaconda3\64\lib\site-packages\conda_build\main_build.py", line 134, in main
    args_func(args, p)
  File "D:\Anaconda3\64\lib\site-packages\conda_build\main_build.py", line 373, in args_func
    args.func(args, p)
  File "D:\Anaconda3\64\lib\site-packages\conda_build\main_build.py", line 320, in execute
    need_source_download=need_source_download)
  File "D:\Anaconda3\64\lib\site-packages\conda_build\build.py", line 448, in build
    verbose=verbose)
  File "D:\Anaconda3\64\lib\site-packages\conda_build\render.py", line 84, in parse_or_try_download
    source.provide(metadata.path, metadata.get_section('source'), verbose=verbose)
  File "D:\Anaconda3\64\lib\site-packages\conda_build\source.py", line 373, in provide
    copytree(abspath(join(recipe_dir, meta.get('path'))), WORK_DIR)
  File "D:\Anaconda3\64\lib\shutil.py", line 303, in copytree
    os.makedirs(dst)
  File "D:\Anaconda3\64\lib\os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\BuildAgent\work\3e38ea7f40c34e7b\Libraries\ScriptApi\conda-build-dir\work'

**Comment by msarahan** [comment]
Thanks for the report.  What arguments, if any, are you passing to ```conda build```, other than the recipe location?

The problem indicates either that the old work folder is not being removed prior to downloading new source, or that there's a bug in the recent separation of rendering and building a recipe where the source is being downloaded twice.

The former would potentially be a Windows timing bug, or perhaps silent failure to completely remove the folder.  It looks like you're on some kind of build server.  Can you manually delete the work folder and try again?

Also, I'm confused why conda build is trying to create a folder in ```'D:\BuildAgent\work\3e38ea7f40c34e7b\Libraries\ScriptApi\conda-build-dir\work'``` - it should be something more like ```<Miniconda install dir>\conda-bld\work``` - are you customizing this build location somehow?  Maybe what's missing is some recognition of that customization?

**Comment by oyse** [comment]
I tried to delete the work folder manually and the problem is still the same unfortunately.

I set the build folder using the CONDA_BLD_PATH environment variable.

The command is "<full path>\conda.exe <path to build agent dir>\conda-recipe"

The conda-recipe dir is a sub-dir of the module being built.

I must admit I can't really remember why I am not building to the standard directory. Maybe something about access rights or wanting to keep everything related to the build in same place.

**Comment by msarahan** [comment]
Just to save me some head scratching, can you not set the CONDA_BLD_PATH, and see if the behavior persists?  I'm leaning towards a bug in that area, but the code there is pretty simple.

**Comment by oyse** [comment]
Looks like removing the CONDA_BLD_PATH did the trick.

**Comment by ikalev** [comment]
I am experiencing the same issue. My setup looks like this:

```shell
$ set CONDA_BLD_PATH=build
$ conda build build\.recipe
```
Confirming that this problem was introduced in version ``conda-build=1.20.2``.

**Comment by msarahan** [comment]
Thanks both of you.  I'll look into this and get a bugfix release out soon.
