### ISSUE TITLE
Make it easier to write wrapper scripts that set environment variables

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#99]
A lot of times, the only way to make a package relocatable is to set some environment variable when it runs. It would be useful if conda made it easier to write little wrapper scripts, like

``` sh
#!/bin/sh
export ENVVAR=/opt/anaconda1anaconda2anaconda3/whatever
/opt/anaconda1anaconda2anaconda3/bin/.realexecutable "$@"
```

which are automatically added to `has_prefix_files`.

**Comment by bkreider** [comment]
Is this solved by the activate environment variables in conda-env?

**Comment by asmeurer** [comment]
Man I really hate that feature. You shouldn't have to activate an environment to use it. The feature suggested here doesn't require that. Neither does binary prefix replacement, which requires adding *one* line (`detect_binary_files_with_prefix: true`) to your meta.yaml.

**Comment by bkreider** [comment]
> You shouldn't have to activate an environment to use it. 

Agreed.  I've written those shims.  I didn't think there was going to be a way of doing this beyond the activate envs.  I spent a lot of time almost getting golang to work, but it really wants to compile in some paths.  Maybe I should try again with the new conda-build relocation features.   When i had done it i made a very long path to get relocation to work -- some of the time.
