### ISSUE TITLE
cannot find conda skeleton pypi output?

### ISSUE THREAD

**Issue by Data-drone** [conda/conda-build#992]
I ran `conda skeleton pypi sandman2 --version 0.0.7` which build successfully but then when I tried to run:

`conda install --use-local sandman2` I got back `Error: Package missing in current win-64 channels`

Note I ran conda skeleton in the root environment and tried to install in a different environment is this an issue?

**Comment by msarahan** [comment]
conda skeleton does not build the package itself, it only creates the recipe.  Are you building the recipe afterwards?

If you are building the recipe, then this is a problem with conda more than conda-build.  Please let me know, so I can direct this issue accordingly.

**Comment by Data-drone** [comment]
How do I build the recipe?

**Comment by msarahan** [comment]
conda build <path to your recipe>
