### ISSUE TITLE
conda-build 1.20.3 and Python 3.4 32-bit fail to build pyyaml on Windows/AppVeyor

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#993]
When using `conda-build` 1.20.3 and Python 3.4 32-bit on AppVeyor, building `pyyaml` fails to properly include `yaml.h` even though the correct path is provided. Switching to `conda-build` 1.20.0 fixes the issue (though there may be versions in-between that also work). See this [log]( https://ci.appveyor.com/project/conda-forge/pyyaml-feedstock/build/1.0.1/job/dfj15b71in9qi2ch ) for an example of the failure.

cc @msarahan

**Comment by msarahan** [comment]
Noted.  Will fix this ASAP.

**Comment by jakirkham** [comment]
Turns out this was a PEBCAK bug. It has been corrected.
